### ISSUE TITLE
http client with proxy and json credentials both setting failed

### ISSUE THREAD

**Issue by chestarss** [googleapis/google-cloud-go#10014]
same issue https://stackoverflow.com/questions/65296130/http-client-with-proxy-and-json-credentials

**Client**

e.g. PubSub

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

$ go version
go version go1.20 linux/amd64
$ go env

**Code**

e.g.
```go
ctx := context.Background()
opts := make([]option.ClientOption, 0)
opt := option.WithCredentialsJSON([]byte(cloudAccount.GcpJson))
...
proxyOpt := option.WithHTTPClient(httpClient)
opts = append(opts, proxyOpt)
client, err := redis.NewService(ctx, cs.Options...)

```

**Expected behavior**

e.g. Messages arrive really fast.

**Actual behavior**

e.g. Messages arrive really slowly.

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

e.g. Started after upgrading to v0.50.0.

**Comment by codyoss** [comment]
This is by design. Please see my comment here for how to work around this: https://github.com/googleapis/google-api-go-client/issues/2497#issuecomment-2027537404
