### ISSUE TITLE
storage: delete folder without iterator

### ISSUE THREAD

**Issue by Auxority** [googleapis/google-cloud-go#10025]
**Is your feature request related to a problem? Please describe.**
Currently I am using a "transformations" bucket that contains modified versions of an original image stored in an "uploads" bucket. I store these transformed images in folders like so: `/{originalSHA256Hash}/{nameOfTransformations}.{extension}`. But if a user wants to delete their original upload, I now have to query the bucket with a prefix and delete each object individually.

**Describe the solution you'd like**
I'd like to be able to delete an entire folder with one request. A possible implementation could be something like this:

```go
// bucket.go
func (b *Bucket) Folder(name string) *Folder {
    // add implementation here, no network requests yet.
}

// folder.go
func (f *Folder) Delete() error {
    // add implementation here, execute API request.
}

// usage:
client, err := storage.NewClient(ctx)
if err != nil {
	log.Fatalf("error creating cloud storage client: %w", err)
}

bucket := client.Bucket("NameOfBucket")

// new code:
folder := bucket.Folder("NameOfFolder")

err := folder.Delete()
if err != nil {
    log.Errorf("could not delete folder: %w", err)
}
```

**Describe alternatives you've considered**
1. Delete all objects inside a folder using goroutines. This introduces a bunch of network traffic that could be prevented.

2. Using lifecycle object management rules with a prefix to achieve this. Does the job, but your service needs to have permission to create these rules and might not delete the folder immediately.

3. You can just call the existing endpoint of the Google API via any HTTP Client to achieve the desired end result.

**Additional context**
The Google API already supports this feature through the web interface.

<img width="1201" alt="Screenshot 2024-04-23 at 09 47 23" src="https://github.com/googleapis/google-cloud-go/assets/35202343/b398dfa0-02b6-46c2-b02c-aab550cd0ee7">

**Comment by tritone** [comment]
Closing this out due to lack of response; feel free to re-open or file a new issue if you have further questions.
