### ISSUE TITLE
[Feature request] Cloud DNS package

### ISSUE THREAD

**Issue by QuynhVir** [googleapis/google-cloud-go#10035]
This library supports everything I need, except Cloud DNS. 
I see there is a library out there that supports Cloud DNS: google.golang.org/api/dns/v1
But right on that repository, they also recommend using the newer Cloud Client Libraries for Go, which is why I am here.
I would love to have all in this library and not need to install both for full functionality.

**Comment by codyoss** [comment]
Most of the libraries in this repository are generated from proto specs and DNS does not currently publish this spec for us to generate a library from. I don't think we will be generating this client is this repository any time soon for that reason. I would recommend to keep using google.golang.org/api/dns/v1 for the foreseeable future. I will try to update this issue if that changes in the future.
