### ISSUE TITLE
bigquery: add function to list all projects

### ISSUE THREAD

**Issue by cocoa-xu** [googleapis/google-cloud-go#10044]
**Is your feature request related to a problem? Please describe.**
To the best of my knowledge, current BigQuery API implemented in Go does not support list all projects.

**Describe the solution you'd like**

BigQuery should have a way to list/enumerate all projects that the current user has access to. This API could be like

```go
client, err := bigquery.NewClient(ctx, projectID, credentials)
if err != nil {
	return err
}

// this should return an enumerator for all projects
// that the current user has access to
projects, err := client.Projects()
if err != nil {
	return err
}
```

**Describe alternatives you've considered**

An alternative solution could be support this feature using SQL queries (although I do understand that's not in the scope of this repository).

**Additional context**
<img width="591" alt="Screenshot 2024-04-25 at 05 45 55" src="https://github.com/googleapis/google-cloud-go/assets/89497197/50d83dc3-8684-4549-a465-b4c1fe7e9199">

**Comment by shollyman** [comment]
Projects are a more general GCP resource, and programmatic access to project information is best done via the [resource manager](https://cloud.google.com/resource-manager/docs) service.  There are some BigQuery INFORMATION_SCHEMA views that expose organization-level information, but there's not one that aligns well for the general task of listing projects.

BigQuery has an [older API](https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list) for project enumeration, but doesn't encourage it's use.  As such, we don't include it in handwritten client libraries such as this one.

**Comment by shollyman** [comment]
For Go, your easiest path forward looks to be:
https://pkg.go.dev/cloud.google.com/go/resourcemanager/apiv3

**Comment by shollyman** [comment]
I'm going to close this issue out at this time, but if there's followup feedback we can reopen as needed.  Thanks for reaching out.

**Comment by feng-andrew-ge** [comment]
@shollyman Is there a way to filter out bigquery projects by using the [resource manager API ](https://cloud.google.com/resource-manager/reference/rest/v3/projects/search)?  It returns all the projects, not just bigquery ones. 
I tried "labels.kind:bigquery" and "labels.kind:bigquery#project" , both returned empty.
