### ISSUE TITLE
compute: client authentication fails

### ISSUE THREAD

**Issue by shaxiaozz** [googleapis/google-cloud-go#10041]
**Client**

cloud.google.com/go/compute/apiv1
cloud.google.com/go/compute/apiv1/computepb

**Go Environment**
$ go version
go version go1.21.4 windows/amd64

$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\myg\AppData\Local\go-build
set GOENV=C:\Users\my\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\my\Desktop\golang\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\my\Desktop\golang
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\my\AppData\Local\Temp\go-build2404005934=/tmp/go-build -gno-record-gcc-switches

**Code**
```go
package main

package main

import (
	compute "cloud.google.com/go/compute/apiv1"
	"cloud.google.com/go/compute/apiv1/computepb"
	"context"
	"fmt"
	"github.com/wonderivan/logger"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"log"
	"net/http"
	"net/url"
	"os"
)

func main() {
	logger.Info("start")

	// proxy
	proxyURL, err := url.Parse("http://192.168.56.1:7890")
	if err != nil {
		log.Fatalf("Failed to parse proxy URL: %v", err)
	}
	httpClient := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(proxyURL),
		},
	}

	ctx := context.Background()
	scopes := compute.DefaultAuthScopes()
	instancesClient, err := compute.NewInstancesRESTClient(ctx, option.WithCredentialsFile("E:\\key.json"), option.WithHTTPClient(httpClient), option.WithScopes(scopes...))
	if err != nil {
		fmt.Errorf("NewInstancesRESTClient: %w", err)
	}
	defer instancesClient.Close()

	req := &computepb.ListInstancesRequest{
		Project: "my_project_id",
		Zone:    "australia-southeast2-a",
	}

	it := instancesClient.List(ctx, req)
	for {
		instance, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			logger.Error(err)
                        return
		}
		logger.Info(instance.GetName(), instance.GetMachineType())
	}
}
```

**Expected behavior**

Executing go run main.go should output a list of virtual machines in the "australia-southeast2-a" area under my project.

**Actual behavior**
An error occurred：googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or o
ther valid authentication credential

**Screenshots**

![image](https://github.com/googleapis/google-cloud-go/assets/43721571/98993d74-d33f-46fc-a55d-59c6ddc767c3)

**Local Development Environment**
My development environment is based on windows 10+GoLand 2023.2.5

**Service Account**
I can be sure that the json key file status of my services account is activated.
![image](https://github.com/googleapis/google-cloud-go/assets/43721571/bbf7ce26-032c-4c49-b92c-ff5287fb4e24)

**IAM permissions**
![image](https://github.com/googleapis/google-cloud-go/assets/43721571/1bf70325-ca91-445e-b745-0710de689094)

**Additional context**
Now I cannot authenticate the Google API through the option.WithCredentialsFile method. I hope to use this authentication method to complete the addition, deletion, modification and check of the virtual machine.

I don't know which step I did wrong. At the same time, I also checked the documentation of Compute Engine API, which all describe how to set up authentication under gcloud CLI. I don't want it to go this way. I want to complete the authentication through the service account

Hope to get your reply

**Comment by shaxiaozz** [comment]
Supplement: The reason why I added "scopes := compute.DefaultAuthScopes()" to the code is because I saw this issue is similar https://github.com/googleapis/google-cloud-go/issues/4494

```go
	ctx := context.Background()
	scopes := compute.DefaultAuthScopes()
	instancesClient, err := compute.NewInstancesRESTClient(ctx, option.WithCredentialsFile("E:\\v1-project-418113-9e698f98aef5.json"), option.WithHTTPClient(httpClient), option.WithScopes(scopes...))
	if err != nil {
		fmt.Errorf("NewInstancesRESTClient: %w", err)
	}
```

But I deleted "scopes := compute.DefaultAuthScopes()" and got the same error.

**Comment by codyoss** [comment]
The issue here is if you specify an HTTP client that takes precedence over the provided credential. If you don't need to override some setting I suggest not setting that option. If you do need to customize the client I suggest building the transport layer with this code that will add in auth to the transport layer of the client: https://pkg.go.dev/google.golang.org/api/transport/http#NewTransport

Hope that helps

**Comment by shaxiaozz** [comment]
@codyoss Thanks for your reply, glad I have resolved the issue.

I can achieve proxy access by setting the HTTP_PROXY and HTTPS_PROXY system environment variables instead of stupidly modifying the default httpClient in the golang code.
