### ISSUE TITLE
storage: support custom query strings and headers

### ISSUE THREAD

**Issue by wiley-target** [googleapis/google-cloud-go#10089]
**Is your feature request related to a problem? Please describe.**
No, but the lack of support for custom query strings and HTTP headers in the Golang GCS SDK is limiting our ability to interact with GCS in certain scenarios. Specifically, we need the ability to send custom query strings and HTTP headers similar to what is possible with the XML API. Additionally, there's a gap in functionality related to multipart uploads and listing objects that we'd like to address.

**Describe the solution you'd like**
We would like to see the Golang GCS SDK updated to support custom query strings and HTTP headers, allowing for greater flexibility in interacting with GCS. This would ensure that we can achieve parity with the functionality available through the XML API. Specifically, for multipart uploads, we need support for creating, uploading (with upload ID and part number), and completing multipart uploads in a manner similar to what is available with the XML API. Additionally, for listing objects, we require support for custom query strings such as continuation-token, delimiter, encoding-type, fetch-owner, generation-marker, list-type, marker, max-keys, prefix, start-after, and versions for objects listing using the v2 API.

**Describe alternatives you've considered**
As alternatives, we have explored workarounds such as using the XML API directly or implementing our own custom HTTP client with the necessary functionality. However, these approaches are less than ideal as they introduce complexity and may not integrate seamlessly with the rest of our codebase.

**Additional context**

**Comment by tritone** [comment]
We currently do support sending custom headers via the Go client. See https://pkg.go.dev/cloud.google.com/go/storage#hdr-Sending_Custom_Headers

Most query params for object listing are also supported; see https://pkg.go.dev/cloud.google.com/go/storage#Query

Can you take a look at these and then let us know what specific gaps you see for your use case?

**Comment by wiley-target** [comment]
Thank you, @tritone. I'm eager to ensure that the Golang SDK can manage all XML API requests, but I'm struggling to find comprehensive documentation on this. Specifically, I can't locate details on how to initiate and complete multipart uploads. Additionally, I'm uncertain if multipart uploads with part numbers and upload IDs are supported. Could you please guide me in the right direction?

**Comment by tritone** [comment]
We mainly use the JSON & gRPC APIs for Cloud Storage in this library, but this should cover almost all core GCS functionality. If there is any specific functionality that you see missing please file a feature request.

One gap is that we don't support multipart uploads currently; if you need these specifically, you can use the s3 Go client and change the endpoint to hit GCS. See https://cloud.google.com/storage/docs/aws-simple-migration .

There is an open FR to support parallel uploads in this library here: #3219. We are planning on getting to this later in the year; you can follow the issue for updates.

I'm going to close this issue; feel free to file another one or comment on the parallel uploads issue if you have other concerns.
