### ISSUE TITLE
monitoring: TimeSeriesData_PointData behavior vs documentation

### ISSUE THREAD

**Issue by ilevinpanw** [googleapis/google-cloud-go#10115]
**Client**

Monitoring/MonitoringPB

**Environment**

N/A

**Go Environment**

go version go1.21.8 darwin/arm64

**Code**

Code taken directly from **metric.pb.go**:

```go
// A point's value columns and time interval. Each point has one or more
// point values corresponding to the entries in `point_descriptors` field in
// the TimeSeriesDescriptor associated with this object.
type TimeSeriesData_PointData struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields
  
  // The values that make up the point.
  Values []*TypedValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
  // The time interval associated with the point.
  TimeInterval *TimeInterval `protobuf:"bytes,2,opt,name=time_interval,json=timeInterval,proto3" json:"time_interval,omitempty"`
}
```

Sample code:

```go
func materializeTimeSeriesData[T number](iter *monitoring.TimeSeriesDataIterator) ([]T, error) {
    res := make([]T, 0)
    
    resp, err := iter.Next()
    if errors.Is(err, iterator.Done) {
      return []T{}, nil
    }
    
    if err != nil {
      return nil, err
    }
    
    for _, p := range resp.GetPointData() {
      values := p.GetValues()
      pointData := values[0].GetValue()
      ...
    }
}
```

**Expected behavior**

 It is expected according to the documentation that `Values` will always have a length of 1 and above.

**Actual behavior**

Due to some temporary issue with the GCP Metrics service, length of `Values` was zero. It also has the `omitempty` tag which is confusing.

I'd appreciate a clarification of what the intended behavior is. Thanks.

**Comment by codyoss** [comment]
This sounds like a temporary error that is no longer happening. For service specific questions I recommend reaching out to service specific issue trackers. https://cloud.google.com/stackdriver/docs/getting-support
