### ISSUE TITLE
Full Compute Client as Storage or BigQuery

### ISSUE THREAD

**Issue by alan-ma-umg** [googleapis/google-cloud-go#1019]
## Client

Compute

## Describe Your Environment

GAE Flex

## Expected Behavior

Full feature client with functions matching https://cloud.google.com/compute/docs/reference/rest/v1/

**Comment by pongad** [comment]
I'll assign myself to this.

Caveat: With what I'm working on, the compute client will probably be "code-generatey" and not quite as high-quality as Storage and BigQuery.

**Comment by alanma** [comment]
Thanks @jba and @pongad for the quick confirmation.

**Comment by jadekler** [comment]
We've investigated this and it looks like it's going to be a significant project to migrate the compute API. Unfortunately I've got no details on the timeline of this - it's entirely dependent on the backend team. I'm going to close this issue: we will announce this as we do with our new clients through our CHANGES.md and by adding to our README.md.
