### ISSUE TITLE
spanner: Cannot insert specific float values into JSON column 

### ISSUE THREAD

**Issue by h6ah4i** [googleapis/google-cloud-go#10283]
**Client**

- cloud.google.com/go/spanner v1.63.0

**Environment**

- MacOS 14.4.1 (23E224)

**Go Environment**

```
$ go version
go version go1.21.4 darwin/amd64

$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/***/Library/Caches/go-build'
GOENV='/Users/***/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/***/go/1.21.3/pkg/mod'
GONOPROXY='***'
GONOSUMDB='***'
GOOS='darwin'
GOPATH='/Users/***/go/1.21.3'
GOPRIVATE='***'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/***/go/1.21.3/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.4.darwin-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/***/go/1.21.3/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.4.darwin-amd64/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/***/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/7g/5yfd82ss2mjcg794bzgnj6000000gn/T/go-build3418130814=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Code**

When I try to insert a record with the following NullJSON value, Cloud Spanner returns an error.

```go
spanner.NullJSON{Valid: true, Value: map[string]any{"f": 5.7003336}}
```

**Expected behavior**

A record with a JSON-encoded value should be inserted without errors.

**Actual behavior**

The following error is returned: 
```
Invalid value for column *** in table ***: Expected JSON.
```

Note that this error occurs **only on real Cloud Spanner**; it does not occur when using the Spanner Emulator.

**Additional context**

As a workaround, I'm using the following wrapper struct.

```go
var safeSpannerJsonEncoder = jsoniter.Config{
	EscapeHTML:              true,
	SortMapKeys:             true,
	ValidateJsonRawMessage:  true,
	MarshalFloatWith6Digits: true,
}.Froze()

type spannerSafeJsonWrapper struct {
	val any
}

func (w spannerSafeJsonWrapper) MarshalJSON() ([]byte, error) {
	return safeSpannerJsonEncoder.Marshal(w.val)
}
```

```go
spanner.NullJSON{Valid: true, Value: spannerSafeJsonWrapper{map[string]any{"f": 5.7003336}}}
```

**Comment by h6ah4i** [comment]
I found a new value that Cloud Spanner cannot accept: `65.34619`

**Comment by rahul2393** [comment]
@h6ah4i 
Cloud Spanner requires that floating point values can be roundtripped from string to double and vice-versa without precision loss.

See also the restrictions here: https://cloud.google.com/spanner/docs/working-with-json#specs

Hence numbers like 5.7003336 or 65.34619 can't be stored.

**Comment by h6ah4i** [comment]
Thanks! I'm currently using the following workaround to resolve this issue.

1. Sanitize the JSON by the following query
```sql
SELECT TO_JSON_STRING(PARSE_JSON(@jsonContent, wide_number_mode=>'round'))
```

2. Create a NullJSON object with `spannerSafeEncodedJsonString`
```go
type spannerSafeEncodedJsonString struct {
	val string
}

func (w spannerSafeEncodedJsonString) MarshalJSON() ([]byte, error) {
	return ([]byte)(w.val), nil
}

# use the following 
spanner.NullJSON{Value: spannerSafeEncodedJsonString{sanitizedJsonString}, Valid: true}
```

**Comment by fabianedl777** [comment]
Hi @rahul2393 , I would like to know how I can replicate this behavior from Go to avoid having to make a query to Spanner to perform the conversion. Is it possible to do this on the client and have some property to activate it because it is a repetitive job that we must do when we want to persist floats64 or do we have to create custom types to persist these values? I think it is normal to have floats with a very long decimal part and due to this limitation we must build extra code.
