### ISSUE TITLE
logging/logadmin: fetching log enteries with pagination not working as expected

### ISSUE THREAD

**Issue by RavGup** [googleapis/google-cloud-go#10348]
**Client**
LogAdmin

**Environment**
GKE

**Go Environment**
bash-3.2$ go version
**go version go1.22.2 darwin/amd64**
bash-3.2$ go env
**GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/ravi.gupta/Library/Caches/go-build'
GOENV='/Users/ravi.gupta/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/ravi.gupta/go/pkg/mod'
GONOPROXY='gitlab.com/ericssonedge/*'
GONOSUMDB='gitlab.com/ericssonedge/*'
GOOS='darwin'
GOPATH='/Users/ravi.gupta/go'
GOPRIVATE='gitlab.com/ericssonedge/*'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/opt/go/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/opt/go/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK='/Users/ravi.gupta/Documents/projects/backend/stratus-api/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/qx/xsnxthn10bn07v688mmhbc700000gn/T/go-build1761307809=/tmp/go-build -gno-record-gcc-switches -fno-common'**
$ go version
$ go env

**Code**
import (

    "cloud.google.com/go/logging"

    "cloud.google.com/go/logging/logadmin")

client, err := logadmin.NewClient(emptyContext, "projects/"+utils.Config.GetString("googleCloudProject"), option.WithTelemetryDisabled())

	if err != nil {

		return nil, echo.NewHTTPError(http.StatusInternalServerError, GenericErrorGetErrorMessages("Failed to retrieve logs", err.Error()))

	}

	defer client.Close()

	var filters []cloudutils.Filter

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.enterprise", Operator: "=", Value: "wareCo"})

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.site", Operator: "=", Value: "uk-lab-1"})

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.imsi", Operator: "=", Value: "999880000000002"})

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.event_ts", Operator: ">=", Value: time.Unix(1716398520, 0).UTC().Format(time.RFC3339)})

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.event_ts", Operator: "<=", Value: time.Unix(1717611764, 0).UTC().Format(time.RFC3339)})

	//passing January 1, 1975 12:00:00 AM value for timestamp. which will be always true. Need this to make event_ts attribute filter working.

	filters = append(filters, cloudutils.Filter{Key: "timestamp", Operator: ">=", Value: time.Unix(157766400, 0).UTC().Format(time.RFC3339)})

	filters = append(filters, cloudutils.Filter{Key: "jsonPayload.is_relevant", Operator: "=", Value: "true"})

	

	entryIte := client.Entries(emptyContext,

		logadmin.Filter(cloudutils.BuildFilter(ctx, filters, utils.Config, cloudutils.CpeServiceResourceType)),

		logadmin.ResourceNames([]string{"projects/" + utils.Config.GetString("googleCloudProject") + "/locations/global/buckets/UE_event_logs/views/_AllLogs"}),

		logadmin.PageSize(5),

	)

```

**Expected behavior**
Log entries must return 5 entries as per pageSize

**Actual behavior**
Log Entries return more records.

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

e.g. Started after upgrading to v0.50.0.

**Comment by gkevinzheng** [comment]
@RavGup How are you checking the number of log entries in the iterator?

**Comment by RavGup** [comment]
I just added a counter while iterating through `entryIte` iterator.

**Comment by gkevinzheng** [comment]
@RavGup The `entryIte` iterator is continuously fetching new LogEntries while iterating through the list of log entries, so adding a counter while iterating through the iterator would give a false result.

I set my `client.Entries` request to a PageSize of 5, and I used the following code to iterate through the entries:

```
count := 0
for {
    fmt.Println(entryIte)
     _, err := entryIte.Next()
    if err == iterator.Done {
	  // No more entries in iterator
	  break
    }
    if err != nil {
	// Error while getting next entry
	break
    }
    count++
}

fmt.Printf("No. Of entries: %v", count)
```

I am printing the iterator here because one of the fields in the `EntryIterator` struct is what the current buffer of logging Entry items is:
https://github.com/googleapis/google-cloud-go/blob/42958171503ed5dab09144bcc2ca59b8aa308217/logging/logadmin/logadmin.go#L273-L278

When I ran the code, I got:
```
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058cfa0 0xc00058d040 0xc00058d0e0 0xc00058d180]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058d040 0xc00058d0e0 0xc00058d180]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058d0e0 0xc00058d180]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058d180]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058dd60 0xc00058de00 0xc00058dea0 0xc00032c140]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058de00 0xc00058dea0 0xc00032c140]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00058dea0 0xc00032c140]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00032c140]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00032cbe0 0xc00032cc80 0xc00032cdc0 0xc0003b2780]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00032cc80 0xc00032cdc0 0xc0003b2780]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc00032cdc0 0xc0003b2780]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0003b2780]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0001225a0 0xc000123040 0xc000123400 0xc000123540]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000123040 0xc000123400 0xc000123540]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000123400 0xc000123540]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000123540]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0003d00a0 0xc0003d0140 0xc0003d01e0 0xc0003d0280]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0003d0140 0xc0003d01e0 0xc0003d0280]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0003d01e0 0xc0003d0280]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0003d0280]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0004448c0 0xc000444960 0xc000444a00 0xc000444aa0]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444960 0xc000444a00 0xc000444aa0]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444a00 0xc000444aa0]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444aa0]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444d20 0xc000444dc0 0xc000444e60 0xc000444f00]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444dc0 0xc000444e60 0xc000444f00]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444e60 0xc000444f00]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444f00]}
&{0xc000408740 0xc000173c20 0xa74160 []}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444460 0xc000444500 0xc0004445a0 0xc000444640]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444500 0xc0004445a0 0xc000444640]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc0004445a0 0xc000444640]}
&{0xc000408740 0xc000173c20 0xa74160 [0xc000444640]}
&{0xc000408740 0xc000173c20 0xa74160 []}
No. Of entries: 40
```

You can see how even though the number of entries is 40, the `items` buffer doesn't exceed 5 items.

**Comment by RavGup** [comment]
@gkevinzheng in the case where, `The entryIte iterator is continuously fetching new LogEntries while iterating through the list of log entries` there is no way we can implement the pagination functionality on UI where, we can display only first 5 records and upon next click, we can grab next 5 and so on... is my understanding correct?

**Comment by gkevinzheng** [comment]
@RavGup The `EntryIterator` struct supports pagination. I was able to get pagination to work with something like this:

```
func NextBatch(it *logadmin.EntryIterator) ([]*logging.Entry, error) {
	var batch []*logging.Entry

	for moreItems := true; moreItems; moreItems = it.PageInfo().Remaining() > 0 {
		entry, err := it.Next()
		if err == iterator.Done {
			// No more entries in iterator
			return batch, err
		}
		if err != nil {
			// Error while getting next entry
			return nil, err
		}
		batch = append(batch, entry)
	}
	return batch, nil
}
```

You can iterate through these batches similarly to how you iterate through log entries.

**Comment by RavGup** [comment]
@gkevinzheng sorry I may no understand correctly but looking at it, when next page is clicked on UI, how we can make sure it gives me records from 6 to 10 (w.r.t example of 5 pagesize). there is not page token which we can return to UI.

**Comment by gkevinzheng** [comment]
You could probably extend the code I have to do something like that, but for that kind of functionality you'd probably have to iterate through the entire list and break it up into chunks cached locally somewhere. I don't think we offer that usecase in the library itself.
