### ISSUE TITLE
spanner: ReadOnlyTransaction().ReadRowUsingIndex()

### ISSUE THREAD

**Issue by majelbstoat** [googleapis/google-cloud-go#1035]
`ReadRow` is useful method for getting a single row. However, if you want to get all the columns of a single row using an index (a common case for unique fields, like, say finding a user by username), it's much harder. ReadUsingIndex requires that you define `STORING` for every column name, which is duplicative and brittle to maintain (remembering to add every new column as you go*) .

The alternative is to use a `SELECT ... {FORCE_INDEX=index}` statement, and call `Query`. Both this and `ReadUsingIndex` require the handling of an iterator which you need to process for just a single item, iterator.Done for Not Found etc. 

It would be helpful if the APIs for such similar queries weren't so wildly different.

I would like to see `ReadRowUsingIndex`, which under the hood did the same kind of join as `SELECT {FORCE_INDEX}` query does, and which returns a single row (technically the first) as a result. I wouldn't even mind if it was enforced that you could only call this on a `UNIQUE` index. This would dramatically reduce boilerplate, which already has to be quite substantial due to Go's lack of generics.

--

(* meta-point, for those cases where I really do want to do this, I'd love to see a language extension like `STORING ALL` or something similar. DynamoDB offers this for its Global Indices, for example.)

**Comment by jba** [comment]
Thanks for your suggestion. 

@snehashah16 thoughts?

**Comment by snehashah16** [comment]
One other way to make this easy, expose the ExecuteQuery (non streaming) version to avoid iterating on resultSets.

**Comment by odeke-em** [comment]
Thank you for this report! @alisskapie and @ilyafaer are working on this with CL https://code-review.googlesource.com/c/gocloud/+/43190
