### ISSUE TITLE
securitycenter: apiv2 listfindings iterator breaking

### ISSUE THREAD

**Issue by y4nben** [googleapis/google-cloud-go#10368]
**Client**

securitycenter 

**Environment**

Cloud Workstation 

**Go Environment**

Go 1.22 

**Code**

```go

import (
	"context"
	"fmt"

	securitycenter "cloud.google.com/go/securitycenter/apiv2" # note this is v2
	"cloud.google.com/go/securitycenter/apiv2/securitycenterpb" # note this is v2 as well
	"google.golang.org/api/iterator"
)

// ... shortened for brevity
req := &securitycenterpb.ListFindingsRequest{
		Parent: "organizations/redacted/sources/-",
	}
	it := client.ListFindings(ctx, req)
	for {
		result, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			fmt.Printf("Listfindings: %v", err)
		}
		finding := result.Finding
		fmt.Printf("Finding Name: %s, ", finding.Name)
		fmt.Printf("Resource Name %s, ", finding.ResourceName)
		fmt.Printf("Category: %s\n", finding.Category)
	}
}
```

**Expected behavior**

When calling ListFinding on securitycenter apiv2, iteration breaks after the first page:

```
Listfindings: rpc error: code = InvalidArgument desc = Invalid page token. Page token does not match request parameters. Field: Parent.panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa04245]
```

I haven't done too much digging into exactly how the iterator breaks, just that it does on apiv2. Changing the imports to apiv1:
```go
import (
	securitycenter "cloud.google.com/go/securitycenter/apiv2" # note this is v1
	"cloud.google.com/go/securitycenter/apiv2/securitycenterpb" # note this is v1
	"google.golang.org/api/iterator"
)
```
Fixes the problem and allows normal iteration. At least from a first glance I can't really see an issue with the autogen implementation.

**Comment by codyoss** [comment]
Hey thanks for the report. I would report this to the service team and/or try with curl. All our iterators work in the same way based off of https://google.aip.dev/132 . Being that all other clients work here makes me think this is a backend issue and not an issue with the client.

Might be good to eyeball the differences in the token format too. You can call `it.PageInfo().Token` to see if there is a visual difference.

**Comment by y4nben** [comment]
Hey Cody, thanks for the super quick response - it does look like the issue is with the scc apiv2 backend, as curl/api explorer give the same error. Looks like their v2 is technically beta but I'll toss them a bug anyways, thanks for the help!
