### ISSUE TITLE
Support for batch api in cloud storage.

### ISSUE THREAD

**Issue by dneralla** [googleapis/google-cloud-go#1040]
## Client

Storage

Is there a way to do batch requests for the storage client  ? If not any plans to add the support ?

**Comment by jba** [comment]
Unfortunately the answer to both is no. But in Go it's usually easy to use concurrency to provide similar performance. Describe what you're trying to do in more detail and we'll try to help you design a high-throughput solution.

**Comment by dneralla** [comment]
@jba We like to reduce number of ops to keep our costs down. Our access pattern is get a bunch of files most times.

**Comment by jadekler** [comment]
@dneralla I've checked in with the storage team. There's value in batch in regards to using less HTTP connections, but each operation in a batch is still billed individually. So, network operations and associated costs would go down, but not access costs.

The storage team is working towards making this a widely supported feature. I'm not sure what the timeframe looks like, but for now I'll change this to a feature request.

**Comment by shanebarnes** [comment]
@jadekler Is there any update on the time frame for batch API support? In my case, I am performing parallel object composite uploads for large files and would like to be able to delete objects quickly after the composition is complete.

**Comment by jadekler** [comment]
cc @frankyn (the storage expert)

**Comment by jadekler** [comment]
cc @frankyn

**Comment by frankyn** [comment]
Hi folks,

Batch API is something in our backlog and is not yet prioritized.
I'll make sure this issue gets prioritized when it does.

**Comment by frankyn** [comment]
For future updates please review tracking bug: https://issuetracker.google.com/issues/142641783.
Closing issue.
