### ISSUE TITLE
maps: option.WithAPIKey no longer works

### ISSUE THREAD

**Issue by nadeemc** [googleapis/google-cloud-go#10456]
**Client**

Places v1 API

**Environment**

Alpine Docker

**Code**

```go
package main

import (
	"context"

	places "cloud.google.com/go/maps/places/apiv1"
	"google.golang.org/api/option"
)

func main() {
	run()
}

func run() error {
	GoogleMapsAPIKey := "some-key-here"
	ctx := context.Background()

	client, err := places.NewClient(
		ctx,
		option.WithAPIKey(GoogleMapsAPIKey),
	)
	if err != nil {
		return err
	}

	// client will error when used for no authentication when used
	/*
	   error = rpc error: code = Unauthenticated desc = Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	*/

	return client.Close()
}
```

**Expected behavior**

WithAPIKey authentication is a valid option. If this is no longer supported, then I would expect a larger semver bump as a breaking change between v1.11.1 and v1.11.2

**Actual behavior**

Authentication fails

**Additional context**

Started after upgrade to cloud.google.com/go/maps v1.11.2

Works after downgrading back to cloud.google.com/go/maps v1.11.1

**Comment by codyoss** [comment]
This should be fixed in https://github.com/googleapis/google-cloud-go/releases/tag/maps%2Fv1.11.3 . Thanks again for the report!

**Comment by nadeemc** [comment]
Confirmed that this is fixed! Thank you for the quick turnaround :)
