### ISSUE TITLE
transport: better error messages for token refreshes.

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1048]
Given this code, and using a 3-legged OAuth token (e.g., via gcloud's ADC), subsequent calls fail with a fairly opaque error message.

```
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	c, err := instance.NewInstanceAdminClient(ctx)
	if err != nil {
		log.Fatal(err)
	}
	cancel()
```

Error returned:

```
rpc error: code = Unauthenticated desc = transport: context canceled
```

**Comment by jba** [comment]
The refresh happens in `golang.org/x/oauth2`. So maybe add something to [`internal.RetrieveToken`](https://github.com/golang/oauth2/blob/master/internal/token.go#L179).

**Comment by broady** [comment]
https://go-review.googlesource.com/c/oauth2/+/121420

**Comment by broady** [comment]
Related to #1045, where this error message would have helped debug the problem.

**Comment by jadekler** [comment]
Friendly ping - is this a feature that we can close here, since the work appears to be in oauth2?

**Comment by odeke-em** [comment]
Thank you @broady, @jba and @jadekler for taking a look at this issue!

In deed as others here have noticed, this work being done is under the oauth2 package and perhaps let's just keep it tracked on that CL as this issue has been left open for longer than a year.

I shall close it but please feel free to reopen it if you please.
