### ISSUE TITLE
"occurrences:vulnerabilitySummary" is missing in apiv1

### ISSUE THREAD

**Issue by ypwu1** [googleapis/google-cloud-go#10517]
**Client**

 `GetVulnerabilitySummary` is only available in `containeranalysis/apiv1beta`.  However `apiv1beta` is marked as deprecated. 

[documentaton](https://cloud.google.com/artifact-analysis/docs/reference/rest/v1/projects.occurrences/getVulnerabilitySummary) do state that it's available  in v1. So what's status quo of this api?

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

Any version

**Expected behavior**
customer should be able to  send `GetVulnerabilitySummary` request provided by `containeranalysis/apiv1`

**Actual behavior**
Use deprecated api `containeranalysis/apiv1beta`

**Comment by codyoss** [comment]
I will look into getting this client updated, thanks for the report.
