### ISSUE TITLE
recommender: v1beta1 Grpc Recommender Client lacking locations calls

### ISSUE THREAD

**Issue by murarustefaan** [googleapis/google-cloud-go#10559]
**Client**

Recommender GRPC

**Environment**

N/A

**Go Environment**

N/A

**Code**

N/A

**Expected behavior**

Go recommender client should have Location methods exposed in the docs.

https://pkg.go.dev/cloud.google.com/go/recommender/apiv1beta1#Client.ListRecommendations
https://cloud.google.com/recommender/docs/reference/rest/v1beta1/organizations.locations/list
https://cloud.google.com/recommender/docs/reference/rest/v1beta1/projects.locations/list
https://cloud.google.com/recommender/docs/reference/rest/v1beta1/folders.locations/list

**Actual behavior**

Go recommender client does not have any location methods.

**Additional context**

Trying to pull recommendations from all locations, but it does not make sense to waste API calls to regions that do not have recommendations at all.

I am willing to work on this if it's something I'm able to do, provided you can share some hints on where to start.

**Comment by codyoss** [comment]
Thank you for the report. I have reported this internally so we can get this fixed.

Internal Bug: 355625308

**Comment by codyoss** [comment]
The internal bug was closed, so I am inclined to close this as well. Please feel free to reach out to support is this is still an issue for you or report it to the service team: https://cloud.google.com/recommender/docs/recommendation-hub/get-support
