### ISSUE TITLE
speechpb: SpeechAdaption

### ISSUE THREAD

**Issue by ibaques** [googleapis/google-cloud-go#10556]
I want to use SpeechContexts in v2 but it's not working anymore when i try to use SpeechAdaption:

	sc := &speechpb.SpeechAdaptation{
			PhraseSets: []*speechpb.SpeechAdaptation_AdaptationPhraseSet { 
				InlinePhraseSet: *speechpb.PhraseSet{
					Phrases: []*speechpb.PhraseSet_Phrase{
							{Value: "Hello"},
							{Value: "Bye"},
					},					
				},
			},
		}

**Comment by codyoss** [comment]
Can you please provide a full code example and explain what is not working. I would encourage you to take a look at our bug template for info to fill out.

**Comment by quartzmo** [comment]
Closing due to lack of response.
