### ISSUE TITLE
auth: panic cloning http.DefaultTransport when it is not a *http.Transport instance

### ISSUE THREAD

**Issue by hslatman** [googleapis/google-cloud-go#10638]
**Client**

KMS

Applies to all authentication paths relying on `auth/internal.CloneDefaultClient`

**Expected behavior**

Detection of the authentication method to succeed

**Actual behavior**

`panic: interface conversion: http.RoundTripper is *something.Different, not *http.Transport`

**Additional context**

This seems to apply to packages that are using the new(er) `auth` package. In this particular case, the automatic detection of application credentials fails, because ultimately the code ends up at `auth/internal.CloneDefaultClient`: https://github.com/googleapis/google-cloud-go/blob/baa1c4076e47df02b146e54cc7f5238c46179bd6/auth/internal/internal.go#L49-L55. 

A similar issue in `identitytoolkit` was reported earlier this year, and was fixed by checking the type before cloning: https://github.com/googleapis/google-cloud-go/issues/10159. Fix: https://github.com/googleapis/google-cloud-go/pull/10162.

The same could be done in this case, potentially renaming the function to reflect its new logic. It could become something like this:

```golang
// DefaultClient returns a [http.Client] with some good defaults.
func DefaultClient() *http.Client {
	if transport, ok := http.DefaultTransport.(*http.Transport); ok {
		return &http.Client{
			Transport: transport.Clone(),
			Timeout:   30 * time.Second,
		}
	}

	return &http.Client{
		Transport: http.DefaultTransport,
		Timeout:   30 * time.Second,
	}
}
```

Note `Clone` was dropped from the function name to reflect the fact that it's not _always_ cloning the transport in this case. The goal of the function also isn't really to clone the client, but to provide a client with sensible defaults, so "Clone" can be dropped from it.

Instead of relying on the `http.DefaultTransport`, the implementation could provide its own sensible defaults instead too.

**Comment by quartzmo** [comment]
@hslatman Thank you for reporting this issue!

**Comment by hslatman** [comment]
Hey @quartzmo, no problem 🙂  

I'm willing to contribute a patch for this on a very short timeline, as this is blocking some of our dependency updates. If my suggestion sounds OK, I can do it immediately. I can abstain from renaming the function, although I think it makes sense to remove `Clone` from it, as the goal of the function is to get a default client.

**Comment by quartzmo** [comment]
@hslatman This change LGTM, and I am also OK with renaming the function. I will also ask @codyoss to approve (original author, who also approved #10162).

If you want, please proceed with your PR. Include a unit test similar to `auth/httptransport/httptransport_test.go` in #10162.

However, if you have any issues with the CLA or just happen to get busy with something else, please let me know, I can also do a PR for this quickly.

**Comment by hslatman** [comment]
@quartzmo I've opened the PR: https://github.com/googleapis/google-cloud-go/pull/10669.

I've changed the approach slightly by checking for a `clonableTransport` instead. This way it would work for `*http.Transport`, but also for user-provided `http.RoundTripper` implementations and a `Clone` method added.
