### ISSUE TITLE
civil: proposal support Date.Weekday

### ISSUE THREAD

**Issue by kardianos** [googleapis/google-cloud-go#1063]
Propose new method on Date to return time.Weekday `func (Date) Weekday() time.Weekday`.

Weekday is strictly calculated from year,month,day. Without this function we have to call `d.In(time.Local).Weekday()`. Certainly not the end of the world, but needless work by programmer and computer.

**Comment by jadekler** [comment]
We looked into it at https://code-review.googlesource.com/c/gocloud/+/41950, but decided not to build this. The time.Location is a variable that users might want to set, which means we need to accept it as a param, which means there's little value in the method itself.

Closing this for now, but happy to review CLs about this if you have specific ideas.
