### ISSUE TITLE
bigtable: Create a cbt tool test suite

### ISSUE THREAD

**Issue by garye** [googleapis/google-cloud-go#1070]
There is currently limited testing of the user-facing surface of `cbt`, e.g. argument parsing for a command. We should have comprehensive tests that verify that both valid and invalid commands are parsed correctly, pass the right request to the server, and show the right information.

**Comment by garye** [comment]
This can be done at the Go API level, but might be even more useful if it can use a `cbt` binary instead.

**Comment by jba** [comment]
[cram](https://pypi.org/project/cram) is great for that. I've used it before.

**Comment by jadekler** [comment]
cc @sneakybueno

**Comment by telpirion** [comment]
The `cbt` tool has moved to another [repo](https://github.com/googleapis/cloud-bigtable-cbt-cli).
