### ISSUE TITLE
auth: panic when calling httptransport.NewClient if http.DefaultTransport was overwritten

### ISSUE THREAD

**Issue by adapap** [googleapis/google-cloud-go#10742]
## Client

androidmanagement/v1

## Environment

go 1.19

## Code and Dependencies

```go
package main

import (
    "net/http"
    "cloud.google.com/go/auth/httptransport"
)

type rt struct {
	key   string
	value string
}
func (r *rt) RoundTrip(req *http.Request) (*http.Response, error) {
	req2 := req.Clone(req.Context())
	req2.Header.Add(r.key, r.value)
	return http.DefaultTransport.RoundTrip(req2)
}

func main() {
    // Override the global http.DefaultTransport.
    http.DefaultTransport = &rt{}

    _, err := httpttransport.NewClient(&httptransport.Options{
        APIKey: "key",
    })
    if err != nil {
      return
    }
}
```

## Expected behavior

Calling `httptransport.NewClient` with a custom implementation of `http.DefaultTransport` should not panic.

## Actual behavior

```panic: interface conversion: http.RoundTripper is *rt, not *http.Transport```

## Additional context

If a client does not specify opts.BaseRoundTripper in httptransport.NewClient, avoid a panic if the global http.DefaultTransport has been overwritten to something that is not an instance of *http.Transport.

It seems that there are several cases where this type check occurs, but this one in particular is blocking our upgrade of Google APIs.

Prior art:
- #10638 (fixed by #10669)
- #10159 (fixed by #10162)

Our use case is to create a new Google API client, but the constructor for NewClient does not allow passing a BaseRoundTripper option as seen [here](https://github.com/googleapis/google-api-go-client/blob/v0.193.0/transport/http/dial.go#L51).

CC @codyoss - proposed PR to fix is here: https://github.com/googleapis/google-cloud-go/pull/10733

**Comment by codyoss** [comment]
Thanks for the report. I agree that this is an issue, but if an non http.Transport is used I don't think we can honor it. Here is the old logic for this area of code:

- https://github.com/googleapis/google-api-go-client/blob/f83609532cab4a169683501030736a5bcd6bfe82/transport/http/dial.go#L253-L256
- https://github.com/googleapis/google-api-go-client/blob/f83609532cab4a169683501030736a5bcd6bfe82/transport/http/dial.go#L324-L330
- https://github.com/googleapis/google-api-go-client/blob/f83609532cab4a169683501030736a5bcd6bfe82/transport/http/dial.go#L288-L302

This logic surrounding this code needs to be able manipulate a http.Transport object for setting up things like mTLS.

**Comment by adapap** [comment]
I see. In the old logic based on the links you provided, there is a default HTTP transport setup if the global one has been overwritten. Perhaps similar logic can be adopted here instead of using the global transport directly? In particular, I think this [baseTransport()](https://github.com/googleapis/google-cloud-go/blob/74cf45efe7dc6f74cadac3f015a705f8dbf69622/auth/internal/transport/transport.go#L89) function could be relevant.

**Comment by codyoss** [comment]
I think that would be a good fallback if the type-converstion and clone fail, yes.
