### ISSUE TITLE
computepb: Add supporting for max_run_duration

### ISSUE THREAD

**Issue by whatisor** [googleapis/google-cloud-go#10744]
## Is your feature request related to a problem? Please describe.
Cannot set max run duration
https://cloud.google.com/compute/docs/instances/limit-vm-runtime#limit-runtime-new-vm

## Describe the solution you'd like
Add MaxRunDuration for Scheduling.

**Comment by codyoss** [comment]
I believe our compute client is a bit out of date and is currently blocked on a breaking change. I will update this issue when we have regenerated the client.

**Comment by codyoss** [comment]
This should now be fixed.
