### ISSUE TITLE
internal/debug: setting debug breakpoints by file/line broken

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#1079]
Original issue:  golang/go#25715. 

Moved here because `x/debug` has moved to `cmd/go-cloud-debug-agent/internal/debug`.

**Comment by olvesh** [comment]
Is this fixed and released? I download the debugger wrapper from https://storage.googleapis.com/cloud-debugger/compute-go/go-cloud-debug but I still get the errors like:
```error setting breakpoint at pkg/pubsub/handler.go:43: couldn't find file "pkg/pubsub/handler.go"```

I can see the v0.26.0 in the releases, but as a pre-release.

**Comment by bgetsug** [comment]
I also have not been able to get snapshots to work. I've tried the release linked from the documentation, and builds of `v0.30.0` and `master`. With the binary from `storage.goog...` I receive `error setting breakpoint...`. With the most recent versions I receive `Error getting stack: DWARF entry for "runtime.lessstack" not found`. 

I've tried compiling my project with:
* go 1.11, `-gcflags=all='-N -l' -ldflags=-compressdwarf=false`
* go 1.10, `-gcflags=all='-N -l'`

@jba can this be re-opened?

**Comment by namusyaka** [comment]
@jba Any progress on this? We need to resolve this issue as soon as possible because our users want to strongly use this.

**Comment by jadekler** [comment]
@namusyaka Debugging tools are currently being holistically investigated (incl by members of the core Go team). To the best of my knowledge, there are some non-trivial technical problems.  I believe there's no immediate ETA for that investigation, and I don't believe a fix for this bug is expected in the immediate future. Sorry :( Will post more news when we have something concrete.

**Comment by kazshinohara** [comment]
@jadekler thanks for your update, looking forward to hearing good news soon.   Lots of users are interested in Stackdriver debug & generally they like golang app on GKE but they cannot make it now due to this issue. .Again thanks for your work!

**Comment by kazshinohara** [comment]
@jadekler Hi any update on this ?

**Comment by jadekler** [comment]
@kazshinohara None that I'm aware of, sorry. Will ping this bug when we know more.

**Comment by dnguyenglu** [comment]
Any updates on this?  I'm getting `Error getting stack: DWARF entry for "runtime.lessstack" not found` as well on go 1.11.11.  Google should document that the cloud debugger doesn't work until this is resolved, so people don't spend time integrating with the go-cloud-debug-agent to find out it's a complete waste of time.

**Comment by willgoldby** [comment]
>  Google should document that the cloud debugger doesn't work until this is resolved, so people don't spend time integrating with the go-cloud-debug-agent to find out it's a complete waste of time.

@dnguyenglu, what's your source for Debugger documentation? Is it [cloud.google.com/debugger/docs](https://cloud.google.com/debugger/docs/), or somewhere else? Where would you like to see this documented?

**Comment by dnguyenglu** [comment]
@willgoldby Probably this page:  https://cloud.google.com/debugger/docs/setup/go 

If you see that page, you'd probably think google cloud debugger fully supports golang, whereas it's really broken.

**Comment by willgoldby** [comment]
@dnguyenglu, I absolutely agree. Thanks for the input!

**Comment by farcaller** [comment]
`Error getting stack: DWARF entry for "runtime.lessstack" not found` is broken even on go 1.10

**Comment by farcaller** [comment]
and go 1.9 is broken with `Error getting stack: PCToSPOffset: no frame table`

**Comment by jadekler** [comment]
This is still being investigated. It requires very extensive fixes / architectural changes. Sorry, not great news. But, yeah, we're still looking into it.

**Comment by codyoss** [comment]
Closing as [cmd/go-cloud-debug-agent is deprecated](https://github.com/googleapis/google-cloud-go/releases/tag/v0.69.0).
