### ISSUE TITLE
pubsub: expire old processing time measurements

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1082]
The pubsub client currently measures time between reception and ack of messages (processing time) in a percentile distribution. The 99%th value of this percentile distribution is used as the ack deadline for messages. This has the the positive effect of reducing the amount of modacks (used to send the ack deadline); a single modack with the right time for a message is better than many modacks with an incorrect arbitrarily low time.

Unfortunately, since we use the 99%th value, we effectively always take the ceiling (excluding extreme outliers - the remaining 1%). Furthermore, since we don't expire data, a very small amount of high values at some point in time will dominate any low values thereafter until the total number of data points is so high as to push the high values into the 1%.

A simple solution to this downside is to expire recordings after a period of time. I think that 6 hours is a good starting place for how much data to hold on to.

**Comment by meredithslota** [comment]
This is in our go/cps-plan backlog.

**Comment by hongalex** [comment]
We attempted an implementation of this but we're not certain that the tradeoffs of increasing complexity warrants this change. Closing in favor of higher priority items.
