### ISSUE TITLE
go-cloud-debug-agent: the exit code of debugged application is not propagated

### ISSUE THREAD

**Issue by olvesh** [googleapis/google-cloud-go#1087]
## Client

go-cloud-debug 

## Describe Your Environment

Alpine Docker on GKE

## Expected Behavior

When the program go-cloud-debug exits I expect the exit code to be propagated by go-cloud-debug

## Actual Behavior

go-cloud-debug exits with code 0.

I have verified my failing program exits with code 1 when not wrapping it, and 1 when wrapped with  go-cloud-debug. And I see no sign of an attempt to capture the exit code of my debugged program in the source under https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/cmd/go-cloud-debug-agent

**Comment by codyoss** [comment]
Closing as [cmd/go-cloud-debug-agent is deprecated](https://github.com/googleapis/google-cloud-go/releases/tag/v0.69.0). The last version of Go it worked with was 1.11.
