### ISSUE TITLE
Regression: TTS Journey voices with Opus: "This voice currently only supports LINEAR16 and MULAW output".

### ISSUE THREAD

**Issue by chrbsg** [googleapis/google-cloud-go#10879]
## Client

Go v1 SDK but looks like a backend server regression/bug.

## Environment

Linux

## Code and Dependencies

```
        req := texttospeechpb.SynthesizeSpeechRequest{
                Voice: &texttospeechpb.VoiceSelectionParams{
                        LanguageCode: "en-US",
                        Name:         "en-US-Journey-D",
                },
                AudioConfig: &texttospeechpb.AudioConfig{
                        AudioEncoding:   texttospeechpb.AudioEncoding_OGG_OPUS,
                        SampleRateHertz: 48000,
                },
        }
        req.Input = &texttospeechpb.SynthesisInput{
                        InputSource: &texttospeechpb.SynthesisInput_Ssml{
                                Ssml: "hi",
                        },
                }
        resp, err := client.SynthesizeSpeech(ctx, &req)
```

## Expected behavior

Opus audio should be generated. 

## Actual behavior

This code has been working for a long time (since Journey voices were first introduced), but today the `client.SynthesizeSpeech` call is returning an error:

```
code = InvalidArgument 
desc = This voice currently only supports LINEAR16 and MULAW output.
```

## Additional context

This looks a lot like the transcription regression where Opus support was apparently removed accidentally: https://github.com/googleapis/google-cloud-node/issues/5609 @danielbankhead

**Comment by chrbsg** [comment]
I opened issue https://issuetracker.google.com/issues/367647327 on the Cloud Platform issue tracker.

**Comment by SuppliedOrange** [comment]
As of the latest update, here's what they say:
https://cloud.google.com/text-to-speech/docs/voice-types#journey_voices_preview
> Note: Journey Voices doesn't support SSML input, speaking rate and pitch audio encodings, and only returns LINEAR16 or MULAW audio.

**Comment by SuppliedOrange** [comment]
Any advice with converting the resulting .wav to .mp3 is appreciated. I've tried using `ffmpeg` and `pydub` (which also uses ffmpeg underneath but the audio turns weird and monodirectional.
