### ISSUE TITLE
compute: expose `ConfidentialInstanceType` field

### ISSUE THREAD

**Issue by msanft** [googleapis/google-cloud-go#10873]
## Is your feature request related to a problem? Please describe.
Currently, the library does not allow to specify the confidential instance type (within the confidential instance config block), while [Terraform provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#example-usage---confidential-computing) and REST API do.

## Describe the solution you'd like
Expose the field in the Go API.

## Additional context
cc @deeglaze, who implemented this in the Terraform provider

**Comment by msanft** [comment]
Perhaps this needs to be adressed in the API spec before being incorporated here? The [upstream proto definition](https://raw.githubusercontent.com/googleapis/googleapis/master/google/cloud/compute/v1/compute.proto) doesn't expose the field as well.

**Comment by codyoss** [comment]
These changes should now be rolled out.
