### ISSUE TITLE
storage: scope creep with extending retention?

### ISSUE THREAD

**Issue by KastenMike** [googleapis/google-cloud-go#10905]
`gcs.bucket.Object(blobPath).NewWriter(ctx)` lets you set `.ObjectAttrs.Retention` and create the blob with the specified retention period with a client that contains `storage.ScopeReadWrite` scope.

If you then try to extend the retention period with `gcs.bucket.Object(blobPath).Update(ctx, updAttrs)` it then fails with `googleapi: Error 403: Access denied., forbidden`. Only changing the client scope to `storage.ScopeFullControl` makes it work.

Was it an oversight or a specific decision? If I want to create a blob with 1 day protection and then the next day extend it another 24 hours it shouldn't be necessary to increase scope to be able to delete the bucket just to allow for the extension imo

client like:
```
ts, _ := google.DefaultTokenSource(ctx, gcsclient.ScopeFullControl)
clientOption := option.WithTokenSource(ts)
cli, err := gcsclient.NewClient(ctx, clientOption)
```

edit: you can limit the accounts role to the minimum permissions so I guess it doesn't matter ultimately, but still seems unnecessary to have to alter scope only for `storage.objects.setRetention`

**Comment by tritone** [comment]
Thanks for the question. This is really an API issue rather than anything specific to this library, but I am not that surprised that adjusting retention policy requires additional scope (and fortunately it looks like you found that there is a way to do it that's short of full control).

If you have further questions or requests for this I'd suggest filing a support case or reaching out to your account rep.

**Comment by KastenMike** [comment]
> but I am not that surprised that adjusting retention policy requires additional scope 

Not a policy, the retention of a single blob. You upload a 100gb blob and set it to be not deletable for 100 years with `ScopeReadWrite` but you can't extend the retention period of a 100kb blob by 1 day with it :D

**Comment by tritone** [comment]
Ah got it -- yeah I would expect additional scope needed to shorten a retention policy, but not to extend it. Feel free to file an issue with support; that is kind of surprising.
