### ISSUE TITLE
storage: RawPath weird behaviour when retrieving bucket's blob 

### ISSUE THREAD

**Issue by GuyAfik** [googleapis/google-cloud-go#10911]
## Client

Storage

## Environment
`Linux`

```
 % go version
go version go1.22.0 darwin/arm64
```

## Code and Dependencies
```
r, err = s.bucketGCP.NewReader(ctx, storagePath, nil)
```

## Problem
We have a large server code base that reads storage content from GCP. The structure of it is the following:
```
/name1-name2-name3/./folderA/folderB/FolderC/FolderD/some-file.zip
```

To read the object we use the storage module:
```
ctx := context.Background()
r, err = s.bucketGCP.NewReader(ctx, storagePath, nil)
```
At the moment we use old version (1.30.1) 
We have tried to upgrade to google storage 1.36.0 and since then our storage objects cannot be found anymore. (in 1.30.1 it works just fine)

The error i am getting is:
```
blob (key "folderA/folderB/FolderC/FolderD/some-file.zip") (code=NotFound): storage: object doesn't exist
```

From my investigation its related to the `RawPath` added when doing http request (in version 1.30.1 - the `RawPath` isn't used):
https://github.com/googleapis/google-cloud-go/blob/main/storage/http_client.go#L839 

If I remove it manually then our storage folders are found just fine. It might be related to URL escaping.

Assistance would be appreciated to whether its related to URL escaping which is done properly or anything else 

## Expected behavior
Request should be successful and storage zip should be found

## Additional context

e.g. Started when upgrading to v1.36.0.

**Comment by tritone** [comment]
Can you provide a fuller repro? In particular I'm curious if your application code is manually escaping the path before passing it in somehow, and what options you are passing when creating the client.

When you view the object in the GCP console, what does the object name look like there?

It also might be worth trying https://pkg.go.dev/cloud.google.com/go/storage#WithJSONReads

**Comment by GuyAfik** [comment]
Hi,

Thanks for the quick response, I will check it out and come back to you with the details.

At the moment I would be happy to try and use [WithJSONReads (https://pkg.go.dev/cloud.google.com/go/storage#WithJSONReads)

Can you provide a code sample?

here's a bit more extended code:

```
type ServiceMarketplace struct {
	bucketGCP               *blob.Bucket
}
func (s *ServiceMarketplace) downloadSomething {
    r, err = s.bucketGCP.NewReader(ctx, file.file, nil)
}
```

It seems like `NewReader` signature is:
```
func (b *Bucket) NewReader(ctx context.Context, key string, opts *ReaderOptions) (*Reader, error)
```

when `ReaderOptions` is a struct:
```
// ReaderOptions sets options for NewReader and NewRangeReader.
type ReaderOptions struct {
	// BeforeRead is a callback that will be called exactly once, before
	// any data is read (unless NewReader returns an error before then, in which
	// case it may not be called at all).
	//
	// asFunc converts its argument to driver-specific types.
	// See https://gocloud.dev/concepts/as/ for background information.
	BeforeRead func(asFunc func(interface{}) bool) error
}
```

How can I configure to use JSON instead of XML?

**Comment by GuyAfik** [comment]
@tritone Can you please help with the query above? Thanks

**Comment by tritone** [comment]
Hey, I'm not sure what code you are referencing above, maybe it's something internal to your codebase? Here is the signature for NewReader in this library: https://pkg.go.dev/cloud.google.com/go/storage@main#ObjectHandle.NewReader

To use WithJSONReads you supply it as an option to NewClient: https://pkg.go.dev/cloud.google.com/go/storage@main#NewClient

`client, err := storage.NewClient(context.Background(), storage.WithJSONReads())  // supply other opts as needed`

**Comment by GuyAfik** [comment]
@tritone The ** Bucket** object has the `NewReader` method I am referring, to retrieve the bucket we use 
```
blob.OpenBucket
``` 

And not `storage.NewClient`

I do not have the option to set the 
```
storage.WithJSONReads()
```
unfortunately

**Comment by tritone** [comment]
Okay, it seems like you are using a library/codebase that is not this one (and I'm not sure exactly which). We don't have those methods in this library.

**Comment by GuyAfik** [comment]
@tritone I am reopening this one because it seems like the problem is with the `newRangeReaderXML`

```
func (c *httpStorageClient) newRangeReaderXML(ctx context.Context, params *newRangeReaderParams, s *settings) (r *Reader, err error) {
	u := &url.URL{
		Scheme:  c.scheme,
		Host:    c.xmlHost,
		Path:    fmt.Sprintf("/%s/%s", params.bucket, params.object),
		RawPath: fmt.Sprintf("/%s/%s", params.bucket, url.PathEscape(params.object)),
	}
	verb := "GET"
	if params.length == 0 {
		verb = "HEAD"
	}
	req, err := http.NewRequest(verb, u.String(), nil)
	if err != nil {
		return nil, err
	}

	if s.userProject != "" {
		req.Header.Set("X-Goog-User-Project", s.userProject)
	}

	if err := setRangeReaderHeaders(req.Header, params); err != nil {
		return nil, err
	}

	reopen := readerReopen(ctx, req.Header, params, s,
		func(ctx context.Context) (*http.Response, error) {
			setHeadersFromCtx(ctx, req.Header)

			if c.dynamicReadReqStallTimeout == nil {
				return c.hc.Do(req.WithContext(ctx))
			}

			cancelCtx, cancel := context.WithCancel(ctx)
			var (
				res *http.Response
				err error
			)

			done := make(chan bool)
			go func() {
				reqStartTime := time.Now()
				res, err = c.hc.Do(req.WithContext(cancelCtx))
				if err == nil {
					reqLatency := time.Since(reqStartTime)
					c.dynamicReadReqStallTimeout.update(params.bucket, reqLatency)
				} else if errors.Is(err, context.Canceled) {
					// context.Canceled means operation took more than current dynamicTimeout,
					// hence should be increased.
					c.dynamicReadReqStallTimeout.increase(params.bucket)
				}
				done <- true
			}()

			// Wait until stall timeout or request is successful.
			stallTimeout := c.dynamicReadReqStallTimeout.getValue(params.bucket)
			timer := time.After(stallTimeout)
			select {
			case <-timer:
				log.Printf("stalled read-req (%p) cancelled after %fs", req, stallTimeout.Seconds())
				cancel()
				err = context.DeadlineExceeded
				if res != nil && res.Body != nil {
					res.Body.Close()
				}
			case <-done:
				cancel = nil
			}
			return res, err
		},
		func() error { return setConditionsHeaders(req.Header, params.conds) },
		func() { req.URL.RawQuery = fmt.Sprintf("generation=%d", params.gen) })

	res, err := reopen(0)
	if err != nil {
		return nil, err
	}
	return parseReadResponse(res, params, reopen)
}
```

Particularly the `RawPath`

```
	u := &url.URL{
		Scheme:  c.scheme,
		Host:    c.xmlHost,
		Path:    fmt.Sprintf("/%s/%s", params.bucket, params.object),
		RawPath: fmt.Sprintf("/%s/%s", params.bucket, url.PathEscape(params.object)),
	}
``` 

The bucket we are sending is lets say `test-test-test`
and the object we are sending is something like `a/b/c/1.1.1/test.zip`

We do not escape it any where in the program.

If I run the same code and omit the `RawPath` it works as expected.
