### ISSUE TITLE
Cloud Bigtable emulator for instances 1 of 4 - Instance

### ISSUE THREAD

**Issue by AVaksman** [googleapis/google-cloud-go#1092]
This is a sub-issue to #1069 

**Implement Instance CRUDL on emulator**

1. CreateInstance
   * Dev
   * PROD
   * Support array of clusters at creation
2. ListInstances
3. GetInstance
4. PartialUpdateInstance
5. DeleteInstance

**Comment by jadekler** [comment]
Deprioritized.
