### ISSUE TITLE
Cloud Bigtable emulator for instances 2 of 4 - Cluster

### ISSUE THREAD

**Issue by AVaksman** [googleapis/google-cloud-go#1093]
This is a sub-issue to #1069

**Implement Cluster CRUDL**
1. CreateCLuster (additional replicated cluster)
2. ListClusters (from instance)
3. ListClusters (from project) -> `instanceId` is passed as `-` [documentation](https://github.com/googleapis/googleapis/blob/01aee5ba3e7bb694a698d803cd10397a4878d696/google/bigtable/admin/v2/bigtable_instance_admin.proto#L289)
4. GetCluster
5. UpdateCluster
6. DeleteCluster

**Comment by jadekler** [comment]
Deprioritized.
