### ISSUE TITLE
tpu: Type mismatch for DeleteNode operation

### ISSUE THREAD

**Issue by m-strzelczyk** [googleapis/google-cloud-go#10951]
Copying [this Issue](https://github.com/GoogleCloudPlatform/golang-samples/issues/4422#issue-2565816398) over, to get some eyes on it:

## Client

TPU

## In which file did you encounter the issue?
https://github.com/googleapis/google-cloud-go/blob/main/tpu/apiv1/auxiliary.go#L101

## Did you change the file? If so, how?
I am trying to wait result from operation of **DeleteNode()** in [PR](https://github.com/GoogleCloudPlatform/golang-samples/pull/4421/files)

## Describe the issue
Delete operation return the wrong type. Expected type to response is `var resp tpupb.Node`, however `DeleteNodeOperation.lro.proto.Result.Operation_Response.Response.TypeUrl` has value `type.googleapis.com/google.protobuf.Empty`. Therefor code the following code:

```go
op, err := client.DeleteNode(ctx, req)
if err != nil {
	return err
}
node, err := op.Wait(ctx) // raises here
if err != nil {
	return err
}
```

Causes an error:
`proto: mismatched message type: got "google.cloud.tpu.v1.Node", want "google.protobuf.Empty`

**Comment by codyoss** [comment]
@m-strzelczyk Can you please report this to the service team. According to the public protos for this service Node is the correct type. https://github.com/googleapis/googleapis/blob/b6a27d13a2f0223051ef720e4e9d0d52323560e6/google/cloud/tpu/v1/cloud_tpu.proto#L75

Closing as if this is an issue, it can't be fixed without the service team republishing there definitions.
