### ISSUE TITLE
Stackdriver Profiler: Support disabling running on GCE auto detection. 

### ISSUE THREAD

**Issue by kelseyhightower** [googleapis/google-cloud-go#1100]
## Client

Stackdriver Profiler

## Describe Your Environment

Google Cloud Functions

## Expected Behavior

Collect and submit profiling data when running on Google Cloud Functions.

## Actual Behavior

Stackdriver Profiler detects it's running on GCE and attempts to retrieve the instance host name and zone from the instance metadata service which is not available on Google Cloud Functions.

As a workaround I've patched the following file:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/profiler/profiler.go#L463

And removed the following code block:

```
if onGCE() {
    var err error
    if config.ProjectID == "" {
        if config.ProjectID, err = getProjectID(); err != nil {
            return fmt.Errorf("failed to get the project ID from Compute Engine: %v", err)
        }
    }

    if config.zone, err = getZone(); err != nil {
        return fmt.Errorf("failed to get zone from Compute Engine: %v", err)
    }

    if config.instance, err = getInstanceName(); err != nil {
        return fmt.Errorf("failed to get instance from Compute Engine: %v", err)
    }
}
```

**Comment by kelseyhightower** [comment]
@aalexand With the check in place I get the following error:

```
failed to get instance from Compute Engine: metadata: GCE metadata "instance/hostname" not defined
```

**Comment by aalexand** [comment]
@kelseyhightower I see. The Cloud Functions environment exposes a metadata server as well, but that doesn't provide the instance attribute.

@jqll FYI

**Comment by aalexand** [comment]
I don't seem to have the rights to close the issue, but this should have been fixed with https://code-review.googlesource.com/c/gocloud/+/33650.

**Comment by enocom** [comment]
Thanks, @aalexand. Closing.
