### ISSUE TITLE
got HTTP response code 400 with body: Invalid multipart request with 0 mime parts

### ISSUE THREAD

**Issue by snktagarwal** [googleapis/google-cloud-go#1107]
I am getting the above error while using the golang GCS API *occasionally*. We are hitting a bit of scale and we are seeing this happen once in a while.

What is the best way for the object to recover at this point? To give you an outline this is what I am doing:

```
if err := aw.bktWriter.Close(); err != nil {
        sugar.Errorf("Unable to close audio file but still proceeding, possibly pushing partial audio file: %+v", err)
}
```

Where bktWriter is basically a `Writer` object.

I am guessing the object (and its connection) to GCS is hosed and I need some kind of recovery mechanism on my side to write the content reliably. Any pointers here?

**Comment by jadekler** [comment]
@frankyn Is this something you know about? If not, I'll follow up with the backend folks.

**Comment by snktagarwal** [comment]
@blangner-suki

**Comment by jadekler** [comment]
Friendly ping @snktagarwal. Also, is it possible to provide a small repro of your code so that we can see which methods you're using?

**Comment by enocom** [comment]
This sounds like it might be related to #1211. @snktagarwal What version of Go are you using?

**Comment by enocom** [comment]
We haven't heard back from you about some clarifying info.

Closing this for now, but feel free to respond and continue the discussion later."

**Comment by bradfitz** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/39076 gensupport: fix incorrect MIME boundary being used in bodies on retries
