### ISSUE TITLE
compute: List Firewalls - mock response Iterator

### ISSUE THREAD

**Issue by patrick-lerch** [googleapis/google-cloud-go#11082]
## Client

compute

## Environment

N.A.

## Code and Dependencies

```go
import (
compute "cloud.google.com/go/compute/apiv1"
)

package main

func TestListingFirewalls() {
  firewallIt := compute.FirewallIterator{} // how can I properly build such an object, so I can make my mock NewFirewallsRESTClient.List return it
}
```

<details>
  <summary>go.mod</summary>

```text
module modname

go 1.23.0

require (
   cloud.google.com/go/compute v1.28.0
)
```

</details>

## Expected behavior

I need a way to mock the List response of the NewFirewallsRESTClient

## Actual behavior

Mocking not possible

## Screenshots

N.A

## Additional context

N.a

**Comment by quartzmo** [comment]
Hi @patrick-lerch,

Sorry for the late response. The fields of `compute.FirewallIterator` are private, so you can't set them externally. I believe you will need to mock `compute.FirewallIterator` as well.

**Comment by patrick-lerch** [comment]
Hey @quartzmo can you maybe provide an example how I can mock the https://pkg.go.dev/cloud.google.com/go/compute/apiv1#FirewallsClient.List call ?

**Comment by codyoss** [comment]
See https://github.com/googleapis/google-cloud-go/blob/main/testing.md for advice in this space.

**Comment by patrick-lerch** [comment]
I was aware of this guide already, but I think for the compute service it is not working or at least I was not able to come up with a working solution.

Can you point me to the unimplemented service which I could use for this. Last time I checked I didn't find one for the "new" sdk.

**Comment by quartzmo** [comment]
The top section in the guide is about gRPC, but the compute client uses HTTP. Check out the next section: https://github.com/googleapis/google-cloud-go/blob/main/testing.md#testing-using-mocks.

**Comment by codyoss** [comment]
In general with this SDK I would recommend using fakes and standing up a backing HTTP service. If you want to mock things like list rpcs you would first need to put a small facade in front of the types so you can better control the state of the iterator.
