### ISSUE TITLE
aiplatform: please release the `aiplatform` component

### ISSUE THREAD

**Issue by Valeriy-Burlaka** [googleapis/google-cloud-go#11124]
Please release the `aiplatform` component. The [last release](https://github.com/googleapis/google-cloud-go/pull/9772) was in June and it's missing many updates for the Evaluation Service API, [including](https://github.com/googleapis/google-cloud-go/pull/10627/files#diff-4a8a13bdf7b6e088262f4ef03a83bccca4884e8ac12c451a1b2ac36f4ead711fR442) pairwise and pointwise metrics.
Thanks!

**Comment by codyoss** [comment]
Done. There was another team managing this release for a while so it got split out from our main release train. I will move it back later this week. v1.69.0 is released
