### ISSUE TITLE
storage: return file metadata on read

### ISSUE THREAD

**Issue by jshore1296** [googleapis/google-cloud-go#11211]
## Is your feature request related to a problem? Please describe.
Currently, it requires two API calls to open a file and retrieve its metadata.  It is cheaper at scale to return metadata when opening the file.  This is supported at the API level by both xml and gRPC, but is not exposed by this library.

## Describe the solution you'd like
Add a field to the `ReaderObjectAttrs` that stores the Metadata on the file being read, and expose this to the caller similar to how `Size` and other such options are exposed.

**Comment by tritone** [comment]
#11212 has been merged and will go out tomorrow in storage/v1.49.0. Thanks for the contribution!
