### ISSUE TITLE
pubsub: ackDeadline cancel context

### ISSUE THREAD

**Issue by piapip** [googleapis/google-cloud-go#11210]
## Is your feature request related to a problem? Please describe.
Duplicated events when the process takes too long.

## Describe the solution you'd like
Cancel the given context if ackDeadline has been reached.

## Additional context
PubSub pushes the event back to the queue if it takes too long to process. I understand that it's for preventing event loss in case the application crashes. But if the actual event processing takes a long time to perform (says, the Database takes a long time to write), then it may create duplicated events.
Is it better to have the application handle the AckDeadline separately?
Or is it better to have the library cancel the given context?

**Comment by piapip** [comment]
> I'll assume you're referring to the [message ack deadline](https://pkg.go.dev/cloud.google.com/go/pubsub#hdr-Ack_Deadlines) that's set by the client library rather than the subscription's ackDeadline

Yes, you are correct, I should have made it clearer that I refer to the client library.

> Could you clarify more on that point?

My goal is to get a cue when the AckDeadline hits, so I can cancel the current process. Maybe I can receive a cue if I set MaxExtension equal to AckDeadine, let me test that.

**Comment by piapip** [comment]
Oooh I found the kinda same issue here.
https://github.com/googleapis/google-cloud-go/issues/5858

So mbrancato tried to handled context.Canceled from
```go
	err = sub.Receive(givenCtx, func(ctx context.Context, m *pubsub.Message) {
		// Processing that may, at times, exceed the max extension time
                time.sleep(1 * time.Minute)
		m.Ack()
	})
	if err != context.Canceled {
		// TODO: Handle error.
	}
```

So I was thinking that maybe the `sub.Receive` would cancel the givenCtx when the MaxExtension has been reached. But it seems like it won't. After checking the library and your explanation, I'm quite sure that it won't.

Could you help me confirm it?

**Comment by hongalex** [comment]
So this isn't exactly how contexts work. In the above example, `givenCtx` is something you as the developer would pass into the `Receive` function to tell the library to cancel execution. There is no way to signal that context is cancelled using `givenCtx` from the library's perspective.

> My goal is to get a cue when the AckDeadline hits, so I can cancel the current process.

This isn't something the library supports currently as you already found out. I recommend creating a timer inside your handler function to check for how long the message has been processed for.

**Comment by piapip** [comment]
I agree. Thank you so much for the explanation!!!
