### ISSUE TITLE
internal/uid: Timestamp() does not work on 32bit architectures 

### ISSUE THREAD

**Issue by pterjan** [googleapis/google-cloud-go#11351]
The tests fail when building:

```
cloud.google.com/go/internal/uid
--- FAIL: TestTimestamp (0.00s)
    uid_test.go:46: got ok = false, want true
```

The reason is that it uses nanoseconds since midnight so after about 4s after midnight it no longer fits in a 32bit int so strconv.Atoi in https://github.com/googleapis/google-cloud-go/blob/6aa27dc79046df09e34e93044dbfe47cb3e9aa54/internal/uid/uid.go#L134 returns an error.

I am not sure what the correct solution would be as we can't just use strconv.ParseInt(subs[4], 10, 64) because time.Date wants an int for the ns parameter.

Easiest would be to use the hour/minute/second in the string and only use ns at the end for subsecond duration, like is probably intended by time.Date taking an int rather than an int64 .

**Comment by pterjan** [comment]
Something that seems to be working:
```go
        ns, err4 := time.ParseDuration(subs[4] + "ns")
        ...
        return time.Date(y, time.Month(m), d, 0, 0, 0, 0, time.UTC).Add(ns), true
```

**Comment by quartzmo** [comment]
@pterjan Thank you for reporting this issue. I will review your related PR as soon as I can.
