### ISSUE TITLE
Add an in-memory emulator for spanner

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1181]
Details:

- Very basic.
- When making queries like SELECT, user should provide the expected output instead of trying to interpret SQL.

**Comment by lzlicd** [comment]
Just curious do we have in-memory emulator currently?

**Comment by jadekler** [comment]
We do not, and we do not plan to in the near future.

**Comment by tmc** [comment]
@jadekler does reopening indicate that there are plans for this?

**Comment by dsymonds** [comment]
Yes, I've got something coming...

**Comment by dsymonds** [comment]
Hey, @jadekler, we can probably close this bug now that the emulator is in a tagged release. I'm still working on improving it, but this issue seems satisfied.

**Comment by jadekler** [comment]
SG
