### ISSUE TITLE
Expose all Table Info in SDK

### ISSUE THREAD

**Issue by cobookman** [googleapis/google-cloud-go#1182]
Have `type Table struct....` expose the full data represented in RPC call for Table: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource

This requires Code Change to Function (bqToTable) that converts RPC Call Table to library Table:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/dataset.go#L347-L357

Which is called here:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/dataset.go#L342

**Comment by cobookman** [comment]
Hi Jadekler,

I'd argue that this is a bug in the Golang SDK. The SDK is not exposing the full information given by each RPC call and doesn't follow the RPC spec.

**Comment by cobookman** [comment]
For reference.

## Golang SDK:

dataset.Tables() gives an iterator which returns objects of type Table.
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/d85eb0e711d3ac52c5d912b762c25044c8a140c7/bigquery/table.go#L29-L39

You'd then need to call `table.Metadata` on each table, causing an additional RPC call for getting the full table metadata.
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/d85eb0e711d3ac52c5d912b762c25044c8a140c7/bigquery/table.go#L42-L108

Where-as for the RPC, you can do 1 [Tables List API call](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/list) to get many table's metadata:
```
{
  "kind": "bigquery#tableList",
  "etag": etag,
  "nextPageToken": string,
  "tables": [
    {
      "kind": "bigquery#table",
      "id": string,
      "tableReference": {
        "projectId": string,
        "datasetId": string,
        "tableId": string
      },
      "friendlyName": string,
      "type": string,
      "timePartitioning": {
        "type": string,
        "expirationMs": long,
        "field": string,
        "requirePartitionFilter": boolean
      },
      "clustering": {
        "fields": [
          string
        ]
      },
      "labels": {
        (key): string
      },
      "view": {
        "useLegacySql": boolean
      },
      "creationTime": long,
      "expirationTime": long
    }
  ],
  "totalItems": integer
}
```

**Comment by shollyman** [comment]
I'm inclined to leave this as is for now, pending further changes to the backend or a major revision to this library.  One problem is that the fields provided in the table list response is only a partial projection, so the resource you get back isn't the full set of metadata.  A notable missing aspect as you see in the example is it's missing the schema in the response.

By contrast, the java version of the bigquery library does return the provided table metadata as part of the list response in the client, and a frequent problem reported by users is the fact that you still need to call the equivalent of bigquery.tables.get to get the complete representation.

**Comment by jadekler** [comment]
Closing this issue unless we run into other, specific problems that this surfaces. I'll note that manual clients intentionally do not attempt to cover 100% of the underlying library's surface.
