### ISSUE TITLE
Logging: integration test TestLogsAndDelete should not share a client with other tests

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1189]
[TestLogsAndDelete](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/deb9345c9d7f5f3d9d07726b582d39105f57feb1/logging/logging_test.go#L461) tests the deletion of all logs. However, it relies on other tests in the package to create these logs. This makes the behavior of the test unpredictable. When run by itself, it may delete zero logs. When run with other tests, it may delete many logs. The unpredictability makes it hard to test: in the former case it always passes, but in the latter case it may fail.

The logging service is eventually consistent: we should explore whether that eventual consistency is order of seconds or not. If it only takes a few seconds for a log to reach the server, then perhaps we should consider updating the test to:

- Create a log
- Poll for the server for the log
- Delete the log

**Comment by jadekler** [comment]
I'm not entirely sure it's worth investigating this test further. The [current failures](https://sponge.corp.google.com/target?id=d6818557-c2c9-47ea-b9a4-3820034aae74&target=cloud-go-libraries%2Fcontinuous%2Fgo19&searchFor=) are the result of quota problems. Updating the test as described above would help by making the test more consistent and by making the test delete only one log per run (instead of on average 5), but it may not be a problem we care enough to "fix".

@jba Do you have thoughts on this? I noticed that you were the last one to work on unflaking this test.

**Comment by codyoss** [comment]
https://github.com/googleapis/google-cloud-go/issues/1654 will fix this.

**Comment by nicoleczhu** [comment]
Reopening this. I'll impl Jean's suggest bc this test should be able to run on its own
