### ISSUE TITLE
cbt should support passing arbitrary bytes from the command line

### ISSUE THREAD

**Issue by enocom** [googleapis/google-cloud-go#1195]
Bigtable supports arbitrary bytes for a number of values (e.g., row key, column qualifier, etc.). See [here](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/data.proto).

The `cbt` tool should likewise support passing in arbitrary bytes from the command line. For example, assuming a `\x80\x80` row key exists with values, the following `cbt` command should return the appropriate values:

```
cbt lookup sometable '\x80\x80'
```

**Comment by jadekler** [comment]
cc @sneakybueno

**Comment by sneakybueno** [comment]
Hey @enocom,

I did a little testing and at least in regards to `cbt lookup`, arbitrary bytes are supported but require a prefix to be interpreted properly. 

If you add a `$` to the byte string cbt should work as intended.

For example:
`cbt lookup sometable $'\x80\x80'

**Comment by jadekler** [comment]
@sneakybueno How about let's call this a docs issue and spell that out for users? WDYT?

**Comment by enocom** [comment]
I agree. It's a documentation problem. I haven't looked at this for awhile, but didn't see any obvious way to do this as a user.
