### ISSUE TITLE
storage: support the compose operation using the SignedURL

### ISSUE THREAD

**Issue by ks888** [googleapis/google-cloud-go#1199]
It would be great if the storage library supports the compose operation using the signed url.

https://cloud.google.com/storage/docs/xml-api/put-object-compose

I think there is some ways to implement this:

(a) Add the `Compose bool` field to the [storage.SignedURLOptions](https://godoc.org/cloud.google.com/go/storage#SignedURLOptions). If the value is true, the `compose` query parameter is added when the signature and signed url are generated.

(b) Add the `Query string` field to the [storage.SignedURLOptions](https://godoc.org/cloud.google.com/go/storage#SignedURLOptions). The specified query is used to generate the signature and the signed url.

Because other operations such as [GET Object Encryption](https://cloud.google.com/storage/docs/xml-api/get-object-encryption) and [Get Object ACLs ](https://cloud.google.com/storage/docs/xml-api/get-object-acls) also depend on the query parameter, it seems (b) is more convenient for me.

If it looks ok, I'd like to create the pull request to support this.

**Comment by jadekler** [comment]
cc @frankyn

**Comment by frankyn** [comment]
Hi @ks888, thanks for filing an issue!

I don't understand the rationale for having a signedURL used to perform a compose operation. Could you tell us more about your use case?

**Comment by ks888** [comment]
@frankyn I want to upload a large object in parallel, as described in the doc below:
https://cloud.google.com/storage/docs/composite-objects#_Uploads

I'm now working on a CI service and my users' code runs on the limited docker container. The container creates the snapshot of the workspace for the caching purpose. The problem here is the workspace is often larger than 1GB, and its upload occupies a half of the total time. In this case, I think the parallel upload is helpful.

**Comment by frankyn** [comment]
Apologies on time. I had to do some research on this question.

I think (b) sounds like a fine solution given how [compose operations work using the XML API](https://cloud.google.com/storage/docs/composite-objects#_Xml). It should be exposed as a general query map parameter for other operations.

**Comment by odeke-em** [comment]
How's it going @ks888 and @frankyn on this issue?

**Comment by frankyn** [comment]
This was resolved by @tritone in https://github.com/googleapis/google-cloud-go/issues/1747.
