### ISSUE TITLE
cmd/go-cloud-debug: should forward SIGUSR1 and SIGUSR2

### ISSUE THREAD

**Issue by MrTrustor** [googleapis/google-cloud-go#1203]
In GoogleCloudPlatform/microservices-demo#85, we want to use SIGUSR1 and SIGUSR2 to modify the behavior of a running application.

Today, it doesn't seem like go-cloud-debug is forwarding those signals to the process it's running.

**Comment by codyoss** [comment]
Closing as [cmd/go-cloud-debug-agent is deprecated](https://github.com/googleapis/google-cloud-go/releases/tag/v0.69.0). The last version of Go it worked with was 1.11.
