### ISSUE TITLE
go-cloud-debug seems to break logging?

### ISSUE THREAD

**Issue by MrTrustor** [googleapis/google-cloud-go#1204]
## Client

Stackdriver Debugger

## Describe Your Environment

GKE + Docker image from that [PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/87/files#diff-4d6739bb8f093ea2faa9a57047afc857) (it introduces go-cloud-debug in the ProductCatalogService app)

## Expected Behavior

Logs from the application behave like before.

## Actual Behavior

I'm getting the first few lines of logs of the application, and then nothing.

## Impacted PRs
GoogleCloudPlatform/microservices-demo#85
GoogleCloudPlatform/microservices-demo#87

**Comment by jadekler** [comment]
Just to be clear, are you using `go-cloud-debug-agent`?

**Comment by MrTrustor** [comment]
I'm following the official instructions: https://cloud.google.com/debugger/docs/setup/go#gce
The binary is called go-cloud-debug. Are there 2 different things?

**Comment by jadekler** [comment]
Ah! Thanks, TIL that we have a binary distribution for it. Yes, that's it.

Unfortunately, we're aware of several major issues about this tool that will require substantial work. For now, we're researching what that work looks like.

**Comment by jadekler** [comment]
@MrTrustor An internal Go team member asks whether you could try building from source? It may be that the binary is out of date with recent fixes. See: https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/cmd/go-cloud-debug-agent

**Comment by odeke-em** [comment]
Hello again @MrTrustor, @jadekler left a question some months ago, could you please try again?

**Comment by MrTrustor** [comment]
I'm not able to reproduce anymore, so I'll close this. I'll reopen this if I run into this again.
