### ISSUE TITLE
yarn-env prefix not supported by Go Dataproc client API

### ISSUE THREAD

**Issue by marioguerriero** [googleapis/google-cloud-go#1209]
## Client

Dataproc

## Describe Your Environment

Docker on GKE

## Expected Behavior

When creating a new cluster, software configuration properties can be passed to all the nodes. Specifically, by passing the following property:

```
SoftwareConfig: &dataprocpb.SoftwareConfig{
    Properties:	map[string]string{
        "yarn-env:YARN_RESOURCEMANAGER_OPTS": "-javaagent:/usr/bin/jolokia-jvm-1.6.0-agent.jar",
}
```

I would expect a new environment variable definition to be added to the `yarn-env.sh` file.

## Actual Behavior

Passing the above property using `gcloud` command line utility works fine. However, the Go client library is unable to set it, as the `yarn-env` prefix is apparently not supported.

The [list of all the available prefixes](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties) includes `yarn-env` but [here](https://godoc.org/google.golang.org/api/dataproc/v1#SoftwareConfig) is the documentation for the `SoftwareConfig` structure, not mentioning the `yarn-env` as one of the supported ones.

**Comment by jadekler** [comment]
Hello! The dataproc client is auto-generated. Would you mind filing an issue against the backend team at https://cloud.google.com/support/docs/issue-trackers?
