### ISSUE TITLE
Unable to take firestore export (backup)

### ISSUE THREAD

**Issue by viggy28** [googleapis/google-cloud-go#1210]
(delete this for feature requests)

## Client

Firestore

## Describe Your Environment

localhost, cloud functions (doesn't matter)

## Expected Behavior

I don't see a method called exportDocuments()

As per the comments here https://github.com/googleapis/google-api-go-client/blob/master/firestore/v1/firestore-gen.go#L3, I should see the method in this package

https://github.com/googleapis/google-api-go-client/blob/master/firestore/v1/firestore-gen.go#L1380

## Actual Behavior

I don't see the method. Or am i missing anything?

**Comment by jadekler** [comment]
@schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
The official Go client for Firestore (the manual client) doesn't yet support this method. We currently only support non-Admin APIs.

If you want to use this functionality, then you have to follow our documentation to call either the GRPC or the REST endpoint directly (https://firebase.google.com/docs/firestore/use-rest-api). 

The`exportDocuments` API is outlined here https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases/exportDocuments 

Sorry about the inconvenience.

**Comment by jadekler** [comment]
Go now supports the admin SDK at http://godoc.org/cloud.google.com/go/firestore/apiv1/admin.
