### ISSUE TITLE
storage: Bucket/Object operations panic with nil Client

### ISSUE THREAD

**Issue by rsc** [googleapis/google-cloud-go#1222]
## Client

Storage

## Describe Your Environment

My Mac. 
cloud.google.com/go v0.33.1

This program:

```
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/storage"
)

func main() {
	var client *storage.Client
	fmt.Println(client.Bucket("b").Object("o").Attrs(context.Background()))
}
```

## Expected Behavior

I get a nice error returned from Attrs about mistakenly using a nil Client.

## Actual Behavior

I get a panic that I have to debug to find out that o.c is nil.

```
go run x.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x143249b]

goroutine 1 [running]:
cloud.google.com/go/storage.(*ObjectHandle).Attrs(0xc0000f2bb0, 0x1608260, 0xc0000c8000, 0x0, 0x198ed60, 0x1c01458)
	/Users/rsc/pkg/mod/cloud.google.com/go@v0.33.1/storage/storage.go:378 +0x18b
main.main()
	/tmp/z/x.go:12 +0x1e2
exit status 2
```

I see a call named o.validate. Maybe it should check that o.c != nil.

**Comment by jadekler** [comment]
Closing this since the conversation has stalled. Give a shout if you'd like to continue the conversation.
