### ISSUE TITLE
Firestore: Query.StartAt is broken for subcollections

### ISSUE THREAD

**Issue by erock2112** [googleapis/google-cloud-go#1225]
Query.collectionPath() inserts an extra "/documents/" for subcollections: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/query.go#L51

For the parent collection, the query works as expected.  For the sub-collection, I get this error:

```
firestore: document snapshot for
projects/my-project/databases/(default)/documents/parent-collection/parent-doc/my-coll
passed to query on projects/my-project/databases/(default)/documents/parent-collection/parent-doc/documents/my-coll
```

Note the extra instance of "/documents/".  Here's some code to reproduce:

```
func testQuery(ctx context.Context, coll *firestore.CollectionRef) {
        doc := coll.NewDoc()
        if _, err := doc.Create(ctx, map[string]string{
                "label": "my-label",
        }); err != nil {
                panic(err.Error())
        }
        snap, err := doc.Get(ctx)
        if err != nil {
                panic(err.Error())
        }
        q := coll.Where("label", "==", "my-label").StartAt(snap)
        it := q.Documents(ctx)
        for {
                d, err := it.Next()
                if err == iterator.Done {
                        break
                } else if err != nil {
                        panic(err.Error())
                }
                fmt.Println(d.Ref.ID)
        }
        fmt.Println("Success")
}

func main() {
        ...
        ctx := context.Background()
        client, err := firestore.NewClient(ctx, "my-project", ...)
        if err != nil {
                panic(err.Error())
        }
        parentColl := client.Collection("parent-collection")
        testQuery(ctx, parentColl)

        parentDoc := parentColl.Doc("parent-doc")
        coll := parentDoc.Collection("my-coll")
        testQuery(ctx, coll)
}
```

**Comment by jadekler** [comment]
Thanks for reporting this, and the fantastic repro.

**Comment by jadekler** [comment]
It turns out this is actually illegal - StartAt may only be queried with a child document (as opposed to a parent, in your example). I'll amend our docs to call this out.

**Comment by erock2112** [comment]
I'm a little confused; in both cases in the above code, the document passed to StartAt is a child of the collection being queried.  For the record, the code which triggered the issue for us is more natural; when we hit server-side timeouts due to iterating a large number of documents in a query, we stop querying and start again, passing the last-seen document to StartAt.  To me, this seems like a natural usage of StartAt.

**Comment by jadekler** [comment]
Apologies, and thanks for the followup. You're right, this once again looks like a bug. :)

**Comment by erock2112** [comment]
No worries, thanks!
