### ISSUE TITLE
Firestore: Transaction writes are not reset when the transaction is retried

### ISSUE THREAD

**Issue by erock2112** [googleapis/google-cloud-go#1226]
In RunTransaction, when a transaction fails to commit with Aborted status, the entire transaction is retried.  However, Transaction.writes is not reset between attempts.  This results in read+write transactions failing the second attempt due to "read after write in transaction", and also results in both the initial and retried sets of writes being sent on the subsequent call to Commit.  The relevant code is here: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/transaction.go#L151

I was able to reproduce this was by hacking the client code to return Aborted on the second call to Commit, ie. change this code https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/apiv1beta1/firestore_client.go#L309 to the below:

```
var MockCommitAborted bool = false

// Commit commits a transaction, while optionally updating documents.
func (c *Client) Commit(ctx context.Context, req *firestorepb.CommitRequest, opts ...gax.CallOption) (*firestorepb.CommitResponse, error) {
        ctx = insertMetadata(ctx, c.xGoogMetadata)
        opts = append(c.CallOptions.Commit[0:len(c.CallOptions.Commit):len(c.CallOptions.Commit)], opts...)
        var resp *firestorepb.CommitResponse
        err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
                var err error
                resp, err = c.client.Commit(ctx, req, settings.GRPC...)
                return err
        }, opts...)
        if err != nil {
                return nil, err
        }
        if MockCommitAborted {
                return nil, status.Errorf(codes.Aborted, "Aborted")
        }
        return resp, nil
}
```

And then used this code to reproduce:

```
func main() {
        ...
        ctx := context.Background()
        client, err := firestore.NewClient(ctx, "my-project", ...)
        if err != nil {
                panic(err.Error())
        }

        coll := client.Collection("fake-collection")
        ref := coll.NewDoc()
        if _, err = ref.Create(ctx, map[string]string{
                "hello": "world",
        }); err != nil {
                panic(err.Error())
        }
        apiv1beta1.MockCommitAborted = true
        if err := client.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
                snap, err := tx.Get(ref)
                if err != nil {
                        return err
                }
                data := snap.Data()
                data["label"] = "my-label"
                return tx.Set(ref, data)
        }); err != nil {
                panic(err.Error())
        }
}
```

The test for retrying transactions includes an empty transaction, otherwise I think this would have been caught by the test: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/transaction_test.go#L144
I haven't run the steps in the Contributing guide to try to extend the test to cover this case.

**Comment by jadekler** [comment]
See: https://code-review.googlesource.com/c/gocloud/+/34510

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/36092 fixes this
