### ISSUE TITLE
Spanner client  doesn't cancel after context.Deadline()

### ISSUE THREAD

**Issue by dneralla** [googleapis/google-cloud-go#1230]
## Client

Spanner

Spanner client on a large number of requests doesn't cancel and exit even after context.Deadline() is exceeded.  In our case deadline is 1 sec. But context gets cancelled after 40 seconds. I checked the Spanner server RPC metrics and during this period most of the requests doesn't reach server at all. Its definitely something on the client.

By looking at the code my guess is that its happening while acquiring a lock on the sessionPool  

```golang
          p.mu.Lock()
          if !p.valid {
              p.mu.Unlock()
              return nil, errInvalidSessionPool()
          }
          if p.idleWriteList.Len() > 0 {
              // Idle sessions are available, get one from the top of the idle list.
              s = p.idleWriteList.Remove(p.idleWriteList.Front()).(*session)
              tracePrintf(ctx, map[string]interface{}{"sessionID": s.getID()}, "Acquired read-write session")
          } else if p.idleList.Len() > 0 {
              s = p.idleList.Remove(p.idleList.Front()).(*session)
              tracePrintf(ctx, map[string]interface{}{"sessionID": s.getID()}, "Acquired read-only session")
          }

````

**Comment by dneralla** [comment]
@jadekler  Any update here ?

**Comment by jadekler** [comment]
@dneralla Sorry for the lack of an update. Holidays + traveling. :/ I plan to look at this next week, hopefully early in the week.

**Comment by jadekler** [comment]
@dneralla I tried and failed to reproduce this, but of course I'm certain your setup is different than mine. :) To help figure this out, could you (ideally) provide a small repro, or post some of your code?

**Comment by jadekler** [comment]
We've asked some clarifying information but haven't heard from you in a while. Closing this issue. Feel free to ping back at a later time.
