### ISSUE TITLE
rpcreplay hangs in replay mode if endpoint is unresponsive

### ISSUE THREAD

**Issue by vangent** [googleapis/google-cloud-go#1239]
Go Cloud (https://github.com/google/go-cloud) is using [rpcreplay](https://godoc.org/cloud.google.com/go/rpcreplay) for record/replay on gRPC. We've noticed that `grpc.DialContext` hangs, even when using the `DialOptions` returned from rpcreplayer's `DialOptions()`, when given an unresponsive endpoint. I wouldn't expect replay mode to make any network connections.

For example, you can pull Go Cloud and:

```
cd runtimevar/runtimeconfigurator
go test
# works, replay mode!
vi runtimeconfigurator.go  
# edit the endPoint constant to use port 444 instead of 443
go test
# hangs....
```

You can also reproduce this by disabling your internet connection when running the tests.

If I remove the `WithBlock` options added [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/rpcreplay/rpcreplay.go#L370), the tests work, but there's a comment about why that option is added so I doubt it is safe to just remove.

**Comment by vangent** [comment]
@jba FYI

**Comment by jadekler** [comment]
Could you expand on how you're using rpcreplay? Bit confused about this part:

```
I wouldn't expect replay mode to make any network connections.
```

AFAIK, _the user_ is in charge of making/not making connections. So, for example, in our tests we do:

```
if testing.Short() {
    if testutil.CanReplay(replayFilename) {
        // ...
        l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return nil, err
	}
	conn, err := grpc.Dial(l.Addr().String(),
		append([]grpc.DialOption{grpc.WithInsecure()}, rep.DialOptions()...)...)
	if err != nil {
		return nil, err
	}
        client, err := NewClient(ctx, ri.ProjectID, option.WithGRPCConn(conn))
         // ...
    }
} else if *record {
    rec, err := rpcreplay.NewRecorder(replayFilename, b)
    // ...    
}
```

See: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/datastore/integration_test.go#L109-L134

**Comment by vangent** [comment]
Hmm, the documentation does not suggest that at all.

https://godoc.org/cloud.google.com/go/rpcreplay#hdr-Replaying

uses the same `serverAddress` in `Dial` that was used in `Record` above.

If this behavior is expected, maybe just update that documentation.

**Comment by jba** [comment]
I'll look into whether rpcreplay can do a better job here.
