### ISSUE TITLE
[bigtable] Emulator reads with row count from table with deleted rows differ from production

### ISSUE THREAD

**Issue by dinsandra** [googleapis/google-cloud-go#1240]
Hello.

Given the following script:

```shell
BIGTABLE_EMULATOR_HOST=localhost:8086
PROJECT=testproject
INSTANCE=testinstance

cbt -project $PROJECT -instance $INSTANCE createtable tab families=fam
cbt -project $PROJECT -instance $INSTANCE set tab r1 fam:col=v1
cbt -project $PROJECT -instance $INSTANCE set tab r2 fam:col=v2
cbt -project $PROJECT -instance $INSTANCE set tab r3 fam:col=v3
cbt -project $PROJECT -instance $INSTANCE read tab start=r count=2
cbt -project $PROJECT -instance $INSTANCE deleterow tab r1
cbt -project $PROJECT -instance $INSTANCE read tab start=r count=2
cbt -project $PROJECT -instance $INSTANCE deleterow tab r2
cbt -project $PROJECT -instance $INSTANCE read tab start=r count=2
```

The emulator seems to produce different results to this script when compared to production.
Emulator reads rows:
* `[r1, r2]`
* `[r2]`
* `[]`

Production reads rows:
* `[r1, r2]`
* `[r2, r3]`
* `[r3]`

Arbitrary sleeps can be introduced and it still produces the same results, so it doesn't seem to be timing dependent

This difference can also be seen when running code using the java `bigtable-client-core:1.6.0` client library.
The result after a `readRowsAsync` request exactly matches the result from cbt.

## Client

cbt

## Describe Your Environment

MacOS using Docker Desktop (Version 2.0.0.0-mac78 (28905))
Google Cloud SDK 226.0.0
alpha 2018.11.09
beta 2018.11.09

## Expected Behavior

That reading with a limit would return all rows up to the limit

## Actual Behavior

Reading with a limit in the presence of deleted rows returns fewer (possibly no rows).

**Comment by enocom** [comment]
Thanks for the detailed bug report. I'll be working on a fix.
