### ISSUE TITLE
README: remove godoc.org from package names

### ISSUE THREAD

**Issue by bradfitz** [googleapis/google-cloud-go#1245]
README.md has a table of packages linking to godoc.org for docs. Linking to godoc.org is fine, but you should remove the "godoc.org/" prefix from the "Package" name in the link. The godoc.org part isn't part of the package name.

**Comment by Lyon555** [comment]
good to know.  thanks.now they will work with me, not against I.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/36130
