### ISSUE TITLE
storage: GenerationMatch = 0 produces error

### ISSUE THREAD

**Issue by eriklott** [googleapis/google-cloud-go#1246]
The [google storage documentation](https://cloud.google.com/storage/docs/object-versioning) suggests:

> If you set a generation-match precondition to 0 when uploading an object, Cloud Storage performs the specified request only if there is no live version of the object. 

When using the "cloud.google.com/go/storage" package in go, I expect that writing to a new object with the GenerationMatch condition to set 0 will succeed and preventing us from overwriting any existing objects in the bucket.

Instead, I'm getting a `storage: NewWriter: empty conditions` error when the GenerationMatch condition to 0.

    client, _ := storage.NewClient(ctx)
    w := client.
        Bucket("mybucket").
        Object("mykey").
        If(storage.Conditions{GenerationMatch: 0}).
        NewWriter(ctx)
     
    io.Copy(w, src)
    err := w.Close()
    // returns error "storage: NewWriter: empty conditions"

Can you guys find a way to interpret the 0 value as an intentional value, rather than a missing zero value? Thanks

**Comment by eriklott** [comment]
Thanks. I missed the 'DoesNotExist' field in the docs, and that's what we need.

**Comment by frankyn** [comment]
I learned something new thanks @eriklott for updating the issue!

**Comment by jadekler** [comment]
Ah, I also missed that field. Doh. Thanks for updating the issue. :)
