### ISSUE TITLE
pubsub: Seeing many failed acks despite large MaxExtension and Synchronous

### ISSUE THREAD

**Issue by fastest963** [googleapis/google-cloud-go#1247]
## Client

PubSub

## Describe Your Environment

fa2eb35 on GCE CentOS 7

## Expected Behavior

See very minimal failed acks because expired.

## Actual Behavior

Seeing lots (as in greater than 50%) of failed acks because expired.

Settings:
```
sub.ReceiveSettings.MaxOutstandingMessages = 3
sub.ReceiveSettings.MaxExtension = time.Hour
sub.ReceiveSettings.NumGoroutines = 1
sub.ReceiveSettings.Synchronous = true
```

The Ack Deadline for this subscription is 10 seconds.

Number of ack'd jobs per minutes:
![image](https://user-images.githubusercontent.com/112555/49671658-9765a880-fa36-11e8-814e-a5a3a67861bd.png)

Number of failed ack's because expired (via stackdriver) per minute:
![image](https://user-images.githubusercontent.com/112555/49671611-7c933400-fa36-11e8-8a75-b34437a17013.png)

We're ack'ing ~100/minute and stackdriver is reporting that 50-70 of those are ultimately being ignored because the deadline expired.

Time-to-ack 95th percentile:
![image](https://user-images.githubusercontent.com/112555/49671733-cc71fb00-fa36-11e8-91b8-73f1c6f50f42.png)

For some reason there's only ~20 ModAcks being sent per minute:
![image](https://user-images.githubusercontent.com/112555/49671960-93865600-fa37-11e8-824f-f3e9db032413.png)

But since the 50th percentile is <20 seconds maybe it's finishing quick enough not to warrant a modack?

We're acking most messages in less than a minute and since we have `MaxExtension` set to an hour I'd assume we'd have relatively 0 failed acks.

I'll be testing to see what happens if I disable Synchronous and if I increase the Ack Deadline to 60 seconds on the subscription.

**Comment by fastest963** [comment]
Increasing the subscriptions Ack Deadline to 60 seconds has lowered the failed Ack count to only ~10/minute but I had thought that ModAck's should make it somewhat irrelevant what the actual deadline is so I'm still inclined to think this is a bug.

**Comment by jadekler** [comment]
@fastest963 Thanks for reporting this. Did this happen recently? Is there something that could have caused this, like a dependency upgrade?

We shipped https://code-review.googlesource.com/c/gocloud/+/36050 yesterday: is it possible you have this commit? If so, could you try one commit before and see if that commit

**Comment by fastest963** [comment]
@jadekler I tried downgrading to v0.33.1 and I'm still having the issue. I'm going to try setting Synchronous to false and see if that helps.

**Comment by fastest963** [comment]
I disabled `Synchronous` and it actually made the problem worse. Now we have 0 ack's succeeding and 100% of them failing because of expired.

**Comment by jadekler** [comment]
> We're ack'ing ~100/minute and stackdriver is reporting that 50-70 of those are ultimately being ignored because the deadline expired.

The ack deadline, or the (gRPC) request deadline? Could you describe what "Failed Pull Ack Requests" is measuring?

> For some reason there's only ~20 ModAcks being sent per minute:

We send an initial modack when a message (or batch of messages) is received. Furthermore, we send modacks to extend the lease whilst processing is happening. [In v0.26.0 we change this to use a percentile distribution](https://github.com/googleapis/google-cloud-go/releases/tag/v0.26.0) based on the time-to-ack to determine how frequently to send modacks. Ideally, each message would only have a single modack, since the percentile can accurately guess how much time you'll need. Rarely should you get more than one modack per message. So, the fact that you're only seeing 20 per minute is not strange to me.

> I disabled Synchronous and it actually made the problem worse. Now we have 0 ack's succeeding and 100% of them failing because of expired. If I look at the ModAck count, I see all of them succeeding and the rate of ModAck's now is matching the rate of Ack's so it seems like this fixed the "issue" of the ModAck's not matching the count of messages.

What version did you upgrade from to see this problem? Is it possible to help us binary search this, or provide any additional details? Apart from the aforementioned change, [there hasn't really been much change in pubsub](https://github.com/googleapis/google-cloud-go/commits/master/pubsub).. 🤔

Also, I tried and failed to reproduce this with a very small, contrived example. I saw pretty steady acks (~120,000 per minute) before it plowed through all the messages in its topic.

![screen shot 2018-12-10 at 2 27 12 pm](https://user-images.githubusercontent.com/3584893/49767009-c759b980-fc8b-11e8-8a27-18627503d4cc.png)

(undelivered didn't drop to 0 because another topic has messages)

I probably don't have the same environment as you, though. Just adding a data point.

**Comment by fastest963** [comment]
> The ack deadline, or the (gRPC) request deadline? Could you describe what "Failed Pull Ack Requests" is measuring?

Specifically I'm using the stackdriver metrics to know how many failed ack requests there are.
```
subscription/streaming_pull_ack_message_operation_count{response_code="expired"}
```
I assume that's measuring the ack deadline. To be clear, we're not getting any errors back from the client, we're just noticing them via the stackdriver metrics and because we are seeing a large amount of duplicated messages.

The change to a distribution might have been the issue. Let me try going to an older version than v0.26.0 and see if I have the same problem. Let me try and also produce a simple test case. I can imagine the problem might arise because 50% of our jobs take less than a second but the 95th percentile is over a minute.

**Comment by jadekler** [comment]
Ah! TIL that you can specify response code. For my short reproduction, it seems none expired. Also, FWIW, my expectation is that the distribution should have no affect - if a message lasts longer than the distribution thought it would, it simply results in two (or more) modacks instead of one. All that said, thanks for digging further, very interested to hear what you find out and get to the bottom of this.

**Comment by fastest963** [comment]
Here's a reproduction script that actually causes more `expired` than `success`:
https://gist.github.com/fastest963/ad5f14e20cc624b9fc388712649d7839

Running that on a single `n4-standard-4` in `us-east1-c` prints out:
```
~ INFO -- count received last minute -- count="319"
~ INFO -- count received last minute -- count="518"
~ INFO -- count received last minute -- count="466"
~ INFO -- count received last minute -- count="501"
~ INFO -- count received last minute -- count="464"
~ INFO -- count received last minute -- count="510"
~ INFO -- count received last minute -- count="515"
~ INFO -- count received last minute -- count="497"
~ INFO -- count received last minute -- count="494"
~ INFO -- count received last minute -- count="508"
~ INFO -- count received last minute -- count="503"
~ INFO -- count received last minute -- count="510"
~ INFO -- count received last minute -- count="477"
~ INFO -- count received last minute -- count="491"
~ INFO -- count received last minute -- count="512"
~ INFO -- count received last minute -- count="504"
~ INFO -- count received last minute -- count="481"
~ INFO -- count received last minute -- count="508"
~ INFO -- count received last minute -- count="503"
~ INFO -- count received last minute -- count="490"
~ INFO -- count received last minute -- count="493"
~ INFO -- count received last minute -- count="472"
~ INFO -- count received last minute -- count="515"
~ INFO -- count received last minute -- count="496"
```

and the metrics from:
```
subscription/pull_ack_message_operation_count
```
![image](https://user-images.githubusercontent.com/112555/49825729-1fa7be80-fd53-11e8-8589-f0ba401b1679.png)

(Red is expired and Green is success)

For some reason this is exacerbating the issue and only 100/minute ack's are successful and almost 400/minute are failing. This was testing with the latest gocloud commit (411f10768a0b30e6f400faf6b7d67b17f2d05f2f).

**Comment by jadekler** [comment]
Hmmm... something fishy is going on. I ran that script (thank you for providing it) and did see _some_ expired, though not nearly as many as you. Setting NumGoroutines=100 (and Sync=false, though I think NumGoroutines did it) seemed to drop it the expired messages to 0. See:

![screen shot 2018-12-11 at 4 04 52 pm](https://user-images.githubusercontent.com/3584893/49838313-f7be5800-fd5e-11e8-9ce9-50d0347b49f6.png)

Is there a reason you're using NumGoroutines=1?

Also, this might be a good time to have one of the pub/sub folks take a look at your project and see if anything funky is going on. Would you like us to do so? If so, could you email me your project ID? I have one for you already, but probably good to re-send it just to make sure we know for-sure we're talking about the same project. :)

**Comment by fastest963** [comment]
I'll send you an email with the projectID and the subscription. We were using `NumGoroutines=1` for most of our subscriptions since it is the default (also for a lot of our subscriptions we only see a few messages a minute). For higher throughput subscriptions we set it higher.

I retried it with the same setup as you but I'm still seeing the number of expired be super high. There must be something wrong with the project or the region or something. I started with `NumGoroutines=1` and then changed to `NumGoroutines=100` but left `Synchronous=true` both times. It seems to be fine for a minute or two and then it switches to failing more than succeeding.
![image](https://user-images.githubusercontent.com/112555/49845219-d330a300-fd93-11e8-859c-bd769be07452.png)
I switched at the dip around the 20th minute from 1 to 100 NumGoroutines.

Also, what flags did you run the script with, I saw your y-axis was over 6,000 but with the 1-120 second sleep and default of 500 consumers it shouldn't be able to do much more than 500/minute.

**Comment by jadekler** [comment]
Good spot. It turns out I had a subscriber running in some k8s cluster. I am seeing this issue as well. Preliminary results indicate it is related to high modack values (which the distribution is happy to provide). Labeling as bug and investigating.

**Comment by jadekler** [comment]
We've honed in on the bug and got a reliably passing integration test. While we work on a solution, please pin to v0.26.0. We hope to have this fixed soon!

**Comment by jadekler** [comment]
@fastest963 Could you try https://code-review.googlesource.com/c/gocloud/+/36430 and let me know if this solves your issue?

Also, I'm only able to reproduce this in `Synchronous=true` mode. In https://github.com/googleapis/google-cloud-go/issues/1247#issuecomment-445948155 you mention that `Synchronous=false` made it _worse_. Could you confirm that? I'm not seeing this behavior. 🤔 Certainly happy to keep digging though!

**Comment by fastest963** [comment]
@jadekler it looks like that fixed it! I'm seeing 100% success rate now. I tried turning off Synchronous again and I can't reproduce what happened before. I'll open a new bug if I can get it to happen since it seems like your fix for `Synchronous=true` works great.

**Comment by jadekler** [comment]
Wonderful news! Thanks a million for testing. Hope to have this fix out soon.

**Comment by dsymonds** [comment]
I'm observing a similar poor behaviour, with `MaxOutstandingMessages=1` (though same happened with bigger numbers), and `Synchronous=false`, on messages that sometimes but not always take a long time to process (e.g. multiple minutes, but comfortably under 10m). My code under `Receive` returns and calls `m.Ack()`, but I see the same that @fastest963 observed: fine at the start of the program, then it switches to always yielding an expired status code.

I'm running at HEAD. It's only started happening, as far as I can tell, over the last little while. I didn't observe any issues last year, but I also can't see any changes to the pubsub part of this repo since your fix above.

**Comment by dsymonds** [comment]
FYI, I tried pinning to `v0.26.0` and it didn't help.

**Comment by jadekler** [comment]
@dsymonds If these long-processing messages exceed their deadline, then it is intended behavior that the ack should fail.

More context: with Synchronous=false, receive gets batches of messages at a time. If the client receives 100 messages but you're only processing one at a time, it's possible that you'll only get through 30 (for example) before their deadline is up and then ack->fail 70 the rest.

If you set Synchronous=true, no more than `MaxOutstandingMessages` will be held in memory and I would expect you not to run into this scenario as often. https://godoc.org/cloud.google.com/go/pubsub#ReceiveSettings

**Comment by dsymonds** [comment]
The messages get nowhere near their deadline (like 3-4m vs. 10m).

However, what you say about batching with Synchronous=false does make sense. I've switched to Synchronous=true and it does appear to be running more reliably. It's strange that I never observed this last year, but maybe that's all that it was.

**Comment by jadekler** [comment]
One subtlety is that the deadline starts when we receive them, not when the user starts processing them.
