### ISSUE TITLE
logging: after upgrade to 0.33.1, logs have disappeared from the Log Viewer

### ISSUE THREAD

**Issue by jmhodges** [googleapis/google-cloud-go#1248]
(delete this for feature requests)

## Client

Logging

## Describe Your Environment

golang:1.11.2 container in GKE

## Expected Behavior

Messages go to the log in "Global" and then "howsmyssl_allowance_checks" logs as they were in the lib at commit 4e436992a513aa1dec28f8adda5c8173724d493e.

## Actual Behavior

The howsmyssl_allowance_checks log in "Global" stopped being updated. I've not been able to find the new place they are going and suspect they aren't. The logs do seem to be sent correctly as the OnError func is not being triggered except for a couple of times because of bad UTF-8 in some users' google.logging.type.HttpRequest.UserAgent which seems unrelated.

My set up code:

```
		tokSrc := googConf.conf.TokenSource(context.Background())
		client, err := logging.NewClient(
			context.Background(),
			googConf.ProjectID,
			option.WithTokenSource(tokSrc),
		)
		if err != nil {
			log.Fatalf("unable to make Google Cloud Logging client: %s", err)
		}
		client.OnError = func(err error) {
			log.Printf("goog logging error: %s", err)
		}
		gclog = client.Logger(*allowLogName)
```

and the logs are sent as

```
	gclog.Log(logging.Entry{
		Payload:     entry,
		HTTPRequest: &logging.HTTPRequest{Request: r, RemoteIP: remoteIP},
		Labels: map[string]string{
			"app":             "howsmyssl",
		},
	})

```

**Comment by jmhodges** [comment]
Here's the commit where I upgraded the google cloud libraries with the adjustment that the Log method lots its `error` return value.  https://github.com/jmhodges/howsmyssl/pull/238

The relevant code is in howsmyssl.go and allow.go

**Comment by jadekler** [comment]
Thanks for the information. It looks like you've upgraded from `cloud.google.com/go v0.0.0-20161227155656-4e436992a513` to `cloud.google.com/go v0.33.1`. This is a substantial upgrade encompassing two years of change, including a change from beta to stable (AFAICT). I'm unsurprised something changed :)

That said, I was unable to reproduce any problems. [This is my reproduction code.](https://gist.github.com/jadekler/29000fceecdea277dc4a5a31404f812b)

<img width="679" alt="screen shot 2018-12-10 at 7 55 53 am" src="https://user-images.githubusercontent.com/3584893/49744152-0ae30200-fc51-11e8-9f70-1f4afd86da1b.png">

Could you try to isolate the issue into a small code sample that reproduces the problem? That would help this investigation.

**Comment by jadekler** [comment]
We've asked some clarifying questions but have not heard back from you. Closing this issue - please feel free to ping the issue if you want to continue discussing.

**Comment by jmhodges** [comment]
Sorry about the delay. 

I changed the code to use the WithCredentialsFile (and the project id is set correctly) but there's still no logs coming into "Google Project, personal-sites-1295". https://github.com/jmhodges/howsmyssl/pull/240

Is it possible that running in GKE changes the math here, somehow? Or maybe the svc account needs more than just the Logs Writer (logging.logEntries.create) permissions to start a new log?

Interestingly, the original source for my logs was not in "Google Project, <whatever>" (as in your screenshot) but in "Global".

**Comment by jmhodges** [comment]
Oh, interesting! There is a log showing up in `gcloud logging logs list` as `projects/personal-sites-1295/logs/howsmyssl_allowance_checks` but I don't see the equivalent in the console.cloud.google.com UI!

**Comment by jmhodges** [comment]
Yeah! Using the advanced filter and `logName=projects/personal-sites-1295/logs/howsmyssl_allowance_checks` in the console site's UI gets me all of my log entries!

And it's been logging there for a while! I'm not sure how to report this bug to the console folks. Any clue?

**Comment by jmhodges** [comment]
I tossed them a feedback thing with a screenshot, but we'll see!

**Comment by jadekler** [comment]
Oh super strange. Yeah, sounds like it could be a console problem... 🤔 I think the feedback button is right, but you could also try the stackdriver issue tracker at https://cloud.google.com/support/docs/issue-trackers.
