### ISSUE TITLE
Cloud Firestore Emulator support

### ISSUE THREAD

**Issue by sinmetal** [googleapis/google-cloud-go#1249]
## Client

Firestore

## Describe Your Environment

Alpine Docker on GKE

## Expected Behavior

I like hundreds of emulators in Datastore to support Firestore emulator.

https://cloud.google.com/sdk/gcloud/reference/beta/emulators/firestore/

**Comment by sinmetal** [comment]
Like PubSub Emulator and Datastore Emulator, I would like to have a function to use the Firestore Emulator by setting values ​​in environment variables.

https://github.com/googleapis/google-cloud-go/blob/3bec1e11d6972bd04fd9a0ecbd4fcff0f5810439/pubsub/pubsub.go#L60

https://github.com/googleapis/google-cloud-go/blob/3bec1e11d6972bd04fd9a0ecbd4fcff0f5810439/datastore/datastore.go#L61


Or can I use https: //cloud.google.com/sdk/gcloud/reference/beta/emulators/firestore/ in another way?

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/36890
