### ISSUE TITLE
Duplicate Row Mutation Doesn't Return Error Wrapped by gRPC Status

### ISSUE THREAD

**Issue by jon-whit** [googleapis/google-cloud-go#1252]
## Client

Spanner

## Describe Your Environment

Alpine Docker on GKE

## Expected Behavior
I'd expect the code below to work fine...
```
// Create mutation that would lead to a duplicate row entry
mutation := []*spanner.Mutation{
   ...
}

_, err := db.Apply(ctx, mutation)
if err != nil {
    stat := status.Convert(err)
    if stat.Code() == codes.AlreadyExists {
        return nil
    }

    return err
}

```
## Actual Behavior
The error response *is not* wrapped by the gRPC status package, so the `status.Convert(...)` fails to convert the gRPC error. This should be fixed.
```
stat := status.Convert(err)
if stat.Code() == codes.Unknown {
    log.Print("Now you see the error")
} else {
    log.Print("I promise you won't see this line :)")
}
```

**Comment by jon-whit** [comment]
@jadekler Could you elaborate a bit on why this is a feature request? According to the `status` Go package, gRPC service handlers should return errors that come from the `status` package. Since this package is a package implemented by Google, it seems appropriate that a gRPC service handler written by Google should return it's own type of statuses...

This feels like a bug, not a feature.

**Comment by jadekler** [comment]
@jon-whit Apply does not guarantee return of a gRPC error, so I hesitate to call it a bug. That said, I'm in agreement that it should return the gRPC error when it can. For posterity, [this line is probably the where it's being wrapped](https://github.com/googleapis/google-cloud-go/blob/ac3720150beed4ebd66918aa31d4713110098260/spanner/client.go#L446).
