### ISSUE TITLE
Unpinned dependencies causing unexpected behavior

### ISSUE THREAD

**Issue by tevren** [googleapis/google-cloud-go#1256]
## Client
datastore

## Describe Your Environment
Docker image: golang:1.10 (debian) running on GKE.

## Expected Behavior
Background connection reestablishment happens without any incident/error.

## Actual Behavior
Every hour, datastore transactions see an increased error rate for 4-5 minutes as background token refreshes cause connection to be reset and re-established. 
I've traced bug to https://github.com/grpc/grpc-go, it was addressed in https://github.com/grpc/grpc-go/pull/2380

This issue occurred in our service even though we are using glide to pin our dependencies. We've pinned the version of this library (cloud.google.com/go), however this library doesn't pin its own dependencies. When I updated the version of cloud.google.com/go, I also pulled in updates for grpc-go which included a bug. This could have been avoided if google-cloud-go pinned its dependencies to release versions or commits. 

Could you use go dep or glide (or any dependency management tool) to pin the requirements for this library?

**Comment by jadekler** [comment]
Tracked in https://github.com/googleapis/google-cloud-go/issues/1068.
