### ISSUE TITLE
Cold Starts in Firestore

### ISSUE THREAD

**Issue by jeffreydking** [googleapis/google-cloud-go#1257]
I am seeing significant latency (10+ seconds) for the first Firestore query after periods of no use. (I have seen issues reported for other client platforms.) Is this a known issue for the Golang package as well? Is it being worked on?

**Comment by jadekler** [comment]
Could you describe your deployment environment?

**Comment by kingjeffrey** [comment]
RIght now, my code is in a local development environment. I'll have it in Kubernetes after I get some unit tests ironed out.

Local development environment is MacOS. I'm running go1.11.2 darwin/amd64.

**Comment by jadekler** [comment]
Thanks. Could you paste some code for us to look at?

Furthermore, you mentioned issues reported for other client platforms - could you link to those?

cc @mikelehen
