### ISSUE TITLE
spanner healthcheck session maintainer not maintaining enough sessions and also possible leakage

### ISSUE THREAD

**Issue by dneralla** [googleapis/google-cloud-go#1259]
## Client

Spanner

We have the following set up 

We have been observing our active session count on the cloud spanner when run for a long time more than the MaxOpened and even after hour of startup lot less than MinOpened

Below is our setup 

```
const (
	numSpannerChannels = 15
	maxSpannerSessions = numSpannerChannels * 100
	// num sessions which health check maintainer makes sure it keeps active
	minSpannerSessions     = 500
	maxSpannerSessionBurst = 100
	spannerWriteSessions   = 0.05 // keep 5% of sessions warmed for writes
)

client, err := spanner.NewClientWithConfig(ctx, dbPath,
	spanner.ClientConfig{NumChannels: numSpannerChannels, SessionPoolConfig: spanner.SessionPoolConfig{
		MaxOpened:     maxSpannerSessions,
		MinOpened:     minSpannerSessions,
		MaxBurst:      maxSpannerSessionBurst,
		WriteSessions: spannerWriteSessions,
	}})
```
  
We have 40 pods running the client code like the above and our spanner instance has 10 nodes.
Some times total session count exceeds 100k and some times its below 9k.

According to min and max config it should be between 20k to 60k. This is the only place from which that database is accessed too.

By looking at session.go in spanner client library it seemed like healthCheckMaintainer should be maintaining atleast MinOpened sessions. We are also closing the created client on the shut down of the pod.(and on redeploy we observe sessions being deleted)

I could not figure out from session.go where the leakage could happen and why replenishPool wouldn't maintain the MinOpened Sessions. I also checked the latencies of GetSession  if we need to increase any health check workers. p99 around 30ms. which means around 33 per sec and 33 * 300 for 5 minute interval and its well above the MaxOpened so I didn't see the reason to increase the workers too. Is there some known session leakage problem going on or no one reported yet?  or do you think there is something wrong with our above setup?

+ @jadekler.

**Comment by dneralla** [comment]
To give more info to you I also exported the opensession_count metric from client libraries to  stackdriver. And in the initial 1 hr you can see number of sessions were only 200 where as my MinOpened configuration is 600. I ll also post the metric when it gets to more than MaxOpened.

<img width="972" alt="screen shot 2018-12-14 at 5 38 27 pm" src="https://user-images.githubusercontent.com/2191033/50037533-3b1aff80-ffc7-11e8-8b15-4a645824ea13.png">

**Comment by dneralla** [comment]
According to the default configuration healthcheck maintainer should be running every 1 minute to make sure we have atleast MinOpened Sessions.

**Comment by jadekler** [comment]
@dneralla I think I've found the issue. Would it be possible to try https://code-review.googlesource.com/c/gocloud/+/36711?
