### ISSUE TITLE
versionClient should only be updated for clients that have changes

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#1262]
Copied from [gapic-generator #2485](https://github.com/googleapis/gapic-generator/issues/2485) as the change belongs here.

Only client libraries that have an actual change should have their `versionClient` field updated.

**Comment by jadekler** [comment]
Fixed in https://github.com/googleapis/google-cloud-go/commit/3bec1e11d6972bd04fd9a0ecbd4fcff0f5810439
