### ISSUE TITLE
firestore: support a field mask for GetAll

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#1266]
The Firestore client spec states that the GetAll method takes an optional list of fields to retrieve. The Go client doesn't have this feature.

It would be a breaking change to add it to `Client.GetAll`, so it should be a new method, 
```
Client.GetAllWithFields(ctx, []*DocumentRef, fields []interface{}) ([]*DocumentSnapshot, error)
```
where each element of `fields` is either a string or a `FieldPath`.

**Comment by jadekler** [comment]
Tracked in internal bug 120085151. Also, since firestore is beta, I think we have the option of breaking the current GetAll API. But, whether or not that's a good idea is another discussion... Closing this for now, let's continue the conversation in 120085151.
