### ISSUE TITLE
firestore: order by __name__ with field value cursor generates invalid Resource name for sub-collections

### ISSUE THREAD

**Issue by marcin-ptaszynski** [googleapis/google-cloud-go#1271]
## Client

Firestore

## Describe Your Environment

Attempting to run following code - note use of sub-collection:
```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/firestore"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()
	fsc, err := firestore.NewClient(ctx, "<project-id>", option.WithCredentialsFile("credentials.json"))
	if err != nil {
		panic(err)
	}

	query := fsc.
		Collection("namespaces/test/cities").
		OrderBy("__name__", firestore.Asc).
		StartAt("london").
		Limit(3)
	docs, err := query.Documents(ctx).GetAll()
	if err != nil {
		panic(err)
	}

	fmt.Printf("got %d results\n\n", len(docs))

	for _, doc := range docs {
		fmt.Println(doc.Data())
	}
}
```

## Expected Behavior

results starting from "london" are fetched from db and printed

## Actual Behavior

`/documents` is prepended twice by go client library (once for database and once for sub-collection), which results in invalid document reference string and following error:
```
rpc error: code = InvalidArgument desc = Resource name "projects/dev01-220700/databases/(default)/documents/namespaces/test/documents/cities/london" lacks "/" at index 91.
```

**Comment by jadekler** [comment]
Hello! We've asked some clarifying questions but haven't heard back from you. We're going to close this issue, but if you would like to continue the conversation please ping back and we can re-open.

**Comment by marcin-ptaszynski** [comment]
Hi @jadekler , my apologies for not replying earlier, issue was occurring in v0.31.0. I've confirmed that latest v0.36.0 is free from this bug. Thanks!

**Comment by jadekler** [comment]
@marcin-ptaszynski Great to hear! :)
