### ISSUE TITLE
Datastore.Key.Decode() is not compatible with google.golang.org/appengine/datastore.Key.Encode()

### ISSUE THREAD

**Issue by goog-lukemc** [googleapis/google-cloud-go#1272]
In a  multi service appengine environment services write to (memcache, taskq, gcs) and rely on the results of google.golang.org/appengine/datastore.Key.Encode() to target specific datastore entities for processing.  The cloud.google.com/go/datastore SDK uses a different protobuf type and doesn't encode to the same string making forward and backward compatibly between Key.Decode() functions incompatible.  This slows adoption of the new lib and presents compatibility issues with appengine flex, GKE and GCE services that use cloud.google.com/go/datastore SDK.

- [Encode/DecodeKey in cloud.google.com/go](https://github.com/googleapis/google-cloud-go/blob/15dc68d11f3fc3f1a30824af6a107546b2ae2158/datastore/key.go#L195-L227)
- [Encode/DecodeKey in google.golang.org/appengine](https://github.com/golang/appengine/blob/e9657d882bb81064595ca3b56cbe2546bbabf7b1/datastore/key.go#L228-L261)

**Comment by Deleplace** [comment]
Despite what the doc says ([here](https://godoc.org/cloud.google.com/go/datastore), generated from [this file](https://github.com/googleapis/google-cloud-go/blob/f35fa89a7117b680d7eafbded858d35d5d59a30c/datastore/doc.go)), cloud.google.com/go/datastore.Key does not contain an application ID.

Thus the old Key and new Key types are not equivalent. Working with them at the same time and converting between them would need to explicitly take the "AppID" question into account.

**Comment by broady** [comment]
It sounds like we should figure out if we can seamlessly decode the GAE-style.
If not feasible or not a good idea (too much magic?), then provide a way to convert between the two encodings.

Is there any precedence in other language runtimes? What does Java do?

**Comment by enocom** [comment]
@goog-lukemc Would you mind updating the issue with what you've found?

**Comment by trueselfco** [comment]
https://github.com/googleapis/google-cloud-python/issues/3293  This is the same problem in python.   They resolved this by creating from_legacy_urlsafe and to_legacy_urlsafe.  https://github.com/googleapis/google-cloud-python/blob/master/datastore/google/cloud/datastore/key.py

**Comment by jadekler** [comment]
I believe this is now fixed. Closing this, but let me know if I'm wrong about that.

**Comment by luigitni** [comment]
@jadekler Hi, can I ask how and what version fixes this issue?
We encounter this right today using  the version 1.0.0 of the cloud.google.com/datastore package which still encodes and decodes differently from google.golang.org.
This completely breaks compatibility making it impossible to update some applications to the client library, which is a critical issue.
Is this still on the roadmap? If not, would it be possible to provide documentation on how to roll an own solution to keep make the library backward compatible?

**Comment by jadekler** [comment]
@luigitni Would you mind opening a new issue with details about the problem you've seen? We can link to this issue for context. This thread is quite old and I'd rather not ping everyone on it.
