### ISSUE TITLE
How to retrieve account name using Gcloud Go library?

### ISSUE THREAD

**Issue by waterskater** [googleapis/google-cloud-go#1276]
I am trying to implement the below gcloud command in Go Lang (without shelling out and running gcloud)

gcloud config get-value account
abc@def.com

I have looked in "https://godoc.org/cloud.google.com/go", but I am unable to find how I could implement this. Any ideas?

**Comment by jadekler** [comment]
This is not functionality the client library exposes, unfortunately. I _believe_ that gcloud reads some config file on the filesystem. I would imagine that you could discover where that file exists, and then just use the Go stdlib's file reading libraries to read and parse that file (I assume it's json or something easily readable).
