### ISSUE TITLE
Can't compile basic Firestore client

### ISSUE THREAD

**Issue by dbolkensteyn** [googleapis/google-cloud-go#1277]
Apologies if I am missing something obvious - I am new to Go.

## Client

Firestore

## Describe Your Environment

* `go version go1.10.3 darwin/amd64`
* `$GOPATH/src/cloud.google.com/go` is at commit 105f0564f8d67e66e7ea5ecc5a6e46dad440aa09
* `$GOPATH/src/google.golang.org/genproto` is at commit 2a72893556e4d1f6c795a4c039314c9fa751eedb

Trying to build this code:
```
package main

import (
	"context"
	"cloud.google.com/go/firestore"
)

func main() {
	ctx := context.Background()
	firestore.NewClient(ctx, "projectID")
}
```

## Expected Behavior

Successful compilation

## Actual Behavior

```
../../../cloud.google.com/go/firestore/docref.go:410:19: undefined: "google.golang.org/genproto/googleapis/firestore/v1beta1".DocumentTransform_FieldTransform_AppendMissingElements
../../../cloud.google.com/go/firestore/docref.go:451:19: undefined: "google.golang.org/genproto/googleapis/firestore/v1beta1".DocumentTransform_FieldTransform_RemoveAllFromArray
../../../cloud.google.com/go/firestore/query.go:486:8: undefined: "google.golang.org/genproto/googleapis/firestore/v1beta1".StructuredQuery_FieldFilter_ARRAY_CONTAINS
```

**Comment by dbolkensteyn** [comment]
Rebased genproto to db91494dd46c1fdcbbde05e5ff5eb56df8f7d79a and it worked. Closing.

**Comment by jadekler** [comment]
Glad you got it working! FWIW we're doing our best to pin dependencies in our go.mod, so you should be able to use that as a way to avoid this problem in the future.
