### ISSUE TITLE
Datastore documentation is outdated

### ISSUE THREAD

**Issue by mihaiav** [googleapis/google-cloud-go#1278]
I'm trying to adapt a 2 years old project to the new datastore client library. A lot of breaking changes there....Can someone at least keep the documentation up to date? There is no "interator.Done" error defined. 
`` Next returns the key of the next result. When there are no more results, iterator.Done is returned as the error. ``
https://godoc.org/cloud.google.com/go/datastore#Iterator.Next

**Comment by jadekler** [comment]
Sorry for the confusion. `iterator.Done` is defined at https://godoc.org/google.golang.org/api/iterator#pkg-variables.
