### ISSUE TITLE
spanner: Open session count view

### ISSUE THREAD

**Issue by lc-caigwatkin** [googleapis/google-cloud-go#1279]
What is the recommended alternative to the open session count view removed from the spanner package?

In the latest release v0.35.0 the opencensus view `OpenSessionCountView` was moved from the `cloud.google.com/go/spanner` package to the `cloud.google.com/go/spanner/internal/trace` package, meaning it is no longer visible to our code that configures our opencensus statistics.

This view has been a very useful diagnostic tool for us, providing a view of the open spanner sessions grouped by instance. It has allowed us to pinpoint bugs in our usage of the spanner package and continues to be a useful view of how each microservice instance behaves with spanner. It would be appreciated if there were some alternative to this view now that it has been moved to an internal package of the spanner library.

Thanks!

**Comment by jadekler** [comment]
Reverting that change. Apologies for the disruption. We'll cut a 0.35.1.

**Comment by lc-caigwatkin** [comment]
Thanks @jadekler that will allow us to upgrade as soon as that's changed!

**Comment by jadekler** [comment]
@lc-caigwatkin Thanks for reporting this. We're waiting for CI to finish running and then we'll cut a 0.35.1.

**Comment by jadekler** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/v0.35.1
