### ISSUE TITLE
datastore: unflake TestTransaction integration_test.go

### ISSUE THREAD

**Issue by enocom** [googleapis/google-cloud-go#1282]
```
=== RUN   TestTransaction
--- FAIL: TestTransaction (5.26s)
    integration_test.go:1016: 3 attempts, 3 conflicts: got err rpc error: code = InvalidArgument desc = transaction closed, want datastore: concurrent transaction
```

**Comment by havardk** [comment]
I believe that the cause of this error is that datastore sometimes return DEADLINE_EXCEEDED on transaction commit, but the transaction can complete anyway.  The RPC client will retry deadline exceeded errors (https://github.com/googleapis/google-cloud-go/blob/master/datastore/client.go#L107).  If the transaction already is complete we get this "transaction closed" error on retry.

I'm not sure how to handle this best.  As far as I can tell the result of the transaction is lost if this happens.

**Comment by jadekler** [comment]
This is now called `TestIntegration_Transaction`, FYI.

**Comment by jadekler** [comment]
Can't repro. Please re-open if you experience this issue.
