### ISSUE TITLE
spanner: unflake TestTakeFromWriteQueue

### ISSUE THREAD

**Issue by enocom** [googleapis/google-cloud-go#1283]
```
--- FAIL: TestTakeFromWriteQueue (1.00s)
    session_test.go:704: write queue unexpectedly empty
```

https://source.cloud.google.com/results/invocations/d0b7094c-c71b-4185-9e95-687944d73b58

**Comment by olavloite** [comment]
Caused by the SessionPool maintainer that sometimes cleans up the session before it is taken from the queue. Fixed by https://code-review.googlesource.com/c/gocloud/+/40151

**Comment by odeke-em** [comment]
Just encountered a flake https://source.cloud.google.com/results/invocations/273cee0a-0bba-4140-965d-c3f302eddf72/targets/tests/tests
