### ISSUE TITLE
pubsub: Delete returns error on successful delete

### ISSUE THREAD

**Issue by breznik** [googleapis/google-cloud-go#1286]
I am creating a subscription programmatically via the pubsub client, and when I take the same subscription and call `.Delete(ctx)`, it's returning an error:
rpc error: code = NotFound desc = Resource not found (resource=my-subscription-name-here).

When I check Google Cloud Console, I can see that the subscription is successfully created for the topic. After I call delete, even though it returns the above error, it still successfully deletes the subscription as well. I would expect it to not return an error when successfully deleting the subscription.

## Client

PubSub

## Describe Your Environment

Alpine Docker
Using cloud.google.com/go tagged release v0.35.1

## Expected Behavior

Subscription successfully deleted, err returned should be nil.

## Actual Behavior

err is not nil and contains above error.

**Comment by jadekler** [comment]
@kolea2 @kamalaboulhosn have y'all seen anything like this? Feels like a backend-y error, potentially?

**Comment by breznik** [comment]
My code is not that dissimilar from your trivial example, but I'll have to see if I can extract it to share. One key difference might be that after creating the `sub`, I invoke `sub.Receive(..)` before I call `sub.Delete(..)`.

**Comment by jadekler** [comment]
@breznik Any updates? Do you think you could provide us a reproduction?

**Comment by breznik** [comment]
I've not been able to isolate and produce a shareable code example that replicates this, but I am still experiencing this issue, both with code I have running locally in docker and also in GKE. It's possible I have something going on with one go-routine creating the sub and another one trying to delete it (but not at the same time).

**Comment by breznik** [comment]
Since I see this in GKE, is this something that would be worth having me create a support ticket in GCP, since perhaps the support person would be able to capture more info from the live environment?

**Comment by jadekler** [comment]
I imagine that goroutine interaction is the culprit. Without a reproduction, I'm not sure that we or they would be able to accurately debug... :/ Would you feel comfortable sharing code with the GCP support team? If so, then I would recommend you towards that tracker.

**Comment by jadekler** [comment]
We've asked some clarifying questions but haven't heard from you in a while. Closing this for now. Let me know if you'd like to continue the discussion, though!

**Comment by draeder** [comment]
I have this same issue in node.js. It seems to be a race condition of some kind.
