### ISSUE TITLE
bigquery: use sql.Scanner if implemented

### ISSUE THREAD

**Issue by buyology** [googleapis/google-cloud-go#1287]
We have quite a few custom types that we use with other databases, that implement `sql.Scanner` (and `driver.Valuer` for that matter). 

It would be handy if, when passing a struct pointer to the `Next`-method, it could check if a field implements `sql.Scanner` and use that if so.

**Comment by meredithslota** [comment]
Closing in favor of https://github.com/googleapis/google-cloud-go/issues/2197
