### ISSUE TITLE
Pub/Sub client does not implicitly get project ID from GCP environment/GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by stewblr** [googleapis/google-cloud-go#1289]
Note: this may apply to clients beyond the Pub/Sub client.

If I look at [this sample](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/pubsub/pubsub_quickstart/main.go), it looks like I need to explicitly provide the project ID. I have confirmed that removing the projectID argument passed to NewClient results in a compilation failure:

```
./main.go:19:40: not enough arguments in call to "cloud.google.com/go/pubsub".NewClient
        have (context.Context)
        want (context.Context, string, ...option.ClientOption)
```

Should this project ID not be picked up automatically from GOOGLE_APPLICATION_CREDENTIALS or from the deployed App Engine/Cloud Functions environment?

**Comment by steren** [comment]
All GCP compute environments expose a [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata). this is true on Compute Engine, App Engine, Cloud Functions.

The Go client library should be using it to determine the current project ID.

**Comment by mchmarny** [comment]
+1 on not requiring it... 

But, Ideally, the client would, 1) check for presence of specific env var to allow devs to explicitly oceride 2) fall back to check for gcloud to derive project 3) fall back to use metadata server

Option 1 for example when using PubSub and Firestore from non-GCP compute runtime (eg Edge IoT)

Option 2 is important for when you are connecting to GCP services from for example local machine.

PS. GitHub gives only 2 lines to enter all this text on phone so appologies for formatting

**Comment by steren** [comment]
I am not on the client library team, but I have talked anough to them to understand the recommendation.
@mchmarny, your comment is not correct:

Point 2) should not be "fall back to check for gcloud", but use the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. 
Locally, GCP developers are invited to use a service account and to create this env var. See [this page](https://cloud.google.com/docs/authentication/getting-started) for more details.  

This is captured in the issue title.

@JustinBeckwith can you help fixing the libraries that are asking for explicit project ID?

**Comment by jadekler** [comment]
Hello! We intentionally require project ID in the Pub/Sub and other clients. It's possible to add another constructor that does not require it, but we cannot change the existing constructor (breaking changes to stable clients are not allowed). I think this request is a topic for the larger Yoshi team - please send an email to yoshi-team@ and let's discuss further there.

**Comment by mchmarny** [comment]
I think the essenes of what I was trying to communicate was that the project ID discovery needs to work outside of GCP compute platforms as well. Whatever order, as long as opeque to the developer with an ability to override when needed.

**Comment by jadekler** [comment]
I'm not entirely sold on the idea of auto-configuration, but as mentioned let's discuss as a team. I think our TL is probably the best suited to talk on this subject.
