### ISSUE TITLE
What exactly does filling the log entry operation struct do on Stackdriver?

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-cloud-go#1291]
https://godoc.org/google.golang.org/genproto/googleapis/logging/v2#LogEntryOperation

What happens if I set the ID, producer, first or last on stackdriver? I can't seem to find their concrete affects documented anywhere.

**Comment by jadekler** [comment]
cc @dazuma @munangst

**Comment by dazuma** [comment]
[`LogEntryOperation`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntryOperation) is a way to group logs related to a larger semantic task (usually some kind of long-running operation). After tagging log entries with a particular operation, you can use [advanced filters](https://cloud.google.com/logging/docs/view/advanced-filters) in the logging UI to find and view logs associated with that operation. In particular, the Stackdriver backend indexes the `id` field of `LogEntryOperation` so searches for a particular operation should be fast.

**Comment by jadekler** [comment]
Closing since this seems to be answered. Let us know if you'd like to continue discussing.

**Comment by nhooyr** [comment]
What about the first and last fields?

**Comment by nhooyr** [comment]
Ah, interesting. So does Stackdriver group logs by the operation ID? This would really simplify correlating logs as right now its a process. See #1290

**Comment by rogerhub** [comment]
I think grouping by trace (#1290) and grouping by operation (this issue) are orthogonal, although I'm unsure of the semantic differences.

**Comment by nhooyr** [comment]
I just tested, the UI does not appear to group logs by operation ID nor does it show the first of operation and last of operation. If this is unexpected behaviour, I can put up some code that reproduces for me.

**Comment by munangst** [comment]
The `First of <ID>` ... `Last of <ID>` behavior mentioned above is currently only for App Engine request logs.

**Comment by jadekler** [comment]
Looks like this question has been answered. Closing for now - give a shout if you have further questions!
