### ISSUE TITLE
logging: what fields are special in the proto entry payload?

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-cloud-go#1293]
E.g. the value of the `message` field in the proto payload comes up in the UI as the main line of the log.

What other special fields are there?

**Comment by jadekler** [comment]
cc @dazuma @munangst

**Comment by munangst** [comment]
Currently the `message` field is the only JSON field treated specially. The other special behavior is that if your log entry has `httpRequest` populated, the summary will be rendered as an HTTP access log. If you want to customize the fields shown in the summary, you can do this using the [custom fields](https://cloud.google.com/logging/docs/view/overview#custom-fields) config option in the UI.

**Comment by nhooyr** [comment]
Awesome, thanks.
