### ISSUE TITLE
purpose of location in a logging entry?

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-cloud-go#1297]
Doesn't seem to show up in the Stackdriver UI.

See https://github.com/googleapis/google-cloud-go/blob/b2f67320b4ef8ea4a3b762e54394254d11fa2844/logging/logging.go#L605

**Comment by munangst** [comment]
Currently it's not used for much, although you can use [custom fields](https://cloud.google.com/logging/docs/view/overview#custom-fields) to add the the file, line number, etc. to the log entry display. In the future we may add features that take advantage of this field, like automatic linking to source code, and grouping by source location in the Errors page.

**Comment by nhooyr** [comment]
Future features sounds good.

It doesn't appear in the stackdriver UI at all for me. Like according to the UI, its not part of the entry, it doesn't exist.

**Comment by munangst** [comment]
Interesting, I'm sorry to hear that. It does work in my project but I'll investigate to see if we can reproduce the issue. Which sub-fields of sourceLocation are you populating?

**Comment by nhooyr** [comment]
Just tested, it started working for me. Not sure what happened before. Probably just my own mistake.
