### ISSUE TITLE
bigtable: Bigtable client outside of GAE request context

### ISSUE THREAD

**Issue by kmeelu** [googleapis/google-cloud-go#1298]
## Client

Bigtable

## Describe Your Environment

Appengine Standard Env

## Description

I'm attempting to retain a long-living Bigtable client that outlives the context of any one AppEngine request (running GAE with go runtime in standard environment). The issue I run into here is that the creation of a new Bigtable client uniquely requires a context, which on Appengine Standard, is associated with a single request (attempting to reuse that context results in Bigtable client errors related to the outdated context). See https://godoc.org/cloud.google.com/go/bigtable#NewClient for more details.

As such, is it required that every Request needs to open a new Bigtable client? Wouldn't this be a significant performance issue? Are there limits to number of open clients?

Any info/advice is much appreciated.

**Comment by jadekler** [comment]
cc @sduskis @igorbernstein2

**Comment by sduskis** [comment]
@garye do you have any "context" about this question?

**Comment by sduskis** [comment]
@jadekler, this seems like a question that's orthogonal to Cloud Bigtable.  I did a quick perusal of other product's golang clients, and they too use `ctx context.Context`.  Therefore, I don't think that the Cloud Bigtable team should own this issue.

**Comment by broady** [comment]
This is possible using the "second generation" Go 1.11 runtime (currently in beta).

It is not possible in previous versions of the runtime.
Additionally, in the older runtime, gRPC connections (as used by the bigtable client) use the [Socket API](https://cloud.google.com/appengine/docs/standard/go/sockets/), which has no SLA.

Hope that helps.

**Comment by broady** [comment]
Sorry, just to elaborate quickly, in second gen you can do something like this...

```
package main

var bt *bigtable.Client

func main() {
  ctx := context.Background()
  var err error
  bt, err = bigtable.NewClient(ctx, ...)

  http.HandleFunc("/", handle)
  log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), nil)
}

func handle(w http.ResponseWriter, r *http.Request) {
  ctx := r.Context()
  // use bt client here.
}
```
