### ISSUE TITLE
bigquery how extract to csv with UTF-8 with BOM

### ISSUE THREAD

**Issue by nosovk** [googleapis/google-cloud-go#1299]
Big-query allows to export to CSV. Supported encoding is UTF-8.
It's good, because allows to work with non Latin characters.
But unfortunately CSV from BQ do not have BOM. I mean that windows applications like excel or notepad couldn't recognize UTF-8 inside, here is a result:
![image](https://user-images.githubusercontent.com/1398808/52175165-8d4af680-27a8-11e9-98df-a75cf457e0f2.png)
It's not hard to fix an issue adding option to add BOM to export.

Or probably there is some workaround?
I tried to add BOM to column name, to have BOM character be a first letter in first column. Unfortunate for me BQ prohibits usage of special characters in column names.
Related issue: #292

**Comment by jadekler** [comment]
Thanks for splitting this out! /cc @JesseLovelace @shollyman @weslem

**Comment by shollyman** [comment]
Thanks for highlighting  I see someone's already pinged https://issuetracker.google.com/issues/35905733 on the public issue tracker for this, which is the right place for changing the behavior of an extract job that writes a CSV output.

The client libraries have no control over whether CSV exports write a UTF8 BOM, but its possible to consume the structured row results form a table/query via the API and then write the CSV output yourself.

**Comment by jadekler** [comment]
Closing in favour of https://b.corp.google.com/issues/35905733.

**Comment by nosovk** [comment]
> Closing in favour of https://b.corp.google.com/issues/35905733.

this is an internal link, could you please provide current status of an issue?

**Comment by codyoss** [comment]
External link: https://issuetracker.google.com/issues/35905733
