### ISSUE TITLE
spanner: respect retryinfo for all calls

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1309]
As per #1215, retry info from the Spanner server via grpc trailers is only respected for transaction's Commit call.

We should extract the trailers for every call in the Spanner client (and maybe other APIs, too?)

Correct code:
https://github.com/googleapis/google-cloud-go/blob/a53d2daf2cb6fc4081032ebb3dc8b4f042f46875/spanner/transaction.go#L764-L778

**Comment by broady** [comment]
Apparently this information was originally only on the Commit call, so I'm changing this to a feature request.

**Comment by broady** [comment]
Low priority. After looking at what the Spanner server returns (the benefits of accessing source code for all the services at Google), it seems that the RetryInfo is a relatively simple exponential backoff starting at 10ms (which is in line with the observed data returned by the server). So, I think we're just as good implementing that backoff in the client for now.

RetryInfo for Commit calls is different, however, and looks to be dependent on the time taken for the previously Aborted Commit.

**Comment by olavloite** [comment]
The Spanner client library now extracts this information automatically from the returned `Status` error for all RPCs without the need for specifically extracting trailers. The change was implemented in https://code-review.googlesource.com/c/gocloud/+/52790.
