### ISSUE TITLE
all: investigate using golang.org/x/xerrors

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1310]
Tracking bug for general investigation of Go 1.13 style errors.

**Comment by broady** [comment]
#1223 would be addressed by this issue.

```
var se spanner.Error
xerrors.As(&se)
...
```

**Comment by jba** [comment]
It would be great if you guys would kick the tires on this. Please let me know of any questions or concerns.

**Comment by jadekler** [comment]
Noting for posterity: I'm hesitant to move on this because https://godoc.org/golang.org/x/exp/xerrors is (highly, to my knowledge) experimental.

**Comment by jadekler** [comment]
Nevermind, it turns out there's also a non-experimental https://godoc.org/golang.org/x/xerrors. Dropping my note of reluctance!

**Comment by codyoss** [comment]
Closing out this issue as we now support the std fmt/error packages for error wrapping and do a bit of this in the gax layer to provide richer errors for gRPC clients.
