### ISSUE TITLE
Dropped storage read requests are not retried

### ISSUE THREAD

**Issue by chaimleib** [googleapis/google-cloud-go#1311]
Originally reported in PR #1274:

## Client
storage

## Describe Your Environment
Google App Engine standard for Go 1.9

## Expected Behavior
When read requests temporarily fail or timeout, they should be retried with exponential backoff. If a read returns an error, the error's Code field contains an HTTP error number, like 404.

## Actual Behavior
Read calls to GCS are failing roughly every 200 requests, and certain temporary failures are not being retried with exponential backoff. Instead, the read fails completely with one of three messages, and the Code field of all the errors is 0. My logs show that there were three types of error messages:

```
gcs.go:144: server/en_ioutil.gcsReadBinaryFile(ctx, "gs://en-prod-wwwsite-cps/cms/en/webroot/index.json"): could not create object Reader
	Get https://storage.googleapis.com/en-prod-wwwsite-cps/cms/en/webroot/index.json: Call error 11: Deadline exceeded (timeout)

gcs.go:144: server/en_ioutil.gcsReadBinaryFile(ctx, "gs://en-prod-wwwsite-cps/cms/en/webroot/index.json"): could not create object Reader
	Get https://storage.googleapis.com/en-prod-wwwsite-cps/cms/en/webroot/index.json: API error 2 (urlfetch: FETCH_ERROR)

gcs.go:144: server/en_ioutil.gcsReadBinaryFile(ctx, "gs://en-prod-wwwsite-cps/cms/en/webroot/index.json"): could not create object Reader
	Get https://storage.googleapis.com/en-prod-wwwsite-cps/cms/en/webroot/index.json: API error 5 (urlfetch: DEADLINE_EXCEEDED)
```
I was able to work around the issue by calling my `gcsReadBinaryFile` function again whenever the Code field was zero.

Here is the code that was erroring:
```
func gcsCleanPath(u *url.URL) string {
	return strings.TrimLeft(u.EscapedPath(), "/")
}

func gcsReadBinaryFile(
	ctx context.Context,
	u *url.URL,
) ([]byte, error) {
	// prepare my error wrapper, also logs func args
	b := debug.NewBugger("ctx, %q", u)
	client, err := storage.NewClient(ctx)
	if err != nil {
		return nil, b.ErrorChainf(err, "could not create client")
	}
	obj := client.Bucket(u.Host).Object(gcsCleanPath(u))
	reader, err := obj.NewReader(ctx)  // ## SPORADIC ERRORS HERE ##
	if err != nil {
		return nil, b.ErrorChainf(err, "could not create object Reader")
	}
	slurp, err := ioutil.ReadAll(reader)
	reader.Close()
	if err != nil {
		return nil, b.ErrorChainf(err, "error while reading object")
	}
	return slurp, nil
}
```

To work around this, here is the retry check I used:
```
func shouldRetry(err error) bool {
	switch e := err.(type) {
	case *googleapi.Error: // # errors caught here
		return e.Code == 0
	default:
		return false
	}
}
```
After I started triggering one retry on that check, all the errors disappeared.

**Comment by jadekler** [comment]
cc @frankyn 

@chaimleib Thank you for reporting this. Your error wrapping makes it a bit hard to figure out what's happening in our library. Could you please replace your `return nil, b.ErrorChainf(err, "error while reading object")` statements with `panic(err)`, and then provide us the exact stacktrace from the panic?

**Comment by chaimleib** [comment]
Unfortunately, it's not acceptable to cause panics on production. Whenever I have a little time, I'm investigating how to email myself a stack trace without killing the server.

**Comment by jadekler** [comment]
Sounds good. With a stacktrace we should be able to make progress to figure this out.

**Comment by jadekler** [comment]
Hello! We've asked some clarifying questions and haven't heard from you in a while. We're going to close this issue at the moment, but if you would like to re-continue the conversation please feel free to ping back here!
