### ISSUE TITLE
Semantic search on Datastore using GoLang

### ISSUE THREAD

**Issue by shekharsumanpandey-tudip** [googleapis/google-cloud-go#1313]
Hi All,

I am using GoLang and database is Datastore.

I have to implement a Semantic search functionality but I don't know how to implement semantic search.

I know how to do an exact match search functionality but I don't know how I implement Semantic search.

Please help me out.

Any help appreciated.

**Comment by jadekler** [comment]
As in, https://en.wikipedia.org/wiki/Semantic_search? I don't think the Datastore client library (this repository is scoped to client libraries) has anything out the box for that. I'd recommend asking if any other datastore users have implemented this sort of thing. Stackoverflow might be a good place to ask such a question: https://stackoverflow.com/questions/tagged/google-cloud-datastore.

**Comment by shekharsumanpandey-tudip** [comment]
> As in, https://en.wikipedia.org/wiki/Semantic_search? I don't think the Datastore client library (this repository is scoped to client libraries) has anything out the box for that. I'd recommend asking if any other datastore users have implemented this sort of thing. Stackoverflow might be a good place to ask such a question: https://stackoverflow.com/questions/tagged/google-cloud-datastore.



> As in, https://en.wikipedia.org/wiki/Semantic_search? I don't think the Datastore client library (this repository is scoped to client libraries) has anything out the box for that. I'd recommend asking if any other datastore users have implemented this sort of thing. Stackoverflow might be a good place to ask such a question: https://stackoverflow.com/questions/tagged/google-cloud-datastore.

@jadekler  Thanks for the quick feedback, I Just want to know it is possible to search on column name by comparing with string(just LIKE operator in sql) or adding a regex by the filter.

Fo ex: I have string "ra" and compare on the column. Return all possible solution related with that string

**Comment by jadekler** [comment]
> I Just want to know it is possible to search on column name by comparing with string(just LIKE operator in sql) or adding a regex by the filter.
>
> Fo ex: I have string "ra" and compare on the column. Return all possible solution related with that string

cc @poy @andrewsg

**Comment by poy** [comment]
@shekharsumanpandey-tudip So I took a look at the Datastore [docs](https://cloud.google.com/datastore/docs/concepts/queries#filters) for filters and it looks like the only operators are:

Operators | Meaning
-- | --
"=" | Equal to
"<" | Less than
"<=" | Less than or equal to
">" | Greater than
">=" | Greater than or equal to

You can do these operators against a string, however its not a fuzzy search nor is it regex.
