### ISSUE TITLE
securitycenter/apiv1beta1: CreateFinding source properties example

### ISSUE THREAD

**Issue by mmwtsn** [googleapis/google-cloud-go#1314]
Could someone update the `CreateFinding` example showing how to add source properties?

The [`Finding`](https://godoc.org/google.golang.org/genproto/googleapis/cloud/securitycenter/v1beta1#Finding) type's `SourceProperties` field is a map of string to [`structpb.Value`](https://godoc.org/github.com/golang/protobuf/ptypes/struct#Value) pointers. I'm probably missing something but I'm not sure how to serialize data into that type so I can add source properties to a security finding. I have a JSON byte slice of properties that I tried to using the jsonpb package's [`Unmarshal`](https://godoc.org/github.com/golang/protobuf/jsonpb#Unmarshal) function which compiled successfully but the call failed with this error:

> rpc error: code = InvalidArgument desc = value must be NUMBER, STRING, OR BOOL

Trying to cast directly into the type or use a proto message both failed to compile.

**Comment by mmwtsn** [comment]
The answer ended up being:

```go
sourceProperties := map[string]*structpb.Value{
	"StringExampleKey": &structpb.Value{
		Kind: &structpb.Value_StringValue{StringValue: "abc"},
	},
	"BoolExampleKey": &structpb.Value{
		Kind: &structpb.Value_BoolValue{BoolValue: true},
	},
	"NumberExampleKey": &structpb.Value{
		Kind: &structpb.Value_NumberValue{NumberValue: 123},
	},
}
```

**Comment by jadekler** [comment]
Oof. That's unpleasant. Leaving this open for us to circle around and improve the docs.

**Comment by mmwtsn** [comment]
Awesome, thanks @jadekler!

**Comment by odeke-em** [comment]
Thank you for filing this issue @mmwtsn and for the follow-up @jadekler!

So golang-samples under Google-Cloud-Platform has an excellent example as per https://github.com/GoogleCloudPlatform/golang-samples/blob/602d0b609e4c5cfdee8fada906a100062712279f/securitycenter/findings/create_finding_with_source_properties.go#L49-L71

Unfortunately securitycenter in this project all contain auto-generated code, which explains the non-descript example so am not sure how to proceed. If we can deem it necessary we can make a hand generated example_test.go file and put up an example, I have one ready
```go
package securitycenter_test

import (
	"context"

	securitycenter "cloud.google.com/go/securitycenter/apiv1beta1"
	pstruct "github.com/golang/protobuf/ptypes/struct"
	securitycenterpb "google.golang.org/genproto/googleapis/cloud/securitycenter/v1beta1"
)

func ExampleClient_CreateFinding_fields() {
	ctx := context.Background()
	c, err := securitycenter.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}

	req := &securitycenterpb.CreateFindingRequest{
		Parent:    "organizations/acme/sources/coyote",
		FindingId: "wile",
		Finding: &securitycenterpb.Finding{
			Name:         "organizations/acme/sources/coyote/findings/789",
			Parent:       "organizations/acme/sources/coyote",
			ResourceName: "WileE",
			State:        securitycenterpb.Finding_ACTIVE,
			Category:     "XSS_FLASH_INJECTION",
			ExternalUri:  "https://example.com",
			SourceProperties: map[string]*pstruct.Value{
				"latest":   {Kind: &pstruct.Value_BoolValue{BoolValue: true}},
				"version":  {Kind: &pstruct.Value_NumberValue{NumberValue: 3}},
				"category": {Kind: &pstruct.Value_StringValue{StringValue: "xss"}},
				"parent":   {Kind: &pstruct.Value_NullValue{NullValue: pstruct.NullValue_NULL_VALUE}},
				"expiry": {Kind: &pstruct.Value_StructValue{
					StructValue: &pstruct.Struct{
						Fields: map[string]*pstruct.Value{
							"tld":         {Kind: &pstruct.Value_StringValue{StringValue: ".com"}},
							"refresh_min": {Kind: &pstruct.Value_NumberValue{NumberValue: 10.0}},
						},
					},
				}},
			},
		},
	}
	resp, err := c.CreateFinding(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp

}
```

@jadekler @broady what do y'all think?

**Comment by odeke-em** [comment]
Thank you for the patience @mmwtsn! So in this case we can always refer to the already written examples as well as the Godoc for how to use these properties. I am going to close this issue but please feel free to reopen if I am missing something.
