### ISSUE TITLE
Add bazelbuild/remote-apis protos

### ISSUE THREAD

**Issue by t-chaik** [googleapis/google-cloud-go#1322]
The Remote Execution API (REAPI) is a gRPC+protobuf protocol that Bazel (but not only) uses to distribute build and test actions across multiple machines. The protos are currently hosted in a separate repo from the core `googleapis`: [`remote-apis`](https://github.com/bazelbuild/remote-apis). Would be nice to add it as a proto source to `google-cloud-go`: that would make it easier for Go developers to use that API. For details about remote execution see Bazel's [documentation](https://docs.bazel.build/versions/master/remote-execution.html). An (alpha) remove execution service is available on Google Cloud Platform: [RBE](https://groups.google.com/forum/#!forum/rbe-alpha-customers).

**Comment by jadekler** [comment]
Sorry, I was unclear. By "that repo" I mean https://github.com/bazelbuild/remote-apis.
