### ISSUE TITLE
Cloud IoT Core API implementation

### ISSUE THREAD

**Issue by brocaar** [googleapis/google-cloud-go#1323]
Are there plans to add support for the Cloud IoT Core API to this package?

I believe such a client already exists for NodeJS (https://cloud.google.com/nodejs/docs/reference/iot/0.2.x/), but as far as I know, this is not available for Go? 

My usecase is that I would like to send messages to connected devices using a Cloud Function written in Go by calling the Cloud IoT Core (cloudiotdevice) API.

**Comment by jadekler** [comment]
Happy to generate it. See: https://code-review.googlesource.com/c/gocloud/+/38392

**Comment by jadekler** [comment]
https://godoc.org/cloud.google.com/go/iot/apiv1
