### ISSUE TITLE
Enormous dependency tree for cloud.google.com/go/storage

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1328]
I just want to use GCS buckets from my Go app, but it is taking many MiB's and several minutes to download all of the various dependencies involved in that lib.

I confess I began with the incorrect assumption that the GCS Go library would consist of a basic Go wrapper around some HTTP calls, but it looks like grpc, OpenCensus, Protobuf, and the kitchen sink are involved with this. Would it be possible to pare down this dependency tree, while keeping accuracy and performance comparable with the existing lib?

**Comment by jadekler** [comment]
Sorry about that! We absolutely plan to introduce multiple modules in this repository, which will solve your problem. However, first we're solidifying our module tooling and CI processes, and waiting for 1.12.

Closing this in favour of tracking internally. Once the change happens, `go mod tidy` will transparently pick up the changes. :)
