### ISSUE TITLE
Add `useAvroLogicalTypes` to Configuration Load in bigquery package

### ISSUE THREAD

**Issue by JustinCarmony** [googleapis/google-cloud-go#1329]
Love using the libraries so far, found one issue where you can't pass along a setting.

Per the BigQuery Documentation (https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#decimal-logical-type), you can have BigQuery infer types by using the `configuration.load.useAvroLogicalTypes` boolean set to true (see: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.useAvroLogicalTypes). This will allow BigQuery to infer the schema correctly (like Timestamps) instead of treating them as integers.

I've scoured the codebase looking for this setting, and it appears to just be missing. 

## Client

bigquery package

## Describe Your Environment

This impacts any environment, we're using it locally on MacOS.

## Expected Behavior

Be able to set `useAvroLogicalTypes` on the LoadConfig struct (or where ever the correct location for `configuration.load.useAvroLogicalTypes` is.

## Actual Behavior

Unable to configure the loader to use this setting.

## Example Code

```golang
package main

import (
	"cloud.google.com/go/bigquery"
	"context"
	"google.golang.org/api/option"
	"log"
)

func main() {
	ctx := context.Background()
	options := option.WithCredentialsFile("/path/to/gcp-auth-file.json")
	client, _ := bigquery.NewClient(ctx, "example-project-id", options)
	dataset := client.Dataset("example_dataset")
	table := dataset.Table("example_table")
	gcsRef := bigquery.NewGCSReference("gs://example-bucket/avro-file-with-schema.avro")
	gcsRef.SourceFormat = bigquery.Avro
	gcsRef.AutoDetect = true

	loader := table.LoaderFrom(gcsRef)
	loader.WriteDisposition = bigquery.WriteTruncate
	loader.CreateDisposition = bigquery.CreateIfNeeded
	loader.Location = "US"

	// *** MISSING CONFIG ***
	loader.UseAvroLogicalTypes = true

	log.Println("Start job...")
	job, _ := loader.Run(ctx)

	log.Println("Waiting for job... ")
	jobStatus, _ := job.Wait(ctx)
	log.Println("done:", jobStatus.Err())
}
```

Thank you! I really appreciate the help and work you all do. :)

**Comment by jadekler** [comment]
cc @shollyman
