### ISSUE TITLE
Re-pin oauth2 for new urls and cut new release

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1333]
Token endpoints were recently changed in https://go-review.googlesource.com/c/oauth2/+/136356. Per https://github.com/googleapis/google-cloud-common/issues/260#issuecomment-467669448, let's let this bake for a week or two and then re-pin oauth2 here and in google-api-go-client, and then also re-pin google-api-go-client here.

Then, we should release a new version.

**Comment by shinfan** [comment]
Thanks for handling this Jean.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/38930

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/38950
