### ISSUE TITLE
datastore: add RunInTransaction method variant allowing access to the used context.Context

### ISSUE THREAD

**Issue by vvakame** [googleapis/google-cloud-go#1334]
https://godoc.org/cloud.google.com/go/datastore#Transaction contains context.Context.
But we can't access it.
so, I can't construct good trace graph on StackDriver Tracing.

I want
```
cloud.google.com/go/datastore.RunInTransaction
└── MySpanName
    └── cloud.google.com/go/datastore.Transaction.PutMulti
```

But now
```
cloud.google.com/go/datastore.RunInTransaction
├── MySpanName
└── cloud.google.com/go/datastore.Transaction.PutMulti
```

I think We need something like...
`func (t *Transaction) MergeContext(ctx context.Context) (context.Context, *Transaction)`
Why this method returns context.Context? because I want to get context when using 
 https://godoc.org/cloud.google.com/go/datastore#Client.NewTransaction . It doesn't return context.Context to us.

Can I send a pull request?

<details>

```go
package main

import (
	"cloud.google.com/go/datastore"
	"context"
	"go.opencensus.io/trace"
)

type Data struct {
	Value string
}

func main() {
	ctx := context.Background()
	err := func1(ctx)
	if err != nil {
		panic(err)
	}
}

func func1(ctx context.Context) error {
	var dsCli datastore.Client
	tx, err := dsCli.NewTransaction(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	ctx, tx = tx.MergeContext(context.Background()) // extract NewTransaction's context

	err = withTx(ctx, tx)
	if err != nil {
		return err
	}

	_, err = tx.Commit()
	if err != nil {
		return err
	}

	return nil
}

func withTx(ctx context.Context, tx *datastore.Transaction) error {
	ctx, span := trace.StartSpan(ctx, "MySpanName")
	defer span.End()

	ctx, tx = tx.MergeContext(ctx) // join Tx into MySpanName
	_, err := tx.Put(datastore.IncompleteKey("Data", nil), &Data{Value: "example"})
	return err
}
```

</details>

**Comment by jadekler** [comment]
Hello!

Thanks for filing this issue. A couple of things:

- It occurs to me that PutMulti and other transaction methods are not performing RPCs, and as such should not have their own traces. The only RPC that happens in a transaction is the transaction commit. I think we're going to remove these non-RPC traces, and if users need them they can create and end a span around the PutMulti / whatever SDK call themselves. Since there are no children of these spans (again, no RPCs below that level) this is equivalent.

- It's unfortunate that we don't propagate ctx into the callback function specified in RunInTransaction. I think the approach we should take for things of this ilk is to make a new method:

```
func (c *Client) RunInTransaction(ctx context.Context, f func(innerCtx context.Context, tx *Transaction) error, opts ...TransactionOption) (cmt *Commit, err error)
```

**Comment by vvakame** [comment]
> we're going to remove these non-RPC traces

👍 

> `func (c *Client) RunInTransaction(ctx context.Context, f func(innerCtx context.Context, tx *Transaction) error, opts ...TransactionOption) (cmt *Commit, err error)`

👍

**Comment by broady** [comment]
To get nesting like this, the methods on the Transaction (such as GetMulti) need to accept a context parameter. I'm not sure it's worth the change.

**Comment by odeke-em** [comment]
>But @jadekler's idea about removing non-RPC spans seems good, especially with the reasoning that people can wrap themselves if they really want nested traces.

In deed, we removed non-RPC spans with https://github.com/googleapis/google-cloud-go/commit/fc9c8526dbce4c4df4a8edfe98be03a2d2a50d55

>What's the idea behind propagating the ctx into the callback? What would this ctx do differently?

From the discussion with @jadekler, the idea was that we want to give users back control and flexibility because Transaction methods might do other things with their contexts such as in this case start a span and re-assign `t.ctx = doSomething(t.ctx, ....)`

>To get nesting like this, the methods on the Transaction (such as GetMulti) need to accept a context parameter. I'm not sure it's worth the change.

Yes, I agree too. That'd be a huge breakage.

**Comment by jadekler** [comment]
> > To get nesting like this, the methods on the Transaction (such as GetMulti) need to accept a context parameter. I'm not sure it's worth the change.

> Yes, I agree too. That'd be a huge breakage.

Yuck :/ Yeah, that's no good. Hm... maybe this is a datastore v2 proposal, and not feasible in the current datastore.

**Comment by broady** [comment]
> their contexts such as in this case start a span and re-assign

Right, but the re-assignment happens after the reference to the context has been taken when the callback is invoked. So, as [CL 40291](https://code-review.googlesource.com/c/gocloud/+/40291) is currently implemented, the context is always the same.

If you want to have sub-spans, etc, I think you need some context that can be swapped out on the fly, which is pretty odd and very un-context-like.

Something like this:

```
// dynamicContext implements context.Context
var _ context.Context = dynamicContext{}

type dynamicContext struct { mu sync.Mutex; c context.Context }

func (dc *dynamicContext) SetContext(ctx context.Context) {
  dc.mu.Lock()
  dc.c = ctx
  dc.mu.Unlock()
}

func (dc *dynamicContext) Value(...) {
  dc.mu.Lock()
  defer dc.mu.Unlock()
  return dc.c.Value(...)
}
```

On re-assignment: the non-RPC spans are gone now, so what re-assignment is happening? Nothing, I think?

**Comment by jadekler** [comment]
@vvakame Yes, separate issue please. :)

**Comment by vvakame** [comment]
I thought about versioning to do Breaking Change, but it's too difficult.
I could not write a good proposal... 😿 
If we try to operate correctly as semver to do Breaking Change, Go Modules needs to be tagged on git.
But that's difficult with this repository, which is a collection of packages.
It will be difficult if you don't break this repository into pieces, and Google won't do that I think.

My first suggestion is to solve the problem without Breaking Change.
This is an idea that can be shooting itself in the foot, but it does not break someone's code.

**Comment by jadekler** [comment]
@vvakame This repository will become a [multi-module repository](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories), which allows per-client v2s. However, it'll be a while before we adopt them, and even then it'll be a long while before there's enough justification for the hassle and complication of publishing a v2 of a client.

**Comment by vvakame** [comment]
wow, I didn't know that spec! SGTM.
I am looking forward to v2.

**Comment by jadekler** [comment]
Closing this, since we can't do it in v1. Adding it to our tracking list of v2 features.
