### ISSUE TITLE
FEATURE: BigQuery InferSchema include field details in error messages

### ISSUE THREAD

**Issue by nfisher** [googleapis/google-cloud-go#1335]
The BigQuery InferSchema is a nice convenience function for generating schemas. It would be helpful for debugging purposes if additional details were included in the error being returned including:

 * field name.
 * parent struct name.
 * file.
 * line number.

Line number/file would be nice but not essential.

Some of our structs/schemas have dozens of fields. As a result the current approach for resolving schema errors is either adding 1 field at a time for new schemas or commenting out fields for preexisting structs.

### Example Behaviour

Using an unsupported type results in the following error string:

`bigquery: unsupported type of field in struct`

### Desired Behaviour

Some variation like this where Bob is the field and Alice is the parent struct would be ideal:

```
bigquery: unsupported type of field (Bob) in struct (Alice)
```

**Comment by jadekler** [comment]
@shollyman WDYT?

**Comment by jba** [comment]
I'm doing it. It's clearly the right thing and I need a quick win during perf week.

**Comment by nfisher** [comment]
Thanks! Haven't had an opportunity to test this yet but looking at the change looks like it should tick the boxes. 👍
