### ISSUE TITLE
errorreporting: how to link an error to a log message?

### ISSUE THREAD

**Issue by nhooyr** [googleapis/google-cloud-go#1336]
I'd like to link an error with a log message for with gRPC.

Is this currently possible?

**Comment by nhooyr** [comment]
Or provide some extra multiline data?

Right now the UI seems to condense everything onto a single line which is very hard to read.

**Comment by nhooyr** [comment]
I guess I could use the raw format to view instead.

**Comment by nhooyr** [comment]
Example of my problem:

parsed:
<img width="560" alt="screen shot 2019-02-27 at 6 43 40 pm" src="https://user-images.githubusercontent.com/10180857/53531028-f845cf80-3abf-11e9-8454-793f76c6aa37.png">

raw: 
<img width="612" alt="screen shot 2019-02-27 at 6 43 43 pm" src="https://user-images.githubusercontent.com/10180857/53531036-009e0a80-3ac0-11e9-9831-ef170faea295.png">

**Comment by nhooyr** [comment]
For now, I added commas after every field and `{` and `}` around the fields. Much easier to read now.
<img width="565" alt="screen shot 2019-02-27 at 7 05 44 pm" src="https://user-images.githubusercontent.com/10180857/53531908-b5d1c200-3ac2-11e9-9235-8afa5b83b507.png">

**Comment by nhooyr** [comment]
Ended up removing that all together, makes the summary of errors include an individual error's fields which looks really weird.

<img width="1854" alt="screen shot 2019-02-27 at 7 17 20 pm" src="https://user-images.githubusercontent.com/10180857/53532432-e286d900-3ac4-11e9-8c69-8da4e94c34f3.png">

**Comment by jadekler** [comment]
Sorry, this issue fell off my radar. cc @dazuma

**Comment by nhooyr** [comment]
Follow up question, is there any way to add additional information to the log, instead of just a single line.

**Comment by nhooyr** [comment]
Looks like this is a decent work around https://stackoverflow.com/questions/51217273/google-stackdriver-error-reporting-api-include-custom-data

**Comment by jadekler** [comment]
cc @jmdobry @dazuma @munangst

**Comment by jadekler** [comment]
Friendly ping @munangst

**Comment by jadekler** [comment]
Hello! I've gotten in touch with the team, and they recommend posting to https://stackoverflow.com/questions/tagged/google-cloud-error-reporting. (several googlers are watching that closely)
