### ISSUE TITLE
FEATURE: pstest clear funtionality

### ISSUE THREAD

**Issue by IngCr3at1on** [googleapis/google-cloud-go#1338]
We're using pstest to test the behavior of a pubsub based application; we chose pstest over the pubsub emulator because we can easily start it from within the tests rather than having to docker-compose the emulator and in general it appears to be less flakey than the emulator just in my direct fiddling (that may not be entirely the case)...

At anyrate we've encountered some confusing behavior in our tests (related to asynchronous operations); a super simple solution that we came up with was to just clear the pstest server messages in between a couple of our tests to avoid seeing republish of messages that were purposefully not acked or nacked as part of our test coverage.

The change that I made inside our vendor repo is as follows (super simple and I can't imagine why anyone would have an issue with it).

```
// Clear all the messages from the internal array.
func (s *Server) Clear() {
	s.GServer.mu.Lock()
	s.GServer.msgs = make([]*Message, 0, 0)
	s.GServer.mu.Unlock()
}
```

----

My question is; would such a change be welcome (if so I'd be happy to submit it but I haven't had gerrit setup in quite some time and would rather not bother if the change is not welcome)?

**Comment by jba** [comment]
Have you tried closing and restarting the server between tests? It should come up pretty fast.

If each test started and stopped its own server, you could even run your tests in parallel.

**Comment by IngCr3at1on** [comment]
We considered something like that but the issue is at the moment we're initializing the pubsub client at the start of our service and passing it along into a worker pool so attempting to stop/start the server between tests means re-injecting the pubsub client into the worker pool (for both the publisher and subscriber methods); which shouldn't (ideally) be possible from outside the service.

To be clear my actual unit tests do what you are suggesting this is a service integration test that's proving difficult to test out entirely and the 'Clear' function was just the simplest fix we could come up with.

**Comment by jba** [comment]
Then `Clear` sounds good to me. @jadekler?

**Comment by jadekler** [comment]
SGTM. @IngCr3at1on do you want to submit this CL (please see our [CONTRIBUTING.md](https://github.com/googleapis/google-cloud-go/blob/master/CONTRIBUTING.md) if so)? If not, I'm happy to.

**Comment by IngCr3at1on** [comment]
@jadekler hmm... interestingly in our particular use case after having debugged everything it turns out we don't need the `Clear` function for our final implementation but it was still insanely useful in troubleshooting.

To that end even though I don't actually have a _need_ for this function anymore today it still proved particularly useful. I'd be more than happy to submit it when I have the time but I wouldn't want you to go out of your way today either. :smile:

**Comment by hongalex** [comment]
@IngCr3at1on Were you ever able to look at this? If not, I can start work on this and loop you in if you'd like.

**Comment by IngCr3at1on** [comment]
@hongalex I apologize I kind of forgot about this on account of winding up not needing it in our final implementation. If others still think it's needed I'd be happy if you wanted to pick it up as I'm not sure when I will have the time otherwise.
