### ISSUE TITLE
Clean up apiv1beta1, v1beta1, scheduler API name mismatches

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1339]
I think the Google Cloud Scheduler Go API is still in beta, but even so, we may want to use a more conventional Go import structure. The current setup is split between `scheduler`, `apiv1beta`, and `v1beta1`, with the behaviors located on one import path, request objects on another import path, and the Go compiler emitting yet other import paths. This can add confusion to the debugging process.

As a workaround, I am digging into the google-cloud-go implementation code to identify the right import paths for these things.

**Comment by jadekler** [comment]
I'm failing to grok. Could you list the import paths in full that you're describing?

**Comment by jadekler** [comment]
We've asked for clarifying information and not heard from you in a while. Closing this issue but please feel free to reply and continue the conversation.
