### ISSUE TITLE
Update to protoc-go 1.3.1

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1341]
https://github.com/golang/protobuf/releases

**Comment by jadekler** [comment]
https://github.com/google/go-genproto/pull/164
https://code-review.googlesource.com/c/gocloud/+/41070

**Comment by odeke-em** [comment]
Congrats @jadekler!

Now that CL https://code-review.googlesource.com/c/gocloud/+/41230 has been merged, shall we close this issue?

**Comment by jadekler** [comment]
Ah yeah good call, thanks.
