### ISSUE TITLE
profiler: unflake TestAgentWithServer

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1343]
```
=== RUN   TestAgentWithServer
--- FAIL: TestAgentWithServer (11.45s)
    profiler_test.go:881: validateProfile(HEAP) got error: wanted function name profilee not found in the profile
```

https://sponge.corp.google.com/target?id=76a0f74e-badd-4497-b330-334640364944&target=cloud-go-libraries%2Fgoogle-cloud-go%2Fpresubmit%2Fgo112&searchFor=

**Comment by aalexand** [comment]
@kalyanac FYI

@jadekler I was trying to re-assign to @kalyanac but couldn't. Could you add google/pprof-team as the read members for this repo so that the members show up in the people list?

**Comment by jadekler** [comment]
@aalexand Sorry for the continued troubles. I've added the https://github.com/orgs/googleapis/teams/api-profiler team as a writer. Unfortunately can only add teams in the googleapis org.

**Comment by jadekler** [comment]
Happened again today.

```
--- FAIL: TestAgentWithServer (10.84s)
    profiler_test.go:961: validateProfile(HEAP) got error: wanted function name profilee not found in the profile
```

**Comment by kalyanac** [comment]
@jadekler I'll look at it today.

**Comment by jadekler** [comment]
Flaked again today: https://sponge.corp.google.com/target?id=4b6db966-28fd-44c9-971f-b8fc4d83138c&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=ALL&sortBy=STATUS

Skipping for the time being https://code-review.googlesource.com/c/gocloud/+/39730

**Comment by kalyanac** [comment]
Fixed with
https://code-review.googlesource.com/c/gocloud/+/40110
