### ISSUE TITLE
profiler: remove x/build dependency

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1344]
Relevant: https://github.com/golang/go/issues/29935#issuecomment-457600355

Per [Alexey's comment](https://github.com/golang/go/issues/29935#issuecomment-457629198):

> It should be totally reasonable to get rid of golang.org/x/build/kubernetes dependency in cloud.google.com/go/profiler/proftest, probably replacing it with k8s.io/client-go. In fact, for now that code can just be removed as the profiler GKE tests are broken and that code needs to be updated anyway. So the immediate action is I think to remove the dependency and the code from proftest.go, then figure out how to do it proper.

In the future, when we support multiple modules within this repository, this won't be a problem.

**Comment by aalexand** [comment]
Tracked with b/123400217.

**Comment by dmitshur** [comment]
This has been fixed in commit 8a3b7e3bd08fdfc1cefccf1f08c7f7b32c890f61, which is included in version v0.37.3 and newer. This issue can be closed.

**Comment by odeke-em** [comment]
Great, thank you @dmitshur for the ping!
