### ISSUE TITLE
spanner: no way to ignore errors in ReadWriteTransaction

### ISSUE THREAD

**Issue by colinmarc** [googleapis/google-cloud-go#1345]
The following example behaves in a way that seems inconsistent with the docs:

```go
commit, err := spanner.ReadWriteTransaction(context.Background(), func(ctx context.Context, tx *spanner.ReadWriteTransaction) error {
	for i := 0; i < 2; i++ {
		// There's a primary key on Foo, so this fails the second time with AlreadyExists.
		_, err := tx.Update(ctx, spanner.NewStatement("INSERT INTO Foos (Foo, Bar) VALUES (1, 'test')"))
		if spanner.ErrCode(err) != codes.AlreadyExists {
			return err // This line is never hit.
		}
	}

	return nil
})

// err is AlreadyExists, and commit is a zero time.
```

I'd expect errors to only bubble out if returned, since the docs require you to return them.

**Comment by lc-caigwatkin** [comment]
I've run into this before. Until the transaction is committed you won't see the AlreadyExists error. The docs of tx.Update(...): "...any data read will be validated upon commit."

So the fix would be:
```go
commit, err := spanner.ReadWriteTransaction(context.Background(), func(ctx context.Context, tx *spanner.ReadWriteTransaction) error {
	for i := 0; i < 2; i++ {
		// There's a primary key on Foo, so this fails the second time with AlreadyExists.
		_, err := tx.Update(ctx, spanner.NewStatement("INSERT INTO Foos (Foo, Bar) VALUES (1, 'test')"))
		if err != nil {
			return err
		}
	}
	return nil
})
if err != nil {
	if spanner.ErrCode(err) != codes.AlreadyExists {
		// Handle conflict
	}
	// Handle error
}
```

**Comment by colinmarc** [comment]
Well, at a minimum, I'd expect `commit` to be nonzero in that case, since the transaction didn't fail.

**Comment by colinmarc** [comment]
@jadekler do you mind clarifying the "question" label? This seems like it's pretty clearly a bug.

**Comment by broady** [comment]
/cc @jsimonweb

I'm a little confused here, can you elaborate?

> I'd expect errors to only bubble out if returned, since the docs require you to return them.

If you try to apply an update within a transaction, but don't return the error, this doesn't seem like a valid transaction. What you wrote in your first comment seems like correct behavior.

So we can investigate and make any changes to docs, could you provide exact steps:

* state before code runs
* code you're running
* error state of transaction; plus state after code runs
* error state you expected; plus state you expected

**Comment by colinmarc** [comment]
Given the following table:

```sql
CREATE TABLE Foos (
  Foo INT64 NOT NULL,
  Bar STRING(MAX) NOT NULL,
) PRIMARY KEY (Foo);
```

The following behavior is, I think, a bug:
```go
commit, err := spanner.ReadWriteTransaction(context.Background(), func(ctx context.Context, tx *spanner.ReadWriteTransaction) error {
	for i := 0; i < 2; i++ {
		// There's a primary key on Foo, so this fails the second time with AlreadyExists.
		_, err := tx.Update(ctx, spanner.NewStatement("INSERT INTO Foos (Foo, Bar) VALUES (1, 'test')"))
		if spanner.ErrCode(err) != codes.AlreadyExists {
			panic(err) // This is never hit.
		}
	}

	return nil
})

fmt.Println(err)
// spanner: code = "AlreadyExists", desc = "Row [1] in table Foos already exists"
fmt.Println(commit.IsZero())
// true
```

The first bug here is that even though the function passed to `ReadWriteTransaction` returned nil, the error is still returned by `ReadWriteTransaction`. The second bug is that even though the transaction *succeeded* (if you SELECT afterwards), commit is zero.

**Comment by colinmarc** [comment]
Hm, looking again, it seems that I got the latter half wrong - I thought the transaction was succeeding, but it is failing. It still seems wrong that an individual update failing will roll back the whole transaction; on an application level, you might want to do something else if the row still exists, and still preserve transactionality.

**Comment by broady** [comment]
Yes, "INSERT" will (correctly) fail if you try to insert on something that's already there. And therefore abort the transaction.

If you want to implement upsert (insert if it doesn't exist), then you need to read/query for the entity first within the transaction.

> It still seems wrong that an individual update failing will roll back the whole transaction

That's the purpose of transactions - they are atomic updates. Everything or nothing in the transaction succeeds.

**Comment by colinmarc** [comment]
Ok, I understand now. It seemed like not returning the error was a way of making the client ignore it for the purposes of considering the transaction valid - and I thought that the transaction was succeeding.

I guess this is more an issue of not supporting `ON DUPLICATE KEY`/`ON CONFLICT DO NOTHING` (I know about the undocumented `INSERT-OR-UPDATE`, but that's actually not the same in this case).

Feel free to close, although I think this could be pointed out in the `ReadWriteTransaction` docs:

> If the transaction cannot be committed or if f returns an ABORTED error, ReadWriteTransaction will call f again. It will continue to call f until the transaction can be committed or the Context times out or is cancelled. If f returns an error other than ABORTED, ReadWriteTransaction will abort the transaction and return the error.

I'd change this line:

> If any operation in the transaction fails, or if f returns an error other than ABORTED, ReadWriteTransaction will abort the transaction and return the error encountered. 

And maybe even add something like:

> If an operation fails, the ReadWriteTransaction will return the error even if f returns nil.

**Comment by broady** [comment]
Right, even if you ignore the error in your transaction, the list of mutations that are lined up in the transaction still need to be valid when applied by the server. Returning nil definitely does not guarantee that it's a valid transaction that can be applied.

A better way to think of transactions is that they're a list of mutations (and queries) that are added to in a stateful way, then applied when committed.

/cc @jsimonweb for potential docs updates. Something along those lines might be useful across all languages, not just for Go.

**Comment by colinmarc** [comment]
> A better way to think of transactions is that they're a list of mutations (and queries) that are added to in a stateful way, then applied when committed.

That's interesting and helpful, thanks. I'll note that not all databases handle errors that way; mysql can still commit if an individual write fails, for instance. So probably worth calling out somewhere.

Thanks for your time!

**Comment by broady** [comment]
> mysql can still commit if an individual write fails

Interesting. We'd need to add a way to undo mutations to support something like that.

If you're interested, you can see what's sent along with a commit request behind the scenes here:
https://godoc.org/google.golang.org/genproto/googleapis/spanner/v1#CommitRequest

Currently we only add to the list of Mutations.
