### ISSUE TITLE
Firestore: new index is not picked up by a running client

### ISSUE THREAD

**Issue by vaijab** [googleapis/google-cloud-go#1346]
## Client
Firestore

## Describe Your Environment
go version go1.12 linux/amd64. Go code compiled to a static binary, running on linux and/or in GKE.

## Expected Behavior
Firestore composite index does not exist. Client starts making queries and receives an error `rpc error: code = FailedPrecondition desc = The query requires an index.`.

When a required index gets created, the client should pick it up (without needed a restart/reconnect) and stop returning the error.

## Actual Behavior
The client requires to be restarted for the index to be picked up.

**Comment by jadekler** [comment]
Could you post a minimal repro?

**Comment by jadekler** [comment]
We've asked for clarifying information and not heard from you in a while. Closing this issue but please feel free to reply and continue the conversation.
