### ISSUE TITLE
Enhancement: Upsert for jobs

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1348]
Would be convenient to have a method for ensuring that a named job exists and is configured correctly, rather than having to write this logic ourselves atop the lower level update, create methods.

**Comment by jadekler** [comment]
Sorry, just to clarify, is this firestore?

**Comment by mcandre** [comment]
Nah, jobs for the Google Cloud Scheduler.

**Comment by jadekler** [comment]
Gotcha! Would you mind filing a feature request against the scheduler team at https://b.corp.google.com/issues/new?component=589898&template=1238347?
