### ISSUE TITLE
googleapi: got HTTP response code 400 with body: Invalid multipart request with 0 mime parts.

### ISSUE THREAD

**Issue by TongLi1992** [googleapis/google-cloud-go#1350]
(delete this for feature requests)

## Client

I'm using the storage go client in go routine
I attached the simplest sample code to reproduce the error
[main.go.tar.gz](https://github.com/googleapis/google-cloud-go/files/2943977/main.go.tar.gz)

## Describe Your Environment

go version go1.12 linux/amd64
Environment:  linux

## Expected Behavior

There shouldn't be any error when writing to gcs bucket with the go client 

## Actual Behavior

Got error
` googleapi: got HTTP response code 400 with body: Invalid multipart request with 0 mime parts.`

**Comment by jadekler** [comment]
Related: https://github.com/googleapis/google-cloud-go/issues?utf8=%E2%9C%93&q=multipart

**Comment by jadekler** [comment]
Investigation tracked in https://github.com/golang/go/issues/30693

**Comment by bradfitz** [comment]
https://code-review.googlesource.com/c/google-api-go-client/+/39076 gensupport: fix incorrect MIME boundary being used in bodies on retries

**Comment by dobegor** [comment]
@bradfitz is there a library release which contains a fix for this?

**Comment by jadekler** [comment]
@dobegor `cloud.google.com/go v0.40.0` and `google.golang.org/api v0.6.0` contain this fix.

**Comment by dobegor** [comment]
@jadekler thanks!

**Comment by chihkaiyu** [comment]
@jadekler Hi, I'd upgraded `cloud.google.com/go` to `v0.40.0` and `google.golang.org/api` to `v0.6.0` (and even latest release) and I still got the same error here.  
My golang version is `1.13.5`.

**Comment by jadekler** [comment]
> @jadekler Hi, I'd upgraded `cloud.google.com/go` to `v0.40.0` and `google.golang.org/api` to `v0.6.0` (and even latest release) and I still got the same error here.
> My golang version is `1.13.5`.

Please file a new bug. :)
