### ISSUE TITLE
rpc error: code = InvalidArgument desc = Schedule or time zone is invalid.

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1352]
## Client

Scheduler

## Describe Your Environment

macOS Mojave

## Expected Behavior

Update job request succeeds.

## Actual Behavior

Sometimes the update job request reports an error:

```console
rpc error: code = InvalidArgument desc = Schedule or time zone is invalid.
```

This happens around 1/10 of the time with the same request configuration. As a workaround, I am manually deleting and creating schedules when this happens.

The official godocs for this API say that the TimeZone defaults to UTC. However, the error message indicates this as one of two potential sources of error. So I am now explicitly setting UTC just in case.

**Comment by jadekler** [comment]
Sorry, which client is this for? Also, could you post a small code snippet where you're encountering this error?

**Comment by mcandre** [comment]
The official Go client to the Google Cloud Scheduler API. RPC validation errors are all kinds of generic, too generic to help the programmer identify the source of the error.

**Comment by jadekler** [comment]
cc @bart-at-google any idea what's going on here?

**Comment by jadekler** [comment]
@mcandre Would you mind filing this bug against the scheduler team at https://b.corp.google.com/issues/new?component=589898&template=1238347? They'll help investigate. :)

**Comment by proost** [comment]
@mcandre Hi, I am experiencing same issue.

Condition like this:
1. When update a job
2. config is same as exiting job

Could you share work around?
