### ISSUE TITLE
Different naming conventions used between Google products

### ISSUE THREAD

**Issue by mcandre** [googleapis/google-cloud-go#1354]
GCP API calls use different naming conventions, such as a fully qualified resource name vs. a short name. This happens with topics and instances, for example, depending on which API method is being run.

This happens with both the official Go and official Python libraries for interacting with GCP. Can we please promote one of these naming conventions, so that users can enjoy a more consistent syntax, across the array of available Google Cloud methods?

**Comment by jadekler** [comment]
Could you provide an example?

**Comment by jadekler** [comment]
We've asked for clarifying information and not heard from you in a while. Closing this issue but please feel free to reply and continue the conversation.
