### ISSUE TITLE
all: docs say to use iterator.Done without saying where to find it

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1356]
A lot of our godocs mention "iterator.Done" without saying the path to the iterator package.

e.g., https://godoc.org/cloud.google.com/go/spanner

/cc @noahdietz @jadekler

**Comment by broady** [comment]
Comments from old bug (I filed in the wrong repo):

<hr>

@noahdietz:
> Similar to gapic-generator #2620 and could be solved with the same approach. Shall we add iterator to the types we "identify" with a comment in the generated snippets?

<hr>

@jadekler:
> Maybe it could be solved with a cloud.google.com/go level comment about iterators? We have a similar thing for the option package.

<hr>

@broady:
> @noahdietz Yep, I think so. Let's decide on a style and go with it everywhere. I wonder if we can automate/tool for this across all examples?
> 
> @jadekler top-level is good, but one level of indirection for something that is really core to the packages that have iterators.
> 
> option is in a better state because it has an actual godoc hyperlink into the package, whereas iterator isn't part of the actual API surface, so there's no godoc hyperlink.

**Comment by zaddok** [comment]
+1

I recall first encountering this in the documentation and not having any idea of where to import this from. I worked out that searching the example code here for it here on github would give me the answer, but it probably shouldn’t be like that.

**Comment by noahdietz** [comment]
This will *really* be fixed once we start generating Go clients with the gapic-generator-go. If you want to reopen this until then, fine by me.
