### ISSUE TITLE
Google Vision Web Search returns error.

### ISSUE THREAD

**Issue by lukaszraczylo** [googleapis/google-cloud-go#1357]
Using the code from the example returns error returned in 'actual behaviour' section.
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/vision/detect/detect.go#L379
Running SafeSearch with the same file works completely fine.

## Client

Google Vision API

## Describe Your Environment

An application running in alpine docker, running on K8S in GCE

## Expected Behavior

Returning list of web results

## Actual Behavior

Throwing an error ```rpc error: code = InvalidArgument desc = Request must specify image and features.```

Issue described also in https://github.com/GoogleCloudPlatform/golang-samples/issues/794 as I'm not sure who's responsible for what.

**Comment by jadekler** [comment]
Could you file a bug at https://github.com/GoogleCloudPlatform/golang-samples/issues please?

**Comment by jadekler** [comment]
Oh whoops, I see you filled one out there already. That's the right place, so you're all set! :)

**Comment by lukaszraczylo** [comment]
@jadekler thank you for fast response, really appreciate! I'm also double checking if everything is alright on my side ( just wiped the $GOPATH and re-downloading all the dependencies ).
