### ISSUE TITLE
pubsub:ExpirationPolicy is not included in SubscriptionConfig

### ISSUE THREAD

**Issue by iluminae** [googleapis/google-cloud-go#1361]
## Client
PubSub

## Feature
Ability to set `ExpirationPolicy` on pubsub `SubscriptionConfig{}` object. Currently, `ExpirationPolicy` cannot be set on the subscription. This feature exists in the API and Google Cloud Console when creating a subscription.

here it is in the protobuf:
https://github.com/google/go-genproto/blob/master/googleapis/pubsub/v1/pubsub.pb.go#L953

**Comment by jadekler** [comment]
@sduskis @kir-titievsky @kamalaboulhosn

**Comment by sduskis** [comment]
@jadekler, it would indeed be awesome to have expiration policy and `oidc_token` in the pub/sub subscription CRUD.

**Comment by odeke-em** [comment]
For some status updates, we are almost finished with this feature:

- [x] ExpirationPolicy added with https://github.com/googleapis/google-cloud-go/commit/06e163b5f181cb98f6179f966b1b88cf03b491ec
- [ ] OpenIDConnectToken pending https://code-review.googlesource.com/c/gocloud/+/40771

**Comment by lc-caigwatkin** [comment]
This is a good addition, however, I am not sure how I would use this feature to set the expiration policy to "never expire," a feature which is available through the GCP UI. Did I miss something in the documentation?

**Comment by odeke-em** [comment]
Great question @lc-caigwatkin! So the GCP UI and gcloud cli use a sentinel value of "never" and we are going to mimick the same by providing a NeverExpire constant in a CL coming up shortly.
Thus code to do this will look like this:
```go
package main

import (
	"context"
	"log"
	"time"

	"cloud.google.com/go/pubsub"
)

func main() {
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, "odeke-sandbox")
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	topic, _ := client.CreateTopic(ctx, "issue-1361-t")

	// Create the new subscription
	subName := "sub-1361"
	_, _ = client.CreateSubscription(ctx, subName, pubsub.SubscriptionConfig{
		Topic:            topic,
		AckDeadline:      30 * time.Second,
		ExpirationPolicy: 25 * time.Hour,
	})

	gotSub := client.Subscription(subName)
	cfg, err := gotSub.Config(ctx)
	if err != nil {
		log.Fatalf("Failed to retrieve the config: %v", err)
	}
	log.Printf("Config: %+v\n", cfg)

	<-time.After(1 * time.Minute)
	// Now update it.
	sCfg := pubsub.SubscriptionConfigToUpdate{
		ExpirationPolicy: pubsub.NeverExpire,
	}
	updated, _ := gotSub.Update(ctx, sCfg)
	log.Printf("Updated: %+v\n", updated)
}
```
and you'll be able to verify on the UI that ExpirationPolicy is set to NEVER expire.

**Comment by lc-caigwatkin** [comment]
Thanks @odeke-em 

From looking at your example, is it best practice to first create a subscription that is not set to never expire before updating it as such? Or would simply creating it with pubsub.NeverExpire be just as good?

**Comment by odeke-em** [comment]
That example is just to show you that you can update it. But from the get-go you'll be able to set it to `pubsub.NeverExpire` so during creation too.

**Comment by lc-caigwatkin** [comment]
Excellent! Thanks for your explanation

**Comment by jadekler** [comment]
This is now implemented. See: https://godoc.org/cloud.google.com/go/pubsub#SubscriptionConfig

**Comment by jadekler** [comment]
For posterity: https://code-review.googlesource.com/c/gocloud/+/41211

**Comment by odeke-em** [comment]
I believe this issue can now be closed and all CLs have been merged.
