### ISSUE TITLE
bigtable: grpc with compression?

### ISSUE THREAD

**Issue by uschen** [googleapis/google-cloud-go#1362]
It seems C++ ClientOption exposes 

https://googleapis.github.io/google-cloud-cpp/0.6.0/bigtable/classgoogle_1_1cloud_1_1bigtable_1_1v0_1_1ClientOptions.html#a7b983a96130ccfd167a268b2ee936c38

I wonder if there are any documentations on whether Cloud Bigtable grpc support compression.

**Comment by sduskis** [comment]
I tried turning on compression in the java client.  I believe that Cloud Bigtable service disables compression.

**Comment by jadekler** [comment]
@sduskis Does that mean that we can't implement at the moment?

**Comment by sduskis** [comment]
@jadekler, I believe so.  I'll circle back with the CBT team to confirm.

**Comment by sduskis** [comment]
Compression is not on now.  If and when compression is on, we can revive this discussion.  For now, I think we should close this issue.
