### ISSUE TITLE
Firestore slow queries

### ISSUE THREAD

**Issue by Talento90** [googleapis/google-cloud-go#1364]
## Client
Firestore

## Describe Your Environment
Build with GO version 1.11
Running a static binary in Alpine Docker image on GKE

## Actual Behavior

Querying firestore using GO 1.11 is quite slow. I am doing 2 queries and I expect the first one to be slow since it's the first time the client connects to the db. But the second query is taking around 150ms - 200ms which is a lot for a small collection... 

Code that I am using:
```go
func main() {
	ctx := context.Background()

        opts := option.WithCredentialsFile("...")
	fsApp, err :=  firebase.NewApp(ctx, nil, opts)

	if err != nil {
		log.Fatal("Error connecting to firebase", err)
	}

	client, err := fsApp.Firestore(ctx)

	if err != nil {
		log.Fatal("Error connecting to firestore", err)
	}

	_, err = client.Collection("products").Doc("product-1").Get(ctx)

	if err != nil {
		logger.Fatal(err)
	}

	startTime := time.Now()

	_, err = client.Collection("products").Doc("product-1").Get(ctx)

	if err != nil {
		logger.Fatal(err)
	}

	log.Info(time.Since(startTime))

	log.Info("done")
}
```

**Comment by jadekler** [comment]
cc @mikelehen @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
@Talento90 Thanks for filing this issue! Can you let us know where you are connecting from and where your Firestore instance is located? It looks like you are in London - did you pick one of our European data centers? Please take a look at our list of [supported locations](https://firebase.google.com/docs/firestore/locations).

**Comment by Talento90** [comment]
@schmidt-sebastian Yes, I am based in London and I am using `europe-west2`.

**Comment by schmidt-sebastian** [comment]
As per our backend team,  the read times you report are expected for occasional single document lookups even from London to `europe-west2`. Firestore will perform better if you issue a sustained rate of high requests, at which point all of our backends will be initialized fully, resulting in a reduced processing time for all requests.

**Comment by Talento90** [comment]
@schmidt-sebastian Thanks for your answer! What is a sustained rate of high requests? 10, 100, 1000, 10000 requests? Any documentation that points that?

**Comment by jadekler** [comment]
ping @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
We need more project specific data to be able to diagnose what is causing the slowness here. Can you contact our support team via https://firebase.google.com/support/troubleshooter ?

**Comment by jadekler** [comment]
Closing this - to continue the discussion, please reach out via the link that @schmidt-sebastian provided. Thank you!
