### ISSUE TITLE
storage: crc for range request?

### ISSUE THREAD

**Issue by liamstask** [googleapis/google-cloud-go#1368]
I'm interested in the ability to verify the integrity of a range read via `storage.ObjectHandle.NewRangeReader()`, while it appears that a crc is only calculated in the event that a complete object is read.

The use case I'm interested in is downloading large files, specifically the ability to verify crc (and retry if necessary) on a per-chunk basis rather than retrying the entire download, since it can be slow for multi-GB files.

Any chance this is possible with the existing APIs and I've missed it? Any suggestions would be welcome.

**Comment by jadekler** [comment]
I'm not aware of such a thing, but @frankyn is the authority. Frank, do you know of any per-chunk crc features?

**Comment by frankyn** [comment]
Hi @liamstask, 

Thanks for raising the question. 

At the moment Cloud Storage(GCS) does not support integrity checks using (crc32c or md5) for ranged GETs.  Ref in first warning message: https://cloud.google.com/storage/docs/hashes-etags

At the moment, there's no alternative solution other. The GCS team is aware of this issue, and I'll share the feedback with them.

There are no plans to support this feature in the client library at this time. Closing this issue given the no-op.

**Comment by liamstask** [comment]
Thanks for the feedback - is there an open issue somewhere tracking this feature request? Would be nice to follow along for updates etc.

**Comment by frankyn** [comment]
There is no public issue tracking this request AFAIK. I've filed an issue internally with your feedback, and don't have an estimate on time.

Apologies, the best way to get updates will be by following [release-notes](https://cloud.google.com/storage/docs/release-notes).

ref bug: 128907364
