### ISSUE TITLE
logging: Allow specification of a LogEntry_ProtoPayload as part of the logging payload.

### ISSUE THREAD

**Issue by tmc** [googleapis/google-cloud-go#1369]
In https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L803 the payload field is either set to a 
https://godoc.org/google.golang.org/genproto/googleapis/logging/v2#LogEntry_TextPayload
or a 
https://godoc.org/google.golang.org/genproto/googleapis/logging/v2#LogEntry_JsonPayload

But there is no mechanism to supply a https://godoc.org/google.golang.org/genproto/googleapis/logging/v2#LogEntry_ProtoPayload

Allowing this would allow writing of type.googleapis.com/google.cloud.audit.AuditLog payloads from customers.

**Comment by jadekler** [comment]
cc @dazuma @munangst

**Comment by munangst** [comment]
Can you describe a bit more about your intended use case? `google.cloud.audit.AuditLog` is primarily intended for use by Google Cloud services when writing audit logs. End-user defined protos are not supported because there's no way to configure the proto descriptor, which is required to support converting the `google.protobuf.Any` to JSON.

**Comment by tmc** [comment]
Maybe this could be scoped down to sending AuditLog payloads then? Writing custom AuditLogs is desirable.

**Comment by tmc** [comment]
FWIW I opened https://code-review.googlesource.com/c/gocloud/+/39091

**Comment by nicoleczhu** [comment]
Hi @tmc , can you give more context on your use case? Specifically, 
1. What do you want to include in a custom audit log? 
2. How do you want to use that information down the line (be it as a filter, sink exclusion, etc)?

Alternatively, can you achieve what you need by writing a set of custom labels, or by writing a structured log in the jsonPayload, with your required information?

Audit logs are reserved for GCP services. Modifying these logs will impact other GPC products and UI downstream. At the moment, we do not intend to expose modifying this feature to customers at the client library level.

**Comment by nicoleczhu** [comment]
Hi @tmc , I'll close this issue for now. Feel free to reopen once you provide us with your intended use case. We'll then have a discussion around whether it's something we should support. Thanks!
