### ISSUE TITLE
datastore: why do SaveStruct and LoadStruct use flattened properties instead of using nested entities?

### ISSUE THREAD

**Issue by jhump** [googleapis/google-cloud-go#1371]
Datastore supports field values that are [nested entities](https://cloud.google.com/datastore/docs/concepts/entities#embedded_entity). But `SaveStruct` and `LoadStruct` try to flatten properties instead of using nested entities, in cases where the struct to be saved/loaded has nested structs.

When converting structs that have slices at multiple levels (such as a slice of structs that therein has a field that is a slice of strings), the resulting properties are a bit confusing, using flattened property names that then have nested/multi-dimensional slices for values.

Why does the library use the current approach? Do nested entities incur an undocumented performance penalty? Or was support for them added *after* the `LoadStruct` and `SaveStruct` methods were spec'ed/implemented?

**Comment by jhump** [comment]
I ask because I am considering writing a library for encoding protos as datastore entities, and it feels simplest to model the entities using nested entities (instead of trying to flatten properties, like this library does). So I want to know if there are undocumented disadvantages to that approach.

**Comment by broady** [comment]
History/context: https://groups.google.com/forum/#!topic/google-api-go-announce/79jtrdeuJAg

Maybe there needs to be a separate SaveStruct/LoadStruct that uses nested entities instead of flattening?

**Comment by jadekler** [comment]
Seems like this is answered, so I'll close this issue. Let me know if there's more to discuss here though @jhump.
