### ISSUE TITLE
SIGSEGV in container API

### ISSUE THREAD

**Issue by algermissen** [googleapis/google-cloud-go#1374]
Hi, when doing a cluster-by-name lookup via the SDK, I get a SIGSEGV in

https://github.com/googleapis/google-cloud-go/blob/e567dc8944f58f266e938dac18a179f335adfab7/container/container.go#L167

The call 'stack' is

    cloud.google.com/go/container.(*Client).Cluster(0xc0002b68c0, 0xb98360, 0xc000028040, 0xac0afb, 0xe, 0xabc340, 0x7, 0xc0002b68c0, 0x0, 0x0)
    /go/src/cloud.google.com/go/container/container.go:167 +0x1bf
    cloud.google.com/go/container.resourceFromRaw(0xc000107180, 0x0)

Yesterday this did no show up. My biggest question at the moment is what I changed that makes this error appear? Any clues?

Jan

**Comment by jadekler** [comment]
Regrettably that package is deprecated. Please use `cloud.google.com/go/container/apiv1` instead.
