### ISSUE TITLE
bigtable, spanner: consolidate duplicated OpenCensus tracing code into internal/trace

### ISSUE THREAD

**Issue by odeke-em** [googleapis/google-cloud-go#1376]
While following up with an email request for tasks on this repo I noticed that in 
spanner and bigtable, we've got code that's repeated

### Spanner
https://github.com/googleapis/google-cloud-go/blob/4b031de94b32c3a6b8cf7d64fd2b377ac5859eef/spanner/trace.go#L26-L59

### Bigtable
https://github.com/googleapis/google-cloud-go/blob/4b031de94b32c3a6b8cf7d64fd2b377ac5859eef/bigtable/trace.go#L24-L57

### internal/trace
https://github.com/googleapis/google-cloud-go/blob/4b031de94b32c3a6b8cf7d64fd2b377ac5859eef/internal/trace/trace.go#L27-L84

of which internal/trace has comprehensive code that actually translates RPC errors to proper status and messages that will add the proper status to OpenCensus spans.

and in spanner we use `statsPrintf` but that code is for tracing. I think we can consolidate that trace code into internal/trace.

/cc @jadekler @broady

**Comment by sduskis** [comment]
We need to take the notion of "operations" into account.  Specifically, Bigtable and Spanner will retry the same operation if there's a transient failure.  There ought to be some way of aggregating all RPCs for the same operation into a single trace.

**Comment by jadekler** [comment]
@sduskis This already is the current behavior. There's a parent span that sits on top of all actually-send-an-RPC spans. :)
