### ISSUE TITLE
PubSub - Are NACKed messages retained for longer than 7 days?

### ISSUE THREAD

**Issue by angadn** [googleapis/google-cloud-go#1387]
## Client
PubSub

## Describe Your Environment
Golang

## Question
As the maximum duration for the retention of an 'undelivered' message is 7 days, I am curious as to what a NACK does as regards keeping the message 'alive'.

For example, if I NACK a message one day before its expiry does it get a fresh lease of 7 days before it's dropped, or does it die the next day itself?

I am unsure of of [how to interpret the language of this documentation](https://cloud.google.com/pubsub/docs/subscriber) as a NACKed message technically hasn't failed to deliver, but has been refused by the Subscriber.

**Comment by jadekler** [comment]
Hello! This issue tracker is just for the client library, not for the product as a whole. For a question like this, please file an issue at one of:

- [The Pub/Sub public issue tracker](https://issuetracker.google.com/savedsearches/559741)
- Or, [the Pub/Sub documentation issue tracker](https://googlecloudplatform.uservoice.com/forums/302631-cloud-pub-sub/filters/top)
- Or, [the Pub/Sub stackoverflow](https://stackoverflow.com/questions/tagged/google-cloud-pubsub)

All of these are tracked and responded by the core pub/sub team. :)
