### ISSUE TITLE
translate: godoc broken link

### ISSUE THREAD

**Issue by arxdsilva** [googleapis/google-cloud-go#1389]
## Expected Behavior

Hi! I was reading the link to https://godoc.org/cloud.google.com/go/translation is broken since It is not found by godoc.

## Actual Behavior

The readme link should show infos about the package

**Comment by jadekler** [comment]
Ah, a bit confusing, but the client is called `translate`: https://godoc.org/cloud.google.com/go/translate. Closing since this seems resolved - let me know if you'd like to continue discussion though.

**Comment by jadekler** [comment]
Oh wait! I see what you're saying - the README link is bad. My fault! Fixing.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/39870
