### ISSUE TITLE
all: provide a package for formatting resource names

### ISSUE THREAD

**Issue by gelraen** [googleapis/google-cloud-go#1393]
Please provide a library for formatting resource names. Use of `fmt.Sprintf` I see in documentation examples is too tedious and error-prone.

**Comment by jadekler** [comment]
@gelraen Do you have a specific product in mind?

**Comment by gelraen** [comment]
Not really, but also kind of all of them ¯\\_(ツ)_/¯

Here are a few examples:
https://cloud.google.com/tasks/docs/creating-appengine-tasks
https://cloud.google.com/kms/docs/reference/libraries#using_the_client_library
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account

Basically, any place where you see a literal string ["project/"](https://github.com/GoogleCloudPlatform/golang-samples/search?l=Go&q=%27%22projects%2F%27) should be call to a specialized function that generates the relevant resource name from user-supplied identifiers. If you check [Tasks](https://cloud.google.com/tasks/docs/creating-appengine-tasks) link above and click through examples for different languages you may notice that all of them except Go use a function named "queue path" or "queue name".

**Comment by codyoss** [comment]
We will be moving forward with this feature at this time.
