### ISSUE TITLE
Support for V4 Storage Signing Process

### ISSUE THREAD

**Issue by af-engineering** [googleapis/google-cloud-go#1395]
It seems like `storage.SignedURL()` is creating V2 signed URLs. Using these URLs on our newly created buckets is causing issues:

```Anonymous caller does not have storage.objects.create access to <bucket>/<file>```

Using `gsutil` to create signed V4 URLs, we are able to create and read files on the bucket without issue. Is there a planned timeline for the V4 signing utility?

**Comment by jadekler** [comment]
Yes - this is currently being worked on. Please track in https://code-review.googlesource.com/c/gocloud/+/38870.
