### ISSUE TITLE
bigtable: expose btpb.RowSet as bigtable.RowSet

### ISSUE THREAD

**Issue by uschen** [googleapis/google-cloud-go#1400]
currently there are only:

> RowList, RowRange and RowRangeList

and the range has specified to have a `StartKeyClosed` and `EndKeyOpen` (Why?) comparing to btpb.RowSet that allows both `Keys` and `Ranges` while Range key can be either open or closed.

**Comment by uschen** [comment]
something like this?

https://github.com/nuorder/google-cloud-go/commit/dd8805f114d009a0b4b55105a5194047881116ef

**Comment by uschen** [comment]
or just save a lot of people a lot of hustle:

```go
type RowSet interface {
	Proto() *btpb.RowSet
	RetainRowsAfter(lastRowKey string) RowSet
	Valid() bool
}
```

**Comment by odeke-em** [comment]
Thank you or filing this issue @uschen!

Please help explain what you are trying to do and why we need to expose this?
I ask because your issue was more like a question with 
>and the range has specified to have a StartKeyClosed and EndKeyOpen (Why?) comparing to btpb.RowSet that allows both Keys and Ranges while Range key can be either open or closed.

and then you made a suggestion for an interface in https://github.com/googleapis/google-cloud-go/issues/1400#issuecomment-485661574

I am interested in helping to get this going.

**Comment by uschen** [comment]
@odeke-em thank you for following up.

here is a very simple case:

for value_range filter:

* `start_closed` + `end_closed` => equal.

**Comment by uschen** [comment]
I meant the Filter has the same issue as RowSet

**Comment by uschen** [comment]
and regarding RowSet, it is uncommon to perform both random reads (via Keys) and scans (via ranges) together.

**Comment by telpirion** [comment]
`RowSet` is now exposed as an interface in the client library. See the [reference docs](https://pkg.go.dev/cloud.google.com/go/bigtable#RowSet).

Please reopen this issue if you have additional context to add to this issue.
