### ISSUE TITLE
kms/apiv1 should not panic when no credentials are found

### ISSUE THREAD

**Issue by eclipseo** [googleapis/google-cloud-go#1404]
kms/apiv1 panics when there are no credentials:

```
cloud.google.com/go/kms/apiv1
--- FAIL: TestIntegration (0.00s)
panic: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. [recovered]
	panic: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

Other API like dataproc/apiv1beta2 /expr/apiv1alpha1 or container/apiv1 fail gracefully with a warning message « No 'Application Default Credentials' found. ». It would be great for kms/apiv1 to do the same thing.

**Comment by jadekler** [comment]
Hmmm.. I think all clients panic. Could you provide a small reproduction of a client that does not panic when ADC is not found and credentials are not provided?

**Comment by jadekler** [comment]
We've asked some clarifying questions and not heard back in a while. Closing this issue, but please feel free to respond back if you'd like to continue the discussion.
