### ISSUE TITLE
spanner: fix session pool maintainer race

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1406]
Consider the following snippet: https://github.com/googleapis/google-cloud-go/blob/6beee3ac088c8356efe6e4902bbbf5d986e8e726/spanner/session.go#L977-L1000

The problem with the above code is that we take a lock on the pool to calculate currSessionsOpened and currSessionsInUse, which determines the value of sessionsToKeep, and then we release the lock, and then we replenish/shrink based on sessionsToKeep (in which we take the lock again).

This creates a race condition. In between the first lock acquisition, which we calculate sessionsToKeep, and the second lock acquisition, in which we grow/shrink the pool, the values of currSesssionsInUse and currSesssionsOpened can change.

I'm fairly sure what should happen here is that we lock only once around both our sessionsToKeep calculations as well as replishPool/shrinkPool.

This is a fairly extensive change: it means that we should remove all the locking that happens in replenishPool and shrinkPool (and recursive methods, like sesssion.destroy) and make sure we lock in their calling functions.

**Comment by jadekler** [comment]
Specifically this causes an issue in TestTakeWriteSessionFromIdleList:

- maintainer runs, takes lock, sees 0 open, sets sessionsToKeep=0, releases lock
- Take 10 since lock is free
- Recycle 10 since lock is free
- maintainer takes lock, shrinks to 0, releases lock
- Take 10, expecting from idle list, but actually has to CreateSession

**Comment by odeke-em** [comment]
I just saw this flake too for `TestTakeFromWriteQueue` at https://source.cloud.google.com/results/invocations/18964e53-cd17-4d61-a87e-d73e45a2be09/targets/cloud-go-libraries%2Fgoogle-cloud-go%2Fpresubmit%2Fgo112/log

**Comment by olavloite** [comment]
Fixed by https://github.com/googleapis/google-cloud-go/commit/80979225afc76a1e08783859dc578ff0c0cffabd
