### ISSUE TITLE
Upgrade OpenCensus and Google API versions.

### ISSUE THREAD

**Issue by songy23** [googleapis/google-cloud-go#1408]
Similar to https://github.com/googleapis/google-api-go-client/issues/360.

Sample PR: https://github.com/googleapis/google-cloud-go/pull/1407.

**Comment by songy23** [comment]
@jadekler Could you push a new tag (`+alpha` is also fine) with https://github.com/googleapis/google-cloud-go/commit/96cc533ddb3b6bd450e6ec66aca33d83fb2b3f68?

**Comment by jadekler** [comment]
@songy23 Certainly. I plan to cut a new minor on monday.

**Comment by jadekler** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/v0.38.0 is released.
