### ISSUE TITLE
spanner:  "The code field is required for types" to SQL statement with an empty array 

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-go#1411]
## Client

Spanner

## Notes
This is an issue that was filed internally in 2017. I am unsure if this is still an issue.
internal issue: b/62232721 Cloud Go: "The code field is required for types" to SQL statement with an empty array

## Issue

I feed the following statement to a Spanner transaction:

{SQL:SELECT
  a_1 AS col22,
  (@p2 IN (
    SELECT
      projectscan_15.a_4 AS a_4
    FROM
      (
        SELECT
          filterscan_9.a_4 AS a_4,
          filterscan_9.a_6 AS a_6,
          STRUCT< int64_f INT64 > (- 7379608347939257899) AS a_10,
          filterscan_9.a_5 AS a_11,
          (@p8 IN (
            SELECT
              projectscan_14.a_13 AS a_13
            FROM
              (
                SELECT
                  b"\xfb\xf1\x0d\xcc`%\xc9\xf6\x9e\x90\xafNMOv\\\xe9\xff\xdds\xbe\xc3" AS a_13
              ) AS projectscan_14
          )) AS a_12
        FROM
          (
            SELECT
              flickeringtable_8.a_4 AS a_4,
              flickeringtable_8.a_5 AS a_5,
              flickeringtable_8.a_6 AS a_6,
              flickeringtable_8.a_7 AS a_7
            FROM
              (
                SELECT
                  FlickeringTable.user_id AS a_4,
                  FlickeringTable.folder_id AS a_5,
                  FlickeringTable.flickering AS a_6,
                  FlickeringTable.alterable AS a_7
                FROM
                  FlickeringTable
              ) AS flickeringtable_8
            WHERE
              (flickeringtable_8.a_4) = 1
          ) AS filterscan_9
        WHERE
          @p7
      ) AS projectscan_15
  )) AS col32,
  SESSION_USER() AS col33
FROM
  UNNEST(@p6) AS a_1 WITH OFFSET AS a_2; Params:map[p2:-429028007256875121 p6:[] p7:true p8:[107 150 99 79 180 20 185 223 12 205 172 207 67 108 238 33 152 92 184 64 89]]}

And get this error back: spanner: code = "InvalidArgument", desc = "The code field is required for types."

This happens in every test and I noticed that every time there's an empty array parameter there, so I'm assuming it has to do with arrays. Any idea about what is wrong there? According to my code, p6 above is of type []cloudspanner.Nullstring.

For reference, here's the original request from systest worker:
workid:"workid_888628932" op:1344 read_options:<strong:true > database_path:"projects/spanner-cloud-systest/instances/test-instance/databases/db0" query:<query_request:<options:<experimental:<memory_limit:268435456 > > db:<opaque:"\n?/span/test-cloud-universe/spanner-cloud:ln-0xa583-0x10000000001\020\201\200\200\200\200 " > query:<sql_version:1 sql:<do_not_set_this_field_directly:"SELECT\n  a_1 AS col22,\n  (@p2 IN (\n    SELECT\n      projectscan_15.a_4 AS a_4\n    FROM\n      (\n        SELECT\n          filterscan_9.a_4 AS a_4,\n          filterscan_9.a_6 AS a_6,\n          STRUCT< int64_f INT64 > (- 7379608347939257899) AS a_10,\n          filterscan_9.a_5 AS a_11,\n          (@p8 IN (\n            SELECT\n              projectscan_14.a_13 AS a_13\n            FROM\n              (\n                SELECT\n                  b\"\\xfb\\xf1\\x0d\\xcc`%\\xc9\\xf6\\x9e\\x90\\xafNMOv\\\\\\xe9\\xff\\xdds\\xbe\\xc3\" AS a_13\n              ) AS projectscan_14\n          )) AS a_12\n        FROM\n          (\n            SELECT\n              flickeringtable_8.a_4 AS a_4,\n              flickeringtable_8.a_5 AS a_5,\n              flickeringtable_8.a_6 AS a_6,\n              flickeringtable_8.a_7 AS a_7\n            FROM\n              (\n                SELECT\n                  FlickeringTable.user_id AS a_4,\n                  FlickeringTable.folder_id AS a_5,\n                  FlickeringTable.flickering AS a_6,\n                  FlickeringTable.alterable AS a_7\n                FROM\n                  FlickeringTable\n              ) AS flickeringtable_8\n            WHERE\n              (flickeringtable_8.a_4) = 1\n          ) AS filterscan_9\n        WHERE\n          @p7\n      ) AS projectscan_15\n  )) AS col32,\n  SESSION_USER() AS col33\nFROM\n  UNNEST(@p6) AS a_1 WITH OFFSET AS a_2;" > param:<name:"p2" type:<code:2 > value:<int64_value:-429028007256875121 > > param:<name:"p6" type:<code:10 array_element_type:<code:9 > > value:<> > param:<name:"p7" type:<code:5 > value:<bool_value:true > > param:<name:"p8" type:<code:9 > value:<bytes_value:"k\226cO\264\024\271\337\014\315\254\317Cl\356!\230\\\270@Y" > > proto_descriptors:<> > > >

-------------------------------------------------

One more occurrence:

Statement:

{SQL:SELECT
  limitoffsetscan_4.a_1 AS col1,
  limitoffsetscan_4.a_2 AS col2,
  ARRAY(
    SELECT
      projectscan_10.a_9 AS a_9
    FROM
      (
        SELECT
          limitoffsetscan_4.a_1 AS a_7,
          @p1 AS a_8,
          limitoffsetscan_4.a_1 AS a_9
        FROM
          (
            SELECT
              1
          ) AS singlerowscan_6
        WHERE
          @p0
      ) AS projectscan_10
  ) AS col6,
  @p2 AS col7
FROM
  (
    SELECT
      users_3.a_1 AS a_1,
      users_3.a_2 AS a_2
    FROM
      (
        SELECT
          Users.user_id AS a_1,
          Users.name AS a_2
        FROM
          Users
      ) AS users_3
    WHERE
      (users_3.a_1) = 1
    LIMIT 381 OFFSET 191
  ) AS limitoffsetscan_4; Params:map[p0:true p1:[] p2:["tU\x10#%|\x1d\x0f\x19Y\b\x1aJ\x1bR0f\x18e{C@%'QzE^m]\x02@" "\x19{~$X\a\x1dZ\x04\x11\x11p:i1\x17^;z\x14\x1e0Gv9aO>Fs;\u007fQ;_S\x123hT4\u007f" "/*â‚¬o\x11\vA)?}Wr\x14\x0e\x18H\x04j3,Sz0" "Â¢PxW,i8D[gT7\x10PY;Hw#Ba\x181)r*H%\t\x02:" "\x01{\"\x14qThwJ1\x1fv*\x0f_\a`{\x02.\x028cQz@(\x15\x01\"â‚¬X-\x10$R\x18\x14~)\x1a%m4B\x1dww#`\x1b\x036e\x15\x10if\a" "j\x19â‚¬HL/X\x14.q|Nu\x15\v:q" "\x0frJn\"Nk\f/\x10%zELaÂ¢\nv3Â¢HA\x01h'~{\">y*%7\x1c\"bg;,S`#p'" "\x18XG]DDb\x17k\x11\x19\x1dB?\x1eMgY,.]WO\x17â‚¬" "TI\vg145V{ Q,\x14\td\b\x12QbMc\x036\\p{c35M^@H\tGdRAeFYhð¤­¢b@%5J^" "-=M\x01/l" "Q\x1aX\v\x17pU%/6>~AqW\x1ewbt)W\x1c\x17,(\x13Xfl y(_e\x1bJ\x1bz\n\u007f[,fp\"$â‚¬-+\x01)Sg\x02i8A" "\fW\x01ht(.8+f\x17sc\ne\x0517\t_\vOHs\x1c_B\bHUi=c>\x0eBM\t\x1fð¤­¢J\x12\x19pqc"]]}

ExecuteSqlRequest: session:"projects/spanner-cloud-systest/instances/test-instance/databases/db0/sessions/AAROArXqIVtK1BbRqoz_lFYF3pnghlSEsvayaRCBLDUhC-KjUYudJdHQngOXpgXL" transaction:<single_use:<read_only:<read_timestamp:<seconds:1496271844 nanos:578591000 > return_read_timestamp:true > > > sql:"SELECT\n  limitoffsetscan_4.a_1 AS col1,\n  limitoffsetscan_4.a_2 AS col2,\n  ARRAY(\n    SELECT\n      projectscan_10.a_9 AS a_9\n    FROM\n      (\n        SELECT\n          limitoffsetscan_4.a_1 AS a_7,\n          @p1 AS a_8,\n          limitoffsetscan_4.a_1 AS a_9\n        FROM\n          (\n            SELECT\n              1\n          ) AS singlerowscan_6\n        WHERE\n          @p0\n      ) AS projectscan_10\n  ) AS col6,\n  @p2 AS col7\nFROM\n  (\n    SELECT\n      users_3.a_1 AS a_1,\n      users_3.a_2 AS a_2\n    FROM\n      (\n        SELECT\n          Users.user_id AS a_1,\n          Users.name AS a_2\n        FROM\n          Users\n      ) AS users_3\n    WHERE\n      (users_3.a_1) = 1\n    LIMIT 381 OFFSET 191\n  ) AS limitoffsetscan_4;" params:<fields:<key:"p0" value:<bool_value:true > > fields:<key:"p1" value:<null_value:NULL_VALUE > > fields:<key:"p2" value:<list_value:<values:<string_value:"tU\020#%|\035\017\031Y\010\032J\033R0f\030e{C@%'QzE^m]\002@" > values:<string_value:"\031{~$X\007\035Z\004\021\021p:i1\027^;z\024\0360Gv9aO>Fs;\177Q;_S\0223hT4\177" > values:<string_value:"/*\342\202\254o\021\013A)?}Wr\024\016\030H\004j3,Sz0" > values:<string_value:"\302\242PxW,i8D[gT7\020PY;Hw#Ba\0301)r*H%\t\002:" > values:<string_value:"\001{\"\024qThwJ1\037v*\017_\007`{\002.\0028cQz@(\025\001\"\342\202\254X-\020$R\030\024~)\032%m4B\035ww#`\033\0036e\025\020if\007" > values:<string_value:"j\031\342\202\254HL/X\024.q|Nu\025\013:q" > values:<string_value:"\017rJn\"Nk\014/\020%zELa\302\242\nv3\302\242HA\001h'~{\">y*%7\034\"bg;,S`#p'" > values:<string_value:"\030XG]DDb\027k\021\031\035B?\036MgY,.]WO\027\342\202\254" > values:<string_value:"TI\013g145V{ Q,\024\td\010\022QbMc\0036\\p{c35M^@H\tGdRAeFYh\360\244\255\242b@%5J^" > values:<string_value:"-=M\001/l" > values:<string_value:"Q\032X\013\027pU%/6>~AqW\036wbt)W\034\027,(\023Xfl y(_e\033J\033z\n\177[,fp\"$\342\202\254-+\001)Sg\002i8A" > values:<string_value:"\014W\001ht(.8+f\027sc\ne\00517\t_\013OHs\034_B\010HUi=c>\016BM\t\037\360\244\255\242J\022\031pqc" > > > > > param_types:<key:"p0" value:<code:BOOL > > param_types:<key:"p1" > param_types:<key:"p2" value:<code:ARRAY array_element_type:<code:STRING > > > 

Original request was: workid:"workid_1053778180" op:1316 read_options:<read_timestamp:1496271844578591 > database_path:"projects/spanner-cloud-systest/instances/test-instance/databases/db0" query:<query_request:<options:<experimental:<memory_limit:268435456 root_parallel_failover:<max_concurrent_replica_rpcs:2 timeout_seconds:0.27558564598796725 > > > db:<opaque:"\n?/span/test-cloud-universe/spanner-cloud:ln-0xa583-0x10000000001\020\201\200\200\200\200 " > query:<sql_version:1 sql:<do_not_set_this_field_directly:"SELECT\n  limitoffsetscan_4.a_1 AS col1,\n  limitoffsetscan_4.a_2 AS col2,\n  ARRAY(\n    SELECT\n      projectscan_10.a_9 AS a_9\n    FROM\n      (\n        SELECT\n          limitoffsetscan_4.a_1 AS a_7,\n          @p1 AS a_8,\n          limitoffsetscan_4.a_1 AS a_9\n        FROM\n          (\n            SELECT\n              1\n          ) AS singlerowscan_6\n        WHERE\n          @p0\n      ) AS projectscan_10\n  ) AS col6,\n  @p2 AS col7\nFROM\n  (\n    SELECT\n      users_3.a_1 AS a_1,\n      users_3.a_2 AS a_2\n    FROM\n      (\n        SELECT\n          Users.user_id AS a_1,\n          Users.name AS a_2\n        FROM\n          Users\n      ) AS users_3\n    WHERE\n      (users_3.a_1) = 1\n    LIMIT 381 OFFSET 191\n  ) AS limitoffsetscan_4;" > param:<name:"p0" type:<code:5 > value:<bool_value:true > > param:<name:"p1" type:<code:10 array_element_type:<code:5 > > value:<> > param:<name:"p2" type:<code:10 array_element_type:<code:8 > > value:<string_array_value:<value:"tU\020#%|\035\017\031Y\010\032J\033R0f\030e{C@%'QzE^m]\002@" value:"\031{~$X\007\035Z\004\021\021p:i1\027^;z\024\0360Gv9aO>Fs;\177Q;_S\0223hT4\177" value:"/*\342\202\254o\021\013A)?}Wr\024\016\030H\004j3,Sz0" value:"\302\242PxW,i8D[gT7\020PY;Hw#Ba\0301)r*H%\t\002:" value:"\001{\"\024qThwJ1\037v*\017_\007`{\002.\0028cQz@(\025\001\"\342\202\254X-\020$R\030\024~)\032%m4B\035ww#`\033\0036e\025\020if\007" value:"j\031\342\202\254HL/X\024.q|Nu\025\013:q" value:"\017rJn\"Nk\014/\020%zELa\302\242\nv3\302\242HA\001h'~{\">y*%7\034\"bg;,S`#p'" value:"\030XG]DDb\027k\021\031\035B?\036MgY,.]WO\027\342\202\254" value:"TI\013g145V{ Q,\024\td\010\022QbMc\0036\\p{c35M^@H\tGdRAeFYh\360\244\255\242b@%5J^" value:"-=M\001/l" value:"Q\032X\013\027pU%/6>~AqW\036wbt)W\034\027,(\023Xfl y(_e\033J\033z\n\177[,fp\"$\342\202\254-+\001)Sg\002i8A" value:"\014W\001ht(.8+f\027sc\ne\00517\t_\013OHs\034_B\010HUi=c>\016BM\t\037\360\244\255\242J\022\031pqc" > > > proto_descriptors:<> > > >

-------------------------------------------------

I think there are couple of issues here:
1. In cloud spanner go client, we have a bug where we do not set the param type for array parameters if the value is nil.
This will return param type as nil instead of the correct type.

2. It is not clear to me whether Sergey should be sending nil in the first place since he really wants to bind to an empty array. In cloud spanner request, I would think a null value for array parameter is not the same as an empty array. 

Irrespective of that the bug in go client does need to be fixed.

-------------------------------------------------

Right, but unfortunately in Go, nil slice is a synonym of empty slice. Here's a common pattern:

func Filter(s []int, fn func(int) bool) []int {
    var p []int // == nil
    for _, v := range s {
        if fn(v) {
            p = append(p, v)
        }
    }
    return p
}
(take from the official blog here https://blog.golang.org/go-slices-usage-and-internals)

The return value will be nil if no elements are added. In this I see a certain conflict between Go style and our API.

-------------------------------------------------

So essentially current state is that in the Go client, there is no way to bind a null array as a parameter. If you pass nil it fails. You can explicitly pass an empty array to bind an empty array.
Expected state is that users should be able to bind both a null array and an empty array. jba@ what do you think is the right way to support this? 
One option is that we treat nil as a null array and an empty array as an empty array but that seems to go against idiomatic Go.
Another option is that both nil and empty array are treated as empty arrays. To support null arrays we will then need to do something like what we did for String where we added a specific type called NullString. Complication with that is that null arrays need to be typed so we will need to add multiple such types NullStringArray, NullIntArray etc...

-------------------------------------------------

https://code-review.googlesource.com/13551 fixes the first problem, about returning the right type.

It's not unheard-of to treat nil and empty slices differently. The encoding/json package does this. I think it's reasonable here as well, since, as with JSON, we are encoding a Go value into another representation that distinguishes null and empty.

I'm happy to do the work, but please explain what you want in concrete terms (as in, a case of TestEncodeValue in value_test.go, and also an integration test). Should we represent a nil []int as a NULL value with type ARRAY(INT)? If so, I believe the CL above already does that.

-------------------------------------------------

Just to clarify #11 and #12: The Go client has always distinguished nil and empty slices in mutations, and in parameter binding as well. A nil slice like []int(nil) will result in NULL, and an empty slice like []int{} will result in a zero-length list. 

The only change here is to add the right type information for parameter binding.

You still must pass a typed nil like []int(nil). A plain nil can't be given a type, so should probably be an error in parameter binding.

**Comment by jadekler** [comment]
Closing since the work appears to be done in https://code-review.googlesource.com/13551
