### ISSUE TITLE
Firestore: Support Custom Marsheling and Unmarsheling

### ISSUE THREAD

**Issue by giautm** [googleapis/google-cloud-go#1416]
I wish firestore support custom data type as ([google/uuid](https://github.com/google/uuid)) via custom marshal/unmarshal.

Currently: `firestore: cannot convert type uuid.UUID to value`

**Comment by jadekler** [comment]
Could you provide a small code snippet how you're passing google/uuid to firestore?

**Comment by giautm** [comment]
I added a field name `ID` to structure. Then ran into the error.
```
type State struct {
	ID         uuid.UUID `firestore:"id"`
	Capital    string    `firestore:"capital"`
	Population float64   `firestore:"pop"` // in millions
}
```

**Comment by giautm** [comment]
Hi @jadekler , Do you have any comment?

**Comment by jadekler** [comment]
Looks like the issue is that we don't handle arrays properly (uuid.UUID is a byte array). I've submitted a CL to fix this: https://code-review.googlesource.com/c/gocloud/+/40996

**Comment by giautm** [comment]
Yes, This fix worked. But not the way that I want. UUID was converted to an array of bytes.

![image](https://user-images.githubusercontent.com/12751435/57541452-43f6de00-7379-11e9-9fce-3957593fbecb.png)

**Comment by jadekler** [comment]
Right, that's because [uuid.UUID is an array of bytes](https://github.com/google/uuid/blob/c2e93f3ae59f2904160ceaab466009f965df46d6/uuid.go#L19). :) If you're looking for a string representation, you will have to change the type and do the string conversion yourself.

**Comment by giautm** [comment]
@jadekler : If firestore support `encoding`(https://golang.org/pkg/encoding/) encoding, we can do it easier

**Comment by giautm** [comment]
Hi @jadekler , I created a PR to support encoding/text https://github.com/googleapis/google-cloud-go/pull/1425/files

**Comment by marwan-at-work** [comment]
@giautm @jadekler I stumbled upon this for a similar (but not exact) reason: **it would be really helpful if the client also supported custom JSON Marshaler/Unmarshaler interfaces** 

Do you mind re-opening this issue or maybe I can create a new/separate issue for it? Thanks

**Comment by jadekler** [comment]
@marwan-at-work Yes, please file a new issue.

**Comment by marwan-at-work** [comment]
@jadekler done (https://github.com/googleapis/google-cloud-go/issues/1475) 
thanks!
