### ISSUE TITLE
spanner: refactor retrying

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1418]
Spanner should:

- Use `github.com/googleapis/gax-go/v2` for retrying, replacing all the custom logic in [runRetryable and runRetryableNoWrap](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L168-L207).
- Retry on `codes.Aborted` only, removing entirely our [`transport is closing`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L50-L61), [`streaming terminated by RST_STREAM`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L65-L75), and [`unexpected EOF`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L79-L97) retries. 
  - These should happen approximately never, and when they do happen are probably indicative of some critical failure that we should not retry.
  - These may have been returned by grpc-go when it was younger and buggier. It seems as though a lot of the retry logic in spanner was implemented pre- grpc-go 1.9. (grpc-go is currently at 1.20.1 by comparison)
- Leave _almost all_ retrying to gapic layer (including `UNAVAILABLE` and `UNKNOWN`). The only retrying that should happen in the manual client is retries around transactions in which the retry block ([`runInTransaction`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/transaction.go#L908-L933)) encompasses all transactional RPCs, and ABORTED causes the entire transaction to be rolled back and retried.
  - One likely exception to this is [`StreamingRead`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/read.go#L280), which seems to (correctly) have retry logic around [`resumableStreamDecoder`](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/read.go#L280). This retry logic should probably be replaced with something like a [`gax.OnCodes(ABORTED, UNAVAILABLE, UNKNOWN)`](https://godoc.org/github.com/googleapis/gax-go/v2#OnCodes) rather than doing retry counting and and so on.
  - It's not 100% clear to me whether UNKNOWN and UNAVAILABLE should cause the entire transaction to be rolled back, but from the reading of [ABORTED documentation](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) and [spanner.proto](https://github.com/googleapis/googleapis/blob/39c876cca5403e7e8282ce2229033cc3cc02962c/google/spanner/v1/spanner.proto#L99-L102) I believe these are safe to retry per-RPC, whereas ABORTED should retry the entire transaction.
- Remove the assignment of gRPC codes to errors, as seen for example [here](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/errors.go#L103-L105) and [here](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L38-L46). The _only_ acceptable place to generate gRPC errors is gRPC.
  - This might need to be a separate errors epic.

**Comment by jadekler** [comment]
cc @broady @olavloite

**Comment by jadekler** [comment]
Made some progress on this in https://code-review.googlesource.com/c/gocloud/+/40790, but not sure if I have the time to continue. Thought I'd record my thoughts in the meantime if someone else has more time.

**Comment by olavloite** [comment]
Reopening as there is still some work to do on this.

**Comment by olavloite** [comment]
Custom retry loops have been replaced with standard GAX retryers where applicable. All other retries are handled by GAPIC. As noted above: Removing/refactoring the assignment of gRPC codes to errors should be handled in a separate issue.

**Comment by apstndb** [comment]
> Retry on codes.Aborted only, removing entirely our [transport is closing](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L50-L61), [streaming terminated by RST_STREAM](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L65-L75), and [unexpected EOF](https://github.com/googleapis/google-cloud-go/blob/06e163b5f181cb98f6179f966b1b88cf03b491ec/spanner/retry.go#L79-L97) retries.

It seems that the retry on `RST_STREAM` has been restored. Now, is it considered safe to retry?https://github.com/googleapis/google-cloud-go/pull/6699
