### ISSUE TITLE
monitoring: missing method for notification client

### ISSUE THREAD

**Issue by avdhoot** [googleapis/google-cloud-go#1419]
## Client
monitoring/notification_channel_client

## Describe Your Environment
ubuntu 18.04, go1.11.5

## Expected Behavior
Missing some method for monitoring notification client which documented in api page:

- GetNotificationChannelVerificationCode
- SendNotificationChannelVerificationCode
- VerifyNotificationChannel

## Actual Behavior

- GetNotificationChannelVerificationCode
- SendNotificationChannelVerificationCode
- VerifyNotificationChannel

This method should available in go client sdk 

Let me know if I am missing something. I am very new to go lang.

**Comment by jadekler** [comment]
Hello! This is fairly intentional: the upper-level clients roughly try to cover 80 or 90% of the usecases of the underlying clients. If you'd like to use those methods, please see the underlying auto-generated library https://godoc.org/cloud.google.com/go/monitoring/apiv3.

That said, happy to mark this a feature request and we'll see about adding those to the upper-level client.

**Comment by avdhoot** [comment]
Thanks for reply. Looks like auto-generated library also does not provide that. Hope I am not missing something.

**Comment by jadekler** [comment]
I notice a [GetNotificationChannel](https://godoc.org/cloud.google.com/go/monitoring/apiv3#NotificationChannelClient.GetNotificationChannel) and [CreateNotificationChannel](https://godoc.org/cloud.google.com/go/monitoring/apiv3#NotificationChannelClient.CreateNotificationChannel). Are these what you're looking for?

**Comment by avdhoot** [comment]
Looking for `GetNotificationChannelVerificationCode` `SendNotificationChannelVerificationCode` `VerifyNotificationChannel`

**Comment by jadekler** [comment]
@avdhoot Which API documentation advertises these?

**Comment by avdhoot** [comment]
API [doc](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.notificationChannels) 
I think this Low level API. Not sure.  [link](https://github.com/google/go-genproto/blob/54afdca5d873f7b529e2ce3def1a99df16feda90/googleapis/monitoring/v3/notification_service.pb.go#L799)  Not sure how to use it.

**Comment by jadekler** [comment]
For posterity, I've filed internal bug 132366696.

**Comment by jadekler** [comment]
Tracking internally. Thanks for notifying us.
