### ISSUE TITLE
opencensus: how do I turn off span creation?

### ISSUE THREAD

**Issue by chaserchen** [googleapis/google-cloud-go#1420]
I use pubsub module to receive queue message.
When I start my subscriber service, create to many spans like "driver.Subscription.ReceiveBatch".
I found this code in a for loop and I can't stop it.
https://github.com/google/go-cloud/blob/master/pubsub/pubsub.go#L679

Now, I don't need these spans like "driver.Subscription.ReceiveBatch", What can I do?

Thanks

**Comment by odeke-em** [comment]
Hello @chaserchen, thank you for reporting this issue and welcome to the Go cloud project!

So you can turn off span creation by passing in a context with the [opencensus.trace.NeverSample()](https://godoc.org/go.opencensus.io/trace#NeverSample) sampler so
```go
import (
   "context"

   "go.opencensus.io/trace"
)

ctx, fauxSpan := trace.StartSpan(context.Background(), "neverSampled",
                                 trace.WithSampler(trace.NeverSample()))
fauxSpan.End()

// Then use the above ctx to pass instead of context.Background() or use it
// with the context parent methods.
sub, err := client.CreateSubscription(ctx, "subName", pubsub.SubscriptionConfig{
    Topic:            topic,
    AckDeadline:      10 * time.Second,
    ExpirationPolicy: 25 * time.Hour,
})
```

That's the same style that we use for locally monitoring spans from exporters but ensuring that those spans are never exported.

Hope this helps. I am happy to discuss more and thank you!

**Comment by chaserchen** [comment]
Thank you!
