### ISSUE TITLE
bigquery: Query Parameters should be settable via a method

### ISSUE THREAD

**Issue by m-wynn** [googleapis/google-cloud-go#1426]
The recommended way to set query parameters is:

```go
ctx := context.Background()
client, err := bigquery.NewClient(ctx, "project-id")
q := client.Query("select num from t1 where name = @user")
q.Parameters = []bigquery.QueryParameter{
    {Name: "user", Value: "Elizabeth"},
}
```

This makes it very difficult to use an interface for Client and Query, as interfaces cannot have attributes.  This complicates mocking BigQuery in tests.

It would be nice to be able to do something like:

```go
ctx := context.Background()
client, err := bigquery.NewClient(ctx, "project-id")
q := client.Query("select num from t1 where name = @user")
q.SetParameters(
    []bigquery.QueryParameter{
        {Name: "user", Value: "Elizabeth"},
    }
)
```

**Comment by shollyman** [comment]
I'm a bit hesitant to add methods for this, as there's a large number of settable properties beyond just query parameters.  Are you mocking the whole query flow, or just particular interactions?

**Comment by m-wynn** [comment]
I've switched away from Go.  Feel free to close this.
