### ISSUE TITLE
pubsub: Pull Subcription with GVisor (CloudRun) issue

### ISSUE THREAD

**Issue by guillaumeblaquiere** [googleapis/google-cloud-go#1430]
Hello

I would like to pull a Google PubSub subscription. It works well locally but when I deploy it on Cloud Run, impossible to pull any message.

Here my code snippet
```
func (pubSubService *pubSubService) Received() (msgArray []*pubsub.Message, err error) {
    ctx := context.Background()
    cctx, cancel := context.WithCancel(ctx)
    msgArray = []*pubsub.Message{}

    var receivedMessage = make(chan *pubsub.Message)

    go func() {
        for {
            select {
            case msg := <-receivedMessage:
                msgArray = append(msgArray, msg)
            case <-time.After(pubSubService.waitTimeOutInMillis * time.Millisecond):
                cancel()
            }
        }
    }()

    err = pubSubService.client.Subscription(pubSubService.subscriptionName).Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
        receivedMessage <- msg
        msg.Ack()
    })
    if err != nil {
        return
    }

    return
}
```

Here the log error on cloud run

```
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x7,0x6,0x12,0xc00006f204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x5,0x6,0x12,0xc0003c1204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0xa,0x6,0x12,0xc0003bd204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0xc,0x6,0x12,0xc00037d204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x6,0x6,0x12,0xc0002d3204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x8,0x6,0x12,0xc00052b204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x9,0x6,0x12,0xc000391204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0xb,0x6,0x12,0xc00043b204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x6,0x6,0x12,0xc0003b3204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0xc,0x6,0x12,0xc0003d3204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x7,0x6,0x12,0xc000391204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0x5,0x6,0x12,0xc000309204,0x4,0x0) 
D  Container Sandbox Limitation: Unsupported syscall setsockopt(0xb,0x6,0x12,0xc0004d3204,0x4,0x0) 
```

The Received call is filtered by the GVisor sandbox of Cloud Run

Do you know workarround or ReceiveSetting to set for this issue ? Thanks in advance.

There is also sandbox limitation log entries when publishing messages but it's not blocking (message are published despite the logs)

(related Stackoverflow issue : https://stackoverflow.com/questions/56197404/pubsub-pull-subcription-with-gvisor-cloudrun-issue)

**Comment by ahmetb** [comment]
What you’re seeing (“sandbox limitation”) is not necessarily an error. Some languages try to make use of new syscalls and options when they are available, but often they have a fallback.

I assume your app actually works fine. 

Your app doesn’t work because Cloud Run apps aren’t supposed to do background tasks. They work when they receive requests. So it’s normal that your Run app can’t poll PubSub. 

Try using PubSub with push mode. Cloud Run website has a tutorial about this.

**Comment by guillaumeblaquiere** [comment]
Pubsub push works fine (deployed on other microservice of this project) but that doesn't fit my design. I would like to poll periodically the pubsub subscription, make a file and load it into BigQuery. Load job is free. Pubsub push means streaming into BigQuery, and it's not free. But, it's a possible fallback (Or I will also try in Python3)

Anyway, there is no option for preventing the background process but rather to use a Go Routine for example ?

**Comment by guillaumeblaquiere** [comment]
@ahmetb I dig into the code and nothing seems strange or running stuff in background. Only Goroutine.
But I found my issue : I over estimated the GCP global network: My timeout which cancel the polling was set to 200ms. With this requirement, my app don't have the time to recover the first message before the cancel. With 2000ms of timeout, it work perfectly !

I close this issue. Sorry for the false alert!

**Comment by ahmetb** [comment]
Yeah it is background stuff. Your app is polling for pubsub in the background.  That’s not how Cloud Run apps are supposed to work. 

Please refer to the PubSub tutorial on Cloud Run docs.

**Comment by guillaumeblaquiere** [comment]
@ahmetb, it's not a background async (which won't work on Cloud Run, I agree with you), it's background sync. I mean by this, the poll in the Goroutine is performed during the http request processing. I wait the end of the poll before replying to the request. By the way, the execution context is still up during the poll.

For me, it's the standard behavior. I will loop with Steren to be sure.
