### ISSUE TITLE
KMS client creating a binding between a service account and a role

### ISSUE THREAD

**Issue by kangarlou** [googleapis/google-cloud-go#1431]
(delete this for feature requests)

## Client
KMS

## Describe Your Environment
I'm running KMS client on a MacBook Pro (10.13.6).

## Expected Behavior
I have two service accounts. The first service account has been granted all KMS IAM roles. The second service account has been granted no KMS IAM roles. The first service account creates a key ring and tries to bind the second service account with the key ring and the `roles/cloudkms.cryptoKeyEncrypterDecrypter` role.

```
        handle := client.ResourceIAM(keyRingResourceID)
	policy, err := handle.Policy(ctx)
	if err != nil {
		return nil, err
	}
	log.WithFields(log.Fields{
		"keyRing": keyRingResourceID,
		"roles":   policy.Roles(),
		"members": policy.Members("roles/cloudkms.cryptoKeyEncrypterDecrypter"),
	}).Debug("Retrieved IAM roles.")
       policy.Add("serviceAccount:mysa@myproject.iam.gserviceaccount.com", "roles/cloudkms.cryptoKeyEncrypterDecrypter")
       
        // Verify the new policy.
	handle = client.ResourceIAM(keyRingResourceID)
	policy, err = handle.Policy(ctx)
	if err != nil {
		return nil, err
	}
	log.WithFields(log.Fields{
		"keyRing": keyRingResourceID,
		"roles":   policy.Roles(),
		"members": policy.Members("roles/cloudkms.cryptoKeyEncrypterDecrypter"),
	}).Debug("Retrieved IAM roles.")
```
I appreciate if you could confirm `policy.Add("serviceAccount:mysa@myproject.iam.gserviceaccount.com", "roles/cloudkms.cryptoKeyEncrypterDecrypter")` has the right syntax to set a policy binding.

## Actual Behavior
If I use gcloud (`gcloud kms keyrings add-iam-policy-binding mykeyring --location global --member serviceAccount:mysa@myproject.iam.gserviceaccount.com --role roles/cloudkms.cryptoKeyEncrypterDecrypter`) or the Cloud Console to create the binding, I can see the Go client retrieving the roles and members associated with a policy properly. However, I want to know what's the proper way to set the policy binding using the Go client package.

**Comment by jadekler** [comment]
cc @jskeet @bdhess

**Comment by jskeet** [comment]
So what happens with the code you've got at the moment? What does it log? (To be clear, I have no experience of doing this in code either - and I don't know the Go IAM API.)

**Comment by kangarlou** [comment]
`policy.Add("serviceAccount:mysa@myproject.iam.gserviceaccount.com", "roles/cloudkms.cryptoKeyEncrypterDecrypter")` doesn't have any impact, so the logs don't show anything different before and after this statement (no roles, no members). Also, https://github.com/googleapis/google-cloud-go/blob/398f4508a26f0c3d933f32c128523e5701756506/iam/iam.go#L211 doesn't return anything, so I have no idea what went wrong with `policy.Add`.

**Comment by jadekler** [comment]
Friendly ping @jskeet @bdhess

**Comment by jskeet** [comment]
Not quite sure what's expected from me here - I can try doing the equivalent in the C# client, if that would be useful? (I'm certainly no expert in KMS...)

**Comment by jadekler** [comment]
Add does not perform an RPC - it just changes the local state. Use [SetPolicy](https://godoc.org/cloud.google.com/go/iam#Handle.SetPolicy) to set the policy.
