### ISSUE TITLE
datastore: Confusing error on transaction commit

### ISSUE THREAD

**Issue by havardk** [googleapis/google-cloud-go#1434]
For a datastore transaction, the commit RPC can sometimes return DeadlineExceeded. If it does it seems like the transaction may have completed successfully.  There is some mention of this on this page: https://cloud.google.com/appengine/articles/life_of_write

If this happens, the datastore RPC client (https://github.com/googleapis/google-cloud-go/blob/master/datastore/client.go) will always retry the RPC, and if the transaction completed previously the transaction commit will typically return an error with: code = InvalidArgument desc = transaction closed.  This return value is confusing, since it make it seem like the caller did something wrong.   I think it would be better to return the DeadlineExceeded error to the client, so that the client can understand what happened, and can decide what to do about it.

There is an example of this happening in #1282

**Comment by jadekler** [comment]
Thanks for reporting this. It'll need some investigating. I'm not sure whether it's a bug or intended behavior, so I've just called this issue a feature request for now. Will try to find a datastore person to investigate.

**Comment by BenWhitehead** [comment]
I was able to get in touch with someone from the backend team, this is their assessment

> This is the intended behavior on the server. I would not recommend that clients retry transactional commits by default on deadline_exceeded. Note however that non-transactional commits are generally safe to retry.
> (this depends on the value of `mode` in the CommitRequest: https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto#L215)

Based on the above, I believe this is a bug, and we need to look into updating the client to only retry in the case of a [`NON_TRANSACTIONAL`](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto#L208) commit, otherwise return the DeadlineExceeded error.

@jadekler Do you know off the top of your head if this change should be relatively straightforward?

**Comment by jadekler** [comment]
We should never retry `DEADLINE_EXCEEDED` or `CANCELED`: these can be generated by user-provided deadlines or cancellations (ex https://godoc.org/context#WithDeadline, https://godoc.org/context#WithCancel).

However, we could increase the gapic-provided deadline.

@havardk btw, are you seeing a context deadline? If so, the above is moot, and the solution may be as simple as increasing the deadline.

**Comment by havardk** [comment]
No I'm not seeing a context deadline.  If that were the case, I don't think the request would have been sent to the server a second time.  As I mentioned in the original report, DEADLINE_EXCEEDED errors are always retried:  https://github.com/googleapis/google-cloud-go/blob/b9197a057a6cb1129f29cd21ca11d1bb043666d1/datastore/client.go#L108-L117

**Comment by jadekler** [comment]
That retry should not be happening. I'll call this a p2, since it seems like something you could work around, but let me know if you think this should be a higher priority.

**Comment by tritone** [comment]
The official documentation at https://cloud.google.com/datastore/docs/concepts/errors recommends "Retry using exponential backoff" for DEADLINE_EXCEEDED. Given this, I'm hesitant to remove the retry, given that users may be depending on this behavior currently. @jadekler what do you think?

**Comment by jadekler** [comment]
`DEADLINE_EXCEEDED` must never be retried and that page should be updated accordingly. https://aip.dev/194

**Comment by tritone** [comment]
Okay, that seems pretty definitive. Will put up a PR to remove this.

**Comment by tritone** [comment]
Retry for DEADLINE_EXCEEDED has been removed; now this error will be returned to the caller instead.
