### ISSUE TITLE
datastore: Project() results in type mismatch between int and time.Time

### ISSUE THREAD

**Issue by jshore1296** [googleapis/google-cloud-go#1439]
## Client

Datastore

## Describe Your Environment

go111 runtime in Appengine Standard, using v0.39.0 of the google-cloud-go sdk

## Expected Behavior

queries that contain .Project() on a time column don't fail with an int -> time.Time type mismatch iff the same query without .Project() doesn't fail.

## Actual Behavior

See the code in https://github.com/jshore1296/datastoreProjectionBug

It seems that if a struct contains a time.Time field, then you cannot project on that field in a query without getting an error like `cannot load field "Created" into a "main.MyStruct": type mismatch: int versus time.Time`.

When I deployed and ran this code, the following text was returned:
```
WorkingQuery:
Keys: [/MyStruct,5710211792764928 /MyStruct,5757332281622528 /MyStruct,5676084116848640 /MyStruct,5701325169885184 /MyStruct,5711670806577152]
Values: [{Name:Struct-0 Created:2019-05-29 12:54:52.070884 +0000 UTC} {Name:Struct-1 Created:2019-05-29 12:54:52.86181 +0000 UTC} {Name:Struct-2 Created:2019-05-29 12:54:53.179045 +0000 UTC} {Name:Struct-3 Created:2019-05-29 12:54:53.564619 +0000 UTC} {Name:Struct-4 Created:2019-05-29 12:54:53.836069 +0000 UTC}]
BadQuerydatastore: cannot load field "Created" into a "main.MyStruct": type mismatch: int versus time.Time
```

**Comment by jadekler** [comment]
Could you please link to a specific file, or post a code snippet?

**Comment by jshore1296** [comment]
There's a minimal example in the repo I linked here: https://github.com/jshore1296/datastoreProjectionBug/blob/master/src/app/main.go

**Comment by jadekler** [comment]
I'm unable to reproduce. Could you take a look at this test and tell me if perhaps I missed something?

```
func TestIntegration_Project_TimestampStoreAndRetrieve(t *testing.T) {
	ctx := context.Background()
	client := newTestClient(ctx, t)
	defer client.Close()

	type T struct{ Created time.Time }

	now := time.Now()
	k, err := client.Put(ctx, IncompleteKey("foo", nil), &T{Created: now})
	if err !=  nil {
		t.Fatal(err)
	}
	defer func() {
		if err := client.Delete(ctx, k); err != nil {
			log.Println(err)
		}
	}()

	q := NewQuery("foo").Order("Created")
	res := []T{}
	if _, err := client.GetAll(ctx, q, &res); err != nil {
		t.Fatal(err)
	}
	if len(res) != 1 {
		t.Fatalf("expected 1 result, got %d", len(res))
	}
	if got, want := res[0].Created.Unix(), now.Unix(); got != want {
		t.Fatalf("got %v, want %v", got, want)
	}
}
```

**Comment by jshore1296** [comment]
Can you try it with a `NewQuery("foo").Order("Created").Project("Created")` ?

**Comment by jadekler** [comment]
Whoops! Sorry. Yes, that causes the bug.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/41572

**Comment by jshore1296** [comment]
Thanks for the help!

**Comment by jadekler** [comment]
Of course! Thanks for filing this bug!
