### ISSUE TITLE
testutil.NewServerWithPort doesn't work in IPv6-only environments

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1442]
If I replace 127.0.0.1 with [::1], then it works fine, but perhaps there's some more agnostic way that doesn't break if a server is missing either of ipv4 or ipv6.

## Expected Behavior

Tests pass.

## Actual Behavior

gRPC service tests fail with `listen tcp 127.0.0.1:0: socket: address family not supported by protocol`

**Comment by Capstan** [comment]
Just using `localhost` seems to work for IPv6-only as well.

**Comment by jadekler** [comment]
Thanks for reporting this. Good point. cc @hongalex
