### ISSUE TITLE
`gcloud deploy app` fails for Go app on Windows 10 when local `GOPATH` has differing casing

### ISSUE THREAD

**Issue by scan** [googleapis/google-cloud-go#1445]
Apologies if this is not the right place to raise this issue. I'm currently learning to work with Google App Engine.

When I try to deploy a Go app using the `gcloud` CLI on Windows 10, I get an error message about it not being in `GOPATH`. I checked the `$GOPATH` on my machine, an it was set to `%USERPROFILE%\go`, while the actual folder was named `C:\Users\Tom\Go`. Since Windows uses a case-insensitive file system, this caused no problems with running Go code locally.

## Client

`gcloud` client on Windows 10

## Describe Your Environment

Go 1.12.5, using PowerShell Core 6.

## Expected Behavior

Deploy goes through without an error.

## Actual Behavior

I get the following error message

```
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build ed47fe27-9500-4012-a825-86e65157188b status: FAILURE.
Error ID: FAB35585.
Error type: BuildError.
Error message: 2019/06/01 20:18:59 Copying /workspace/_gopath/src/cloud.google.com to /tmp/staging098174360/srv/gopath/src/cloud.google.com
2019/06/01 20:18:59 Copying /workspace/_gopath/src/github.com to /tmp/staging098174360/srv/gopath/src/github.com
2019/06/01 20:18:59 Copying /workspace/_gopath/src/go.opencensus.io to /tmp/staging098174360/srv/gopath/src/go.opencensus.io        
2019/06/01 20:18:59 Copying /workspace/_gopath/src/golang.org to /tmp/staging098174360/srv/gopath/src/golang.org
2019/06/01 20:18:59 Copying /workspace/_gopath/src/google.golang.org to /tmp/staging098174360/srv/gopath/src/google.golang.org      
2019/06/01 20:18:59 Your app is not on your GOPATH, this build may fail.
2019/06/01 20:18:59 Building from Go source in /tmp/staging098174360/srv, with main package at ./...
2019/06/01 20:18:59 Building /tmp/staging098174360/srv, saving to /tmp/staging098174360/usr/local/bin/start
2019/06/01 20:19:01 Wrote build output to /builder/outputs/output
2019/06/01 20:19:01 Failed to build app: Your app is not on your GOPATH, please move it there and try again.
building app with command '[go build -o /tmp/staging098174360/usr/local/bin/start ./...]', env '[PATH=/go/bin:/usr/local/go/bin:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=3203526548f5 HOME=/builder/home BUILDER_OUTPUT=/builder/outputs DEBIAN_FRONTEND=noninteractive GOROOT=/usr/local/go/ GOPATH=/go GOPATH=/tmp/staging098174360/srv/gopath]': err=exit status 1, out=go build: cannot use -o with multiple packages.
```

It took me a while to realise that the `GOPATH` this message was complaining about is the one on my _local_ machine, not the one in the app engine. Nowhere in the message I could find an indication for this. Once I fixed my local `GOPATH` to `%USERPROFILE%\Go`, I could deploy.

I know this is an edge case, but it would be helpful to either have a more helpful message for this or make sure the deploy process can deal with case-insensitive file systems.

**Comment by jadekler** [comment]
Hello! Would you mind directing this question to https://stackoverflow.com/questions/tagged/google-app-engine? There are several googlers looking out for questions there, as well as community members. It also lets community members in the future find answers faster. :)
