### ISSUE TITLE
Google Cloud Docs Not Synced With API Docs

### ISSUE THREAD

**Issue by martinomburajr** [googleapis/google-cloud-go#1446]
## Client

Scheduler

## Describe Your Environment

Windows (Local)

## Issue

The [GCP docs on the Cloud Scheduler](https://cloud.google.com/scheduler/docs/reference/rest/v1/projects.locations.jobs/create) showcase the use of a different api and technique to create a scheduler client and use it. Not sure which one is the recommended approach.

**Comment by jadekler** [comment]
Thanks for reporting this. Would you mind using the "Send Feedback" button on that page to send that feedback? This helps route it to the right people, and helps us track per-page feedback. Thanks again!
