### ISSUE TITLE
Handle new Google Cloud Storage endpoints before 2019/06/20

### ISSUE THREAD

**Issue by NguyenMinhQuang** [googleapis/google-cloud-go#1447]
Hello

I received a mail from CGS for update the new endpoint storage.googleapis.com :

> Hello Google Cloud Storage Customer,
> We are writing to let you know that starting June 20, 2019, Cloud Storage will allow JSON API requests to be sent to storage.googleapis.com in addition to www.googleapis.com (the current endpoint).
> What do I need to know?
> On June 20, 2019, we will begin updating the Cloud Client Libraries and gsutil to use the new endpoint; storage.googleapis.com. After the update, your JSON API requests will start using the new endpoint.
> What do I need to do?
> If your production or test code doesn't check for endpoint-specific details, no action is required on your part.
> If your production or test code checks for endpoint-specific details, you will need to modify them before June 20, 2019 as follows:
> •	If your code checks that the ‘baseUrl’ or ‘rootUrl’ fields in the JSON API Discovery document point to www.googleapis.com, you will need to modify those checks to allow either storage.googleapis.com or www.googleapis.com. Note that the oauth2 scopes fields in the Discovery document will not change and will continue to point to www.googleapis.com.
> •	If your code checks that the ‘selfLink’ field in bucket or object metadata points to www.googleapis.com, you will need to modify that check to allow either storage.googleapis.com or www.googleapis.com.
> •	If you access Cloud Storage through a firewall, you will need to ensure that requests to storage.googleapis.com are allowed by your firewall rules.

In project, i'm using url which it is just called out via golib.
I'm not sure whether there will be an effect or not, when GCS updates the new endpoint.
My golang library is in use:

> go get -v -u golang.org/x/oauth2
> go get -v -u golang.org/x/text
> go get -v -u golang.org/x/crypto/...
> go get -v -u golang.org/x/exp/...
> go get -v -u golang.org/x/image/...
> go get -v -u golang.org/x/mobile/...
> go get -v -u golang.org/x/net/...
> go get -v -u golang.org/x/oauth2/...
> go get -v -u golang.org/x/sync/...
> go get -v -u golang.org/x/sys/...
> go get -v -u golang.org/x/text/...
> go get -v -u golang.org/x/tools/...

**Comment by jadekler** [comment]
No additional work is necessary if you are consuming GCS through this library.
