### ISSUE TITLE
firestore: support distributed counters

### ISSUE THREAD

**Issue by marwan-at-work** [googleapis/google-cloud-go#1448]
https://firebase.google.com/docs/firestore/manage-data/add-data

**Comment by jadekler** [comment]
cc @benwhitehead @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
We have documentation for how implement Distributed Counters in the Mobile SDKs here: https://firebase.google.com/docs/firestore/solutions/counters

This should work similarly in the Go SDK.

**Comment by odeke-em** [comment]
@iIlyaFaer is working on this issue as per CL https://code-review.googlesource.com/c/gocloud/+/43192

**Comment by BenWhitehead** [comment]
@marwan-at-work Are you asking that support for [Increment a numeric value](https://firebase.google.com/docs/firestore/manage-data/add-data#increment_a_numeric_value) be added to the Go SDK?

If so, it was implemented and merged last week in https://github.com/googleapis/google-cloud-go/commit/727795a4db72ea4a4cbe02f494a33cb87f1cc267 and released in `v0.44.3`. Unfortunately we haven't had a change to update the docs yet, but there is an example usage in that commit that you could refer to in the meantime [here](https://github.com/googleapis/google-cloud-go/blob/727795a4db72ea4a4cbe02f494a33cb87f1cc267/firestore/examples_test.go#L611-L645).

**Comment by marwan-at-work** [comment]
@BenWhitehead that looks great, thank you! Will try it out very soon
