### ISSUE TITLE
rpcreplay doesn't work in IPv6-only environments

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1450]
Analogous to issue #1442.

`rpcreplay.Connection` connects to 127.0.0.1, which will fail with `listen tcp 127.0.0.1:0: socket: address family not supported by protocol` on an IPv6-only machine.

**Comment by Capstan** [comment]
`fake_test.go` has an additional instance of it

**Comment by jadekler** [comment]
cc @jba
