### ISSUE TITLE
httpreplay's test doesn't work in IPv6-only environments

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1451]
Analogous to issue #1442 and issue #1450.

gc go1.12.5 for linux/amd64

If you test httpreplay_test.go in an IPv6-only environment, it will fail with the error

```
…/httpreplay_test.go:278: listen tcp4 :0: socket: address family not supported by protocol
```

under `TestRemoveAndClear` [here](https://github.com/googleapis/google-cloud-go/blob/master/httpreplay/httpreplay_test.go#L276). Perhaps the martian proxy is somehow erecting an IPv4-only proxy? (I have not dug in yet.)

/cc @jadekler @jba

**Comment by hongalex** [comment]
So the issue seems to be related to the fact we switched awayfrom IPv6 sockets for these tests due to an issue with Travis as indicated in [this commit](https://github.com/googleapis/google-cloud-go/commit/45cf3e15d299a55070c9c75f92b61c1d31d1429a).

**Comment by jadekler** [comment]
@hongalex We no longer use travis, so maybe we can now revert that?

**Comment by Capstan** [comment]
If that doesn't work, you could take the net/http/httptest approach and [fall back on ipv6 if trying to listen on ipv4 didn't work](https://github.com/golang/go/blob/go1.12.5/src/net/http/httptest/server.go#L63).

**Comment by hongalex** [comment]
https://code-review.googlesource.com/c/gocloud/+/41731

For now, let's just continue using `localhost` since it matches the format we have for other tests.
