### ISSUE TITLE
storage: support bucket.location_type

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-go#1452]
Location type is a new read-only field for buckets. This corresponds to internal bug 130188026. 

Location type will be a new field added for Bucket resource. It will be populated on-the-fly for output path, and is a read-only field so patch/update/create will not have any effect on bucket resource.
Example

Google Cloud Storage Python client library feature request: Add location type on bucket
```
// Get bucket
storage_client = storage.Client()
bucket = storage_client.get_bucket("bucket-name")

// Get location type
location_type = bucket.location_type

// Request:
// GET https://www.googleapis.com/storage/v1/b/bucket-name?fields=locationType
// Response Body
// {
//   "locationType": "multi-region"
// }
```

**Comment by JesseLovelace** [comment]
Note: The current location type values are "MULTI_REGION", "REGION", and" DUAL_REGION", however these were supposed to be "multi-region", "region", and "dual-region". They will be changed in the API after a rollout on June 26 and that should also be reflected here.

**Comment by odeke-em** [comment]
Thank you for filing this issue Jesse and for the assignment Jean!

I have mailed https://code-review.googlesource.com/c/gocloud/+/42671 but I think there might be something to update on the GCS backend to ensure this updates go through.
