### ISSUE TITLE
bigtable: emulator still return error ("Error in field 'column_qualifier_regex_filter' : error parsing regexp: invalid escape sequence: \\C") after released fix in https://github.com/googleapis/google-cloud-go/pull/1433

### ISSUE THREAD

**Issue by Valentin-Nikolov** [googleapis/google-cloud-go#1454]
Hi guys, I still observe the same error message within the emulator bigtable as described in the closed https://github.com/googleapis/google-cloud-go/issues/1405 (after fix is released and bigtable emulator updated with v.0.40.0. https://github.com/googleapis/google-cloud-go/pull/1433). What I did is to update with `gcloud components update` and verify the latest updates and fixes are installed. Though when perform query using filter 'column_qualifier_regex_filter' I get the following error:

"status": {
"code": "INVALID_ARGUMENT",
"description": "Error in field 'column_qualifier_regex_filter' : error parsing regexp: invalid escape sequence: \\C",
"cause": null,
"ok": false
}

I open new ticket here and link the closed ticket to that one for better understanding the issue history.

**Comment by odeke-em** [comment]
Hello @Valentin-Nikolov, sorry about that. The change was made but the release on `gcloud components` hasn't yet been made. In the meantime you can update your go built version of the emulator by
```shell
go get -u -v cloud.google.com/go/bigtable/cmd/emulator
``` 

and then running your emulator with your GOOGLE_APPLICATION_CREDENTIALS appropriately e.g. if they aren't already set in your environment
```shell
GOOGLE_APPLICATION_CREDENTIALS=<your_credentials_file.json> emulator
```

Kindly paging @jadekler @garye for the `gcloud components` release

**Comment by Valentin-Nikolov** [comment]
Ok, thank you for the fast response @odeke-em! Will wait for the official release of the fix too.

**Comment by jadekler** [comment]
Closing since the work on our side is finished, and just pending BigTable team's release.
