### ISSUE TITLE
storage: signedURLV4 hard codes the host, how do you use CNAME redirects?

### ISSUE THREAD

**Issue by mbinette** [googleapis/google-cloud-go#1458]
(delete this for feature requests)

## Client

Storage

## Describe Your Environment

Go v1.12

## Expected Behavior

Using the CNAME redirects as described in [https://cloud.google.com/storage/docs/request-endpoints](Request endpoints), Instead of storage.googleapis.com, you can have your own host such as storage.mycustomdomain.com. But the code hard codes the Host value in the signedURLV4 method.

The signed URL works if you leave the storage.googleapis.com in the URL but doesn't work if you use the CNAME.

**Comment by jadekler** [comment]
cc @broady @frankyn

**Comment by frankyn** [comment]
Hi @mbinette,

I wasn't aware of using a custom CNAME instead as being a possible feature with signed URLs. I relayed the question to the GCS team and it's possible to use a CNAME to a GCS bucket with signed URL. However, I haven't tested it. 

It's a reasonable feature request that should be respected by all language implementations.

**Comment by frankyn** [comment]
dedup against https://github.com/googleapis/google-cloud-go/issues/1745

**Comment by tritone** [comment]
This has been added in e44449b6b71536e41c165d84eb8a9253154c0ba8  (use the BucketBoundHostname Style option).
