### ISSUE TITLE
[Feature request] Cloud Translate v3

### ISSUE THREAD

**Issue by sharkyze** [googleapis/google-cloud-go#1461]
Hello,
Cloud Translation API v3beta1 was released recently with some nice features.

I found this: https://godoc.org/google.golang.org/genproto/googleapis/cloud/translate/v3beta1 and was wondering if we could expect to see the Go client library any time soon ?

**Comment by jadekler** [comment]
The translate team have not yet started the process for library generation. It may be that the library is in very early beta, still. Once they begin the process we should have libraries out quite soon.

**Comment by jadekler** [comment]
ps: if you have a strong need of v3, let me know and I'll follow up internally.

**Comment by sharkyze** [comment]
thank you, I don't know if it is a strong need 😄 but we are starting a project using translate v3 with Glossaries and Go using the REST API for the moment. If the client library is coming soon it would be nice not to have to rewrite the Cloud translate layer.

**Comment by jadekler** [comment]
Right on. The v3 REST approach is a good idea, and more likely to be stable than this beta.
