### ISSUE TITLE
PubSub - Go client publisher gets stuck

### ISSUE THREAD

**Issue by etodd** [googleapis/google-cloud-go#1464]
## Client

PubSub

## Describe Your Environment

GKE. We are calling the pubsub client's `Publish()` function inside a goroutine. Default PublishSettings.

## Expected Behavior

If a publisher starts encountering errors, timeouts, etc. it should eventually recover, re-establish connection, etc.

## Actual Behavior

Something happens where messages stop going through and then every publish request from then on fails with `bundler reached buffered byte limit`. Restarting the pod fixes the issue.

![image](https://user-images.githubusercontent.com/1226339/59727631-3ee44480-91eb-11e9-99ec-b39dcce9ad9c.png)

The above memory usage increase appears to reflect the size of the bundler buffer.

**Comment by etodd** [comment]
More info. We currently have 14 replicas which in total publish about 4,000 messages per second, each message being about 1-1.5KB in size. When we lower the replicas to 8 (so about 500 messages per second per instance), this problem occurs within minutes.

**Comment by hongalex** [comment]
We recently exposed `PublishSettings.BufferedByteLimit` in `topic.go` via ad9d9cbfd8a5e1a022fe6f4ba329c01798b03217 so this error can be addressed. Essentially, as messages are buffered, they take up memory if they cannot be published fast enough. The default limit is about 100MB (10 times the max message size) so the publisher doesn't cause memory issues for most scenarios. However, for publish-heavy applications such as yours, I recommend playing around with a higher `BufferedByteLimit` amount.

If throughput were not a concern, you could also consider throttling calls but I think the aforementioned solution works better for your scenario.

**Comment by etodd** [comment]
Increasing `PublishSettings.BufferedByteLimit` to 2GB did not solve the problem, but we worked around the issue by opening 4 Pub/Sub clients per pod instead of 1, with `NumGoroutines` divided by 4 for each client.
