### ISSUE TITLE
cbt: parseGCPolicy undefined

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1468]
commit 2c827a5dee654731ef9d21d83bc2ad395987118c seems to have removed `parseGCPolicy` from bigtable/cmd/cbt/cbt.go, but the file still has references to it. Does this compile for y'all?

/cc @jadekler

**Comment by jadekler** [comment]
It just got moved to `bigtable/cmd/cbt/gcpolicy.g` in that commit. :)
