### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-go#1470]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by jadekler** [comment]
Heyo! This looks like a regen request. Would you mind filing it through those channels? (go/yoshi-site has a section on this).

**Comment by crwilcox** [comment]
This is both a regen and a verification. We have found that multiple Spanner libraries aren't respecting the gapic configuration. Can you verify that a regeneration would pick this up?

**Comment by jadekler** [comment]
Gotcha. Regen will pick it up, and as mentioned in the other PR we need @olavloite's retry CL to switch from manual-level retry logic to gapic-level retry logic. We will prioritize that (I believe @olavloite is working on that), and I'll prioritize reviewing it, but just another plug that we could really use some spanner reviewers. The CLs for that are too large for me alone.
