### ISSUE TITLE
Spanner: Ensure client backoff is implemented to respect client configuration.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-go#1471]
There was an issue in the client library for python where requests to retry could occur without a proper retry object. In this case, rather than defaulting to an exponential backoff, we defaulted to immediate retry. Ensure that for this client library we respect the min, max, and multiplier as specified in the gapic configuration. 

Original Bug: https://github.com/googleapis/google-cloud-python/issues/7303

**Comment by jadekler** [comment]
Currently, the go impl:

- We do not modify gapic config (it exists and works unmodified)
- We have a large layer of retry wrapping separate from gapic. It wraps all methods. It handles fine-grained specific errors as well as generic grpc codes, like Unavailable

In short-term future (https://code-review.googlesource.com/c/gocloud/+/41131 by @olavloite):

- We do not modify gapic config (it exists and works unmodified)
- We have a small layer of retry wrapping separate from gapic. It wraps transactional methods. It handles Aborted

We need spanner specific reviewers to move forward the near and long term futures. :)

**Comment by olavloite** [comment]
In addition to the above: The custom retry logic for the Go library will fall back to an exponential backoff algorithm (that is unrelated to the gapic config) if there is no retry info in the error. It will not do an immediate retry.

**Comment by olavloite** [comment]
Change https://code-review.googlesource.com/c/gocloud/+/41131 has been merged which fixes most of the issues. There are still a couple of specific places using custom retry logic.

**Comment by olavloite** [comment]
All gRPC calls use the generated gapic client, which again automatically use the gapic configuration, including the backoff settings. The only two places where custom backoff-and-retry logic is applied are now:
* Aborted transactions: In case of an aborted transaction, the client will try to extract the delay from the error. If none can be found, it will fallback to an exponential backoff with an initial retry delay of minimum 20ms.
* Broken streaming result sets: In case of a broken stream, the client will retry using an exponantial backoff with an initial retry delay of 20ms.
