### ISSUE TITLE
pubsub: fatal in streaming_pull_test's ReconnectsAfterServerDies

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1473]
While trying to run these tests in the mono-repo, I deterministically get failures in this test target https://github.com/googleapis/google-cloud-go/blob/42e6c5e0731d2d01a39a3087413bf1251d88373e/pubsub/streaming_pull_test.go#L409 of the form `listen tcp [::1]:1: bind: permission denied`. Is `Close()` on the `testutil.Server` guaranteed to release the port immediately for rebinding?

**Comment by jadekler** [comment]
Yes. Moreover, though I don't really fully understand IPv6 signatures, doesn't `[::1]:1:` mean "pick any open port"? o.O

**Comment by Capstan** [comment]
No, it's using port 1, presumably after opening the server originally on
port 0 and being assigned port 1. The test tries to be able to replace the
server and have the client still work.

Jean de Klerk <notifications@github.com> schrieb am Di., 25. Juni 2019,
22:01:

**Comment by IlyaFaer** [comment]
@Capstan, is issue still actual? For now, I didn't found a way to reproduce the error

Usually, `bind()` fails with Permission Denied when low privileged user is trying to connect to a port with number below 1024, but looks like your first test server started successfully, so it's off the table. 

As for trying to connect to a port, which is already taken, it should fail with `bind: Only one usage of each socket address (protocol/network address/port) is normally permitted` (and it's falling, I've reproduced it in several ways in this test), so, I suspect, it is not simultaneous access issue.

Could you tell me what is your OS? I've heard about such errors with Unix sockets

**Comment by Capstan** [comment]
Yes, it is still actual in the monorepo. gLinux is Debian Rodete. Our test environment is IPv6 only.

**Comment by hongalex** [comment]
I currently do not have access to a physical glinux device in an ipv6 only environment. I suspect that this issue is likely stale and will be closing. If other people from within Google are still encountering this issue, please ping me directly and I'll try to assist internally.
