### ISSUE TITLE
Firestore: support custom JSON Marshal/Unmarshal

### ISSUE THREAD

**Issue by marwan-at-work** [googleapis/google-cloud-go#1475]
Firestore supports the `firestore` tag instead of the `json` one although they are identical so im not sure why it does that. 

Furthermore, the Go Firestore client should support custom unmarshalling/marshalling of a Struct type to make interactions with the database easier. 

Related to: https://github.com/googleapis/google-cloud-go/issues/1416

**Comment by jadekler** [comment]
cc @benwhitehead

**Comment by adrianduke** [comment]
This would resolve my issue outlined here: https://github.com/googleapis/google-cloud-go/issues/1740#issuecomment-627959960

**Comment by crwilcox** [comment]
closing. Please follow 2610 for updates on this issue as we are collecting similar issues together to target with a design.

**Comment by treeder** [comment]
#2610 (for linkage)

**Comment by subimage** [comment]
Why does this support custom unmarshaling but not marshaling? Makes no sense.
