### ISSUE TITLE
logging: no way to set TraceSampled on underlying LogEntry

### ISSUE THREAD

**Issue by someone1** [googleapis/google-cloud-go#1476]
It should be a trivial addition to the `logging.Entry` struct to include a TraceSampled boolean that will be added to the underlying generated LogEntry pb. We should know if the trace is sampled from a call like `span.SpanContext().IsSampled()`

**Comment by odeke-em** [comment]
Thank you @someone1 for reporting this issue! 

In deed, the proto definition has `bool trace_sampled` https://github.com/googleapis/googleapis/blob/de1150ccad2a3daa4e265a0948bec54fdf9c8b54/google/logging/v2/log_entry.proto#L142-L148

![Screen Shot 2019-06-24 at 3 51 58 PM](https://user-images.githubusercontent.com/4898263/60057050-04b9ed80-9698-11e9-9ab1-d37e2a41d152.png)

but also we need to be able to retrieve from the Entry's HTTPRequest.Request.Header `X-Cloud-Trace-Context` if it was traced as per https://cloud.google.com/trace/docs/troubleshooting#force-trace

**Comment by odeke-em** [comment]
Just for posterity, the `trace_sampled` field was added just 9 months ago in https://github.com/googleapis/googleapis/commit/7b34e5a3ed10775fe14d15ffa842870dc3b5400e

**Comment by odeke-em** [comment]
I mailed https://code-review.googlesource.com/c/gocloud/+/42250 which will close this issue whenever it is reviewed and merged.
