### ISSUE TITLE
errorreporting : resolution status and resolution filter are not available

### ISSUE THREAD

**Issue by norbjd** [googleapis/google-cloud-go#1481]
Hello,

I'm using the beta client for error reporting : `cloud.google.com/go/errorreporting/apiv1beta1`, from `cloud.google.com/go v0.40.0`.

I would like to retrieve, for a specific project, all error groups **with their resolution status**. I use the following code (error handling have been removed to simplify) :

```go
package main

import (
        "context"
        "fmt"

        errorreporting "cloud.google.com/go/errorreporting/apiv1beta1"
        "google.golang.org/api/iterator"
        clouderrorreportingpb "google.golang.org/genproto/googleapis/devtools/clouderrorreporting/v1beta1"
)

func main() {
        projectName := "<my-project>"

        ctx := context.Background()
        c, _ := errorreporting.NewErrorStatsClient(ctx)
        defer c.Close()

        req := &clouderrorreportingpb.ListGroupStatsRequest{
                ProjectName: "projects/" + projectName,
        }

        it := c.ListGroupStats(ctx, req)
        for {
                resp, err := it.Next()
                if err == iterator.Done {
                        break
                }

                fmt.Println(resp.GetGroup())
        }
}
```

This code returns :

```
name:"projects/<my-project>/groups/<group1>" group_id:"<group1>"
name:"projects/<my-project>/groups/<group2>" group_id:"<group2>"
...
```

But there is **no resolution status** field in the resulting groups (as the doc states though, so it seems normal). I looked into the proto definition and I can't find neither the resolution status here :

https://github.com/googleapis/googleapis/blob/540a500/google/devtools/clouderrorreporting/v1beta1/common.proto#L31

**However**, filtering and retrieving the resolution status **is possible from the Google Web Console**.

Filtering can be done following [this doc on resolution status filtering](https://cloud.google.com/error-reporting/docs/viewing-errors#resolution_status_filtering). And if I inspect network traces with my browser, I can see that `resolutionStatus` info is available :

![resolution_status_console](https://user-images.githubusercontent.com/26850303/60178393-c0eff100-981b-11e9-92d9-6c838084cf7c.png)

For information, if I filter on `OPEN` and `ACKNOWLEDGED` resolution status, I can also see the `resolutionFilter` in the request :

```
https://clouderrorreporting.clients6.google.com/v1beta1/projects/<my-project>/groupStats?groupStatsResponseView=INCLUDE_UNFILTERED&pageSize=30&pageToken&timeRange.period=PERIOD_30_DAYS&resolutionFilter=OPEN&resolutionFilter=ACKNOWLEDGED&key=<some-key>
```

I can't figure why I can get this information from the Console, but not from the Go client. There is neither `resolutionFilter` available in `ListGroupStatsRequest`, nor `resolutionStatus` available in `ErrorGroup`. Actually, I mostly don't understand why I can get this information (or filter) in the Console even if this resolution status is not present in the proto message!

Is there a way to get resolution status associated with an error group, or to filter? Does someone have any clue?

Thanks in advance.

**Comment by odeke-em** [comment]
Thank you for reporting this issue @norbjd and welcome to the Google-Cloud-Go project!

Since the UI shows those fields, the network shows they are sent, then this seems like an issue of where the proto definitions and the actual service haven't yet been synchronized.
Kindly pinging @mtwo @JustinBeckwith to perhaps help connect us to someone who can help with synchronizing the proto definitions.

**Comment by norbjd** [comment]
Hello @odeke-em,

Thanks for your answer. Do you have any news about this?

**Comment by odeke-em** [comment]
Thank you for the ping @norbjd! I reported this to the Stackdriver ErrorReporting PM and they gave me an engineering contact but they are currently flooded with a bunch of work that this issue is on the back burner unfortunately. I shall check again in a few hours.

**Comment by aclowkey** [comment]
This isn't even documented for REST.
But looking at the Error Reporting page I can see the filter being sent. So I think a workaround is possible

`../v1beta1/projects/<proj>/groupStats?eventView=ORIGINAL_AND_PARSED&filter&groupStatsResponseView=INCLUDE_UNFILTERED&order=COUNT_DESC&pageSize=30&pageToken&timeRange.period=PERIOD_1_HOUR&timedCountDuration.seconds=120&resolutionFilter=OPEN&resolutionFilter=ACKNOWLEDGED&key=...`

**Comment by norbjd** [comment]
@odeke-em Can I help on this? Can `ListGroupStats` method (from ` ErrorStatsClient`) be modified?

https://github.com/googleapis/google-cloud-go/blob/0aca7e59167a13b5a5f5a0539c509b84648165ea/errorreporting/apiv1beta1/error_stats_client.go#L130

However, I'm puzzled because this query is based on `clouderrorreportingpb.ErrorGroupStats` (`clouderrorreportingpb` references `google.golang.org/genproto/googleapis/devtools/clouderrorreporting/v1beta1`). Since the `resolutionFilter` field is not present in [`clouderrorreportingpb.ErrorGroupStats`](https://github.com/googleapis/go-genproto/blob/fa694d86fc64c7654a660f8908de4e879866748d/googleapis/devtools/clouderrorreporting/v1beta1/error_stats_service.pb.go#L369) (generated from the proto definition), is it a good idea to update directly `ListGroupStats`?

The best way would be to add the field `resolutionFilter` and `resolutionStatus` directly in the proto definition, but, waiting for this, is patching `ListGroupStats` an appropriate solution?

**Comment by jadekler** [comment]
> Can ListGroupStats method (from ErrorStatsClient) be modified?

It cannot, unfortunately. It is auto-generated from a .proto that the backend team controls. If they decide to change/add features like this, they have to add this feature to their API and publish the updated protos, which will lead to those libraries having the feature (after regeneration).

**Comment by norbjd** [comment]
@jadekler Thanks for your answer.

Ok, so the protobuf definition of `ListGroupStatsRequest` :

https://github.com/googleapis/googleapis/blob/540a500e3663763887087ac3eb77bddd601c3645/google/devtools/clouderrorreporting/v1beta1/error_stats_service.proto#L57

is used to generate the `ListGroupStatsRequest` struct in Go :

https://github.com/googleapis/go-genproto/blob/fa694d86fc64c7654a660f8908de4e879866748d/googleapis/devtools/clouderrorreporting/v1beta1/error_stats_service.pb.go#L162

And this Go struct is then used in `google-cloud-go` client.

To sum up, in order to get this `resolutionFilter` in `ListGroupStatsRequest` available in the Go client, its proto definition in https://github.com/googleapis/googleapis repository must be updated.

@jadekler @odeke-em Do you know if there is a way to contact the backend team controlling the https://github.com/googleapis/googleapis repository to ask them to add the `resolutionFilter` (or at least sync their proto definition in this repo because it seems that it is already available and used in the Web Console)? Issues are not available. Thank you very much.

**Comment by odeke-em** [comment]
@norbjd I have filed https://issuetracker.google.com/issues/139429418 which will be the tracking bug and have rapport with the actual Stackdriver Errorreporting team, but otherwise this library here can't do anything about it, we depend on the public proto definitions. Please comment/communicate on that bug and when the protos get regenerated, we'll be notified and those protos will then be regenerated and finally we'll have something actionable. I'll close this issue otherwise.
