### ISSUE TITLE
storage: fix TestIntegration_Objects

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1482]
Consistently timing out after 30m in CI.

https://sponge.corp.google.com/target?id=ea4179a5-c2c0-4bac-9770-eb8526d0b6bc&target=cloud-go-libraries/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

https://sponge.corp.google.com/target?id=4296be21-bbfb-4606-9be3-02aa25f0aa80&target=cloud-go-libraries/google-cloud-go/continuous/go19&searchFor=&show=ALL&sortBy=STATUS

**Comment by jadekler** [comment]
Unable to repro locally with -count=1. Maybe needs more counts, or parallelism. Runs in 15s on my local machine.

**Comment by frankyn** [comment]
Reproduced as a cURL request. Issue is in GCS backend.

```
curl -v --http1.1 -X PATCH \
 -H "Content-Type: application/json" \
 -H "Accept-Encoding: gzip" \
--data '{"bucket":"go-integration-test-20190627-81353067379000-0001","contentType":null}' \
'https://www.googleapis.com/storage/v1/b/go-integration-test-20190627-81353067379000-0001/o/obj1?alt=json&prettyPrint=false&projection=full'
```

internal bug: 136205936 Pending response.

**Comment by jadekler** [comment]
Closing since this is tracked internally.
