### ISSUE TITLE
datastore: segfault in Iterator.Cursor() due to new OpenCensus tracing calls

### ISSUE THREAD

**Issue by tmotee** [googleapis/google-cloud-go#1483]
Existing test code is consistently getting segfaults when calling Iterator.Cursor() since opencensus calls were added in this commit: 

https://github.com/googleapis/google-cloud-go/commit/cf239ab67c4b6d36266dd69ee1fb771654d8f577

First failure was on 6/26 following integration of these changes in cl/255212900. The stack trace is here:

https://sponge.corp.google.com/343de113-9840-4143-bed3-b02bd0d38fc9

Neither the test nor code being tested have changed in the last four months. I don't see anything suspicious in the calling code; all it does is Client.Run() followed by Next() and then Cursor() on the returned iterator.

My guess is maybe the iterator's ctx was not initialized properly?

**Comment by jadekler** [comment]
That could happen if your iterator is `nil`. Could you check to see if that's the case?

**Comment by odeke-em** [comment]
Thank you for filing this issue @tmotee and welcome to the Google-Cloud-Go project! Thank you too @jadekler for the triaging and checking.

@tmotee in addition to @jadekler's questions, could you please point me to the publicly accessible stacktrace? You pointed to a sponge.corp.google link and that requires logging in as a Googler but the public translation of that link https://source.cloud.google.com/results/invocations/b5dd368b-91b2-4b20-860f-5c8d8d7349f6 doesn't show anything.

**Comment by tmotee** [comment]
Hi @odeke-em, thanks for following up! I should have updated this issue, but it turns out our test was using a mock Iterator with nil context. The tracing calls must be the first to actually use the context. We've updated our test and it's fine now!

**Comment by odeke-em** [comment]
Awesome, thank you @tmotee for the update and great to hear that y'all solved it. In that case I shall close this bug. Please don't hesitate to reach out and file other bugs.
