### ISSUE TITLE
pubsub: subscription keeps "trash" in message.Data from previous fetches

### ISSUE THREAD

**Issue by tscolari** [googleapis/google-cloud-go#1484]
## Client

Pubsub

## Describe Your Environment

Alpine image running the compiled binary

## Expected Behavior

For each message I queue in the topic, I want the subscription to retrieve it exactly as it was published.

## Actual Behavior

I'm seeing the behaviour where `message.Data` is corrupted.
I managed to track this for one example:

1. I queued a json that had len 2345 - valid json.
2. I queued another json that had only len 2133 - valid json.

a. The first json was retrieved with success by the subscription (valid json, len 2345).
b. The second json was retrieved, but the `message.Data` had len 2345 (not 2133) and after the original json there was a line break and the remaining of bits of the first json.

I debugged this to the point I'm certain that the correct message was queued in both times.

**Comment by tscolari** [comment]
I think I found the culprit:

```
for scanner.Scan() {
  ...
  data := scanner.Bytes()
  topic.Publish(ctx, &pubsub.Message{Data: data})
  ...
}
```

It turns out that `scanner.Bytes()` mutate `data` while pubsub is asynchronously publishing.
The fix was to make that call synchornous:

```
  topic.Publish(ctx, &pubsub.Message{Data: data}).Get(ctx)
```

**Comment by odeke-em** [comment]
Hello @tscolari, thank you for filing this bug and welcome to Google-Cloud-Go!

So in deed, `topic.Publish` is an asynchronous method and if you are sharing the byte buffer, across goroutines, the same copy will be shared.

One way that you can keep your asynchronous publishing yet correctness of the bytes buffer
is by creating a fresh copy of your data using Go's slice copy operator `[:]` so `data[:]` and in the full snippet.
```go
for scanner.Scan() {
  ...
  data := scanner.Bytes()
  topic.Publish(ctx, &pubsub.Message{Data: data[:]})
  ...
}
```

I shall close this issue as there is nothing actionable for us to change in the libraries but you can adapt to the reslice. Thank you for the report and please don't hesitate to reach out in case of any bugs or questions.
