### ISSUE TITLE
unsupported struct field type: map[string]*datastore.Value

### ISSUE THREAD

**Issue by Sheshagiri** [googleapis/google-cloud-go#1489]
unable to put objects created using the datastore/v1 protobuf's to google cloud datastore.

## Client

e.g. datastore

## Describe Your Environment

Client SDK: https://github.com/googleapis/google-cloud-go/tree/master/datastore

## Expected Behavior

should not throw any error

## Actual Behavior

following is the error
```
datastore: unsupported struct field type: map[string]*datastore.Value
```

following is my code
```
package main

import (
	"fmt"
	"cloud.google.com/go/datastore"
	"context"
	pb "google.golang.org/genproto/googleapis/datastore/v1"
)

func main() {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "project-id-goes-here")
	if err != nil {
		fmt.Printf("unable to create a client, %v\n", err)
	}
	key := datastore.NameKey("ExecutionStatus", "e-1", nil)
	execution := &pb.Entity{
		Properties:map[string]*pb.Value{
			"e-1":{
				ValueType: &pb.Value_StringValue{
					StringValue:"Execution completed",
				},
			},
		},
	}
	_, err = client.Put(ctx, key, execution)
	if err != nil {
		fmt.Printf("unable to save to datastore: %v\n",err)
	}
}
```

**Comment by jadekler** [comment]
Datastore does not support maps. See: https://godoc.org/cloud.google.com/go/datastore

**Comment by xaah** [comment]
Just checking, is this still not on the cards? Would be really helpful if the datastore client supported maps.
