### ISSUE TITLE
bigtable: Connection is closing/draining

### ISSUE THREAD

**Issue by noamt** [googleapis/google-cloud-go#1492]
## Client

`cloud.google.com/go v0.41.0`

## Describe Your Environment

Alpine Docker on GKE at `europe-west4` sending and receiving data from a development instance of BigTable at `europe-west1`

## Expected Behavior

I'm not entirely sure what the issue is but I guess the pool should keep connections alive or retry?

## Actual Behavior

Getting intermittent errors of:
`rpc error: code = Unavailable desc = the connection is draining`
And
`rpc error: code = Unavailable desc = transport is closing`
When sending data

**Comment by odeke-em** [comment]
Thank you for reporting this issue @noamt!

Apologies for the late reply, it is the July 4th weekend over here.

How often is this happening for you? When did it start? Are you able to reliably reproduce this problem? Is there a way we could get more information to help diagnose the problem for your project?

I shall kindly ping someone from the Bigtable team @igorbernstein2.

**Comment by noamt** [comment]
No worries.

We see it maybe once a day in the morning hours (CET), but I'm not able to locally reproduce.
I can supply any information needed on the app side, our BigTable is of course on GCP :)

**Comment by igorbernstein2** [comment]
What methods are exhibiting this behavior? The bigtable client does implement retries for idempotent requests like read rows and mutations that have an explicit timestamp. However non-idempotent mutations (ie. ones that use serverside timestamps), conditional mutations and read modify write mutations will not be retried

**Comment by noamt** [comment]
Thanks @igorbernstein2 , that might explain the issue.
It's actually [Table.Apply](https://godoc.org/cloud.google.com/go/bigtable#Table.Apply) with a server side timestamp, so I'll add explicit timestamps
I now see that it's stated in the ["Retries"](https://godoc.org/cloud.google.com/go/bigtable#hdr-Retries) section of the godoc so apologies for wasting your time.
