### ISSUE TITLE
Datastore: set min backoff duration more shortly

### ISSUE THREAD

**Issue by vvakame** [googleapis/google-cloud-go#1493]
same as #1215 

We got `unavailable: all SubConns are in TransientFailure, latest connection error: <nil>` error from `google.datastore.v1.Datastore.Lookup`.
https://github.com/grpc/grpc-go/blob/005a2997efe403ec528055f31c393f584a311800/picker_wrapper.go#L147-L151
finally, this task completed with success. but it's slow.

I think We can use more short backoff duration in Datastore client.
https://github.com/googleapis/google-cloud-go/blob/335e9e09b93e170ef8b409517495bb988e4f4279/datastore/client.go#L101

We use 1s. But it is slow... 😿 
https://github.com/googleapis/gax-go/blob/289fb28c333ea06e7d38a6e7b47b7c234198a6c2/v2/call_option.go#L97-L114

in Spanner. We use 20ms to minBackoff finally.
so, I think We can change 1s to 100ms backoff duration in Datastore too.
https://github.com/googleapis/google-cloud-go/commit/ab1512ccf757de1b7f7f62883d9f975dfc152cef
https://github.com/googleapis/google-cloud-go/commit/c1cf806de067f030d2ff26f153e7950386b22178 (20 ms is maybe too short? 🤔 )

Can I send a pull request?

**Comment by jadekler** [comment]
> finally, this task completed with success. but it's slow.

Did it immediately reconnect after 1s, or did it take longer? If the former, yes, I agree shortening the period seems like a good idea. If the latter, I'm not sure it'll help. If your connection is legitimately unavailable then no amount of retrying will help until it's back.

All that said, I'm generally not opposed to shortening the period. If you'd like to submit a change, please see our CONTRIBUTING.md which has guidance. (we don't accept PRs)

**Comment by vvakame** [comment]
@jadekler sorry for late response.
We go about 800-830ms delay. not reaching to just 1s.
This is our trace graph.
![DD](https://user-images.githubusercontent.com/125332/61265374-d0cf7500-a7ca-11e9-8d9e-2f14d629b1ed.png)
so, our Instance exists northeast-asia, and Datastore is in US. Maybe 650-700ms is real delay time... 🤔

**Comment by jadekler** [comment]
Yes, 650ms seems reasonable-ish for such a distance. (having no actual measurements myself)

Could you try setting the period to 100ms yourself and seeing if that helps, and reporting back?

**Comment by vvakame** [comment]
okay... I'll try it. But it may take some times... 🙇

**Comment by vvakame** [comment]
I started using 100ms version library in our test env.

**Comment by jadekler** [comment]
Sounds good. Has it made a difference, or are you still seeing the aforementioned latency? If the former, this seems like a good change. If the latter, it seems like it might just be the distance to datacenter.

**Comment by vvakame** [comment]
It seems that the effect was not better than I thought. 😿 
I mistake our environment is not using US datastore. We use `asia-northeast1` in app and Datastore both. sorry!
and, We update all dependencies (include grpc client).

we try to use 100ms in library.
https://github.com/googleapis/google-cloud-go/blob/335e9e09b93e170ef8b409517495bb988e4f4279/datastore/client.go#L101
and
https://github.com/grpc/grpc-go/blob/120728e1f775e40a2a764341939b78d666b08260/internal/backoff/backoff.go#L43

so, we got low error rate than original. but It looks like there is not much difference in latency.

I did not know clearly that this changes has good effect. 🤔

**Comment by jadekler** [comment]
Gotcha. If latency is your goal, the next step would be to work with a cloud representative to see if there's any debugging, network changes, and so on that could be done: https://cloud.google.com/support/.

If there are no specific changes to the libraries you'd like, do you mind if I close this issue?

Also, I've made the 100ms change here: https://code-review.googlesource.com/c/gocloud/+/43090

**Comment by vvakame** [comment]
thanks! Our company have a Google support contract. 😉 
and, thank you to make 100ms change. 🌹
