### ISSUE TITLE
Dialogflow V2 is Missing Types

### ISSUE THREAD

**Issue by mishushakov** [googleapis/google-cloud-go#1494]
Dialogflow's (v2) Proto seems to be missing Response types for Actions on Google in `webhookPayloadgoogle`.`google`

Actions on Google passes it's results back to Dialogflow in the `webhookPayload`. `google` object, that contains `richResponse`.`items`, typed according to the Actions on Google [types](https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/src/service/actionssdk/api/v2.ts).

Here is an example:

<img width="685" alt="Screenshot 2019-07-08 at 22 49 40" src="https://user-images.githubusercontent.com/10400064/60842333-28228380-a1d4-11e9-915a-c44f9e35421b.png">

It's not the case with the Proto though, because the `webhookPayload` responses are typed as `google.protobuf.Struct`.

See here: https://github.com/googleapis/googleapis/blob/master/google/cloud/dialogflow/v2/session.proto#L235-L237

And generated client:
https://godoc.org/google.golang.org/genproto/googleapis/cloud/dialogflow/v2#QueryResult

Possible resolutions:
1) Dialogflow and Actions on Google will merge their `fulfillmentMessages` schemas (which already look pretty similar), so there is no need for `webhookPayload`.`google` object
2) Dialogflow will include Actions on Google types in `webhookPayload`.`google` object

Feels like a complete mess. I also noticed, that you can't unmarshal json response, without a hack, [reference](https://github.com/googleapis/go-genproto/issues/74).

Thank you.

**Comment by jadekler** [comment]
Thanks for filing this issue. Unfortunately we only handle the creation and generation of libraries, not the protos for backend services. Would you mind re-filing this issue directly to the dialogflow team at https://cloud.google.com/support/docs/issue-trackers?

**Comment by mishushakov** [comment]
Hey @jadekler, sure, will do it! Thanks.
