### ISSUE TITLE
pubsub: Recommended library to use with GAE standard in 2019

### ISSUE THREAD

**Issue by andwun** [googleapis/google-cloud-go#1498]
#702 concludes that `google.golang.org/api/pubsub/v1` should be used for GAE standard apps.
Is this still the way to go today (even for the 2nd gen runtimes [1.11, 1.12])?
The [docs for `google.golang.org/api/pubsub/v1`](https://godoc.org/google.golang.org/api/pubsub/v1) say its deprecated and `cloud.google.com/go/pubsub` should be used instead.

**Comment by jadekler** [comment]
Not a GAE expert, but looks like the latest documentation at https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-install-go suggests `cloud.google.com/go/pubsub` is the most relevant. I'd give that a shot! Please feel free to report back if you experience difficulties.

**Comment by jadekler** [comment]
cc @hongalex

**Comment by andwun** [comment]
@jadekler In the section [Using the client library](https://cloud.google.com/pubsub/docs/reference/libraries#using_the_client_library) it still has this text and even refers to #702 
> If you're running on Google App Engine standard, we recommend using the older Google APIs Client Libraries. See this GitHub issue for more details.

**Comment by jadekler** [comment]
OH I see. cc @broady is that still the case?
