### ISSUE TITLE
go: failed to create cache directory /go/pkg/mod/cache: mkdir /go: permission denied

### ISSUE THREAD

**Issue by Mayank-blkchn** [googleapis/google-cloud-go#1503]
@geekthatweaks
Go version: 1.12.4.linux
while running **make install** command inside docker file from non-root user i am getting error as:
**go: failed to create cache directory /go/pkg/mod/cache: mkdir /go: permission denied**

**Comment by jadekler** [comment]
This is a docker question, and does not seem related to the Go client libraries project. Closing this.

**Comment by HowCome** [comment]
How is it a docker question? the command cannot be run in docker container, which is what is mainly used on build machines.
go should be aware that it is running in docker and not vise versa.

 I am trying to create and publish a go package in jenkins that runs in a docker container and it is really hard and slow. Worst of all is when someone else runs into the same problem the regular answer from go people "this is not my problem" .
