### ISSUE TITLE
logging: fix (*Logger) StandardLogger godoc

### ISSUE THREAD

**Issue by rakyll** [googleapis/google-cloud-go#1508]
(*Logger) StandardLogger returns a log.Logger which is a concrete type not an interface. Package godoc should avoid using "interface" when referring to the type.

```
The Standard Logger Interface
You may want use a standard log.Logger in your program.
```

Users are confused, see https://twitter.com/freeformz/status/1150931060340883461.

@freeformz

**Comment by freeformz** [comment]
Less confused personally, just highlighting that it can be confusing until you look at the implementation: https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L833

But users shouldn't have to do that to understand the documentation.

Suggestion: `s/The Standard Logger Interface/Using as a Standard Logger/`

**Comment by freeformz** [comment]
It may also be beneficial to link to [log.Logger](https://golang.org/pkg/log/#Logger) if possible, just to make sure there is no confusion about *which* standard logger.

**Comment by odeke-em** [comment]
Thank you for the report @rakyll and @freeformz!
i've mailed CL https://code-review.googlesource.com/c/gocloud/+/42872 please take a look.
