### ISSUE TITLE
cmd/go-cloud-debug-agent: error when loading module

### ISSUE THREAD

**Issue by govargo** [googleapis/google-cloud-go#1513]
## Client

Debugger

## Describe Your Environment

GKE v1.12.8-gke.10
Go 1.12.6
Debugger(Latest)
Source Code: https://github.com/govargo/foo-controller
Dockerfile: https://github.com/govargo/foo-controller/blob/master/Dockerfile

## Expected Behavior

I can use Stackdriver Debugger for my go binary(foo-controller).
Go binary in container runs on GKE.

## Actual Behavior

It failed that Go binary in container runs on GKE.
When it runs go-cloud-debug-agent, the following error occurred.
```
$ /go/bin/go-cloud-debug-agent -v -sourcecontext=/source-context.json -appmodule=foo-controller -appversion=1.0 -- /foo-controller
Error loading program: AttrStmtList not present or not int64 for unit 393
```

Is the above error due to my binary?
Or, wrong with go build method?(https://github.com/govargo/foo-controller/blob/master/Dockerfile#L18)

It seems that the error is happend with https://github.com/googleapis/google-cloud-go/blob/master/cmd/go-cloud-debug-agent/debuglet.go#L110-L114.

However I don't know what to do so that I can solove this problem.
What should I do?

**Comment by odeke-em** [comment]
Thank you for reporting this issue @govargo!

I shall kindly page @shantuo who worked on the cloud-debug-agent to take a look.

**Comment by Monnoroch** [comment]
Same problem here, same exact GC flags setup.

**Comment by philpearl** [comment]
Same problem here. Any clues?

**Comment by tbpg** [comment]
Can you run the agent locally, not just on GKE? What version of Go? What build+runs commands are you using (might be different from the Dockerfile linked above)?

**Comment by kristiandrucker** [comment]
@tbpg I have the same problem. When I clone an example into Cloud Shell [HotApp](https://github.com/GoogleCloudPlatform/golang-samples/profiler/hotapp), build it without any arguments and run it with this command `go-cloud-debug-agent -appmodule=main -appversion=1.0 -- main` I get this error `2020/04/15 10:41:20 Error loading program: AttrStmtList not present or not int64 for unit 233`

**Comment by tanbc1997** [comment]
> 2020/07/07 08:00:15 Error loading program: AttrStmtList not present or not int64 for unit 535

got the same problem. @govargo have you solved this?

**Comment by Fryuni** [comment]
Just got this with Go 1.14.3 to

**Comment by codyoss** [comment]
Closing as [cmd/go-cloud-debug-agent is deprecated](https://github.com/googleapis/google-cloud-go/releases/tag/v0.69.0). The last version of Go it worked with was 1.11.
