### ISSUE TITLE
storage: Hardcoded Reader host precludes emulator use

### ISSUE THREAD

**Issue by MarcvanMelle** [googleapis/google-cloud-go#1515]
## Client

storage (GCS)

## Describe Your Environment

Docker `go 1.11.5` image
Using `fsouza/fake-gcs-server` image as an emulator in testing and development environment

## Expected Behavior

GCS `Reader` allows for changing host to function with emulator

## Actual Behavior

GCS `Reader` URL host is hard coded
https://github.com/googleapis/google-cloud-go/blob/master/storage/reader.go#L99

---

I found this a little odd, since the `Writer` uses the [`Client`](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L84)'s  [`raw`](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L99) [`Service`](https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L135) [`BasePath`](https://github.com/googleapis/google-api-go-client/blob/master/storage/v1/storage-gen.go#L81) which can be injected using `option.WithEndpoint`.

Possible solution?
```
host := "storage.googleapis.com"
bp, err := url.Parse(o.c.raw.BasePath)
if err == nil && bp.Host != "www.googleapis.com" {
  host = bp.Host
}

u := &url.URL{
  Scheme: "https",
  Host:   host,
  Path:   fmt.Sprintf("/%s/%s", o.bucket, o.object),
}
```

**Comment by jadekler** [comment]
Funny you should mention this, because we just began working on this feature. Please track in https://code-review.googlesource.com/c/gocloud/+/42970.

cc @acmp1

**Comment by MarcvanMelle** [comment]
Awesome! Glad to know you're on the case!

**Comment by odeke-em** [comment]
We just merged https://code-review.googlesource.com/c/gocloud/+/42970. Shall we consider this issue solved and can be closed?

**Comment by jadekler** [comment]
Thanks - yes.
