### ISSUE TITLE
logging: detect resource automatically on GAE

### ISSUE THREAD

**Issue by benjaminjkraft** [googleapis/google-cloud-go#1521]
Right now, the logging client will automatically detect the current resource (product, project, zone, etc.) on GCE, but not on GAE.  In principle it's equally easy to do so, and is nice so the logs show up in the right place in the logs viewer.

I've put up a [diff](https://code-review.googlesource.com/c/gocloud/+/42810) to add this support.

Client: logging
Environment: GAE (standard, Go 1.12)
Expected: logs logged with the logging client show up under App Engine (with the right service/version) in the logs viewer
Actual: they show up under "Google Cloud Project"

**Comment by odeke-em** [comment]
Thank you for working on this @benjaminjkraft! We've merged your CL and it will be included in the next release.

**Comment by odeke-em** [comment]
Just /cc-ing @sbuss for when we make a release for a document update.
