### ISSUE TITLE
set up gopherbot

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1528]

**Comment by jadekler** [comment]
@dmitshur do you have some time to show me how to do this? :D

**Comment by dmitshur** [comment]
I don't have a lot of context for this issue so I might not be understanding it correctly. I'll provide some background first. "gopherbot" consists of these things:

- the @gopherbot GitHub account
- the [`golang.org/x/build/cmd/gopherbot`](https://godoc.org/golang.org/x/build/cmd/gopherbot) command source code
- a [`maintnerd`](https://godoc.org/golang.org/x/build/maintner/maintnerd) instance at https://maintner.golang.org that's set up to track repos in the [github.com/golang](https://github.com/golang) organization

I don't think we can use the @gopherbot instance you know from the [github.com/golang](https://github.com/golang) organization on other GitHub organizations; it's a bot specifically for the Go project. It's source code is also [hard-coded](https://github.com/golang/build/blob/6cacbcd1953c94f45c0aa98fe0bd6c530469b6aa/cmd/gopherbot/gopherbot.go#L278-L299) to do tasks specific to the Go issue tracker that don't apply elsewhere (but of course some of the tasks are more generally useful).

What is viable, if you'd like, is for you to use portions of its code that are useful to you and run your own instance configured for the target project(s) you have in mind.

If you're still interested in learning more, feel free to send me a calendar invite, I'm happy to answer any questions.

**Comment by jadekler** [comment]
Ahh gotcha. Thanks for the information. Sounds like it's _not_ an easy win. Closing this issue for now.
