### ISSUE TITLE
Why PubSub client uses asynchronous callbacks instead of channels?

### ISSUE THREAD

**Issue by yellowred** [googleapis/google-cloud-go#1530]
Hi,

I have a question regarding asynchronous callbacks being used in `Receive` function stack of Google PubSub. AFAIK this is not idiomatic Go and channels should be used instead. Is this a bad code, legacy or there is a particular reason for that?

**Comment by jadekler** [comment]
It's a good question. You're right; it's not idiomatic. Per [Rethinking Classical Concurrency Patterns](https://www.youtube.com/watch?v=5zXAHh5tJqQ), we should probably be using an iterator.

I believe the reason the async style was adopted was,

A. high throughput with little effort on the part of the user
B. a common interface across multiple languages

Hope that clears it up. You can always use the underlying API https://godoc.org/cloud.google.com/go/pubsub/apiv1 to implement your own if you prefer a different style! :)

**Comment by dsymonds** [comment]
Worth noting that the callback is *not* asynchronous, and it abstracts the complexity of extending the ACK deadline while the callback is running. It's quite idiomatic to use callbacks for doing iteration (e.g. see path/filepath.Walk in the standard library).

Channels are a great way to combine code, but they rarely belong in an API.

**Comment by jadekler** [comment]
@dsymonds for clarity, could you expand on what you mean by "the callback is not asynchronous"? It runs in its own goroutine: https://github.com/googleapis/google-cloud-go/blob/aee6ec571016ab1edcc511dbbb3e91a61ad034aa/pubsub/subscription.go#L727-L730

**Comment by dsymonds** [comment]
That is part of the implementation detail. The callback itself is generally synchronous, and one could imagine an implementation where the callback was invoked synchronously. But more pertinently, the "lifetime" of the message is the duration of the callback's execution (so it is synchronous in that regard); if the API was channel-based then the pubsub library would have no view into when the message handling was "done" except by explicit Ack/Nack.

In the Go world, an "async callback" generally means that you register a function that will be invoked at some point in the future, independent of the registration (think, for instance, a net/http handler). That isn't the case in the pubsub API, where the callback is provided to the Receive method, and Receive doesn't return until after the callbacks have returned.

**Comment by jadekler** [comment]
Right on, thanks for taking the time to follow up!
