### ISSUE TITLE
PubSub messages expire cyclically

### ISSUE THREAD

**Issue by christian-roggia** [googleapis/google-cloud-go#1533]
## Client

- PubSub

## Describe Your Environment

- Distroless Image (Bazel-built for Go services) on GKE
- Pub/Sub Subscription:
- - Acknowledgement deadline: 300s
- - Message retention duration: 1d
- - Delivery type: Pull

## Expected Behavior

We expect only 1 outstanding message at a time. We expect that since the ACK deadline is large (5 minutes) and our job runs in less than 30 seconds all messages will get acknowledged and no messages expires.

## Actual Behavior

We publish around 15.000 messages per day, each message requires between 5 to 15 seconds to be processed by the subscriber process. The messages are extremely small (less than 10kb).

We set the Golang `subscription.ReceiveSettings.MaxOutstandingMessages` to `1` as we want to process the messages sequentially in our development environment.

The receive function written in Golang is simplified in the following way:

```
function (...) {
  timer.start()
  ...
  // Process the message
  ...
  timer.stop()
  msg.Ack()
}
```

The timer is logged and shows us that the work requires between 5 and 15 seconds, once the job is finished the message is acknowledged.

The issue we are currently facing is that, even if the message processing is supposed to be sequential and even if the ACK deadline is set to 5 minutes and the max extension period to 10 minutes (default value) the messages eventually will expire in a cyclical way.

We have observed the following behaviour in Stackdriver:
![img 1](https://user-images.githubusercontent.com/6957360/63022088-66315800-bea2-11e9-8bb6-75f9dc742965.png)
![img 2](https://user-images.githubusercontent.com/6957360/63022094-69c4df00-bea2-11e9-820d-f66c543b75c0.png)

After hours of debugging we couldn't find a single reason why cyclically there is a spike in expired requests.

**Comment by jadekler** [comment]
> The issue we are currently facing is that, even if the message processing is supposed to be sequential

There is no guarantee of this, btw.

[Also, `MaxOutstandingMessages` is](https://godoc.org/cloud.google.com/go/pubsub#ReceiveSettings) best-effort in the asynchronous (ReceiveSettings.Synchronous=false) case. The pub/sub server sends bundles of messages, whose size a client cannot control. So, we'll halt pulling if we hold more in memory than MaxOutstandingMessages, but the last bundle may have given >MaxOutstandingMessages.

If you care about truly enforcing MaxOutstandingMessages, please also use `ReceiveSettings.Synchronous=true`.

cc @hongalex
