### ISSUE TITLE
all: document which parts of the clients are safe for concurrent use

### ISSUE THREAD

**Issue by benjaminjkraft** [googleapis/google-cloud-go#1535]
It's not clear to me from reading the documentation which parts of these clients are safe to share in concurrent code.  We've had some really nasty bugs in Python due to sharing clients that [are not threadsafe](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md), and we're keen to avoid those mistakes in our Go applications.

The `datastore` documentation suggests that a typical application "would create a single client which is reused for every datastore operation" -- this implies, but never really says, that a client is safe for use by multiple goroutines.  Is that in fact the case?

Does the same apply to other clients?  (For example, the KMS client doesn't say, and its examples construct the client inline, whereas the Spanner client says it's safe (except for `Close`).)

What about specific data structures returned by the clients -- is it safe to concurrently iterate over a query iterator (`datastore.Iterator`)?  (My assumption here, from a quick glance at the source, is that it must not be: multiple queries might call `nextBatch` concurrently, and overwrite the `results` field.)  Is it safe for a transaction to spawn goroutines which use datastore?  (Presumably the transaction function would need to wait on them, of course.)

In general, it would be great for this to be clearly documented, because it's always a nasty surprise if it comes up in prod.

**Comment by jadekler** [comment]
Typically in our Go client libraries (and most Go libraries, I think?), objects and methods are assumed safe for concurrent use unless otherwise marked as such. In datastore, we note that Iterator is not safe for concurrent use as part of the Query documentation. I've created a CL to explicitly call it out on the Iterator itself: https://code-review.googlesource.com/c/gocloud/+/44130
