### ISSUE TITLE
firestore: emulator support should also configure Admin credentials

### ISSUE THREAD

**Issue by ryanpbrewster** [googleapis/google-cloud-go#1537]
When a Firestore client is established, [this code](https://github.com/googleapis/google-cloud-go/blob/master/firestore/client.go#L66-L72) checks for the environment variable `FIRESTORE_EMULATOR_HOST` and, if found, automatically configures the client to connect to the Firestore emulator.

This code should also automatically configure admin credentials, so that the client can make metadata requests (e.g., `ListCollectionIds`). In particular, the client should set the gRPC metadata field `"Authorization"` to `"Bearer owner"` on every request.

((In Java it is possible to do this with gRPC channel credentials. In the C core gRPC implementation this is not possible; any insecure channel automatically rejects all channel credentials. I'm not sure which situation the Go gRPC implementation is in.))

**Comment by bcspragu** [comment]
I tested a change locally, it's actually as simple as adding `grpc.WithAuthority("owner")`:

```golang
if addr := os.Getenv("FIRESTORE_EMULATOR_HOST"); addr != "" {
  conn, err := grpc.Dial(addr, grpc.WithInsecure(), grpc.WithAuthority("owner"))
  if err != nil {
    return nil, fmt.Errorf("firestore: dialing address from env var FIRESTORE_EMULATOR_HOST: %v", err)
  }
  o = []option.ClientOption{option.WithGRPCConn(conn)}
}
```

**Comment by jadekler** [comment]
I don't quite follow - does the admin emulator require authorization headers, but the non-admin emulator does not?

**Comment by jadekler** [comment]
cc @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
There are some RPCs that are marked as Admin-only that require these credentials (such as ListCollectionIdsRequest and ListDocumentsRequest with showMissing=true). It's meant to ensure that all client apps with third-party credentials that work against the emulator also work in production. The client SDKs don't specify "Bearer: Owner" and hence requests to Admin-only APIs fail.

**Comment by SowjanyaKotha** [comment]
I took the latest changes after the fix, I still face the same issue with ListDocuments request. If I do a curl request to the emulator with the owner as the token, it works fine. So, I'm assuming the emulator is fine. But the gRPC call is not taking in the authority that is set in the client. Should I set anything else?

**Comment by jadekler** [comment]
Hmm... I'll re-open this for investigation. I won't be able to get to this for a few weeks, so anyone else that has free cycles feel free to step in.

**Comment by ryanpbrewster** [comment]
This was resolved by https://code.googlesource.com/gocloud/+/78c93a17a96166b19ae5017c467ce233237a9d50
