### ISSUE TITLE
pubsub: Reader/Writer performs a lot of allocations for ackDeadline

### ISSUE THREAD

**Issue by tsholmes** [googleapis/google-cloud-go#1538]
## Client

Pubsub

## Describe Your Environment

Alpine Docker on GKE

## Expected Behavior

Memory allocations are negligible (or at least dominated by the message payloads).

## Actual Behavior

Client continuously makes small/medium allocations (4.8kb) to calculate percentile for ackDeadline.

In our graphql server (which is a reader/writer for different queues), these allocations are 3-5% of allocated heap objects and 50-70% of allocated heap space.
In our message processing backend (reader), these allocations are 10-20% of allocated heap objects and >80% of allocated heap space.

I'll submit a PR with a possible fix.

**Comment by jadekler** [comment]
👍 on submitting an improvement, though please do check out our CONTRIBUTING.md (we can't accept PRs).

**Comment by jadekler** [comment]
cc @hongalex

**Comment by tsholmes** [comment]
proposed change: https://code-review.googlesource.com/c/gocloud/+/44291
