### ISSUE TITLE
storage: Support negative offset range requests

### ISSUE THREAD

**Issue by brimworks** [googleapis/google-cloud-go#1540]
The GCS service supports negative suffix length range requests:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

```
Range: <unit>=-<suffix-length>
```

However, the Go client doesn't currently allow making range requests in this way. One use-case for this is fetching the last N bytes of a log file, something that is especially useful in the context of a log file for a failed build (since error messages typically are at the end of the log file).

Additionally, when specifying a suffix length, it is useful to know the absolute offset of the partial content which was returned. This is useful so one can implement "page backwards" functionality.

This information is in the `Content-Range` header which is already being parsed to obtain the total size of the object even though a partial response is being returned:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range

```
Content-Range: <unit> <range-start>-<range-end>/<size>
```

To that end, I've put forth two patches which would allow this functionality:

https://code-review.googlesource.com/c/gocloud/+/44131
https://code-review.googlesource.com/c/gocloud/+/44132

The `44131` patch extends the existing `NewRangeReader()` API so that instead of returning an error if the `offset` parameter is negative, it would interpret this to indicate that it is desired to obtain the absolute value number of bytes from the END of the object.

The `44132` patch extends the existing `ReaderObjectAttrs` structure with a new `Offset` field which would return the absolute offset of bytes that was returned. Specifically, if a positive offset is passed into `NewRangeReader()` API, then the `ReaderObjectAttrs.Offset` would reflect that exact same value. However, this becomes more useful when a negative offset is passed to `ReadObjectAttrs`, since this would reflect the actual absolute offset of bytes that was returned.

**Comment by odeke-em** [comment]
Thank you for filing this feature request @brimworks and welcome to the Google Cloud Go project!

In deed, Google Cloud Storage supports negative range requests as per https://cloud.google.com/storage/docs/xml-api/reference-headers#range
<img width="1133" alt="Screen Shot 2019-08-20 at 2 47 48 PM" src="https://user-images.githubusercontent.com/4898263/63383137-8016e300-c359-11e9-811a-9c17c4b0a5f7.png">

Thank you for the CLs too, I am going to take a look.

**Comment by jadekler** [comment]
@frankyn Is this something we support in other languages?

**Comment by frankyn** [comment]
Follow-up through in the CL.

**Comment by brimworks** [comment]
BTW, today was my last day at Puppet, so I no longer have access to the code review tools (nor do I have access to the patches I uploaded). So, I won't be able to make any changes nor will I be able to receive any feedback about the code review. Hopefully this can still make it in, but I won't be able to be there to "escort" it any more.

Thanks,
-Brian

**Comment by odeke-em** [comment]
Oh, thank you @brimworks for working on this, we are almost ready to merge!
Your contributions are much appreciated and wherever your next journey is we look forward to one day having you using these libraries again. Sure, I'll take over your CLs and give you the credit. Cheers!

**Comment by brimworks** [comment]
Thanks!
