### ISSUE TITLE
pubsub: provide an example of using response.Get from receive

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1543]
(it should happen in a gofunc, possibly with an err channel, etc)

**Comment by learncode** [comment]
@jadekler any update on this?

**Comment by jadekler** [comment]
@learncode Not yet - it's assigned and will be worked on as time permits.

**Comment by hongalex** [comment]
This exists in [golang-samples](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/pubsub/topics/publish_scale.go) actually. Closing.
