### ISSUE TITLE
spanner/spansql: cannot parse 0XBEAF (0X-prefixed number)

### ISSUE THREAD

**Issue by MakeNowJust** [googleapis/google-cloud-go#1544]
## Describe Your Environment

Go 1.12.9

## Expected Behavior

The following code should work successfully.
In fact `SELECT 0XBEAF` is valid spanner query.

```go
package main

import (
	"log"

	"cloud.google.com/go/spanner/spansql"
)

func main() {
	log.Println(spansql.ParseQuery("SELECT 0XBEAF"))
}
```

## Actual Behavior

The below error is shown.

```
2019/08/22 14:23:22 {{[] [] <nil>} [] <nil>} unexpected trailing query contents "XBEAF"
```

**Comment by MakeNowJust** [comment]
CL for this is [here](https://code-review.googlesource.com/c/gocloud/+/44352).

**Comment by MakeNowJust** [comment]
> In fact `SELECT 0XBEAF` is valid spanner query.

Actually spanner accepts this:

![スクリーンショット 2019-08-22 15 06 15](https://user-images.githubusercontent.com/6679325/63489948-71156980-c4ee-11e9-9f60-aa6b4700d059.png)

However, the document says:

> Integer literals are either a sequence of decimal digits (0–9) or a hexadecimal value that is prefixed with "0x". Integers can be prefixed by "+" or "-" to represent positive and negative values, respectively.

Maybe it is documentation bug, or spanner internal bug.

**Comment by dsymonds** [comment]
Thanks for the report. However, the entire spansql/spannertest library has a big TODO to support case insensitivity properly, and we should address that, rather than making individual fixes. For now, just use `0x`-prefixed literals.

**Comment by MakeNowJust** [comment]
IMHO this issue isn't be fixed with case insensitivity supports because it is really individual from other case insensitivity problems.

At least, to me, there is only way to solve this issue and other TODOs at once, that the tokenizer unifies character case on reading character. But I don't think it is good solution. What do you think?

**Comment by dsymonds** [comment]
Okay, you make a fair case. Let's proceed with your change.
