### ISSUE TITLE
bigtable: Support a single method to update an instance, including adding/removing clusters

### ISSUE THREAD

**Issue by garye** [googleapis/google-cloud-go#1545]
This is useful for terraform support:
terraform-providers/terraform-provider-google/issues/4318

**Comment by igorbernstein2** [comment]
does this belong in the core client? Shouldn't it be pushed to the terraform provider?

**Comment by garye** [comment]
Maybe? I'll take it up with terraform folks. My understanding was that it made their lives a lot easier to have this in the client. I have the code for the client version so feel free to assign over to me.

**Comment by jadekler** [comment]
> does this belong in the core client? Shouldn't it be pushed to the terraform provider?

(my 2c) +1, also feels like something specific to terraform. But, don't feel too strongly.

**Comment by garye** [comment]
It looks like similar tools such as Ansible, Puppet, Chef, etc. could benefit from an easy way to reconcile a current and a desired instance config (if they ever add Bigtable instance management). Doesn't seem like a terrible idea to have the logic in one place.

**Comment by jadekler** [comment]
Seems reasonable 👍

**Comment by odeke-em** [comment]
For easy following, @garye sent CL https://code-review.googlesource.com/c/gocloud/+/44410 which is still under review.
