### ISSUE TITLE
pubsub: allow messages to be gzipped for sending and receiving

### ISSUE THREAD

**Issue by heldtogether** [googleapis/google-cloud-go#1546]
We send quite a lot of data over pubsub and would like to be able to gzip the message data to help reduce cost. I've written an implementation that makes sense to me and created a code review on Gerrit, see https://code-review.googlesource.com/c/gocloud/+/44175. 

I would appreciate some discussion and feedback.

**Comment by jadekler** [comment]
cc @kamalaboulhosn @hongalex

**Comment by hongalex** [comment]
Hey! Thanks for bringing this to our attention. We're currently looking into this, but traditionally we're a bit hesitant to add one-off features like this into the client library in a single language. Essentially, our goal is to keep the client library experience for Pub/Sub the same across languages.

With that said, supporting compressed messages is definitely a useful feature to have. In the meantime, you might need to just add the gzip compression-logic prior to publishing a message, which I suspect you're probably already doing.

**Comment by heldtogether** [comment]
Thanks for the update @hongalex, makes sense to approach it on the HTTP2 level for support across clients. I look forward to tracking the progress 👍

**Comment by hongalex** [comment]
We were revisiting this issue and decided that the library isn't the best place to implement this. We would need to have a unified compression agreement across libraries (and also gcloud/ web UI) and some way to detect if messages have been zipped or not. If the idea is to save costs, this can still be done on the application level (zip before publishing & unzip in Receive).
