### ISSUE TITLE
bigtable: is it safe to remove WithBlock() from NewClientWithConfig()?

### ISSUE THREAD

**Issue by mattayes** [googleapis/google-cloud-go#1547]
## Client

Bigtable

## Describe Your Environment

N/A

## Problem

I was looking at the code for [`NewClientWithConfig()`](https://github.com/googleapis/google-cloud-go/blob/0f42522d468af83e2d814e7b069402984504f41f/bigtable/bigtable.go#L67-L93) and noticed [this comment](https://github.com/googleapis/google-cloud-go/blob/0f42522d468af83e2d814e7b069402984504f41f/bigtable/bigtable.go#L77-L79):

```go
// TODO(grpc/grpc-go#1388) using connection pool without WithBlock
// can cause RPCs to fail randomly. We can delete this after the issue is fixed.
```

grpc/grpc-go#1388 is closed. Is it safe to remove `WithBlock()`? Happy to do the work if so.

**Comment by odeke-em** [comment]
Thank you for following up @mattayes and welcome to the Google Cloud Go project!

Let me just kindly ping some folks to help confirm: @pongad, @menghanl
