### ISSUE TITLE
firestore: support "add only if non-existent" while adding a document

### ISSUE THREAD

**Issue by learncode** [googleapis/google-cloud-go#1548]
I've observed that while adding document with ID, the operation either creates a new document with the ID as the one passed or overwrites an existing document.

`_, err := client.Collection("cities").Doc("new-city-id").Set(ctx, data)`

Is there some way to prevent the behavior of overwriting an existing document? The only work around I see right now is to make a `GET()` call, if the document is not there then perform the `Add()`. From what I researched the feature I'm looking for is not available, Is it possible to support this feature request?

**Comment by odeke-em** [comment]
Thank you for filing this issue @learncode and welcome to the Google Cloud Go project!

I'll kindly ping @schmidt-sebastian too.

**Comment by jadekler** [comment]
I believe a get and set is correct. You should do so with a [precondition](https://godoc.org/cloud.google.com/go/firestore#hdr-Preconditions) or [transaction](https://godoc.org/cloud.google.com/go/firestore#hdr-Transactions) to prevent race conditions.
