### ISSUE TITLE
bigquery:  implement support use_avro_logical_types for export jobs

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-go#1549]
With the next discovery release, BigQuery will support control of logical type annotations when specifying export jobs that use the Apache Avro file format.  This will be controlled via the use_avro_logical_types.

Description from the API layer: 

[Optional] If destinationFormat is set to "AVRO", this flag indicates
whether to enable extracting applicable column types (such as TIMESTAMP) to
their corresponding AVRO logical types (timestamp-micros), instead of only
using their raw types (avro-long).

This should mirror reciprocal support in load jobs for specifying whether logical type annotations should be used when building the schema of a table.

**Comment by shollyman** [comment]
released v0.10.0 earlier today for go which includes this.

**Comment by shollyman** [comment]
https://code-review.googlesource.com/c/gocloud/+/44953
