### ISSUE TITLE
compute/metadata: add *Client.Email method

### ISSUE THREAD

**Issue by odeke-em** [googleapis/google-cloud-go#1551]
Coming here from @frankyn's code review comment on CL https://code-review.googlesource.com/c/gocloud/+/42270

>The service account should be requested from the Metadata service in case it changes. 

We don't currently have a method to request the email for a service account.

## Problem statement
We can't currently retrieve the email address for a service account on GCE and we need to be able to query the metadata service for the email currently being used, so as to be able to created SignedURLs automagically.

**Comment by jadekler** [comment]
Could you please make the description of this issue standalone, describing why we need this? It's hard to go parse through all the comments in the linked CL.
