### ISSUE TITLE
pubsub: Cannot Publish from Cloud Run

### ISSUE THREAD

**Issue by CaptainCodeman** [googleapis/google-cloud-go#1552]
## Client
PubSub

## Describe Your Environment
Cloud Run (Managed)

## Expected Behavior
Can publish a message to a topic

## Actual Behavior
Error: Container Sandbox Limitation: Unsupported syscall setsockopt(0x8,0x6,0x12,0xc0003451fc,0x4,0x0). Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.

Should this work or are we supposed to use the lower-level `google.golang.org/api/pubsub/v1` package on Cloud Run, as we do with AppEngine?

**Comment by jadekler** [comment]
Thanks for reporting this. Which call produces this error?

**Comment by CaptainCodeman** [comment]
I'm not sure - either the `res := topic.Publish` one or the subsequent `res.Get` (to wait till it had been sent). The message wasn't published from what I could tell.

I did try setting `topic.PublishSettings.NumGoroutines = 1` which didn't _appear_ to make any difference but I noticed this morning that the errors are still showing up in stackdriver logs but from an old, deleted Cloud Run version which must be still alive, so it's possible the errors I was seeing at some point were misleading.

**Comment by hongalex** [comment]
This seems strange. Is this happening all the time, or is it occasional? Also, can you paste your Dockerfile here?

I'm able to publish messages successfully with the `google-cloud-go` repository just fine, using something similar to [this guide](https://medium.com/google-cloud/google-cloud-run-for-go-ec09ddbba111)

**Comment by CaptainCodeman** [comment]
It started happening when I added the code to do the pubsub publish. When I get chance I'll try and make a cut-down app to test it.

Here's what my Dockerfile looks like:

```docker
# syntax=docker/dockerfile:experimental
FROM golang:1.12 as build
WORKDIR /go/src/app
ENV GO111MODULE on
ENV CGO_ENABLED 0
ENV GOOS linux

ARG DOCKER_NETRC
RUN echo "${DOCKER_NETRC}" > ~/.netrc

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -v -o /app .

FROM gcr.io/distroless/static
COPY --from=build /app /app
COPY ./credentials ./credentials
COPY ./templates ./templates

CMD ["/app"]
```

**Comment by hongalex** [comment]
Do you have any updates? I looked into this a bit more, and you might need to deploy using `gcr.io/distroless/base` as your image instead of `gcr.io/distroless/static`.


From [the description for base:](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md)
```Most other applications (and Go apps that require libc/cgo) should start with gcr.io/distroless/base, which contains all of the packages in gcr.io/distroless/static, and glibc libssl openssl```

**Comment by CaptainCodeman** [comment]
Yeah, this still happens with the different base image (`gcr.io/distroless/base`)

Just trying to create the pubsub client instance triggers it, so it's unusable to publish messages from cloud run.

**Comment by CaptainCodeman** [comment]
Here's a reproduction:

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"net/http"

	"cloud.google.com/go/pubsub"
)

var (
	ps *pubsub.Client
)

func init() {
	ctx := context.Background()

	var err error
	ps, err = pubsub.NewClient(ctx, "photo-serve-data")
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	http.HandleFunc("/", handler)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Listening on %s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello world!")
}
```

Docker file using `gcr.io/distroless/base`

Results in:
<img width="1196" alt="Screen Shot 2019-11-11 at 11 53 06 AM" src="https://user-images.githubusercontent.com/304910/68612502-e5223680-0479-11ea-8ce2-782fde86735e.png">

**Comment by brendanstennett** [comment]
Receiving the same error message with the Ruby client.  Service account associated with the service has permission to publish and the publish works fine locally.

**Comment by hongalex** [comment]
So I commented this in the [issue tracker](https://issuetracker.google.com/issues/144256396) as well but I was able to see the `unsupported syscall` message in stackdriver logging, but saw that the message was published in spite of this. Can you double check to see if you are able to publish a message too? We suspect that the message listed here is a warning rather than an error.

**Comment by CaptainCodeman** [comment]
Even if the message is published, it caused other issues with Cloud Run - the service ended up with a red exclamation mark against it (but just "unknown error") and the revision it _said_ was serving requests was pinned to an older version, even after deploying newer ones (which did actually serve requests). The old ones were still running though and filling the logs with repeated error messages so I wouldn't deploy code with it even if it published as it seemed to make things unstable.

**Comment by steren** [comment]
Unimplemented syscalls are debug messages, not error messages. They likely have nothing to do with the issue you are encountering.
Speaking of the issue, it seems that the messages are actually published to PubSub, so, should we close this issue?

**Comment by hongalex** [comment]
Also, the red exclamation mark is related to deployment rather than errors that happen during invocations. Can you try deploying again to see if that goes away?

**Comment by CaptainCodeman** [comment]
It ended up going away (after a few weeks) but only started when I tried to add the code with this pub-sub issue and in my naive thinking, the thing I just changed caused the issues I started seeing immediately after that change.

It wasn't just one messages in the log, it was a constant stream of them.

**Comment by codyoss** [comment]
Closing this out as this seems to be resolved. Please reopen if that is not the case.
