### ISSUE TITLE
spanner: Remove AppEngine-specific `numChannels` behavior

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#1553]
/cc @sbuss to correct any of my misunderstandings.

According to [Go Versions Supported](https://github.com/googleapis/google-cloud-go#go-versions-supported), this project only supports the two most recent versions of Go. AppEngine supports Go 1.11 and Go 1.12, with Go 1.9 being phased out imminently.

IIUC (and it's possible that I don't), beyond Go 1.9, this can use the regular implementation, and so there should be no need to have alternate `numChannels` definitions selected by the `appengine` build tag, which is going to be deprecated. 

This means removing the following two files:
*   https://github.com/googleapis/google-cloud-go/blob/master/spanner/appengine.go
*   https://github.com/googleapis/google-cloud-go/blob/master/spanner/not_appengine.go

…and placing the `numChannels` definition somewhere else.

Once this is done and reimported back into the mono-repo, we can remove a bunch of bazel-related complexity to create separate AppEngine and non-AppEngine build targets.

**Comment by jadekler** [comment]
Would be great if we can drop 1.9. Definitely curious to hear from @sbuss. cc @broady.
