### ISSUE TITLE
pubsub: integration test that asserts x-goog-api-client (and related headers) is being sent

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1554]
go/cloud-api-headers-2019

**Comment by odeke-em** [comment]
Since pubsub has its own modules, we'll just update the tests in pubsub after cutting a new release of cloud.google.com/go

**Comment by odeke-em** [comment]
The exact changes for pubsub can be retrieved from patchset 12 of the fixing CL at
https://code-review.googlesource.com/c/gocloud/+/45130/12.

**Comment by odeke-em** [comment]
This issue was fixed by CL https://code-review.googlesource.com/c/gocloud/+/45130

**Comment by jadekler** [comment]
Thanks Emmanuel!

**Comment by odeke-em** [comment]
Actually, I reverted the change because pubsub modules were trippin' :) I'll send the full CL shortly though.

**Comment by odeke-em** [comment]
So the code in testIAM in integration_test.go makes requests with Handles made from the *grpc.ClientConn connection of the client which unfortunately doesn't have the underlying infrastructure to send those pre-set headers along and that tripped out more tests which led me on a dig for a long time as it was an unexpected part of the unit tests
https://github.com/googleapis/google-cloud-go/blob/1b8eb06c5057030c75ed4a519d64f9e36c4bff00/pubsub/integration_test.go#L254

and that test only takes in a context.Context as well as the handles -- this is what delayed the CL.
