### ISSUE TITLE
firestore: integration test that asserts x-goog-api-client (and related headers) is being sent

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1557]
go/cloud-api-headers-2019

**Comment by odeke-em** [comment]
So for firestore, we've already got a grpc interceptor in the integration tests that tests that these headers are ALWAYS sent as per
https://github.com/googleapis/google-cloud-go/blob/d4d57431b6a369d42130c17867ad7d92b6ff2970/firestore/integration_test.go#L80

and
https://github.com/googleapis/google-cloud-go/blob/d4d57431b6a369d42130c17867ad7d92b6ff2970/firestore/integration_test.go#L111-L129

**Comment by odeke-em** [comment]
I think for gRPC, we can scale all these tasks by creating in internal/testutil a struct HeadersEnforcer and we can add to it specific fields to check or by default just "x-goog-api-client".

/cc @shollyman @jadekler

**Comment by jadekler** [comment]
@odeke-em Could you provide a CL demonstrating this?

**Comment by odeke-em** [comment]
@jadekler yes I can once I arrive and I am settled in at my office :)

**Comment by odeke-em** [comment]
@jadekler I am finally settled and I've mailed https://code-review.googlesource.com/c/gocloud/+/45130
