### ISSUE TITLE
firestore: document the right scope to use

### ISSUE THREAD

**Issue by kjk** [googleapis/google-cloud-go#1560]
I spent way too much time figuring out how to authenticate with Firebase project from Go.

I only had cryptic messages about not being authorized / wrong scopes to go on. The docs are not adequate.

I was following https://godoc.org/cloud.google.com/go/firestore

The bottom line is that I had to do:
```
creds, err := google.CredentialsFromJSON(ctx, d, "https://www.googleapis.com/auth/datastore")
```

The error was that I initially had:
```
creds, err := google.CredentialsFromJSON(ctx, []byte("JSON creds"), pubsub.ScopePubSub)
```
(based on CredentialsFromJSON example in https://godoc.org/cloud.google.com/go).

Obviously, `pubsub.ScopePubSub` is the wrong scope, but being new to the SDK such details tend to escape the notice.

The biggest problem is that even when I figured out that I have to change scope, there is no  `firestore.ScopeFirestore` and https://godoc.org/cloud.google.com/go/firestore has zero mention of scopes.

To make things really bad, there is no https://www.googleapis.com/auth/firestore scope, but https://www.googleapis.com/auth/datastore works. It was a lucky guess that I figured it at all.

## What to do

At the very minimum, add a constant `firestore.ScopeFirestore`:
```go
const (
    ScopeFirestore = "https://www.googleapis.com/auth/datastore"
)
```

Add more information about scopes and how to set them (either when creating credentials or when creating a client).

To make things foolproof for people just following main docs, change example:

```go
ctx := context.Background()
client, err := firestore.NewClient(ctx, "projectID")
if err != nil {
	// TODO: Handle error.
}
```

to:
```go
ctx := context.Background()
scopeOption := option.WithScopes(firestore.ScopeFirestore)
client, err := firestore.NewClient(ctx, "projectID", scopeOption)
if err != nil {
	// TODO: Handle error.
}
```
(I assume it'll add/overwrite the scopes from creds).

Better yet, `firestore.NewClient` should just set the right scope. 

Is there a use case for a firestore client that doesn't have this scope? Seems to me it would be completely useless.

**Comment by jadekler** [comment]
Which library are you using?

**Comment by jadekler** [comment]
Ah, shoot, your original message includes a godoc link - sorry, I should have seen that. Thanks for reporting this frustration. There is a [DefaultAuthScopes](https://godoc.org/cloud.google.com/go/firestore/apiv1#DefaultAuthScopes) in `/apiv1`, but I could see that not being obvious. Will keep this open and think on a way to make that a bit more obvious.

**Comment by jadekler** [comment]
So, for the `cloud.google.com/go/firestore` client, the scopes are provided for you: you should not have to specify them at all. If you're using the lower-level `cloud.google.com/go/firestore/apiv1` client, you should use [DefaultAuthScopes](https://godoc.org/cloud.google.com/go/firestore/apiv1#DefaultAuthScopes).

**Comment by kjk** [comment]
This is not about my problems, which I have now solved.

This bug is about documentation for the next person. Has anything changed?

I was following https://godoc.org/cloud.google.com/go/firestore and had very frustrating experience due to things not being documented well.

Here's how my journey looked like:

I started at https://godoc.org/cloud.google.com/go/firestore which refers to https://godoc.org/cloud.google.com/go for authentication.

So I copied and pasted CredentialsFromJSON example and didn't notice it uses `pubsub.ScopePubSub`.

Understand that as someone new to the whole thing, I have no idea what scopes. This is not called out in the example.

That fails with cryptic error message about auth. I resort to googling and re-reading the docs.

Finally I had a flash of insight and connected the auth error messages to scopes and tried to figure out what scope to use. Googling "firestore scopess" turned nothing. 

I tried googling ScopeFirestore`. Again, nothing.

I looked at the code and what `pubsub.ScopePubSub` is and I tried the string `https://www.googleapis.com/auth/firestore`. This doesn't work.

So I had second hail mary and tried `https://www.googleapis.com/auth/datastore`. Finally that worked.

Tell me how can anyone start with https://godoc.org/cloud.google.com/go/firestore and figure those things out? 

How am I even supposed to know about cloud.google.com/go/firestore/apiv1 and https://godoc.org/cloud.google.com/go/firestore/apiv1#DefaultAuthScopes ?

It can be easily solved by adding an auth section with tested examples to https://godoc.org/cloud.google.com/go/firestore so that people can copy&paste.

How am I supposed to know if I should use https://godoc.org/cloud.google.com/go/firestore/apiv1 or https://godoc.org/cloud.google.com/go/firestore?

I mean from reading the docs those packages.

Finally:
> So, for the cloud.google.com/go/firestore client, the scopes are provided for you: you should not have to specify them at all. 

I don't know what that means. I'm guessing that you mean that not giving any scopes to `google.CredentialsFromJSON` will work.

If that's true across packages, then fix `CredentailsFromJSON` example at https://godoc.org/cloud.google.com/go to not provide a scope for pubsub when it's a generic auth example.

**Comment by kjk** [comment]
Regarding:

> So, for the cloud.google.com/go/firestore client, the scopes are provided for you: you should 
not have to specify them at all.

I just checked and doesn't seem correct.

I changed my code from working:

```go
const (
	ScopeFirestore = "https://www.googleapis.com/auth/datastore"
)

func getFirestoreClient() (*firestore.Client, error) {
	ctx := context.Background()
	d := []byte(jsonCreds)
	creds, err := google.CredentialsFromJSON(ctx, d, ScopeFirestore)
	if err != nil {
		return nil, err
	}
	optCreds := option.WithCredentials(creds)
	client, err := firestore.NewClient(ctx, gcpProjectID, optCreds)
	if err != nil {
		return nil, err
	}
	return client, nil
}
```

to omitting the scopes:
```
creds, err := google.CredentialsFromJSON(ctx, d)
```

And it leads to:
```
rpc error: code = Unauthenticated desc = transport: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_scope",
  "error_description": "Empty or missing scope not allowed."
}
```

**Comment by jadekler** [comment]
Sorry, you're right, that statement was incorrect. I think I see one way we could increase the documentation is to point to where to find scopes in that example you used. I've filed https://code-review.googlesource.com/c/gocloud/+/44950.
