### ISSUE TITLE
datastore: document how to distinguish "entity exists" errors

### ISSUE THREAD

**Issue by bobg** [googleapis/google-cloud-go#1561]
Please export an error from the `datastore` library for the case where the mutation produced by `NewInsert` encounters an existing key.

## Client

Cloud datastore

## Expected Behavior

```
ins := datastore.NewInsert(...)
_, err := client.Mutate(ctx, ins)
if merr, ok := err.(datastore.MultiError); ok && merr[0] == datastore.EntityExists {
  // handle entity-exists case
} else if err != nil {
  // handle error
} else {
  // handle entity-was-inserted case
}
```

## Actual Behavior

According to [the doc](https://godoc.org/cloud.google.com/go/datastore#NewInsert):
> NewInsert creates a mutation that will save the entity src into the datastore with key k, returning an error if k already exists.

But it doesn't say what the error is, and the `datastore` library does not appear to export an error that means "entity exists," so there's no way to test the return value from `Mutate`.

**Comment by bobg** [comment]
I think I figured out the way this is supposed to work in code:

```
ins := datastore.NewInsert(...)
_, err := client.Mutate(ctx, ins)
if merr, ok := err.(datastore.MultiError); ok && status.Code(merr[0]) == codes.AlreadyExists {
  // handle entity-exists case
} else if err != nil {
  // handle error
} else {
  // handle entity-does-not-exist case
}
```

(using the `status` and `codes` packages from grpc).

Can you confirm that this is right? If it is, then all that's needed is to update the documentation. Thanks!

**Comment by jadekler** [comment]
Yes, that looks correct.

**Comment by odeke-em** [comment]
I mailed https://code-review.googlesource.com/c/gocloud/+/44810 to show to examine the respective RPC status coded errors.

**Comment by bobg** [comment]
Thanks @odeke-em !

However, since I wrote [the comment above](https://github.com/googleapis/google-cloud-go/issues/1561#issuecomment-526451586) I discovered that I need to look for GRPC status codes in both `datastore.MultiError`s and in non-`MultiError`s. Both can come back from `datastore.Mutate`.

I added [a comment](https://code-review.googlesource.com/c/gocloud/+/44810/1#message-6f8a09e8c0020e8776572c17ca3ff683db8eeeac) in Gerrit about this.
