### ISSUE TITLE
firestore: serverTimestamp behavior is counter-intuitive

### ISSUE THREAD

**Issue by CaptainCodeman** [googleapis/google-cloud-go#1562]
I find the behavior of the `serverTimestamp` _tag_ counter-intuitive and surprising.

The docs say:

> serverTimestamp: The field must be of type time.Time. When writing, if the field has the zero value, the server will populate the stored document with the time that the request is processed.

Great, very useful - perfect for created or updated event timestamps. Given this struct:

```go
Test struct {
	Name    string    `firestore:"name"`
	Created time.Time `firestore:"created,serverTimestamp"`
}
```

If I write the data without the `Created` property set (so a zero time value):

```
ref := client.Doc("test/thing")
data := Test{
	Name: "Thing",
}
ref.Set(ctx, data)
```

... the created timestamp is set as expected:

![save with timestamp](https://user-images.githubusercontent.com/304910/63876537-f2537d00-c982-11e9-9eb3-6a77bbbd6e04.png)

However, if I want to set my own time value, most typically because I have loaded the struct from the database to make some modifications and now want to save it or I'm adding pre-existing data from another source, then the behavior is that the field is _not_ saved:

```go
// load existing record
doc, err := ref.Get(ctx)
if err != nil {
  t.Fatal(err)
}

// populate the struct
if err := doc.DataTo(&data); err != nil {
  t.Fatal(err)
}

// update the entity
data.Name = "Updated Thing"

// resave it
if _, err := ref.Set(ctx, data); err != nil {
  t.Fatal(err)
}
```

In this case the field is not saved (no `created` property in the database):

![save without timestamp](https://user-images.githubusercontent.com/304910/63876703-4b231580-c983-11e9-866e-c3469e38fa6a.png)

The docs don't mention this clearly - I think at the very least it should make clear that a `time.Time` field that does _not_ have the zero value won't be saved at all.

However, this seems like the worst database behavior I can imagine - I'm asking the client to "save this thing" and it doesn't. I struggle to think of a scenario where I have a time value set on a struct, mapped to a property with a firestore tag and _wouldn't_ want and expect that to save to the database. I would expect the tag to only affect the behavior if the `time.Time` field were zero, in a better way than using `time.Now()` because it's using Google's atomic clock wizardry.

It's quite different behavior to other clients (e.g. node) where you can round-trip loading and saving something without having fields disappear.

It's not todo with wanting to do a merge or not. I have a struct, it has a value, I'd like it to save the value.

**Comment by jadekler** [comment]
> The docs don't mention this clearly - I think at the very least it should make clear that a time.Time field that does not have the zero value won't be saved at all.

We do currently have,

> - serverTimestamp: The field must be of type time.Time. When writing, if
  the field has the zero value, the server will populate the stored document with
  the time that the request is processed.

But, I agree, we could make it clear that in the non-zero case it no-ops.

> However, if I want to set my own time value, most typically because I have loaded the struct from the database to make some modifications and now want to save it or I'm adding pre-existing data from another source, then the behavior is that the field is not saved:

IIRC this is intentional: that fields labeled `ServerTimestamp` are read-only. I think what you're looking for is using the [ServerTimestamp](https://godoc.org/cloud.google.com/go/firestore#pkg-constants) constant on creation.

The docs here could be improved, though.

**Comment by CaptainCodeman** [comment]
But when the time.Time field _isn't_ a zero value, why wouldn't it just behave as thought the serverTimestamp tag wasn't there?

Why wouldn't it be the same as this:

```
Test struct {
	Name    string    `firestore:"name"`
	Created time.Time `firestore:"created"`
}

ref := client.Doc("test/thing")
data := Test{
	Name: "Thing",
	Created: time.Now(),
}
ref.Set(ctx, data)
```

You'd expect the created field to be written.

**Comment by jadekler** [comment]
cc @tritone
