### ISSUE TITLE
Unable to fetch thrift

### ISSUE THREAD

**Issue by magicalbanana** [googleapis/google-cloud-go#1563]
(delete this for feature requests)

## Client

`/go` package

## Describe Your Environment

GKE

## Expected Behavior

Should be able to perform `go get` successfully

## Actual Behavior

Unable to fetch `thrift`.

```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/foo/projekts/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out

```

**Comment by magicalbanana** [comment]
Wrong repo.

**Comment by magicalbanana** [comment]
@JustinBeckwith is this still an issue?

**Comment by tbpg** [comment]
@magicalbanana No, this was an automated cleanup that got a little overzealous. No action required. :smiley:
