### ISSUE TITLE
firestore: DocumentRef.Get sleeps when on GKE

### ISSUE THREAD

**Issue by tevjef** [googleapis/google-cloud-go#1564]
Not sure how to even start debugging this. I make a get call and it just sleeps in the goroutine. 
What's odd is that deploying locally works fine, but when it runs on GKE it just sleeps. The network on GKE works fine, other parts of that same application make external API calls. 

stacktrace of the sleeping goroutine:
```
#	0xb00d71	github.com/googleapis/gax-go.Sleep+0xd1						/go/pkg/mod/github.com/googleapis/gax-go@v2.0.2+incompatible/invoke.go:54
#	0xb00f4f	github.com/googleapis/gax-go.invoke+0x11f					/go/pkg/mod/github.com/googleapis/gax-go@v2.0.2+incompatible/invoke.go:85
#	0xb00c65	github.com/googleapis/gax-go.Invoke+0xf5					/go/pkg/mod/github.com/googleapis/gax-go@v2.0.2+incompatible/invoke.go:47
#	0xb550ca	cloud.google.com/go/firestore/apiv1beta1.(*Client).BatchGetDocuments+0x1ca	/go/pkg/mod/cloud.google.com/go@v0.26.0/firestore/apiv1beta1/firestore_client.go:282
#	0xb62eee	cloud.google.com/go/firestore.(*Client).getAll+0x44e				/go/pkg/mod/cloud.google.com/go@v0.26.0/firestore/client.go:154
#	0xb64c19	cloud.google.com/go/firestore.(*DocumentRef).Get+0xf9				/go/pkg/mod/cloud.google.com/go@v0.26.0/firestore/docref.go:72
```

**Comment by odeke-em** [comment]
Hello @tevjef, thank you for filing this issue!

So you can debug in your logs with `GODEBUG=http2debug=2` but that sleep is part of the exponential backoff. The debug HTTP/2 logs will show you why it is failing.

**Comment by tevjef** [comment]
Rookie mistake on my part. I had forgotten to add a certificate authority on this particular container.
