### ISSUE TITLE
Add repo metadata to all clients

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1567]
Each gapic and manual needs the following file:

```
.repo-metadata.json
{
        "name": "pubsub",
        "name_pretty": "Cloud Pub/Sub API"
        "product_documentation": "https://cloud.google.com/pubsub",
        "client_documentation": "http://godoc.org/cloud.google.com/go/pubsub"
        "release_level": "ga", # oneof alpha, beta, ga, deprecated
        "language": "go",
        "repo": "googleapis/google-cloud-go",
        "distribution_name": "cloud.google.com/go/pubsub", # for gapics, this is just "cloud.google.com/go"
        "api_id": "pubsub.googleapis.com",
        "requires_billing ": true
}
```

**Comment by odeke-em** [comment]
SGTM, but I'll need more information on where to get that metadata.

**Comment by odeke-em** [comment]
I've got it and will submit a CL later today :)

**Comment by odeke-em** [comment]
CLs https://code-review.googlesource.com/c/gocloud/+/44891 and https://code-review.googlesource.com/c/gocloud/+/44910 have been merged in. I'll do a walkthrough to examine what spots were missed and then we can close this issue afterwards.

**Comment by jadekler** [comment]
Thank you, Emmanuel.

**Comment by odeke-em** [comment]
And now we can close this after the second comb through with CL https://code-review.googlesource.com/c/gocloud/+/44952.
