### ISSUE TITLE
Update MultiRegional and Regional to Standard

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-go#1570]
(I don't have assign privileges in this repo but this should be assigned to @odeke-em )
Previously, we implemented the concept of "Location Type" to move the concept of bucket location away from storage class. It is no longer considered correct to use "MultiRegional" or "Regional" as a storage class, instead those should be location types.

As such, we need to update every instance of the "MultiRegional" and "Regional" storage in samples, library documentation, and tests to use "Standard" instead--Standard is a correct storage class.

Note that "MultiRegional" and "Regional" should only be replaced with "Standard" in cases where they are used a storage class. If they're used as a location type, that's fine and doesn't need to be replaced.

https://github.com/googleapis/google-cloud-go/blob/f5404d6c65b2a7a73e4914d7463b6342d6d676e2/storage/bucket_test.go
https://github.com/googleapis/google-cloud-go/blob/f5404d6c65b2a7a73e4914d7463b6342d6d676e2/storage/integration_test.go#L257

**Comment by odeke-em** [comment]
Cool, thank you @JesseLovelace for sending over the update from your end!

I've mailed CL https://code-review.googlesource.com/c/gocloud/+/45230 to remove "MULTI_REGIONAL" and "REGIONAL" from StorageClass, replacing them with "STANDARD".
