### ISSUE TITLE
Logging: use PageToken directly

### ISSUE THREAD

**Issue by ptone** [googleapis/google-cloud-go#1572]
(delete this for feature requests)

## Client

logging

## Describe Your Environment

Cloud Run

## Expected Behavior

I want to be able to use https://godoc.org/google.golang.org/genproto/googleapis/logging/v2#ListLogEntriesRequest `PageToken` field directly in 
https://godoc.org/cloud.google.com/go/logging/logadmin#Client.Entries

But there is no https://godoc.org/cloud.google.com/go/logging/logadmin#EntriesOption that exposes it.

I don't want to use the iterator.NewPager as that just paginates the returned iterator

## Actual Behavior

I'm stuck using a timestamp based pagination system with Client.Entries

**Comment by jadekler** [comment]
Thanks for the feature request. Not sure when we'll get to this, but in the meantime you could build a small iterator around the lower-level https://godoc.org/cloud.google.com/go/logging/apiv2 if you need this right away.
