### ISSUE TITLE
errorreporting: Direct error reports to stderr

### ISSUE THREAD

**Issue by Yekut** [googleapis/google-cloud-go#1582]
Is there a way to configure the errorreporting client to print out errors, e.g., to stderr, instead of sending directly to StackDriver? Having looked at the available `errorreporting.Config` and `option.ClientOption` but these don't seem to provide a solution.

It could obviously be done with a "debug" client that has the same interface and prints out to stderr, but wondering if there's a built in way to support this use case (or if it'll be worth it to add one).

**Comment by jadekler** [comment]
Unfortunately not AFAIK: wrapping with an interface and providing your own output switching is the correct way.
