### ISSUE TITLE
What is correct way to form request for creating/listing SA roles?

### ISSUE THREAD

**Issue by csandanov** [googleapis/google-cloud-go#1586]
I'm following the docs at https://cloud.google.com/iam/docs/granting-roles-to-service-accounts trying to create/list roles for a service account.

Creation:

```go
saEmail := "my-sa@my-project.iam.gserviceaccount.com"
policyRequest := &iam.SetIamPolicyRequest{
	Policy: &iam.Policy{
		Bindings: []*iam.Binding{&iam.Binding{
			Members: []string{"serviceAccount:" + saEmail},
			Role:    "roles/container.admin",
		}},
	},
}
policy, err := service.Projects.ServiceAccounts.SetIamPolicy("projects/my-project", policyRequest).Do()
```

I get the error:
```
The requested URL <code>/v1/projects/my-project:setIamPolicy?alt=json&amp;prettyPrint=false</code> was not found on this server. 
```

I tried to specify a service account name as a resource instead of `projects/my-project` but got a different error.
```
Role roles/container.admin is not supported for this resource.
```
I went to the console and assigned the role manually without any issues. Tried to get it:
```go
service, _ := iam.NewService(ctx, option.WithTokenSource(tokenSource))
saEmail := "my-sa@my-project.iam.gserviceaccount.com"
res := "projects/my-project/serviceAccounts/" + saEmail
policy, _ := service.Projects.ServiceAccounts.GetIamPolicy(res).Do()
```
There's no error but `policy.Bindings` is always empty.

What is the correct way to form create/listing requests for SA roles?

**Comment by csandanov** [comment]
Ok, I figured out, `setIamPolicy` method actually has comprehensive comments:
> // SetIamPolicy: Sets the Cloud IAM access control policy for
// a
// ServiceAccount.
//
// Note: Service accounts are both
// [resources
// and
// identities](/iam/docs/service-accounts#service_account_permissions
// ). This
// method treats the service account as a resource. Use it to grant
// members
// access to the service account, such as when they need to impersonate
// it.
//
// This method does not grant the service account access to other
// resources,
// such as projects. To grant a service account access to resources,
// include
// the service account in the Cloud IAM policy for the desired resource,
// then
// call the appropriate `setIamPolicy` method on the target resource.
// For
// example, to grant a service account access to a project, call
// the
// [projects.setIamPolicy](/resource-manager/reference/rest/v1/projec
// ts/setIamPolicy)
// method.

**Comment by jadekler** [comment]
Thanks for posting the follow-up solution. :)
