### ISSUE TITLE
Unflake TestIntegration_HTTPR

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1587]
https://sponge.corp.google.com/target?id=60039573-29f9-4a76-9e75-85e83a0c81c3&target=cloud-go-libraries/google-cloud-go/continuous/go113&searchFor=&show=ALL&sortBy=STATUS

```
=== RUN   TestIntegration_HTTPR
--- FAIL: TestIntegration_HTTPR (12.12s)
    integration_test.go:73: server never came up
FAIL
FAIL	cloud.google.com/go/httpreplay/cmd/httpr	12.160s
```

**Comment by codyoss** [comment]
Closing this issue for now as this has not popped up in that last 8 months. Buildcop will alert us if it does.
