### ISSUE TITLE
logging: incorrect parsing of Trace Context header without sampling indicator

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1590]
Sometimes the header doesn't include the sampling information.

e.g.:

```
X-Cloud-Trace-Context: 6518720b40e1efacf2299758d229210a/14866474463603563926
```

Current assumption:

```
var reCloudTraceContext = regexp.MustCompile(`([a-f\d]+)/([a-f\d]+);o=(\d)`)
```

**Comment by odeke-em** [comment]
Hey @broady, thanks for this report!

Coming here from the trace-context specification for Stackdriver https://cloud.google.com/trace/docs/troubleshooting#force-trace
![Screen Shot 2019-09-20 at 1 26 05 PM](https://user-images.githubusercontent.com/4898263/65356820-3add0f80-dbaa-11e9-97e3-17fb8059f0a5.png)
and  also from the CL that I sent to enforce it in commit https://github.com/googleapis/google-cloud-go/commit/392bd16d8f72017d4999a896d28ccbfd536aca52#diff-ad8a2265fa17b7808fca5ae77cada94f are we asking that we parse a malformed `X-Cloud-Trace-Context`? That is a header value without the `;o=(\d)` part?

**Comment by broady** [comment]
Hm, if this is indeed the spec then I need to file a bug against App Engine.

**Comment by nicoleczhu** [comment]
Hi @broady fyi at the client library level, we now accept user input where sampleTrace field is optional (in which case, we default sampleTrace to false). 

However, this fix doesn't solve the lower lvl issue where the service is not flagging it as true when it should be. Thanks!
