### ISSUE TITLE
pubsub: invalid memory address in pubsub.(*Topic).initBundler (topic.go:468)

### ISSUE THREAD

**Issue by cmoad** [googleapis/google-cloud-go#1593]
## Client

PubSub (cloud.google.com/go/pubsub v1.0.1)

## Describe Your Environment

Scratch Docker on GKE

## Expected Behavior

No segfault. We're seeing a periodic segfault in our logs. It appears to be coming from the pubsub library attempting to acquire an internal lock, so I don't believe it has anything to do with our code.

## Actual Behavior

```
runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xba8cee]
at sync.(*RWMutex).RLock (rwmutex.go:48)
at cloud.google.com/go/pubsub.(*Topic).initBundler (topic.go:468)
at cloud.google.com/go/pubsub.(*Topic).Publish (topic.go:396)
```

**Comment by hongalex** [comment]
Hey, thanks for bringing this to our attention. Can you describe the conditions in which this error is occurring? Specifically, I wanted to know:

1. How often this error is occurring. Does it happen soon after starting up the client, or does it take a while before it starts?
2. What values do have you set for [`PublishSettings`](https://godoc.org/cloud.google.com/go/pubsub#PublishSettings)?

**Comment by cmoad** [comment]
1. Strangely it's only happened in one service (we have ~15) and we only run a single instance of this particular service. It has happened 13 times in 3d2h.
2. We don't customize PublishSettings.

**Comment by hongalex** [comment]
This may actually be because `CreateTopic` can return nil if the topic already exists. An example of this is in https://github.com/GoogleCloudPlatform/golang-samples/pull/363. Can you check if you are calling `CreateTopic` prior to the segfaults?

**Comment by cmoad** [comment]
I checked and we do ensure the topic in the startup of all our microservices using the following code. I can't explain why only a single service is affected. I restarted the pod for that service this morning to see if the pattern continues. There were 13 more restarts in the last 4 days.

```golang
// MustCreateTopicIfNotExists ...
func MustCreateTopicIfNotExists(c *pubsub.Client, topic string) *pubsub.Topic {
	ctx, cancelFunc := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancelFunc()

	// Check if the topic already exists
	t := c.Topic(topic)
	exists, err := t.Exists(ctx)
	if err != nil {
		panic(err)
	}
	if exists {
		return t
	}

	// Create the topic since it doesn't exist
	if t, err = c.CreateTopic(ctx, topic); err != nil {
		panic(err)
	}

	return t
}
```

**Comment by hongalex** [comment]
For some reason, I'm still having some difficulty reproducing the issue. What version of Go are you on?

I'm wondering if it's an issue with the environment rather than the library, since you said you have other instances of the same library that's working fine.

**Comment by cmoad** [comment]
We use docker base images golang:1.13-alpine for our builds and scratch for deployment. I'm doing refresh build of the affected services just to see if anything changes.

**Comment by cmoad** [comment]
23 hours later and no errors. Possibly something bad with that build? I'll reopen if I see this issue again. Thanks for the help.
