### ISSUE TITLE
Vision: Why no scores in EntityAnnotations for text detection?

### ISSUE THREAD

**Issue by beattymg** [googleapis/google-cloud-go#1595]
Why does the SDK return empty confidence in `EntityAnnotations` for text detection? Is this a feature or a bug?

I see confidence values for the predicted locale, but it would be useful to have them for each text annotation.

**Comment by jadekler** [comment]
Hello! Are you using https://godoc.org/cloud.google.com/go/vision/apiv1?

**Comment by beattymg** [comment]
Hi @jadekler! Yes, I am.

Wondering about text annotation score/confidence since it appears for in `EntityAnnotation`s for other tasks (like the responses from label detection).

**Comment by jadekler** [comment]
Right on! So, that library is auto-generated in several languages from a common spec (https://github.com/googleapis/googleapis). Service teams like vision tend not to spend a lot of time tracking these per-language repositories, especially if their client is just auto-generated.

Therefore, would you mind re-filing your issue at one of the support channels that the vision team keeps eyes on? Those can be found at https://cloud.google.com/vision/docs/support.

Closing for now, but happy to keep chatting if you'd like to continue the conv. :)
