### ISSUE TITLE
logging.Entry should support no payload

### ISSUE THREAD

**Issue by ptone** [googleapis/google-cloud-go#1597]
## Client

logging

## Describe Your Environment

GCE, cloudshell, and go cloud builders

## Expected Behavior

logadmin list entries method not fatal exit on service generated entries

## Actual Behavior

The `run.googleapis.com/requests` log generates entries that have no payload.

If you use https://godoc.org/cloud.google.com/go/logging/logadmin#Client.Entries

to list these entries, the Iterator bombs out from this switch statement: 
https://github.com/googleapis/google-cloud-go/blob/master/logging/logadmin/logadmin.go#L312

The payload is marked as optional:
https://github.com/googleapis/googleapis/blob/master/google/logging/v2/log_entry.proto#L71

**Comment by jadekler** [comment]
Sorry, I'm having a bit of trouble following this. (it could be because it's midnight, and I haven't looked at the logging library in a bit, but...)

Would you mind posting a small code snippet to show what you're describing?

**Comment by ptone** [comment]
https://gist.github.com/ptone/219bf6709cbcc01cccb0ae2522b2555d

To fully reproduce of course you would of course need a project with a cloud run service which has recently received requests.

The issue is that cloud run does not provide ANY payload or payload type for this type of request in the Entry proto, and the go library assumes it is always one of the types. However the proto file comment clearly marks this fields as optional.

**Comment by jadekler** [comment]
I was able to repro this with this program: https://gist.github.com/jadekler/9293a2f74f0509c8dd32ba3d8e80ae09. Here's the output incl a sample log:

```
deklerk at deklerk-macbookpro2 in ~/workspace/google-cloud-go/logging on master*
$ go run dummy/main.go
log_name:"projects/deklerk-sandbox/logs/run.googleapis.com%2Frequests" resource:<type:"cloud_run_revision" labels:<key:"configuration_name" value:"hello" > labels:<key:"location" value:"us-central1" > labels:<key:"project_id" value:"deklerk-sandbox" > labels:<key:"revision_name" value:"hello-00001" > labels:<key:"service_name" value:"hello" > > timestamp:<seconds:1569881271 nanos:612530000 > receive_timestamp:<seconds:1569881271 nanos:623047687 > severity:INFO insert_id:"5d927cb7000958b2d017875c" http_request:<request_method:"GET" request_url:"https://hello-m7zva4imga-uc.a.run.app/" request_size:769 status:200 response_size:4388 user_agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" remote_ip:"2607:fb90:1782:5a97:28d9:9e42:cddb:b345" server_ip:"2001:4860:4802:36::35" latency:<nanos:6223475 > protocol:"HTTP/1.1" > labels:<key:"instanceId" value:"00bf4bf02d735a1043eeb0070e92e28f7589f6f575e1ac9108d408da72715c22b6b5943ede06271edfffe284c8f1f7c3def8abc5210e3a842a048cbd68f12c143b727f" > trace:"projects/deklerk-sandbox/traces/cee87b0d902526ffb4aa90c04f305f07"
panic: logging: unknown payload type: <nil>

goroutine 1 [running]:
main.main()
	/Users/deklerk/workspace/google-cloud-go/logging/dummy/main.go:26 +0x203
exit status 2
```

Re-classifying as a bug.

**Comment by jadekler** [comment]
@ptone I've waffled on what priority this should be. Is there a way to get around it in your code? If not, I'll bump the priority and get it fixed ASAP. If not, I'll keep it as-is and use it as an introductory bug for one of our new members, which may take a bit more time.

**Comment by ptone** [comment]
I agree this is a good size small project good for onboarding (I considered tackling the PR, but I'm trying to focus on the surrounding work). I'm able to work around it for now by excluding that log in my filter.  So I would not consider it urgent/high.

**Comment by jadekler** [comment]
Awesome. Thanks again for reporting this so thoroughly, and thanks for your patience. Will ping back when we resolve this.
