### ISSUE TITLE
logging: document about "Grouping Logs by Request" parent.timestamp meaning

### ISSUE THREAD

**Issue by vvakame** [googleapis/google-cloud-go#1598]
## Client

Logging

## Describe Your Environment

AppEngine/SE

## Expected Behavior

grouping logs by ...
`newer than parent.Timestamp, and older than parent.Timestamp + parent.HTTPRequest.Latency`

## Actual Behavior

`older than parent.Timestamp, and newer than parent.Timestamp - parent.HTTPRequest.Latency, assuming the parent timestamp marks the end of the request.`
https://github.com/googleapis/google-cloud-go/blob/1532374853c261adec6accdb86a491c45ae416d2/logging/doc.go#L124-L126

but real environment is `parent.timestamp == parent.protoPayload.startTime`.
I think this document's `timestamp` means `parent.protoPayload.endTime`.

![log](https://user-images.githubusercontent.com/125332/65665127-c4428500-e075-11e9-8c52-157b7593cf5f.png)

is the document incorrect? or Is AppEngine special?
No documents other than this were found on how to group logs... 😿

**Comment by jadekler** [comment]
Hi @vvakame. Thanks for filing this issue. Re:

> is the document incorrect?

Could you specify which document you were looking at?

**Comment by vvakame** [comment]
Yes, from `Grouping Logs by Request` section.
I think it's copied from https://github.com/googleapis/google-cloud-go/blob/1532374853c261adec6accdb86a491c45ae416d2/logging/doc.go#L116-L132

**Comment by jadekler** [comment]
Thank you! I hope to investigate this and get an answer this week.

**Comment by codyoss** [comment]
@vvakame I will update the docs to try and clarify the behavior. Thanks for the report.

**Comment by codyoss** [comment]
Fixed by a8038f9
