### ISSUE TITLE
spanner: Session pool should hand out sessions in LIFO order

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-go#1604]
**Is your feature request related to a problem? Please describe.**
Currently sessions are handed out from the session pool in FIFO order. Least recently used sessions are unlikely to be in backend caches, and the transactions associated with them are likely to aborted due to idleness.

**Describe the solution you'd like**
The session pool should hand out sessions in LIFO order.

**Comment by AlisskaPie** [comment]
@skuruppu, in Go we have two methods ([take](https://github.com/googleapis/google-cloud-go/blob/b2463266735921687c8e4de0948af9e1bead6e83/spanner/session.go#L653), [takeWriteSession](https://github.com/googleapis/google-cloud-go/blob/b2463266735921687c8e4de0948af9e1bead6e83/spanner/session.go#L724)) to take sessions from the pool, and [recycle method](https://github.com/googleapis/google-cloud-go/blob/b2463266735921687c8e4de0948af9e1bead6e83/spanner/session.go#L799) which "puts session back to the session pool's idle list". 

My solution was to take sessions right away from the back of the pool in take/takeWriteSession methods. @olavloite proposed instead to continue to take sessions from the front of the pool, but to reverse the order of recycle. We decided to ask your expert opinion before proceeding, so what do you think about it?

**Comment by skuruppu** [comment]
Thanks for checking with me @AlisskaPie. Performance-wise, I don't think there will be a difference in taking items for the front or back of the list since the underlying data structure is a linked list.

I have a slight preference for @olavloite's solution only because the session pool now behaves as a stack so you put things on top and you take things out of the top.

I hope that helps.
