### ISSUE TITLE
Compute Engine

### ISSUE THREAD

**Issue by DazWilkin** [googleapis/google-cloud-go#1605]
jba@ it's remarkable (as in "worth remarking" not as in "look Aliens!") that Compute Engine is not supported by a Golang Cloud Client Library (see e.g. #77, #744).

Is this a result of the velocity of the Compute Engine API? Or resourcing? Compute Engine is a large API but it is also a foundational service in GCP. Are Google's own services (presumably those preferring Golang), e.g. Kubernetes Engine, provisioning GCE resources via the API Client Library?

IIUC Google does not expose gRPC endpoints for Compute Engine ([link](https://github.com/googleapis/googleapis/tree/master/google)) and the [Go **C**DK](https://gocloud.dev/) does not include an abstraction for VM provisioning either.

A consequence -- of course -- is that developers need to fallback to the API Client Library and miss out on -- to quote Google:

"...our latest and recommended client libraries for calling Google Cloud APIs. They provide an optimized developer experience by using each supported language's natural conventions and styles. They also reduce the boilerplate code you have to write because they're designed to enable you to work with service metaphors in mind, rather than implementation details or service API concepts"

**Comment by jadekler** [comment]
Hello! Yes, this is a bummer. We are encouraging and working with several teams towards the adoption of the new proto-based API specification. I'll forward this along to their team, but there's nothing specific we can do about this so I'll close this issue. If you'd like to file a ticket directly against their team and have a direct conversation, please feel free to do so via https://cloud.google.com/support/docs/issue-trackers.

Closing for now, but let me know if you'd like to continue the conversation!
