### ISSUE TITLE
bigtable: Cbt Snapshots functionality doesn't work

### ISSUE THREAD

**Issue by mosabkng** [googleapis/google-cloud-go#1607]
>  cbt createsnapshot bigtable-0 test-snapshot test_bigtable ttl=1h

gives the following error:

> Failed to create Snapshot: rpc error: code = Unimplemented desc = Operation is not implemented, or supported, or enabled. 

Google support asked us to create an issue here as this is not expected according to them.

## Client
Cbt

## Describe Your Environment

Mac High Sierra

## Expected Behavior

Snapshot created

## Actual Behavior

Error message saying method not implemented.

**Comment by igorbernstein2** [comment]
Hi @mosabkng,

I apologize for the run around, this isn't a client issue. The message is coming from the serverside. The snapshots feature is currently in early access and is not available to the general public. Unless your project has been whitelisted for the snapshots EAP program, it will not be available. If you did sign up for the EAP program, please re-open the support ticket and ask it to be routed to me.

Best,
Igor
