### ISSUE TITLE
civil: support formatting of standard time package

### ISSUE THREAD

**Issue by ear7h** [googleapis/google-cloud-go#1609]
Currently the civil time/date parsing is done with `RFC3339`. My request is to provide a function which the user can specify a layout of the string like [time.Parse](https://golang.org/pkg/time/#Parse) from the Go standard library. The new functions could be called `ParseLayout*` and have the signature `func(layout, value string) (T, error)`

**Comment by codyoss** [comment]
Along the same lines as #1755. We will not be moving forward with this feature at this time.
