### ISSUE TITLE
containeranalysis: Filter examples

### ISSUE THREAD

**Issue by skeet70** [googleapis/google-cloud-go#1614]
##  Client

Container Analysis

## Expected Behavior

The Filter option on most of the request protos has some examples or other documentation of what the structure should be.

## Actual Behavior

From the [doc site](https://cloud.google.com/container-registry/docs/reference/rest/v1beta1/projects.occurrences/list):
```
filter | string                                        The filter expression.
```

From the [client docs](https://godoc.org/google.golang.org/genproto/googleapis/devtools/containeranalysis/v1beta1/grafeas#ListOccurrencesRequest):
```go
type ListOccurrencesRequest struct {
    // The name of the project to list occurrences for in the form of
    // `projects/[PROJECT_ID]`.
    Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
    // The filter expression.
    Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
    // Number of occurrences to return in the list.
    PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
    // Token to provide to skip to a particular spot in the list.
    PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}
```

The tests also all appear to be stubs, and I can't find other examples anywhere really. I have some basics like `Filter: fmt.Sprintf("kind=\"VULNERABILITY\"")` working but I'm not sure what nested property access looks like, what is used to combine filters, or what operators are available.

**Comment by skeet70** [comment]
It seems like https://cloud.google.com/logging/docs/view/advanced-queries / https://github.com/grafeas/grafeas/tree/master/go/filtering is supposed to be how the filtering works, but it doesn't line up with what I'm seeing in practice.

**Comment by codyoss** [comment]
Filtering for our list apis is defined [here](https://google.aip.dev/160). If you are getting an invalid argument the error should contain some details to help point you in the right direction.
