### ISSUE TITLE
Include an example in docs for APIs with an emulator

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#1617]
The documentation for APIs that have emulators should include an example of how to manually configure a client to connect to the emulator. This is useful for APIs that have a GAPIC and an emulator e.g. the Spanner Database/Instance Admin clients.

This was originally brought up in #1602, moved to https://github.com/googleapis/gapic-generator-go/issues/230 for exploration as a micro-generator feature, and ultimately ends up back here as a documentation change.

**Comment by codyoss** [comment]
I think we should split out this issue into individual doc task for each manual that has emulator to put the visibility better on each client.

**Comment by codyoss** [comment]
Closing this issue as now each product has its own issue.
