### ISSUE TITLE
logging.Entry needs custom unmarshaller for string based severity

### ISSUE THREAD

**Issue by ptone** [googleapis/google-cloud-go#1622]
## Client

logging

## Describe Your Environment

Audit log -> pubsub sink -> push sub -> Cloud Run

## Expected Behavior

I can use Google client lib types to parse payloads

## Actual Behavior

2019/10/17 01:16:29 data json.NewDecoder: json: cannot unmarshal string into Go struct field Entry.Severity of type logging.Severity

A snippet that shows the context of the problem:

```
	var m PubSubMessage
	var e *logging.Entry

	if err := json.NewDecoder(r.Body).Decode(&m); err != nil {
		log.Printf("message json.NewDecoder: %v", err)
		return
	}

	if err := json.Unmarshal(m.Message.Data, &e); err != nil {
		log.Printf("data json.NewDecoder: %v", err)
		return
	}


	var aLog *audit.AuditLog

	json.Unmarshal(e.Payload.([]byte), &aLog)
```

While https://github.com/googleapis/google-cloud-go/issues/345 added a convenience function, this is not afforded in any way that lets you unmarshal from pubsub sinks (I didn't even get to the payload part of the above snippet.

I don't expect this to be a high priority - but an included custom unmarshaller I guess would be the fix?

**Comment by codyoss** [comment]
It looks to me like you might have the wrong struct you are trying to Unmarshal to. According to [this doc](https://cloud.google.com/logging/docs/audit/) it looks like the type you are looking for is actually `LogEntry`, which is the proto type. If you try to use that type instead does it solve the issue you are having?

**Comment by ptone** [comment]
I have not tried directly the proto struct, but I'm pretty sure I'll hit the same stringified enum problem

logging.Entry is the Cloud Go's more idiomatic representation of LogEntry:
https://godoc.org/cloud.google.com/go/logging#Entry

We shouldn't force people to drop to raw proto structs.

This is all about the fact that when the audit log json-renders the severity enum, it is converting it to a string, and the Unmarshal doesn't know anything about this stringified severity enum, and is expecting an typed int
