### ISSUE TITLE
storage: suspected memory leak while iterating over `bucket.Objects`

### ISSUE THREAD

**Issue by eliben** [googleapis/google-cloud-go#1623]
## Client

Storage

## Describe Your Environment

Regular desktop / server

## Expected Behavior

Using the standard recommended way to iterate over objects in a bucket:

```
	bucket := client.Bucket(bucketName)
	var names []string

	it := bucket.Objects(ctx, nil)
	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		names = append(names, attrs.Name)
	}
```

I expect the memory to grow due to the `names` slice being populated, but it should be to the tune of tens of bytes per bucket item.

When run on a very large bucket (~3 mln objects), I expect the memory usage to be a few tens of MBs tops.

## Actual Behavior

In reality, it seems the code above retains several KiB per iteration. Memory usage (`MemStats.Alloc`) grows to multiple GiBs for my benchmark of 3 mln objects. This causes the program to run out of memory on small VMs, and also a general slowdown of 20-40%.

**Comment by eliben** [comment]
The iterator is supposed to fill up the `ObjectIterator.items` slice and flush it once all the elements were returned to caller. However, this doesn't appear to be happening.

I instrumented `ObjectIterator.fetch`, and in it the length of `it.items` grows monotonously without ever resetting.

I also instrumented the closure passed to `iterator.NewPageInfo` as `takeBuf` - this closure resets `it.items`, but *it never gets called*.

**Comment by jadekler** [comment]
For posterity:

- fetch appears to append forever [1]
- Next appears to index instead of pop [2]
- Next appears to clear the buf when it gets an error: [3] -> [4] -> [5] -> [6] -> [7]

So, yep, looks like you're right. That seems like something we definitely should fix.

1: https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1127
2: https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1089-L1098
3: https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1090
4: https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1047
5: https://github.com/googleapis/google-api-go-client/blob/master/iterator/iterator.go#L110-L137
6: https://github.com/googleapis/google-api-go-client/blob/master/iterator/iterator.go#L122
7: https://github.com/googleapis/google-api-go-client/blob/master/iterator/iterator.go#L145

**Comment by eliben** [comment]
@jadekler thanks. I think the root problem here is that iterator's `next` expects this:

> 
> // next provides support for an iterator's Next function. An iterator's Next
> // should return the error returned by next if non-nil; else it can assume
> // there is at least one item in its buffer, and it **should return that item and
> // remove it from the buffer**.

However, `ObjectIterator.Next` does not remove anything from the buffer, as @jadekler mentions in the second bullet.

This seems to have been introduced in https://code-review.googlesource.com/c/gocloud/+/45313
@odeke-em

**Comment by odeke-em** [comment]
Thank you for the bissection @eliben and @jadekler!

>I also instrumented the closure passed to iterator.NewPageInfo as takeBuf - this closure resets it.items, but it never gets called.

That's odd that that closure that performs the reset never gets called, what commit are you on?

**Comment by codyoss** [comment]
I think if you sliced the slice by the index before it is reset here it would fix the problem: https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1051

**Comment by odeke-em** [comment]
>I think if you sliced the slice by the index before it is reset here it would fix the problem:

@codyoss I believe @eliben mentioned that he tried instrumenting it as takeBuf but it was never invoked.

I think this bug might have existed for a while but the indexing instead of reslicing makes its resetting take longer, i.e. until nextFunc()'s condition has run out of buffer i.e. len(..) == 0.

I am more inclined to revert my patch as the interaction with the iterator seems more complex than it appeared to be, and I'd vote for returning to a working state than leaking memory due to a subtle interaction.

**Comment by odeke-em** [comment]
I'll send a revert shortly, please help test it out @eliben after it has landed.

**Comment by eliben** [comment]
I'm closing this issue as the memory leak was eliminated with @odeke-em 's revert.

FWIW I don't see a great reason to do this micro-optimization - it's not clear what goal it is serving, given that the network requests far outweigh any microsecond-level cost of reslicing. If reslicing on each `Next` is deemed expensive (by realistic benchmarks demonstrating that), we can apply a softer optimization of only reslicing once some number of items was returned, to amortize it across multiple calls.

**Comment by odeke-em** [comment]
Thanks for the report and follow-up @eliben!

>FWIW I don't see a great reason to do this micro-optimization - it's not clear what goal it is serving, given that the network requests far outweigh any microsecond-level cost of reslicing. If reslicing on each Next is deemed expensive (by realistic benchmarks demonstrating that), we can apply a softer optimization of only reslicing once some number of items was returned, to amortize it across multiple calls.

For the record, I came to the same conclusion in July 2019 https://github.com/googleapis/google-cloud-go/issues/1506#issuecomment-511100019 but I also considered the case when there were many elements that had already been paged from the network and now doing iterations, that the performance was very slow just for iterations which prompted me to reopen the issue and send that CL. Iterate with 3 million items and you'll see the speed problem that I am talking about :)

**Comment by eliben** [comment]
> Thanks for the report and follow-up @eliben!
> 
> > FWIW I don't see a great reason to do this micro-optimization - it's not clear what goal it is serving, given that the network requests far outweigh any microsecond-level cost of reslicing. If reslicing on each Next is deemed expensive (by realistic benchmarks demonstrating that), we can apply a softer optimization of only reslicing once some number of items was returned, to amortize it across multiple calls.
> 
> For the record, I came to the same conclusion in July 2019 [#1506 (comment)](https://github.com/googleapis/google-cloud-go/issues/1506#issuecomment-511100019) but I also considered the case when there were many elements that had already been paged from the network and now doing iterations, that the performance was very slow just for iterations which prompted me to reopen the issue and send that CL. Iterate with 3 million items and you'll see the speed problem that I am talking about :)

Do you see a scenario where this could happen with `Next`? I think it only fetches new items (in batches) after the old ones have been consumed, so there shouldn't be a scenario where we pulled all objects from the network and only then started iterating.
