### ISSUE TITLE
bigtable: add deleteAllDataFromTable flag to the DropRowRange function

### ISSUE THREAD

**Issue by aghdom** [googleapis/google-cloud-go#1630]
Pretty much what the title says. 
This field (`deleteAllDataFromTable`) is already being supported by the `bigtableadmin` API (as described by the [docs](https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances.tables/dropRowRange)), and it is also already defined in the `bigtable_table_admin_proto`, but it is not supported by the `AdminClient.DropRowRange` function.

It would be really nice to have this functionality, since currently the only way to use this feature is directly calling the API.

**Comment by IlyaFaer** [comment]
Take a look at this code, I think, the flag already implemented, but in another method:
https://github.com/googleapis/google-cloud-go/blob/a7c42305cc232dc762db97d7aceffe1c60382724/bigtable/admin.go#L291-L301

**Comment by aghdom** [comment]
Yeah, you are right. We had an older version in our code, so I wasn't able to find it locally... Sorry, my bad. I will close the issue. Thanks
