### ISSUE TITLE
pubsub: unflake TestIntegration_CreateSubscription_NeverExpire

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1637]
https://sponge.corp.google.com/target?id=73bd15a1-2861-47cc-b4d2-e3c62b5f7b51&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=ALL&sortBy=STATUS

```
=== CONT  TestIntegration_UpdateSubscription
--- FAIL: TestIntegration_CreateSubscription_NeverExpire (5.76s)
    integration_test.go:502: 
        got: - want: +
          pubsub.SubscriptionConfig{
        - 	Topic:       s"_deleted-topic_",
        + 	Topic:       s"projects/dulcet-port-762/topics/topic-20191023-75896644136924-0004",
          	PushConfig:  pubsub.PushConfig{},
          	AckDeadline: s"10s",
          	... // 4 identical fields
          }
```

**Comment by jadekler** [comment]
Again today https://sponge.corp.google.com/target?id=59a1fd72-5386-4109-b2f9-bbf728a13123&target=cloud-devrel/client-libraries/go/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

**Comment by hongalex** [comment]
Fixed as of [CL 50590](https://code-review.googlesource.com/c/gocloud/+/50590).
