### ISSUE TITLE
Object existence unknown

### ISSUE THREAD

**Issue by joshuaseaton** [googleapis/google-cloud-go#1638]
I have logic that checks the existence of an object:
```
obj := s.bucket.Object(name)
attrs, err := obj.Attrs(ctx)
if err == storage.ErrObjectNotExist {
	return false, nil
} else if err != nil {
	return false, fmt.Errorf("object %q: possibly exists remotely, but is in an unknown state: %v", name, err)
}
...
```

I recently saw that second 'unknown state' branch get hit - in trying to read a public bucket - with
```
...possibly exists remotely, but is in an unknown state: Get https://www.googleapis.com/storage/v1/b/fuchsia-artifacts/o/blobs%2F3790cd271285a8b59d804aeed16bc6027167028a03470b8c4f8702458108d3e2?alt=json&prettyPrint=false&projection=full: dial tcp 108.177.111.95:443: connect: connection refused
```

* What happened here? Is this an unavoidable, transient issue?
* Is there anything that can be done to mitigate this on the client side (either by me or upstream in the library)?

Thanks!

## Client

Storage

## Describe Your Environment

GCE instance
*cores*: 16
*cpu*: x64 | x86 | x86-64-Haswell_GCE | x86-64-avx2
*gpu*: none
*kvm*: true
*machine_type*: n1-standard-16
*os*: Debian | Debian-9.5 | Linux
*ssd*: true

**Comment by joshuaseaton** [comment]
@frankyn, @jadekler if you could also take a look at this one, that would be very appreciated!

**Comment by tritone** [comment]
I did some research looking into this and I think that we should retry on connection refused errors. I have a PR up here if you'd like to take a look: https://code-review.googlesource.com/c/gocloud/+/48990 . @joshuaseaton I can add you if create an account on this gerrit instance.
