### ISSUE TITLE
Please sort out the tangled go.mod imports for these API libraries

### ISSUE THREAD

**Issue by andreib1** [googleapis/google-cloud-go#1640]
Importing cloud.google.com/go/bigquery v1.1.0 imports...
**cloud.google.com/go v0.46.3** imports...
cloud.google.com/go/bigquery v1.0.1 imports...
**cloud.google.com/go v0.44.2** imports...
cloud.google.com/go/datastore v1.0.0 imports...
**cloud.google.com/go v0.44.1** imports...
go.opencensus.io v0.22.0 imports...
google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb imports...
google.golang.org/grpc v1.19.0 imports...
**cloud.google.com/go v0.26.0** imports...

another dependency imports...
**cloud.google.com/go v0.38.0**

I am not sure how the dependencies are being maintained.  Each time a bugfix is made to a library and a new version is released, there is no guarantee that the underlying infrastructure will be using those fixed versions.

Please bring all versions up to a level playing field.  Could I suggest moving the go.mod up to the top and create a monorepo, or at maybe use a dependency scanner to view the import tree.

It is causing a real headache to try and work out which libraries are using old versions.

**Comment by jadekler** [comment]
Are you actually seeing problems? All the above you've mentioned is WAI.

**Comment by jadekler** [comment]
> The issue is, that to version control my libraries, I must first work out the versions of the dependencies, and to do that, I need to work out why for instance, BigQuery imports a library that imports an older version of BigQuery, and how it is being used.

I disagree with this assertion. If you need the latest version of pubsub, you can simply perform `go get -u cloud.google.com/go/pubsub`. Ditto for any other module, or the root module `cloud.google.com/go`.

> But without me going through each and every import to see if and how they are using the old libraries it is really difficult to tell.

(using pubsub as an example) Performing `go get -u cloud.google.com/go/pubsub` (requiring the latest pubsub version in your go.mod) will force all your transitive dependencies to use that version of pubsub, regardless of what their go.mod files state. See https://research.swtch.com/vgo-mvs.

--------

Closing this issue as it appears to be a no-op for us.

**Comment by andreib1** [comment]
I get that.  I guess my dependency issue is the following:
Things like the DataStore API are not updated upon newer versions of the underlying libraries, therefore they may not get bug fixes for the library unless I coincidentally import something with a newer version of dependencies, or explicitly set versions for all of it's dependencies in my go mod.

I agree that the fact that there are circular references between modules isn't my problem, however it makes solving the above issue harder, and probably should be looked at from a design perspective, as suggests a convoluted separation between modules.

**Comment by jadekler** [comment]
> Things like the DataStore API are not updated upon newer versions of the underlying libraries, therefore they may not get bug fixes for the library unless I coincidentally import something with a newer version of dependencies, or explicitly set versions for all of it's dependencies in my go mod.

If you'd like a release of any of our libraries, please feel free to open an issue and we'll be happy to accomodate. :)

> I agree that the fact that there are circular references between modules isn't my problem, however it makes solving the above issue harder

This should not affect users at all. If you need a newer release, just open an issue for us. It wouldn't be any different if we had a simpler module graph.
