### ISSUE TITLE
NewPager nil pointer dereference when passing an empty Pageable

### ISSUE THREAD

**Issue by jordancoll** [googleapis/google-cloud-go#1642]
`pageInfo` is `nil` on empty pageables (or is at least in the case of `bigquery.RowIterator`), which results in a nil pointer dereference.

could either:
1. handle nil `pageInfo`s in `NewPager`, and create an empty `Pager`
1. fix `bigquery.RowIterator` to always have a `pageInfo`, even when empty
1. add documentation to check if the iterator is empty before creating a `Pager`

**Comment by shollyman** [comment]
Started poking at this.

**Comment by shollyman** [comment]
https://code-review.googlesource.com/c/gocloud/+/47910 in progress for this.
