### ISSUE TITLE
No validation on HTTP method for SignedUrl

### ISSUE THREAD

**Issue by h4xnoodle** [googleapis/google-cloud-go#1644]
## Client
Storage

## Describe Your Environment
mac/any

## Expected Behavior
A validation error occurs when a lowercased HTTP Method is given for SignedUrl

## Actual Behavior
Eventually we would receive a SignatureDoesNotMatch when using a lowercased HTTP Method.

Method is shown as uppercased in the comments https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L194

validation for absence of method
https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L371

builds a v4 url with whatever method was passed
https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L417

I understand the expectation for clients to use uppercased methods, as per https://tools.ietf.org/html/rfc7231 but the error is misleading when this is not the case. I would expect the SDK to give a validation error here. We have instead needed to implement validation ourselves.

**Comment by tritone** [comment]
Thanks very much for the thorough report! I think I agree that it would make sense to add some validation for this in the client. Will update when I'm able to dive in further.

**Comment by tritone** [comment]
Just merged a PR to fix this; it will be included in the next release of the storage module.

**Comment by h4xnoodle** [comment]
@tritone thanks!
