### ISSUE TITLE
pubsub: PullCount not updated when using Synchronous = true

### ISSUE THREAD

**Issue by fastest963** [googleapis/google-cloud-go#1645]
## Client

PubSub (bd64c13)

## Describe Your Environment

CentOS on GCE

## Expected Behavior

I expected the PullCount to be incremented when using Synchronous =true

## Actual Behavior

PullCount is never changed when using Synchronous =true

**Comment by hongalex** [comment]
Thanks for reporting! I checked and indeed `PullCount` is only updated with messages pulled using `StreamingPull`. Refactoring OpenCensus metrics for subscriptions is something that's on my backlog, but just haven't had time to look into. I'll try to give an update by next week with a better timeline.

**Comment by hongalex** [comment]
https://code-review.googlesource.com/c/gocloud/+/48210 should fix this issue in the meantime
