### ISSUE TITLE
Private end point override doesn't work if no port number specified

### ISSUE THREAD

**Issue by guolin4321** [googleapis/google-cloud-go#1646]
(delete this for feature requests)

## Client

PubSub as an example

## Describe Your Environment

GCE VM instance

## Expected Behavior

Private end point override should work even if no port number specified for client to make grpc call. The doc doesn't mention it should have "hostname:port"

## Actual Behavior

Private end point override doesn't work if no port number specified. Grpc failed to connect with warning:

WARNING: 2019/11/04 23:17:26 grpc: addrConn.createTransport failed to connect to {pubsub-lin.p.googleapis.com 0  0}. Err :connection error: desc = "transport: Error while dialing dial tcp: address pubsub-lin.p.googleapis.com: missing port in address". Reconnecting...

**Comment by jadekler** [comment]
WAI as far as I can tell. Please pass a port.

Closing for now, but let me know if you'd like to continue discussing.
