### ISSUE TITLE
logging: fix TestLogsAndDelete

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1654]
Too many runs causes us to run out of quota. We've tried and failed to dramatically increase quota (logging team gives a ridiculously low quota of, like, 20 per hour to Delete, and won't budge on it).

We should probably use a project pool.

https://sponge.corp.google.com/target?id=35806e80-802d-4ab2-8c8a-006e70d5b9aa&target=cloud-go-libraries/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

```
=== RUN   TestLogsAndDelete
--- FAIL: TestLogsAndDelete (0.08s)
    logging_test.go:497: deleting "GO-LOGGING-CLIENT/TEST-LOG-20191021-67194905680597-0001": rpc error: code = ResourceExhausted desc = Quota exceeded for quota metric 'logging.googleapis.com/control_requests' and limit 'ControlRequestsPerMinutePerProject' of service 'logging.googleapis.com' for consumer 'project_number:36639933145'.
```

**Comment by nicoleczhu** [comment]
Taking a look at this now
