### ISSUE TITLE
spanner: Unactionable "Failed to prepare session" errors in logs

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-go#1657]
## Client

Cloud Spanner

## Describe Your Environment

N/A

## Expected Behavior

Sessions are prepared for writes without errors.

## Actual Behavior

Periodically, errors of the following form are reported in logs. But there seems to be no affect on performance and the errors are unactionable so maybe we should consider not printing them.

```
Failed to prepare session, error: spanner: code = "DeadlineExceeded", desc = "context deadline exceeded"
```

They seem to be getting logged from [here](https://github.com/googleapis/google-cloud-go/blob/90c61cb6b2d275ce6037ff82aa8cef13996bd861/spanner/session.go#L1178) and [here](https://github.com/googleapis/google-cloud-go/blob/90c61cb6b2d275ce6037ff82aa8cef13996bd861/spanner/session.go#L1306).

**Comment by skuruppu** [comment]
@nevinheintze @hengfengli @larkee

**Comment by hengfengli** [comment]
The fix is in https://code-review.googlesource.com/c/gocloud/+/49830.
