### ISSUE TITLE
Error getting BigQuery dataset metadata when dataset is shared with `allUsers`

### ISSUE THREAD

**Issue by kieras** [googleapis/google-cloud-go#1658]
## Client

PubSub v1.2.0

## Describe Your Environment

Cloud Function, Go 1.11.
It also happened in a command line program to test/debug.

Using the console:

1. Create a new Project, and a new Dataset.
2. Select the dataset, click on `Share Dataset` button.
3. In the `Dataset permissions` sidebar fill `Add members` with the value **`allUsers`** and select any role. Click `Add`.
4. Click  `Done`.

## Expected Behavior

When calling `client.Dataset(datasetID).Metadata(ctx)`, it should return the dataset metadata with all access entries for the dataset.

## Actual Behavior

The return of this call is an error: `bigquery: invalid access value`
Metadata is `nil`.

(if you remove `allUsers` from the dataset permissions, it works fine.)

It looks like there's a missing case in this method (something like `case q.IamMember != "":`): https://github.com/googleapis/google-cloud-go/blob/50b37a95bf7b4a358661c89fad8219ef943e66d5/bigquery/dataset.go#L699

**Comment by kieras** [comment]
Debug session:

![image](https://user-images.githubusercontent.com/1938355/68502809-18798100-0240-11ea-9b1e-feecb2c1438f.png)

**Comment by kieras** [comment]
Test program: 

```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/bigquery"
)

func main() {
	ctx := context.Background()
	projectID := "sec-automation-dev"
	datasetID := "test_dataset2"
	client, err := bigquery.NewClient(ctx, projectID)
	if err != nil {
		fmt.Println(fmt.Errorf("error in client initialization: %w", err))
	}
	md, err := client.Dataset(datasetID).Metadata(ctx)
	if err != nil {
		fmt.Println(fmt.Errorf("error getting metadata: %w", err))
	}
	fmt.Printf("metadata: %v", md)
}
```

**Comment by shollyman** [comment]
Looks like there's been some changes to how the persisted policy is communicated from the backend, and allUsers is coming through IAMMember rather than via specialGroup.  I'll work on updating.

**Comment by shollyman** [comment]
```
 "access": [
    {
      "role": "WRITER", 
      "specialGroup": "projectWriters"
    }, 
    {
      "role": "OWNER", 
      "specialGroup": "projectOwners"
    }, 
    {
      "role": "OWNER", 
      "userByEmail": "user@domain.com"
    }, 
    {
      "iamMember": "allUsers", 
      "role": "READER"
    }, 
    {
      "role": "READER", 
      "specialGroup": "projectReaders"
    }
  ], 

```

**Comment by shollyman** [comment]
https://code-review.googlesource.com/c/gocloud/+/48291 in review to address this.
