### ISSUE TITLE
Error: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration

### ISSUE THREAD

**Issue by abdulrehmank** [googleapis/google-cloud-go#1660]
## Client
Firebase Auth

## Actual Behavior
root/vendor/cloud.google.com/go/storage
vendor/cloud.google.com/go/storage/bucket.go:558:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:727:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:735:4: unknown field 'UniformBucketLevelAccess' in struct literal of type storage.BucketIamConfiguration
vendor/cloud.google.com/go/storage/bucket.go:1077:18: b.UniformBucketLevelAccess undefined (type *storage.BucketIamConfiguration has no field or method UniformBucketLevelAccess)
vendor/cloud.google.com/go/storage/bucket.go:1080:39: b.UniformBucketLevelAccess undefined (type *storage.BucketIamConfiguration has no field or method UniformBucketLevelAccess)

This error occurs only after the latest update in 0.48.0 from 0.47.0.

**Comment by tritone** [comment]
Hi @abdulrehmank ; I suspect one or more of your dependencies is out of date. Could you try updating to the latest version of all of the following?
* cloud.google.com/go
* cloud.google.com/go/storage
* google.golang.org/genproto
* google.golang.org/api

Let me know if you continue to experience the issue after this.

**Comment by tritone** [comment]
Since I haven't heard back, I'm going to close this for now. Feel free to re-open if the issue comes up again.
