### ISSUE TITLE
Spanner: concurrent independent transaction from within read-write transaction

### ISSUE THREAD

**Issue by mikesun** [googleapis/google-cloud-go#1661]
We have a scenario where within a read-write transaction, we'd like to make a separate, independent transaction. We run into the issue where Spanner disallows this since it detects it as a potential nested transaction: https://github.com/googleapis/google-cloud-go/commit/4c9d8c5d3fd0430bd16a69abfa3c5b11c6f2ce18

Right now, we're working around it by creating a separate context for use in the "inner" independent transaction. Is there a better way?

**Comment by olavloite** [comment]
No, that is the only way to do it. This 'protection' was added to minimize any possible confusion on the semantics of inner/nested transactions. As you write, the transactions are completely independent of each other. Committing or rolling back one of them, will not have any effect on the other. This ensures that anyone who might do this by accident is notified that it might not work as he/she is expecting.

Are you running into any practical problems with this work-around? Or is your question purely for verification that there really is no alternative solution?

**Comment by mikesun** [comment]
Thanks for the quick response. We haven't run any issues with this workaround, just wanted to see if there was another way that was cleaner.
