### ISSUE TITLE
datastore: query iteration steps cannot use independent context timeouts

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1663]
Originally filed by @daboyuka at https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/245.

-----------------

When iterating over datastore query results, a context with deadline may be used to limit the time allowed for the entire query. However, individual calls to Iterator.Next cannot currently be configured with independent, shorter deadlines, since they all share a single context deadline.

Practically, this means that a large query must either A) use a long deadline, leading to slow reaction time of calling code in response to contention, etc., or B) use a short deadline, leading to many spurious restarts of the query.

Instead, allowing independent contexts, or perhaps better, independent sub-deadlines/timeouts for each call to `Iterator.Next` / `.nextBatch`, would improve visibility of datastore contention to calling code.

Snippets from current code in cloud.google.com/go/datastore:

```go
func (c *Client) Run(ctx context.Context, q *Query) *Iterator {
	...
	t := &Iterator{
		ctx: ctx, ...
	}
	...
}
```

```go
func (t *Iterator) nextBatch() error {
	...
	resp, err := t.client.client.RunQuery(t.ctx, t.req)
	...
}
```

Expected behavior: the ability to either pass a `context.Context` to `datastore.Iterator.Next`, or perhaps to pass a per-step timeout during construction of the query or iterator, such that internally the context passed to the inner client would be wrapped in (another) layer of `context.WithTimeout` using that smaller timeout.

Note: this is a regression in practice vs. the legacy AppEngine Datastore library, which appears to use a short (5-second?) timeout on each underlying AppEngine API call during iterator Next.

**Comment by tbpg** [comment]
Looking at the implementations:
* https://github.com/googleapis/google-cloud-go/blob/datastore/v1.0.0/datastore/query.go#L631
* https://github.com/golang/appengine/blob/v1.6.5/datastore/query.go#L629

I don't see an immediate difference in the context/deadline logic there.

Following the stack down a bit, the `appengine` client has a default RPC timeout of 60 seconds: https://github.com/golang/appengine/blob/v1.6.5/internal/api.go#L477. That's much longer than 5 seconds, though, so I'm not sure where that comes from.

**Comment by tbpg** [comment]
I don't see the same default timeout in the `cloud.google.com/go/datastore` client: https://github.com/googleapis/google-cloud-go/blob/datastore/v1.0.0/datastore/client.go#L60

**Comment by daboyuka** [comment]
> Looking at the implementations:
> 
> * https://github.com/googleapis/google-cloud-go/blob/datastore/v1.0.0/datastore/query.go#L631
> * https://github.com/golang/appengine/blob/v1.6.5/datastore/query.go#L629
> 
> I don't see an immediate difference in the context/deadline logic there.

You are correct, the deadline is not applied there in either library.

> Following the stack down a bit, the `appengine` client has a default RPC timeout of 60 seconds: https://github.com/golang/appengine/blob/v1.6.5/internal/api.go#L477. That's much longer than 5 seconds, though, so I'm not sure where that comes from.

> I don't see the same default timeout in the `cloud.google.com/go/datastore` client: https://github.com/googleapis/google-cloud-go/blob/datastore/v1.0.0/datastore/client.go#L60

You are correct here as well, including on the 60 seconds. Apologies on the 5 second thing, that was second-hand knowledge for me, and I went back and realized the 5 seconds is from AppEngine *Gen1*.

Regardless, the point is that AppEngine Datastore query iteration has a _de facto_ per-Next timeout (of 60s, due to underlying RPC timeout), whereas under Cloud Datastore there is no option to have a per-Next timeout. 

Our need for more granular timeouts is reasonable, isn't it? We'd like to be able to run an arbitrarily-long-running query without worrying about choosing an overall deadline, so long as the iterator continues to make progress (i.e., no single Next call takes too long). We do generally use "checkpoints" (capture query cursor and restart) to avoid losing the entire iteration if an error occurs, but even under this scheme it's not ideal to have to come up with an overall deadline.

**Comment by tbpg** [comment]
I'm seeing a couple angles for this:

1. Queries are taking a long time for some reason. Can we prevent that and sidestep this issue completely?
1. Currently, we can't set a per-iteration deadline.

Let's investigate the first one a bit more to get a clear picture of what the problem is. If we can't find a solution there, we'll figure out something here. How does that sound?

**Comment by tbpg** [comment]
Removing the priority label for now (usually only used for bugs). Can reevaluate once we find out more.

**Comment by mkj-pendo** [comment]
Certainly we investigate when we have pattern of queries that take too long. But per-iteration deadlines would reduce the "blast radius" of noise. So 1 is something we look at operationally, and 2 is defense in depth in code that makes checkpoint/restart more effective. I'd like us to pursue 2 here.

**Comment by tbpg** [comment]
(Closed by accident.)

**Comment by meredithslota** [comment]
Closing as a "Won't Fix" — we've addressed query latency in a number of other ways since this issue was filed, and we haven't seen repeat requests for this feature.
