### ISSUE TITLE
spanner: BatchCreateSessions causing grief

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1665]
Copied from https://code-review.googlesource.com/c/gocloud/+/45111

> This change caused us a bit of grief. We have some uses of this library in a context where the program doesn't have IAM permission to write, only read, so we got a lot of log spam of this sort:
> 
> Failed to prepare session, error: spanner: code = "PermissionDenied", desc = "Caller is missing IAM permission spanner.databases.beginOrRollbackReadWriteTransaction on resource <our DB>
> 
> In addition to the log spam, it outright caused failures even in read operations trying to use the spanner client.
> 
> We can work around this ourselves by providing a custom SessionPoolConfig, but I wonder if this situation should be handled more gracefully by the client library (e.g. detecting the permission problem, and not trying to create write sessions at all).
> 
> Also, it feels like this could have been called out in the release notes a bit more clearly.

@olavloite Can we:

- Update the release notes retroactively?
- Improve this experience at all?

cc @dsymonds @hengfengli @skuruppu

**Comment by olavloite** [comment]
Handling this case more gracefully (i.e. improve the experience) is handled by #1662.
But I agree that we should also update the release notes retroactively.

**Comment by olavloite** [comment]
Release notes have been appended and the error is now handled gracefully by the client library.
