### ISSUE TITLE
pubsub: unflake TestIntegration_CancelReceive

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1666]
https://sponge.corp.google.com/target?id=443b723b-8392-4b48-b7ad-603fa339c4e7&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=ALL&sortBy=STATUS

```
--- FAIL: TestIntegration_CancelReceive (62.20s)
    integration_test.go:463: Waited 60 seconds for Receive to finish, should have finished sooner
FAIL
FAIL	cloud.google.com/go/pubsub	74.840s
```

**Comment by hongalex** [comment]
Fixed as of [CL 50590](https://code-review.googlesource.com/c/gocloud/+/50590).
