### ISSUE TITLE
[Feature Request] Cloud Run

### ISSUE THREAD

**Issue by hden** [googleapis/google-cloud-go#1668]
It would be very useful if we could interact with managed cloud run via API.

Use cases:

* Deploy services / revisions
* Delete services
* Adjust environment variables

**Comment by jadekler** [comment]
I'm not aware of a cloudrun public API (I checked for protos in https://github.com/googleapis/googleapis/tree/master/google/cloud). Unless you're aware of one, would you mind filing an issue against the cloud run team? They have a public issue tracker at https://cloud.google.com/support/docs/issue-trackers.

Closing for now, but happy to continue the discussion.

**Comment by hden** [comment]
It seems that Cloud Run only support a RESTful API (1), but you can use the discovery document (2) to generate an API client.

1. https://cloud.google.com/run/docs/reference/rest/#rest-resource-v1namespacesservices
2. 
https://run.googleapis.com/$discovery/rest?version=v1

**Comment by jadekler** [comment]
Looks like that API exists at https://github.com/googleapis/google-api-go-client/tree/master/run/v1.

**Comment by tj** [comment]
Why are there two official GCP packages? Some mention of google.golang.org/api in the docs would be helpful, this one seems to be missing quite a bit

**Comment by tbpg** [comment]
Sorry for the confusion. @grayside is looking at this and the right way to fix it.
