### ISSUE TITLE
pubsub: unflake TestIntegration_UpdateTopicLabels

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1669]
https://sponge.corp.google.com/target?id=9d9a1c46-3f37-46dc-8163-914d4edb512b&target=cloud-go-libraries/google-cloud-go/continuous/go112&searchFor=&show=ALL&sortBy=STATUS

```
--- FAIL: TestIntegration_UpdateTopicLabels (2.73s)
    integration_test.go:784: rpc error: code = NotFound desc = Resource not found (resource=projects/dulcet-port-762/topics/topic-20191118-39270558631395-0003).
```

**Comment by hongalex** [comment]
Fixed as of [CL 50590](https://code-review.googlesource.com/c/gocloud/+/50590).
