### ISSUE TITLE
pubsub: how to flush in memory messages before instance shutdown in GAE standard

### ISSUE THREAD

**Issue by rororo12** [googleapis/google-cloud-go#1670]
## Client
PubSub

## Describe Your Environment
GAE Standard Go 1.12

## Expected Behavior
Publish data from GAE without log disappearance.

## Actual Behavior
I found PubSub Go client publish messages using goroutine(google.golang.org/api/support/bundler),
which running asynchronously.
In GAE standard environment, instance shutdown without a signal.
Without calling the `flush` method before shutdown,
messages stored in memory may be disappeared before sent to pubsub endpoint.

I know run like below may send a message synchronously,
but this got terrible performance.
```
result := t.Publish(ctx, &pubsub.Message{Data: msg})
id, err := result.Get(ctx)
```

Is there any other way to make sure messages be sent to pubsub definitely?

**Comment by Deleplace** [comment]
The GAE doc for Go (1.9, 1.11, 1.12, 1.13) does mention [shutdown hooks](https://cloud.google.com/appengine/docs/standard/go/how-instances-are-managed#shutdown).
I guess we could call `flush` there.

Caveat 1: in "rare cases", the shutdown hook is not able to run.
Caveat 2: I've never registered a shutdown hook myself in GAE, so we still need to figure out the exact way to do this.

**Comment by rororo12** [comment]
GAE's [shutdown hooks](https://cloud.google.com/appengine/docs/standard/go/how-instances-are-managed#shutdown) has 2 weaknesses:
1. It is not available when using automatic_scaling.
2. As referred by @Deleplace , there are "rare cases" the shutdown hook is not able to run.

I wonder what is the best practice to use pubsub with GAE, especially when using automatic_scaling.

**Comment by hongalex** [comment]
What is the rate at which you are publishing messages? Unfortunately, I think the best suggestion we have is simply to wait on the publish results, though there are performance issues are you suggested.

Also, out of curiosity, are you currently calling [`defer t.Stop()`](https://godoc.org/cloud.google.com/go/pubsub#Topic.Stop)?

**Comment by rororo12** [comment]
@hongalex 
Our API server is in development, which is expected to have 5000 ~ 7000 requests per sec,
and every request will publish 1 message to pubsub.

We are calling [PublishResult.Get](https://godoc.org/cloud.google.com/go/pubsub#PublishResult.Get) for each request for now.
`defer t.Stop()` is not called this time because there's not a shutdown hook when using automatic_scaling.

**Comment by hongalex** [comment]
Unfortunately, we don't have much guidance on this issue as it is currently a limitation of App Engine and not a client library related issue.
