### ISSUE TITLE
Request: Export the error `errNilDocRef` from `docref.go`

### ISSUE THREAD

**Issue by acco** [googleapis/google-cloud-go#1677]
Referring to `firestore/docref.go`

If I make a `Get()` query like so:

```
snap, err := client.Doc("users/1234/products/4321").Get(ctx)
```

It appears there are situations where `err` is a `errNilDocRef` (line: https://github.com/googleapis/google-cloud-go/blob/master/firestore/docref.go#L33)

[The docs](https://godoc.org/cloud.google.com/go/firestore#DocumentRef.Get) suggest that if the document does not exist, Get will return a NotFound error which should satisfy:

```
status.Code(err) == codes.NotFound
```

But this does not appear to be the case. So instead, I need to compare the `err` returned to `errNilDocRef`. It would naturally be best practice to use `errors.Is()`and compare the `err` returned to that of `ErrNilDocRef` in the package.

Does this sound appropriate? Or am I using the API incorrectly? Let me know.

Thanks!

**Comment by olavloite** [comment]
`client.Doc("users/1234/products/4321").Get(ctx)` method should only return a `errNilDocRef` if you call it with an invalid document reference, such as for example a reference containing an odd (uneven) number of IDs or a reference containing a nil ID.
So you should not have to check for `errNilDocRef` as long as you never call this method with an invalid document reference.

```go
// The following will always return an errNilDocRef
snap, err := client.Doc("users/1234/products/4321/foo").Get(ctx)

// The following should never return an errNilDocRef, regardless whether the
// document exists or not. You can safely check the error for
// status.Code(err) == codes.NotFound.
snap, err = client.Doc("users/1234/products/4321").Get(ctx)
```

Are you actually running into a situation where you are receiving an `errNilDocRef` while passing it a valid document reference, albeit one for an non-existing document? Or are you just looking for confirmation that you can safely remove your error checking for `errNilDocRef`?

**Comment by tritone** [comment]
@acco, does the explanation above make sense to you? I'll close this ticket unless you have further questions. Thanks!
