### ISSUE TITLE
regression with using fake local GCS server

### ISSUE THREAD

**Issue by vikstrous** [googleapis/google-cloud-go#1680]
## Client

Storage

## Describe Your Environment

Local docker container running https://github.com/fsouza/fake-gcs-server, tests trying to connect to it with the GCS client in this repo.

## Expected Behavior

Connects to the local server

## Actual Behavior

Connects to https://storage.googleapis.com/storage/v1/ unconditionally and returns a 404 error

The regression was introduced by https://github.com/googleapis/google-cloud-go/commit/fc09f3a79b851d8012f55167dac291610ebf01a2 in https://github.com/googleapis/google-cloud-go/releases/tag/storage%2Fv1.3.0 (version 1.3.0)

**Comment by tritone** [comment]
Hi @vikstrous , thanks for the report. Can you show me how you are setting the endpoint when you have this issue? I took a look at your repo but it wasn't immediately obvious to me. Thanks!

**Comment by vikstrous** [comment]
Ah, actually, it looks like we had to do some hacks to set the endpoint. Our code looks something like this:

```go
	addr := "127.0.0.1:4443"
	opt := option.WithHTTPClient(&http.Client{
		Transport: &http.Transport{
			DialTLS: func(string, string) (net.Conn, error) {
				return tls.Dial("tcp", addr, &tlsConfig)
			},
		},
	})
	client, err := storage.NewClient(ctx, opt)
	if err != nil {
		panic(err)
	}
```

**Comment by tritone** [comment]
Ah, that can be easily fixed on your end then. Just pass the following option into NewClient as well:

> `option.WithEndpoint(addr)`

Let me know if that doesn't work on your end.

**Comment by vikstrous** [comment]
WithEndpoint was the right hint, but I actually had to use `option.WithEndpoint("https://www.googleapis.com/storage/v1/")` to connect to my local fakegcs server. Any other value was not working as expected. I didn't dig far enough to understand exactly why.

**Comment by tritone** [comment]
Got it, thanks for following up!
