### ISSUE TITLE
spanner: Support Use of Pointers for Null Values in Spanner

### ISSUE THREAD

**Issue by mikesun** [googleapis/google-cloud-go#1684]
The Spanner package provides null types such as `NullString`, but this ties Spanner specific types to struct types that may be used in more general ways. For example, it make it more cumbersome when dealing with JSON encoding/decoding of structs that use these types.

For example:

```
type BAccount struct {
	ID   string             `spanner:"id" json:"id,string"`
	Name spanner.NullString `spanner:"name" json:"name,omitempty"`
}
```

To get the JSON encoding where a null `Name` is omitted from the JSON, a custom `Account.MarshalJSON()` method has to be implemented.

It would be nice if a string pointer could be used with the Spanner package with similar semantics as the `NullString` type.

Example:

```
type BAccount struct {
	ID   string  `spanner:"id" json:"id,string"`
	Name *string `spanner:"name" json:"name,omitempty"`
}
```

This is an approach that Russ Cox has supported in the Go sql package:
https://groups.google.com/forum/#!topic/golang-nuts/vOTFu2SMNeA
https://groups.google.com/forum/#!topic/golang-dev/SiRHeFQgoLE

**Comment by olavloite** [comment]
Related to what is mentioned in this comment as well: https://github.com/googleapis/google-cloud-go/issues/1610#issuecomment-541244994

**Comment by arminm** [comment]
I think #1735 would resolve this issue as well
