### ISSUE TITLE
Firestore: Metadata operations require admin authentication (with emulator)

### ISSUE THREAD

**Issue by bsr203** [googleapis/google-cloud-go#1685]
When using firestore API with emulator, I get error
```
panic: rpc error: code = PermissionDenied desc = Metadata operations require admin authentication. [recovered]
        panic: rpc error: code = PermissionDenied desc = Metadata operations require admin authentication.
```

I see the create operation works, and most likely the error is from the clear the database code. I get all the collections, iterate through it and delete all doc ref.
```
  iter := client.Collections(context.Background())
   ....
```
I see similar issues at
https://github.com/firebase/firebase-tools/issues/1395
https://github.com/googleapis/google-cloud-php/issues/2197

**Comment by jadekler** [comment]
Which emulator are you using, btw?

**Comment by tritone** [comment]
This sounds like a bug based on my initial research (thanks for linking these related issues!). If you could provide some more complete repro code, that would be very helpful as we attempt to fix this.

**Comment by bsr203** [comment]
> Which emulator are you using, btw?

I just started using it, and run it like 
```
gcloud beta emulators firestore start --host-port="127.0.0.1:8088"


gcloud   --version
Google Cloud SDK 272.0.0
alpha 2019.05.17
app-engine-go 
app-engine-python 1.9.87
beta 2019.05.17
bq 2.0.50
cloud-datastore-emulator 2.1.0
cloud-firestore-emulator 1.10.0
core 2019.11.16
gsutil 4.46
```

This is the code I use to clear the store after test. It may take me a while to do an isolated repo, but hope you can see which API is needed admin auth.

thanks

```

func deleteTree(c *firestore.Client, ref *firestore.DocumentRef) error {

	batch := c.Batch()
	if err := deleteTreeRecursive(d, ref, batch); err != nil {
		return err
	}

	if writeResult, err := batch.Commit(context.Background()); err != nil {
		for _, e := range writeResult {
			log.Printf("deleteTree: %s", e)
		}
		return err
	}
	return nil
}

func deleteTreeRecursive(d *dstore, ref *firestore.DocumentRef, batch *firestore.WriteBatch) error {
	var iter *firestore.CollectionIterator
	if ref == nil {
		iter = c.Collections(context.Background())

	} else {
		batch.Delete(ref)
		// fmt.Printf("deleteTreeRecursive  ref: %s\n", ref.Path)
		iter = ref.Collections(context.Background())
	}

	for {
		c, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return err
		}

		docIter := c.Documents(context.Background())
		for {
			doc, err := docIter.Next()
			if err == iterator.Done {
				break
			}
			if err != nil {
				return err
			}

			if err := deleteTreeRecursive(d, doc.Ref, batch); err != nil {
				return err
			}
		}
	}
	return nil
}
```

**Comment by netbrain** [comment]
I'm having this issue as well

**Comment by netbrain** [comment]
solved it by updating my go firestore client library

**Comment by tbpg** [comment]
Thanks. I'm going to tentatively close this. But, @bsr203, please let us know if you're still having this problem and we'll reopen.

**Comment by DarrenBangsund** [comment]
Hello I'm bumping this because I am seeing this issue as well when trying to read document refs, and I can't find any solution to this:

```go
c := i.dal.Client.Collection(i.path)
			
refs, err := c.DocumentRefs(ctx).GetAll()
if err != nil {
  return fmt.Errorf("failed to get document refs for tx: %w", err)
}

docs, err = tx.GetAll(refs)
if err != nil {
  return fmt.Errorf("failed to get documents in tx: %w", err)
}
```

I'm receiving the error `failed to get document refs for tx: rpc error: code = PermissionDenied desc = Metadata operations require admin authentication.`

I'm using: 
`firebase-tools` v11.20.0 
`firestore-emulator` v1.15.1 (installed with firebase-tools) 
`cloud.google.com/go/firestore` v1.9.0
`firebase.google.com/go/v4` v4.10.0

Thank you!
