### ISSUE TITLE
storage: Have storage.Reader implement io.ReaderAt

### ISSUE THREAD

**Issue by joshuaseaton** [googleapis/google-cloud-go#1686]
May [storage.Reader](https://godoc.org/cloud.google.com/go/storage#Reader) be made to implement [io.ReaderAt](https://golang.org/pkg/io/#ReaderAt)?
I have a use-case in which I have to incrementally send bytes being read from GCS elsewhere, possibly with retries. It would be nice to not have to read the entire file (which can be quite large) into, say, a bytes.Reader first to accommodate those retries.

It looks like some of the RangeReader logic could be repurposed to this end.

**Comment by joshuaseaton** [comment]
(@frankyn, @jadekler, @tritone, one more for fuchsia's wishlist :-D )

**Comment by odeke-em** [comment]
Thank you for the feature request @joshuaseaton!

Have you taken a look at [ObjectHandle.NewRangeReader](https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#ObjectHandle.NewRangeReader)

I realize that's inflexible, so I am going to mail a CL shortly, but in the meantime perhaps NewRangeReader can help out.

**Comment by odeke-em** [comment]
@joshuaseaton I've mailed out CL https://code-review.googlesource.com/c/gocloud/+/54650, please take a look, thank you!

**Comment by joshuaseaton** [comment]
Emmanuel, thanks a lot for picking this up. Very appreciated.

**Comment by lukasschwab** [comment]
@odeke-em the last entry in that change log:

> Abandoned
> 
> We are migrating the source of truth of this repository to GitHub. As a part of that process all open CLs are being closed. If this change set is still desired please re-open it as a GitHub pull request.

I certainly still desire this change set; do you intend to reopen it as a GitHub PR?

**Comment by tritone** [comment]
@lukasschwab we are somewhat backlogged but it's on our list! Feel free to re-open on github yourself if you're interested (otherwise we'll hope to get to it by the end of the year).

**Comment by Rimantovas** [comment]
Any news on this?

**Comment by tritone** [comment]
Sorry not to update this issue sooner.

Having worked on this library for longer, I don't think this is something we'd want to implement for a few reasons. The `io.ReaderAt` [docs](https://pkg.go.dev/io#ReaderAt) state that "Clients of ReadAt can execute parallel ReadAt calls on the same input source". The Reader implementation in this client is not thread-safe and there is no straightforward way to make it threadsafe. Currently one Reader corresponds to one object GET request to GCS. There's no way to support concurrent ReadAt calls without having the client manage multiple requests under the hood or doing a lot of extra internal buffering, both of which would be problematic for performance. Even non-concurrent ReadAt calls would involve closing the request and creating a new one each time the consumer needs to Seek to a different offset, which has latency overhead that might be surprising to users.

For the non-concurrent use case, if you need to seek forward a short distance in the file, it would probably be best to just keep reading the same Reader, discarding unneeded bytes. If seeking forward a larger distance or seeking backwards, close the current Reader and use `NewRangeReader` to create a new one at the desired offset. For the use case in the initial issue, this could be part of the retry mechanism for your application.

I would imagine any interest in concurrent calls to ReadAt would be for parallelizing large object downloads. We have a new subpackage [transfermanager](https://pkg.go.dev/cloud.google.com/go/storage/transfermanager) to handle parallel object downloads and the next release will include parallelizing large file downloads in chunks. Please take a look at this if it's relevant to your use case.
