### ISSUE TITLE
spannertest: Roadmap

### ISSUE THREAD

**Issue by ericwenn** [googleapis/google-cloud-go#1689]
Currently migrating a project from Datastore to Spanner, and so far it's been a delightful experience. Internally we had a in memory database fulfilling the `datastorepb` interface enabling cheap (and offline) integration tests for data access code. Moving towards Spanner we want to maintain this possibility for testing. Found `spannertest` which is similar in goal of our internal Datastore testing, however it is lacking a lot of features (as outlined in the readme) which means that using it for testing is infeasible.

What are the plans, if there are any, of extending `spannertest` with more of the Spanner functionality?

**Comment by jadekler** [comment]
cc @dsymonds

**Comment by jadekler** [comment]
> Currently migrating a project from Datastore to Spanner, and so far it's been a delightful experience.

(that's great to hear, btw!)

**Comment by dsymonds** [comment]
There's no specific plans with spannertest. It is extended as desired. Any particular missing features that matter to you most?

**Comment by ericwenn** [comment]
> There's no specific plans with spannertest. It is extended as desired. Any particular missing features that matter to you most?

Timestamp types, joins, and query offsets. 
For us the rest of the unimplemented features are not needed atm. 

I'd be up for giving timestamps a go, considering it should be least intrusive change afaict.

**Comment by dsymonds** [comment]
Go for it. New types are fairly straightforward.

**Comment by dsymonds** [comment]
I think we can close this bug since we don't have a "roadmap" per se, but feel free to open issues for specific missing features that you want.
