### ISSUE TITLE
How to update an entity's particular field in datastore?

### ISSUE THREAD

**Issue by ameen-dev** [googleapis/google-cloud-go#1690]
I have the following struct:

type MyEntity struct {
     DSGeneratedID          int64           `json:"-" datastore:"-"`
     Phone                          string          `json:"phone"`
     Name                           string          `json:"name"`
     Address                       string          `json:"address"`
}

In the google datastore, I have stored as follows:

Name/ID                                  Name        Phone                  Address
id=5101067637358592         Sandy       9275939377      24, Nehru road, Chennai          

Say, I want to change the phone number value. Now if I know the "key.id" value, I could use the following code and achieve what I want.

entity := publisher.MyEntity{
    Phone:       "9472749280",
    Name:        "Sandy",
    Address:     "24, Nehru road, Chennai",
  }
key := datastore.IDKey("Mine", **5101067637358592**, nil)
client.Put(ctx, key, &entity)

But for this I need this key **5101067637358592**. Now, if I know the name, address and old phone number, is there any way to get the key/id?

Or if there is any other way to do this please let me know.

**Comment by tritone** [comment]
If you don't have the key, you'll have to perform a query to determine which entity you want to update. See https://cloud.google.com/datastore/docs/concepts/queries (which includes examples using this library).

**Comment by ameen-dev** [comment]
@ Tritone, I am able to construct a query and get all the other fields of that entity except "id.key"
because when I fetch it, it's coming as "0"
So either 1) How can I get the "id.key"?
(or)
2) I am able to get all the other fields of the entity other than "id.key". Now, how can I update one of those fields of that entity?

**Comment by tritone** [comment]
The key is not a field on the entity. However, when you iterate through the results of the query, the key is returned by `Iterator.Next` See https://github.com/googleapis/google-cloud-go/blob/master/datastore/query.go#L627 for details on how this works.
