### ISSUE TITLE
spanner: client lib spams with top-level trace spans with no way to suppress them

### ISSUE THREAD

**Issue by vadimsht** [googleapis/google-cloud-go#1691]
## Client

Spanner

## Describe Your Environment

Using cloud.google.com/go/spanner and go.opencensus.io/trace (with configured exporter) in the same process.

## Expected Behavior

Spanner lib doesn't send top-level (parentless) trace spans on its own.

## Actual Behavior

Cloud Tracing shows a ton of "Sent.google.spanner.v1.Spanner.GetSession" (mostly useless) top-level spans:
![traces](https://user-images.githubusercontent.com/580077/69908369-66dff280-139c-11ea-835a-ecb6fcbe838f.png)

This is probably due to this code:

```
// ping verifies if the session is still alive in Cloud Spanner.
func (s *session) ping() error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	// s.getID is safe even when s is invalid.
	_, err := s.client.GetSession(contextWithOutgoingMetadata(ctx, s.md), &sppb.GetSessionRequest{Name: s.getID()})
	return err
}
```

It unconditionally passes essentially background context to gRPC client, which then logs a span. Since it's a background context, there's no way to propagate a not-recorded parent span through it.

There's a workaround: using `option.WithTelemetryDisabled()` in `NewClient`, but it will disable reporting spans from all other RPCs as well which is sad.

It would be nice to be able to supply a context used for background activities.

**Comment by vadimsht** [comment]
Another workaround is to disable sampling globally in the process by default via `trace.ApplyConfig(trace.Config{DefaultSampler: trace.NeverSample()})` and then explicitly start spans from serving goroutines only.

**Comment by skuruppu** [comment]
@rghetia would I be able to get your advice here since I'm not familiar with OpenCensus? We essentially want this background context to know whether the parent span is recorded or not so that we don't spam trace spans. Is there a way to structure this so that we know about the parent span?

**Comment by rghetia** [comment]
> @rghetia would I be able to get your advice here since I'm not familiar with OpenCensus? We essentially want this background context to know whether the parent span is recorded or not so that we don't spam trace spans. Is there a way to structure this so that we know about the parent span?

Other alternative is to start a span with recording disabled (using NeverSample() sampler).

```go
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

        // Start parent span that doesn't record.
	parentCtx, span := StartSpan(ctx, "ping", WithSampler(NeverSample()))
        defer span.End()

	// s.getID is safe even when s is invalid.
	_, err := s.client.GetSession(contextWithOutgoingMetadata(parentCtx, s.md), &sppb.GetSessionRequest{Name: s.getID()})
	return err
```

**Comment by skuruppu** [comment]
> Other alternative is to start a span with recording disabled (using NeverSample() sampler).

I'm not sure if I'm a fan of that since if the parent span is sampled, then it would be good to capture the "ping" spans in case there's some bottleneck there. This was an issue that came up recently for a customer.

**Comment by rghetia** [comment]
> > Other alternative is to start a span with recording disabled (using NeverSample() sampler).
> 
> I'm not sure if I'm a fan of that since if the parent span is sampled, then it would be good to capture the "ping" spans in case there's some bottleneck there. This was an issue that came up recently for a customer.

But the ping doesn't seem to have any parent (It uses context.Background()). Am I missing something?

**Comment by skuruppu** [comment]
> But the ping doesn't seem to have any parent (It uses context.Background()). Am I missing something?

Yeah you are right. We currently don't have the parent available so that's why it's using context.Background(). I think my preference is:
* Try to see if we can create a child span from the parent so that these spans will be sampled if the parent is.
* If this isn't possible then use @rghetia's idea and use NeverSample(). Or maybe even remove the tracing code if it's never sampled.

**Comment by soichisumi** [comment]
Hi, there is a way to only disable the spam traces without disabling all traces by configuring GRPCDialOption of the client.

like:
```go
client, err := spanner.NewClient(
    context.Background(),
    fmt.Sprintf("projects/%s/instances/%s/databases/%s", project, instance, database),
    option.WithGRPCDialOption(grpc.WithStatsHandler(
    &ocgrpc.ClientHandler{
      StartOptions: trace.StartOptions{
        Sampler: trace.ProbabilitySampler(0), // trace only if parent span is sampled
      }},
    )),
  )
```

this method should be used to another client.

**Comment by skuruppu** [comment]
@rghetia do you know if @soichisumi's idea would work? That would be ideal.

**Comment by rghetia** [comment]
> @rghetia do you know if @soichisumi's idea would work? That would be ideal.

Will there be case where there is no parent span but it is regular( non-ping) get session call from the application? If yes, then that case will never be sampled either.

**Comment by soichisumi** [comment]
That's true
So, this workaround is useful for users who want to get a trace related to the request context.
On the other hand, users can't get a trace that doesn't have a request context, so we need to fix the spanner client library to deal with the trace

**Comment by skuruppu** [comment]
Just as a side note, recently we replaced the `GetSession` calls with `ExecuteSql` requests that send a `SELECT 1` (there are reasons why this is more efficient than doing `GetSession` and it also makes the implementations consistent across the languages).

But this doesn't help the issue in discussion since a different RPC will spam the traces.

**Comment by skuruppu** [comment]
When we previously had performance issues, it was due to us using `GetSession`. So now that we're no longer using it, I think it's quite safe to use NeverSample on the ping requests. So I think I will proceed with this option.
