### ISSUE TITLE
OPTIONS in create table statement is not supported in cloud.google.com/go/spanner/spansql 

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#1693]
(delete this for feature requests)

## Client

cloud.google.com/go/spanner/spansql

## Describe Your Environment

google cloudspanner , ParseDDL 

## Expected Behavior
_,err:= spansql.ParseDDL (`CREATE TABLE riskfactor (
  patientId STRING(MAX) NOT NULL,
  send_version TIMESTAMP OPTIONS (allow_commit_timestamp = true),
) PRIMARY KEY(patientId);
`)

behavior: expect that option will be parsed

## Actual Behavior

you got error "got "OPTIONS", want ")" or ","

in parser.go in func parseCreateTable , the options are not allowed

**Comment by neguse** [comment]
https://code-review.googlesource.com/c/gocloud/+/46390
I wrote a patch for this issue two months ago.

**Comment by olavloite** [comment]
cc @dsymonds

**Comment by dsymonds** [comment]
Yep, @neguse's patch seems like it'll be fine.
