### ISSUE TITLE
[Feature Request] SNAPPY compression Big Query Avro Export

### ISSUE THREAD

**Issue by jazzy57** [googleapis/google-cloud-go#1694]
Unless I missed it I don't think there is support for SNAPPY compression for Big Query to GCS Avro export, which does work with the CLI.  Let me know if it's something I could add and if you would accept the contribution.

**Comment by shollyman** [comment]
Thanks for pointing this out.  I created https://code-review.googlesource.com/c/gocloud/+/49331 to make it a bit clearer through some of the comments and consts, but the compression is part of the [GCSReference](https://godoc.org/cloud.google.com/go/bigquery#GCSReference).

Once that change is in, you'll be able to do something like this:

```
gcsRef := bigquery.NewGCSReference("gs://mybucket/myoutput.avro")
gcsRef.DestinationFormat = bigquery.Avro
gcsRef.Compression = bigquery.Snappy

extractor := client.DatasetInProject(srcProject, srcDataset).Table(srcTable).ExtractorTo(gcsRef)
```

However, in the interim you can simple set `gcsRef.Compression = "SNAPPY"` explicitly if you need to get unblocked.

**Comment by jazzy57** [comment]
Thanks this will due!
