### ISSUE TITLE
cbt client should detect if credentials are expired

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-go#1695]
## Client
Cloud Bigtable cbt cli client.

## Describe Your Environment
- gcloud project, with a limited [session length] (https://gsuiteupdates.googleblog.com/2019/09/session-length-for-google-cloud-console-login.html) of 2 mins and a  re-authentication method of security key
- gcloud auth login email-from-domain
- gcloud config set project my-project

## Expected Behavior
After waiting for more than 2 minutes, running a cbt command
`cbt listinstances`
cbt should print a message like "You do not currently have an active account selected." 

## Actual Behavior

Instead cbt prints  `Missing -project`

I think the underlying issue is that we are not detecting errors from config-helper:
https://github.com/googleapis/google-cloud-go/blob/be07a624a2e4501df135ab7f731b7cfb408d9df2/bigtable/internal/cbtconfig/cbtconfig.go#L213-L225

See b/130751317 for the original bug report.

**Comment by tritone** [comment]
Sorry for the delayed response on this, and thanks for your report!

So, it looks like the call to `config-helper` is made in line 214 above. But we are catching any error from Cmd.Output in the subsequent lines. According to https://golang.org/pkg/os/exec/#Cmd.Output an error should be returned if the process exits with an error. @igorbernstein2 , could you clarify how you think we should be catching errors from `config-helper`? I'm not super familiar with this gcloud command and would appreciate more context if you have it.

**Comment by jimfulton** [comment]
@igorbernstein2 quite a bit of time has passed. (Sorry.)  Could you verify that you're still seeing the same behavior?

I tried to reproduce this by logging in and then revoking creds.  I realize that that isn't exactly what you're doing.

If you're still seeing this, then I'll figure out how to set up an account that expires quickly. :)

**Comment by telpirion** [comment]
`cbt` has moved to another [repo](https://github.com/googleapis/cloud-bigtable-cbt-cli).
