### ISSUE TITLE
InstanceName() should not return first portion of hostname

### ISSUE THREAD

**Issue by joe-bowman** [googleapis/google-cloud-go#1698]
## Client

Metadata

## Describe Your Environment

n/a

## Expected Behavior

metadata InstanceName() call should return the `name` field from an instance's metadata.
(see **https://github.com/googleapis/google-cloud-go/blob/0a414e0b1324f270b6a646b3ef9cefececd5f1b4/compute/metadata/metadata.go#L409**)
## Actual Behavior

It returns the first portion of the `hostname` field, which can be completely different.

Example:

```
joe@kworker05:~$ curl http://metadata.google.internal/computeMetadata/v1/instance/name -H'Metadata-Flavor:Google'
kubeworker05

joe@kworker05:~$ curl http://metadata.google.internal/computeMetadata/v1/instance/hostname -H'Metadata-Flavor:Google'
kworker05.guse1.cs.prod.chorus1.net
```

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/49330

**Comment by joe-bowman** [comment]
Amazing, thank you!
