### ISSUE TITLE
stackdriver: update log level on GAE request entry 

### ISSUE THREAD

**Issue by darrenmcc** [googleapis/google-cloud-go#1701]
## Describe Your Environment

AppEngine standard go1.12

I'm able to use the logging/v2 library with trace IDs to group application logs by trace ID. However the log level for the entire request is not inherited from the application logs.

<img width="588" alt="Screen Shot 2019-12-10 at 10 28 13 PM" src="https://user-images.githubusercontent.com/1442631/70589246-420a2d00-1b9d-11ea-9ec0-e40d8beb347a.png">

Following the docs I was able to create a "parent" logger that has the updated severity. However this log entry was captured and grouped along with the application logs under the request log.

<img width="552" alt="Screen Shot 2019-12-10 at 10 33 01 PM" src="https://user-images.githubusercontent.com/1442631/70589232-39b1f200-1b9d-11ea-8463-eae362049e62.png">

The only way I was able to successfully group the logs together with the appropriate severities was to generate my own trace ID on a per-request basis and log every entry with it. 

<img width="418" alt="Screen Shot 2019-12-10 at 10 40 55 PM" src="https://user-images.githubusercontent.com/1442631/70589636-2fdcbe80-1b9e-11ea-80c0-f3f5eee23186.png">

This works, but the logs in stackdriver only appear if you query on the custom `logName` that I created for the "parent" logger. This is undesirable since it's not shown by default in stackdriver like `appengine.googleapis.com%2Frequest_log`. Is there no way to update the log entry that's created automatically with the highest severity level like GAE standard used to do?

**Comment by darrenmcc** [comment]
The other issue that's tangentially related is how the _first_ request to any instance will not have any application logs sent to stackdriver. It seems they're being overwritten by the default info message: 

> This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.

<img width="872" alt="Screen Shot 2019-12-16 at 11 42 48 AM" src="https://user-images.githubusercontent.com/1442631/70925536-603ab780-1ff9-11ea-8daf-5a296094678e.png">

**Comment by codyoss** [comment]
From our doc: https://cloud.google.com/appengine/docs/standard/go111/writing-application-logs

> In older App Engine runtimes, a request log entry would inherit the highest severity level from its child entries. For example, if a request entry was correlated with a warning from your app log, the request entry would appear as a warning in the Logs Viewer. This inheritance feature is not available in newer runtimes such as Go 1.11. Instead, all entries maintain the severity level that was assigned when the entry was generated.

There is no current way to have this behavior. Sorry I could not be more help.
