### ISSUE TITLE
is there anyway to just routing the credential request to an arbitrary credential provider endpoint ? 

### ISSUE THREAD

**Issue by hixichen** [googleapis/google-cloud-go#1703]
I saw this: 
```
os.Setenv("GOOGLE_APPLICATION_CREDENTIALS", config.Creds)
os.Setenv(metadataHostEnv, "127.0.0.1")
```
But, these is not something we exactly looking for. 

`GOOGLE_APPLICATION_CREDENTIALS` is a one-time setting for creds.

With `metadataHostEnv`, it is doable to route all the requests,  but it would be nice to just configure the credentials endpoint.

Ideally, if SDK to send the credential request and retry to an external provider,  it would be much easier to release the credential rotation work from our own services. 

refer:
https://github.com/aws/aws-sdk-go-v2/issues/451

**Comment by jadekler** [comment]
Not to my knowledge atm (@broady ?). Marked feature request.

**Comment by broady** [comment]
Yes it's possible, GCE_METADATA_HOST but this is not supported, it's only
for testing. We use a different path for token retrieval than in that
linked bug.

I suggest implementing the TokenSource interface and passing that as a
client option.

**Comment by jadekler** [comment]
@hixichen Does the TokenSource work for you? If so, do you mind if I close this issue?

**Comment by hixichen** [comment]
@jadekler  the goal here is to release burden for the client which is using google sdk do the creds rotation work. 
For example, my services used google sdk, it may got call failure with 401 as return code. 
Then, google sdk could try to get the credential via ENV, files, request to credentials again.

I am not sure how tokenSource internface would work for this case.

**Comment by broady** [comment]
Can you explain more? What server will you be pointing it to? Why 401? What
environment are you running in?

What credentials are being rotated?

**Comment by hixichen** [comment]
Could you please read the reference here?
https://github.com/aws/aws-sdk-go-v2/issues/451

**Comment by broady** [comment]
I read that. I still don't have the answers to my questions above. What am
I missing?

>

**Comment by broady** [comment]
Did you look at option.WithTokenSource and golang.org/x/oauth2.TokenSource?

**Comment by hixichen** [comment]
yeah,  I read the code to use WithTokenSource to initial http client. 

but, this is more like to have minimum or even 0 change for the service(meaning the service is using SDK) part, automatically route request to the external endpoint, get token and feed the sdk.

**Comment by broady** [comment]
Closing this for now, but we are thinking about ways to integrate third-party credentials (e.g., AWS metadata server) into our auth stack.

If we do, it will not be a Go-specific solution.

Thanks for raising this request!
