### ISSUE TITLE
spanner: unflake TestLIFOTakeWriteSessionOrder

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1704]
https://sponge.corp.google.com/target?id=12839dd0-c7d6-4a9c-a77d-64c962727111&target=cloud-devrel/client-libraries/go/google-cloud-go/presubmit/go113&searchFor=&show=ALL&sortBy=STATUS

```
--- FAIL: TestLIFOTakeWriteSessionOrder (0.17s)
    session_test.go:202: got session with id: projects/[PROJECT]/instances/[INSTANCE]/databases/[DATABASE]/sessions/3, want: projects/[PROJECT]/instances/[INSTANCE]/databases/[DATABASE]/sessions/2
```

**Comment by IlyaFaer** [comment]
Aleksandra already have a sign from @olavloite, in here:
https://github.com/googleapis/google-cloud-go/issues/1688

**Comment by hengfengli** [comment]
I probably close this one to avoid duplicated issues since it has been assigned in https://github.com/googleapis/google-cloud-go/issues/1688.
