### ISSUE TITLE
Authorisation on go sdk does not use the default (i.e. active) account

### ISSUE THREAD

**Issue by pkaramol** [googleapis/google-cloud-go#1706]
## Client

Authorization module
Cloud Resource Manager Module: `google.golang.org/api/cloudresourcemanager/v1`

## Describe Your Environment

`go 1.13` app running on `MacOS` Mojave

## Expected Behavior

The auth should take place with the account that `gcloud` cli indicates as `ACTIVE`

## Actual Behavior

My available `gcloud` auth accounts:

```
▶ gcloud auth list                                                        
         Credentialed Accounts
ACTIVE  ACCOUNT
        account1@gmail.com
        account2@gmail.com
*       account3@gmail.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

```

When performing `gcloud projects list` I __do__ get the list of projects corresponding to the account that above is indicated as ACTIVE (i.e. the one with the asterisk, `account3@gmail.com`)

Nonetheless, when I use the `go` [google cloud sdk][1] and more specifically the [`cloudresourcemanager`][2] in order to list my projects, I get the ones corresponding to `account1@gmail.com`.

Why isn't `go` sdk using the account that `gcloud` perceives as `ACTIVE` and how can I instruct it to do so?

The strange part is when I developed some tools using the `python` sdk, the behaviour was straightforward and all the sdk calls were indeed using the active account without me having to do any extra configuration steps. 

  [1]: https://github.com/googleapis/google-cloud-go
  [2]: https://godoc.org/google.golang.org/api/cloudresourcemanager/v1#ProjectsListCall

**Comment by pkaramol** [comment]
This is getting even weirder...

I performed

```
gcloud auth revoke account1@gmail.com
```

and my program still lists the projects of the revoked account.

**Comment by jadekler** [comment]
There are a number of application default credentials it tries in a specific order. These are described here: https://github.com/golang/oauth2/blob/858c2ad4c8b6c5d10852cb89079f6ca1c7309787/google/default.go#L61-L75.

Would you mind checking if any of these apply to your environment?

**Comment by codyoss** [comment]
Closing due to lack of response.
