### ISSUE TITLE
spanner: ` for special keywords not supported in cloud.google.com/go/spanner/spansql

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#1710]
(delete this for feature requests)

## Describe Your Environment

extract the ddl of the cloudspanner database and got in a go structure

## Expected Behavior

get the go structure 

## Actual Behavior

CREATE TABLE `enum` (
	enumId STRING(MAX) NOT NULL,
) PRIMARY KEY (enumId)

got following error :  unexpected byte 0x60

the special character  ` is the cause of the problem

**Comment by dsymonds** [comment]
Yes, this is a known TODO.

```
spanner/spansql/parser.go:	// TODO: backtick (`) for quoted identifiers.
```

**Comment by dsymonds** [comment]
https://code-review.googlesource.com/c/gocloud/+/51415
