### ISSUE TITLE
Firestore release 1.1.1 is missing "v" prefix in Git tag

### ISSUE THREAD

**Issue by mrkanister** [googleapis/google-cloud-go#1716]
When updating the dependencies of a project of mine that is using Firestore, I noticed that it would stay at v1.1.0 even though there was already a newer release. Upon closer inspection, I saw that the Git tag for the [release][1] is missing the "v" prefix that is required by Go modules:

```bash
# expected
firestore/v1.1.1

# actual
firestore/1.1.1
```

This leads to the following error on fetching it:
```bash
$ go get cloud.google.com/go/firestore@1.1.1
go get cloud.google.com/go/firestore@1.1.1: cloud.google.com/go/firestore@1.1.1: invalid version: unknown revision 1.1.1

$ go get cloud.google.com/go/firestore@v1.1.1
go get cloud.google.com/go/firestore@v1.1.1: cloud.google.com/go/firestore@v1.1.1: invalid version: unknown revision firestore/v1.1.1
```

[1]: https://github.com/googleapis/google-cloud-go/releases/tag/firestore%2F1.1.1

**Comment by codyoss** [comment]
Thank you for the report! We will get this retagged

**Comment by tritone** [comment]
Hi @mrkanister -- I fixed the tags and verified that `go get cloud.google.com/go/firestore@v1.1.1` works correctly now. Can you verify that this now works for you?

**Comment by mrkanister** [comment]
It's working as expected now, thanks for the quick response!

**Comment by tritone** [comment]
Fantastic, thanks for confirming!
