### ISSUE TITLE
GoDoc link for kms package is broken (link in README)

### ISSUE THREAD

**Issue by mickeyreiss** [googleapis/google-cloud-go#1722]
[README.md:52](https://github.com/googleapis/google-cloud-go/blame/master/README.md#L52) includes a link to `https://godoc.org/cloud.google.com/go/kms`, but this page is broken for me:

![image](https://user-images.githubusercontent.com/47405/72008724-5461a000-3209-11ea-9fef-48fe815a23ca.png)

Thanks!

**Comment by codyoss** [comment]
Thanks for the report we will get this corrected!
