### ISSUE TITLE
monitoredres.MonitoredResourceMetadata have always empty map with UserLabels 

### ISSUE THREAD

**Issue by homelessnessbo** [googleapis/google-cloud-go#1725]
## Client

StackDriver 

## Describe Your Environment

MacOS

## Expected Behavior

`(monitoredres.MonitoredResourceMetadata).GetUserLabels()` returns labels that are defined by users on GCP objects like compute VMs or CloudSQL instances.

## Actual Behavior

Always returns empty map whenever object has or does not have user-defined labels.

To reproduce: 

1. Create a VM and assign some labels to it, like `test: 123`
2. Create a SA with read permissions on StackDriver API and put it to `sa.json` file next to the `main.go`

Replace `$YOUR_PROJECT_IS_HERE` and `$YOUR_VM_IS_HERE` hardcoded in the following snippet with GCP project where your VM is located and name of the VM you just created accordingly. 

Put the code snippet to the `main.go`. Then just `go run main.go`

As output you will always see `map[]` (instead of real user-defined labels that I'd expect as output from `fmt.Println(series.GetMetadata().GetUserLabels())` in the end of the snippet)

Code snippet (I'm sorry for the code quality, I did not have much time to prepare anything clean and beautiful): 
```go
package main

import (
	"bytes"
	"context"
	"fmt"
	"github.com/golang/protobuf/ptypes/timestamp"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/api/iterator"
	"github.com/prometheus/common/log"
	"google.golang.org/api/option"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"io"
	"time"

	monitoring "cloud.google.com/go/monitoring/apiv3"
	monitoringpb "google.golang.org/genproto/googleapis/monitoring/v3"
)

const (
	timeRange         time.Duration = 5 * time.Minute
)

func main () {
	var buf bytes.Buffer
	if err := printUserLabels(&buf, "$YOUR_PROJECT_IS_HERE", "compute.googleapis.com/instance/cpu/utilization"); err != nil {
		log.Errorln(err)
	}
	result := buf.String()
	fmt.Printf(result)
}


func printUserLabels(w io.Writer, projectID, metricType string) error {
	ctx := context.Background()
	c, err := monitoring.NewMetricClient(ctx)
	if err != nil {
		return fmt.Errorf("NewMetricClient: %v", err)
	}
	req := &monitoringpb.GetMetricDescriptorRequest{
		Name: fmt.Sprintf("projects/%s/metricDescriptors/%s", projectID, metricType),
	}
	resp, err := c.GetMetricDescriptor(ctx, req)
	if err != nil {
		return fmt.Errorf("could not get custom metric: %v", err)
	}
	filter := "( metric.type = \"" + resp.Type + "\" ) AND metric.label.instance_name = \"$YOUR_VM_IS_HERE\""
	endTime := time.Now().UTC()
	startTime := endTime.Add(-timeRange)


	mClient, err := monitoring.NewMetricClient(ctx, option.WithCredentialsFile("./sa.json"))
	if err != nil {
		log.Errorln(err)
	}
	it := mClient.ListTimeSeries(ctx, &monitoringpb.ListTimeSeriesRequest{
		Name:   "projects/" + projectID,
		Filter: filter,
		Interval: &monitoringpb.TimeInterval{
			StartTime: &timestamp.Timestamp{Seconds: startTime.Unix()},
			EndTime:   &timestamp.Timestamp{Seconds: endTime.Unix()},
		},
		View: monitoringpb.ListTimeSeriesRequest_FULL,
	}, gax.WithGRPCOptions())
	for {
		series, err := it.Next()
		if err == iterator.Done ||
			status.Code(err) == codes.NotFound ||
			status.Code(err) == codes.Canceled ||
			err == context.Canceled {
			break
		}
		if err != nil {
			log.Errorf("Error retrieve %s: %s", resp.Type, err)
			break
		}
		fmt.Println(series.GetMetadata().GetUserLabels())
	}
	return nil
}
```

**Comment by homelessnessbo** [comment]
@codyoss I find it more like a bug. As explained method is the only way to pull user defined labels I found and it never returns them.

**Comment by codyoss** [comment]
I think there is a misunderstanding. The way I understand it is that those tags would relate to the metric itself and not the instance. You can add extra labels to a metric for custom metrics. This is different then the labels on the instance itself. But you could search with instance labels.

**Comment by homelessnessbo** [comment]
@codyoss so you are saying that `UserLabels` [here](https://godoc.org/google.golang.org/genproto/googleapis/api/monitoredres#MonitoredResourceMetadata) are only for user-defined labels on custom metrics?

**Comment by tbpg** [comment]
The Stackdriver API deals with Stackdriver resources, like metrics.

If you're looking for the labels on something like a Compute instance, you can use the Compute API: https://pkg.go.dev/google.golang.org/api/compute/v1?tab=doc#Instance (note the `Labels` field). If you create an instance with labels then use [`(*InstancesService).Get`](https://pkg.go.dev/google.golang.org/api/compute/v1?tab=doc#InstancesService.Get), you should see the labels.

**Comment by tbpg** [comment]
Closing this, but let us know if you run into another issue!
