### ISSUE TITLE
spannertest: TIMESTAMP support

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#1727]
Following up on https://github.com/googleapis/google-cloud-go/issues/1689

We're using Spanner as the backing storage for a resource oriented API (we're using the [Cloud API design guide](https://cloud.google.com/apis/design/standard_fields)).

This means we're storing a [standard set](https://cloud.google.com/apis/design/standard_fields) of `created_at`, `updated_at` and `deleted_at` timestamps for our resources, using [TIMESTAMP](https://cloud.google.com/spanner/docs/data-types#timestamp-type) as the column type.

Support for `TIMESTAMP` in [spannertest](https://github.com/googleapis/google-cloud-go/tree/master/spanner/spannertest) is the one thing blocking us from covering these APIs with `spannertest`-based unit tests (offset support would enable unit testing of list pagination, but that's a separate, smaller issue).

We're currently strapped for time and are not able to take on implementation of this ourselves.

Creating this issue on the off-chance you are able to up-prioritize it.

**Comment by dsymonds** [comment]
Sorry, only just noticed this bug. I can likely tackle this today or tomorrow.

**Comment by dsymonds** [comment]
https://code-review.googlesource.com/c/gocloud/+/50791

**Comment by odsod** [comment]
@dsymonds Nice one! Many thanks, this will come in handy.

Great work on the `spannertest` and `spansql` packages by the way - really improves the developer experience for Spanner in Go. :star:

**Comment by dsymonds** [comment]
You’re welcome! I’m glad it is helping you out.
