### ISSUE TITLE
firestore: Allow projections to be passed for getting Batched Documents in `GetAll()`

### ISSUE THREAD

**Issue by ninadingole** [googleapis/google-cloud-go#1728]
## Client

firestore

## Describe Your Environment
Using firestore for web services deployed on Google App Engine 

We have used firestore as our backend to serve static data from our web services. However, while we batch 50 documents from the firestore in some scenarios we do not require the entire documents, we need only 5 fields out of the entire documents. But because there is no way you can pass projection/fields to be selected from documents during batch query we saw our API was taking more time to respond.

In the source code, we saw:

```func (c *Client) getAll(ctx context.Context, docRefs []*DocumentRef, tid []byte) ([]*DocumentSnapshot, error)```

It creates 
```
req := &pb.BatchGetDocumentsRequest{
		Database:  c.path(),
		Documents: docNames,
	}
```
This BatchGetDocumentsRequest has `Mask *DocumentMask` field which only returns the selected fields from the resultset or query the firestore only for the given data. But there is no provision in the `GetAll()` method to pass the fields. We have created a wrapper in our code that takes an array of field paths `fieldPaths []string` and create a `DocumentMask` with this array and pass it to the `BatchGetDocumentsRequest` instance. After doing this we again did a performance test of our application and the result showed us a 77% improvement in total response time. I am raising this Issue so that If approved I will like to raise a PR where the `GetAll` method also takes fieldPaths array and pass it to `BatchGetDocumentsRequest` or have another method in the API that allows projection. This will help others also who are having the same scenario as ours and using the same API to use Projection.

## Expected Behavior
Should allow the user to pass FieldsPath to `GetAll()` Method and Only return the requested fields by the user and if fieldPaths is `nil` then return the entire document.

## Actual Behavior
Current API doesn't allow a user to do projects for `GetAll()` method call.

**Comment by ninadingole** [comment]
@tbpg and @tritone please let me know how you want to do it? I already have the fix I can just push that and you people can review it and let me know, I want to contribute to this issue

**Comment by tbpg** [comment]
This sounds like a good idea to me. Perhaps we should add another method like `GetAllWithMask`?

(We can't add the argument to `GetAll` because it would be a breaking change.)

Thoughts, @tritone and @BenWhitehead?

**Comment by tritone** [comment]
@BenWhitehead and I are doing some additional follow up with the Firestore team since this is a fairly large change, and it's not a feature that is available through the client library APIs in other languages. We'll have further information soon.

**Comment by ninadingole** [comment]
any updates on this?

**Comment by ninadingole** [comment]
@BenWhitehead I can contribute to the changes, me and my team has already worked on implementing the same thing in our own project and I can raise a PR for this, just let me know what are your team thoughts on how to implement in this API without breaking the existing method. As per @tbpg it would be a breaking change if we add another param to the existing `GetAll` method, should I add a new Method like `GetAllWithMask()` that will take a second param of which fields to select from Firestore?

**Comment by BenWhitehead** [comment]
@tbpg and/or @tritone What are you thoughts on the best way @ninadingole could contribute the work their team has done internally?

**Comment by tbpg** [comment]
I think this is something we should do. It has a clear, measured benefit. We just need to find the right API to add it. @ninadingole, thank you for bringing this up and offering to implement. Sorry for the slow response.

Here is the underlying request proto: https://pkg.go.dev/google.golang.org/genproto/googleapis/firestore/v1beta1?tab=doc#BatchGetDocumentsRequest

I see a few options:
1. `GetAllWithMask`
1. `GetAllWithMaskAndConsistency` (some shorter name than this, but you get the idea)
1. `GetAllWithOptions(ctx context.Context, docRefs []*DocumentRef, opts ...GetAllOption) (_ []*DocumentSnapshot, err error)`
1. `GetBatch(ctx context.Context, req *pb.BatchGetDocumentsRequest) (_ []*DocumentSnapshot, err error)`

(Open to other ideas.)

I am concerned about a few things:
* I don't want to end up with 5 variants of `GetAll` depending on the necessary args.
* Someone else may want/need the consistency options.
* There may be additional fields added to the request in the future.

Option 4 seems awkward and like we're mixing APIs with unclear semantics.

Option 3, defining options just for `GetAll` seems like overkill.

Option 2 seems like most people won't actually need the consistency arg, so why include it for everyone who wants to use a mask.

That leaves option 1. It's not ideal, but it works for today and the foreseeable future.

Thoughts?

**Comment by ninadingole** [comment]
@tbpg I am also in the favour of option 1. I don't know how much is the usage of the Consistency parameter used by the consumers? Do you have any idea?

**Comment by tbpg** [comment]
I haven't seen any feature requests like this one for the consistency parameter. But, this is the first one I've seen for mask. :)

**Comment by BenWhitehead** [comment]
After some digging, I've found that this type of API usage is already implemented in the nodejs version of the Firestore library. This functionality is part of the query interface via the function [`select`](https://github.com/googleapis/nodejs-firestore/blob/8c52d475ae486e2998220947a0b0441d4a95ab49/types/firestore.d.ts#L944). The idea here being that of a select clause in an SQL statement. 

As far as implementation, we should only be using the v1 protos. v1 has been GA for over a year now, and we should move away from v1beta1 protos. I'm not sure I understand what is meant by consistency options @tbpg Firestore is strongly consistent. Would it be possible to add a `select` function to the query interface similar to `Where` and take care of things there?

One final note, when using a `select` on a query, as far as Firestore is concerned the full document still must be read from the backend, so you will still be billed for the full document read, the reduction will only be reduced WAN bytes (I am assuming you have large-ish documents and are wanting to reduce bandwidth usage).

**Comment by tbpg** [comment]
Here is the v1 link: https://pkg.go.dev/google.golang.org/genproto/googleapis/firestore/v1?tab=doc#BatchGetDocumentsRequest

(Wasn't advocating for the beta version -- it was the first one that popped up.)

By consistency arg, I was referring to this field in the above type:

```
	// The consistency mode for this transaction.
	// If not set, defaults to strong consistency.
	//
	// Types that are valid to be assigned to ConsistencySelector:
	//	*BatchGetDocumentsRequest_Transaction
	//	*BatchGetDocumentsRequest_NewTransaction
	//	*BatchGetDocumentsRequest_ReadTime
	ConsistencySelector  isBatchGetDocumentsRequest_ConsistencySelector
```

Go also has `Query.Select`: https://pkg.go.dev/cloud.google.com/go/firestore?tab=doc#Query.Select

Would that be an acceptable workaround for this `GetAll` issue?

**Comment by telpirion** [comment]
Since we haven't heard back on @tbpg's suggested workaround, I'm going to close this issue.
