### ISSUE TITLE
pubsub: client does not interact with local emulator

### ISSUE THREAD

**Issue by willfreeborn** [googleapis/google-cloud-go#1730]
## Client

Pubsub

## Describe Your Environment

MacOS Mojave

## Expected Behavior

Querying for topics with emulator returns true if exists, false otherwise

## Actual Behavior

Function hangs and does not return until timeout

```
es, err = pubsub.NewClient(ctx, "dev")
if err != nil {
	log.Fatalf("Failed to create client: %v", err)
}
topic := es.Topic("hello")
ok, err := topic.Exists(ctx)
if err != nil {
	i.Fatalf("failed to check if topic exists: %v", err)
}
if ok {
	if err := topic.Delete(ctx); err != nil {
		i.Fatalf("failed to cleanup the topic (%q): %v", "hello", err)
	}
}
```

**Comment by willfreeborn** [comment]
ENVVars are also set according to the guide: https://cloud.google.com/pubsub/docs/emulator#using_the_emulator

**Comment by hongalex** [comment]
Just to be sure, are you running `gcloud beta emulators pubsub start --project=PUBSUB_PROJECT_ID`? If so, can you paste the messages that show up there as the emulator is running?

**Comment by hongalex** [comment]
Closing due to lack of response. Feel free to comment if you're still having issues and I'll reopen
