### ISSUE TITLE
storage: endpoint port is dropped

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1737]
**Client**

Storage

**Code**

e.g.
```go
	c, err := NewClient(ctx, option.WithEndpoint("example.com:8888"))
```

**Expected behavior**

Port is retained.

**Actual behavior**

Port is dropped.

**Additional context**

Behavior was added in https://github.com/googleapis/google-cloud-go/commit/95bbb7d728ee6b3f6c1873cfee71b0cb87a0f60d#diff-efc763a7d18657aa44c013131823cfc9R131.

Docs for [(*url.URL).Hostname](https://pkg.go.dev/net/url/?tab=doc#URL.Hostname):
> Hostname returns u.Host, stripping any valid port number if present.

Reported in https://github.com/googleapis/google-cloud-go/issues/1619#issuecomment-576057316.

cc @tritone @broady

**Comment by tritone** [comment]
My mistake on this one; posted https://code-review.googlesource.com/c/gocloud/+/50891 with a fix.

**Comment by vikstrous** [comment]
Thanks for fixing. I couldn't verify the fix because both before and after the fix, there was no combination of options that worked for connecting to fake gcs storage backend. I'm using the following instead:
```
	addr := "127.0.0.1:4443"
	opt := option.WithHTTPClient(&http.Client{
		Transport: &http.Transport{
			DialTLS: func(string, string) (net.Conn, error) {
				return tls.Dial("tcp", addr, &tls.Config{
					InsecureSkipVerify: true,
				})
			},
		},
	})
	client, err := storage.NewClient(ctx, opt)
```
