### ISSUE TITLE
Firestore transaction lock not working as expected, and won't retry in some cases

### ISSUE THREAD

**Issue by renxiawang** [googleapis/google-cloud-go#1741]
**Client**
Firestore

**Environment**

Docker: golang:1

**Code**

```go
package main

lockDocRef := client.Collection("lockDocCollection").Doc(lockDocID)
err := client.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
    lockDoc, err := tx.Get(lockDocRef)
    if err != nil {
        return errors.Wrap(err, "")
	}

	fmt.Println("Start processing")
	
	// .. time consuming read and write docs from other collection, can throw error:
	// rpc error: code = Aborted desc = Too much contention on these documents. Please try again.

	fmt.Println("End processing")
}
```

**Expected behavior**
Two expectations: 
1.  When executing this piece of code in parallel with same lockDocID, I expect the see the printf printed sequentially, like

```
Start processing
End processing
Start processing
End processing
```
because I place a lock at the beginning. 

2. When `rpc error: code = Aborted desc = Too much contention on these documents. Please try again.` occurs (which shouldn't if the lock is working as i expcted), I expect the [firestore.go](https://github.com/googleapis/google-cloud-go/blob/master/firestore/transaction.go) retries on that error. 

**Actual behavior**

1. I see printf printed not in sequential order, as if the lock on the lockDoc is not locking.

```
Start processing
Start processing
End processing
End processing
```

2. By tracking down the retry logic, I found that if the error is return from [this line](https://github.com/googleapis/google-cloud-go/blob/f194c54bc709cae688f324a6c2b6e4cd6ccc3c29/firestore/transaction.go#L128), it won't be retried. if it returned from [this line](https://github.com/googleapis/google-cloud-go/blob/f194c54bc709cae688f324a6c2b6e4cd6ccc3c29/firestore/transaction.go#L139), it will be retried.

**Comment by renxiawang** [comment]
NVM, I should have RTFM. 

```
// If f returns non-nil, then the transaction will be rolled back and
// this method will return the same error. The function f is not retried.
```

**Comment by tbpg** [comment]
Glad you got it figured out! Let us know if you run into any other issues.
