### ISSUE TITLE
storage:  V4 Signature Signed URLs With Bucket-Bound Hostnames

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-go#1745]
Tracking issue for work defined in companion document.

[New Client Request - Support for Bucket-Bound Hostnames With GCS Signed URLs](https://docs.google.com/document/d/1Da8LQEmc1OKRECxXqdivQa4tcTEImlti_fVYzoh4reI)

**Comment by tritone** [comment]
This has been added in e44449b6b71536e41c165d84eb8a9253154c0ba8 .
