### ISSUE TITLE
storage: V4 Signature Support for virtual hosted-style signed 

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-go#1746]
Tracking issue for work defined in companion document.

[New Client Request - Support for virtual hosted-style signed URLs](https://docs.google.com/document/d/1TkoDiZjz6nINNVQrYbrfaODhmcMTR-crb94aR1cXZVA/edit#)

**Comment by tritone** [comment]
This has been added in e44449b6b71536e41c165d84eb8a9253154c0ba8 .
