### ISSUE TITLE
logging: concerns about client.entries performance

### ISSUE THREAD

**Issue by andie1706** [googleapis/google-cloud-go#1749]
**Client**

Cloud Function 

**Actual behavior**
Concerned about the performance of the library (Go stackdriver library : cloud.google.com/go/logging/logadmin) when it escalates in a linear pattern.

When using the Client.Entries method [1] it was found a non linear performance behavior
- 25 resources: 30 seconds
- 50 resources: 1 min 30 seconds
- 75 resources: 2 minutes
- 100 resources: 3 minutes 30 seconds.

The recommendation would be break up the search into, say, 25-resource blocks and distribute them using Go functions?

[1] https://godoc.org/cloud.google.com/go/logging/logadmin#Client.Entries

**Additional context**
The code used the following 
- Compose a block of resources (no more than MaxResourcesPerSearch)
- Call Clients.logReader.Entries() using the current block of resources and the search criteria. (Clients.logReader is a logadmin object)
- Advance through the results via searchResults.Next(), accumulating the log entries in the 'detections' variable. (searchResults is an EntryIterator object)

**Comment by tbpg** [comment]
Thank you for filing this! Would you mind sharing the exact code you were using? That would help make sure we're looking at the same thing and can reproduce the results.

**Comment by tbpg** [comment]
Closing this as we need additional information. But, if you end up having a reproducible benchmark, let us know!
