### ISSUE TITLE
automl/apiv1beta1: Wrong Model ID being returned

### ISSUE THREAD

**Issue by 9mm** [googleapis/google-cloud-go#1754]
**Client**

`cloud.google.com/go/automl/apiv1beta1`

**Environment**

AutoML Tables

**Code**

We are receiving wrong Model ID from AutoML using Golang GCP library

Here's the code we are running:

```go
req := &automlpb.ListModelsRequest{
		Parent: "projects/testml-datas-12345/locations/us-central1",
		Filter: "tablesModelMetadata:*",
	}
...
client, err := automl.NewClient(ctx, option.WithCredentialsFile(appConfig.GCPcredsPath))
	if err != nil {
...
	}
	it := client.ListModels(ctx, req)

for {
		resp, err := it.Next()
...
	}
```

This is what inside of our Model struct (resp from code above is response from GCP API)

```
Model{
			DisplayName:         resp.GetDisplayName(),
			DatasetID:           resp.GetDatasetId(),
			CreateTime:          time.Unix(resp.GetCreateTime().GetSeconds(), 0),
			TablesModelMetadata: resp.GetTablesModelMetadata(),
			UpdateTime:          time.Unix(resp.GetUpdateTime().GetSeconds(), 0),
			DeploymentState:     resp.GetDeploymentState(),
		}
```

The contents of the struct have `DisplayName` and `DatasetID`, however while the former is correct, `DatasetID` does NOT match what is in the GCP user panel.

We couldn't find any other publicly documented way to use specific model for predictions in Golang without using DatasetID. Because of this we can't use new models automatically in our application as the returned ID is invalid, we need to set it manually.

**Comment by tbpg** [comment]
Thank you for filing this! Is it possible there is more than one model? Are you checking all of the models returned by `ListModels`?

Another idea is to confirm the UI - can you post a screenshot (redacted if needed) of the model in the console?

Finally, have you tried not using the custom `Model` type and just printing out the dataset ID of each model returned by `ListModels`? That way, we can make the reproduction as minimal as possible. A test case that somehow shows the failure would be even better (maybe two `ListModels` calls return different results?)

**Comment by 9mm** [comment]
I'm quite sorry for this, it appears we were using the wrong function, getdatasetid instead of getname... my apologies

**Comment by tbpg** [comment]
No worries! I'm glad you got it working. Let us know if you have any other issues.
