### ISSUE TITLE
civil: helpers to work with dates: Range, Min, Max?

### ISSUE THREAD

**Issue by evanj** [googleapis/google-cloud-go#1755]
I'm writing some Go programs that coordinate a bunch of fairly complex queries, and work with tables. I've found it useful to reuse the `civil.Date` type. As part of this, I've written some "helper" utilities, like a `Range` type and a `Min/Max` function. Would this be welcomed upstream into the `civil` package? If so, I'm happy to post my code as a Gerrit CL. If not, feel free to close this: I can also see the argument that this isn't directly used by google-cloud-go, so it shouldn't be supported by this team. I won't be offended, I just thought it could be useful to others.

This is similar to feature requests like #1609 and #1145, which are requesting adding "new" functionality to this package.

**Comment by tbpg** [comment]
I'm inclined to not add this directly to the `civil` package. I'm not entirely opposed, but I'm also hesitant to extend the API if there isn't much demand. Of course, helpers might be good in a separate package. 

Thank you for filing this issue and not just sending the CL. We really do appreciate it.

**Comment by evanj** [comment]
Makes sense to me! I just thought I would offer in case there was interest. civil is pretty useful, it feels like a package that belongs in a golang/x repo!
