### ISSUE TITLE
pubsub: pstest seems to hang

### ISSUE THREAD

**Issue by evfimivs** [googleapis/google-cloud-go#1757]
**Client**

PubSub Go Client

**Environment**

MacBook with Catalina 10.15.2

Hardware:
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,3
  Processor Name:	6-Core Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  Boot ROM Version:	1037.60.58.0.0 (iBridge: 17.16.12551.0.0,0)
  Serial Number (system):	C02XT152LCM6
  Hardware UUID:	B53A770E-47B9-59CA-B9B8-9A7B18ED3330
  Activation Lock Status:	Enabled

**Code**

```
package main
import (
	"context"
	"flag"
	"fmt"
	"os"
	"cloud.google.com/go/pubsub"
)
func main() {
	var (
		project = "redacted"
	)
	flag.StringVar(&project, "p", project, "GCP project")
	flag.Parse()
	if flag.NArg() == 0 {
		fmt.Printf("Usage: pstest [ -p PROJECT ] TOPIC...\n")
		os.Exit(1)
	}
	ctx := context.Background()
	fmt.Println("Creating a pubsub client...")
	mq, err := pubsub.NewClient(ctx, project)
	if err != nil {
		panic(err)
	}
	fmt.Println("pubsub client created")
	for _, topic := range flag.Args() {
		fmt.Printf("Creating a topic '%s'\n", topic)
		_, err := mq.CreateTopicWithConfig(ctx, topic, &pubsub.TopicConfig{
			Labels: map[string]string{
				"created-by": "pstest",
			},
		})
		if err != nil {
			panic(err)
		}
		fmt.Printf("'%s' topic created\n", topic)
	}
	fmt.Println("Done")
}
```
$ uname -a
Darwin Stuarts-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64 i386 MacBookPro15,3 Darwin
$ gcloud -v
Google Cloud SDK 275.0.0
bq 2.0.51
core 2020.01.03
gsutil 4.46
$ ./pstest test-topic
Creating a pubsub client...
pubsub client created
Creating a topic 'test-topic'
^C
$

**Expected behavior**

Works smoothly.
**Actual behavior**

Hangs indefinitely after "Creating a topic 'test-topic'" is printed.

**Comment by tbpg** [comment]
Glad you got it figured out. Let us know if you have any other issues.
