### ISSUE TITLE
spanner: Error.GRPCStatus breaks backward-compatibility

### ISSUE THREAD

**Issue by ktr0731** [googleapis/google-cloud-go#1767]
**Client**

Spanner.

**Environment**

All.

**Code**

e.g.
```go
fmt.Println(&spanner.Error{Code: codes.Unavailable})
```

**Expected behavior**
In other versions before spanner/v0.1.2 prints `spanner: code = "Unavailable", desc = ""`.

**Actual behavior**
In spanner/v0.1.2 prints `spanner: code = "Unknown", desc = ""`, not `Unavailable`.
Because `Error.GRPCStatus` returns a status that has `Unknown` when `Error.err` is unspecified.
Older versions return the code that is specified by `Error.Code`.

**Addtional context**
I've sent a patch https://code-review.googlesource.com/c/gocloud/+/51113 for fixing it.

**Comment by olavloite** [comment]
I'm not 100% sure this is something we would want to support. Spanner errors should normally only be created by the Spanner library, and the client library will always create them with a wrapped error that will supply the status code. The `Error.Code` field has also been deprecated, and adding this would mean that we would still be using it.

Is there a specific reason that you are creating Spanner errors yourself? Or do you know of a situation where the client library creates a Spanner error without a wrapped gRPC status error?

**Comment by ktr0731** [comment]
Thank you for the quick response.
In our case, our tests for an error handling helper function were broken by the above code. In this test, it is desirable to use the same Spanner error as the input to get closer to the production environment.

Also,  just as you said, we shouldn't depend on `Error.Code` field, but first of all I think we shouldn't be export `Error.Code` without backward-compatibility. In the perspective of a reader of `Error.Code`, it has been still be kept backward-compatibility, but the perspective of a writer is not.
We should keep it until `Error.Code` will be dropped. Of course, after dropping or unexportig `Error.Code`, we don't need to concern it.

 Also I thought it is better to unexport `Error` itself to prevent using `Error` such as our tests.

**Comment by olavloite** [comment]
Fixed by https://code-review.googlesource.com/c/gocloud/+/51113
