### ISSUE TITLE
pubsub: unflake TestIntegration_Errors

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1768]
https://source.cloud.google.com/results/invocations/dd806b4e-2299-4f0e-b83d-b77dd1f553bc/targets/tests/tests

**Comment by hongalex** [comment]
That test is passing locally (and [here](https://source.cloud.google.com/results/invocations/09596ba1-97c5-47e6-bf6c-e2de965c9949/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fcontinuous%2Fgo113/log)) so I'll need to do some more testing to figure out what's happening.

**Comment by hongalex** [comment]
Closing since it seems like it was a one time blip in network; tests have been green since last week.
