### ISSUE TITLE
internal/gapicgen: changes in grpc appear to have broken proto generation

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-go#1769]
Generation of protobuf files managed by internal/gapicgen are failing.  Quick look implicates changes in grpc side.

Example failures (happens for multiple APIs):

googleapis/ads/admob/v1/admob_api.pb.go:608:11: undefined: grpc.SupportPackageIsVersion6
googleapis/ads/admob/v1/admob_api.pb.go:628:5: undefined: grpc.ClientConnInterface

Scanning grpc, it seems there's changes in the expectations of consumers:
https://github.com/grpc/grpc-go/pull/3350 just updated readme:

Compiling error, undefined: grpc.SupportPackageIsVersion
If you are using Go modules:
Please ensure your gRPC-Go version is required at the appropriate version in the same module containing the generated .pb.go files. For example, SupportPackageIsVersion6 needs v1.27.0, so in your go.mod file:

module <your module name>

require (
    google.golang.org/grpc v1.27.0
)

**Comment by tbpg** [comment]
One idea to prevent this from happening again is to add an auto-update to the generation pipeline.

**Comment by tbpg** [comment]
Can downgrade to p2 after things are working again.

https://github.com/googleapis/go-genproto/pull/295 should fix this instance. Waiting on the next run.

**Comment by broady** [comment]
GAPIC generation failed:

```
microgen generating texttospeech
exec.Command.Run: /usr/bin/protoc [protoc -I /tmp/update-genproto212726311/googleapis -I /tmp/update-genproto212726311/proto --go_gapic_out /tmp/update-genproto212726311/gocloud --go_gapic_opt go-gapic-package=cloud.google.com/go/texttospeech/apiv1;texttospeech --go_gapic_opt grpc-service-config=google/cloud/texttospeech/v1/texttospeech_grpc_service_config.json --go_gapic_opt gapic-service-config=google/cloud/texttospeech/v1/texttospeech_v1.yaml --go_gapic_opt release-level=alpha /tmp/update-genproto212726311/googleapis/google/cloud/texttospeech/v1/cloud_tts.proto]
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/api/client.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/client.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/api/client.proto:67:8: "google.protobuf.ServiceOptions" is not defined.
google/api/client.proto: "google.protobuf.ServiceOptions" is not defined.
google/api/field_behavior.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/field_behavior.proto:28:8: "google.protobuf.FieldOptions" is not defined.
google/cloud/texttospeech/v1/cloud_tts.proto:20:1: Import "google/api/annotations.proto" was not found or had errors.
google/cloud/texttospeech/v1/cloud_tts.proto:21:1: Import "google/api/client.proto" was not found or had errors.
google/cloud/texttospeech/v1/cloud_tts.proto:22:1: Import "google/api/field_behavior.proto" was not found or had errors.
error generating gapics (may need to check logs for more errors): exit status 1
```

**Comment by shollyman** [comment]
Yeah, smells like the common proto files aren't in the directory/path expected by the binary.

**Comment by broady** [comment]
Yep, I think I needed to install `protobuf-dev` too.

The other day I learned about Alpine's package searcher:
https://pkgs.alpinelinux.org/contents?file=descriptor.proto&path=&name=protobuf-dev&branch=edge&repo=main&arch=x86_64

Very handy!

**Comment by broady** [comment]
protos and gapics all up-to-date.

feel free to re-open (e.g. if you want to track the preventative work)
