### ISSUE TITLE
spanner: Nullable type support bug

### ISSUE THREAD

**Issue by arminm** [googleapis/google-cloud-go#1770]
**Client**

Spanner v1.2.0 added this feature: fbe1038431742623104ab8a3b44345f7866de5cb
Requested by this Issue: #1684

I gave it a try by converting a `spanner.NullTime` to `*time.Time` and reading from Spanner works, but writing to spanner fails with:
```
spanner: code = "InvalidArgument", desc = "client doesn't support type *time.Time"
```

**Environment**

Go v1.13

**Code**

e.g.
```go
type Model struct {
  expiry *time.Time `spanner:"Expiry"`
}
```

**Expected behavior**

should set `expiry` to `nil` for Null times on reads
should set `Expiry` to `Null` for `nil` times on writes

**Actual behavior**

Sets `expiry` to `nil` on for Null times on reads
Does NOT set `Expiry` to `Null` for `nil` times on write

**Comment by arminm** [comment]
@tbpg may i ask why this issue is being labelled as "feature request" instead of a bug? The new feature has already been added but it doesn't work as expected.

**Comment by olavloite** [comment]
https://code-review.googlesource.com/c/gocloud/+/51491
