### ISSUE TITLE
bigquery: Implement Integer Range Partitioning

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-go#1771]
This is a tracking FR for implementing the Integer Range Partitioning functionality within the
BigQuery API. 

Integer range partitioning supports partitioning a table based on the values in a specified integer column, and divides the table using start, stop, and interval values.  A table can only support a single partitioning specification, so users can choose either integer partitioning or time-based partitioning, but not both.  Clustering is independent of partitioning and works with both.

More implementation details about this API are shared directly with library
maintainers. Please contact shollyman for questions.

**Comment by shollyman** [comment]
Added https://code-review.googlesource.com/c/gocloud/+/45890
