### ISSUE TITLE
spannertest: Support CommitTimestamp

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#1774]
**Is your feature request related to a problem? Please describe.**
Thanks to https://github.com/googleapis/google-cloud-go/issues/1727 we are successfully using `spannertest` to unit test our resource APIs. However, we must refrain from using commit timestamps for e.g. update timestamps, since spannertest does not yet support this.

**Describe the solution you'd like**
Add support for commit timestamps to `spannertest`.

**Describe alternatives you've considered**
Keep relying on `time.Now()` and equivalents for commit timestamps.

**Comment by dsymonds** [comment]
https://code-review.googlesource.com/c/gocloud/+/51710

**Comment by odsod** [comment]
@dsymonds Nice one!

**Comment by dsymonds** [comment]
Note that the implementation is a little buggy in the presence of racing transactions; the commit timestamps aren't guaranteed to be monotonic (though they will be unique). I'm preparing a change to fix that, but thought I should give you a heads up in case you rely on that property.

**Comment by dsymonds** [comment]
The fix for the latter is now submitted as ee18a51, so update to that if you are depending on commit timestamps being monotonic.
