### ISSUE TITLE
datastore: Fields marked as 'noindex' are not saved by Put()

### ISSUE THREAD

**Issue by kirakira** [googleapis/google-cloud-go#1775]
**Client**

Datastore

**Environment**

Reproduced in both local environment with Datastore Emulator and App Engine.

**Code**

```go
package main

import (
	"context"
	"os"

	"cloud.google.com/go/datastore"
)

type MyType struct {
	Data1 string `datastore:"noindex"`
	Data2 string `datastore:"noindex"`
}

func Put(ctx context.Context, client *datastore.Client, m *MyType) *datastore.Key {
	key, err := client.Put(ctx, datastore.IncompleteKey("MyType", nil), m)
	if err != nil {
		panic(err)
	}
	return key
}

func Get(ctx context.Context, client *datastore.Client, key *datastore.Key) *MyType {
	var m MyType
	if err := client.Get(ctx, key, &m); err != nil {
		panic(err)
	}
	return &m
}

func main() {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, os.Getenv("GOOGLE_CLOUD_PROJECT"))
	if err != nil {
		panic(err)
	}

	m := MyType{
		Data1: "hello",
	}
	key := Put(ctx, client, &m)
	loaded := Get(ctx, client, key)

	if loaded.Data1 != "hello" {
		panic("Data1 not saved")
	}
}
```

**Expected behavior**

Program does not panic.

**Actual behavior**

panic: Data1 not saved

goroutine 1 [running]:
main.main()
	/tmp/test/test.go:45 +0x1a2
exit status 2

**Additional context**

The struct type needs to have at least 2 fields marked as 'noindex' in order to reproduce.

**Comment by kirakira** [comment]
Figured it out - I missed a comma in the definition: it should be `datastore:",noindex"`, rather than `datastore:"noindex"`.

**Comment by tbpg** [comment]
Ahh. Thank you for following up! Glad you got it figured out.

For others reading this, without the comma, `datastore:"noindex"` names the field `noindex` in Datastore. The comma makes it so `noindex` is a modifier, not the name to use.
