### ISSUE TITLE
spanner: Session leakage when using ApplyAtLeastOnce

### ISSUE THREAD

**Issue by lhecker** [googleapis/google-cloud-go#1776]
**Client**

`cloud.google.com/go/spanner`

**Environment**

Alpine Docker on GKE

**Code**

e.g.
```go
package main

import (
	"context"

	"cloud.google.com/go/spanner"
)

func main() {
	client, _ := spanner.NewClient(context.Background(), "example-project-name")

	// Assuming: CREATE TABLE foobar (column INT64) PRIMARY KEY (column)
	mutations := []*spanner.Mutation{
		spanner.Insert("foobar", []string{"column"}, []interface{}{1234}),
	}

	// BUG: This will never complete due to the session leakage
	for i := 0; i < 1000; i++ {
		client.Apply(context.Background(), mutations, spanner.ApplyAtLeastOnce())
	}
}
```

**Expected behavior**

The above code completes.

**Actual behavior**

The above code never completes.

**Screenshots**

Before/After on a test instance of a service with and later on without `spanner.ApplyAtLeastOnce()`:
![Screenshot 2020-02-12 at 17 42 45](https://user-images.githubusercontent.com/2256941/74360970-55688d00-4dc6-11ea-8b79-c99b2b6cde4e.png)

**Additional context**

`sh.recycle()` is missing here in case it's not a NotFound error: https://github.com/googleapis/google-cloud-go/blob/ef02dafeb6b3510dde7bd3672de66ffe688a96cf/spanner/transaction.go#L1034-L1038

A patchset has been submitted here: https://code-review.googlesource.com/c/gocloud/+/51890

**Comment by lhecker** [comment]
Would it be possible to tag this as `spanner/v1.2.1`? 🙂

**Comment by olavloite** [comment]
CC @hengfengli @skuruppu

**Comment by hengfengli** [comment]
I'll do a release.
