### ISSUE TITLE
all: remove last uses of gtransport.Dial

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1777]
```
$ git grep transport.Dial | grep -v DialPool | grep -v test | cut -d: -f1 | sort | uniq
asset/v1beta1/asset_client.go
automl/apiv1/auto_ml_client.go
automl/apiv1beta1/auto_ml_client.go
automl/apiv1beta1/prediction_client.go
automl/apiv1/prediction_client.go
bigquery/datatransfer/apiv1/data_source_client.go
cloudbuild/apiv1/cloud_build_client.go
containeranalysis/apiv1/container_analysis_client.go
container/apiv1/cluster_manager_client.go
grafeas/apiv1/grafeas_client.go
iam/admin/apiv1/iam_client.go
pubsub/apiv1/publisher_client.go
pubsub/apiv1/subscriber_client.go
talent/apiv4beta1/application_client.go
talent/apiv4beta1/company_client.go
talent/apiv4beta1/completion_client.go
talent/apiv4beta1/event_client.go
talent/apiv4beta1/job_client.go
talent/apiv4beta1/profile_client.go
talent/apiv4beta1/tenant_client.go
```

@shollyman re: bigquery/datatransfer/apiv1/data_source_client: "we can probably just remove it"

**Comment by noahdietz** [comment]
```
automl/apiv1/auto_ml_client.go
automl/apiv1beta1/auto_ml_client.go
automl/apiv1beta1/prediction_client.go
automl/apiv1/prediction_client.go
pubsub/apiv1/publisher_client.go
pubsub/apiv1/subscriber_client.go
talent/apiv4beta1/application_client.go
talent/apiv4beta1/company_client.go
talent/apiv4beta1/completion_client.go
talent/apiv4beta1/event_client.go
talent/apiv4beta1/job_client.go
talent/apiv4beta1/profile_client.go
talent/apiv4beta1/tenant_client.go
```

These will be handled by moving to microgenerator.

**Comment by noahdietz** [comment]
`asset/v1beta1/asset_client.go`

This client should be removed, it doesn't conform to `apiv` prefixing and was added accidentally at some point.

**Comment by broady** [comment]
Any ETA on that, @noahdietz? Primarily concerned about `pubsub/apiv1` which is used by hand-written `pubsub` client, which uses pooling by default.

**Comment by broady** [comment]
Blocks https://github.com/googleapis/google-api-go-client/issues/441

**Comment by noahdietz** [comment]
`pubsub` and `automl` have CLs open internally to configure their protos. They are under review by the API teams. I can push on them.

The `talent` microgen migration results in a client lib breaking change and the API team requested a different client lib breaking change in response to the first one, which requires work on the generator. We're close to committing to it, but need to sync up with the API team first.

**Comment by noahdietz** [comment]
```
cloudbuild/apiv1/cloud_build_client.go
containeranalysis/apiv1/container_analysis_client.go
container/apiv1/cluster_manager_client.go
grafeas/apiv1/grafeas_client.go
iam/admin/apiv1/iam_client.go
```

These aren't generated anymore and require manual work. I have little context on why they aren't generated anymore.

**Comment by broady** [comment]
Current list as of Feb 26, 2020:

Moving to new generator soon:
```
automl/apiv1/auto_ml_client.go
automl/apiv1beta1/auto_ml_client.go
automl/apiv1beta1/prediction_client.go
automl/apiv1/prediction_client.go
```

Fixed soon due to migration to microgenerator:
```
pubsub/apiv1/publisher_client.go
pubsub/apiv1/subscriber_client.go
```

Stale/not generated anymore (per comment above):
```
cloudbuild/apiv1/cloud_build_client.go
containeranalysis/apiv1/container_analysis_client.go
container/apiv1/cluster_manager_client.go
grafeas/apiv1/grafeas_client.go
iam/admin/apiv1/iam_client.go
```

@shollyman: can we really remove this? It doesn't have "alpha" or "beta" in the path and there's no doc comment saying it's experimental.
```
bigquery/datatransfer/apiv1/data_source_client.go
```

**Comment by broady** [comment]
Current list as of March 3, 2020:
```
automl/apiv1/auto_ml_client.go
automl/apiv1/prediction_client.go
automl/apiv1beta1/auto_ml_client.go
automl/apiv1beta1/prediction_client.go
bigquery/datatransfer/apiv1/data_source_client.go
cloudbuild/apiv1/cloud_build_client.go
container/apiv1/cluster_manager_client.go
containeranalysis/apiv1/container_analysis_client.go
grafeas/apiv1/grafeas_client.go
iam/admin/apiv1/iam_client.go
```

Pub/Sub was the last API blocking [CL 50573](https://code-review.googlesource.com/c/google-api-go-client/+/50573)

**Comment by codyoss** [comment]
Is there more to do here still?

**Comment by broady** [comment]
I believe there's no change since my comment on March 2.
