### ISSUE TITLE
spannertest: Support reading with ranges

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#1779]
**Is your feature request related to a problem? Please describe.**

We are successfully using `spannertest` to unit test our [Create](https://aip.dev/133), [Get](https://aip.dev/131), [Update](https://aip.dev/134) and [Delete](https://aip.dev/135) standard methods, but we are unable to use it for unit testing [List](https://aip.dev/132), since reading with ranges is not yet supported.

```
spanner: code = "Unknown", desc = "rpc error: code = Unknown desc = reading with ranges not supported"
```

**Describe the solution you'd like**

Support reading with key ranges, for example when using a [KeyRange](https://godoc.org/cloud.google.com/go/spanner#KeyRange) and a limit through the [ReadWithOptions](https://godoc.org/cloud.google.com/go/spanner#ReadOnlyTransaction.ReadWithOptions) API.

**Describe alternatives you've considered**

Not unit test List endpoints and rely only on integration testing.

**Comment by tbpg** [comment]
cc @dsymonds (can't assign for some reason).

**Comment by dsymonds** [comment]
https://code-review.googlesource.com/c/gocloud/+/51970

**Comment by odsod** [comment]
@dsymonds Hero! :muscle:
