### ISSUE TITLE
bigtable: Client.Close() returns error with emulator as of v0.53.0

### ISSUE THREAD

**Issue by erock2112** [googleapis/google-cloud-go#1780]
**Client**

bigtable

**Environment**

Debian Linux

**Code**

```go
package main

import (
	"context"
	"cloud.google.com/go/bigtable"
)

func main() {
	client, err := bigtable.NewClient(context.Background(), "test-project", "test-instance")
	if err != nil {
		panic(err)
	}
	if err := client.Close(); err != nil {
		panic(err)
	}
}
```

**Expected behavior**

No error

**Actual behavior**

panic: rpc error: code = Canceled desc = grpc: the client connection is closing (and 2 other errors)

goroutine 1 [running]:
main.main()
        /path/to/repro.go:15 +0xd7
exit status 2

**Additional context**

The above program runs with no errors with these versions in go.mod:
	cloud.google.com/go v0.52.0
	cloud.google.com/go/bigtable v1.2.0
	cloud.google.com/go/datastore v1.0.0
	google.golang.org/grpc v1.27.0

It fails with these versions:
	cloud.google.com/go v0.53.0
	cloud.google.com/go/bigtable v1.3.0
	cloud.google.com/go/datastore v1.1.0
	google.golang.org/grpc v1.27.1

This is blocking our automated process which updates go.mod, since our tests use the BigTable emulator.

**Comment by broady** [comment]
it'll be fixed on the next tag of `google.golang.org/api/transport/grpc`. should be this week sometime.

**Comment by broady** [comment]
`go get google.golang.org/api@latest`
