### ISSUE TITLE
bigtable: int64 overflow in Timestamp.Time()

### ISSUE THREAD

**Issue by kuzmiigo** [googleapis/google-cloud-go#1784]
**Client**

cloud.google.com/go/bigtable v1.3.0

**Environment**

Ubuntu 18.04

**Code**

`Timestamp.Time()` converts timestamp in microseconds to `time.Time` by multiplying the value (microseconds) by 1000 and calling `time.Unix(sec, nsec)` (with `sec` always set to 0). This causes an overflow with large timestamps (for example, we use reverse timestamps sometimes). Instead, `Timestamp.Time()` could separate microseconds into seconds and nanoseconds and use these to call `time.Unix(sec, nsec)`.

```go
package main

import (
	"fmt"
	"math"
	"time"

	"cloud.google.com/go/bigtable"
)

func main() {
	// a timestamp in microseconds
	var ts bigtable.Timestamp = 1487227360611000
	// reverse timestamp
	var rts bigtable.Timestamp = math.MaxInt64 - ts

	// convert timestamps in microseconds to time.Time
	// by separating seconds and nanoseconds
	expectedTime := time.Unix(int64(ts)/1e6, int64(ts)%1e6*1e3)
	expectedReverse := time.Unix(int64(rts)/1e6, int64(rts)%1e6*1e3)

	// compare manual conversion to Timestamp.Time()
	fmt.Printf("%19v\t%v\t%v\n", ts, ts.Time(), expectedTime)
	fmt.Printf("%19v\t%v\t%v\n", rts, rts.Time(), expectedReverse)
}
```

**Expected behavior**

Expected output:
```
   1487227360611000	2017-02-16 06:42:40.611 +0000 GMT	2017-02-16 06:42:40.611 +0000 GMT
9221884809494164807	294199-11-23 21:18:14.164807 +0000 GMT	294199-11-23 21:18:14.164807 +0000 GMT
```

**Actual behavior**

Output:
```
   1487227360611000	2017-02-16 06:42:40.611 +0000 GMT	2017-02-16 06:42:40.611 +0000 GMT
9221884809494164807	1922-11-15 17:17:19.388999 +0000 GMT	294199-11-23 21:18:14.164807 +0000 GMT
```

**Additional context**

`cbt` shows the cell timestamp from above as `1922/11/15-17:17:19.388192`, although it orders cell versions correctly (by timestamp (int64) value descending).

**Fix**

I would propose to replace
```go
func (ts Timestamp) Time() time.Time { return time.Unix(0, int64(ts)*1e3) }
```
with
```go
func (ts Timestamp) Time() time.Time { return time.Unix(int64(ts)/1e6, int64(ts)%1e6*1e3) }
```
or (more readable)
```go
func (ts Timestamp) Time() time.Time {
	seconds := int64(ts) / 1e6
	milliseconds := int64(ts) % 1e6
	return time.Unix(seconds, milliseconds*1e3)
}
```

**Comment by tbpg** [comment]
@billyjacobson, will you take a look at this?

**Comment by tbpg** [comment]
(Can't assign for some reason.)

**Comment by kolea2** [comment]
Hi, thanks for raising this! Quick update, I've just submitted a proposed fix for this.
