### ISSUE TITLE
firestore: could not find service account when ran in cloud run

### ISSUE THREAD

**Issue by weeco** [googleapis/google-cloud-go#1785]
**Client**

Firestore

**Environment**

Docker Container deployed in Google Cloud Run

**Code**

```go
	client, err := firestore.NewClient(ctx, cfg.ProjectID, []option.ClientOption{})
	if err != nil {
		return nil, err
	}
```

**Expected behavior**

I am not entirely sure whether this issue belongs to Cloud Run or this repository. I am trying to deploy a cloud run service which uses Firestore. Therefore I've create a service account which is attached as service account for my cloud run deployment.

I expected that this service account is automatically mounted into the container and is used by the firestore client to authenticate against firestore. Unfortunately this does not work as I get the following log messages:

```
Service Account file does not exists!
{error: failed to create the firestore repo: cannot read credentials file: read /: is a directory, level: fatal, msg: failed to setup the API, ts: 2020-02-19T18:04:27.113Z}
```

**Actual behavior**

The service account could not be found apparently.

**Additional context**

----

I couldn't find any special options to create the firestore client so that it would use the service account which is attached to the cloud run instance. Am I missing something?

**Comment by codyoss** [comment]
Have you checkout out: https://cloud.google.com/run/docs/deploying? Seems like a cloud run thing more than firestore.

**Comment by weeco** [comment]
@codyoss can you pinpoint me at something more specific in that documentation? I couldn't find anything which would help me figuring out what my problem is.

Could you explain how firestore-go approaches if I don't set any further options? As far as I know it would look at the environment variable called "GOOGLE_APPLICATION_CRDENTIALS". If this is set it interprets this value as the path to a service account.

Is this right?

**Comment by codyoss** [comment]
The firestore client will auto detect `GOOGLE_APPLICATION_CREDENTIALS`, yes.

Questions:
- Are you using fully managed Cloud Run?
- Have you tried not attaching a service account just to see if that works? [By default](https://cloud.google.com/run/docs/using-gcp-services#connecting_to_services_in_code) I believe you should have access to resources in your project.

**Comment by weeco** [comment]
@codyoss Yes I am using the fully managed cloud run. 

As suggested I have tried using the default service account, which indeed has Project Editor permissions (I checked that again). However that failed for the same reasons / log messages.

According to the documentation here: https://cloud.google.com/run/docs/securing/service-identity this is indeed supposed to work. I believe you should be able to easily reproduce this in your own Google project.

It would just require a docker image which tries to create a Firestore client. If you want to I can prepare that docker image and send you the code along?

**Comment by tbpg** [comment]
Are you still setting the `GOOGLE_APPLICATION_CREDENTIALS` env var? You shouldn't have to set that when you're deploying to any GCP service -- perhaps that's what's causing problems when trying to use the default service account.

**Comment by weeco** [comment]
No I don't explicitly set this (or any other environment variable). From the CloudRun UI:

![image](https://user-images.githubusercontent.com/23424570/75044663-54b8b080-54c2-11ea-9302-deccf64afde6.png)

**Comment by tbpg** [comment]
Very interesting... To summarize:
* default service account,
* not setting `GOOGLE_APPLICATION_CREDENTIALS`, and
* not specifying the credentials file when creating the client.

Not sure what the issue would be.

What version of the module are you using?

**Comment by weeco** [comment]
Since I was not able to create a tiny service which has the same problem and therefore should be reproducible for you I assume it is an issue with my code until proven the opposite. Indeed I was able to connect to firestore there.

Thanks for your efforts so far

**Comment by tbpg** [comment]
Let us know if you end up figuring it out!
