### ISSUE TITLE
storage: scheme unchanged in NewClient with option.WithEndpoint

### ISSUE THREAD

**Issue by sachinagada** [googleapis/google-cloud-go#1791]
**Client**

storage

**Code**

e.g.
```go

storageClient, err := storage.NewClient(ctx, option.WithoutAuthentication(), option.WithEndpoint("http://127.0.0.1:8080"))


```

**Expected behavior**

A *storage.Client struct with scheme set to "http"

**Actual behavior**

A *storage.Client struct with scheme set to "https"

**Additional context**

When the WithEndpoint option is used, the rawService.BasePath and readHost are properly configured but the scheme isn't changed accordingly.

**Comment by codyoss** [comment]
I have a feeling this affects more than just storage. Will take a look into this tomorrow. Thanks for the rpeort.

**Comment by codyoss** [comment]
As a workaround for now if you set the env var `STORAGE_EMULATOR_HOST` I think you will see the desired behavior.

**Comment by codyoss** [comment]
`option.WithoutAuthentication()` is an option for not providing creds when talking to public resources for instance. The schema you are referring to is around to support using emulators like I mentioned in the comment above. I believe that setting that env var is the right thing to do for your use case. Let us know if you have any more questions.
