### ISSUE TITLE
spannertest: Support read timestamps

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#1796]
**Is your feature request related to a problem? Please describe.**

Thanks to d4674f1362604d5f0f3891fdc4f3a00295ab0d5d we are able to unit test our standard List methods with spannertest. However, we are unable to include the transaction's read timestamp in the page token (to ensure a consistent view of results across calls), because spannertest does not yet support read timestamps.

After reading a page of results, we call:

```go
ts, err := tx.Timestamp()
if err != nil {
	return err
}
```

which gives the error:

```
spanner: code = "Internal", desc = "read timestamp is unavailable"
```

**Describe the solution you'd like**

Add support for read timestamps to spannertest.

**Describe alternatives you've considered**

Not supporting read timestamps in page tokens.

**Comment by tbpg** [comment]
cc @dsymonds (can't assign).

**Comment by dsymonds** [comment]
This might be tricky to support correctly, but might be plausible to support enough to be useful. Can you explain in a bit more detail how you'd use the read timestamp? Is it just to bust some sort of cache or state for paging, so you'd just re-query if previous pages came from an older read timestamp?

I could imagine simply returning the last issued commit timestamp on any reads, which would get bumped on any mutation. Would that suffice?

**Comment by odsod** [comment]
@dsymonds If it's a lot of work to support, I think it might not be worth the effort right now. For us, it's simply to give the requester a consistent view of a collection while paging. On our end, it's not worth persisting the last issued commit timestamp for.

No worries if we close this issue as "won't fix" to focus on other low hanging fruit instead. :smiley_cat:

**Comment by dsymonds** [comment]
What did you make of my simplified proposal, namely that of returning the timestamp of the last commit? That wouldn't be a lot of work.

**Comment by odsod** [comment]
@dsymonds That would work for our use case!
