### ISSUE TITLE
Query on how google compile its go-file

### ISSUE THREAD

**Issue by edwardsujono** [googleapis/google-cloud-go#1799]
Hi" not sure where to put this query, so I just put it under the issues.

Right now I am playing with delve debugger,
On delve we should compile the golang code with this flag
```
-gcflags="all=-N -l"
```
which from my understanding will use the non-optimized format i.e. DWARF, 
so that we can change the queried function name to its address location.
The prolem with this non-optimized code is it slows down the performance by 2 - 3 times without doing anything. 

How could you compile golang code without affecting its performance

**Comment by tbpg** [comment]
Unfortunately, I don't _think_ there is a way to use Delve right now with optimized binaries. You might have better luck asking at https://github.com/go-delve/delve or on StackOverflow. However, you can (and should) enable tracing and metrics in prod. Hopefully you can debug locally when you need a debugger.

This repo is for the Go client libraries for Google Cloud, so I'm going to close this. But, good luck!
