### ISSUE TITLE
testing: split output sponge_log.xml files into module directories

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1801]
Right now, we output a single `sponge_log.xml` file to a directory named `tests`. That directory is then what shows up in build results. We should split that `sponge_log.xml` file into one for each module and output into each module's directory. That way, when we look at results, it's clear which modules have passed and which have failed.

Given we have teams of people where certain modules are more or less relevant, this should speed up debugging time when someone needs to look at test results.

Related to #1782. But, this came up again with @tritone, so I think it's worth fixing.

@tritone or @codyoss, would you mind doing this?

**Comment by codyoss** [comment]
I can take care of that.

**Comment by tbpg** [comment]
Thank you!
