### ISSUE TITLE
profiler: provide bottom up view alternative to flame graph

### ISSUE THREAD

**Issue by noamhurwitz** [googleapis/google-cloud-go#1804]
**Is your feature request related to a problem? Please describe.**
I'd like to analyze CPU and memory profiles both from a top down view (as implemented by the flame graph), and from a bottom up view showing most resource intensive calls on aggregate (as a contrived example, it would show "append" using a total of 0.6% of CPU time for the whole service).

**Describe the solution you'd like**
An option in the UI to toggle back and forth between a flame graph and a bottom up view.

**Describe alternatives you've considered**
None.

**Additional context**
Xoogler, used this feature a lot in continuous pprof.

**Comment by nolanmar511** [comment]
Our team had some discussion on this. We think using Stackdriver Profiler's focus table (the list icon to the left of the filter bar) to identify functions with high self values, then focusing on the function of interest (by clicking on it in the focus table) should be equivalent to the "top down" view should provide functionality that is sufficiently similar to the top-down view to be used in its place. I'm thinking this workflow should be pretty similar in terms of number of clicks to get at the same information.

Let us know if this works. 
I'm marking this as close for now.

**Comment by noamhurwitz** [comment]
Ah I hadn't seen that, but I agree. Thank you!
