### ISSUE TITLE
spanner: provide column types in results

### ISSUE THREAD

**Issue by rakyll** [googleapis/google-cloud-go#1805]
The underlying proto contains ResultSetMetadata.RowType for results returned from the API but spanner.Row or spanner.RowIterator are not surfacing them to the user. I'm trying to put together a "database/sql" driver for Spanner and without the column type it is not possible. 

/cc @tbpg

**Comment by rakyll** [comment]
`spanner.GenericColumnValue` seems to be doing what I want to do.

**Comment by hengfengli** [comment]
Hi @rakyll, I think currently, using `spanner.GenericColumnValue` is right choice when you don't know in advance what column type to expect. 

In client library, we have the type info in `Row.fields[i].Type`, which returns `*sppb.Type` (`sppb "google.golang.org/genproto/googleapis/spanner/v1"`). However, the type info is not exposed. If we want to expose this info, we might need to add the following code in line 167 of `row.go` after `ColumnNames()` method: 

```go
// ColumnRawTypes returns all column raw types of the row.
func (r *Row) ColumnRawTypes() []*sppb.Type {
	var n []string
	for _, c := range r.fields {
		n = append(n, c.Type)
	}
	return n
}
```

**Comment by hengfengli** [comment]
Hi @rakyll , do you think whether or not the proposed method is a solution for your problem? or have you already solved your problem? 

Is this still a feature that you would like us to add?

**Comment by rakyll** [comment]
`spanner.GenericColumnValue` worked for my case. I can close this issue, thanks.

**Comment by apstndb** [comment]
I want to see `ResultSetMetadata.RowType` even when there are empty results.
It is available using raw API and `gcloud` but unavailable using `spanner.GenericColumnValue` because there is no Row.
```
$ gcloud spanner databases execute-sql ${DATABASE_ID} --sql='SELECT * FROM (SELECT 1) LIMIT 0' --format=yaml
metadata:
  rowType:
    fields:
    - type:
        code: INT64
  transaction: {}
```

I believe it is useful to write a generic client application.

**Comment by olavloite** [comment]
It does seem that the Go client does not return the metadata of a result set, which makes it impossible to determine the column names and types of an empty result set.
