### ISSUE TITLE
testing: compile and possibly test GoogleCloudPlatform/golang-samples

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1806]
https://github.com/GoogleCloudPlatform/golang-samples is the main source of Go samples on cloud.google.com. We should make sure it continues to work (or at least compile) with all changes to cloud.google.com/go.

Theoretically, we can add another SCM to the Kokoro config, have it compile, `go mod edit` to update dependencies, then make sure we can compile (and possibly test).

**Comment by codyoss** [comment]
We are now currently building the samples on presubmits. There is still more work to be done to run the tests on continuous.

**Comment by codyoss** [comment]
Closing this out as I think compiling has served us well for now. If we have breakages we are not being caught with this method down the road we should evaluate and consider testing as well.
