### ISSUE TITLE
spannertest: add support for indexes

### ISSUE THREAD

**Issue by jrmeinride** [googleapis/google-cloud-go#1808]
**Is your feature request related to a problem? Please describe.**
We like to use spannertest for unit testing our code. Since we use indexes for some services, we cannot test those services as well as we would like to.

**Describe the solution you'd like**
I would be happy if we could use indexes with the STORING clause in spannertest.

**Describe alternatives you've considered**
We have considered using "home grown" mocks, but spannertest would be far superior.

**Additional context**
None

**Comment by tbpg** [comment]
cc @dsymonds

**Comment by dsymonds** [comment]
Can you clarify what's actually missing for you? spannertest/spansql supports CREATE INDEX with the STORING clause, though it doesn't actually use the indexes for serving queries.

**Comment by jrmeinride** [comment]
We have a spanner table that uses indexes, like this:
```
CREATE TABLE some_table (
  index_column STRING(MAX) NOT NULL,
  thekey STRING(MAX) NOT NULL,
  thetime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  somevalue INT64 NOT NULL,
) PRIMARY KEY (thekey, thetime DESC);
CREATE INDEX some_index ON some_table(index_column, thetime DESC) STORING (somevalue);

```
In the subsequent code we use something sort of like this (tried to anonymize it):
```
--- snip ---
_, err := spannerclient.ReadWriteTransaction(ctx, func(
	ctx context.Context,
	tx *spanner.ReadWriteTransaction,
) error {
	var lastRow RowType
	readOptions := &spanner.ReadOptions{
		Limit: 1,
		Index = "some_index",
	}
	err := tx.ReadWithOptions(
		ctx,
		"some_table",
		spanner.Key{"index_prefix"}.AsPrefix(),
		allColumns,
		readOptions,
	).Do(func(row *spanner.Row) error {
		if err := lastRow.UnmarshalRow(row); err != nil {
			...
		}
		return nil
	})
--- snip ---

```
The error message that I get is this:
```
index reads (\"index_column\") not supported
```
Looking at the code for spannertest I find that it originates from this function in `inmem.go`:
```
func (s *server) StreamingRead(req *spannerpb.ReadRequest, stream spannerpb.Spanner_StreamingReadServer) error {
```
One odd thing is that the error points to the column, rather than the index. This is unexpected. When I run the code agains our spanner table in the test environment everything works nicely, which leads me to believe that the code is, at least partly, correct.

I hope that I did not inadvertently butcher the code when trying to anonymize it.

**Comment by dsymonds** [comment]
Okay, thanks. That clears things up.

I think I can just remove the error message, since the simulated reads in spannertest don't use indexes at all but can still yield the correct result.

**Comment by groeney** [comment]
can you verify that the reads still yield correct results?

**Comment by groeney** [comment]
actually, i can confirm that this is not WAI and ReadUsingIndex returns incorrect results.
