### ISSUE TITLE
logging: concurrent map iteration and map write - WriteLogEntriesRequest

### ISSUE THREAD

**Issue by jshore1296** [googleapis/google-cloud-go#1810]
**Client**

Logging (currently using v0.45.1)

**Environment**

Appengine Flexible

**Actual behavior**

We are seeing app crashes due to concurrent map accesses.  Stacktrace is below

```
fatal error: concurrent map iteration and map write

  goroutine 1924307 [running]:

  runtime.throw(0x1dbd199, 0x26)
  	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000315350 sp=0xc000315320 pc=0x42f212
  runtime.mapiternext(0xc00b105e00)
  	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0003153d8 sp=0xc000315350 pc=0x410bc7
  reflect.mapiternext(0xc00b105e00)
  	/usr/local/go/src/runtime/map.go:1349 +0x2b fp=0xc0003153f0 sp=0xc0003153d8 pc=0x411a9b
  reflect.Value.MapKeys(0x19f9280, 0xc007406298, 0x195, 0x19f9280, 0xc007406298, 0x195)
  	/usr/local/go/src/reflect/value.go:1150 +0x109 fp=0xc000315468 sp=0xc0003153f0 pc=0x48bb59
  github.com/golang/protobuf/proto.makeMapMarshaler.func2(0xc007406298, 0x1, 0x2)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:2319 +0xce fp=0xc000315548 sp=0xc000315468 pc=0x78174e
  github.com/golang/protobuf/proto.(*marshalInfo).size(0xc00172e150, 0xc007406240, 0x319)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:183 +0xa1 fp=0xc0003155b0 sp=0xc000315548 pc=0x758721
  github.com/golang/protobuf/proto.makeMessageSliceMarshaler.func1(0xc00aa57fa0, 0x1, 0x63)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:2248 +0x75 fp=0xc000315600 sp=0xc0003155b0 pc=0x7810b5
  github.com/golang/protobuf/proto.(*marshalInfo).size(0xc00052e690, 0xc00aa57f80, 0x3423320)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:183 +0xa1 fp=0xc000315668 sp=0xc000315600 pc=0x758721
  github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(0x3423320, 0x23cb700, 0xc00aa57f80, 0x7fd4a39b6188)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:125 +0x67 fp=0xc000315698 sp=0xc000315668 pc=0x7582c7
  google.golang.org/genproto/googleapis/logging/v2.(*WriteLogEntriesRequest).XXX_Size(0xc00aa57f80, 0x23cb700)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/genproto/googleapis/logging/v2/logging.pb.go:176 +0x43 fp=0xc0003156c8 sp=0xc000315698 pc=0x8dc613
  github.com/golang/protobuf/proto.(*Buffer).Marshal(0xc004936c98, 0x23cb700, 0xc00aa57f80, 0xc004f1c000, 0xc00aa57f80)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/golang/protobuf/proto/table_marshal.go:2740 +0x85 fp=0xc0003157a0 sp=0xc0003156c8 pc=0x76bc65
  google.golang.org/grpc/encoding/proto.marshal(0x1cc6040, 0xc00aa57f80, 0xc004936c90, 0x0, 0x0, 0xc0115f0000, 0x1b17200, 0x1)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/encoding/proto/proto.go:59 +0xe2 fp=0xc0003157e8 sp=0xc0003157a0 pc=0x7d07f2
  google.golang.org/grpc/encoding/proto.codec.Marshal(0x1cc6040, 0xc00aa57f80, 0x0, 0x1, 0xc0115f0050, 0x0, 0x203000)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/encoding/proto/proto.go:74 +0xad fp=0xc000315868 sp=0xc0003157e8 pc=0x7d093d
  google.golang.org/grpc/encoding/proto.(*codec).Marshal(0x3444048, 0x1cc6040, 0xc00aa57f80, 0x0, 0xc000315970, 0x40d869, 0xc00221d5a0, 0x20)
  	<autogenerated>:1 +0x46 fp=0xc0003158b0 sp=0xc000315868 pc=0x7d11a6
  google.golang.org/grpc.encode(0x7fd4a3915630, 0x3444048, 0x1cc6040, 0xc00aa57f80, 0xc00b85e4b0, 0xc0099cc000, 0x7fd4a3a4bd98, 0x0, 0x0)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/rpc_util.go:543 +0x52 fp=0xc000315910 sp=0xc0003158b0 pc=0x83c472
  google.golang.org/grpc.prepareMsg(0x1cc6040, 0xc00aa57f80, 0x7fd4a3915630, 0x3444048, 0x0, 0x0, 0x0, 0x0, 0xc002dcfa30, 0xc022b85200, ...)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/stream.go:1501 +0x85 fp=0xc0003159b0 sp=0xc000315910 pc=0x847025
  google.golang.org/grpc.(*clientStream).SendMsg(0xc002be27e0, 0x1cc6040, 0xc00aa57f80, 0x0, 0x0)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/stream.go:681 +0x150 fp=0xc000315b28 sp=0xc0003159b0 pc=0x843540
  google.golang.org/grpc.invoke(0x23daf00, 0xc022b85020, 0x1ddcff8, 0x33, 0x1cc6040, 0xc00aa57f80, 0x1bf57e0, 0xc00221d380, 0xc00045b880, 0x0, ...)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/call.go:70 +0xe7 fp=0xc000315bb0 sp=0xc000315b28 pc=0x82f2a7
  google.golang.org/grpc.(*ClientConn).Invoke(0xc00045b880, 0x23daf00, 0xc022b85020, 0x1ddcff8, 0x33, 0x1cc6040, 0xc00aa57f80, 0x1bf57e0, 0xc00221d380, 0x0, ...)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/grpc/call.go:37 +0x1b4 fp=0xc000315c60 sp=0xc000315bb0 pc=0x82f034
  google.golang.org/genproto/googleapis/logging/v2.(*loggingServiceV2Client).WriteLogEntries(0xc000010d90, 0x23daf00, 0xc022b85020, 0xc00aa57f80, 0x0, 0x0, 0x0, 0x10, 0x20, 0xc00221d360)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/genproto/googleapis/logging/v2/logging.pb.go:865 +0xd2 fp=0xc000315ce8 sp=0xc000315c60 pc=0x8df0a2
  cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries.func1(0x23daf00, 0xc022b85020, 0x1f27cb8, 0x0, 0x0, 0x0, 0xc002dcfdb0, 0x40e0f8)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/cloud.google.com/go/logging/apiv2/logging_client.go:163 +0x84 fp=0xc000315d50 sp=0xc000315ce8 pc=0x8e9a24
  github.com/googleapis/gax-go/v2.invoke(0x23daf00, 0xc022b85020, 0xc00221d340, 0x1f27cb8, 0x0, 0x0, 0x0, 0x1f290d8, 0x40e0f8, 0x20)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/googleapis/gax-go/v2/invoke.go:70 +0x90 fp=0xc000315dc0 sp=0xc000315d50 pc=0x84d5e0
  github.com/googleapis/gax-go/v2.Invoke(0x23daf00, 0xc022b85020, 0xc00221d340, 0xc0022f5040, 0x1, 0x1, 0x0, 0x0)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/github.com/googleapis/gax-go/v2/invoke.go:48 +0xf6 fp=0xc000315e38 sp=0xc000315dc0 pc=0x84d386
  cloud.google.com/go/logging/apiv2.(*Client).WriteLogEntries(0xc001a05650, 0x23daf00, 0xc022b85020, 0xc00aa57f80, 0x0, 0x0, 0x0, 0xc00035c728, 0x19304c0, 0xc002307620)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/cloud.google.com/go/logging/apiv2/logging_client.go:161 +0x1c8 fp=0xc000315eb0 sp=0xc000315e38 pc=0x8e8408
  cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc001b26f00, 0xc0213c3000, 0xd3, 0x100)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/cloud.google.com/go/logging/logging.go:819 +0x159 fp=0xc000315f30 sp=0xc000315eb0 pc=0x8efa69
  cloud.google.com/go/logging.(*Client).Logger.func2(0x19304c0, 0xc002307620)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/cloud.google.com/go/logging/logging.go:442 +0x5a fp=0xc000315f60 sp=0xc000315f30 pc=0x8f0a1a
  google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1(0xc001cf6240, 0x19304c0, 0xc002307620, 0x97, 0x29f43, 0xfbf)
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/api/support/bundler/bundler.go:272 +0xda fp=0xc000315fb0 sp=0xc000315f60 pc=0x8ec8da
  runtime.goexit()
  	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000315fb8 sp=0xc000315fb0 pc=0x45e681
  created by google.golang.org/api/support/bundler.(*Bundler).startFlushLocked
  	/go/src/github.com/pendo-io/pendo-appengine/vendor/google.golang.org/api/support/bundler/bundler.go:266 +0x12b
```

**Comment by codyoss** [comment]
@jshore1296 Thanks for the report. I was wondering if you could share a little more information to make this easier to reproduce. Some questions for you:
1. Could you please provide a snippet of code showing how to reproduce this?
2. Are you able to consistently reproduce this? Is it constant?
3. Can you run your tests with the race detector?

**Comment by jshore1296** [comment]
Hi Cody,

I'm still digging through our stacktrace to find the other goroutine involved.  This is running on an Appengine Flex service that does a lot of data processing with likely a few thousand goroutines running at a time.  We've never seen this in a test case and don't currently have code to reproduce it.  I'm currently trying to understand what map is being concurrently accessed and what code could possibly be writing to it.  

Sorry that's not much to go on, but if you're able to point me at possible answers to those questions I can keep working to get you more information.

**Comment by codyoss** [comment]
Are you using a `sync.Map` anywhere in your code?

**Comment by jshore1296** [comment]
Based on the stacktrace - it looks like the map being concurrently accessed is in the logging library.  I think it is the Labels map on the WriteLogEntriesRequest struct, which is not a sync.Map.

**Comment by jshore1296** [comment]
We did a code audit - we have one sync.Map, but it doesn't interact with the logging library in any way.

**Comment by codyoss** [comment]
Okay I only asked because I have seen an issue before where improperly copying a sync.Map can throw such an error. I am looking at some code but not much to go off of. The mention of `WriteLogEntriesRequest` in the trace deals with an `int` field.

**Comment by codyoss** [comment]
@jshore1296 Any update on your end from this?

**Comment by jshore1296** [comment]
We are still working on finding which goroutine is writing to the map in the log library.  We have a race detector enabled binary running and serving a small percentage of our traffic.

**Comment by codyoss** [comment]
Are you editing a single `WriteLogEntriesRequest` across goroutines?

**Comment by jshore1296** [comment]
Our code does not edit that struct at all.  However, I suspect that the logging library is editing that struct across goroutines.

**Comment by codyoss** [comment]
How are you logging in your application?

- `Log(e Entry)`
- `LogSync(ctx context.Context, e Entry) error`
- etc

**Comment by jshore1296** [comment]
https://github.com/pendo-io/appwrap/blob/master/aeloggingstackdriver.go is the interface we are using to send logs to stackdriver

**Comment by jshore1296** [comment]
We use Log() exclusively

**Comment by codyoss** [comment]
Out of curiosity have you tried to upgrade to the latest version to see if the issue persists?

**Comment by jshore1296** [comment]
We have not yet, since that would also update several other libraries that we use throughout our application.

I did look through the commits since 0.45.1 and it doesn't look like any of them would have fixed this issue.  There were only a few changes in logging.  But we may end up updating at some point to see if it helps.  

We opened an internal issue in the google enterprise support system at our TAM's direction, and I believe investigation is ongoing there as well.  So we are waiting for the results of that before making further changes.

**Comment by codyoss** [comment]
I ask not because of changes in this library, but changes happened in libraries that this one depends on. In this case, I was most curious about: `google.golang.org/api/support/bundler`. That is the mechanism that the async logs are sent and I know some work has been done in there since the version you are using. I don't think there are issues in the version you have, but it is worth trying eventually if need be.

I have looked over the logging library and have not found in instance where we are modifying any map. We simply pass it through to the backend service. 

Just fyi I was pinged on the internal issue as well.

**Comment by codyoss** [comment]
> We are still working on finding which goroutine is writing to the map in the log library. We have a race detector enabled binary running and serving a small percentage of our traffic.

I am sure the race detector will help us pinpoint this issue. Another useful debugging feature is setting `GOTRACEBACK=all`. This will dump of of the goroutines instead of just one.

**Comment by jshore1296** [comment]
We do have the other goroutines in the traceback dumped by fatal error.  None of them were writing to the map though, which is apparently a known issue.  That's why I enabled -race.

I've got a new version running this morning that has fewer, larger instances to try to make race conditions more likely.  I also patched an issue where we had some log messages larger than 256k that were getting dropped, so there might be some information in those that we were previously missing.

**Comment by jshore1296** [comment]
I updated the internal issue as well, but it looks like the majority of our dips on the instance chart are not due to this issue.  We only have the one documented occurrence of this so far.  Unclear on the cause of the other dips.

**Comment by codyoss** [comment]
Thanks for the update, let me know if there is anything more I can help you look into. I am especially curious if you are able to trip the race detector as I have been unable to reproduce this.

**Comment by codyoss** [comment]
@jshore1296 Is there anything actionable with this issue?

**Comment by jshore1296** [comment]
I don't think so at this time.  Thanks for going back and forth with me on this one.

**Comment by codyoss** [comment]
Thanks, I am going to close out this issue for now. If this does pop up again please feel free to reopen.
