### ISSUE TITLE
spanner: Marshaler / Unmarshaler implementations not included in latest release

### ISSUE THREAD

**Issue by rokane** [googleapis/google-cloud-go#1812]
**Client**

spanner

**Environment**

N.A

**Code**

This bug is with reference to a recent change to add the marshal / unmarshal json functions to the spanner null types. Related PR is included here: [spanner: add marshal/unmarshal json for nullable types](https://github.com/googleapis/google-cloud-go/commit/010956571f9064150d9f7eea8aa003d0d2ac407a)

The issue lies in the tag associated with the merge. Once merged, this was tagged and released under `storage/v1.6.0`. As a result, we are unable to import the code associated with the change as the latest spanner submodule tag does not include it.

**Expected behavior**

Running `go get -u cloud.google.com/go/spanner` should result in the changes included in the above PR being imported.

**Actual behavior**

The library which gets imported is `cloud.google.com/go/spanner v1.2.1` which was prior to the change being merged.

**Screenshots**
 
<img width="997" alt="Screen Shot 2020-03-02 at 11 41 18 am" src="https://user-images.githubusercontent.com/11910247/75637477-ca6b0c00-5c7a-11ea-9563-5490d4eecc00.png">

Code associated with latest version: https://github.com/googleapis/google-cloud-go/blob/spanner/v1.2.1/spanner/value.go

Code associated with current master / storage/1.6.0: https://github.com/googleapis/google-cloud-go/blob/master/spanner/value.go

**Comment by tbpg** [comment]
The `storage` tag does not affect the `spanner` module. They are separate modules that are versioned separately.

If you'd like to use a feature before it's tagged in a release, you can `go get cloud.google.com/go/spanner@master`, or replace master with the hash of the commit you want to use. The default is `@latest`, which means the latest tagged version _for that module_.

I'll also note, with modules, you probably don't want to use `go get -u` when upgrading modules. `go get` will take care of any other version changes that need to happen in your `go.mod` as a result of the new `spanner` version. `-u` will upgrade transitive dependencies, which may have surprising effects.

**Comment by rokane** [comment]
Ahhh okay. Apologies for that @tbpg and thanks so much for your help. I have gone ahead and updated that and have the latest code now. Happy to close this off.

Appreciate the fast response!!

**Comment by tbpg** [comment]
Glad you got it working! Let us know if anything else comes up.
