### ISSUE TITLE
spanner: ping() should use "SELECT 1" to keep sessions alive instead of calling GetSession. 

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#1816]
**Client**

spanner/v1.2.1

**Expected behavior**

Be consistent with Java client library to use "SELECT 1" to keep sessions alive instead of calling GetSession(). 

**Actual behavior**

Calling GetSession() for healthchecks. 

**Related code**

* https://github.com/googleapis/google-cloud-go/blob/8f5ae458328266edabccba1832251fdb91e34cd2/spanner/session.go#L432-L439
* https://github.com/googleapis/google-cloud-go/blob/3e5ef4404a0c98073e1cd35889e7200874ee59b0/spanner/session.go#L1188-L1199
* https://github.com/googleapis/google-cloud-go/blob/3e5ef4404a0c98073e1cd35889e7200874ee59b0/spanner/session.go#L1235-L1246

**Comment by hengfengli** [comment]
I will close this issue because `GetSession` is better than `SELECT 1` without calling the query engine.

**Comment by lhecker** [comment]
@hengfengli I'm currently reviewing the changes in the v1.5.0 release and I noticed that the CR for this issue has actually been merged into master: https://github.com/googleapis/google-cloud-go/commit/f2776fcc8ab7a19b3e48fae6da634838a285ec00

> I will close this issue because `GetSession` is better than `SELECT 1` without calling the query engine.

Is that statement no longer true?

**Comment by hengfengli** [comment]
@lhecker This is no longer true. We found that `SELECT 1` is actually better for certain reasons, such as caching, less confusing for users, etc.
