### ISSUE TITLE
spanner: change healthcheck interval to a longer time instead of every 5 mins

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#1817]
**Client**

spanner/v1.2.1

**Expected behavior**

The session will not be expired within an hour so that we don't need to check too frequent for keeping sessions alive. The health checks should be scheduled for every ~50 mins. However, in Go client library, the interval is a random value `time.Now() + [interval*0.5, interval*1.5)` so that we should set the health interval to 30 mins and the random range will become `[15 mins, 45 mins)`. 

**Actual behavior**

The current health check is every 5 mins. This might overload the backend because of making too many GetSession() calls. 

**Related code**

* https://github.com/googleapis/google-cloud-go/blob/8f5ae458328266edabccba1832251fdb91e34cd2/spanner/session.go#L432-L439
* https://github.com/googleapis/google-cloud-go/blob/3e5ef4404a0c98073e1cd35889e7200874ee59b0/spanner/session.go#L1188-L1199
* https://github.com/googleapis/google-cloud-go/blob/3e5ef4404a0c98073e1cd35889e7200874ee59b0/spanner/session.go#L1235-L1246

**Comment by snehashah16** [comment]
> However, in Go client library, the interval is a random value time.Now() + [interval*0.5, interval*1.5) so that we should set the health interval to 30 mins and the random range will become [15 mins, 45 mins).

Is your fix going to run this every [15-45) mins or can we push it out even further ? 
Example:
* if the healthcheck.interval is set by the customer, respect it and run it every interval cadence
* if it is not set, run it at every [50 - 55] mins interval.

I dont see the value in this wide interval of [0.5 - 1.5)*interval

**Comment by hengfengli** [comment]
@snehashah16  E.g., a health check for a session is done at 10:00am and then the next check will happen at a random value between 10:15am and 10:45am. This will spread requests across the time span instead of all traffic going to a single time point. 

> I dont see the value in this wide interval of [0.5 - 1.5)*interval

Sorry, I don't quite understand it. What do you mean by this?

**Comment by hengfengli** [comment]
FYI: a new CL has been merged for this issue: https://code-review.googlesource.com/c/gocloud/+/53252, which updates the health interval to [45, 55) mins.
