### ISSUE TITLE
spansql : support for defining foreign key

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#1820]
support for the foreign keys in the table definition 

https://cloud.google.com/spanner/docs/foreign-keys/overview

now we got an error when we define this

**Comment by olavloite** [comment]
@geerttouquet 
I think that if you pull in the latest version of master you should have a fix for this already. See also https://code-review.googlesource.com/c/gocloud/+/52990

**Comment by olavloite** [comment]
Closing for now as the linked CL should fix this. Please report back if you experience any problems with this new feature, or if this for some other reason does not solve the issue for you.

**Comment by geerttouquet** [comment]
thanks , it works
