### ISSUE TITLE
datastore: documentation is incorrect/unclear on treatment of embedded structs

### ISSUE THREAD

**Issue by benjaminjkraft** [googleapis/google-cloud-go#1825]
The documentation says:
> If the struct pointed to contains other structs, then the nested or embedded structs are themselves saved as Entity values.

It then goes on to give a series of examples about nested structs.  I read the documentation as saying that embedded structs work the same way.  But in fact they don't: properties of embedded structs are serialized as if they belonged to the embedding struct, unless they have an explicit datastore tag or something like that.

The following test case shows the representation is the same:
<details>
<summary>Test case</summary>

```go
package datastore_test

import (
	"context"
	"testing"

	"cloud.google.com/go/datastore"
)

const MyModelKind = "MyModel"

type Inner struct {
	InnerField string `datastore:"inner_field"`
}

type MyModelWithEmbed struct {
	Inner
	OuterField string `datastore:"outer_field"`
}

type MyModelWithoutEmbed struct {
	InnerField string `datastore:"inner_field"`
	OuterField string `datastore:"outer_field"`
}

func TestEmbeddedToNonEmbedded(t *testing.T) {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "benkraft-test")
	if err != nil {
		t.Fatal(err)
	}

	key := datastore.IncompleteKey(MyModelKind, nil)
	model := MyModelWithEmbed{
		Inner:      Inner{InnerField: "inner_value"},
		OuterField: "outer_value",
	}

	key, err = client.Put(ctx, key, &model)
	if err != nil {
		t.Fatal(err)
	}

	var modelAgain MyModelWithoutEmbed
	err = client.Get(ctx, key, &modelAgain)
	if err != nil {
		t.Error(err)
	}
	if modelAgain.InnerField != "inner_value" {
		t.Errorf(`got %v want "inner_value"`, modelAgain.InnerField)
	}
	if modelAgain.OuterField != "outer_value" {
		t.Errorf(`got %v want "outer_value"`, modelAgain.OuterField)
	}
}

func TestNonEmbeddedToEmbedded(t *testing.T) {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "benkraft-test")
	if err != nil {
		t.Fatal(err)
	}

	key := datastore.IncompleteKey(MyModelKind, nil)
	model := MyModelWithoutEmbed{
		InnerField: "inner_value",
		OuterField: "outer_value",
	}

	key, err = client.Put(ctx, key, &model)
	if err != nil {
		t.Fatal(err)
	}

	var modelAgain MyModelWithEmbed
	err = client.Get(ctx, key, &modelAgain)
	if err != nil {
		t.Error(err)
	}
	if modelAgain.Inner.InnerField != "inner_value" {
		t.Errorf(`got %v want "inner_value"`, modelAgain.Inner.InnerField)
	}
	if modelAgain.OuterField != "outer_value" {
		t.Errorf(`got %v want "outer_value"`, modelAgain.OuterField)
	}
}
```
</details>

After running the test one can see in the [entity viewer](https://console.cloud.google.com/datastore/entities;kind=MyModel;ns=__$DEFAULT$__/query/kind?project=benkraft-test) that the entities in datastore indeed have no nesting:
![Table showing two entities with random keys and fields inner_field=inner_value, outer_field=outer_value](https://user-images.githubusercontent.com/111238/76654302-ea76b700-6527-11ea-8a45-dd7de5d01e62.png)

The implementation, once you find the relevant part in `cloud.google.com/go/internal/fields.Cache.listFields`, is also pretty clear about the handling (including the precise details of the edge cases).

Can the documentation be updated to be clear about this?

**Comment by benjaminjkraft** [comment]
A coworker points out to me that this also matches how JSON does things: search "Anonymous struct fields are usually marshaled..." in the [`encoding/json` documentaton](https://golang.org/pkg/encoding/json/).  So that might be a clear way to document it by reference.

**Comment by IlyaFaer** [comment]
@benjaminjkraft, thank you very much for the test case! Let me take a closer look at it.

Preliminary, I'd say, that it`s working that way because of "anonymous fields" features in Go. Consider such an example:

![Безымянный](https://user-images.githubusercontent.com/26030071/78556127-13ccef00-7817-11ea-8025-b2a124832b7c.png)

But if we'll make the field named, it'll give us a struct in a "strict fashion":

![Безымянный](https://user-images.githubusercontent.com/26030071/78556420-a077ad00-7817-11ea-9c5c-d6b8b806253a.png)

**Comment by IlyaFaer** [comment]
@benjaminjkraft, yes, I think, that's it. Here is my sample (based on yours):
```go
package datastore_test

import (
	"context"
	"testing"

	"cloud.google.com/go/datastore"
)

type Inner struct {
	InnerField string `datastore:"inner_field"`
}

type MyModelWithEmbed struct {
	Inner      Inner  // named field
	OuterField string `datastore:"outer_field"`
}

func TestEmbeddedToNonEmbedded(t *testing.T) {
	ctx := context.Background()
	client, _ := datastore.NewClient(ctx, "generalfullaccess")
	key := datastore.IncompleteKey("MyModel", nil)

	model := MyModelWithEmbed{
		Inner:      Inner{InnerField: "inner_value"},
		OuterField: "outer_value",
	}

	key, _ = client.Put(ctx, key, &model)

	var got MyModelWithEmbed
	client.Get(ctx, key, &got)

	// Inner is still a toplevel field, while InnerField is not
	if got.Inner.InnerField != "inner_value" {
		t.Errorf(`got %v want "inner_value"`, got.Inner.InnerField)
	}
	if got.OuterField != "outer_value" {
		t.Errorf(`got %v want "outer_value"`, got.OuterField)
	}
}
```
As you can see, `Inner` field is still there, and `InnerField` can't be reached like `got.InnerField`. Only by full path `got.Inner.InnerField`.

**Comment by IlyaFaer** [comment]
@BenWhitehead, what do you say? Seems to me the issue is fixed, but I think we should add a small notice about anonymous fields into docs, because I saw several similar questions on Stackoverflow and others - looks like it's a common situation for a lot of users.

**Comment by BenWhitehead** [comment]
@IlyaFaer Thinks for digging in and figuring things out. I'll link to this issue from a docs bug.

Do you think we can also add a note into the go doc (maybe on the put & set methods to call out this scenario)? Perhaps a statement like 

> Note: When using an embedded struct the name of the struct will used as the field name, and must be included in the FieldPath when interacting with nested fields. i.e `data.Inner.InnerField` instead of `data.InnerField`"
