### ISSUE TITLE
pubsub: add flush feature to topic

### ISSUE THREAD

**Issue by smorand** [googleapis/google-cloud-go#1831]
**Is your feature request related to a problem? Please describe.**
Cannot ensure the sending of pubsub message without effort

**Describe the solution you'd like**
A method in the pubsub topic object ensuring all message have been sent

**Describe alternatives you've considered**
Implement by myself with more or less complex mechanism (go deep in the underlying layer)

**Additional context**
I propose to add in pubsub/topic.go file the following code:
```go
// Flush ensures all remaining messages are sent
func (t *Topic) Flush() {
	t.bundler.Flush()
}
```

**Comment by hongalex** [comment]
Thanks for raising this issue! This is something on our radar, and we're just making sure this can be safely added in a compatible way to all of our clients. I'll try to post an update soon.
