### ISSUE TITLE
logging: library code should not crash

### ISSUE THREAD

**Issue by ghasemloo** [googleapis/google-cloud-go#1862]
**Client**

Stackdriver Logging
 
**Environment**

all

**Code**

replace panics

https://github.com/googleapis/google-cloud-go/commit/0d861fa3d953cd0912ea4403a996d53aa1df2ae0

**Expected behavior**

library code should not crash (except at startup)

**Actual behavior**

library code crashes when request is nil

**Comment by codyoss** [comment]
From looking at both of these they seem like actual valid reasons to panic. I could be missing something though. Did you trigger these panics while your code was running?

**Comment by codyoss** [comment]
Closing due to lack of response. Please reopen if you have more information to share.

**Comment by ghasemloo** [comment]
Yes, it did, the request was nil I think.

Based on Google's internal go style library code should not panic: go/gocomments#dont-panic
Filed here instead of internally since this seems to be the source of truth for the code.

**Comment by ghasemloo** [comment]
@jba fyi
