### ISSUE TITLE
firestore: custom protobuf encoding/decoding for user-defined types

### ISSUE THREAD

**Issue by marcin-ptaszynski** [googleapis/google-cloud-go#1863]
**Is your feature request related to a problem? Please describe.**
Related to #1438
Current struct field tags and builtin type conversion seem unnecessarily limiting and force use of intermediate types or steps.

**Describe the solution you'd like**
1. Expose Encode/Decode interface to give developer ability to implement custom serialization to firestore protobuf format, e.g.:
```
type Encoder interface {
	EncodeFirestore() (*pb.Value, error)
}

type Decoder interface {
	DecodeFirestore(*pb.Value) error
}
```
2. Protobuf types already have some support, so how about supporting them fully (especially oneofs) using similar format to jsonpb?
3. (simple) Instead of defining `Marshal/Encode` interfaces, methods `toProtoDocument`/`setFromProtoValue` could treat value type of `*firestorepb.Value` in special way, allowing reflection bypass.

**Describe alternatives you've considered**
1. Don't use interface, private fields, ensure structs look right for Firestore client reflection - this is what we're currently doing, but it stings more and more.
2. Translation from/to `map[string]interface` or intermediate type "liked" by Firestore client - seems like the easiest, but requires unnecessary processing (code, cpu, memory).

**Additional context**
We're working with CRUD API and most objects fit well into the DB as they are, with small exceptions (mostly leafs in document tree). Adding intermediate layer only to workaround builtin behavior doesn't feel right - currently we're aligning (limiting) to what firestore reflection supports.

Cases (extracted from https://github.com/googleapis/google-cloud-go/issues/1740#issuecomment-598382965):
1. serialize fields with Interface type (protobuf oneofs, or others)
2. transform types for db indexing and query  purposes, e.g.:
    1. insert GeoPoint with GeoHashes containing it
    2. string with prefixes or infixes
    3. ip address subnets, etc

**Comment by adrianduke** [comment]
This would resolve my issue mentioned in: https://github.com/googleapis/google-cloud-go/issues/1740#issuecomment-627959960

**Comment by crwilcox** [comment]
Closing this as a duplicate as the work needed is captured in 2610.
