### ISSUE TITLE
bigquery: documentation and behavior seem inconsistent

### ISSUE THREAD

**Issue by wade-p** [googleapis/google-cloud-go#1864]
It seems there are some inconsistencies in how the documentation talks about insertIDs in [value.go](https://github.com/googleapis/google-cloud-go/blob/master/bigquery/value.go) and how they're used in [inserter.go](https://github.com/googleapis/google-cloud-go/blob/master/bigquery/inserter.go)

Specifically when an InsertId is missing:

"""
// If non-empty, BigQuery will use InsertID to de-duplicate insertions
	// of this row on a best-effort basis.
	InsertID string
"""

However, the behavior in inserter:

"""
if insertID == NoDedupeID {
			insertID = ""
		} else if insertID == "" {
			insertID = randomIDFn()
		}
"""

does not seem to align with that. In order to prevent insertId from being used, it must be set, otherwise it is given a random value. This makes it harder than it should be to use the [new streaming backend](https://cloud.google.com/bigquery/quotas#streaming_inserts) when using the go library

**Comment by shollyman** [comment]
https://code-review.googlesource.com/c/gocloud/+/53513 out for review
