### ISSUE TITLE
pubsub: speed up tests

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1867]
**Client**

PubSub

**Environment**

Kokoro

**Expected behavior**

Tests finish in under 30 minutes.

**Actual behavior**

Tests time out after 30 minutes.

**Additional context**

https://code-review.googlesource.com/c/gocloud/+/53512 increases the timeout to 45 minutes. Ideally, that CL should not be necessary.

Example failures: https://github.com/googleapis/google-cloud-go/issues/1860

**Comment by hongalex** [comment]
This timeout was related to a test that was failing, and all tests run in <30 minutes. Closing.
