### ISSUE TITLE
secretmanager: add IAM support to v1

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#1882]
Same helpers as for v1beta1, I think.

/cc @sethvargo

**Comment by gwhitehawk** [comment]
I checked here: https://pkg.go.dev/cloud.google.com/go@v0.55.0/secretmanager/apiv1?tab=doc, and there was no mention of helpers, so I used SetIamPolicy/GetIamPolicy accessors.

**Comment by sethvargo** [comment]
@gwhitehawk check out iam.go in v1beta1. That's a hand-written file. We just wrap the IAM handler: https://github.com/googleapis/google-cloud-go/blob/master/secretmanager/apiv1beta1/iam.go

**Comment by gwhitehawk** [comment]
@sethvargo Thanks. I noticed that exists for apiv1 version as well. The import check failed when I keep the IAM code as it was in beta, presumably because I haven't bumped the api version or something.
