### ISSUE TITLE
Get Kube credentials from cluster object

### ISSUE THREAD

**Issue by ishankhare07** [googleapis/google-cloud-go#1886]
I have access to the cluster object that gke created for me. 

#### I would like to generate `kubeconfig` through this so that I can use that with [helm go library](https://pkg.go.dev/k8s.io/helm@v2.16.4+incompatible)

Basically I would like to use the cluster credentials in the [`kubernetes.NewForConfig`](https://pkg.go.dev/k8s.io/client-go@v11.0.0+incompatible/kubernetes?tab=doc#NewForConfig) function so that I can programmatically start interacting with the things inside my cluster.

**Comment by codyoss** [comment]
To get information about a cluster checkout: https://pkg.go.dev/cloud.google.com/go@v0.55.0/container/apiv1?tab=doc#ClusterManagerClient.GetCluster

This should return all of the useful information about a cluster.

**Comment by codyoss** [comment]
Closing due to lack of response. Feel free to reopen if you are still having issues.
