### ISSUE TITLE
firestore: Returned errors unhelpful

### ISSUE THREAD

**Issue by abergmeier** [googleapis/google-cloud-go#1889]
**Client**
firestore

**Environment**
Ubuntu 18.04 running an instance of Firestore Emulator.

**Code**
```go
err = client.RunTransaction(ctx, func(ctx context.Context, tx *firestore.Transaction) error {
		doc, err := tx.Get(store)
		if err != nil {
			return fmt.Errorf("Getting Snapshot %v failed: %v", store, err)
		}

		err = doc.DataTo(&stored)
		if err != nil {
			return fmt.Errorf("Loading from Snapshot %v failed: %v", doc, err)
		}

		err = tx.Set(store, map[string]interface{}{
			"foo": "bar",
		}, firestore.MergeAll)
		if err != nil {
			return fmt.Errorf("Setting failed: %v", err)
		}

		return nil
	})
```

**Expected behavior**
This should either work and return `nil` or give me a better error so I know what is wrong.

**Actual behavior**
`err` after `RunTransaction` is `rpc error: code = Unknown desc =`.
Looking at the code of `RunTransaction` it is not optimal that it often times only returns the raw internal error.

**Additional context**
It might be a problem with my setup, with Firestore Emulator or with a thousand other things. Without proper error reporting this gets cumbersome to find out.

Now my questions are:
1. what is this modules stance on error reporting?
1. Is it this way by design?
1. Would you prefer creating new errors which reference the internal?
1. Would you prefer creating new errors which contain the internal in their message?
1. Would you take patches for error handling in `RunTransaction`?
1. How long is a "normal" PR cycle?

**Comment by codyoss** [comment]
Please see: https://github.com/googleapis/google-cloud-go/issues/1525

The team that manages this repository is not the team that works on the emulator. The linked issue has links and advice on how to reach out.
