### ISSUE TITLE
bigquery: split large requests

### ISSUE THREAD

**Issue by yields** [googleapis/google-cloud-go#1894]
**Is your feature request related to a problem? Please describe.**

The client does not split large requests.

```
googleapi: Error 400: Request payload size exceeds the limit: 10485760 bytes., badRequest
```

**Describe the solution you'd like**

It seems to me that the client is best positioned to split those large requests into multiple smaller ones, since it provides a higher-level API:

```go
inserter.Put(ctx, []Post{...})
```

The client already knows about the protocol (http vs grpc), compression and so it can accurately predict if a request is too large.

**Describe alternatives you've considered**

Our current solution is to calculate the JSON byte size for all rows and if they're larger than 8mb we split the batch of rows into two requests.

Luckily, we already have access to the JSON sizes so it was simple enough to implement, I can imagine how annoying it would be if we didn't.

**Additional context**

I would accept that error if the API was lower level:

```go
buf, err := json.Marshal(posts)
inserter.Write(ctx, buf)
```

**Comment by shollyman** [comment]
There's work to improve the streaming insertion mechanism, but it's happening in the context of a new API surface which is currently in alpha.  Once that API is ready, it'll be more straightforward to build a batching mechanism to support features like auto-splitting.

**Comment by shollyman** [comment]
I'm going to go ahead and close this issue for now, in recognition we'll have another API for this.
