### ISSUE TITLE
spanner: Race condition in (*BatchReadOnlyTransaction).Execute()

### ISSUE THREAD

**Issue by lhecker** [googleapis/google-cloud-go#1895]
**Client**

Spanner

**Environment**

Any

**Code**

The following code counts the total number of rows using `PartitionRead()`.
It'll exhibit the race condition by showing varying total counts at the end of each run.
Of course this only works if your table has more than one partition.

```go
package main

import (
	"context"
	"fmt"
	"sync"
	"sync/atomic"

	"cloud.google.com/go/spanner"
)

func main() {
	client, err := spanner.NewClient(context.Background(), "projects/<project>/instances/<instance>/databases/<database>")
	if err != nil {
		fmt.Println(err)
		return
	}

	txn, err := client.BatchReadOnlyTransaction(context.Background(), spanner.StrongRead())
	if err != nil {
		fmt.Println(err)
		return
	}
	defer txn.Cleanup(context.Background())

	partitions, err := txn.PartitionRead(context.Background(), "<table>", spanner.AllKeys(), []string{"<column>"}, spanner.PartitionOptions{})
	if err != nil {
		fmt.Println(err)
		return
	}

	wg := &sync.WaitGroup{}
	var total uint64

	for _, p := range partitions {
		p := p

		go func() {
			iter := txn.Execute(context.Background(), p)
			defer iter.Stop()

			var count uint64
			err = iter.Do(func(row *spanner.Row) error {
				count++
				return nil
			})
			if err != nil {
				return
			}

			atomic.AddUint64(&total, count)
		}()
	}

	wg.Wait()
	fmt.Println(total)
}
```

**Expected behavior**

`PartitionRead()` reads all rows.

**Actual behavior**

A race condition. :cry: 

**Cause**

Each partition points to the same `rreq`/`qreq`.
For instance for `rreq` [line 137](https://github.com/googleapis/google-cloud-go/blob/a1a1bde6bc683c127b2922557712dcd1d891ded3/spanner/batch.go#L137) in the following code section:

https://github.com/googleapis/google-cloud-go/blob/a1a1bde6bc683c127b2922557712dcd1d891ded3/spanner/batch.go#L124-L139

During the call in `Execution()` the `rreq`/`qreq` fields are then mutated without locks of any kind.
For instance for `rreq` [line 264](https://github.com/googleapis/google-cloud-go/blob/a1a1bde6bc683c127b2922557712dcd1d891ded3/spanner/batch.go#L264) in the following code section:

https://github.com/googleapis/google-cloud-go/blob/a1a1bde6bc683c127b2922557712dcd1d891ded3/spanner/batch.go#L262-L275

The documentation of that function also doesn't mention it's not safe for concurrent use, nor that it mutates it's argument.

I suppose the struct field `pt` exists because this was an attempt to reduce the data size after a call to `MarshalBinary()`?
In that case I'd like to kindly suggest to simply copy the `rreq`/`qreq` fields within the `Execution()` method and mutate the copy only. :slightly_smiling_face: 

**Additional context**

Intermediate fix:
```
data, err := p.MarshalBinary()
if err != nil {
	return
}

p := &spanner.Partition{}
err = p.UnmarshalBinary(data)
if err != nil {
	return
}
```

:point_right: Should I submit a fix?
[I already did so in the past](https://github.com/googleapis/google-cloud-go/commits?author=lhecker), but last time you told me to open an issue beforehand. :smile:

**Comment by olavloite** [comment]
@lhecker Thanks, that's a great catch. And thank you for the very elaborate report and analysis.

There's a fix coming here: https://code-review.googlesource.com/c/gocloud/+/54190
