### ISSUE TITLE
Ability to query projects within an organisation

### ISSUE THREAD

**Issue by govinda-attal** [googleapis/google-cloud-go#1897]
Apologies, I was struggling to find the package and any documentation over internet to query information about projects. So, spamming on this issue channel.

Is it possible to use this sdk to query projects within an organisation and query metadata about other projects. (when executing inside and outside of the google cloud platform).

Best Regards

**Comment by codyoss** [comment]
I think this is what you are looking for: https://pkg.go.dev/google.golang.org/api@v0.20.0/cloudresourcemanager/v1?tab=doc
