### ISSUE TITLE
firestore: add support for minimum and maximum field transforms

### ISSUE THREAD

**Issue by ribrdb** [googleapis/google-cloud-go#1900]
Please add support for minimum and maximum field transforms:
https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.DocumentTransform.FieldTransform

**Comment by BenWhitehead** [comment]
Gerrit CL to add this feature: https://code-review.googlesource.com/c/gocloud/+/54274

**Comment by tritone** [comment]
CL for this was merged; thanks!
