### ISSUE TITLE
datastore: metadataNamespaces example does not work

### ISSUE THREAD

**Issue by directionless** [googleapis/google-cloud-go#1901]
**Client**

datastore

**Code**

e.g.
The example at https://github.com/GoogleCloudPlatform/golang-samples/blob/master/datastore/snippets/snippet_test.go#L653-L678

**Expected behavior**

List namespaces to stdout

**Actual behavior**

```
Namespaces:

```
(no output but the header line

**Additional context**

If I change this to `spew.Dump(k)` I get correct looking data:
```
(*datastore.Key)(0xc0001894c0)(/__namespace__,ns1)
(*datastore.Key)(0xc000189500)(/__namespace__,ns2)
(*datastore.Key)(0xc000189540)(/__namespace__,ns3)
```

**Comment by codyoss** [comment]
@directionless Can you please open this issue under https://github.com/GoogleCloudPlatform/golang-samples
