### ISSUE TITLE
bigquery: High memory usage for large query results

### ISSUE THREAD

**Issue by dmngu9** [googleapis/google-cloud-go#1902]
**Client**

Big Query Golang client

**Expected behavior**

I have a docker container use Big Query Golang client to retrieve data from Big Query. There are 62k rows in total. I expect memory usage to be high because temporary memory need to be allocated for each row. But not as high as what i saw.

**Actual behavior**

But the memory usage jump to 570 MiB. That's very high. It is equivalent to 9kB per row. Way higher than i thought

**Comment by codyoss** [comment]
Hey,

Sorry to hear you are having an issue with high memory utilization. Could you please provide me some more details:

1. What version of the client are you using?
2. What is the composition of data in a single row?  Example 2 strings, 1 bool, and an integer. I am wondering if the rows are just bigger than you think.
3. Have you double checked the table size to make sure it is what you expect? For a given dataset you can query information about a table /w `dataset.__TABLES__`. If you summed this up and divided by the number of rows you could get an estimate of your average row size.
4. Does the memory go back down?

Thanks

**Comment by dmngu9** [comment]
Hi, thanks so much for your reply

1. I saw my Gopkg.lock contains 
```[[projects]]
  digest = "1:8da703568a558dae38da6c1eef8cc88f5b419683a261257ecb94a630702d2124"
  name = "cloud.google.com/go"
  packages = [
    ".",
    "bigquery",
    "civil",
    "compute/metadata",
    "internal",
    "internal/fields",
    "internal/optional",
    "internal/trace",
    "internal/version",
  ]
  pruneopts = "UT"
  revision = "d1af076dc3f6a314e9dd6610fe83b0f7afaff6d6"
  version = "v0.45.1"```
so i guess its part of google cloud go v0.45

2. Single row contains 1 string and array of string. So there are only 2 columns

3. I saw the table size in big query console is only around 6MB for 65k rows

4. I used docker stats to check the memory usage of container. After the process, it does not go down. Not sure it is because of Go garbage collector or some issue with docker stats

**Comment by codyoss** [comment]
I would not trust docker stats as a way to profile memory. Might I suggest some of the following:
1. Writing an integration style test and report the allocs
2. expvar
3. pprof

If you are looking at usage in GCP I might suggest the Cloud Profiler as well.

Given the table size though, I am doubtful this is a bigquery issue. I suspect something else might be at play.

**Comment by dmngu9** [comment]
Hi,

There might be anything wrong with the library.

I think it might be because of long running for loop in go which keeps allocate memory for variable to get value from iterator.Next(). These memory only garbage collect after the for loop.

Im relatively new to Go. Im not sure how to avoid this problem

**Comment by dmngu9** [comment]
json (*decodeState) seems to hold a lot of memory. The table is 65k rows. But on big query console, the table size is only 6Mb. Not sure how it become 255Mb

**Comment by codyoss** [comment]
cc @shollyman

**Comment by dmngu9** [comment]
any update?

**Comment by dmngu9** [comment]
also, i try to understand the Iterator struct. We provide pointer to struct into Next(). Looking at the code, it seems it.nextFunc() (which is pageFetcher) is called every time Next() is called. Without MaxSize of PageInfo is set, does that retrieve one row per Next() called?
`func (it *RowIterator) Next(dst interface{}) error {
	if it.pf == nil { // There are no rows in the result set.
		return iterator.Done
	}
	var vl ValueLoader
	switch dst := dst.(type) {
	case ValueLoader:
		vl = dst
	case *[]Value:
		vl = (*valueList)(dst)
	case *map[string]Value:
		vl = (*valueMap)(dst)
	default:
		if !isStructPtr(dst) {
			return fmt.Errorf("bigquery: cannot convert %T to ValueLoader (need pointer to []Value, map[string]Value, or struct)", dst)
		}
	}
	if err := it.nextFunc(); err != nil {
		return err
	}
	row := it.rows[0]
	it.rows = it.rows[1:]

	if vl == nil {
		// This can only happen if dst is a pointer to a struct. We couldn't
		// set vl above because we need the schema.
		if err := it.structLoader.set(dst, it.Schema); err != nil {
			return err
		}
		vl = &it.structLoader
	}
	return vl.Load(row, it.Schema)
}`

**Comment by codyoss** [comment]
I did a little testing around this as well. You are right, the memory usage is quite high. As your memory profile points out, this mainly comes down to deserializing JSON is expensive. I am not sure how much we will be able to due about this as we are just using the standard library decode function.

**Comment by dmngu9** [comment]
any work around? Currently, i worked around by fetching 20k rows at a time. But im interested in if there is any better work around

**Comment by codyoss** [comment]
I don't think so, as it will still come down to decoding JSON as the bottleneck. I wish I had a better answer for you.
