### ISSUE TITLE
spannertest: Support list parameters

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#1904]
**Is your feature request related to a problem? Please describe.**
Using lists as parameters to spanner statements, for example in the context of `IN UNNEST(@list)`-queries, gives the following response from `spannertest`:

```
spanner: code = "Unknown", desc = "rpc error: code = Unknown desc = unsupported well-known type value kind *structpb.Value_ListValue"
```

**Describe the solution you'd like**
Support lists as statement parameters in `spannertest`.

**Describe alternatives you've considered**
Not test these queries with `spannertest`.

**Comment by olavloite** [comment]
@dsymonds I don't know if you had seen this one, and whether this would be doable or not?

**Comment by dsymonds** [comment]
I hadn't seen it. Thanks for the ping.

https://code-review.googlesource.com/c/gocloud/+/53250 was supposed to have handled this, but maybe there's a part I overlooked.

**Comment by dsymonds** [comment]
Yeah, I think I failed to stitch up the proto interface to the internal DB simulation. It's supported fine in the latter. Should be an easy fix.

**Comment by odsod** [comment]
@dsymonds Nice one, thanks for looking into it!
