### ISSUE TITLE
bigquery: ability to compress streaming inserts in transport

### ISSUE THREAD

**Issue by bschofield** [googleapis/google-cloud-go#1919]
**Is your feature request related to a problem? Please describe.**

I would like a documented mechanism for requesting that data which is being streamed into BigQuery, using the _tabledata.insertAll_ call, be gzip-compressed in transport. Presently, this does not appear to be possible without using an ugly workaround (see below).

I would like this in order to reduce upload bandwidth when streaming into BigQuery, and because it seems that the BigQuery API already supports this functionality.

**Describe the solution you'd like**

An option, either on the `bigQuery.NewClient()` call or on the `Inserter` struct, to enable transparent gzip compression on the json data uploaded to BQ.

**Describe alternatives you've considered**

I looked through the existing BigQuery code, but I couldn't see another obvious way to apply compression on the upload. If there is already a method, could you please point me in the direction of it?

Instead, I am currently forcing requests to become compressed by intercepting the Transport used by the `http.Client`:

```golang
package shim

import (
	"bytes"
	"compress/gzip"
	"context"
	"io"
	"io/ioutil"
	"net/http"

	"google.golang.org/api/option"
	internaloption "google.golang.org/api/option/internaloption"
	htransport "google.golang.org/api/transport/http"
)

// CompressTransport is an http.RoundTripper which transparently compresses the request body
type CompressTransport struct {
	transport http.RoundTripper
}

// RoundTrip compresses the transmitted payload before executing the underlying RoundTrip()
func (ct *CompressTransport) RoundTrip(h *http.Request) (*http.Response, error) {

	// Gzip into a new buffer b
	b := bytes.Buffer{}
	gw, _ := gzip.NewWriterLevel(&b, gzip.BestCompression)
	if _, err := io.Copy(gw, h.Body); err != nil {
		panic(err)
	}
	gw.Close()

	// Update parameters on the request to indicate compression
	h.Header.Set("Content-Encoding", "gzip")
	h.ContentLength = int64(b.Len())
	h.Body = ioutil.NopCloser(&b)

	// Execute the request
	return ct.transport.RoundTrip(h)
}

// NewCompressingClient returns an http.Client for BigQuery which compresses the uploaded payload
func NewCompressingClient(ctx context.Context) *http.Client {

	// Create a new http.Client with suitable scopes
	hc, _, _ := htransport.NewClient(ctx,
		option.WithScopes(
			"https://www.googleapis.com/auth/bigquery",
			"https://www.googleapis.com/auth/bigquery.insertdata",
			"https://www.googleapis.com/auth/bigquery.readonly",
		),
		internaloption.WithDefaultEndpoint("https://bigquery.googleapis.com/bigquery/v2/"),
	)

	// Shim the client's transport
	ct := CompressTransport{
		transport: hc.Transport,
	}
	hc.Transport = &ct

	return hc
}
```

I then create a bigquery client which transparently compresses all uploads:

```golang
httpClient := shim.NewCompressingClient(ctx)
client, err := bigquery.NewClient(ctx, bqProject, option.WithHTTPClient(httpClient))
```

This appears functional, but it feels like a bad solution because (a) it involves modifying requests inside an `http.RoundTripper`, which the golang documentation specifically says not to do, and (b) it depends on knowledge of the internals of `google.golang.org/api`.

**Comment by shollyman** [comment]
Thanks for the report.  As you've identified, constructing a custom http client and passing it into the bigquery client constructor is likely the best way forward here.

I don't anticipate us addressing this via further modifications to the streaming API as it exists in the existing library.  There's work to add high a newer throughput streaming interface which will be grpc-based and build on the work of the BigQuery Storage API, but it's still very much in an alpha state at this time.

**Comment by shollyman** [comment]
I'm going to close this one, as we've got known future improvements coming through the storage API write path.

**Comment by anpatel-twilio** [comment]
@shollyman is there an option to enable payload compression in the new storage write API?

**Comment by yirutang** [comment]
In go, you can do:
 managedwriter.NewClient(
        ctx,
        projectId,
        option.WithGRPCDialOption(
            grpc.WithDefaultCallOptions(
                grpc.UseCompressor(grpc_gzip.Name),
            ),
        ),
