### ISSUE TITLE
spanner: release v1.6.0

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1929]
If users upgrade to github.com/golang/protobuf v1.4.0, `QueryWithOptions` panics. See #1928 for the google-cloud-go issue+fix and https://github.com/GoogleCloudPlatform/golang-samples/issues/1346 for an example panic.

**Comment by hengfengli** [comment]
@tbpg Is it necessary to have a minor version change? Can it be v1.5.1 because this sounds like a bugfix instead of a new feature?

**Comment by hengfengli** [comment]
After discussing with Knut, we think a new release v1.5.1 sounds more reasonable. Please let me know if you have any concerns with the version number.

**Comment by MatthewDolan** [comment]
@hengfengli Does this also require a base release? If one downloads the latest release (`v0.56.0`), the panic is still present. Can the update be released under `v0.56.1`?

**Comment by hengfengli** [comment]
@MatthewDolan I think you can run `go get cloud.google.com/go/spanner` to get the latest version for spanner.
