### ISSUE TITLE
storage: Create object if it doesn't exist

### ISSUE THREAD

**Issue by agorman** [googleapis/google-cloud-go#1931]
I need to create an object if it doesn't exist. I can do this using a precondition and it all works as expected. My issue is that `objWriter.Close()` will return an error if the precondition fails but there is no good way for me to see if the error was caused by the precondition failing or the object creation failing for another reason. If the precondition fails I just want to move on with the code but if it errors for another reason I'd like to return. Is there a way to handle this case?

```go
objWriter := obj.If(storage.Conditions{DoesNotExist: true}).NewWriter(ctx)
if err := objWriter.Close(); err != nil {
	return err
}
```

**Comment by tbpg** [comment]
cc @odeke-em

**Comment by odeke-em** [comment]
Hello @agorman, thank you for filing this issue and welcome to the google-cloud-go project!
Thank you for the ping @tbpg!

@agorman you can type assert on the error and if of type googleapi.Error check the status code, for example
```go
package main

import (
	"context"
	"fmt"
	"net/http"

	"cloud.google.com/go/storage"
	"google.golang.org/api/googleapi"
)

func main() {
	ctx := context.Background()
	client, err := storage.NewClient(ctx)
	if err != nil {
		panic(err)
	}
	defer client.Close()

	ow := client.Bucket("orijtech-gcs-test").Object("fooz").If(storage.Conditions{DoesNotExist: true}).NewWriter(ctx)
	if _, err := ow.Write([]byte("This is some content right here!")); err != nil {
		panic(err)
	}
	if err := ow.Close(); err != nil {
		switch e := err.(type) {
		case *googleapi.Error:
			if e.Code == http.StatusPreconditionFailed {
				fmt.Println("The objext already exists!")
			}
			// And others.
		default:
			panic(err)
		}
	}
}
```
  
If I may ask about user experience: what do you think we could do better to make this easy to surface? We document in the Go doc a section on Errors
![Screen Shot 2020-04-16 at 10 56 39 AM](https://user-images.githubusercontent.com/4898263/79489972-f7784180-7fd0-11ea-92cc-1421bcb2e9c4.png)

but perhaps what do you think could help with easier navigation around this?
Our example on ObjectHandle.If delegates error handling to the caller https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#example-ObjectHandle.If which sends the puck back to the section Errors. @tbpg @codyoss @frankyn @tritone et al what do y'all think?

**Comment by agorman** [comment]
This is exactly what I was looking for, thanks @odeke-em! I totally missed the Errors section in the docs. Now looking back at the docs it seems pretty clear.

Only suggestion I can give is that it might be nice to do this kind of error checking in the If examples like: https://godoc.org/cloud.google.com/go/storage#example-ObjectHandle-If

Thanks again.

**Comment by odeke-em** [comment]
Great to hear that solved your problem!

>Only suggestion I can give is that it might be nice to do this kind of error checking in the If examples like: https://godoc.org/cloud.google.com/go/storage#example-ObjectHandle-If

Thank you! Acknowledged and I hear ye. The problem though is that the myriad of possibilities one can add to these examples. The `// TODO: Handle error.` is left to one's interpretation to avoid distraction from the actual content/intentions of the example. Unfortunately I don't think that there is much that we can do.

**Comment by tbpg** [comment]
Can this also use https://pkg.go.dev/google.golang.org/grpc/status?tab=doc#Code and https://pkg.go.dev/google.golang.org/grpc/codes?tab=doc#Code? That's a bit of an easier API to use than the type conversion.

```go
if status.Code(err) == codes.FailedPrecondition {
    ...
}
```

I wonder if we should update the Errors section.

I agree we shouldn't add a bunch of error checking examples to the examples. But, maybe it would be OK showing a `status.Code` call? It is something very unique to these APIs (and clearly easy to miss).

**Comment by tbpg** [comment]
Looking at it more, we document that an error will be returned if the precondition fails. I think it's reasonable to document (via the example) how to check if the precondition failing is the reason for the error. Even looking at the `codes` package, it's easy to miss there is a `codes.PreconditionFailed`.

**Comment by odeke-em** [comment]
>Can this also use https://pkg.go.dev/google.golang.org/grpc/status?tab=doc#Code and https://pkg.go.dev/google.golang.org/grpc/codes?tab=doc#Code? That's a bit of an easier API to use than the type conversion.

Unfortunately not. That wouldn't work because storage uses HTTP APIs while that package you referenced deals with gRPC status codes and errors.
HTTP status codes are in the range 1XX to 6XX while gRPC codes are XX so

     HTTP.PreconditionFailed = 412

while the equivalent:

    gRPC.FailedPrecondition = 9

One reason why documenting handling might be a trip is that if at some point the storage APIs swap out the underlying implementation to use gRPC instead of HTTP, all the error checking becomes invalid.

>Looking at it more, we document that an error will be returned if the precondition fails. I think it's reasonable to document (via the example) how to check if the precondition failing is the reason for the error. 

Sounds like a plan, I'll mail a CL shortly.

**Comment by odeke-em** [comment]
I've mailed out https://code-review.googlesource.com/c/gocloud/+/54892.
Thank you @agorman and @tbpg for the advocacy, other users and those in the future finna be happy!

**Comment by tbpg** [comment]
Thank you for the quick fix!

**Comment by agorman** [comment]
Thanks!
