### ISSUE TITLE
spanner: doc mentions obsolete function, IsAborted

### ISSUE THREAD

**Issue by rakyll** [googleapis/google-cloud-go#1939]
Spanner package mentions "IsAborted" in the godoc, such as:

```
_, err := client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
    var balance int64
    row, err := txn.ReadRow(ctx, "Accounts", spanner.Key{"alice"}, []string{"balance"})
    if err != nil {
        // This function will be called again if this is an IsAborted error.
        return err
    }
    if err := row.Column(0, &balance); err != nil {
        return err
    }

    if balance <= 10 {
        return errors.New("insufficient funds in account")
    }
    balance -= 10
    m := spanner.Update("Accounts", []string{"user", "balance"}, []interface{}{"alice", balance})
    txn.BufferWrite([]*spanner.Mutation{m})

    // The buffered mutation will be committed.  If the commit
    // fails with an IsAborted error, this function will be called
    // again.
    return nil
})
```

But IsAborted doesn't exist in the package. Furthermore, it is not clear what user can do to abort the transaction. Is any error returned qualify for aborting?

**Comment by hengfengli** [comment]
I think `IsAborted` is outdated. Now, it is `codes.Aborted` from `google.golang.org/grpc/codes`: https://github.com/googleapis/google-cloud-go/blob/8d3876f06c8e5273e98227c0738dc5c6bf7b8436/spanner/retry.go#L76

https://github.com/googleapis/google-cloud-go/blob/1ac32cb883f8ec66a57bec3f2285e7b4b964102d/spanner/client.go#L475-L479

I think if it is not "Aborted" or "Session not found", the transaction will be aborted without retrying and `err` will be returned here: 

```go
_, err := client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
```

@olavloite Please feel free to add any comments.

**Comment by olavloite** [comment]
I've removed the reference to the `IsAborted` function in the doc and tried to clarify the docs a little bit on what an aborted transaction is here: https://code-review.googlesource.com/c/gocloud/+/55592

> Furthermore, it is not clear what user can do to abort the transaction. Is any error returned qualify for aborting?

A user should (normally) not abort a transaction. The Cloud Spanner backend may abort any read/write transaction in case of deadlocks or other concurrency issues (or any other issue the backend might find appropriate reason to abort a transaction). The client library therefore requires the users to specify transactions as a function that can be retried. Whenever the backend aborts a transaction, the client library will start a new transaction and retry the transaction function that was supplied by the user.
This behavior is somewhat different from most other relational databases where transactions are often seen as a sequence of statements with a commit at the end, where each statement and the commit will normally consistently succeed or fail. When dealing with a Cloud Spanner read/write transaction, you always need to take into account that each statement could fail with an `Aborted` error, and that you in that case should retry the entire transaction by starting a new one on the same `Session`. This is all taken care of automatically by the client library.

**Comment by skuruppu** [comment]
@olavloite I think this issue can be closed now. But I'll let you do it in case I'm missing something.
