### ISSUE TITLE
firestore: DOC mention the need to import google.golang.org/api/iterator

### ISSUE THREAD

**Issue by bbalet** [googleapis/google-cloud-go#1940]
**Is your feature request related to a problem? Please describe.**
In the Firestore quickstart guide and in the godoc, the simple examples are not running if you don't import the iterator package. It is confusing for newbies like me as I thought it was a typo with the variable name "iter".

**Describe the solution you'd like**
Update the docs by adding or metioning an import to "google.golang.org/api/iterator"
https://cloud.google.com/firestore/docs/quickstart-servers#go
https://godoc.org/cloud.google.com/go/firestore

**Describe alternatives you've considered**
I know you want to simplify by hidding trivial imports, but a complete first and simple program in the quickstart is not so large.

**Additional context**

**Comment by tbpg** [comment]
https://github.com/GoogleCloudPlatform/golang-samples/issues/1360 will track getting the imports into https://cloud.google.com/firestore/docs/quickstart-servers#go.

Which example are you referring to on http://godoc.org/cloud.google.com/go/firestore (moving to http://pkg.go.dev/cloud.google.com/go/firestore)? There are a bunch of examples there, but I don't think we need to add the import to all them.

**Comment by tbpg** [comment]
Closing this in favor of the golang-samples issue.

**Comment by IlyaFaer** [comment]
@tbpg, if I'm not too late, I think, issue author meant this one:

![Безымянный](https://user-images.githubusercontent.com/26030071/81288780-feddb880-906d-11ea-8899-122c0319c1a0.png)

I don't see any other samples with `iterator`, so it should be.

**Comment by tbpg** [comment]
Not too late. :)

Would you mind sending a CL?
