### ISSUE TITLE
bigquery: Table.FullyQualifiedName() incompatible name formatting

### ISSUE THREAD

**Issue by lightyear15** [googleapis/google-cloud-go#1955]
I can't figure out why the design choice of formatting the fully qualified name for tables as 
``projectID:datasetID.tableID``
when BigQuery only accepts SQL queries with table names formatted this way
``projectID.datasetID.tableID``

**Comment by shollyman** [comment]
The short answer is:  that used to be the format for legacy SQL, which was the dominant dialect when FullyQualifiedName() was implemented.  I'll see about adding an alternative that uses the standard SQL format; we can't change the format of the existing response.

**Comment by tbpg** [comment]
As a workaround, can `:` be replaced with `.`? If so, it might be enough to update the GoDoc for `FullyQualifiedName` and not extend the API more than needed.

**Comment by shollyman** [comment]
There's some oddities to it. A domain qualified project ID can still contain colon (:) characters in a standard SQL reference.  Ex: foo.com:myproject:mydataset.mytable is a valid legacy identifier, foo.com:myproject.mydataset.mytable is the equivalent standard sql identifier.

**Comment by shollyman** [comment]
But then then there's also the need to possibly escape literals, so in a query you're more likely to see SELECT ... FROM `foo.com:myproject`.mydataset.mytable
