### ISSUE TITLE
pubsub: TestPublishScheduler_Put_Basic is flaky

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-go#1965]
Flaky build failure:
https://source.cloud.google.com/results/invocations/9aab0f2a-6987-4d58-8480-6e851523ded3/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Fgo111/log

=== RUN   TestPublishScheduler_Put_Basic
panic: test timed out after 15m0s

goroutine 16 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0x13a
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000cc000, 0x5df037, 0x1e, 0x5e3240, 0xc0000b5c18)
	/usr/local/go/src/testing/testing.go:879 +0x692
testing.runTests.func1(0xc0000cc000)
	/usr/local/go/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc0000cc000, 0xc0000b5d88)
	/usr/local/go/src/testing/testing.go:827 +0x163
testing.runTests(0xc0000a4020, 0x70aa40, 0x7, 0x7, 0xc0000b5e30)
	/usr/local/go/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc0000c0000, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:64 +0x222

goroutine 36 [semacquire]:
sync.runtime_Semacquire(0xc000016088)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000016080)
	/usr/local/go/src/sync/waitgroup.go:130 +0xb5
google.golang.org/api/support/bundler.(*Bundler).Flush(0xc0000de210)
	/go/pkg/mod/google.golang.org/api@v0.22.0/support/bundler/bundler.go:400 +0x184
cloud.google.com/go/pubsub/internal/scheduler.(*PublishScheduler).FlushAndStop(0xc0000c0080)
	/tmpfs/src/google-cloud-go/pubsub/internal/scheduler/publish_scheduler.go:156 +0x10d
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:397 +0xef
testing.(*common).FailNow(0xc0000cc100)
	/usr/local/go/src/testing/testing.go:590 +0x5b
testing.(*common).Fatalf(0xc0000cc100, 0x5e28aa, 0x39, 0xc000042e40, 0x3, 0x3)
	/usr/local/go/src/testing/testing.go:634 +0x95
cloud.google.com/go/pubsub/internal/scheduler_test.TestPublishScheduler_Put_Basic(0xc0000cc100)
	/tmpfs/src/google-cloud-go/pubsub/internal/scheduler/publish_scheduler_test.go:74 +0x905
testing.tRunner(0xc0000cc100, 0x5e3240)
	/usr/local/go/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x65a
FAIL	cloud.google.com/go/pubsub/internal/scheduler	900.013s

**Comment by AlisskaPie** [comment]
After some testing I found out that also failed `TestPublishScheduler_DoesntRaceWithPublisher` with the same error. And it happens pretty often.
Here're the errors: 
`TestPublishScheduler_DoesntRaceWithPublisher`:
![image](https://user-images.githubusercontent.com/38891896/82555023-ad562300-9b6f-11ea-8419-f197754939fb.png)
`TestPublishScheduler_Put_Basic`:
![image](https://user-images.githubusercontent.com/38891896/82555053-bd6e0280-9b6f-11ea-8d3d-c484092aa9a0.png)

**Comment by hongalex** [comment]
Build cop hasn't complained about this in a while (also running the tests locally doesn't seem to surface this issue). Closing.
