### ISSUE TITLE
storage: list bucket objects after marker

### ISSUE THREAD

**Issue by mpl** [googleapis/google-cloud-go#197]
The XML API has https://cloud.google.com/storage/docs/reference-headers#marker , which is really convenient when one wants to enumerate on a bucket with many objects, and skip all the objects before that marker.

I understand this feature is not transparently present in the storage package because (I think) it is based on the JSON API, which does not seem to have that marker feature.

So first of all, did I miss an alternative way to achieve this ? Aside from looping over the listing results and manually skipping the results until I get to the marker of course ?

If I didn't, I was thinking maybe we could adapt Cursor in https://godoc.org/google.golang.org/cloud/storage#Query , so that instead of only being opaquely set by an operation like query = objects.Next , it could also be used as such an aforementioned marker ? Maybe simply documenting the format of Cursor so one could set it manually would already be a first step up ?

What do you think ?

**Comment by mpl** [comment]
Cc @bradfitz

**Comment by bradfitz** [comment]
FWIW, this is preventing us from migrating Camlistore away from our own (old) Cloud Storage package to the official one.

/cc @rakyll @okdave

**Comment by bradfitz** [comment]
We're putting our cloud storage helper functions in https://godoc.org/go4.org/cloud/google/gcsutil for now, until the official package can do it.

/cc @okdave

**Comment by okdave** [comment]
@mpl the `Cursor` in `Query` is the opaque token received back from the list request (the JSON API calls it `pageToken`), so it's not really possible to modify or create one of those tokens at the moment.

I'm chasing up with the team responsible for the JSON API to try to find out why it's only available in XML. I'd want to think very carefully about mixing+matching JSON and XML in this package, since I'm worried the representation of objects might be subtly different and that could lead to weird bugs, so I'd like to see if we can expose it in JSON first. But this does seem like a weird oversight either way.

**Comment by jba** [comment]
Cursors haven't been added to the Storage API in two years and I see no indication that they ever will be, so I'm going to declare this infeasible and close it.

**Comment by abourget** [comment]
No news on that? Is it possible the Marker feature doesn't exist anymore?!

**Comment by jadekler** [comment]
cc @frankyn

**Comment by frankyn** [comment]
`pageToken` can be potentially used a listing cursor, e.g. everything after an exact bucket name. 
> A previously-returned page token representing part of the larger set of results to view.The pageToken is an encoded field containing the name of the last item (bucket) in the returned list. In a subsequent request using the pageToken, items that come after the pageToken are shown (up to maxResults).If you start a listing and then create a new bucket before using a pageToken to continue listing, you will not see the new bucket in subsequent listing results if it is in part of the bucket namespace already listed.


Alternatively there's `prefix` which can help "filter results to objects whose names begin with this prefix".

Reference: https://cloud.google.com/storage/docs/json_api/v1/objects/list

**Comment by jadekler** [comment]
We've asked some clarifying questions and not heard back in a while. Closing this for now, but let us know if you'd like to continue the conversation.

**Comment by pepijnve** [comment]
I'm running into the same limitation as was described originally. What I'm trying to do is parallelise the listing of buckets without prior knowledge of the object keys in the bucket. S3's (i.e. the XML API) marker or startAfter supports this quite well. You can bisect the key space at some arbitrary point and ask for any keys that come after the bisect point. This makes it trivial to list subsections of the key space in parallel.

@frankyn reverse engineering page tokens and using prefixes are both not an option. Both approaches require prior knowledge: you need to either know an exact existing key value or a prefix for an existing key value around the bisect point.

I think the issue can be rephrased as a simple how to question: how do you list, for instance, all keys starting with an `l` or greater without any prior knowledge of the contents of the bucket? With XML API you can do this with `marker: l`. The JSON API does not support this as far as I can tell.
