### ISSUE TITLE
spanner: clean up internal/testutil/mockserver & mockclient

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#1972]
It is confusing to have two mock servers under internal/testutil (although we have third one in spannertest). 

It seems that mockclient.go is not used in anywhere. Can we delete this file? 

Also, can we replace mockserver.go with mocked_inmem_server.go? 

@olavloite Any thoughts about this proposal?

**Comment by olavloite** [comment]
@hengfengli 
I think this is a good idea. The `mockclient.go` and `mockserver.go` files were the old mock implementations that were initially used for testing the Spanner client. Those had very little features and were therefore (largely) replaced by the new `mocked_inmem_server.go`. I can't think of any good reason to keep having more than one mock server for testing.

The `spannertest` version serves a different purpose and should stay. It is a very lightweight emulator that is better for end users to use for testing their own application code. It is not intended for testing the client library. The `mocked_inmem_server.go` however offers features like aborting transactions, removing sessions, and returning errors for specific statements and methods, which are used to test the error handling in the client library.
