### ISSUE TITLE
spanner/spansql: unable to parse alias

### ISSUE THREAD

**Issue by DONSA** [googleapis/google-cloud-go#1973]
**Client**

Spanner

**Environment**

go 1.14

**Code**

```go
package main

import (
    "log"

    "cloud.google.com/go/spanner/spansql"
)

func main() {
    log.Println(spansql.ParseQuery(`
        SELECT COUNT(*) AS count
	FROM Lists AS l
	WHERE l.user_id=@userID
    `))
}
```

**Expected behavior**

No error parsing the query string.

**Actual behavior**
```
bad query: unexpected trailing query contents \"AS count\\n\\t\\tFROM Lists AS l\\n\\t\\tWHERE l.user_id=@userID\"", trailers:metadata.MD(nil), additionalInformation:"
```

**Comment by dsymonds** [comment]
SELECT list aliases were added in 4052efb (though not FROM aliases), but the error suggests the former isn't working in that case for some reason. I'll look into it.

**Comment by dsymonds** [comment]
Yeah, I just tested parsing exactly that query at HEAD (77944b1), and it fails with `unexpected trailing query contents "AS l WHERE l.user_id=@userID"`, so it seems like you are using an older version of the client library.

The alias for the FROM isn't parsed, so I'll take this issue as a feature request for that.
