### ISSUE TITLE
bigquery: Read fails when Query job is a script

### ISSUE THREAD

**Issue by GlennAmmons** [googleapis/google-cloud-go#1974]
**Client**

BigQuery

**Environment**

Borg

**Code**

```go
q := bigquery.Query(ctx, `
CREATE TEMP TABLE Foo ...;
SELECT * FROM Foo;
`)
job, err := q.Run(ctx)
...
if err := job.Read(ctx); err != nil {
  log.Error("job.Read(ctx): %v", err)
  return err
}
...
```

**Expected behavior**

Read returns the results of the final SELECT statement, as suggested by http://cloud/bigquery/docs/reference/standard-sql/scripting#bigquery-scripting, which says

> When jobs.getQueryResults is invoked on a script, it will return the query results for the last SELECT, DML, or DDL statement to execute in the script, with no query results if none of the above statements have executed. To obtain the results of all statements in the script, enumerate the child jobs and call jobs.getQueryResults on each of them

**Actual behavior**

Read returns an error:

> bigquery: query job missing destination table

**Comment by codyoss** [comment]
cc @shollyman

**Comment by shollyman** [comment]
Thanks for pointing this detail.  This is effectively the same issue as https://github.com/googleapis/google-cloud-go/issues/1960 but I wasn't recognizing the documented expectation that the getQueryResults returns a cursor to a specific child job.

It's problematic as the Go library leverages a reference to the destination table for building/maintaining the row iterator, and neither the parent job nor the getQueryResults response contains the destination reference.

Will need to look at how we can address this in the RowIterator internals.

**Comment by codykaup** [comment]
If you run into this issue like I did, a quick workaround is to wait for the job to complete then refresh your job struct with the query results. Something like this:

```go
q := bigquery.Query(ctx, `
CREATE TEMP TABLE Foo ...;
SELECT * FROM Foo;
`)
job, err := q.Run(ctx)
// Wait for job.Status to be done
_, _ = job.Wait()
// Refresh job to get results
job, err = bigquery.JobFromID(ctx, q.job.ID())
...
it, err := job.Read(ctx)
...
```

**Comment by GlennAmmons** [comment]
shollyman, what do you think of codykaup's workaround? I'm worried that it relies on undocumented behavior.

**Comment by shollyman** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/bigquery%2Fv1.10.0 contains this fix.
