### ISSUE TITLE
Pubsub: dead lettering feature does not work

### ISSUE THREAD

**Issue by okisetiawan0101** [googleapis/google-cloud-go#1977]
I try google pubsub dead lettering.

I use console cloud to enable the dead lettering for 1 subscription. I already set the dead letter topic and maxAttemptDelivery attribute to 5.

My expectation is if 1 message redelivery more than 5 times in 1 subscription, that message will be automatically removed from the subscription queue. But it does not happen, the message still infinite loop in the queue. And when i print the attribute deliveryAttempt, the value always null.

Do I have configure something in the code? Currently I only configure the deadletter in gcp console. I am using golang, google pubsub version 1.3.1

**Comment by codyoss** [comment]
cc @hongalex

**Comment by hongalex** [comment]
Enabling dead lettering in the subscription from the console should work. If possible, could you paste your code so I can reproduce this on my end?

**Comment by hongalex** [comment]
Could you ensure you have [followed the steps to grant permissions to the Pub/Sub service account](https://cloud.google.com/pubsub/docs/dead-letter-topics#granting_forwarding_permissions) properly? If this isn't enabled, dead lettering won't work.

**Comment by okisetiawan0101** [comment]
Hi, i just tried again.
When I create new subscription from google cloud console, there is no problem with the dead lettering feature.

But When I create a new subscription using code with dead lettering disabled, then change it to enable using google cloud console, the dead lettering function doesn't work. The message still sent infinitely to my subscriber.
Is there anything wrong with my configuration? I think the permission already granted, right?
![image](https://user-images.githubusercontent.com/19812372/81847547-f27dc200-957d-11ea-8b5a-d7a79facb6a2.png)
![image](https://user-images.githubusercontent.com/19812372/81847565-f90c3980-957d-11ea-8e8d-3bd8bfb37038.png)

**Comment by hongalex** [comment]
> Is there anything wrong with my configuration? I think the permission already granted, right?

Yeah that looks right

Strange, I can't get a working reproduction with that code still. I created the topic with the Go library and modified it in the console to have dead lettering as you described. Are you perhaps not stopping your application after enabling dead lettering in the Pub/Sub console?

**Comment by okisetiawan0101** [comment]
I already delete my application pods and rebuild again but still not working.
But after I delete my deployment pods in kubernetes, and redeploy the application pod again, now it works. I don't know why like that. So I will close this issue.
Thank you so much.

**Comment by anaspk** [comment]
Here is what I have noticed:
1. If you create a subscription without dead lettering, then edit it and turn dead lettering on, it doesn't work.
2. If you turn dead lettering on at the time of creating subscription, it works fine.
I used GCP console exclusively, didn't use gcloud command for any step.

**Comment by hongalex** [comment]
@anaspk Did you keep the client running while enabling dead lettering? If you have a streaming pull connection open, it doesn't enable dead lettering.

**Comment by anaspk** [comment]
@hongalex Nope, I am pretty sure I restarted the client multiple times after enabling dead lettering.

**Comment by okisetiawan0101** [comment]
@anaspk I face the same problem like you. I already enabling the dead lettering and restart the client multiple times but still not working.
What I do is delete the deployment pods then redeploy again, and this is fix my problems.

**Comment by kkalaiselvan** [comment]
> Could you ensure you have [followed the steps to grant permissions to the Pub/Sub service account](https://cloud.google.com/pubsub/docs/dead-letter-topics#granting_forwarding_permissions) properly? If this isn't enabled, dead lettering won't work.

Hello, I have java API for message subscription. when i disable the dead letter configuration to my subscriber in the google console. i see the messages getting subscibed in my JAVA code but at the same time when i enable dead letter feature , my java subscriber is not subscribing message.  I verified in the console and ensured all the grant permissions has been given to the dead letter topic and subscriber.

**Comment by hongalex** [comment]
Hi, this issue is now closed. If you want to file an issue with the java client library, please do so at https://github.com/googleapis/java-pubsub/issues/new.

Thanks!
