### ISSUE TITLE
datastore: rpc error: code = FailedPrecondition desc = no matching index found.

### ISSUE THREAD

**Issue by macarus0** [googleapis/google-cloud-go#1979]
**Client**

datastore 

**Environment**

AppEngine with Firestore

**Code**
	cloud.google.com/go/datastore v1.1.0
	google.golang.org/appengine v1.6.6

```	
	q := datastore.NewQuery("temperatures").
	Filter("Time >", timestamp).
	Order("-Time")
	temperatures := make([]*temperature, 0)
	_, err := client.GetAll(ctx, q, &temperatures)
	return temperatures, err
```

Document definition

![image](https://user-images.githubusercontent.com/33580338/81491674-db6d6600-9245-11ea-95a4-592cd5a8151c.png)

**Expected behavior**

Query returns successfully

**Actual behavior**

500: rpc error: code = FailedPrecondition desc = no matching index found.

**Additional context**

Queries without a filter return correctly. Attempting to create an `index.yaml` file results in 

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This index:
IndexDef{semantics=DATASTORE, kind=temperatures, indexAncestor=NONE, propertyDefs=[PropertyDef{path=Time, mode=ORDERED, direction=DESCENDING}]}
is not necessary, since single-property indexes are built in. Please remove it from your index file and upgrade to the latest version of the SDK, if you haven't already.
```

**Comment by codyoss** [comment]
cc @BenWhitehead

**Comment by BenWhitehead** [comment]
It looks like the code for your query has a small typo in it. Your query should instead be:
```go
q := datastore.NewQuery("temperatures").
	Filter("time >", timestamp).
	Order("-time")
```

Notice the lowercase `time` which matches the data shown in the Cloud Console. Property names are case sensitive in Datastore, so ensure you're always using the correct case.

The error returned by the `index.yaml` is correct. Indexes (Ascending and Descending) in Datastore are automatically created for each property of your entities, and should not be defined in `index.yaml`. `index.yaml` is intended for when you need to create a compound index. For full details on indexes in Datastore take a look at the [Indexes](https://cloud.google.com/datastore/docs/concepts/indexes) reference docs.

**Comment by macarus0** [comment]
With the function changed to 
`	q := datastore.NewQuery("temperatures").
	Filter("Time >", timestamp).
	Order("-Time")`

I still see the same error
`Could not get recent temperatures: rpc error: code = FailedPrecondition desc = no matching index found.`

**Comment by macarus0** [comment]
With the code changed to 
```
	q := datastore.NewQuery("temperatures").
	Filter("time >", timestamp).
	Order("-time")
	temperatures := make([]*temperature, 0)
	_, err := client.GetAll(ctx, q, &temperatures)
	return temperatures, err
```

I still receive a 500 error 
` rpc error: code = FailedPrecondition desc = no matching index found.`

Removing the Filter condition returns all the values in the datastore for that document type.

**Comment by macarus0** [comment]
It turns out I needed to use the `firestore` library as creating a new datastore defaults to using firestore and only the firestore APIs will work with it.

The following code worked as expected:
```
   iter := client.Collection("temperatures").Where("time", ">=", timestamp).Documents(ctx)
	temperatures := make([]*Temperature, 0)
	// _, err := client.GetAll(ctx, q, &temperatures)
	for {
        doc, err := iter.Next()
        if err == iterator.Done {
                break
        }
        if err != nil {
                return nil, err
		}
		var newTemp Temperature
		doc.DataTo(&newTemp)
        temperatures = append(temperatures, &newTemp)
	}
	return temperatures, nil
```

**Comment by ShahNewazKhan** [comment]
Is there another solution to this without switching out to the `firestore` library?

**Comment by chao-camect** [comment]
@ShahNewazKhan Has you found a solution?
I am afraid when I received the email from Google saying they are automatically converting to firestore...

**Comment by chao-camect** [comment]
Just found that Google started to migrate our production system, while our testing system is still on datastore.
Now, seems I have no choice but to use firestore API. Google is unbelievable!
Lesson learned: avoid Google if you can.
