### ISSUE TITLE
functions/metadata: give access to tracing information via the context

### ISSUE THREAD

**Issue by justinruggles** [googleapis/google-cloud-go#1984]
**Is your feature request related to a problem? Please describe.**
In order to get more useful logging with labels and severity levels, I am using the logging package to send logs to stackdriver rather than writing to stderr/stdout. One difference I've noticed is that the standard logs in stackdriver have a trace attached. It would be nice to get access to that trace in order to add it to the custom logs. It could be that it's already there in the context, but I was not able to find any documentation mentioning it.

**Describe the solution you'd like**
Either add it to Metadata or provide a separate function to get it from the context.

**Describe alternatives you've considered**
I considered generating my own trace for logs within a function invocation, but it wouldn't be associated with the auto-generated logs for execution start/stop.

**Comment by justinruggles** [comment]
Relatedly, there also does not seem to be access to the `execution_id` used in stackdriver logging labels or the function name. I can work around not having the function name by adding an environment variable when deploying the function.

**Comment by codyoss** [comment]
Hey,

Thanks for the request. I think the correct place to ask for this would be: https://issuetracker.google.com/issues/new?component=187195&template=0. This would first need to be exposed by the cloud function to enable grabbing it from the context.

**Comment by tbpg** [comment]
cc @juliehockett

**Comment by codyoss** [comment]
I filed http://issuetracker.google.com/issues/184156866 as I think this is a better place to track this request. Closing this issue.
