### ISSUE TITLE
spanner: session keep-alive seems broken with emulator

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-go#2193]
Based on the conversation [here](https://github.com/googleapis/google-cloud-go/issues/1527#issuecomment-629053985) it seems like the session keep-alive functionality is not working in combination with the emulator.

cc @kanekv

**Comment by skuruppu** [comment]
@agasheesh @snehashah16 would you be able to clarify how the emulator manages sessions?

**Comment by snehashah16** [comment]
AFAIK, we don't (automatically) delete/expire sessions on the emulator. @olavloite - could u please try reproducing this ? I suspect there was an explicit emulator restart in the background or the Go client sent a delete session rpc for all idle sessions.

**Comment by kanekv** [comment]
This happened with me. I will try to get a repro case. I didn't restart emulator.

**Comment by snehashah16** [comment]
@olavloite - does Go client not handle SessionNotFound error ? I recollect Java making the following changes:
- get session from pool and execute rpc
- If rpc returns "Session NotFound", it will try to grab another session from pool and retry rpc
- if there is (eventually) no session in the pool, it will create a new session and retry rpc.

Is this a corner case in Go client where a "Session NotFound" error is returned to the customer application ?

**Comment by snehashah16** [comment]
@kanekv - thanks!

**Comment by olavloite** [comment]
> does Go client not handle SessionNotFound error ?

Yes, we made the same change to the Go client, but there's an issue that the `Session not found` errors returned by the emulator are currently not recognized by the Go and Java clients, as the clients recognize this by looking for a specific `ResourceInfo` object appended to the error (as opposed to checking for a specific error message). The emulator does not return that information (yet), but AFAIK someone is working on that.

**Comment by snehashah16** [comment]
@olavloite - thank u for confirming! Yes, ResourceInfo will be populated in the emulator response with the next emulator release.

**Comment by hengfengli** [comment]
@olavloite Can you confirm that this issue has been resolved?

**Comment by olavloite** [comment]
> @olavloite Can you confirm that this issue has been resolved?

No. There are two issues here:
1. The emulator currently does not return `ResourceInfo` for `Session not found` errors, which means that the Go and Java client won't recognize these errors as actual `Session not found` errors. That will be fixed by the next emulator release and should not require any action in the client library.
1. The problem noted in https://github.com/googleapis/google-cloud-go/issues/1527#issuecomment-629053985 seemed to indicate that the current keep-alive functionality in the Go client does not work with the emulator. On the other hand, it seems that the emulator is not automatically timing out any sessions that have not been used for a while, so that would on the other hand indicate that the issue was caused by something else.

I'll try to reproduce the second issue with the Go client and the emulator.

**Comment by olavloite** [comment]
I have not been able to reproduce the second issue above, even after keeping a client open for more than 3 hours and then doing a query. Closing for now as there does not seem to be anything actionable here at the moment, as the `ResourceInfo` fix will come from the emulator.

**Comment by hengfengli** [comment]
Thanks for checking.
