### ISSUE TITLE
spannertest: [BUG] TIMESTAMP comparison is lexicographic

### ISSUE THREAD

**Issue by gdbelvin** [googleapis/google-cloud-go#2195]
The in-memory test database implementation stores TIMESTAMP types as strings, rather than `time.Time` internally. This results in incorrect sorting and key range selection behavior from [`compareVals`](https://github.com/googleapis/google-clou-go/blob/master/spanner/spannertest/db_eval.go#L496)

Timestamps with trailing zeros in the nanosecond position get sorted lexicographically rather than numerically: [Go Playground](https://play.golang.org/p/OODsktN8L_7)
```
Sorted strings: [2020-01-02T00:03:04.100001Z 2020-01-02T00:03:04Z]
Sorted times:   [2020-01-02T00:03:04Z 2020-01-02T00:03:04.100001Z]
```

**Code**
https://github.com/googleapis/google-cloud-go/pull/2194

**Expected behavior**

`2020-01-02T00:03:04Z` comes before `2020-01-02T00:03:04.100001Z`

**Actual behavior**

`2020-01-02T00:03:04.100001Z` comes before. `2020-01-02T00:03:04Z`

**Screenshots**

https://github.com/googleapis/google-cloud-go/pull/2194

```
--- FAIL: TestKeyRange (0.00s)
    db_test.go:1042: keyRange [[A 2020-01-02T00:03:04.000001Z],[A 2020-01-02T00:03:04.100001Z]] does not include [A 2020-01-02T00:03:04.1Z]
```

**Comment by dsymonds** [comment]
Good spot. I had expected every serialisation of a TIMESTAMP value to have the same format, which would have kept semantic and lexicographic ordering equivalent, but it appears that is not the case.

**Comment by dsymonds** [comment]
Fix in https://code-review.googlesource.com/c/gocloud/+/56476. Test it out yourself if you'd care to verify in your specific codebase.

**Comment by gdbelvin** [comment]
@dsymonds I have confirmed that this resolves the issue I reported.  Thanks!

**Comment by gdbelvin** [comment]
@dsymonds A release that contains this bug fix would be very helpful.

**Comment by olavloite** [comment]
cc @hengfengli
