### ISSUE TITLE
Spansql: Parser crash

### ISSUE THREAD

**Issue by AdamKorcz** [googleapis/google-cloud-go#2196]
This bug was found using a fuzzer that has been uploaded to oss-fuzz.

**Stack trace**

`panic: runtime error: slice bounds out of range [2:1]

goroutine 17 [running, locked to thread]:
cloud.google.com/go/spanner/spansql.(*parser).skipSpace(0x10c0001dee60, 0x61a)
        cloud.google.com/go/spanner/spansql/parser.go:725 +0xe45
cloud.google.com/go/spanner/spansql.(*parser).advance(0x10c0001dee60)
        cloud.google.com/go/spanner/spansql/parser.go:747 +0x51
cloud.google.com/go/spanner/spansql.(*parser).next(0x10c0001dee60, 0x10c0001dedd8)
        cloud.google.com/go/spanner/spansql/parser.go:846 +0x66
cloud.google.com/go/spanner/spansql.(*parser).expect(0x10c0001dee60, 0x64090f, 0x6, 0x10c0001e4540)
        cloud.google.com/go/spanner/spansql/parser.go:888 +0x43
cloud.google.com/go/spanner/spansql.(*parser).parseQuery(0x10c0001dee60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        cloud.google.com/go/spanner/spansql/parser.go:1564 +0x9b
cloud.google.com/go/spanner/spansql.ParseQuery(0x10c0000b0480, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        cloud.google.com/go/spanner/spansql/parser.go:171 +0xd3
cloud.google.com/go/spanner/fuzz.Fuzz(...)
        cloud.google.com/go/spanner/fuzz/fuzz.go:20`

**Environment**

oss-fuzz's Docker image

**Code**

Specifically the fuzzer finds a crash on line 725 in spanner/parser.go:

https://github.com/googleapis/google-cloud-go/blob/d4fd4ca5f2c0ffa59e15de2c41da87c5cf6f85e0/spanner/spansql/parser.go#L725

**Payloads**

Here are sample payloads:
1. `/*/*Ä&`
2. `/*/*/`
3. `/*/*^A<82><91>Ä^A<82><91>ÄA<80>`
The project can also be fuzzed with the fuzzer from the PR on oss-fuzz. The bug is found after a few seconds.

**Extra**

To integrate into oss-fuzz, at least one contact email address for maintainers are needed. I would appreciate input on which to add, in case integration is desirable.

**Comment by dsymonds** [comment]
Fix in https://code-review.googlesource.com/c/gocloud/+/56477.

Thanks for the report!

**Comment by AdamKorcz** [comment]
My pleasure!
