### ISSUE TITLE
logging: New release to fix a bug

### ISSUE THREAD

**Issue by ernestoalejo** [googleapis/google-cloud-go#2198]
**Client**
Logging

**Expected behavior**
A new release with this merged fix: https://github.com/googleapis/google-cloud-go/issues/1597

The last release was v1.0.0; Jul 18, 2019: https://pkg.go.dev/cloud.google.com/go/logging@v1.0.0/logadmin?tab=versions

**Actual behavior**
`unknown payload type: <nil>` when trying to access Cloud Run logs with v1.0.0 of this library

**Comment by codyoss** [comment]
Thanks for the reminder! I will get something out this week for logging.

**Comment by codyoss** [comment]
Logging has been had a release since last posing. Closing.
