### ISSUE TITLE
bigquery: allow specifying insertID when passing struct to Put()

### ISSUE THREAD

**Issue by darwinyip** [googleapis/google-cloud-go#2200]
**Is your feature request related to a problem? Please describe.**
The current implementation of `Put()` can take in a slice of `ValueSavers`, structs, or struct pointers. However, only `insertID` can be specified when constructing the data using ValueSavers.

**Describe the solution you'd like**
If a struct contains the field `insertID`, use it as the `insertID` when converting to `ValueSaver`.

**Comment by AlisskaPie** [comment]
We've discussed this feature request with Seth Hollyman, the main googler on BigQuery.
Shortly, there's no necessary to maintain insertID in struct. 
Here's the explanation:
* InsertID is best-effort, and provides no guarantees around the idempotence of inserts.  It's merely probabilistic.   
* For post-insertion deduplication you still need something akin to a unique identifier in the data itself (the insertID is not persisted).
* By _not_ specifying insertID, you get higher throughput: https://cloud.google.com/bigquery/streaming-data-into-bigquery#disabling_best_effort_de-duplication
* There's a new streaming API coming as part of the storage API work which is meant to help users achieve exactly once insertion semantics, which is currently impossible to do using the existing tabledata.insertAll API semantics.  You can see the primitives in storage v1alpha2 which is under heavy development (most of the work is focused on java initially).

**Comment by darwinyip** [comment]
Thanks for reply. Looking forward to this new API.
