### ISSUE TITLE
Datastore: exponential backoff retries on failure

### ISSUE THREAD

**Issue by Kur-Ich** [googleapis/google-cloud-go#2204]
I can't find any info on this but I read Cloud Storage implements exponential backoff when requests return with a network type error. It would be good to have some functionality in the Go Datastore driver so that it is easy to configure for how many seconds exponential backoff should be implemented in case the request fails due to some sort of connection problem.

**Comment by codyoss** [comment]
Could you provide a specific example of the type of error you expect to see retried? The datastore client does retry on Unavailable: https://github.com/googleapis/google-cloud-go/blob/master/datastore/client.go#L116-L119

**Comment by Kur-Ich** [comment]
Thanks for clarifying - that's great. Sorry, I missed this originally.
