### ISSUE TITLE
trace: Support for opentelemetry tracing

### ISSUE THREAD

**Issue by cmouli84** [googleapis/google-cloud-go#2205]
**Is your feature request related to a problem? Please describe.**
I am instrumenting trace using opentelemetry library in application that uses google cloud resources. Since google cloud library instruments trace using [opencensus](https://github.com/googleapis/google-cloud-go/blob/master/internal/trace/trace.go#L29), I do not see spans for interactions with google cloud resources (e.g. _cloud.google.com/go/spanner.ReadWriteTransaction_)

**Describe the solution you'd like**
[Trace package](https://github.com/googleapis/google-cloud-go/blob/master/internal/trace/trace.go) to be updated to propagate both opencensus and opentelemetry Span in context and export it to registered Exporter/SpanProcessor

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by codyoss** [comment]
@cmouli84 thanks for your interest in tracing. This client is auto-generated. If you would like a feature added to it the best place to express that would be https://issuetracker.google.com/issues/new?component=187216&template=0.
Thanks.
