### ISSUE TITLE
all: investigate using release-please for releases

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#2207]
release-please can help automate the release process.

Can/should we use it for Go?

release-please can generate changelogs if the repo follows https://www.conventionalcommits.org/en/v1.0.0/. But, we only include the scope (the affected package), not the type. See https://github.com/golang/go/wiki/CommitMessage.

cc @codyoss @broady @bcoe

**Comment by broady** [comment]
We need to wait until we migrate to GitHub, right?

**Comment by codyoss** [comment]
> Can/should we use it for Go?

I am hesitant to say yes. Unlike other languages Go has its own conventional commit message style that many have bought into as you mentioned with your link. Both the apiaries and and core module of google-cloud-go have no plans, as of right now, to go v1 so a breaking change might not mean a version bump(we put breaking changes under a different import path right now)((Eventually we should call out how we do major version with depreciation somewhere...))

With that said, automated releases sound quite nice, and I dislike writing CHANGELOGs 😸  

> We need to wait until we migrate to GitHub, right?

Yes.

> We just did it for google-api-go-client. Could we try release-please there?

Yeah, if we are going to use conventional commits I would want to make sure we are consistent and use it everywhere in that case.

______

**Comment by bcoe** [comment]
> I am hesitant to say yes. Unlike other languages Go has its own conventional commit message style 

@codyoss, I had a conversation with @tbpg about this ... I have a preference for conventional commit messages... the addition of `feat` and `fix` to your commit message makes it really easy to determine library version, and decide on version bumps...

However, I also hate the idea of us deviating from the community. We could look at extending `release-please` to make the commit analyzer extensible, and add go format commits.

**Comment by broady** [comment]
don't think we need anything special for version bumps. a major version change is a far more significant change in the Go ecosystem than others. we pretty much always use minor versions.

**Comment by codyoss** [comment]
We have an initial imlp of this working now. Although there is an open PR to fix a bug: googleapis/release-please#520. If that looks good the next thing to do will be getting this to work for the sub-modules too. Right now this will only work for the root module.

**Comment by codyoss** [comment]
Release please is now set up for all modules!
