### ISSUE TITLE
spanner emulator: The emulator only supports one transaction at a time.

### ISSUE THREAD

**Issue by kanekv** [googleapis/google-cloud-go#2209]
When test fails (for example panic), emulator becomes unusable, any update queries return `The emulator only supports one transaction at a time.`. Seemingly the only way to recover is to restart emulator...

**Comment by olavloite** [comment]
It is a known limitation that the emulator only supports one transaction at a time. There is not very much we can do about that in the client library.

See https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/blob/master/README.md#features-and-limitations for a full list of limitations.

**Comment by kanekv** [comment]
@olavloite this question is more about transaction being stuck on the emulator and doesn't seem to rollback/release even when app that started it - died.

**Comment by olavloite** [comment]
> @olavloite this question is more about transaction being stuck on the emulator and doesn't seem to rollback/release even when app that started it - died.

Could you supply a concrete example of a transaction that shows this behavior?

I don't think transactions get stuck on the emulator, but what is possible is an infinite loop of transactions that are being aborted. The emulator only supports one transaction at a time, and if you start a second (or more) transaction, that transaction will automatically be aborted by the emulator. The client library will automatically retry any transaction that is aborted, which again will be aborted etc. This could probably also happen if you stop your application while a read/write transaction was still in progress. The emulator will consider that transaction as still running and valid, as it has not yet been committed or rollbacked, and any new transaction that is started by the same or any other client application will automatically be aborted.

**Comment by kanekv** [comment]
Got it, thanks!
