### ISSUE TITLE
transaction.BatchUpdate panics with nil pointer error

### ISSUE THREAD

**Issue by kanekv** [googleapis/google-cloud-go#2210]
Same statements worked when I executed them in a loop with singular `.Update` - executed in test, using emulator.

**Comment by olavloite** [comment]
The emulator does not return an explicit `Status OK` when a batch DML statement succeeds. The Go client expects this (as Cloud Spanner does return that), and thereby causes a panic as it does not check for the possibility of the backend returning a `nil` status. This means that all successful Batch DML statements will fail when using the Go client, while Batch DML statements that contain an error will behave (largely) as Batch DML statements that are sent to Cloud Spanner.

**Comment by kanekv** [comment]
Should we try to fix this in client or better if emulator addresses it?

**Comment by olavloite** [comment]
> Should we try to fix this in client or better if emulator addresses it?

Preferably both, but I don't think this will have a high prio for the emulator itself, as this already works for other client libraries.

**Comment by olavloite** [comment]
https://code-review.googlesource.com/c/gocloud/+/56792
