### ISSUE TITLE
Empty ReadWriteTransaction is very slow

### ISSUE THREAD

**Issue by kanekv** [googleapis/google-cloud-go#2211]
It seems just calling `ReadWriteTransaction` has a pretty big latency. 
I have returned nil immediately inside `ReadWriteTransaction` and it took on average 75ms.
Is it expected?

**Comment by olavloite** [comment]
@kanekv 
The latency will depend on a number of factors, so whether this is as expected or not does depend on your setup. An empty transaction will at least need to execute a `Commit` RPC, and possibly also a `BeginTransaction` RPC, depending on your configuration and the specific code.

The most important factors that influence the latency would be:
1. Where is your client running and where is your Spanner instance located? If for example your client is running on your local machine, and you are connecting to a Spanner instance located on a different continent, the latency for each RPC can of course be high. Locating your client code and Spanner instances as close as possible to each other will reduce latency, for example by running your client application on a VM in the same gcloud project and region as where you have created your Spanner instance.
1. What is the configuration you are using to connect to Spanner? Do you use the default client configuration, or have you set a custom configuration. In the latter case, did you set a specific value for `WriteSessions`?
1. The first read/write transaction that you execute using a Spanner client can experience a higher latency than later transactions. When you create a Spanner client, it will start creating a session pool and fill this pool with read-only and write-prepared sessions. It can take some tens of milliseconds before the pool has been filled with write-prepared sessions, and if you try to execute a read/write transaction during this initialization, the total execution time of the transaction will be higher than for transactions that are executed once the pool has been completely filled up and initialized.

**Comment by kanekv** [comment]
@olavloite thanks for your answer! I think I should close this issue as it seems it's not a ReadWriteTransaction problem, any inserts from spanner console execute upwards from 70ms.
So I guess it's not related to anything that go driver is doing.
