### ISSUE TITLE
monitoring: support for dashboard API

### ISSUE THREAD

**Issue by zsais** [googleapis/google-cloud-go#2213]
**Describe the solution you'd like**
It's now possible to manage Dashboards via the Cloud Monitoring API. Can we bring that functionality to the client library?

**Additional context**
https://cloud.google.com/monitoring/api/ref_v3/rpc
https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.dashboard.v1

**Comment by codyoss** [comment]
I believe the API you are looking for is generated under [another repo](https://github.com/googleapis/google-api-go-client): [ProjectsDashboardsService](https://pkg.go.dev/google.golang.org/api@v0.25.0/monitoring/v1?tab=doc#ProjectsDashboardsService )

**Comment by swarren83** [comment]
@codyoss That package may work but according to the overview `This package is DEPRECATED. Use package cloud.google.com/go/monitoring/apiv3 instead.`. Is it possible to get that functionality in the apiv3 monitoring package?

**Comment by codyoss** [comment]
@swarren83 Possibly. That would be up to the backend product team. If that is something you would like to request I suggest reaching out through the [Cloud Issue Tracker](https://issuetracker.google.com/issues/new?component=187228&template=0).

**Comment by codyoss** [comment]
google.golang.org/api/monitoring/v1 Has been un-deprecated as it has unique functionality not covered by the monitoring client in this repository. For now, that is only way we are supporting the dashboard API.
