### ISSUE TITLE
bigtable: Method to test connection to an instance

### ISSUE THREAD

**Issue by kshitij10496** [googleapis/google-cloud-go#2386]
**Is your feature request related to a problem? Please describe.**
While implementing the readiness checks for services using BigTable, I have to find ad-hoc ways to verify that the connection is still alive.

**Describe the solution you'd like**
Is there a way to implement functionality similar to ping the instance (similar to `PingContext` provided by `database/sql` package)? I could be totally wrong about here but I would love to know why this could not be supported.

**Describe alternatives you've considered**
- Write a query to read random rows from a table on the instance.

**Additional context**
I'm curious to know what is the recommended way to test whether the instance is ready or not.

**Comment by tritone** [comment]
Adding @kolea2 who has more context on bigtable to answer this.

**Comment by igorbernstein2** [comment]
Currently we don't have an RPC for a noop. I think the method you tried is the best way forward:

ReadRowsRequest for a non-existent row with a block all filter

**Comment by tritone** [comment]
I'm going to close this based on @igorbernstein2 's comment. Conferred with @kolea2 and we don't have plans to add an additional method for this at this time.
