### ISSUE TITLE
cloudbuild: getting 502 errors

### ISSUE THREAD

**Issue by Disturbing** [googleapis/google-cloud-go#2396]
**Client**

Cloudbuild

**Environment**

Mac 10.15.4
golang 1.13

**Code**
```go
import 	cloudbuild "cloud.google.com/go/cloudbuild/apiv1/v2"

...
func ....

buildRequest := &api.CreateBuildRequest{
		ProjectId: serviceAccount.ProjectId,
		Build: &api.Build{
			Steps:      steps,
			LogsBucket: "gs://" + config.CloudBuildLogsBucketName,
			Options: &api.BuildOptions{
				SubstitutionOption: api.BuildOptions_ALLOW_LOOSE,
				LogStreamingOption: api.BuildOptions_STREAM_ON,
				Logging:            api.BuildOptions_GCS_ONLY,
			},
			Substitutions: map[string]string{
				"_KINTO_AGENT_HOST_NAME": config.KintoAgentHostname,
			},
			Timeout: &duration.Duration{
				Seconds: int64(config.WorkflowTimeout),
			},
		},
	}

	logger.Debugf("Submitting CloudBuild request %v", buildRequest)
	resp, err := buildClient.CreateBuild(context.Background(), buildRequest)
```

**Expected behavior**

Successfully start the build

**Actual behavior**

```
{"level":"error","error":"rpc error: code = Unavailable desc = 502:Bad Gateway","time":"2020-06-03T15:16:12+08:00","message":"Error during call"}
```

**Additional context**

Works randomly on June 3, 2020 - and works when running on GKE cluster, but not from remote machine.

**Comment by codyoss** [comment]
Hey,
Thanks for reaching out. Generally speaking these types of errors can occur with network hiccups and/or proxy or firewall issues. As to why it does not work on your local machine are you behind a proxy/firewall? If so sometime opening up some rules or making use of the documented environment variables in the net/http package can help: https://golang.org/pkg/net/http/#ProxyFromEnvironment.

**Comment by codyoss** [comment]
Closing do to lack of response. If you are still having issues please feel free to re-open.
