### ISSUE TITLE
Dialogflow: Set a platform when calling DetectIntent

### ISSUE THREAD

**Issue by Sylvain2703** [googleapis/google-cloud-go#2400]
**Client**
Dialogflow v2 gRPC

**Environment**
Local Windows 10 build 18363 x64

**Code**
```go
package main

import (
	dialogflow "cloud.google.com/go/dialogflow/apiv2"
	"context"
	"encoding/json"
	"fmt"
	dialogflowpb "google.golang.org/genproto/googleapis/cloud/dialogflow/v2"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/types/known/structpb"
)

func main() {
	ctx := context.Background()

	sessionClient, err := dialogflow.NewSessionsClient(ctx)
	if err != nil {
		fmt.Println("NewSessionsClient error:", err)
		return
	}
	defer sessionClient.Close()

	payloadJSON := `{ "source": "facebook" }`

	var payloadStruct structpb.Struct
	err = protojson.Unmarshal([]byte(payloadJSON), &payloadStruct)
	if err != nil {
		fmt.Println("protojson.Unmarshal error:", err)
		return
	}

	request := dialogflowpb.DetectIntentRequest{
		Session: fmt.Sprintf("projects/%s/agent/sessions/%s", "<project-id>", "1234567890"),
		QueryInput: &dialogflowpb.QueryInput{
			Input: &dialogflowpb.QueryInput_Text{
				Text: &dialogflowpb.TextInput{
					Text:         "Au revoir",
					LanguageCode: "fr",
				},
			},
		},
		QueryParams: &dialogflowpb.QueryParameters{
			Payload: &payloadStruct,
		},
	}

	response, err := sessionClient.DetectIntent(ctx, &request)
	if err != nil {
		fmt.Println("DetectIntent error:", err)
		return
	}

	responseJSON, err := json.MarshalIndent(response, "", "  ")
	if err != nil {
		fmt.Println("json.MarshalIndent error:", err)
		return
	}

	fmt.Println("Dialogflow response:", string(responseJSON))
}
```

**Expected behavior**
`DetectIntent` returns a response where the WebhookPayload is adapted to Facebook Messenger.
This behavior is not really documented but according to [this StackOverflow post](https://stackoverflow.com/a/52397506), it should work.

**Actual behavior**
`DetectIntent` returns a response without Facebook Messenger specific payload.
Here is a response:
```JSON
{
  "response_id": "<response-id>",
  "query_result": {
    "query_text": "Au revoir",
    "language_code": "fr",
    "parameters": {},
    "all_required_params_present": true,
    "fulfillment_text": "A très vite",
    "fulfillment_messages": [
      {
        "Message": {
          "Text": {
            "text": [
              "A très vite"
            ]
          }
        }
      },
      {
        "Message": {
          "Image": {
            "image_uri": "https://media.giphy.com/media/crpEBn4lPYLkY/giphy.gif"
          }
        },
        "platform": 1
      }
    ],
    "intent": {
      "name": "projects/<project-id>/agent/intents/<intent-id>",
      "display_name": "Bye"
    },
    "intent_detection_confidence": 1
  }
}
```

**Additional context**
Unfortunately, I cannot use the Messenger integration due to [Custom Integration restrictions on Workplace Chat](https://developers.facebook.com/docs/workplace/custom-integrations-new/deactivation-policy)

**Comment by codyoss** [comment]
Looking at that post quick I think you would want payloadJSON to look like this: `{ "source": {"stringValue": "facebook", "kind": "stringValue"}}`

**Comment by Sylvain2703** [comment]
Thanks @codyoss for your answer.

I think, I don't have to do something like that since the protobuf librairie is in charge to do it (`protojson.Unmarshal` function of `google.golang.org/protobuf/encoding/protojson`).

Anyway, I already tried (and just retried) with:
```go
payloadJSON := `{ "source": {"stringValue": "facebook", "kind": "stringValue" } }`
```
and
```go
payloadJSON := `{ "fields": { "source": {"stringValue": "facebook", "kind": "stringValue" } } }`
```
None of these gave me any result.

**Comment by codyoss** [comment]
I am not super familiar with this API. For better support on this issue I would suggest reaching out for help with one of the methods documented on the dialogflow support page: https://cloud.google.com/dialogflow/docs/support/getting-support

**Comment by Sylvain2703** [comment]
Ok thanks, I will contact them and keep this issue updated.

**Comment by codyoss** [comment]
Closing this issue as I don't think there is anything to do from this repositories perspective. Still feel free to update the issue if you get more details down the road to help others in the future. Thanks.
