### ISSUE TITLE
`go get` fails with "disagree about go-import for cloud.google.com/go"

### ISSUE THREAD

**Issue by shonfeder** [googleapis/google-cloud-go#2409]
**Client**

firestore (but happening on any package with this dependency)

**Environment**

```
$ uname -a
Linux comp 5.4.43-1-MANJARO #1 SMP PREEMPT Wed May 27 20:25:12 UTC 2020 x86_64 GNU/Linux

$ go version
go version go1.14.4 linux/amd64
```

**Code**

```
go get cloud.google.com/go/firestore
```

**Expected behavior**

The expected package is obtained.

**Actual behavior**

Fails with

```
unrecognized import path "cloud.google.com/go/firestore": https://cloud.google.com/go/firestore?go-get=1 and //cloud.google.com/go?go-get=1 disagree about go-import for cloud.google.com/go
```

**Comment by tbpg** [comment]
Thanks for the report. We're in the process of updating the source of truth for this repo to GitHub.

Are you using a `GOPROXY`? If so, that should work around this issue while we sort out getting these pages updated.

**Comment by shonfeder** [comment]
I'm not using `GOPROXY`. Any pointers towards a resources explaining how to set that up to fix this?

**Comment by tbpg** [comment]
```
export GOPROXY=https://proxy.golang.org,direct
```

This is the default value for Go 1.13+.

**Comment by broady** [comment]
Sorry about that. We're moving the repo and this error is an accident. It should be resolved in the next few minutes.

**Comment by mconbere** [comment]
This also appears to impact deployment to App Engine Standard with go1.11, which uses Cloud Build. I don't believe it is possible as a user of App Engine to modify the build settings for App Engine apps to include a `GOPROXY` environment variable, so the workaround isn't available for us. Do you have a timeline for resolving this outage or a workaround for App Engine deployment?

**Comment by liyanhui1228** [comment]
To confirm, is this issue already being fixed?

**Comment by broady** [comment]
Should be fixed. I have verified the correct metadata is now being served.

**Comment by tbpg** [comment]
`GOPROXY=direct go get cloud.google.com/go` works locally for me.

**Comment by juliehockett** [comment]
Cloud Functions and AppEngine deployments appear to be back, as well.
