### ISSUE TITLE
pubsub/pstest: allow using a fake clock

### ISSUE THREAD

**Issue by vriesk** [googleapis/google-cloud-go#2421]
**Describe the solution you'd like**

I would like the 'pstest' package accept a fake clock implementation (possibly just time.Now()-equivalent functor) instead of hardcoding time.Now() inside.

This will allow precise testing of interactions with the Pub/Sub client, including timing.

**Comment by IlyaFaer** [comment]
@vriesk, looking at this code:
https://github.com/googleapis/google-cloud-go/blob/124b5702eff3ac831ddcea3c7771f43111d8dd26/pubsub/pstest/fake.go#L45-L58

I suspect that thing you're searching for can be achieved by something like that:
```go
now.Store(timeFunc)  // where timeFunc is a time.Now-like function
```
Didn't you try that yet?

**Comment by vriesk** [comment]
No, this is module-private and can't be used externally.

Also, module-global variables like that won't make parallel testing possible, so it should be Server (or GServer) member variable instead.
