### ISSUE TITLE
secretmanager: permission errors when run within google cloud function

### ISSUE THREAD

**Issue by baldrich-randori** [googleapis/google-cloud-go#2426]
**Client**

Querying a secret from the command line works as expected with gcloud auth login or a service token but when I use this library I can not authenticate when running in a google cloud function.

**Environment**
go 1.13 in google cloud function.

**Go Environment**

$ go 1.13

**Code**
```
func GetSecret(projectID string, secretName string, version string) (secret string, err error) {
	ctx := context.Background()
	client, err := secretmanager.NewClient(ctx)
	if err != nil {
		log.Fatalf("failed to setup secret client: %v", err)
	}
	secretPath := fmt.Sprintf("projects/%s/secrets/%s/versions/%s", projectID, secretName, version)
	// Build the request.
	accessRequest := &secretmanagerpb.AccessSecretVersionRequest{
		Name: secretPath,
	}

	// Call the API.
	result, err := client.AccessSecretVersion(ctx, accessRequest)
	if err != nil {
		log.Fatalf("failed to access secret version: %v", err)
	}
	return result.String(), err
```

**Expected behavior**

I expected it to use the cloud function service account the same way it works with pubsub and gcs. 

**Actual behavior**
```
failed to access secret version: rpc error: code = PermissionDenied desc = Permission denied on  resource project <project name>"
```

**Screenshots**

N/A

**Additional context**

Is it possible that I need to manually grab my services token and then supply it to the client when initializing?

**Comment by codyoss** [comment]
If you add `roles/secretmanager.secretAccessor` to the service account used by the cloud function, that should do the trick 😄

**Comment by baldrich-randori** [comment]
I did that and it still failed, I am able to use it locally from gcloud with that service token but it doesn't work when running in a cloud function.

**Comment by tbpg** [comment]
Did you add the permission to the service account that the Cloud Function is running as? See https://cloud.google.com/functions/docs/securing/function-identity. You can either add the permission to the default account, or create a custom account and set it as the identity for this function.

**Comment by codyoss** [comment]
Closing due to lack of response. I believe the solution posted above should work for you.
