### ISSUE TITLE
pubsub: High Latency of pubishing message

### ISSUE THREAD

**Issue by deepakvarshney** [googleapis/google-cloud-go#2428]
**Client**

PubSub

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

$ go version = 1.14.3
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/deepak/Library/Caches/go-build"
GOENV="/Users/deepak/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/tokopedia"
GONOSUMDB="github.com/tokopedia"
GOOS="darwin"
GOPATH="/Users/deepak/go"
GOPRIVATE="github.com/tokopedia"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="****/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n_/tjh8wnq91cs62fc7l_w_1gv40000gn/T/go-build250547635=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

func main() {
	// ...
}
```

**Expected behavior**

Messages publish latency should remain low all the time.

**Actual behavior**

Messages publish latency high sometimes.

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

Hi Team,
We were using go version 1.10.4 and google cloud library version **0.43.0**
Publish latency was high many times in a day.
```
Pubsub Settings at that time:
    DelayThreshold = 4
    CountThreshold = 50
    ByteThreshold = 1000000
    NumGoroutines = 70
    Timeout = 54
```
Google Cloud support team suggest us to update our google cloud library version to **0.56.0.**
We updated it and issue was gone.

Recently, we updated our golang version to 1.14.3 and this issue again started to appear once in a day. If we change some settings and restart the server, issue gets fixed.
These are the dependencies that were imported.
```
cloud.google.com/go/bigquery v1.8.0
	cloud.google.com/go/bigtable v1.3.0
	cloud.google.com/go/pubsub v1.4.0
	cloud.google.com/go/storage v1.8.0
```
Latency goes upto 1-2 sec and does not drops which effects our system until we change pubSub setting and restart server. 
We publish at the rate of 3k messages/sec on 2 topics.
We have 38 other topics on which we publish with less rate 100 messages/sec.
We have  4 servers with config 4 cores(8CPU) and 16 gb RAM.

Please help.
Let me know if logs are required. I generated using gops tool. Thanks in advance.

**Comment by hongalex** [comment]
Yeah, any logs would be great!

So updating google-cloud-go to v0.56.0 doesn't affect pubsub, since the pubsub library is now it's own submodule. I recommend pinning to v1.3.1 to see if that resolves anything. You can do this by adding `cloud.google.com/go/pubsub v1.3.1` to your `go.mod` file.

**Comment by deepakvarshney** [comment]
Hi @hongalex ,
We already are using latest version.
`cloud.google.com/go/bigquery v1.8.0
	cloud.google.com/go/bigtable v1.3.0
	cloud.google.com/go/pubsub v1.4.0
	cloud.google.com/go/storage v1.8.0`

Here is the trace
https://drive.google.com/file/d/1beoX3NuCA7y-siJ0p4_SEhLZ0oZEirD3/view?usp=sharing

**Comment by hongalex** [comment]
Due to the somewhat sensitive nature of the logs, I've deleted the comment for now. Rest assured, I've had the ability to look at the logs already. At this moment, I believe that the issue might not related to the client libraries (or dependencies) and the best channel is to continue to communicate through Cloud Support (I have been and will continue monitoring from that side).
