### ISSUE TITLE
Add support for enabling services

### ISSUE THREAD

**Issue by tj** [googleapis/google-cloud-go#2445]
I don't see a package for working with services, in my case just enabling them like you would with `gcloud services enable ...`.

**Describe the solution you'd like**
I'd love to have SDK access to this.

**Describe alternatives you've considered**
I'm currently using `gcloud`, but I don't want to require that my customers have `gcloud` enabled as it's quite cumbersome to install and configure, ideally I could just distribute my Go binary without relying on external tools.

Thanks!

**Comment by tj** [comment]
Looks like interactions with projects are missing as well

**Comment by tj** [comment]
ok I'm confused haha, I see them here https://github.com/googleapis/google-api-go-client, but why are there two SDKs?

**Comment by tbpg** [comment]
Thanks for filing the issue. I'm glad you got it figured out. Looks like https://pkg.go.dev/google.golang.org/api@v0.26.0/cloudresourcemanager/v2?tab=doc might be what you're looking for. But, I don't see an API for enabling APIs there. Did you find a package that does what you need?

cloud.google.com/go (this repo) contains "Cloud Client Libraries," which are gRPC-based clients for Google Cloud APIs.

google.golang.org/api (the https://github.com/googleapis/google-api-go-client repo) contains HTTP-based clients for Google (not just Cloud).

In general, prefer the gRPC clients as they have a nicer generated API, sometimes have hand-written wrappers, and should have better performance. However, some APIs only have the HTTP-based google.golang.org/api clients (like this one).

See https://cloud.google.com/apis/docs/client-libraries-explained for more detail.

**Comment by tbpg** [comment]
https://pkg.go.dev/google.golang.org/api@v0.26.0/servicemanagement/v1?tab=doc#ServicesService.Enable appears to be the function to enable an API.

**Comment by tj** [comment]
awesome yea thanks! Took a little bit to find it, from Googling the SDK I landed here so I didn't end up seeing the overview of the various repos
