### ISSUE TITLE
storage: Bucket.Update unable to remove struct attributes like Lifecycle

### ISSUE THREAD

**Issue by jkwlui** [googleapis/google-cloud-go#2450]
**Client**

Storage

**Environment**

Local/CI

**Go Environment**

$ go version
> go version go1.13 darwin/amd64
$ go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jonathanlui/Library/Caches/go-build"
GOENV="/Users/jonathanlui/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jonathanlui/.gvm/pkgsets/go1.13/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jonathanlui/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jonathanlui/.gvm/gos/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jonathanlui/google-cloud-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n6/18rlmblj2gdd6l1mk2ltfjv000j4bn/T/go-build961219203=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

https://github.com/GoogleCloudPlatform/golang-samples/blob/197a823bf6a5191e2aa113d12d3d7e7548c92dc6/storage/buckets/disable_bucket_lifecycle_management.go#L42-L46

**Expected behavior**

Setting an empty struct in a BucketAttrsToUpdate would result in `null` being sent as part of the PATCH JSON API, removing the field from the remote object.

**Actual behavior**

The Lifecycle metadata is not removed in the remote object since the go client never included `"lifecycle": null` in the PATCH request.

**Comment by tritone** [comment]
Submitted a change that will fix this by adding lifecycle to forceSendFields if the user sets an empty struct. Will be released in the next release of storage (hopefully later today).
