### ISSUE TITLE
pubsub: Pub/Sub lite support

### ISSUE THREAD

**Issue by syucream** [googleapis/google-cloud-go#2456]
**Is your feature request related to a problem? Please describe.**
Pub/Sub Lite is available now as a beta service. I prefer to try that.
https://cloud.google.com/pubsub/lite/docs/reference/rest?hl=en

**Describe the solution you'd like**
Add the feature to existing `pubsub` package or create `pubsublite` new package?

**Comment by hongalex** [comment]
Hi! Thanks for filing this issue. Pub/Sub Lite is currently available in [Java](https://github.com/googleapis/java-pubsublite), but we're looking to provide support for other languages soon. We're still trying to figure out the best way to prioritize this, so unfortunately I can't give an ETA on when this will be available. With that said, it's something that's on our radar, so thanks for creating this issue.

For others, please thumbs up this issue so we can properly track demand for the feature going forward.

**Comment by anguillanneuf** [comment]
@manuelmenzella-google @kir-titievsky

**Comment by hongalex** [comment]
As an update for people following, we currently have the [Pub/Sub Lite autogenerated library](https://pkg.go.dev/cloud.google.com/go/pubsublite/apiv1?tab=doc) available as beta. We don't have official samples available just yet, and this library is a bit rough around the edges so YMMV. We're looking at providing a better experience through an official client that wraps the autogenerated library (similar to Pub/Sub), so stay tuned.

**Comment by tmdiep** [comment]
Hi folks, we are pleased to inform that the `pubsublite` module (from version 0.6 onwards) is now in a usable state. It should attain beta status shortly. We welcome early feedback.

Its packages are:
* [cloud.google.com/go/pubsublite](https://pkg.go.dev/cloud.google.com/go/pubsublite) - contains the admin client for managing topic and subscription resources.
* [cloud.google.com/go/pubsublite/pscompat](https://pkg.go.dev/cloud.google.com/go/pubsublite/pscompat) - contains publisher and subscriber clients with interfaces that are compatible with the [`pubsub`](https://pkg.go.dev/cloud.google.com/go/pubsub) module.

**Comment by anguillanneuf** [comment]
🎊 Yay~! Could you point me to the Go release notes where this is announced?

**Comment by tmdiep** [comment]
@anguillanneuf

These are the release notes for the `pubsublite` module: https://github.com/googleapis/google-cloud-go/blob/master/pubsublite/CHANGES.md. Once the library is officially beta, I'll update these release notes as well as the table of APIs in https://github.com/googleapis/google-cloud-go/blob/master/README.md.

**Comment by anguillanneuf** [comment]
@tmdiep That's excellent. Thank you!

**Comment by tmdiep** [comment]
The [pubsublite](https://pkg.go.dev/cloud.google.com/go/pubsublite) library is now in beta (from version 0.7).

Samples can be found at: https://github.com/GoogleCloudPlatform/golang-samples/tree/master/pubsublite.

**Comment by tmdiep** [comment]
I will close this issue. Feel free to open new issues if you find bugs, usability issues, unclear documentation, etc. Thank you!
