### ISSUE TITLE
spannertest: Full support for `GetDDL`

### ISSUE THREAD

**Issue by alethenorio** [googleapis/google-cloud-go#2461]
**Is your feature request related to a problem? Please describe.**
We have been successfully using `spannertest` for our tests and we'd like to be able to retrieve the full DDL of the database after applying a couple of DDL changes but it seems that the `GetDDL` method is missing support for a few things (above all the `NotNull` field)

**Describe the solution you'd like**
Add support for `NotNull` field in the GetDDL API of the `spannertest` package

**Describe alternatives you've considered**
Attempt to parse the DDL statements and derive the final database DDL ourselves

**Comment by skuruppu** [comment]
@dsymonds hope it's ok if I assign this to you. Please assign it back to us if you don't have the cycles to work on it.

**Comment by skuruppu** [comment]
@alethenorio I also have a high-level question. We've been trying to better understand the use of `spannertest` vs the [Cloud Spanner Emulator](https://cloud.google.com/spanner/docs/emulator) so that we can document the use cases where you may want to use one over the other.

In your experience, what are some of the advantages of using `spannertest`?

**Comment by dsymonds** [comment]
Note that spannertest doesn't support all the DDL features (including `NOT NULL`), so the DDL that its GetDDL method returns is somewhat bound by that.

**Comment by dsymonds** [comment]
Trying to use spannertest to stack up DDLs is a bit outside its purpose. In the long run that's a plausible use case, but it's a long way down the priority list. Consider using the spansql package directly for parsing, and see about deducing the final state yourself. I've had reasonable success doing that for diffing schemas between a single DDL file and production and the scope of possible transformations is actually pretty simple. The hard part of it in spannertest is mutating or validating stored data.

**Comment by alethenorio** [comment]
> Trying to use spannertest to stack up DDLs is a bit outside its purpose. In the long run that's a plausible use case, but it's a long way down the priority list. Consider using the spansql package directly for parsing, and see about deducing the final state yourself. I've had reasonable success doing that for diffing schemas between a single DDL file and production and the scope of possible transformations is actually pretty simple. The hard part of it in spannertest is mutating or validating stored data.

Makes sense. I will look into using spansql for the task. Looks straight forward.

You can close the issue as it is not relevant
