### ISSUE TITLE
spannertest: Support for (HASH) JOIN in select statement

### ISSUE THREAD

**Issue by jrmeinride** [googleapis/google-cloud-go#2462]
**Is your feature request related to a problem? Please describe.**
We have some functionality that uses more than one table in spanner. By using interleave the service is still fast and responsive. When adding unit tests we cannot test certain parts of our code, since there is no support for JOIN, or HASH JOIN in spannertest.

The type of query we would like to be able to run is something akin to this:

```
SELECT * 
FROM table1
LEFT OUTER HASH JOIN table2
	ON table1.id = table2.table1_id
```

**Describe the solution you'd like**
We would like spannertest to support `LEFT OUTER HASH JOIN` in `SELECT` statements.

**Describe alternatives you've considered**
The only viable option would be to set up a table for testing in one of our projects, but that can not be considered to be a unit test.

**Additional context**
-

**Comment by skuruppu** [comment]
@jrmeinride another alternative could be to setup the unit tests against the [Cloud Spanner Emulator](https://cloud.google.com/spanner/docs/emulator).

In any case, I will assign this to @dsymonds to see if he's got the cycles to implement this support.

**Comment by jrmeinride** [comment]
> @jrmeinride another alternative could be to setup the unit tests against the [Cloud Spanner Emulator](https://cloud.google.com/spanner/docs/emulator).
> 
> In any case, I will assign this to @dsymonds to see if he's got the cycles to implement this support.

Thank you! I will look into that.

**Comment by dsymonds** [comment]
Starting to do some preliminary work on this in #2850.
