### ISSUE TITLE
bigtable: support for get instance status and instance labels

### ISSUE THREAD

**Issue by na-ga** [googleapis/google-cloud-go#2472]
**Is your feature request related to a problem? Please describe.**

There is no way to get the instance state and labels.

**Describe the solution you'd like**

We would like InstanceAdminClient to support for get InstanceState and Labels in InstanceInfo.

**Describe alternatives you've considered**

None

**Additional context**

Already added to "[google.golang.org/genproto/googleapis/bigtable/admin/v2/instance.pb.go](https://github.com/googleapis/go-genproto/blob/d2e73d30e86fe780e2827d82964233263d36bc3b/googleapis/bigtable/admin/v2/instance.pb.go#L234-L263)".
I think "[cloud.google.com/go/bigtable/admin.go](https://github.com/googleapis/google-cloud-go/blob/v0.58.0/bigtable/admin.go#L685-L689)" needs to be fixed.

**Comment by tritone** [comment]
Thanks for your report! @kolea2 do we have this on the roadmap to support?

**Comment by na-ga** [comment]
Thanks!

**Comment by tritone** [comment]
Released in bigtable/1.4.0
