### ISSUE TITLE
storage: issue setting Cache-Control header while uploading Image in GCP Storage

### ISSUE THREAD

**Issue by max202021** [googleapis/google-cloud-go#2546]
I am trying to add Image to my GCP Staorage bucket and while adding image I am setting metadata Cache-Control.
Image gets uploaded but correct metadata is not reflecting.

My Code is as follows

```
	GCPfileName := strconv.Itoa(int(nanos)) + "Demo" + ".jpeg"
	wc := gcpClient.Bucket("mybuckettest").Object(GCPfileName).NewWriter(myCTX)
	m := make(map[string]string)
	m["Cache-Control"] = "public, max-age=630298681"
	m["cache-control"] = "public, max-age=630298681"
	m["cacheControl"] = "public, max-age=630298681"
	wc.Metadata = m

	err = jpeg.Encode(wc, finalImage, nil)
	if err != nil {
		fmt.Println(err)
		return
	}
```

When I retrieve the image I can see the default cache control.

![image](https://user-images.githubusercontent.com/57527948/86220447-39ad2a00-bba1-11ea-8356-859fe7a2772e.png)

There are now 4 Cache control in response .

The main cache control is not set , instead it added 3 new metadata.

![image](https://user-images.githubusercontent.com/57527948/86220647-809b1f80-bba1-11ea-9397-1831b2201529.png)

Is this issue with API? Similar issue seems to be in google-cloud-node which was reported and fixed.

[https://github.com/googleapis/google-cloud-node/issues/1087 ](https://github.com/googleapis/google-cloud-node/issues/1087)

**Comment by IlyaFaer** [comment]
@max202021, please, take a look at [this page](https://cloud.google.com/go/getting-started). There is a sample of how to set `Cache-Control` via Go API - it should be done with `Writer.CacheControl` field, not metadata:
```go
w := b.StorageBucket.Object(name).NewWriter(ctx)
...
// Entries are immutable, be aggressive about caching (1 day).
w.CacheControl = "public, max-age=86400"
```

**Comment by max202021** [comment]
Thanks @IlyaFaer . This resolved the issue.
