### ISSUE TITLE
storage: support startOffset query during object listing 

### ISSUE THREAD

**Issue by deka108** [googleapis/google-cloud-go#2556]
**Is your feature request related to a problem? Please describe.**
If we have a large number of files stored in the bucket and we only want to list objects starting from a certain prefix, listing objects starting from a specific starting point (under a lexicographical order) would be desirable. This[ feature is supported in the JSON API via `startOffset`](https://cloud.google.com/storage/docs/json_api/v1/objects/list). However, I could not find a way to set this startOffset value under the go sdk.

**Describe the solution you'd like**
Support for `startOffset` when listing objects should be simple. This can be done by:
1. Add `StartOffset` field to `storage.Query` struct
2. Request changes to internal storage client api to add `func (c *BucketsListCall) StartOffset(startOffset string)` to modify the url query parameter for startOffset
3. Modify `func (it *ObjectIterator) fetch(pageSize int, pageToken string)` to incorporate startOffset parameter if it is being set in the Query, ie. `req.StartOffset(it.query.StartOffset)`

To use this feature, I should be able to set the `StartOffset` field in `storage.Query` to some string value, and expect the internal listObjects call to respect the startOffset and list objects starting from startOffset.

**Comment by AlisskaPie** [comment]
Thank you for taking the time to file an issue and proposals.

I made a PR for step 1 and 3 and also provide `EndOffset`.
But for step 2 there already exists [this method](https://github.com/googleapis/google-api-go-client/blob/5d1990ecea8d638d91e62c59dacadc52d719bad0/storage/v1/storage-gen.go#L10387), I think you mean this.

Please let me know if I've missed out anything.

**Comment by tritone** [comment]
This has been merged and will go out in the next release of the storage library.
