### ISSUE TITLE
all: set up Renovate for dependency updates

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#2565]
Renovate can automatically update dependencies. We should set it up for this repo.

Here is the golang-samples config:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/.github/renovate.json

I tried using Dependabot, which is built in to GitHub, but it wasn't as feature-complete as Renovate.

**Comment by codyoss** [comment]
Sounds like a good idea to me. The only quirk I can think of with this repo is not having it touch genproto. We should let our nightly take care of that one.

**Comment by tbpg** [comment]
You can configure Renovate to ignore updates for certain dependencies.

https://docs.renovatebot.com/configuration-options/#ignoredeps
