### ISSUE TITLE
pubsub: go mod vendor - malformed record data

### ISSUE THREAD

**Issue by nhurwitz** [googleapis/google-cloud-go#2607]
**Client**
Pubsub

**Environment**
n/a

**Go Environment**
Mac OS10.15.5
$ go version
`go version go1.13.5 darwin/amd64`
$ go env
```
O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/noamhurwitz/Library/Caches/go-build"
GOENV="/Users/noamhurwitz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="${equal-go-private}"
GONOSUMDB="${equal-go-private}"
GOOS="darwin"
GOPATH="/Users/noamhurwitz/go"
GOPRIVATE="${my-go-private}"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="${my-mod-file}"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1r/qmwmbk_j1vz78w949qys2y_r0000gn/T/go-build029325698=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
**Code**
Module issue.

Adding `cloud.google.com/go/pubsub` to `go.mod` or running `go get -u cloud.google.com/go/pubsub` both result in the following error:
```
verifying golang.org/x/lint@v0.0.0-20190930215403-16217165b5de/go.mod: golang.org/x/lint@v0.0.0-20190930215403-16217165b5de/go.mod: malformed record data
```

I'm able to run go get golang.org/x/lint and it's imported at version `v0.0.0-20200302205851-738671d3881b`. I've tried replacing the version that's failing with that version to no avail:
`replace golang.org/x/lint@v0.0.0-20190930215403-16217165b5de => golang.org/x/lint v0.0.0-20200302205851-738671d3881b`

**Comment by codyoss** [comment]
I just tried to create a fresh module project, pull in pubsub, and ran `go mod tidy`. It did not seem to have an issues. Cloud you try running `go clean -modcache` and then `go mod download` to see if that fixes the issue?

**Comment by nhurwitz** [comment]
That seems like a much easier approach but updating to `go 1.4` also fixed the problem 😅
