### ISSUE TITLE
firestore: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by huyntsgs** [googleapis/google-cloud-go#2640]
**Go Environment**

Go version 1.13

** Source code **

```go
package main

import (
	"context"
	"log"
	"os"
	"github.com/gin-gonic/gin"
	"cloud.google.com/go/firestore"
	firebase "firebase.google.com/go"
)

type ApiContext struct {
	Client *firestore.Client
}
type UserHandler struct {
	apiContext *ApiContext
}

func NewUserHandler(apiContext *ApiContext) UserHandler {
	return UserHandler{apiContext: apiContext}
}

// UpdateData queries and update firestore every one minute
func (h UserHandler) UpdateData() gin.HandlerFunc {
	return func(c *gin.Context) {
		_, err := h.apiContext.Client.Doc("docpath").Get(context.Background())
		if err != nil {
			log.Println("[ERROR] get firestore data", err)
		}
	}
}
func main() {

	ctx := context.Background()
	conf := &firebase.Config{ProjectID: "projectId"}
	app, err := firebase.NewApp(ctx, conf)
	if err != nil {
		log.Fatalln(err)
	}

	client, err := app.Firestore(ctx)
	if err != nil {
		log.Fatalln(err)
	}

	appContext := &ApiContext{Client: client}
	router := SetupRouter(appContext)
	port := os.Getenv("PORT")
	if port == "" {
		port = "8089"
	}
	router.Run(":" + port)
}

func SetupRouter(appContext *ApiContext) *gin.Engine {

	router := gin.New()
	userHandler := NewUserHandler(appContext)
	v1 := router.Group("/api/v1")
	v1.POST("/runeveryminute", userHandler.UpdateData())

	return router
}
```

**Expected behavior**

I expect the firestore database connection is always alive. But many time in the api UpdateData that runs every 1 minute, it encountered the error "rpc error: code = Unavailable desc = transport is closing"

Is there any setup the firestore to keep the connection always available? Thanks in advance!

**Comment by tritone** [comment]
I believe that the firestore library should retry Gets on the error code UNAVAILABLE automatically. See https://github.com/googleapis/google-cloud-go/blob/master/firestore/apiv1/firestore_client.go#L70 . Are you seeing the library perform a retry in this case?

As far as the root cause of the error itself, it's a little bit hard to determine. This is a network-level issue so the frequency may vary a lot depending on what environment you are running in.

**Comment by huyntsgs** [comment]
Thanks @tritone. I deploy the code on Cloud Run. I think the issues come from Cloud Run.

**Comment by codyoss** [comment]
@huyntsgs I would recommend setting the keepalive for longer than your minute update. Example: 

```
opt := option.WithGRPCDialOption(grpc.WithKeepaliveParams(keepalive.ClientParameters{
        Time: 2 * time.Minute,
    }))
firebase.NewApp(ctx, conf, opt)
```

If you are still having issues after trying this please report back and we can investigate further.
