### ISSUE TITLE
firestore: Support MergeAll for structs

### ISSUE THREAD

**Issue by bramp** [googleapis/google-cloud-go#2643]
**Is your feature request related to a problem? Please describe.**

I'm trying to update specific fields of a document, while using my struct. For example

```go
type State struct {
    Capital    string  `firestore:"capital"`
    Population float64 `firestore:"pop,omitempty"` // in millions (** Notice the omitempty)
}

wr, err := client.Doc("States/Colorado").Set(ctx, State{
    Capital:    "Denver",
}, firestore.MergeAll)
```

**Describe the solution you'd like**

Today this example returns an error "firestore: MergeAll can only be specified with map data". 

Instead, I would like this to set all the non-empty fields, specifically the fields that have their nil value, and have "omitempty" set.

Thus in this example, the `Population` field would remain under changed in the database, the `Capital` would be updated to "Denver".

**Describe alternatives you've considered**

Instead of supporting structs, I could write:

```go
wr, err := client.Doc("States/Colorado").Set(ctx, map[string]interface{}{
    'capital':    "Denver",
}, firestore.MergeAll)
```

However, this is error prone, as I have to know `capital` is the field name, and gets rid of the type safety the struct was providing.

An alternative could be to use reflection (or similar) to get a list of Field names, so I can ensure that Capital maps to `capital` however, this loses some of the compile time safety.

**Comment by tritone** [comment]
Thanks for raising the issue. Something like this has been a frequent feature request for the firestore library. We're hoping to get a design together this quarter. See #2610 for any updates.

**Comment by roboncode** [comment]
Here is a file I have created to convert structs to maps - https://gist.github.com/roboncode/d8592d3a6ca3704a92ff2c35baf8456a

**Comment by crwilcox** [comment]
Agree with @tritone this would be an improvement. Considering this a duplicate of the collecting issue.

**Comment by treeder** [comment]
How is this related to custom data types in #2610 that closes this?
