### ISSUE TITLE
spanner: canceled context is used to record stats

### ISSUE THREAD

**Issue by nodirg** [googleapis/google-cloud-go#2660]
I have been reading Spanner client code and stumbled on this: https://github.com/googleapis/google-cloud-go/blob/626dcfc93bc20470967103499967e34781b3c893/spanner/session.go#L1502-L1517

note here that `ctx` is canceled in L1504 and then that context is used in L1517.

I don't have concrete problem that this caused, but this code does not look correct. Perhaps `ctx` variable in L1502 should be renamed

**Comment by skuruppu** [comment]
@olavloite, if you could also take a look at this, that would be great.

CC @hengfengli

**Comment by olavloite** [comment]
@nodirg Thank you for your report. In this specific case it is as far as I can tell not really a problem, but I do agree with you that it looks a little bit suspicious. The reason that it is not really a problem in this case, is that the context is only used to include the tags that should be included with the statistics that are recorded.
I've moved the `cancel()` call to right after where it is used for the stats to prevent any confusion.
