### ISSUE TITLE
How to get the kubeconfig of create K8s cluster?

### ISSUE THREAD

**Issue by gophobic** [googleapis/google-cloud-go#2664]
Is there a way within the go apis that is equivalent to `gcloud container clusters get-credentials` to get the kubeconfig or is this intended to only get it interactively?

**Comment by codyoss** [comment]
I think the closest thing we support in the client libraries would be [GetCluster](https://pkg.go.dev/cloud.google.com/go@v0.61.0/container/apiv1?tab=doc#ClusterManagerClient.GetCluster)
