### ISSUE TITLE
bigtable: cbt: use hex or base64 encoding instead of %q formatting when printing cell values

### ISSUE THREAD

**Issue by RomanIakovlev** [googleapis/google-cloud-go#2680]
Currently cbt uses `%q` formatting option to print the cell value, e.g. when using `cbt lookup`. See `printRow` function here: https://github.com/googleapis/google-cloud-go/blob/766638c7c6d3e45b00ec41b4bc55b61fe6908449/bigtable/cmd/cbt/cbt.go#L1022 This is mildly inconvenient, because the result produced by `%q` is Golang-specific, and it's difficult to use it in other environments (like shell or Python). 

It would be more convenient to use something neutral like `%x`, because hex encoding is much more widespread. For example, when the value of the cell is a protobuf message, and one wants to represent it as something human-readable, one needs to get hold of the actual bytes. Getting to bytes from hex encoding is as easy as calling `xxd`, but getting to bytes from `%q` encoding requires Golang, which is not as widely spread. Base64 would work as well.

P.S. it would be even more awesome to get the support for printing the human-readable protobuf messages (akin to `protoc --decode` or at least `protoc --decode-raw`), but that's probably too far fetched for a feature request?

P.P.S. if it's just about changing `%q` to `%x` or switching to base64, I can totally send a PR if it helps, just let me know.

**Comment by dsymonds** [comment]
`cbt` is a convenience tool for humans to use. It really isn't intended for automation. If you have specific needs then you can write a program to use the cloud libraries (using whatever language you prefer) and get exactly the output you want, likely with better performance.

**Comment by RomanIakovlev** [comment]
I understand and agree with such a purpose of `cbt`. I just think it could be a bit more convenient for humans that have not bought into the Go ecosystem, by using a more standard form of the output. With the current behavior, if one wants to lookup one cell value of protobuf payload and understand what's inside that payload, it's first required to convert the byte output of `cbt` to something standard tools can understand, and that's just inconvenient.

I personally think changing `%q` to `%x` should be rather non-controversial change, not running counter to the purpose of `cbt` being a convenience tool for humans.

**Comment by dsymonds** [comment]
I never saw it as a Go ecosystem thing. I modeled `cbt` after a very similar Google-internal tool called `bt`, which attempted to print cell values as strings, and %q is the right modifier for that, giving readable output for things that are strings (or close to them), while still making it plausible if it isn't strings. %x, on the other hand, is definitely poor for strings.

**Comment by RomanIakovlev** [comment]
It's a fair comment that `%q` is better for strings, which are probably quite popular type of payload. On the other hand, protobuf is probably also quite popular, it's even recommended in Cloud Bigtable docs. Maybe it's then possible to print with `%q` by default, but add an argument to `cbt` to use `%x` or base64 when necessary?

**Comment by dsymonds** [comment]
Yeah, a flag might work fine. The internal `bt` tool has some limited flag control for controlling how values are printed.

**Comment by RomanIakovlev** [comment]
I took the liberty to actually implement this, can be found here: https://github.com/googleapis/google-cloud-go/pull/2759. It's mainly for illustration purposes, and I have left the PR in the draft state for now, but if there's interest from the code owners, I can finalize it. In that case, please let me know of any changes I need to make to make this mergeable. Thanks!

**Comment by jimfulton** [comment]
see #4265 

(Sorry, I wasn't aware of this when I created that.)

**Comment by telpirion** [comment]
This feature has been implemented in `cbt` release # 0.12.0. (The `cbt` tool has also moved to another [repo](https://github.com/googleapis/cloud-bigtable-cbt-cli).)
