### ISSUE TITLE
bigtable: AppendValue function is failing without a error. 

### ISSUE THREAD

**Issue by manojprithvee** [googleapis/google-cloud-go#2686]
``` go
func writeUpdatedProfile(ctx context.Context, event *pb.Event) error {
	profile := bigtable.NewReadModifyWrite()
	profile.AppendValue("latest", "col_name", []byte(strconv.FormatInt(time.Now().UTC().Unix(), 10)+":abcd|"))
	_, err := table.ApplyReadModifyWrite(ctx, event.column.key, profile)
	if err != nil {
		return err
	}
	return nil
}
```
This function does not update the cell and exit without an error. can anyone HELP!

**Comment by manojprithvee** [comment]
let for eg. say i append "4,abcd|" 3 times i am only able to see "4,abcd|" instead of "4,abcd|4,abcd|4,abcd".

**Comment by tritone** [comment]
@kolea2 Could you take a look at this one? I don't see any obvious problem with the code but I'm not an expert.

**Comment by codyoss** [comment]
I tried to reproduce this and was unable to. My result appended successfully to the row/column with similar code. My best guess to what is going on is either `event.column.key` is not the same so the value is not being appended or you are looking at an older [ReadItem](https://pkg.go.dev/cloud.google.com/go/bigtable#ReadItem) for the given column. If you are still having issues please feel free to repopen with some extra details.
