### ISSUE TITLE
bigtable: ttl for bigtable rows like in java Client

### ISSUE THREAD

**Issue by manojprithvee** [googleapis/google-cloud-go#2719]
we are not able to set TTL for a row like in java client.

**Comment by tritone** [comment]
Hi @manojprithvee , thanks for filing the issue.

Can you clarify what methods in the Java client you are referring to? My understanding is that row TTL is not supported as a first-class concept in bigtable (I'm referencing https://cloud.google.com/bigtable/docs/gc-cell-level).

However, if you want to achieve that by modifying the garbage collection policy, that is supported in both Java and Go. Will [SetGCPolicy](https://github.com/googleapis/google-cloud-go/blob/bigtable/v1.5.0/bigtable/admin.go#L266) do what you need?
