### ISSUE TITLE
pubsub: occasional unauthenticated errors

### ISSUE THREAD

**Issue by smit-aterlo** [googleapis/google-cloud-go#2727]
**Client**

PubSub v1.6.1

**Environment**

GKE

**Go Environment**

$ go version
go version go1.14.4 linux/amd64

**Code**

Pubsub client and also provided this while creating the pod `export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"
`
```
psClient, err := pubsub.NewClient(context.Background(), "projectID")
```

**Expected behavior**

Pull messages constantly without interruption 

**Actual behavior**

At least once a day I am getting the following error for around 10-15 minutes which stops the production instance from reading messages. Error is on this line `subscription.Receive()` 
```
Pubsub receive error on subscription subscriptionID: rpc error: code = Unauthenticated desc = Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

**Comment by hongalex** [comment]
Hi, are you wrapping your `subscription.Receive` call so that it automatically retries on errors?

You mentioned this happens at least once a day. Do your errors go away by themselves automatically or do you have to restart the application?

**Comment by smit-aterlo** [comment]
It goes away after 10-15 mins automatically. Yes, program reties but for those 10 minutes it is not able to pull anything across all the subscriptions. We have around 100+ subscriptions

**Comment by hongalex** [comment]
Strange, I haven't heard of any reports related to this yet. Just to be sure, the error is always "Unauthenticated"?

Could you also post your `subscription.ReceiveSettings` or a working reproduction so that I can try to to replicate it?

**Comment by smit-aterlo** [comment]
Yes, it is Unauthenticated every time. I have only one setting `subscription.ReceiveSettings.MaxOutstandingMessages = 10`

**Comment by hongalex** [comment]
Hm, unfortunately I haven't been able to reproduce this just yet. Would you say this started at v1.6.1? If so, could you try rolling back to an older version of the client library (perhaps 1.6.0 or 1.5.0)

Thanks

**Comment by smit-aterlo** [comment]
No this was there in older versions as well

**Comment by hongalex** [comment]
This seems similar to issue #1090. Are you perhaps calling `Receive` in multiple places from a single client instantiation?

**Comment by smit-aterlo** [comment]
Yes, we are doing that. I will change that and see how it goes. Thank you very much for your help.

**Comment by smit-aterlo** [comment]
This issue got resolved once we started using synchronous pull
