### ISSUE TITLE
containers: ServerConfig missing "channels"

### ISSUE THREAD

**Issue by rubensayshi** [googleapis/google-cloud-go#2737]
**Client**

Containers

**Expected behavior**

the `ServerConfig` struct returned from `GetServerConfig` should contain the "channels" as per https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/ServerConfig

**Actual behavior**

it doesn't.

**Comment by codyoss** [comment]
These files are auto-generated from protos. If you think a field should be added I suggest opening up something on the [GCP issue tracker](https://issuetracker.google.com).

**Comment by rubensayshi** [comment]
thanks @codyoss, will do!
