### ISSUE TITLE
internal: can we have a correct library version instead of a date? 

### ISSUE THREAD

**Issue by hengfengli** [googleapis/google-cloud-go#2749]
Currently, the version of the entire client lib is pinned to a date: https://github.com/googleapis/google-cloud-go/blob/e455ed5db86b21a22e9a5b5018a90b74dfc4a392/internal/version/version.go#L27-L29. This can be confusing when comparing to other language client libs. 

What is the story/background behind this? Are we able to have a proper library version, e.g.,  `0.64.0`, instead of a date?

**Comment by codyoss** [comment]
I don't have the context to why this is a date today, but I agree I think we can do better here. I will have to do a little research into what other languages are populating into this value. I assume a semver like `v0.64.0`.

**Comment by crwilcox** [comment]
https://github.com/googleapis/google-cloud-go/issues/3330 related

**Comment by codyoss** [comment]
I think this issue is for the most part complete. I would like to also get this hooked into the GAPIC layer more, but that will happen outside of this repo. Closing this issue for now as the original request of having better data in the manual is now true.
