### ISSUE TITLE
bigquery: unable to download large results

### ISSUE THREAD

**Issue by sharadbhadouria** [googleapis/google-cloud-go#2753]
I have a query that returns over 400million rows and its always stuck during downloading results using storage api(https://cloud.google.com/bigquery/docs/reference/storage/).
I am using single stream . Is there a limitation on number of rows that can be downloaded in a single stream? There are no errors but the code is stuck in download phase for ever. Same code works for ~150million rows. Any idea whats going on?

**Comment by tbpg** [comment]
What version of Go and cloud.google.com/go/bigquery are you using? What version of Go? Can you share a snippet of code that demonstrates the problem?

**Comment by sharadbhadouria** [comment]
go version go1.13.5; bq version bigquery/v1.3.0
The code is similar to https://github.com/GoogleCloudPlatform/golang-samples/blob/7994b440a075139ad2bb92c5f334deaf6a498dea/bigquery/bigquery_storage_quickstart/main.go
I unfortunately don't have a repro. But the data it's trying to download has over 400 million rows and each row on an average has 150 characters.

**Comment by tbpg** [comment]
Just to confirm, are you able to reproduce the issue with Go 1.15 and bigquery/v.1.10.0?

**Comment by sharadbhadouria** [comment]
I haven't tried it yet. Are there any known issues in prior versions? Whats the recommended go and bigquery versions to use storage api?

**Comment by shollyman** [comment]
To clarify, there's no defined limit per stream, no. 

Any additional information you can provide would be helpful here, like a code snippet or repro.

If I'm doing the math correctly, we're talking about a table that's roughly ~50GB in size?  It's not clear what "download phase" here means; is there a chance you're blocking on the stream read?  Is there a typical interval/offset/delay before you start observing lack of progress?

**Comment by sharadbhadouria** [comment]
I have identified the problem by generating flamegraph and its unrelated to storage api. Thanks all for your help!

**Comment by tbpg** [comment]
Glad you got it figured out!

We're always working on improvements. So, we recommend the latest version. But, it's very understandable to not be on the latest.
