### ISSUE TITLE
firestore: add support for arrayUnion and arrayRemove

### ISSUE THREAD

**Issue by marwan-at-work** [googleapis/google-cloud-go#2757]
I'd love for the Go client to add support for these two methods here as they are important for when dealing with firestore arrays: https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array

Thanks

**Comment by tritone** [comment]
@benwhitehead is this supported in other firestore libraries, or on our roadmap?

**Comment by BenWhitehead** [comment]
Yeah this is expected to be supported, we should add it to the queue. A sample of it being used with the node.js client can be seen here: https://github.com/firebase/snippets-node/blob/68135f9e93ada2c2b18230d6fce27f164c7e778f/firestore/main/index.js#L219-L230

**Comment by telpirion** [comment]
Closing this issue now as array union and array remove has not been released for server SDKs.
