### ISSUE TITLE
firestore: does DocumentRef.Create use a read if the document already exists

### ISSUE THREAD

**Issue by LukeBalizet** [googleapis/google-cloud-go#2765]
For the `firestore `api, `DocumentRef.Create` "returns an error if a document with the same ID already exists." In this scenerio, since no write was performed, a write should not be counted towards my billing, however, does a read get performed to see if the document exists? Will this count towards my read total?

**Comment by tritone** [comment]
I believe the answer is no; no separate read operation should be performed for a failed write. @benwhitehead can you confirm?

**Comment by BenWhitehead** [comment]
A failed RPC to Firestore in general isn't billed, however if you are using a "Free tier" instances of Firestore the RPC attempt will be counted against the daily free writes.

**Comment by tritone** [comment]
Thanks Ben! Will close this one out.
