### ISSUE TITLE
pubsub: Message receive rate is slower when NumGoroutines is >1 after updating to 1.6.1

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-go#2775]
**Client**
PubSub

cloud.google.com/go/pubsub v1.6.1
cloud.google.com/go v0.64.0
google.golang.org/grpc v1.31.0

**Environment**

Docker distroless base on GKE

**Go Environment**

Go 1.15

**Code**

```go
return w.pubsubClient.
	Subscription(w.subscriptionName).
	Receive(ctx, func(iCtx context.Context, msg *pubsub.Message) {
		// ticking metrics here
	        // ...
		if err != nil {
			msg.Nack()
		} else {
			msg.Ack()
		}
	})
```

**Expected behavior**

Message receive rates should increase as undelivered messages increase.

**Actual behavior**

Message receive rate remains low as undelivered messages increase.

**Additional context**

Good day team, we have encountered an issue when upgrading to the latest PubSub client (v1.6.1). We've found a workaround which I've outlined below, but I wanted to submit an issue incase others run into something similar. Or maybe we have the wrong expectations after the update.

One of our service has subscriptions to a large number of different topics. The message receivers are started in go routines to wait for new messages to come in. After updating google.golang.org/grpc to v1.31.0 we started to see issues where our Pub/Sub messages weren't being processed at the same rate as before. After noticing Pub/Sub had updated from v1.1.0 to v1.3.1, we tried updating to v1.6.1 because [this issue which sounded similar](https://github.com/googleapis/google-cloud-go/issues/2593), but had no luck.

The figure below shows the time period where we switched from our working v1.1.0 version to v.1.6.1. The graph on the top is a metric ticked every time the `Receive` function runs. The graph on the bottom shows the number of undelivered pubsubs for one of our busier topics. Once the version switches over, we see the undelivered pubsubs begin to climb, and the number of `Receive` calls stay fairly low compared to what we'd expect with that many undelivered messages.
![image](https://user-images.githubusercontent.com/15327741/91195401-32dcf800-e6b6-11ea-9b13-aee42a01b57d.png)
_The line shows roughly the point when the versions were switched from Pub/Sub 1.1.0 to 1.6.1._

The next thing we tried was setting `Synchronous` to true, which actually fixed the problem. The graph below shows the point at which the image is switched from the non synchronous version to the synchronous one and the undelivered messages come right back down, and we see an increase in the number of messages being processed.
![image](https://user-images.githubusercontent.com/15327741/91196445-63716180-e6b7-11ea-9e6f-c95842c3dd89.png)
_The line shows roughly the point when the subscriptions were switched to synchronous._

I found this interesting wanted to do a few more tests to understand the problem. I see under the hood, `Synchronous` false is using a streaming rpc and `Synchronous` true does not. To rule out anything around the type of connection, I switched `Synchronous` back to false, and set `NumGoroutines` to 1. This continued to work the same as having `Synchronous` false. Everything seemed to be processing fine, so it doesn't seem to be unary vs stream related.

Next, I tried setting `NumGoroutines` to 2 to see if that started to cause problems. As soon as that version was up, the number of undelivered messages climbed again and the number of receives remains relatively low.
![image](https://user-images.githubusercontent.com/15327741/91221082-603b9d00-e6da-11ea-88c3-ea23d9c8f012.png)
_The line shows roughly the point the synchronous was set to false and NumGoroutines was set to 2._

For completeness, I decided to see what would happen with NumGoroutines set to something like 100 since the default is 10. There was no real difference. The undelivered messages climb again and the number of received messages remains fairly low compared to the version with NumGoroutines set to 1.
![image](https://user-images.githubusercontent.com/15327741/91228587-b3ffb380-e6e5-11ea-9dd6-b6d5219d4405.png)

This seems to suggest there is some sort of issue around the rate of message processing related to the `NumGoroutines` option.

Please let me know if there is any more information I can provide you.

**Potentially related issues**

[pubsub: process hanging forever when large number of subscription combined with NumGoroutines](https://github.com/googleapis/google-cloud-go/issues/2593)
[pubsub: pull message slow after update](https://github.com/googleapis/google-cloud-go/issues/2540)
[pubsub: subscriber stuck without error in case of lots of messages in the subscription](https://github.com/googleapis/google-cloud-go/issues/1733)

**Comment by hongalex** [comment]
Hey, thanks for filing an issue (as well as the super detailed graphs).

A couple things that might help with investigating this issue:

1. Do you have any other `ReceiveSettings` other than `NumGoroutines` and `Synchronous` (either for the previous or current versions)?
2. What is the Acknowledgement Deadline for your subscription? This can be found in the Pub/Sub console. The default is 10 seconds.
![image](https://user-images.githubusercontent.com/9397363/91233801-cfb78980-e6e6-11ea-9acc-a34889c6928f.png)

**Comment by rwiebe-va** [comment]
Thanks for taking a look Alex, `NumGoroutines` and `Synchronous` are the only `ReceiveSettings` set, everything else was left as the default. The previous version left everything set to the default. The ack deadline for the subscriptions are 10 seconds.

<img src="https://user-images.githubusercontent.com/15327741/91314469-d6401280-e773-11ea-983c-60cc3e446fb2.png" width="30%">

It looks like the `DefaultReceiveSettings` changed `NumGoroutines` from 1 to 10 here https://github.com/googleapis/google-cloud-go/commit/09ba3f8614bab8557260ba47b7bd3a7ec711991a#diff-b4556a07a2b7818c407e847791b06c3bR436 but that change was after 1.3.1 which is where we starting seeing problems.

That made me double check the issue we were seeing when we initially updated. When we were on 1.3.1, we actually saw no metrics ticked from the `Receive` function, indicating we weren't receiving any PubSubs. Which sounds like it was probably [this issue](https://github.com/googleapis/google-cloud-go/issues/2593).

<img src="https://user-images.githubusercontent.com/15327741/91318830-e4dcf880-e778-11ea-9eb7-bb330affff0d.png" width="40%">

After updating to 1.6.1, which fixed that issue, the `DefaultReceiveSettings` changed `NumGoroutines` from 1 to 10. At this point, messages are being processed, but it seems to be slower than desired, and slower than when `NumGoroutines` is 1 or `Synchronous` is true.

To see if this is new to >1.1.0 versions, I switched back to PubSub 1.1.0 which, by default has `NumGoroutines` set to 1. I changed the setting for my subscription to 10, to see if the undelivered messages would spike there too, and it does.
<img src="https://user-images.githubusercontent.com/15327741/91321348-c1677d00-e77b-11ea-8817-97757c309891.png" width="40%">

So it looks like we would've encountered this had we not used the default of 1 `NumGoroutines` in earlier versions.
