### ISSUE TITLE
Firestore: time.Time type not the same after create

### ISSUE THREAD

**Issue by steven-eckhoff** [googleapis/google-cloud-go#2780]
I have a struct with a few time.Time types in them and during my testing of storing them to Firestore and retrieving them they always fail to compare with the Time types differing. I am using the emulator for this test. The following is what I am seeing.

```
expected: LastLogin:time.Time{wall:0xbfc9c28c33aee67b, ext:999660813, loc:(*time.Location)(0xeb2aa0)}, FirstSeen:time.Time{wall:0xbfc9c28c33aee6ae, ext:999660859, loc:(*time.Location)(0xeb2aa0)}

actual  : LastLogin:time.Time{wall:0x33aee560, ext:63734057392, loc:(*time.Location)(nil)}, FirstSeen:time.Time{wall:0x33aee560, ext:63734057392, loc:(*time.Location)(nil)}
```

My question is do I need to do something special to handle storing the time.Time type?

**Comment by tritone** [comment]
I think `time.Time` should be supported based on my reading of https://godoc.org/cloud.google.com/go/firestore#DocumentRef.Create . Could you provide a code repro for what you're seeing? Also wondering if this might be an issue with the emulator-- does your code work as expected with the live service?

cc @benwhitehead

**Comment by BenWhitehead** [comment]
Firestore always uses the [`google.protobuf.Timestamp`](https://github.com/protocolbuffers/protobuf/blob/70b02861f8e8ba711efd187188dfb930db7bcaba/src/google/protobuf/timestamp.proto) (which only supports UTC time zone) for it's representation of time/date values[1]. This applies to both the emulator and the production system.

Looking at your output it appears there is some time zone information associated with your expected value, if you read your expected value with UTC as the zone do you get the same value Firestore is returning? 

If the values are not the same, then I would guess that there is a possible bug in the translation layer for handling mapping between `google.protobuf.Timestamp` and `time.Time`, likely related to timezones. A quick glance at the tests for firestore it looks like UTC is being used[2].


[1] https://github.com/googleapis/googleapis/blob/1a85976e6bcecdaee1242f6e7fd8b3db81904f56/google/firestore/v1/document.proto#L98-L102
[2] https://github.com/googleapis/google-cloud-go/blob/master/firestore/from_value_test.go#L32-L36

**Comment by steven-eckhoff** [comment]
Setting the time zone to UTC fixes resolves most of the issue. The actual time now seems to lose a small amount of precision which causes my test to fail, but I don't think I care. Here is what I am seeing.

```
expected: LastLogin:time.Time{wall:0x1eef4c3c, ext:63734067355, loc:(*time.Location)(nil)}, FirstSeen:time.Time{wall:0x1eef4c71, ext:63734067355, loc:(*time.Location)(nil)}

actual  : LastLogin:time.Time{wall:0x1eef4bd8, ext:63734067355, loc:(*time.Location)(nil)}, FirstSeen:time.Time{wall:0x1eef4bd8, ext:63734067355, loc:(*time.Location)(nil)}
```

**Comment by BenWhitehead** [comment]
Apologies for the naive question as I'm not familiar with how `time.Time` works in go, what precision are you trying to save, microseconds? Firestore will only store values to microseconds rounding down any precision beyond that[1] even though `google.protobuf.Timestamp` allows for nanoseconds.

[1] https://github.com/googleapis/googleapis/blob/1a85976e6bcecdaee1242f6e7fd8b3db81904f56/google/firestore/v1/document.proto#L100-L101

**Comment by steven-eckhoff** [comment]
I can confirm this rounding is happening. This is not an issue for me.

The solution is to use UTC and expect some rounding.
