### ISSUE TITLE
spannertest: Support for GetDatabase()

### ISSUE THREAD

**Issue by bombsimon** [googleapis/google-cloud-go#2789]
**Is your feature request related to a problem? Please describe.**

Without this feature it causes panic (nil pointer) when used and makes it hard to test code. I guess this is both a feature and a bug. A bug because it causes a panic but a features since it seems to be known (mentioned [here](https://github.com/googleapis/google-cloud-go/blob/master/spanner/spannertest/inmem.go#L99)).

**Describe the solution you'd like**

I would like support for `GetDatabase()` with the admin client and `spannertest`.

**Describe alternatives you've considered**

I have no workaround for now and have excluded testing in my code using the `GetDatabase()` method.

**Additional context**

MVP/MRE:

```go
package main

import (
	"context"
	"log"

	"cloud.google.com/go/spanner/spannertest"
	"google.golang.org/api/option"
	"google.golang.org/grpc"

	database "cloud.google.com/go/spanner/admin/database/apiv1"
	databasepb "google.golang.org/genproto/googleapis/spanner/admin/database/v1"
)

const (
	dbName = "projects/issue/instances/issue/databases/issue"
)

func main() {
	ctx := context.Background()

	spannerServer, err := spannertest.NewServer("localhost:0")
	if err != nil {
		log.Fatal(err)
	}

	options := []option.ClientOption{
		option.WithEndpoint(spannerServer.Addr),
		option.WithGRPCDialOption(grpc.WithInsecure()),
		option.WithoutAuthentication(),
	}

	adminClient, err := database.NewDatabaseAdminClient(ctx, options...)
	if err != nil {
		log.Fatal(err)
	}

	_, err = adminClient.GetDatabase(ctx, &databasepb.GetDatabaseRequest{
		Name: dbName,
	})
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by dsymonds** [comment]
Looks like it wouldn't be hard to implement.

**Comment by bombsimon** [comment]
Thanks for the super quick help and response!
