### ISSUE TITLE
spanner: make keysets usable

### ISSUE THREAD

**Issue by therealmitchconnors** [googleapis/google-cloud-go#2798]
**Is your feature request related to a problem? Please describe.**
I would like to create a keyset from a slice of rows for deletion.  I have tried two different code paths:

```
func buildKeySet(input []struct{}) (out KeySet) {
  for _, i := range input {
    out = spanner.KeySets(out, spanner.Key{i.value1, i.value2})
  }
  return 
}
```
this results in the first value of the keyset being nil, causing a panic.
```
func buildKeySet(input []struct{}) (out KeySet) {
  keys []spanner.Key
  for _, i := range input {
    keys = append(keys, spanner.Key{i.value1, i.value2})
  }
  return spanner.KeySets(keys...)
}
```
this doesn't compile, as `keys` is a slice of `spanner.Key`, not a `spanner.KeySet`.  

**Describe the solution you'd like**
modify the `KeySets` function to discard nil values, making it similar to the build-in `append(slice...)` function.

**Comment by dsymonds** [comment]
There could definitely be some sort of usability improvements for building a `KeySet` from a list of `Key` values. Not sure the suggested solution feels right, but a `func KeySetFromKeys(...Key) KeySet` addition would fit in.

**Comment by skuruppu** [comment]
@olavloite if you could please take a look, that would be awesome.
