### ISSUE TITLE
spannertest: support for dropping columns

### ISSUE THREAD

**Issue by odsod** [googleapis/google-cloud-go#2820]
**Is your feature request related to a problem? Please describe.**
We've recently started using [golang-migrate](https://github.com/golang-migrate/migrate) for automated migration of Spanner schemas via CI. Works like a charm, except `spannertest` can't handle dropped columns yet.

Since we describe our schemas as migrations that are incrementally applied, we are unable to apply our migrations to `spannertest` when we have dropped a column.

**Describe the solution you'd like**
Support dropping columns in `spannertest`.

**Describe alternatives you've considered**
Migrate to the Spanner emulator, but we really like `spannertest` in a unit test context since there is no startup/stopping time.

Cheers

**Comment by olavloite** [comment]
cc @dsymonds

**Comment by odsod** [comment]
@dsymonds Nice work - many thanks! :raised_hands:
