### ISSUE TITLE
spansql: support join

### ISSUE THREAD

**Issue by uschen** [googleapis/google-cloud-go#2850]
**Is your feature request related to a problem? Please describe.**
trying to use spansql to build query in project instead of handwriting them. however, it does not support JOIN

**Describe the solution you'd like**
support JOIN and ideally complete set of sql spanner supports

**Describe alternatives you've considered**
seems there are quite some go sql builder/parser around, it shouldn't be difficult to implement(?)
* https://github.com/google/zetasql
* https://github.com/Masterminds/squirrel
* https://github.com/cockroachdb/cockroach/tree/master/pkg/sql

**Additional context**
N/A

**Comment by dsymonds** [comment]
I believe the parsing for joins is (mostly) complete. Implementing evaluation of them in spannertest is tracked in #2462.
