### ISSUE TITLE
BigQuery: Your client has issued a malformed or illegal request, That's all we know

### ISSUE THREAD

**Issue by deankarn** [googleapis/google-cloud-go#2855]
**Client**

BigQuery

**Environment**

gcr.io/distroless/static-debian10 docker

**Go Environment**

$ go version
go version go1.15.1 

$ go env

**Code**

e.g.
```go
package main

func main() {
	client, _ := bigquery.NewClient(
		context.Background(),
		c.ProjectID,
		c.Options...,
	)
        client.Dataset(c.Dataset).Table(c.Table).Inserter().Put(...)
}
```

**Expected behavior**
To succeed or return a useful error

**Actual behavior**

A cryptic error with absolutely no details is returned:
```
bigquery: max attempts (5) reached - googleapi: got HTTP response code 400 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

**Additional context**

This code runs as a worker service which builds up rows to load into BigQuery and call Put on the client. We sometimes receive the above error.

As of yet we have not been able to reproduce the error to determine if any data is causing this, but also expected the error response to indicate what the issue might.

**Comment by shollyman** [comment]
This one's likely to be based on your specific project's behavior and traffic, so the likely outcome here is you'll need to work through another avenue such as a support or the public issue tracker.  They'll have access to see more details about your specific projects.  That said, we can try to isolate some more details.

What order of QPS are we talking about here?  What's the batch factor involved (how many rows per Put call)?

You mention you build up rows, which I'm interpreting to mean you are queuing data in some fashion before sending.  Do you happen to flush it based on a specific condition shared by multiple workers, like a specific deadline time?  I've observed things like this where a large number of senders happen to all transmit in lockstep, with insufficient jitter among them.

**Comment by deankarn** [comment]
We have about 30 services reading from a Kafka queue(one for each partition) which:
- builds up a batch of 10 rows
- Calls Put in the library

The Put's/s are somewhere around 30 rows, 3 Put's/s. FWIW these rows are fairly large and why the limit is 10 to not go over the 1MB streaming insert limit. The total across all services is around 100 rows, 90 Put's/s.

Each service runs the code synchronously and so the client is not shared amongst multiple goroutines.

**Comment by shollyman** [comment]
Thanks for helping explain the data shape a bit more.  That level of traffic does not seem problematic and excludes some of the high volume scenarios I was originally considering.

How frequently are you encountering these errors?  Have you captured a corresponding request that triggered such a response?

**Comment by deankarn** [comment]
@shollyman I have not had the chance to capture the payload yet due to other competing priorities, however, it is happening on the order of hundreds of times per day.

**Comment by deankarn** [comment]
@shollyman I was finally able to capture a payload which causes the issue and was able to reproduce.

It was a payload containing 10 messages. After digging into the messages themselves there was nothing special about them.

But when I adjusted the number of messages is where the issue lies. If I send 9 instead of 10 messages I get a `Request payload size exceeds the limit` error `*googleapi.Error`. But when sending 10 get this cryptic error.

So the payload if obviously too large but the incorrect error is being returned. I dug into the code which led me into https://github.com/googleapis/google-api-go-client/tree/master/bigquery/v2 but I was unable to find any offending code.

I suspect somewhere server-side there is an issue. Perhaps limiting the number of bytes read off the posted body is causing it to be cut short and cause a malformed error rather than returning the correct payload too large error? I've seen this sort of thing, assuming the backend servers are written in Go, when using the `http.MaxBytesReader` which does not allow capturing of the error in a nice way.

Unfortunately I cannot share the payload as it contains sensitive data. But I hope this gives enough guidance to look into it further on your end.

**Comment by shollyman** [comment]
That is very helpful, will work on reproducing this.

**Comment by emicklei** [comment]
my program received the same error when inserting 878 rows. This is reproducible. My workaround is to start batching with 100 rows when this (or any) error occurs and giving up on the first failed batch (most likely something is wrong).

**Comment by shollyman** [comment]
Spent some time on this.  You get different backend responses depending on how oversized the payload is.

For example, exceeded the default limit allowed for a single row will yield an appropriate JSON response indicating the row number in the payload (this example just grows the size of string field in a single row insertion):

```
{"kind":"bigquery#tableDataInsertAllResponse","insertErrors":[{"index":0,"errors":[{"reason":"invalid","location":"","debugInfo":"","message":"Maximum allowed row size exceeded. Allowed: 5242880 Row size: 5242894"}]}]}
```

However, you eventually reach a size (10Mb), where the response is rejected outright without the row-specific processing:
```
{
  "error": {
    "code": 400,
    "message": "Request payload size exceeds the limit: 10485760 bytes.",
    "errors": [
      {
        "message": "Request payload size exceeds the limit: 10485760 bytes.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```
As the size continues to grow even larger, you eventually get an even more generalized response:
```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

Next steps:  consult with backend to see how static these limits are, and improve how we deal with these kinds of errors.
