### ISSUE TITLE
storage: Sudden SignatureDoesNotMatch error for Signed URLs

### ISSUE THREAD

**Issue by ashrafgt** [googleapis/google-cloud-go#2859]
**Client**

Storage 

**Environment**

Google Cloud storage

**Go Environment**

```bash
$ go version

go version go1.13.3 linux/amd64
```

**Code**

e.g.
```go
//using cloud.google.com/go/storage v1.8.0
//"bucketName", "objectName", and "contentType" are string variables
//"googleSAKey" contains the JSON credentials of a project owner
cfg, err := google.JWTConfigFromJSON([]byte(googleSAKey))
if err != nil {
	return "", err
}
url, err := storage.SignedURL(bucketName, objectName, &storage.SignedURLOptions{
	Method:         "GET",
	GoogleAccessID: cfg.Email,
	PrivateKey:     cfg.PrivateKey,
	Expires:        time.Now().Add(time.Second * 1000),
	ContentType:    contentType,
})
```

**Expected behavior**

Opening the resulting URL in the browser or calling a GET on it with `curl` downloads the specified object from the specified bucket.

**Actual behavior**

The download attempt fails with error code 403:

Here's the format of the URL:

```bash
https://storage.googleapis.com/{bucket-name}/{object-name}?Expires=1600187505&GoogleAccessId={service-account-email}&Signature=PGEJSTe9UEU95WEgq%2FDYPWT81tlbUEWWjPgHO8a%2B6fqly2uNmLMlkH9SI5RTLHHyQFcqaa1oEIDoRcyfV7k9xnsZTvxH2lmwo%2BMehapcYEZuoay7Sq09TDdDr1H3YiecxYDzZ0ftIIrM8jQvCfwom68vuh1OcX5tuSpH7%2BvgJ17qOZwr7mnZh8VLwowadl4xEs3adJaKbPkmUalp8aj3HRz67MoP%2BymHI%2FmcWluPNQjeeH19Hv8kpYgsoSYhp8suG%2Bv%2BDq82A7sQQmrJ83Bwgy7cv4%2BxzIYJmL7nDFtOT4lRuRNTHhTBBjxyB%2FUZYPvmxPGrnapeDMw6PEUnnA0O7A%3D%3D
```

Here's the format of the error response:

```xml
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>
    The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
  </Message>
  <StringToSign>
    GET 1600185200 /{bucket-name}/{object-name}
  </StringToSign>
</Error>
```

**Additional context**

The code and the credentials have been working and untouched for the past months, but the issue was noticed just recently.

**Comment by ashrafgt** [comment]
I don't think this is a decisive fix but I created a different SA and used it, and now it's working again. Could this be a reliable workaround or could I be missing something else?

**Comment by tritone** [comment]
Thanks for your report. Your code and the generated URL look fine to me. Based on what you described, I strongly suspect that this is a permissions issue with the service account you were using rather than with the client library code to generate the Signed URL. Is it possible that someone changed a configuration there?

I'm going to close this issue for now since you have a workaround, but feel free to re-open if you run into more problems.

**Comment by ankit-jangir-01** [comment]
I too faced this issue today.
