### ISSUE TITLE
bigtable: return error if cluster.numNodes is invalid

### ISSUE THREAD

**Issue by caieo** [googleapis/google-cloud-go#2874]
**Is your feature request related to a problem? Please describe.**
Bigtable does not reject updates with cluster.numNodes < 1. This was caught by one of our users (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/176). It would be helpful for the API to notice that one of the fields is invalid rather than silently dropping an error. 

**Describe the solution you'd like**
Code here: https://github.com/googleapis/google-cloud-go/blob/master/bigtable/admin.go#L1370-L1373 
Instead of `continue`ing, would it be possible to return an error? 

**Describe alternatives you've considered**
ConfigConnector has added a patch on our side to catch this, but if it's possible to get this changed in the API, we'd appreciate it!

**Comment by tritone** [comment]
Thanks for reporting!

@kolea2 any thoughts on whether we should make this change? Is there a situation where cluster.NumNodes < 1 would be valid?

**Comment by jimfulton** [comment]
@caieo it looks like your link to relevant lines has rotted.  Could you freshen it?  

FWIW whenever I link to lines, I always link from the latest commit, rather than a branch so the links aren't broken by later commits.

**Comment by caieo** [comment]
@jimfulton here's the fresh link https://github.com/googleapis/google-cloud-go/blame/master/bigtable/admin.go#L1524 -- it looks like there is now a check to ensure cluster.numNodes is valid, so I will go ahead and close this. 

Thanks for the tip! I'm also not 100% sure how you link from the latest commit, but from the latest commit here (https://github.com/googleapis/google-cloud-go/commit/a17ff67164645328d301ee1884c7ba42f35ef7ba?branch=a17ff67164645328d301ee1884c7ba42f35ef7ba), it is L1524 in the admin.go file. Or the latest commit that touched that line, which would be this: https://github.com/googleapis/google-cloud-go/commit/a370b006259c0f61fe43f772b40424c318439adb#diff-c0d0b1bb493e787158b8d7b5d3dbed82e559957bb0219167b427dfcfb90a4bf1R1314
