### ISSUE TITLE
question: Why does go.sum contain github.com/golang/exp

### ISSUE THREAD

**Issue by qlcom** [googleapis/google-cloud-go#2893]
i think `go mod tidy` should be run

**Comment by codyoss** [comment]
It is actually right to be in there. If you run `go mod tidy` you will see it does not get removed. Although it is not a direct dependency it is a transitive one. If you are every curious where a transitive dependency like this is coming from `go mod graph` can be a useful tool, especially when paired with something like [modgraphviz](https://pkg.go.dev/golang.org/x/exp/cmd/modgraphviz) to make consuming the data visual.

**Comment by qlcom** [comment]
it was in `go.mod` https://github.com/googleapis/google-cloud-go/commit/4b3b7e572bc8141b535f0f2316c721e0d4289f12
