### ISSUE TITLE
pubsub/pstest: allow updating subscription retry policies

### ISSUE THREAD

**Issue by tommyreddad** [googleapis/google-cloud-go#2900]
**Is your feature request related to a problem? Please describe.**
The testing stub does not support updating a subscription's retry policy, which should be supported since `cloud.google.com/go/pubsub v1.5.0`. Currently, attempting to update a subscription's retry policy gives the error `unknown field name "retry_policy"`.

**Describe the solution you'd like**
The testing stub should support updating a subscription's retry policy.

**Additional context**
A similar issue about updating a subscription's dead letter policy was fixed here: https://github.com/googleapis/google-cloud-go/pull/2632.

**Comment by tommyreddad** [comment]
I'm happy to send a quick PR in for this if that's alright?

**Comment by hongalex** [comment]
Hiya, thanks for the heads up. I'll actually have this fixed by today/tomorrow so if you could hang tight that'd be great!

**Comment by hongalex** [comment]
Released in pubsub/v1.6.2

Thanks!
