### ISSUE TITLE
search: support for Cloud Search

### ISSUE THREAD

**Issue by willie** [googleapis/google-cloud-go#2908]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a package to interface with Cloud Search.

**Describe the solution you'd like**
A package to interface with Cloud Search.

**Describe alternatives you've considered**
Apparently only Java and Python have a library. I'm looking for REST documentation instead.

**Comment by codyoss** [comment]
The equivalent package for Go is in our REST/HTTP client repo. Please see: https://pkg.go.dev/google.golang.org/api/cloudsearch/v1

**Comment by willie** [comment]
Thank you. I had no idea.
