### ISSUE TITLE
pubsub: Allow option to turn off stackdriver client metrics

### ISSUE THREAD

**Issue by adam-cv** [googleapis/google-cloud-go#2911]
**Is your feature request related to a problem? Please describe.**
Using NewClient to setup the pubsub call you are unable to turn off the openCensusOptions call.

Line in question: o = append(o, openCensusOptions()...)

This causes pubsub client metrics to be published to stackdriver by default with no option to disable.

**Describe the solution you'd like**
Either setting of an environment variable to enable the config or to remove the line as the option can be passed directly into the NewClient call.

**Describe alternatives you've considered**
At the moment the line is commented out as the additional metrics are not needed. This is not ideal as when go mod tidy is run the change is reverted. As it is a core library it's not ideal to create a fork of the package with the change.

**Additional context**
Added the function in question, the client supports options being passed, ideally the metrics would be passed into the client or a os.GetEnv to stop the openCensusOptions being appended to the client.

````
func NewClient(ctx context.Context, projectID string, opts ...option.ClientOption) (c *Client, err error) {
	var o []option.ClientOption
	// Environment variables for gcloud emulator:
	// https://cloud.google.com/sdk/gcloud/reference/beta/emulators/pubsub/
	if addr := os.Getenv("PUBSUB_EMULATOR_HOST"); addr != "" {
		conn, err := grpc.Dial(addr, grpc.WithInsecure())
		if err != nil {
			return nil, fmt.Errorf("grpc.Dial: %v", err)
		}
		o = []option.ClientOption{option.WithGRPCConn(conn)}
	} else {
		numConns := runtime.GOMAXPROCS(0)
		if numConns > 4 {
			numConns = 4
		}
		o = []option.ClientOption{
			// Create multiple connections to increase throughput.
			option.WithGRPCConnectionPool(numConns),
			option.WithGRPCDialOption(grpc.WithKeepaliveParams(keepalive.ClientParameters{
				Time: 5 * time.Minute,
			})),
		}
		** o = append(o, openCensusOptions()...)**
	}
	o = append(o, opts...)
	pubc, err := vkit.NewPublisherClient(ctx, o...)
	if err != nil {
		return nil, fmt.Errorf("pubsub: %v", err)
	}
	subc, err := vkit.NewSubscriberClient(ctx, o...)
	if err != nil {
		// Should never happen, since we are passing in the connection.
		// If it does, we cannot close, because the user may have passed in their
		// own connection originally.
		return nil, fmt.Errorf("pubsub: %v", err)
	}
	pubc.SetGoogleClientInfo("gccl", version.Repo)
	return &Client{
		projectID: projectID,
		pubc:      pubc,
		subc:      subc,
	}, nil
}
````

**Comment by codyoss** [comment]
Does [option.WithTelemetryDisabled](https://pkg.go.dev/google.golang.org/api/option#WithTelemetryDisabled) work?

**Comment by adam-cv** [comment]
I don't think so as openCensusOptions function that is being called uses a default client with no obvious way of setting / passing that value:
````
func openCensusOptions() []option.ClientOption {
	return []option.ClientOption{
		option.WithGRPCDialOption(grpc.WithStatsHandler(&ocgrpc.ClientHandler{})),
	}
}
````

**Comment by adam-cv** [comment]
Thanks for your help, that seems to have stopped the stackdriver metrics being recorded.

Closing.
