### ISSUE TITLE
logging:  entry incompatible with json/yaml marshalers 

### ISSUE THREAD

**Issue by adasari** [googleapis/google-cloud-go#2912]
Hello,

I recently started using Cloud logging client to get the logs from the gcloud. 

json/yaml Marshal of log entry is failing/incorrect due to following

1. payload is not compatible with json/yaml marshaller in json and proto payload case
https://github.com/googleapis/google-cloud-go/blob/411f8bc8cb59352cdb5e38d2af21a0fd30fd1407/logging/logadmin/logadmin.go#L299
https://github.com/googleapis/google-cloud-go/blob/411f8bc8cb59352cdb5e38d2af21a0fd30fd1407/logging/logadmin/logadmin.go#L306

Can json payload and proto payload converted into map[string]interface{} and assigned to payload ? 

2. Request field of HTTPRequest is http.Request
https://github.com/googleapis/google-cloud-go/blob/411f8bc8cb59352cdb5e38d2af21a0fd30fd1407/logging/logging.go#L656 
yaml marshal fails for http.Request because of func fields. Also, CacheFillBytes and CacheLookup are missing in the HTTPRequest.
is there any reason to use http.Request here ? can this be replaced with explicit fields ?

Please share your thoughts. 

Thanks.

**Comment by adasari** [comment]
because of above mentioned issues, had to use explicit log entry struct in my application. This is additional overhead. 
Also, CacheFillBytes and CacheLookup are still missing.

**Comment by codyoss** [comment]
Can you please provide a sample payload and a small snippet of code showing what you are trying to do.

Also, please provide the version of cloud.google.com/go/logging you are using.

**Comment by adasari** [comment]
@codyoss  i am using cloud.google.com/go/logging v1.1.0 

reproducer is available at https://gist.github.com/adasari/86de47380e00fd24d29daebc6317799f
Let me know if it requires additional information

**Comment by adasari** [comment]
would like to check if the issue is reproducible ? thanks. any feedback ?

**Comment by nicoleczhu** [comment]
@adasari : You are doing the right steps. To log the httprequest type, you do have to explicitly create an `entry` in your application. We hope to get rid of this additional overhead in the future as we improve this client library. 

Regarding the errors in your code snippet:
1. `// error : json: unsupported type: func() (io.ReadCloser, error)`
You don't need to encode the Entry again. You can directly log at this point by calling `client.Logger("your-log-name").Log(httplog)`

2. `// json payload - incorrect json transformation. Struct{} json marshal is incocrect`
I wasn’t able to reproduce this. Running your sample code, the marshalled JSON object looks correct with a Payload property of: 
```
"Payload": {
    "testing": "123"
  },
```
What are format are you expecting here?

3. Missing CacheFillBytes & Cachelookup
This should auto populate after you do the above steps

**Here's a clearer sample for how it all ties together:**

```go
func indexHandler(w http.ResponseWriter, r *http.Request) {
  client, err := logging.NewClient(r.Context(), "my-project")
  if err != nil {
    log.Fatalf("Failed to create logging client: %V", err)
  }
  defer client.Close()

  logger := client.Logger("my-log")

  entry:= logging.Entry {
    // your actual log goes here
    Payload: "Hello World", 
    HTTPRequest: &logging.HTTPRequest {
      Request: r,
    },
  }

  // Log your message
  logger.Log(entry)
```
