### ISSUE TITLE
logging: LogSink does not include exclusions

### ISSUE THREAD

**Issue by derekperkins** [googleapis/google-cloud-go#2930]
In the Google Cloud docs, new LogSinks have an array of exclusions, which matches what the UI enables (screenshot below).
https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#google.logging.v2.LogSink

The autogenerated REST Google APIs also have them,
https://pkg.go.dev/google.golang.org/api@v0.32.0/logging/v2#LogSink

but the autogenerated protos do not have them
https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging_config.proto#L465-L579
https://pkg.go.dev/google.golang.org/genproto/googleapis/logging/v2#LogSink

Is this a case where the public protos don't match internal protos for some reason? The REST docs say that they are deprecated and to not use them, but if we want to use exclusions, is there another way to get access to them?

![image](https://user-images.githubusercontent.com/3588778/94494629-e309b900-01ac-11eb-83bc-bca888e6c307.png)

**Comment by codyoss** [comment]
My understanding is that this field should be in the public protos. I have filed an internal bug to track this being surfaced. Thank you for bringing this to our attention!

Internal bug: 170250364

**Comment by derekperkins** [comment]
Thanks for the follow up, it seemed like that was likely the case.

**Comment by nicoleczhu** [comment]
Hi @derekperkins ,

Thanks again for helping us identifying this discrepancy! This issue will be fixed in the next client library release. I'll update here again as soon as that happens.

**Comment by derekperkins** [comment]
@nicoleczhu any updates? There have been a number of releases, but none have included this, even in the autogenerated gapics updates.

**Comment by nicoleczhu** [comment]
Hi @derekperkins , The Logging API hasn't been updated yet. This would come out with those updates in a major release. The GAPIC updates within the client library itself wouldn’t include this fix. 

I pinged our internal team to push that users really want this rolled out soon. Thanks for your patience

**Comment by nicoleczhu** [comment]
@derekperkins it's in: https://github.com/googleapis/go-genproto/blob/7adebfbe6a3f014cd2a30b5ec8a2fbdf18d7ab84/googleapis/logging/v2/logging_config.pb.go#L414

Let me know if you encounter issues using it through this client library though. There's a small chance the client library itself needs to be tweaked to allow users to modify exclusions. Though given the non-opinionated way in which this library was written, new parameters should be usable out of the box.

**Comment by derekperkins** [comment]
Great, thanks for pushing that through!
