### ISSUE TITLE
all: add testing support to clients

### ISSUE THREAD

**Issue by zhongduo** [googleapis/google-cloud-go#2943]
**Is your feature request related to a problem? Please describe.**
All the clients in this repo, such as pubsub client and metadata client, are concrete structs without a testing version. This makes unit test of any code using it very difficult. Here are several example problems I encountered:

1. Needs to mimic error return from pubsub client calls. Fortunately pubsub has a test server, so I can get around by adding error injection to the ps test server. Though I still have not figured out how to fail the client creation part.

2. We have logic to query the project id from metadata client if not set. However, I couldn't find any way to mimic this.

3. I want to inject error in the `Policy` function in `iam.go` to mimic an error state, however I couldn't find a proper way to inject that either, as no testing iam server exists.

What we end up doing most of the time is to avoid using this library directory in our code, but instead define interfaces for most objects in this repo and implement a wrapper in production. This is quite a maintenance burden and tedious process. It will be nice to have some support from this repo directly.

**Describe the solution you'd like**

I think it might makes sense to add more testing server like the pubsub testing server, and allow reactors to mimic the server behavior, this will allow quite some flexibility of the code. This server hopefully can support most cloud client features like metadata resolving etc.

**Describe alternatives you've considered**
What we end up doing most of the time is to avoid using this library directory in our code, but instead define interfaces for most objects in this repo and implement a wrapper in production. This is quite a maintenance burden and tedious process. It will be nice to have some support from this repo directly.
**Additional context**

**Comment by codyoss** [comment]
Hey,

> What we end up doing most of the time is to avoid using this library directory in our code, but instead define interfaces for most objects in this repo and implement a wrapper in production.

This is the current recommenced approach. Please see our [testing.md](https://github.com/googleapis/google-cloud-go/blob/master/testing.md) for other options we currently recommend.(fakes and emulators)

> I think it might makes sense to add more testing server like the pubsub testing server, and allow reactors to mimic the server behavior, this will allow quite some flexibility of the code. 

PubSub is a bit unique in that it has a manual hand written layer in front of it, this is the layer for which a fake is written(`pstest`). Most of the clients found in this repository are auto-generated from protos.

**Comment by zhongduo** [comment]
Hi @codyoss ,

Thanks for the answer. I am interested in the fake server part as we are already using `pstest` fake server and it will be very useful to build one ourselves. I know the testing.md is already quite good, but is there any ready-to-run example available? I am using the metadataclient as an example, but it is still not straightforward to me about how to do it. At least I didn't find the `Unimplemented` class.

The reason I don't like mocking the interfaces are: 1) it makes our product code hard to understand with lots of small interfaces like TopicInterface, I would rather offload the complexity to our testing code instead, 2) it does not test the client part, eg if we are using conflict  client options, my mocking interface might not do the check.

**Comment by codyoss** [comment]
`compute/metadata` is actually a handwritten client that makes requests against the metadata service. So the faking approach mentioned for gRPC does not apply to that client. But the metadata client does support a sort of emulation mode, where you could write fakes against an HTTP server. Just spin up a server which listens on the correct routes for the endpoints you are hitting. Then set `GCE_METADATA_HOST ` to your server address. This is lightly documented [here](https://pkg.go.dev/cloud.google.com/go/compute/metadata#Client.Get)

**Comment by zhongduo** [comment]
Hi Cody,

Thanks for the information, it will be tricky for me to find this out. I
guess generally it will be very useful to have a minimal fake server with
minimal configuration for people to test their code against. Eg. a json
file to define project information etc as the metadata client will likely
be used to resolve project id or other default metadata. Anyway, it seems
that the existing framework can already support gRPC mocking from a fake
server. A working example will be highly appreciated, but otherwise we can
close this issue.

Thanks again.

Thanks,
Jimmy

**Comment by codyoss** [comment]
@zhongduo Thanks for the feedback. I will try to find a spot where we can put a full working example of the code mentioned in the testing doc.
