### ISSUE TITLE
gcloud cli: config replaced on sync

### ISSUE THREAD

**Issue by tvvignesh** [googleapis/google-cloud-go#2957]
Hi. I am not sure if this is the right place to file this issue for issues related to gcloud sdk/CLI but still.

I  use GKE and I guess gcloud syncs kubeconfig at periodic intervals (not sure) to keep creds updated.

But, if I edit the kubeconfig manually to add the `proxy-url` flag (https://github.com/kubernetes/client-go/issues/351) it works well without any issues but after some considerable time, the config gets reset automatically and my edits gets lost.

I suspect that gcloud is synchronizing the config and overwriting existing config removing the edits I added.

Environment:
```
Google Cloud SDK 312.0.0
alpha 2020.09.25
beta 2020.09.25
bq 2.0.61
core 2020.09.25
gsutil 4.53
kubectl 1.15.11
```

**Comment by codyoss** [comment]
For the CLI, please file issues [here](https://issuetracker.google.com/issues/new?component=187143&template=0)
