### ISSUE TITLE
pubsub: How to avoid duplicate message receiving in Google pubsub

### ISSUE THREAD

**Issue by reachlakstar** [googleapis/google-cloud-go#2960]
**Client** 

Pubsub

**Go Environment**

$ go version
$ go env
1.15
	cloud.google.com/go/pubsub v1.6.1

**Code**
 pubsub.ReceiveSettings{
			MaxExtension:       30 * time.Minute, 
		}

**Expected behavior**
 No duplicate messages 

**Actual behavior**
 Actual data in pubsub topic is 300m with 200 subscribers, we are  receiving around 800M  records even after setting max extension time 30 mins.
 
how to avoid these duplicates?

**Comment by hongalex** [comment]
Hi, thanks for filing an issue.

Could you clarify what the ack deadline extension is on your subscription?

**Comment by reachlakstar** [comment]
@hongalex which parameter is that? i dont see ack deadline extension on the client side.
Are you referring to this?
pubsub.ReceiveSettings{
MaxExtension: 30 * time.Minute,
}

**Comment by hongalex** [comment]
Ah, apologies, I meant to ask what the acknowledgement deadline is for your subscription. Rather than on the client side, I'm curious what the setting is in on the subscription that was created by the server.

You can see this information in the [Pub/Sub console](http://console.cloud.google.com/cloudpubsub/subscriptions) or by running `gcloud pubsub subscriptions describe your-sub`.

**Comment by reachlakstar** [comment]
Retry policy 
Retry after exponential backoff delay
Minimum backoff duration
10 Seconds
Maximum backoff duration
600 Seconds
Acknowledgement deadline 
600 Seconds
@hongalex

**Comment by hongalex** [comment]
Apologies for the delay, this seems to have fallen off my radar for a while. Depending on processing time, it's still possible that messages are expiring prior to the messages being acked. Even 30 minutes might not be enough assuming that messages are delivered in large batches, overwhelming individual subscriber clients. This can be mitigated by increasing the number of goroutines (limited by the host machine) or switching `ReceiveSettings.Synchronous = true`.

**Comment by reachlakstar** [comment]
@hongalex yes i have changed the sync = true but throughput is less.

**Comment by hongalex** [comment]
Could you check your message backlog to see if you are processing messages at at reasonable pace? Per my previous comment, if you are not using synchronous mode, your messages might be expiring and the way to tell is checking your message backlog. The `oldest_unacked_message_age` metric in Cloud Monitoring should show you this. There are [other metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-pubsub) that might be useful to monitor as well here.

**Comment by hongalex** [comment]
Closing for now, this likely isn't an issue with the client library so if you're still having issues I would recommend posting to the `google-cloud-pubsub` tag on StackOverflow.
