### ISSUE TITLE
firestore: support != and not-in operators

### ISSUE THREAD

**Issue by mbaynton** [googleapis/google-cloud-go#2974]
Per https://firebase.googleblog.com/2020/09/cloud-firestore-not-equal-queries.html, Firestore now supports the `!=` and `not-in` operators in filters.

Support is needed in the client library, though.

**Comment by akavel** [comment]
FWIW, the relevant code seems to be [in firestore/query.go filter.toProto()](https://github.com/googleapis/google-cloud-go/blob/9e64b018255bd8d9b31d60e8f396966251de946b/firestore/query.go#L492-L511) if that might help anyone with enough time at hands to open a PR.

**Comment by mbaynton** [comment]
I just don't have the confidence that that's the only change required to do it right, or I'd try my hand at it

**Comment by akavel** [comment]
@mbaynton you can always try and see what happens :) that's a great way to learn a codebase, and a great way to contribute [speaking as an open-source maintainer myself] :) if at some point you decide it's too much for you, you can always close the PR and go on with your life, that's business as usual in open-source world :) [I'm not affiliated with Google or this project, just to clarify].

**Comment by tritone** [comment]
@benwhitehead is this feature on the libraries roadmap? Any reason we can't add support here?

**Comment by BenWhitehead** [comment]
It is on the roadmap, right now we're working on scheduling the resources to get it implemented.
