### ISSUE TITLE
all: document that users should call client.Close()

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#3031]
**Client**

All.

**Code**

e.g.
```go
package main

func main() {
	client, err := foo.NewClient()
	if err != nil {
		// ...
	}
	defer client.Close() // <--- This line.
}
```

**Expected behavior**

GoDocs and any other relevant documentation should make it very clear users should call `Close()` when done with a client. @codyoss mentioned we may want to start a "best practices" doc to put these types of tips in.

**Additional context**

New and experienced users have had apparent memory leaks due to leaving clients open.

**Comment by tbpg** [comment]
We should also mention if/how clients are safe for concurrent use.

`storage.Client` does (https://pkg.go.dev/cloud.google.com/go/storage#Client), but `datastore.Client` does not (https://pkg.go.dev/cloud.google.com/go/datastore#Client).

**Comment by someone1** [comment]
stumbled here by accident, but I remember going through this exercise myself, it appears the code is already documented on this, and calling `Close` seems to be client specific, and not a requirement:

[PubSub](https://github.com/googleapis/google-cloud-go/blob/master/pubsub/pubsub.go#L99): `If the client is available for the lifetime of the program, then Close need not be called at exit.`

[Storage](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L155): `Close need not be called at program exit.`

But others, such as datastore, kmsclient, etc. do recommend it when done with the client (they specifically appear to be using connection pools).

**Comment by ottob** [comment]
Doesn't this also depend on how/where the code will run? I think I read somewhere that for cloud functions it's not recommended to call `Close`. Is that correct?

**Comment by tbpg** [comment]
As a rule of thumb, if you are able to clean up, you should. So, even if it's not _required_ to call `Close`, I still would (and I do).

> I think I read somewhere that for cloud functions it's not recommended to call Close. Is that correct?

Cloud Functions instances handle a single request a time, but might stick around for more than one request before being cleaned up. In that case, it makes sense to _not_ close the client, because that's better than having to reinitialize a client on every function invocation. However, that means you need to store the client in the global scope. Does that make sense?

**Comment by ottob** [comment]
That makes sense and is what Ive done too. I was just curious if that should also be mentioned in the client docs. Or perhaps it's enough if this special case is explained in the cloud function docs.

**Comment by tbpg** [comment]
> Or perhaps it's enough if this special case is explained in the cloud function docs.

I think so, but I'm open to ideas. In the Cloud Functions case, you're not "done" with the client when you finish processing an event, so it doesn't contradict, but it's not entirely clear.

**Comment by codyoss** [comment]
This is now documented on all client factory methods.
