### ISSUE TITLE
firestore: DataAt* methods don't return distinct error for non-existent fields

### ISSUE THREAD

**Issue by taralx** [googleapis/google-cloud-go#3080]
DataAt* will return NotFound if you call them on a non-existent document (which is a bit weird, since that error has already been returned to you), but just return a generic error if you call them for a non-existent field path. This is less than useful, since there's no easy way to test for field existence otherwise.

**Comment by tritone** [comment]
@benwhitehead any thoughts? Is there another preferred way to test whether a path exists?

**Comment by BenWhitehead** [comment]
Without seeing what the underlying errors are from the backend it's hard to say. The only way I know of to test if a document or collection exists is to try to get it either via the [`GetDocumentRequest`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.GetDocumentRequest) or the [`ListCollectionIdsRequest`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#listcollectionidsrequest).

/cc @crwilcox

**Comment by taralx** [comment]
Note: this isn't about document existence, it's about field existence.

**Comment by crwilcox** [comment]
I think this is a duplicated of #2980, closing as such
