### ISSUE TITLE
spanner: tracing error "no more items in iterator" on iter.Do

### ISSUE THREAD

**Issue by RafaelAdao** [googleapis/google-cloud-go#3110]
**Client**

Spanner (v1.10.0)

**Code**

The following code is a code snippet from [spanner#read.go](https://github.com/googleapis/google-cloud-go/blob/master/spanner/read.go#L191), and the explanation of the problem comes after the code.

```go
func (r *RowIterator) Do(f func(r *Row) error) error {
	defer r.Stop()
	for {
		row, err := r.Next()
		switch err {
		case iterator.Done:
			return nil
		case nil:
			if err = f(row); err != nil {
				return err
			}
		default:
			return err
		}
	}
}

func (r *RowIterator) Stop() {
	if r.streamd != nil {
		defer trace.EndSpan(r.streamd.ctx, r.err)
	}
	if r.cancel != nil {
		r.cancel()
	}
	if r.release != nil {
		r.release(r.err)
		if r.err == nil {
			r.err = spannerErrorf(codes.FailedPrecondition, "Next called after Stop")
		}
		r.release = nil
	}
}
```

When using [spanner#RowIterator.Do](https://godoc.org/cloud.google.com/go/spanner#RowIterator.Do), when `err` equals `iterator.Done`, then `r.Stop ()` is called. In the `Stop()` function, `err` is being traced with "no more items in iterator". Is this really correct? This trace is hindering the visualization of possible real errors that may be happening.

**Expected behavior**

I think the error "no more items in iterator" should be ignored in `trace.EndSpan`.

**Actual behavior**

The "no more items in iterator" error is overflowing the opencensus trace.

**Screenshots**

Look the error rate of at 99.8%. All of this errors is `UNKNOWN: no more items in iterator`.
![image](https://user-images.githubusercontent.com/5923706/97617108-2188d280-19fc-11eb-87ac-e848afe6a08a.png)

**Comment by skuruppu** [comment]
@olavloite assigning to you to take a look.
