### ISSUE TITLE
firestore: add function to get batch writes count

### ISSUE THREAD

**Issue by taltultc** [googleapis/google-cloud-go#3124]
I'm always frustrated when I need to add a counter to the batch, to make sure:
1. Not commit the batch if no writes in the batch. this is important because you can get other errors when trying to commit, so I push all the error logs to gcp Error Reporting service, so I'm getting a lot of errors like this: **firestore: cannot commit empty WriteBatch**
2. not exceed 500 max writes limit

**Describe the solution you'd like**
Adding to `writebatch.go` function that returns the writes count.
```
func (b *WriteBatch) GetWritesCount() int {
	return len(b.writes)
}
```

**Describe alternatives you've considered**
alternative solutions are to add a counter every time I add write to the batch

**Comment by telpirion** [comment]
[BatchWrites](https://github.com/googleapis/google-cloud-go/blob/main/firestore/writebatch.go#L30-L32) has been deprecated in favor of [Bulkwriter](https://github.com/googleapis/google-cloud-go/blob/main/firestore/bulkwriter.go) and [Transaction](https://github.com/googleapis/google-cloud-go/blob/main/firestore/transaction.go).
