### ISSUE TITLE
logging: configure additional kokoro run for just logging & error reporting

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/google-cloud-go#3134]
I'm not sure how to do this, but it would be great to be able to track CI just for logging & error reporting submodules. Our team has a dashboard and an oncall rotation. This would greatly speed up our processes.

Any pointers or resources for how to do this would be greatly appreciated!

**Comment by Daniel-Sanche** [comment]
I did a bit of research into this today. It involves some internal processes, so I left the notes in go/isolating-go-lib-tests

**Comment by nicoleczhu** [comment]
this is done
