### ISSUE TITLE
datastore: best practice on schema changes

### ISSUE THREAD

**Issue by someone1** [googleapis/google-cloud-go#3146]
### Is your feature request related to a problem? Please describe.
Sent here after opening a support case with GCP for guidance (Case 25666310)

We are seeking guidance for best practice or patterns we can follow as we roll out datastore schema changes. **This is specific to Go and the datastore library provided by this repo**. Some other languages, such as Python or Node.js, do not impose strict restrictions on models so unknown fields are carried along and written back to datastore (e.g. Expando Properties) whereas in Go missing fields from the struct throw an error.

The problem seems to occur for a multi-service or backend designed application. For instance, an AppEngine API with 100s of instances and you want to slowly roll out a new version to test changes to your code including datastore schema changes. Or perhaps an API implemented purely with Google Cloud Functions. It may be impossible and/or undesirable to update all services at once that depend on a given datastore model. What ends up happening is that changes introduced in a new version starts to break code in old versions.

### Describe the solution you'd like
We would like to see some documented best practice or general use case patterns we can follow to ensure smooth migrations in our datastore schema, hopefully sourced from successful and battle-hardened implementations.

This may be aided by a new features in this repo. Some ideas (trying to piggyback on the Expando model idea):
* Introduce support in `LoadStruct` such that any unknown fields would be placed into a `[]datastore.Property` or `dastastore.PropertyList` field found on the struct with a special case fieldname or struct tag option
* Update `LoadStruct` to return a `MultiError` so we can track which fields failed to load and implement something like the above on our own while implementing the `PropertyLoadSaver` interface.

### Describe alternatives you've considered
There are several use cases we can think of and ideas on how they can be implemented. The below are some thoughts on the topic, and although not explicitly discussed/shown below, we do follow a versioning pattern where every single Kind in datastore is given a version, and we keep code to migrate between versions available (implemented in a `Load` function satisfying the `PropertyLoadSaver` interface).

For example:

```go

const latestModelVersion = 4

type Model struct {
  Version int `datastore:"v"`
}


func (m *Model) Load(ps []datastore.Property) error {
  if err := datastore.LoadStruct(m, ps), err != nil {
      return err
   }
   switch m.Version {
     case latestModelVersion:
        break // no-op
     case 1:
      m.migrateV1ToV2()
      fallthrough
     case 2:
      m.migrateV2ToV3()
      fallthrough
     case 3:
      m.migrateV3ToV4()
     default:
        if m.Version > latestModelVersion {
            break // new version being rolled out
        }
        return fmt.Errorf("unexpected version encountered: %d", m.Version)
  }

  return nil
}

func (m *Model) Save() ([]datastore.Property, error) {
        m.Version = latestModelVersion
	return datastore.SaveStruct(m)
}
```

#### Removing a property from the schema
This one seems straight forward:

1. Roll out a version of your code removing all dependencies on the field you want to remove from the struct/schema
2. After that code is fully rolled out, push a new version that actively removes the field in a `PropertyLoadSaver` implementation:

```go
type Model struct {
  FieldToKeep int64
  // FieldToRemove string
}

func (m *Model) Load(ps []Property) error {
  for idx := range  ps {
      if ps[idx].Name == "FieldToRemove" {
        ps = append(ps[:idx], ps[idx+1:]...)
        break
     }
  }

  return datastore.LoadStruct(m, ps)
}
```

#### Adding a property from the schema
A couple of ideas here:

**For a 2-phase roll out:**
1. Roll out a version of your code introducing the new field as a pointer and with the `omitempty` struct tag option, make no use of this field yet
2. After that code is fully rolled out, push a new version that then uses this field, changing it from a pointer and/or removing the `omitempty` struct tag option of necessary

```go
type Model struct {
  FieldToKeep int64
  // FieldToRemove string
 FieldToIntroduce *time.Time `datastore:",omitempty"`
}
```

**For a single version roll out (preferred):**
Ensure you follow a pattern where your models implement some sort of "catch-all" feature, such that any unknown fields from `datastore.LoadStruct` are carried with the entity:

```go
type Model struct {
  CatchAll []datastore.Property `datastore:"*,catchall"`
}


func (m *Model) Load(ps []datastore.Property) error {
  // If `LoadStruct` is updated to support the `catchall` property:
  if err := datastore.LoadStruct(m, ps), err != nil {
      return err
   }
  
  // If `LoadStruct` is updated to return a MultiError where entries in the slice that are non-nil correspond to the property in ps that couldn't be loaded
  if err := datastore.LoadStruct(m, ps), err != nil {
      if merr, ok := err.(datastore.MultiError); ok { // Maybe a MultiMismatchError
         m.CatchAll, err = getMissingProperties(ps, merr) // only returns `no such struct field` errors to the `CatchAll`, which doesn't necessarily need to be exported in this scenario
      }
      if err != nil {
        return err
      }
   }

  return nil
}

func (m *Model) Save() ([]datastore.Property, error) {
        ps, err := datastore.SaveStruct(m)
	return append(ps, m.CatchAll...), err
}
```

Although this doesn't require a 2-phased rollout, updates to entities must always be done in a Read -> Mutate Original Entity -> Write to ensure that the `CatchAll` list remains in tact.

#### Modifying an existing property on the schema
This seems like a combination of introducing a new field and then removing the old one - but is there a easier/more efficient way to do this?

**Additional context**
The above hasn't really been tested and requires some bit of overhead (changes done over 2 version rollouts). Are there known patterns/ways to improve upon the above?

**Comment by tritone** [comment]
@benwhitehead @crwilcox could you advise on best practices for handling this?

**Comment by crwilcox** [comment]
Hi @someone1 , the way you describe doing migrations seems reasonable enough. For services I have built where I have wanted migrations, we used [`golang-migrate`](https://github.com/golang-migrate/migrate ). This doesn't have first class support for datastore though.

I would expect a separate file, or method for each version, and for each to be executed in order. Typically an entity in the database can indicate which revision is being used. The provided sample is more or less that :)

While we could theoretically add a support to golang-migrate it would be a decent amount of work, so I don't think it is something we would be getting to soon.

Is there a specific issue you are encountering with your proposed solution?

**Comment by someone1** [comment]
@crwilcox - Thanks for the reply.

I haven't had specific issues with the above as it is just my musings on the topic, not a template that's seen years of success and is battle hardened to edge cases that could arise. Additionally, some goals are not achievable since the `LoadStruct` return does not specify which fields may have failed to load, just the last failure.

Some of the procedures mentioned above are left to the user to figure out (e.g. how do you transition between versions PRIOR to loading the struct and again AFTER especially if you delete properties between versions and/or modify/mutate fields). 

`golang-migrate` seems reasonable, but does it work at scale? It offers a migration path where you migrate the entire database at once, correct? Not as changes are rolled out and different versions of the code exist in production expecting different versions of the models?

I was hoping for something a bit more concrete in the form of a [best practice](https://cloud.google.com/datastore/docs/best-practices) [write up](https://cloud.google.com/docs/enterprise/best-practices-for-enterprise-organizations).

**Comment by crwilcox** [comment]
I have used `golang-migrate` in a global system to migrate schema of a cloud sql postgres database. I would be comfortable recommending following the model laid out there. However, `golang-migrate` can't be used directly as it doesn't support datastore as far as I know.

**Comment by someone1** [comment]
I'm not sure I follow how that model can apply to datastore especially for the scenarios I highlighted. Unlike the databases supported, datastore requires full read/write of entities, not just partials (columns):
  * Code testing new properties (columns) won't affect old code not aware of them since the old code will simply never query for new columns, whereas in datastore it's all or nothing (projection queries not withstanding), and old code not aware of new properties will return an error
  * Code updating entities (rows) doesn't need to worry about new columns since they can only update columns that code is aware of. In datastore, if you ignore errors mentioned above, the entity written by the old code will drop properties new versions of the code may be rolling out.
  * These examples don't include scenarios where "updating your application" isn't as simple as pushing out one new service, but could potentially span 100s of instances across 10s if not 100s of deployments (e.g. Functions).

For these reasons (more specific to Go and this library), models found elsewhere don't seem to apply here, at least not obviously. Support could be added to this library to assist in some ways (e.g. helping to identify which properties could not be loaded properly).

The best practice document goes into some detail for managing [datastore at scale](https://cloud.google.com/datastore/docs/best-practices#designing_for_scale), I hope I've highlighted issues not covered by that documentation, specific to this package, that could use some detail like the topics discussed in that document.

**Comment by telpirion** [comment]
I think this request is best handled by the documentation on cloud.google.com. I would log an issue [here](https://cloud.google.com/datastore/docs/best-practices) if you still require this information.

**Comment by remko** [comment]
@telpirion I'm not convinced this issue can be closed already. If the claim is that proper documentation is enough, then I'd like to see the documentation first, because I don't see it yet what this would say.

I currently have to write a lot of code and use code generators to make sure properties are not lost on e.g. rollbacks of the introduction of new properties. Other datastore SDKs don't suffer from this problem AFAIK (certainly not NDB, but I don't think the Python Datastore  libraries do either, as they just store all properties dynamically on the model). 
A little bit of extra help in the Go datastore library to assist in storing unrecognized properties in an opaque way so they are written back on subsequent writes would be extremely useful here.
