### ISSUE TITLE
spanner/spansql: support for Update in parseDMLStmt

### ISSUE THREAD

**Issue by lazeratops** [googleapis/google-cloud-go#3162]
**Is your feature request related to a problem? Please describe.**

Currently `spannertest` seems to be unusable with `UPDATE` SQL queries. `parseDMLStmt()` in `spansql/parser.go` seems to only support `DELETE`. There is a `TODO: Insert, Update` comment, but I was unable to find an associated feature request issue for this and not sure if it is planned, hence this request to put it on the roadmap. Relevant line: https://github.com/googleapis/google-cloud-go/blob/master/spanner/spansql/parser.go#L1284

**Describe the solution you'd like**

I would like for `UPDATE` DML to be parsed via `spansql` , which would enable us to properly test these statements via `spannertest`. Ideally `INSERT` would be parsed as well, but as `UPDATE` is more relevant for our immediate purpose I am focusing on that one here.

**Describe alternatives you've considered**

An alternative would be to update via an Update mutation instead. We will likely go with this solution for the time being, but being forced to change the implementation to a mutation solely to account for missing test functionality does not seem ideal.

Thanks!

**Comment by dsymonds** [comment]
Syntax types and parsing for `UPDATE` DML is now done in the spansql package. I'll be working on adding its implementation in spannertest next.

**Comment by dsymonds** [comment]
Implementation is out for review.

You could test it locally real quick by running commands like these in your repo:
```
go mod edit -replace cloud.google.com/go/spanner=github.com/dsymonds/google-cloud-go/spanner@spannertest-update-dml
go mod download
go mod tidy
go test ./...
```

and chime in on #3201 if there's something significantly wrong for your use case.
