### ISSUE TITLE
identityplatform: new SDK

### ISSUE THREAD

**Issue by sonatard** [googleapis/google-cloud-go#3163]
https://github.com/googleapis/google-cloud-go/issues/1925

@AlisskaPie commented this.

https://github.com/googleapis/google-cloud-go/issues/1925#issuecomment-614595802

But I need **Cloud Identity Platform** SDK. It's **Cloud Identity**.

Cloud Identity Platform
https://cloud.google.com/identity-platform/docs/apis
https://cloud.google.com/identity-platform/docs/use-rest-api

Cloud Identity
https://cloud.google.com/identity/docs/reference/rest

**Comment by sonatard** [comment]
Currently, we have to use Firebase admin SDK instead of Cloud Identity Platform SDK.
https://github.com/firebase/firebase-admin-go

But It hasn't kept up with the evolution of the Cloud Identity Platform.

**Comment by codyoss** [comment]
Hey, from the links you provided it looks like you are looking for identitytoolkit -- which like the other link provided to you is in another repository: https://pkg.go.dev/google.golang.org/api/identitytoolkit/v3.

**Comment by nyonson** [comment]
@codyoss I believe that is for the old Identity Toolkit offering of google cloud. The new Identity Platform offering is using `/identitytoolkit.googleapis.com/v1/`. I don't know why...but appears to be confirmed by the Identity Platform [docs](https://cloud.google.com/identity-platform/docs/use-rest-api).

**Comment by codyoss** [comment]
Hey @nyonson thanks for bring this back to my attention. I will look into this some more and get back to you.

**Comment by codyoss** [comment]
This work is unblocked now that there are public protos for the service: https://github.com/googleapis/googleapis/tree/master/google/cloud/identitytoolkit/v2

**Comment by codyoss** [comment]
@sonatard Closed a little early but I did open up the onboarding PR for this API today 😄

**Comment by sonatard** [comment]
@codyoss 👍 🎉 🎉 🎉
