### ISSUE TITLE
spanner/spansql: Multiple Joins support?

### ISSUE THREAD

**Issue by chrispotter** [googleapis/google-cloud-go#3180]
**Client**
Spanner

We are using `spannertest` for some unit testing and I just wanted to make sure I was formatting my queries correctly. I _suspect_ since join support was just added this is unsupported, just wanted to get some confirmation.

Right now I am seeing an error with the first LEFT OUTER JOIN

**Code**
```go
SELECT
	cart_items.cart_id,
	cart_items.product_id,
	cart_items.quantity,
	cart_items.create_time,
	cart_items.update_time,
	products.title,
	products.description,
	product_prices.amount,
	product_prices.currency_code,
	product_images.image_id,
	product_images.image_url,
	product_images.position,
	product_images.alt_text,
	product_images.create_time,
	product_images.update_time
FROM cart_items JOIN products USING(product_id)  
  LEFT OUTER JOIN product_prices USING(product_id) 
  LEFT OUTER JOIN product_images USING(product_id)
 WHERE cart_items.cart_id = @cart_id
	AND product_prices.amount IS NOT NULL
	AND product_images.position = 1
ORDER BY cart_items.create_time ASC,
	product_prices.update_time DESC
```

**Expected behavior**
I"m not sure if this is supported yet, I'd expect no error

**Actual behavior**
I'm getting an error from the parser because `parser.go` from spansql is not looping over join statements it seems (from a quick look)
`bad query: unexpected trailing query contents \"( \\n\\t\\t\\tLEFT OUTER JOIN product_prices USING(product_id)...`

Tangentially related to this when trying to present a minimum working statement for this issue I ran into another error
`can't deduce column type from expression [product_prices.amount]` when I changed the JOIN portion of the statement to:
```
...FROM cart_items JOIN products USING(product_id)  
 WHERE cart_items.cart_id = @cart_id
	AND product_prices.amount IS NOT NULL
	AND product_images.position = 1
ORDER BY cart_items.create_time ASC,
	product_prices.update_time DESC"
```
but I suspect this is because of the missing joins, but if that doesn't seem right please let me know.

**Comment by dsymonds** [comment]
Yes, multiple joins can (probably) be parsed, but aren't implemented in spannertest. It's a TODO; we can leave this issue to track that.
