### ISSUE TITLE
spanner: expose internal mocks

### ISSUE THREAD

**Issue by smugcloud** [googleapis/google-cloud-go#3204]
**Is your feature request related to a problem? Please describe.**
We would like to mock all spanner calls for unit tests.  I have been exploring `spannertest`, and while it does provide a reasonable approach to accomplish that task, it would be great to see something more flexible, that doesn't rely on data being populated for all tables that may be queried.

**Describe the solution you'd like**
In projects where MySQL is used as our data store, I have used DataDog's [sqlmock](https://github.com/DATA-DOG/go-sqlmock/blob/master/examples/blog/blog_test.go#L41-L45) which provides some nice helpers to accomplish this task.  It would be great if the `spanner/internal` package was exported for use, and some additional helpers created to accomplish the same tasks.  I have a fork that I can share but it essentially involves allowing the test to set a regular expression for expected queries, along with the expected StatementResult.  This continues to use a map in `getStatementResult`, but matches the actual SQL against the regex pattern registered (see example below)

```	
// AllColumnsMocked is a helper to generate the []*spannerpb.StructType_Field
fields := AllColumnsMocked("fake")

// Create a new row, with the appropriate types set for the values
sr := spannermock.NewRows(fields).AddRow("uuid", true, time.Now()).MakeStatementResult()

// Regular expression of the expected query
reg := "SELECT .* FROM Table.*"

// Register the regex and StatementResult in the map
mockedSpanner.TestSpanner.PutStatementResult(reg, sr)
```

**Describe alternatives you've considered**
I have built some tests using `spannertest` as well as a fork of `spanner/internal` to experiment with.  While we can use the fork, it would great to expose this in the `google-cloud-go` project for wider usage, and community support.

**Comment by skuruppu** [comment]
@smugcloud thanks so much for the feature request and apologies for taking so long to get to it.

I think this is a very reasonable request and I'm not opposed to exporting `spanner/internal`. The main concern that I have is that would it confuse users to have a mock service and `spannertest` available. @dsymonds what are your thoughts? Is there potential for `spannertest` to support this usecase? Or would you mind if a separate mock service was made available?

**Comment by dsymonds** [comment]
Go typically eschews invasive mocks like go-sqlmock for general testing, and instead encourages either using realistic fakes (something like `spannertest`), or by faking out a higher level interface that is more application-specific. Because Go interfaces and types are so lightweight and natural, that becomes a more elegant approach.

For instance, instead of mocking the specific data response to a Spanner API call, you would write a trivial little wrapper interface type that fetches application-specific data using application-specific nomenclature, use it in your code that you wish to test, and write a trivial implementation of that interface that uses Spanner. Then your test can simply provide its own little implementation of that interface.

**Comment by dsymonds** [comment]
(But to be more specific: I don't think exporting the things under `spanner/internal` is a good idea.)

**Comment by skuruppu** [comment]
Thanks for the feedback @dsymonds.

In that case @smugcloud, would you be open to trying the idea from @dsymonds?

**Comment by codyoss** [comment]
I did write a couple short examples on how to create your own fakes for clients in [testing.md](https://github.com/googleapis/google-cloud-go/blob/master/testing.md#testing-grpc-services-using-fakes).

**Comment by skuruppu** [comment]
We won't be proceeding with exposing the internal mocks. So closing the issue for now.
