### ISSUE TITLE
httpreplay: provide a debug-function to understand why requests do not line up during replay

### ISSUE THREAD

**Issue by buyology** [googleapis/google-cloud-go#3213]
**Is your feature request related to a problem? Please describe.**

When a request does not match any of the requests in the chain you currently get something along the following:

```
2020/11/16 15:59:37 ERROR: martian: failed to round trip: no matching request
for &{Method:POST
URL:https://service.googleapis.com
Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Encoding:[gzip]
Content-Length:[14063] Content-Type:[application/json]
User-Agent:[google-api-go-client/0.5] X-Cloud-Trace-Context:[XXXX/XXXX;o=0]
X-Goog-Api-Client:[gl-go/1.15.1 gccl/20201012]] Body:{Reader:0xc00ebb5530}
GetBody:<nil> ContentLength:14063 TransferEncoding:[] Close:false
Host:service.googleapis.com Form:map[] PostForm:map[] MultipartForm:<nil>
Trailer:map[] RemoteAddr:127.0.0.1:46738
RequestURI:/url
TLS:<nil> Cancel:<nil> Response:<nil> ctx:<nil>}
```

It is very difficult to tell from this what causes the mismatch due to the fact that you only see the incoming request — not the candidate requests — and for the incoming request you cannot easily see its body parts.

**Describe the solution you'd like**
It would be helpful if there was an equivalent to `DebugHeaders`, let's call it `DebugReplay`, that let's you debug the other criterias that lead to a non-matching request (`Method`, `URL`, `MediaType`, `BodyParts`) and printed some helpful output on when incoming and candidate requests mismatch on the form

```
method|url|media type|body parts mismatch: incoming %v, candidate %v
```

(In our recent experience differences in these are typically more likely than headers to be the cause of the mismatch!)

**Describe alternatives you've considered**
We currently temporarily patch the `httpreplay/internal/proxy.requestsMatch`-function with such a debug statement at each exit point of the function. Would be nice to avoid having to fork the library to get that functionality.

**Comment by tbpg** [comment]
This sounds reasonable to me. I'm not sure how to print the diff in a useful way, though. For `DebugHeader`, we know everything else about the request matches, so it makes sense to print the first mis-matched header. For this, how do you know if a request is "close enough" to the candidate request? Or are you thinking just print everything?

**Comment by codyoss** [comment]
Closing this as we did not hear back
