### ISSUE TITLE
spanner: inconsistency in spanner errors

### ISSUE THREAD

**Issue by yuriworisch** [googleapis/google-cloud-go#3215]
**Client**
Spanner (cloud.google.com/go/spanner)

**Environment**
- go 1.15
- spanner client v1.10.0 (cloud.google.com/go/spanner)

**Code**
```go

/*
		Sample table to reproduce the error:
		CREATE TABLE example_table (
                    column1 INT64 NOT NULL,
                    column2 STRING(32) NOT NULL,
                    column3 STRING(36) NOT NULL,
                ) PRIMARY KEY (column1, column2, column3)
*/

package main

ctx := context.Background()
client, err := spanner.NewClient(ctx, DB_STRING)
if err != nil {
	panic(err)
}
defer client.Close()

// Step 1: Attempt to update a record that does not exist.
	_, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
		cols := []string{"column1", "column2", "column3"}
		txn.BufferWrite([]*spanner.Mutation{
			spanner.Update("example_table", cols, []interface{}{1, "Example", "example1"}),
		})
		return nil
	})
	
	// Error returned (as expected): spanner: code = "NotFound", desc = "Row [1,Example,example1] in table example_table is missing. Row cannot be updated."
	panic(err)

// Step 2: Attempt to update and insert (in the same transaction) a record that does not exist.
	_, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
		cols := []string{"column1", "column2", "column3"}
		txn.BufferWrite([]*spanner.Mutation{
			spanner.Update("example_table", cols, []interface{}{1, "Example", "example1"}),
			spanner.Insert("example_table", cols, []interface{}{1, "Example", "example1"}),
		})
		return nil
	})
	
	// Error returned (not expected): spanner: code = "InvalidArgument", desc = "Row [1,Example,example1] in example_table was already inserted in this transaction."
	// Expected error: spanner: code = "NotFound", desc = "Row [1,Example,example1] in table example_table is missing. Row cannot be updated."
	panic(err)
	
	
	// Step 3: Attempt to insert the same record twice in the same transaction.
	_, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
		cols := []string{"column1", "column2", "column3"}
		txn.BufferWrite([]*spanner.Mutation{
			spanner.Insert("example_table", cols, []interface{}{1, "Example", "example1"}),
			spanner.Insert("example_table", cols, []interface{}{1, "Example", "example1"}),
		})
		return nil
	})
	
	// Error returned (as expected): spanner: code = "InvalidArgument", desc = "Row [1,Example,example1] in example_table was already inserted in this transaction."
	panic(err)
```

**Expected behavior**

Should return the following error in step 2: spanner: code = "NotFound", desc = "Row [1,Example,example1] in table example_table is missing. Row cannot be updated."

**Actual behavior**

It is returning the following error in step 2: spanner: code =" InvalidArgument ", desc =" Row [1, Example, example1] in example_table has already been inserted in this transaction.

**Additional context**

When creating a new table, the return is: `Inserting row [1,Example,example1] to table example_table requires that the row not already exist, but other mutations in the transaction require that row to exist. For example: Update(row); Insert(row) or Update(child_of_row); Insert(row)` but when use this scenario in our table that already exists, the spanner continues to return the unexpected error.

Therefore, in addition to the problem reported above, a doubt arises.
Does the spanner have any type of version control for tables?

**Comment by olavloite** [comment]
@yuriworisch 
I'm changing the type to 'Question' for the moment, as this does not seem to be directly related to the client library, but rather to what the backend is sending back in these cases. I.e. the client library is in this case just repeating what Cloud Spanner is reporting.

**Comment by skuruppu** [comment]
@yuriworisch really sorry for taking a long time to get to this. I tried out your example. For step 2, the error I get is:
```
spanner: code = "InvalidArgument", desc = "Inserting row [1,Example,example1] to table example_table requires that the row not already exist, but other mutations in the transaction require that row to exist. For example: Update(row); Insert(row) or Update(child_of_row); Insert(row)."
```

This error is trying to inform you that your transaction has unsatisfiable constraints by taking the statements in the entire transaction into account rather than just executing the statements in order and returning the first error.

In a case like this, you can use `spanner.InsertOrUpdate` to make the intent clear.

I hope that helps.

**Comment by skuruppu** [comment]
Closing issue but please reopen if you would like to discuss this any further.
