### ISSUE TITLE
Big table: Memory leak when invoking ReadRow

### ISSUE THREAD

**Issue by KristopherJordan** [googleapis/google-cloud-go#3235]
**Client**
Big Table

**Environment**
Docker on GKE

**Go Environment**

$ go version
`go version go1.14.2 darwin/amd64`
$ go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/usename/Library/Caches/go-build"
GOENV="/Users/usename/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/usename/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/usename/go/src/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/25/5xclvpys36q6x0td4j12g7g80000gn/T/go-build152441838=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Big table version:
`cloud.google.com/go/bigtable v1.6.0`

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"runtime"
	"syscall"
	"time"

	"cloud.google.com/go/bigtable"

	_ "net/http/pprof"

	log "github.com/sirupsen/logrus"
)

func GetRow(ctx context.Context, lookupKey string, c bigtable.Client) (*bigtable.Row, error) {
	startTime := time.Now().AddDate(0, 0, -1)
	filter := bigtable.ChainFilters(
		bigtable.FamilyFilter("family-name"),
		bigtable.TimestampRangeFilter(startTime, time.Time{}),
	)

	tbl := c.Open("table-id")
	row, err := tbl.ReadRow(ctx, lookupKey, bigtable.RowFilter(filter))
	if err != nil {
		return nil, err
	}
	return &row, nil

}

func PrintMemUsage() {
	var mem syscall.Rusage
	syscall.Getrusage(syscall.RUSAGE_SELF, &mem)

	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("\t HeapAlloc: %v MiB", bToMb(m.HeapAlloc))
	fmt.Printf("\t TotalAlloc: %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\t MaxRSS: %v  \n", mem.Maxrss)
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}

func main() {
	ctx := context.Background()
	client, err := bigtable.NewClient(ctx, "project-id", "instanse-id")
	if err != nil {
		log.Fatalf("error creating bt client: %w", err)
	}

	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	for {
		ctx = context.Background()
		_, err := GetRow(ctx, "look-up-key", *client)
		if err != nil {
			log.Fatal("error getting results: %w", err)
		}
		PrintMemUsage()
	}
}


```

**Expected behaviour**

We expect steady memory usage in the app that invokes bigtable.

**Actual behaviour**

We have the logic that handles the `bigtable` client and the invocation of the client in a separate app. We see that some of our pods suddenly get an incremental increase in memory usage, the number of goroutines running and how many open [allocated file descriptors](https://www.robustperception.io/kernel-file-descriptor-metrics-from-the-node-exporter).

A reproduced the issue running the app locally with:
`go tool pprof http://localhost:6060/debug/pprof/heap`
```
      flat  flat%   sum%        cum   cum%
  544.67kB 20.98% 20.98%   544.67kB 20.98%  google.golang.org/grpc/internal/transport.newBufWriter (inline)
  514.38kB 19.82% 40.80%   514.38kB 19.82%  google.golang.org/protobuf/internal/strs.(*Builder).AppendFullName
```

The memory output from the code above looks something like this:
```
go run main.go
	 HeapAlloc: 2 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20406272
	 HeapAlloc: 3 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20525056
	 HeapAlloc: 3 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20586496
	 HeapAlloc: 3 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20598784
...
	 HeapAlloc: 6 MiB	 TotalAlloc: 12 MiB	 MaxRSS: 24387584
	 HeapAlloc: 6 MiB	 TotalAlloc: 12 MiB	 MaxRSS: 24387584
	 HeapAlloc: 6 MiB	 TotalAlloc: 12 MiB	 MaxRSS: 24387584
	 HeapAlloc: 6 MiB	 TotalAlloc: 12 MiB	 MaxRSS: 24395776
```

Note: We don't have any goroutines in the app for reading the data from `ReadRow`. We are just looping over the results and parsing them into some struct.

Are there any best-practises we should know of when initiating the bigtable client that prevents this sudden increase in memory usage, number of running goroutines and open file descriptors after some time?

**Screenshots from the Graphana Dashboard**

Stats from a pod that gets this sudden increase in memory usage, number of running goroutines and open file descriptors.

Open file descriptiors:
![Screenshot 2020-11-19 at 13 11 31](https://user-images.githubusercontent.com/18208262/99664684-d7c66180-2a68-11eb-9a9d-24b2e016a479.png)

The Number of go routines:
![Screenshot 2020-11-19 at 13 12 43](https://user-images.githubusercontent.com/18208262/99664768-f9bfe400-2a68-11eb-83ac-d325cda89f2f.png)

**Comment by tbpg** [comment]
Thank you for the awesome issue writeup!

I haven't reproduced the issue locally yet, but something that stood out to me was passing `bigtable.Client` rather than `*bigtable.Client`. The `Client` type has some unexported fields that would get copied on each of those calls: https://github.com/googleapis/google-cloud-go/blob/bigtable/v1.6.0/bigtable/bigtable.go#L46.

Perhaps one of those (e.g. the connection pool) isn't getting cleaned up, because there is a copy for every single request? This is a total guess, so I could be way off. That also wouldn't explain why FDs and goroutines are stable for a period then start rising.

**Comment by tbpg** [comment]
Here is a general example of what I think could be going on by not passing a pointer: https://play.golang.org/p/KwHMkqrSU8w.

**Comment by KristopherJordan** [comment]
Thank you for the fast response @tbpg. The example above isn't a true copy of our production code, just something to reproduce it.

In the production code the bigtable client is a pointer to the `bigtable.client`, like:
```
type Client struct {
	BTClient       *bigtable.Client
}
```

And then get data  with something like:
```
func (c *Client) GetResults(ctx context.Context, lookUpKey string, days int) (*Results, error) {
	startTime := time.Now().AddDate(0, 0, -days)
	filter := bigtable.ChainFilters(
		bigtable.FamilyFilter(familyName),
		bigtable.TimestampRangeFilter(startTime, time.Time{}),
	)

	tbl := c.BTClient.Open(c.TableID)
	row, err := tbl.ReadRow(ctx, userID, bigtable.RowFilter(filter))
        ....
}
```

**Comment by tbpg** [comment]
Ah, that's unfortunate. :smiley: 

A common cause of memory leaks like this is not closing the client when you're done with it. I've seen similar profiles when a client is created on every request, then not closed when finished with the request. I noticed the client wasn't closed in your sample code, but it also only creates a single client. Perhaps check that in your production code?

(Clients are safe for concurrent use, so you can create a single one for your app instance and reuse it for all requests.)

**Comment by KristopherJordan** [comment]
We only create the bt client once when the app is initiated and close it when the app stops.

Something like:
```
func (c *Client) Init(ctx context.Context, config *config.Config) error {
	c.ProjectID = config.ProjectID
	c.InstanceID = config.BTInstanceID
	c.DefaultTableID = config.BTDefaultTableID

	var err error
	c.BTClient, err = bigtable.NewClient(ctx, c.ProjectID, c.InstanceID)
	if err != nil {
		return err
	}

	return nil
}
```

And closes the bt client when the app stops with something like:
```
func (c *Client) Close() error {
	if err := c.BTClient.Close(); err != nil {
		return err
	}
	return nil
}
```

And call `GetResults(ctx, key, days)` from the handler.

**Comment by tbpg** [comment]
Got it. That seems like a good setup. Unfortunately, that's the end of my immediate ideas of what could be wrong! Will need to reproduce the error to dig in a bit more.

**Comment by tbpg** [comment]
By the way, if you have a support contract, you may want to reach out and reference this issue. That can help us with priority.

**Comment by KristopherJordan** [comment]
ok. Tnx for looking into it @tbpg :)

**Comment by tbpg** [comment]
One more question, does the issue happen when you switch to passing a pointer in the sample code you gave?

**Comment by KristopherJordan** [comment]
I did a bit of refactoring to get the code example closer to the production code. But the incremental increase in memory usage is still an issue @tbpg.

Code
```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"runtime"
	"syscall"
	"time"

	"cloud.google.com/go/bigtable"

	_ "net/http/pprof"

	log "github.com/sirupsen/logrus"
)

// Fill in Config:
const projectID = ""
const instanceID = ""
const tableID = ""
const familyFilter = ""
const lookUpKey = ""

type Client struct {
	BTClient   *bigtable.Client
	ProjectID  string
	InstanceID string
	TableID    string
}

func (c *Client) Init(ctx context.Context) error {
	c.ProjectID = projectID
	c.InstanceID = instanceID
	c.TableID = tableID

	var err error
	c.BTClient, err = bigtable.NewClient(ctx, c.ProjectID, c.InstanceID)
	if err != nil {
		return fmt.Errorf("could not create bigtable client: %v", err)
	}

	return nil
}

func (c *Client) Close() error {
	if err := c.BTClient.Close(); err != nil {
		return fmt.Errorf("could not close bigtable client: %v", err)
	}
	return nil
}

func (c *Client) GetRow(ctx context.Context, lookupKey string) (*bigtable.Row, error) {
	startTime := time.Now().AddDate(0, 0, -1)
	filter := bigtable.ChainFilters(
		bigtable.FamilyFilter(familyFilter),
		bigtable.TimestampRangeFilter(startTime, time.Time{}),
	)

	tbl := c.BTClient.Open(c.TableID)
	row, err := tbl.ReadRow(ctx, lookupKey, bigtable.RowFilter(filter))
	if err != nil {
		return nil, err
	}

	return &row, nil

}

func main() {
	ctx := context.Background()

	var BTClient Client
	if err := BTClient.Init(ctx); err != nil {
		log.Fatalf("error creating bigtable client: %w", err)
	}

	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	for i := 0; i < 100; i++ {
		ctx = context.Background()
		_, err := BTClient.GetRow(ctx, lookUpKey)
		if err != nil {
			log.Fatalf("error getting results: %w", err)
		}
		PrintMemUsage()
	}
	err := BTClient.Close()
	if err != nil {
		log.Fatalf("error closing bt client: %w", err)
	}
}

func PrintMemUsage() {
	var mem syscall.Rusage
	syscall.Getrusage(syscall.RUSAGE_SELF, &mem)

	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	fmt.Printf("\t HeapAlloc: %v MiB", bToMb(m.HeapAlloc))
	fmt.Printf("\t TotalAlloc: %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\t MaxRSS: %v  \n", mem.Maxrss)
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}
```

The results of this are the same:
```
$ go run main.go
	 HeapAlloc: 2 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20033536
	 HeapAlloc: 3 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20144128
	 HeapAlloc: 3 MiB	 TotalAlloc: 6 MiB	 MaxRSS: 20209664
...
	 HeapAlloc: 4 MiB	 TotalAlloc: 8 MiB	 MaxRSS: 21147648
	 HeapAlloc: 4 MiB	 TotalAlloc: 8 MiB	 MaxRSS: 21151744
	 HeapAlloc: 4 MiB	 TotalAlloc: 8 MiB	 MaxRSS: 21155840
```

**Comment by tbpg** [comment]
Thank you! We'll hopefully be able to look more into next week. Let us know if you figure out any possible causes.

**Comment by kolea2** [comment]
Hi @KristopherJordan, taking a look into this but had a quick question as well - in this line,
`tbl := c.BTClient.Open(c.TableID)`, is it possible to reuse `tbl` instead of getting a new one each time? Not sure if that would help or not, but trying to pinpoint any possible causes. Thanks!

**Comment by KristopherJordan** [comment]
Hi @kolea2. No, it's not possible to reuse that line in the production code.

**Comment by dsymonds** [comment]
`(*Client).Open` only makes a couple of allocations. It shouldn't pin any memory.

Have you tried grabbing a profile (heap/goroutine) to see the code path that gets to those extra allocations? The gRPC and protobuf libraries are used by lots of things, so maybe there's something else in your binary causing it.

**Comment by KristopherJordan** [comment]
@dsymonds , here is the memory profile (as a series of screenshots..) of `bigtable.ReadRow()` using [pprof](https://blog.golang.org/pprof).  It's a profile of the `unknown_inuse_space`.

![Screenshot 2020-11-24 at 15 22 37](https://user-images.githubusercontent.com/18208262/100106704-2ad55580-2e69-11eb-9f71-2a68fd2fd9c9.png)
![Screenshot 2020-11-24 at 15 22 51](https://user-images.githubusercontent.com/18208262/100106714-2dd04600-2e69-11eb-9416-1bf8fbc4bd11.png)
![Screenshot 2020-11-24 at 15 23 02](https://user-images.githubusercontent.com/18208262/100106718-3032a000-2e69-11eb-8a94-56d2e54ab646.png)
![Screenshot 2020-11-24 at 15 23 12](https://user-images.githubusercontent.com/18208262/100106724-3294fa00-2e69-11eb-9c7c-69ecaf89f349.png)
![Screenshot 2020-11-24 at 15 23 17](https://user-images.githubusercontent.com/18208262/100106733-34f75400-2e69-11eb-8756-aaa0b4548202.png)

**Comment by kolea2** [comment]
Hi @KristopherJordan, I tried running your most recent example in https://github.com/googleapis/google-cloud-go/issues/3235#issuecomment-731023450, but was unable to reproduce the issue. Increasing the iterations to 1000, I am seeing `heapAlloc`  go from 2 - 5, and then back down to 2. Is there anything else I should try out?

**Comment by ZackKorman** [comment]
@KristopherJordan and I work together. We have now added pprof to our production application, so when we experience this next we will be able to provide a stack trace (hopefully) of the issue as it appears in production.

**Comment by KristopherJordan** [comment]
With not having a good way of reproducing this issue, I'm closing it. We'll monitor our services and create a new issue if we find a better way to reproduce the issue. Thank's for all the input :)

**Comment by tritone** [comment]
Thanks for letting us know! Hopefully your production monitoring will give some insights.
