### ISSUE TITLE
storage: I want to use other http.Client at storage.Client.hc

### ISSUE THREAD

**Issue by kubosuke** [googleapis/google-cloud-go#3242]
**Is your feature request related to a problem? Please describe.**
my Service sets http.DefaultClient with Proxy Configuration.
when I use storage.NewClient and do request, it goes through proxy.
I want to access GCS API directly without via proxy.

**Describe the solution you'd like**
I'm glad if I could use storage.Client.SetHttpClient() to set storage.Client.hc by myself.

**Describe alternatives you've considered**
nothing.

**Additional context**
if you have other solution not to use http.DefaultClient, pls let me know.
thanks.

**Comment by tritone** [comment]
You can pass in the `WithHTTPClient` option when you create the storage client to achieve this https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient .

So then to create the client, you would use `storage.NewClient(ctx, option.WithHTTPClient(hc))`. I could provide a longer sample on how to include auth in this client, just let me know.
