### ISSUE TITLE
logging: bandwidth is limited to 10 Mbps

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [googleapis/google-cloud-go#3279]
**Client**

Logging v1.0.0
Pubsub v1.3.1

**Environment**

Any

**Go Environment**

go1.14.2 windows/amd64

**Description**

Hi there. I've found that logs publishing network bandwidth is limited to 10 Mbps. Sometimes my application has to push a significant amount of logs during a short period. It becomes a bottleneck, and the application always gets stuck with a memory leak that ends with a "logging client: bundler reached buffered byte limit" error inside the library.
I've researched that any Client could pass through it only 10 Mbps.
For the experiment, I created a simple program for spamming logs into Stackdriver. I did it with one logger instance in the first example, and I can only reach 10 Mbps. In the second case, I added a second separate logger instance and pushed logs to them both. In that case, I could get 20 Mbps. Is there any option to increase bandwidth for a single logger instance? 
I use zero longer as a logger wrapper, I don't think it could be related. Please share any thoughts.
Thank you!

**Code**
```go
package main

import (
	"context"
	"fmt"
	zlg "github.com/mark-ignacio/zerolog-gcp"
	"github.com/rs/zerolog"
	"cloud.google.com/go/logging"
	"io"
	_ "net/http/pprof"
	"time"
)

var log zerolog.Logger

func main() {
	log = logConfig()
	taskCount := 25
	for i := 0; i < taskCount; i++ {
		go func() {
			for {
				log.Info().Msgf("Lorem ipsum dolor sit amet, consectetur adipiscing elit,")
			}
		}()
	}
	fmt.Scanln()
}

func logConfig() zerolog.Logger {
	var writers []io.Writer
	gcpWriter, err := newCloudLoggingWriter(context.TODO(), "project-test", "project-test-foo", zlg.CloudLoggingOptions{})
	if err != nil {
		fmt.Print("could not create a CloudLoggingWriter")
	}
	writers = append(writers, gcpWriter)

	mw := io.MultiWriter(writers...)

	zerolog.SetGlobalLevel(zerolog.DebugLevel)
	iLogger := zerolog.New(mw).With().Timestamp().Logger()

	iLogger.Info().Msg("logging configured")
	return iLogger
}
....
func newCloudLoggingWriter(ctx context.Context, projectID, logID string, opts CloudLoggingOptions) (writer zerolog.LevelWriter, err error) {
	logger := opts.Logger
	if opts.Logger == nil {
		var client *logging.Client
		client, err = logging.NewClient(ctx, projectID)
		if err != nil {
			return
		}
		logger = client.Logger(logID, opts.LoggerOptions...)
		loggersWeMade = append(loggersWeMade, logger)
	}
	severityMap := opts.SeverityMap
	if severityMap == nil {
		severityMap = DefaultSeverityMap
	}
	writer = &cloudLoggingWriter{
		ctx:         ctx,
		logger:      logger,
		severityMap: severityMap,
	}
	return
}
.....
```
The second case with two loggers:

``` go
func main() {
	log1 = logConfig()
	log2 = logConfig()
	taskCount := 25
	for i := 0; i < taskCount; i++ {
		go func() {
			for {
				logNum := getRandomLogNumber()
				if logNum == 1 {
					log1.Info().Msgf("Lorem ipsum dolor sit amet, consectetur adipiscing elit,")
				} else {
					log2.Info().Msgf("Lorem ipsum dolor sit amet, consectetur adipiscing elit,")
				}
			}
		}()
	}
	fmt.Scanln()
}
```
**Screenshots**
First case:
![10mbps](https://user-images.githubusercontent.com/10336022/100249796-a4db0c80-2f45-11eb-8357-d532a88396f3.png)
Second case: 
![20mbps](https://user-images.githubusercontent.com/10336022/100249935-c89e5280-2f45-11eb-937f-aa698543bf1b.png)

**Comment by nicoleczhu** [comment]
You can play around with a few [LoggerOptions](https://pkg.go.dev/cloud.google.com/go/logging#LoggerOption), e.g. 
- increase [BufferedByteLimit](https://pkg.go.dev/cloud.google.com/go/logging#BufferedByteLimit). The default is 1GiB only
- increase [ConcurrentWriteLimit](https://pkg.go.dev/cloud.google.com/go/logging#ConcurrentWriteLimit)

If you still encounter low bandwidth, pls let me know. I'll reproduce your issue and see where the fix is.

**Comment by kirill-kostenetskyi** [comment]
@nicoleczhu thank you, ConcurrentWriteLimit works well for me. However, today max bandwidth for 1 thread is 7 Mbps. So summary for two is 14 Mbbs. Yesterday it was 20 Mbbs for two. I There is no clear statement of how much bandwidth for 1 connection it would be, isn't it? I measured out it a few times and had different results for 1 connection. Could you share any thoughts about that?

**Comment by nicoleczhu** [comment]
@kirill-kostenetskyi Re bandwidth variance: it could be that your other thresholds are getting maxed, e.g. how long your entries are pending, how many entries are pending, etc. I suggest playing around with the other thresholds like `DelayThreshold`, `EntryCountThreshold` to see if you get better throughput. Your logs may also warn you of which specific thresholds are getting maxed.

Help this helps. Again, if you do identify a specific issue at the client library level, happy to put in a fix for you.
