### ISSUE TITLE
storage: client Writer does not allow setting of CustomTime for lifecycle management

### ISSUE THREAD

**Issue by sholinaty** [googleapis/google-cloud-go#3280]
**Client**
Storage. 	"cloud.google.com/go/storage"

**Environment**
GCS

**Go Environment**

$ go version
go version go1.14.3 darwin/amd64

**Code**

```go
writer := client.Bucket(bucketName).Object(objectName).NewWriter(csm.ctx)
writer.ContentDisposition = NewContentDispositon
writer.Metadata = map[string]string{
		"Custom time":        time.Now().UTC().Format(time.RFC3339),
		"Custom Time":        time.Now().UTC().Format(time.RFC3339),
		"Custom-time":        time.Now().UTC().Format(time.RFC3339),
		"Custom-Time":        time.Now().UTC().Format(time.RFC3339),
		"x-goog-custom-time": time.Now().UTC().Format(time.RFC3339),
	}

}
```

**Expected behavior**
Writer.CustomTime should exist, or setting the Custom-Time metadata should set the Custom Time metadata on a GCS Storage Object so allow for lifecycle management to be defined during the file creation

**Actual behavior**

- there is no method to set the CustomTime on a GCS Writer, similar to how Content Disposition is set
- per https://cloud.google.com/storage/docs/xml-api/reference-headers#xgoogcustomtime, i should be able to set the x-goog-custom-time field in order to set CustomTime, but that simply adds additional metadata and does not modify the actual CustomTime field.
- there is not option within the GCS writer as defined above to write specific headers prior to an io.copy or a write.

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.
![Screen Shot 2020-11-25 at 10 33 08 AM](https://user-images.githubusercontent.com/66801165/100255800-9d960d80-2f09-11eb-984c-eefdf2d452b0.png)

**Comment by tritone** [comment]
This should be set using `Writer.ObjectAttrs`, which has a `CustomTime` field. See https://pkg.go.dev/cloud.google.com/go/storage#ObjectAttrs . Let me know if you run into problems setting it via this method.

**Comment by sholinaty** [comment]
Wow.   it seems that I had an outdated version of the "cloud.google.com/go/storage" package. 
running an update >go get "cloud.google.com/go/storage" and a Go Mod vendor has brought that writer.ObjectAttrs.CustomTime field.
I should note that it does take in a time.time and not an RFC3339 formatted time string (which the original docs i saw seemed to indicate)

Thanks!
