### ISSUE TITLE
firestore: Release of functionality added after 1.3.0

### ISSUE THREAD

**Issue by nenov92** [googleapis/google-cloud-go#3282]
We are using firestore golang client and we're looking for the release of the functionality that has been introduced with PR #2598 but it's still not part of an official release. Do you have plans to release it anytime soon?

Best regards,
Miroslav

**Comment by tritone** [comment]
Yes we'll cut a release soon, likely later this week. I'll update when it's completed.

**Comment by tritone** [comment]
Release was cut today. https://github.com/googleapis/google-cloud-go/releases/tag/firestore%2Fv1.4.0
