### ISSUE TITLE
storage: 503 Service Unavailable returned to user

### ISSUE THREAD

**Issue by koallen** [googleapis/google-cloud-go#3284]
**Client**

Storage

**Expected behavior**

Any 503 response are retried by the library.

**Actual behavior**

Occasionally getting 503 returned to my code on either `Write()` or `Close()` of an object `Writer`.

I've read both the doc and some of the code, based on my understanding, 503 should be considered transient and retried in the library instead of returned to the caller. This is especially important when uploading huge files (tens or hundreds of GB), we are leveraging resumable uploads after all.

**Comment by tritone** [comment]
We recently the resiliency to these errors in the Writer as of earlier this year. What version of the cloud.google.com/go/storage and google.golang.org/api are you using?

**Comment by tritone** [comment]
Closing due to lack of response, feel free to re-open if you have more information.
