### ISSUE TITLE
spannertest: Support AVG

### ISSUE THREAD

**Issue by sryoya** [googleapis/google-cloud-go#3285]
**Is your feature request related to a problem? Please describe.**
It's better if `spannertest` supports [`AVG`](https://cloud.google.com/spanner/docs/functions-and-operators#avg), one of the aggregated functions provided by Spanner. 

**Describe the solution you'd like**
I feel it's not so difficult because the processes should be similar with "SUM" and "COUNT", which are already supported.

**Comment by dsymonds** [comment]
Totally reasonable feature request. I'll take a look at your PR.
