### ISSUE TITLE
spanner: support big.Rat as NUMERIC in mutation

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-cloud-go#3327]
**Is your feature request related to a problem? Please describe.**

Query parameters accept `big.Rat` and their variants as `NUMERIC` typed value
but mutations doesn't accept `big.Rat` and their variants and emit an error.
```
spanner: code = "InvalidArgument", desc = "client doesn't support type *big.Rat"
```
This behavior is consistent with the documentation, but it seems strange that mutations only don't support it.
https://github.com/googleapis/google-cloud-go/blob/spanner/v1.12.0/spanner/mutation.go#L105-L121

**Describe the solution you'd like**

Mutations can support `NUMERIC` and `ARRAY<NUMERIC>` columns.
https://github.com/googleapis/google-cloud-go/blob/spanner/v1.12.0/spanner/value.go#L3061-L3071

**Describe alternatives you've considered**

Some mutations can be rewritten by DMLs with/without query parameters but they are not exactly same behavior.

**Comment by skuruppu** [comment]
Thanks for the report and for the fix. I will let @olavloite review it since he is more familiar with this code.

**Comment by skuruppu** [comment]
Thanks for your work @apstndb and @olavloite. I think this issue is now fixed so marking it as closed but please reopen if I missed something.
