### ISSUE TITLE
bigtable: Make user agent the same as library version

### ISSUE THREAD

**Issue by mohanli-ml** [googleapis/google-cloud-go#3330]
Currently the user agent of Bigtable in Go is standalone, as in https://github.com/googleapis/google-cloud-go/blob/master/bigtable/doc.go#L121m. Ideally, the user agent should be the same as the library release, which is v1.6.0 currently, see https://pkg.go.dev/cloud.google.com/go/bigtable.

**Comment by jimfulton** [comment]
The fix in #3429 has rotted.  IDK enough about the release process to know how to automate this and prevent rot, _however_

Why should the user agent and server versions be in sync?
