### ISSUE TITLE
bigtable: Simulate latency/errors in Bigtable emulator for performance / DiRT testing

### ISSUE THREAD

**Issue by AdamBSteele** [googleapis/google-cloud-go#3348]
**Is your feature request related to a problem? Please describe.**
I want to use the Cloud Bigtable emulator to test my application's behavior when my Bigtable instance is returning high latency or error rates.

**Describe the solution you'd like**
Add new settings to the Bigtable emulator for inject latency / errors into grpc calls.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by telpirion** [comment]
Performance tests will be addressed by the [Cloud Bigtable clients test](https://github.com/googleapis/cloud-bigtable-clients-test) project.

**Comment by bhshkh** [comment]
[Cloud Bigtable clients test](https://github.com/googleapis/cloud-bigtable-clients-test) project addressed conformance testing and not performance tests.
