### ISSUE TITLE
proposal: make google.golang.org/api/transport a real thing

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#336]
https://godoc.org/google.golang.org/api/transport

> Package transport supports network connections to HTTP and GRPC servers. This package is not intended for use by end developers. Use the google.golang.org/api/option package to configure API clients.

It's pretty useful for people who want to set up a gRPC connection. See [Speech API sample](https://github.com/GoogleCloudPlatform/golang-samples/blob/93b7807c3c000088026846eeebaaf7d7f258b1b0/speech/caption/caption.go#L35-L44).

I think the disclaimer is OK, but should we commit to keeping the API stable so that people who _do_ really want to use it still can without too much worry of it going away?

**Comment by okdave** [comment]
+1, particularly given the arrival of the generally-useful https://godoc.org/google.golang.org/api/transport/bytestream

**Comment by jba** [comment]
I'm okay with making transport stable.

But the Speech API sample should switch to using the generated client.

**Comment by rakyll** [comment]
@jba, see https://github.com/GoogleCloudPlatform/golang-samples/issues/93

+1 to the proposal.

**Comment by jba** [comment]
@broady @rakyll Do you still think this is a good idea? @zombiezen how about you? 

If so, would removing the dissuading sentence in the doc suffice?

**Comment by zombiezen** [comment]
I didn't realize that part of the API was declared unstable.  In that case... I'd really like to split it into a package for gRPC and HTTP separately, so that folks who aren't using gRPC (the rest of the googleapis library) don't pull it in.

**Comment by broady** [comment]
I think it's still a good idea. My only reservation is that people can't extend those options easily - and that's a very minor thing - they can just wrap them with their own option type.

**Comment by jba** [comment]
The [transport package](https://godoc.org/google.golang.org/api/transport) still says "This package is not intended for use by end developers." Now that we've split it, do we want to remove that sentence?

**Comment by zombiezen** [comment]
Can we remove the wrappers in `google.golang.org/api/transport` to gtransport and htransport?  If so, I think it's fine.

**Comment by jba** [comment]
@zombiezen So the only thing exported from `transport` will be `Creds`?

@pongad Can you change the generator to use `google.golang.org/api/transport/grpc`?

**Comment by zombiezen** [comment]
Yes.  This would address the concern of having a package that pulls in both sets of dependencies (HTTP and gRPC) when it doesn't necessarily need it.

**Comment by pongad** [comment]
Actually @andreamlin is the owner of Go GAPIC now.

Andrea, to make things concrete:
Change [this line](https://github.com/googleapis/toolkit/blob/258815faec9f3b71bc9fbede20ddf50acc630ba4/src/test/java/com/google/api/codegen/testdata/go/go_library.baseline#L153) to "google.golang.org/api/transport/grpc" and [this](https://github.com/googleapis/toolkit/blob/258815faec9f3b71bc9fbede20ddf50acc630ba4/src/test/java/com/google/api/codegen/testdata/go/go_library.baseline#L286) to "gtransport.Dial".

**Comment by jadekler** [comment]
Friendly ping - the work pongad@ mentioned appears to be done AFAICT. Can we promote the transport to stable?

**Comment by jba** [comment]
I haven't removed the transport package itself yet. I'll start work on that.

**Comment by jba** [comment]
@pongad, looks like you'll have to change the generator to replace the existing import with
```
import gtransport "google.golang.org/api/transport/grpc"
```

**Comment by jba** [comment]
@jadekler The cloud.google.com/go repo hasn't been updated yet.

**Comment by pongad** [comment]
@jadekler I can't remember if anything else needs to be done here :/

**Comment by broady** [comment]
re: the original request, we've got some thoughts on a separate auth library, which would likely include pretty much everything useful in the transport package for end-consumers.

We thought about promoting transport but we're going to punt on it in favor these (still nascent) plans.

Marking as closed (wontfix)
