### ISSUE TITLE
datastore: civil package types are loaded incorrectly when local machine timezone is not UTC

### ISSUE THREAD

**Issue by dnerdy** [googleapis/google-cloud-go#3360]
**Client**

Datastore

**Environment**

Any

**Go Environment**

$ go version
go version go1.14.12 darwin/amd64
$ go env
[I believe this is unrelated.]

**Code**

The pre-existing TestLoadToInterface test fails when run on a machine that has a timezone set to a non UTC timezone.

```
cd datastore
go test ./... -run TestLoadToInterface
```

Also, the `TestLoadToInterface/struct_with_civil.Date` would fail when run on a machine set to Pacific time if the test timestamp was 1605504600 (11/16/2020 @ 5:30am UTC) instead of 1605474000 (11/15/2020 @ 9:00pm UTC).

**Expected behavior**

I would expect the above tests to pass when run on a machine with any non-UTC timezone.

**Actual behavior**

```
--- FAIL: TestLoadToInterface (0.00s)
    --- FAIL: TestLoadToInterface/struct_with_civil.DateTime (0.00s)
        load_test.go:565: Mismatch: got - want +
              &struct{ DateTime civil.DateTime }{
              	DateTime: civil.DateTime{
              		Date: civil.Date{
              			Year:  2020,
              			Month: s"November",
            - 			Day:   15,
            + 			Day:   16,
              		},
              		Time: civil.Time{
            - 			Hour:       21,
            + 			Hour:       5,
              			Minute:     30,
              			Second:     0,
              			Nanosecond: 0,
              		},
              	},
              }
    --- FAIL: TestLoadToInterface/struct_with_civil.Time (0.00s)
        load_test.go:565: Mismatch: got - want +
              &struct{ Time civil.Time }{
              	Time: civil.Time{
            - 		Hour:       21,
            + 		Hour:       5,
              		Minute:     30,
              		Second:     0,
              		Nanosecond: 0,
              	},
              }
FAIL
FAIL	cloud.google.com/go/datastore	0.869s
ok  	cloud.google.com/go/datastore/admin/apiv1	0.559s [no tests to run]
?   	cloud.google.com/go/datastore/internal/gaepb	[no test files]
FAIL
```

(Also note the comment above about how `TestLoadToInterface/struct_with_civil.Date` also fails under some circumstances).

**Additional context**

I left a common on #3202 with information about how the loading can be corrected.

cc @codyoss

**Comment by codyoss** [comment]
Thanks!

**Comment by tritone** [comment]
@dnerdy let me know if this fix did the trick for you!

**Comment by dnerdy** [comment]
Looks good 👍
