### ISSUE TITLE
storage: add Projection to Query

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-go#3445]
GCS allows users to pass in a projection when listing objects: https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters

Currently we have this hardcoded as "full" which is not ideal for some use cases. https://github.com/googleapis/google-cloud-go/blob/2fa1b727f8a7b20aa62fe0990530744f6c109be0/storage/bucket.go#L1207

We should allow users to pass in the desired Projection via a [Query](https://github.com/googleapis/google-cloud-go/blob/2fa1b727f8a7b20aa62fe0990530744f6c109be0/storage/storage.go#L1310)

**Comment by ava12** [comment]
Is anyone working on this issue? I'd like to take it.

**Comment by tritone** [comment]
@ava12 feel free! Thanks!
