### ISSUE TITLE
all: only run tests on submodules changed by PR

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/google-cloud-go#3454]
At the moment, we have a `continuous` workflow that runs on merges and nightly, for all submodules (cmiiw). 

This is challenging for libraries that require long-running e2e tests as a part of CI, but do not want to increase run time for other teams. Ideally, we can have:
- `Nightly`: runs on all submodules, including long running tests
- `Continuous`: runs on affected submodules, including long running tests
- `Presubmit`: runs Short tests only (leave as is)

What are our general thoughts on a more delineated process like this? Will take a stab at a PR for this unless there's existing work or someone else really wants to

**Comment by tbpg** [comment]
Sounds great to me! The reason it hasn't been done in the past is there is a little more difficulty knowing what changes affect what packages in this repo. But, if we do it at the module level, as you suggested, I don't think that's a problem.

Here is how golang-samples does it: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/testing/kokoro/system_tests.sh. There may be a better way.
