### ISSUE TITLE
anthos: deploying aws management service on slow network

### ISSUE THREAD

**Issue by spkchels** [googleapis/google-cloud-go#3459]
**Client**

anthos-gke version
aws-1.5.1-gke.1

gcloud version
Google Cloud SDK 320.0.0
bq 2.0.64
core 2020.12.04
gsutil 4.55

**Environment**

System Version: macOS 10.15.7 (19H15)
Kernel Version: Darwin 19.6.0

**Go Environment**

go version go1.15.5 darwin/amd64

**Code**

```bash
$ anthos-gke aws management apply
creating S3 bucket: <>-bootstrap
Error: could not mirror gke-node-agent-aws: failed to upload file, MultipartUpload: upload multipart failed
    upload id: xLMSqHcO....--
caused by: ReadRequestBody: read multipart upload data failed
caused by: read tcp <localhost>:50038->142.250.66.208:443: read: connection reset by peer
```

**Expected behavior**

Management service gets deployed

**Actual behavior**

Errors out

**Additional context**

I am trying to deploy the service inside an existing VPC. This has worked in the past. But, started failing today. Same issue happens even if I let awsgke create a VPC and related components. This has not reached to the point where the contents of the anthos-gke.yaml matters. This errors before the tf files get created.

I can see that the gke-aws-node-agent is uploaded to s3. Looks like a timeout sorta issue.

After doing some experiments, the only thing that I could think of being as different is, I was on a slow network. I switched to a fast network and it started working. I will do further testing to confirm if the theory of fast network sticks. But, so far, that is the only symptom.

**Comment by codyoss** [comment]
Hey,

I might be missunderstanding what is going on here, but it does not seem like you are having an issue with the `cloud.google.com/go` libraries, but please correct me if I am wrong. If you are looking for the anthos support try [this link](https://cloud.google.com/anthos/docs/support/getting-support). Closing for now as I don't believe this is a client library issue.

**Comment by spkchels** [comment]
Sorry mate. My assumption was, it must be because of go version based on some cursory reading of similar issues elsewhere. Thank you for taking a look.
