### ISSUE TITLE
firestore: real-time updates via onSnapshot

### ISSUE THREAD

**Issue by nenov92** [googleapis/google-cloud-go#3467]
My team is migrating a service from NodeJS to GoLang. We are using Cloud Firestore on GCP and we need to get real-time updates whenever a document changes. In NodeJS and a few more languages, this functionality is available via the ```doc.onSnapshot``` listener. However, in GoLang the functionality is not available yet (reference: https://firebase.google.com/docs/firestore/query-data/listen#go). Therefore, I'd like to ask if there's a plan to release this functionality anytime soon?

**Comment by tbpg** [comment]
Here is the relevant method: https://pkg.go.dev/cloud.google.com/go/firestore#Query.Snapshots

Looks like we just don't have an example on that page yet. :sweat_smile:

**Comment by tbpg** [comment]
Here is an example of using it: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/firestore/firestore_snippets/listen_changes.go
