### ISSUE TITLE
logging: resource autodetection for CloudRun

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/google-cloud-go#3486]
`Logs` generated in CloudRun containers should have the following fields by default: 

```json
resource: {
type: "cloud_run_revision"
labels: {
revision_name: ...
configuration_name: ...
service_name: ...
location: e.g. "us-west1-1"
project_id: ...
}
}
```

**Comment by pontuspalmenas** [comment]
We experienced this issue a couple of weeks ago, and welcome the suggested solution in the PR. I have patched our source adding the `MonitoredResource` to the `Entry` with `detectGCRResource()` from the PR and verified that it works for us.
