### ISSUE TITLE
firestore: high latency for firestore reads/writes

### ISSUE THREAD

**Issue by killjee** [googleapis/google-cloud-go#3494]
I am developing a new application using golang and firestore. I am facing issues with latency when i try to make some read/write to fireStore. Sample code: 
`
func connectFirestore() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID :=<Project -ID>

	client, err := firestore.NewClient(ctx, projectID)
	if err != nil {
		log.Println("Failed to create client: " + err.Error())
	}
	defer client.Close()

	startTime := time.Now()
	iter := client.Collection("User").Documents(ctx)
	// defer iter.Stop()
	endTime := time.Now()
	log.Println("Latency of DB call ", endTime.Sub(startTime))
	doc, err := iter.GetAll()
	docLat := time.Now()
	log.Println("Doc Parse Latency ", docLat.Sub(endTime))
	log.Println("Got doc ", doc)

}`

This read request is taking approx 800ms to 1sec.

I tried a similar request from nodeJS and it gave me a latency of <10ms. NodeJS code snippet.
```
async function firebaseGetData() {
    const db = new Firestore({
        projectId: ,
        keyFilename: ,
    });
    firebaseGetData(db)
    var startTime = Date.now()
    const snapshot = await db.collection('User').where('phoneNumber', '==', '+919113348990').get();
    var startTime = Date.now()
    console.log("It came here")
    snapshot.forEach((doc) => {
        console.log(doc.id, '=>', doc.data());
        var endTime = Date.now()
        var latency = endTime - startTime
        console.log("Latency " + latency)
    });
}
```

**Comment by crwilcox** [comment]
As I recently did an evaluation of Java, Node, and Go latency, this is not reproducible. All versions are within 1-3ms of one another.

**Comment by crwilcox** [comment]
Also, in general, if you want to measure performance of our clients, I suggest making one call to the database before measuring as things may be evaluated on first request. This way you will see the cost of a single request and not capture client setup on one but not the other.
