### ISSUE TITLE
https://github.com/googleapis/google-cloud-go/blob/993bc6d69389a81fc259e0ce6f5d01cb37bd2899/container/apiv1/doc.go#L76

### ISSUE THREAD

**Issue by tomas1971** [googleapis/google-cloud-go#3495]
https://github.com/googleapis/google-cloud-go/blob/993bc6d69389a81fc259e0ce6f5d01cb37bd2899/container/apiv1/doc.go#L76

**Comment by codyoss** [comment]
Closing as I do not understand the intent of this issue.
