### ISSUE TITLE
iap: client for manipulating identity aware proxy service

### ISSUE THREAD

**Issue by 3cham** [googleapis/google-cloud-go#3499]
**Is your feature request related to a problem? Please describe.**
I try to create the OAuth consent screen & config its credentials with golang. Creating is fine but could be only done using the generated API calls from https://github.com/googleapis/google-api-go-client/tree/master/iap. Furthermore, setting the redirect URI is AFAIK currently done manually, e.g. https://cloud.google.com/iap/docs/enabling-kubernetes-howto#oauth-credentials. Is there anyway to set the redirect URI during creating the credentials since the URI format is pretty 1:1 mapped to the created client_id. I haven't found any module for iap in this project. Is this module not developed yet or intended to be done using above mentioned api calls?

**Describe the solution you'd like**
A module iap for create/list/delete/update the resources inside iap service.

**Describe alternatives you've considered**
Manually creating/editting them.

**Comment by codyoss** [comment]
Hey,

To answer your questions: 

> I haven't found any module for iap in this project. Is this module not developed yet or intended to be done using above mentioned api calls?

You are correct that there is not a client in this project. The client found here are generated from public protos found in googleapis/googleapis. The IAP team currently does not publish their protos there. If you would like to see this added I would recommend filling a feature request to the [IAP issue tracker](https://issuetracker.google.com/issues/new?component=190831&template=1009617).

> Is there anyway to set the redirect URI during creating the credentials since the URI format is pretty 1:1 mapped to the created client_id

Not to my knowledge, but I recommend reaching out through one of the options listed on the [IAP support page](https://cloud.google.com/iap/docs/getting-support).

**Comment by 3cham** [comment]
@codyoss Thank you for your reply. I really appreciate if you could provide more context about the difference between this and *googleapis/google-api-go-client* project? I guess, new features will be pushed in api project beforehand, correct?

**Comment by codyoss** [comment]
In general if an api client is present in this project, cloud.google.com/go, I would recommend using this one. The clients found here are *all gRPC based and a little more idiomatic to use in my opinion. Clients found in google.golang.org/api(google-api-go-client) are HTTP based clients that are generated from Google's public discovery document listing. Hope that helps you out!
