### ISSUE TITLE
spanner: source defaultClientOptions for grpc.Pool

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#3532]
Recently a new feature was rolled to use self-signed JWTs by default when using a service account with a client that has not been manually configured with options like scopes and endpoints. It was pointed out that spanner does not currently get this feature as it dials its own pool in the manual layer. There are two options I see as viable to get this functionality working.

1. Initialize the internal client options with [defaultClientOptions](https://github.com/googleapis/google-cloud-go/blob/6b432db005b77b22486fa5ab09f40a45d6499390/spanner/apiv1/spanner_client.go#L59). This way if more default options get rolled out in the future they will get auto-applied. Note if this option was chosen we would want to audit the grpcDialOptions in particualar to make sure we don't have a regression. It looks like a couple overlap in the generated client and manual layer.
2. Add two more options to the list of [allOpts](https://github.com/googleapis/google-cloud-go/blob/6b432db005b77b22486fa5ab09f40a45d6499390/spanner/client.go#L169). Notably replace option.WithScopes with internaloption.WithDefaultScopes and add `internaloption.WithDefaultAudience("https://spanner.googleapis.com/")`.

I am glad to contribute the required changes, but will defer to you on which approach makes the most sense for the client.

**Comment by skuruppu** [comment]
@olavloite would you be able to look at these options?

**Comment by olavloite** [comment]
@codyoss I would prefer it if could implement this by using the [defaultCallOptions](https://github.com/googleapis/google-cloud-go/blob/6b432db005b77b22486fa5ab09f40a45d6499390/spanner/apiv1/spanner_client.go#L59), as that would, as you also said, ensure that the client automatically receives any future default options. That would mean calling `NewClient` directly without first manually creating a pool.

The reason that we are manually creating a pool is that we use that to achieve session-channel affiliation (i.e. all RPCs that reference a specific session will always use the same channel). AFAICT it would be possible to achieve the same by creating a client directly, but _only_ by using the [Connection()](https://github.com/googleapis/google-cloud-go/blob/6b432db005b77b22486fa5ab09f40a45d6499390/spanner/apiv1/spanner_client.go#L282) function in spanner_client.go. That function is however deprecated. Is there any chance that that method could be un-deprecated? Or that a different method with that does the same (return the next `Connection` from the pool) could be added?

**Comment by codyoss** [comment]
> Is there any chance that that method could be un-deprecated?

I don't think so, it was deprecated with connections pooling for gRPC was introduced. The methods leaks detains that most(any?) users should not have to think about. That being said, it is not going away anytime soon as it would be a be a breaking change to due so across every single generated client.


> Or that a different method that does the same (return the next Connection from the pool) could be added?

No for the same reasons as above.

---

I admit I completely overlooked the fact that `defaultClientOptions` is private, so we would need to call NewClient. Two ways we could expose these options to the base spanner package:

1. We could create a wrapper function in spanner/apiv1 to export these options. This is simple, but we are adding surface to the API that provides value only for internal use.
2. We create an internal package that has a Exported []option.ClientOptions and a `Register` method. Then we could add a init function in spanner/apiv1 to capture the defaultClientOptions in the state of the internal package. This could then be extracted in the base spanner package. This is a little more complex and deals with some internal global state, but it has the added advantage of not exposing any extra surface to the client.

Maybe we should just manually add these extra options to the base spanner client for now to unblock the feature and iterate later with a more future proof design?

**Comment by olavloite** [comment]
Thanks for the detailed answer. It does make sense that it is deprecated.

> Maybe we should just manually add these extra options to the base spanner client for now to unblock the feature and iterate later with a more future proof design?

That sounds like a good option for now. My preference would be option 1, as it seems less complex for something that should ideally be a temporary solution. I'll look into that tomorrow.
