### ISSUE TITLE
logging: missing assignment in function "toHTTPRequest"

### ISSUE THREAD

**Issue by yanjusong** [googleapis/google-cloud-go#3588]
In this [file](https://github.com/googleapis/google-cloud-go/blob/master/logging/logadmin/logadmin.go#L164) of line 164, we can see the assignment of logging.HTTPRequest's field "RemoteIP", and maybe the field "LocalIP" should be assigned also?

here shows the fixed:
![image](https://user-images.githubusercontent.com/17964471/105351642-c85dc300-5c27-11eb-89c4-ca7579cacbd7.png)

**Comment by nicoleczhu** [comment]
Great suggestion @yanjusong . I created a PR with your suggestion & 2 additional fields. Do feel comfortable to directly submit the PR next time, we really welcome such contributions. Thanks again

**Comment by yanjusong** [comment]
> Great suggestion @yanjusong . I created a PR with your suggestion & 2 additional fields. Do feel comfortable to directly submit the PR next time, we really welcome such contributions. Thanks again

Thanks！
