### ISSUE TITLE
dlp: Support for text redact

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-go#3604]
**Is your feature request related to a problem? Please describe.**
Currently there is no method for redacting data from text. There is only support only for image redaction. 
https://github.com/googleapis/google-cloud-go/blob/master/dlp/apiv2/dlp_client.go#L43

**Describe the solution you'd like**
Support text redaction https://cloud.google.com/dlp/docs/redacting-sensitive-data

**Comment by codyoss** [comment]
This issue tracker is used for issues in the generated code. As this is a feature request for a backend service I would recommend reaching out via one of the methods listed on the [DLP Support Page](https://cloud.google.com/dlp/docs/support/getting-support). Thanks.

**Comment by tbpg** [comment]
Text redaction is supported. Perhaps the issue is missing a sample? You should be able to get it working based on this example: https://cloud.google.com/dlp/docs/deidentify-sensitive-data#dlp-deidentify-masking-go

**Comment by Mistic92** [comment]
Yep, I got confused by docs and I was thinking that I need text redact. It's working fine with deidentify.

**Comment by tbpg** [comment]
Great! I'm glad you got it working!
