### ISSUE TITLE
logging: add wrapper for tailing API

### ISSUE THREAD

**Issue by 0xSage** [googleapis/google-cloud-go#3635]
Tailing api [go protos](https://github.com/googleapis/go-genproto/blob/44e461bb6506e1f454f092a809a64f303b6c8e33/googleapis/logging/v2/logging.pb.go#L880) now exist and has been [gapic generated](https://github.com/googleapis/google-cloud-go/blob/b8ada6f197e680d0bb26aa031e6431bc099a3149/logging/apiv2/logging_client.go#L48). We need to write a more user friendly wrapper for it in logadmin and expose it in package documentation. 

TODO: 
- wrapper implementation(s)
- test(s)
- docs

**Comment by minherz** [comment]
We do not get requests for the wrapper. Please, see the way to tail log entries in Go in the [public documentation](https://cloud.google.com/logging/docs/view/streaming-live-tailing).
