### ISSUE TITLE
pubsub: consistent latency in message delivery in high throughput

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-go#3655]
**Client**

Pub/Sub

**Environment**

Ubuntu on GCE

**Go Environment**

go 1.15

**Expected behavior**

Messages get delivered without any latency

**Actual behavior**

Due to flow control, messages are not delivered in high volume periods. This is visible in 30 minute intervals, when stream teardowns occur. The latency is consistently 60s, which points to `StreamAckDeadlineSeconds` being a culprit. Messages eventually expire and are redelivered to a different stream, by which the message usually processes fine.

**Additional context**

Publishing about 8k messages/second can trigger this.

**Comment by codyoss** [comment]
It is possible that this is no longer an issue, should be re-tested.

**Comment by hongalex** [comment]
This issue was likely the result of having too many streams opened and Pub/Sub tearing down streams. This isn't specific to the Go client library, so closing.
