### ISSUE TITLE
bigquery: Support for Arrow

### ISSUE THREAD

**Issue by mrgleeco** [googleapis/google-cloud-go#3682]
A golang analog to the Java implementation as described at https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1

**Comment by shollyman** [comment]
I looked at this a while back, and at the time the arrow ipc package in go was a bit problematic to use.  It's worth a second look.

This issue also likely belongs in the golang-samples repo, as that's where we host the quickstarts and snippets.  I'll see about getting that moved over.

**Comment by shollyman** [comment]
github doesn't let me transfer this issue across the org boundary, so I've filed https://github.com/GoogleCloudPlatform/golang-samples/issues/1946 to track this.  Closing this issue out, please follow the other one for updates.

**Comment by mrgleeco** [comment]
Thank you! 💌
