### ISSUE TITLE
spanner: Scope constants removed

### ISSUE THREAD

**Issue by sinmetal** [googleapis/google-cloud-go#3683]
This PR has removed the Scope and AdminScope constants.

https://github.com/googleapis/google-cloud-go/commit/549c351222ee0369e47eacb4930aeac597a0d62f#diff-a7eef968d026e320839e33486c1ce4e449d69d9f6c86052edeae4528b60b5579L50-L57

These are constants that were exported, so they correspond to Breaking Change.
I was referencing this constant, so I got a compile error.

I think these constants should be reverted or listed in the Release Note as a Breaking Change.

**Additional context**

Started after upgrading to v1.14.0.

**Comment by codyoss** [comment]
@sinmetal Thanks for bringing this up. This was unintentionally removed. We will get a patch out shortly.

**Comment by codyoss** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/spanner%2Fv1.14.1
