### ISSUE TITLE
spannertest/spansql: Support "NOT IN" clause

### ISSUE THREAD

**Issue by sryoya** [googleapis/google-cloud-go#3715]
**Is your feature request related to a problem? Please describe.**
I noticed "NOT IN" is not supported, while simple "IN" is supported.
Actually I got the following error.

```
spanner: code = "InvalidArgument", desc = "bad query: got \"IN\", want LIKE or BETWEEN"
```

**Describe the solution you'd like**
- Cause
The function to parse Comparison Operators seems to try to parse "NOT IN" and treat it as unexpected tokens.

- Solution
Make this function to skip parsing when "NOT IN" is provided.

**Comment by dsymonds** [comment]
Thanks for filing this issue.

I don't think your solution is the right approach. It should be handled by `parseInOp`, and we shouldn't put special cases elsewhere to work around some over-eager parsing in the wrong place. Let me take a stab at a better fix.

**Comment by sryoya** [comment]
I see. I took a look at your solution and it looks better indeed. Thanks!
