### ISSUE TITLE
logging: race condition in error reporting

### ISSUE THREAD

**Issue by loburm** [googleapis/google-cloud-go#3720]
**Client**

Logging

**Environment**

GKE

**Go Environment**

$ go version
go version go1.14.15 linux/amd64

$ go env
>GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build912265370=/tmp/go-build -gno-record-gcc-switches"

**Code**

e.g.
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"time"

	gce "cloud.google.com/go/compute/metadata"
	"cloud.google.com/go/logging"
	"github.com/golang/glog"
	mrpb "google.golang.org/genproto/googleapis/api/monitoredres"
)

func main() {
	flag.Parse()
	projectID, err := gce.ProjectID()
	if err != nil {
		glog.Fatalf("Failed to fetch projectID: %v", err)
	}
	client, err := logging.NewClient(context.Background(), projectID)
	if err != nil {
		glog.Fatalf("Failed to created client: %v", err)
	}

	go func() {
		lgi := client.Logger("incorrect")
		for i:=0; i<100000; i++ {
			lgi.Log(logging.Entry{
				LogName:   "hello",
				Timestamp: time.Now(),
				Resource:  &mrpb.MonitoredResource{Type: "global"},
			})
			lgi.Flush()
		}
	}()
	for i:=0; i < 10; i++ {
		lgc := client.Logger("correct")
		go func(logger *logging.Logger, n int) {
			for i := 0; i < 1000; i++ {
				lgc.Log(logging.Entry{
					Payload:   fmt.Sprintf("Hello %v %v", n, i),
					Timestamp: time.Now(),
					Resource:  &mrpb.MonitoredResource{Type: "global"},
				})
				err := lgc.Flush()
				if err != nil {
					glog.Errorf("Unexpected error: %v", err)
				}
			}
		}(lgc, i)
	}
	time.Sleep(time.Hour)
}
```

**Expected behavior**

Log line "Unexpected error" shouldn't be printed. Here we are starting 11 goroutines, one of them producing incorrect logs that fail immediately all other 1- are sending single log line "Hello <routine_number> <seq_number>". After calling the Flush function I'm reading the error. In the second part of the code errors are unexpected (at least not the errors from the first goroutine).

**Actual behavior**

5 times out of 10000 we have got this error in our logs:
E0222 13:37:35.928153       1 main.go:48] Unexpected error: saw 1 errors; last: logging: Entry.LogName should be not be set when writing

Problem seems to be in the [Flush](https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L837) method. At the same time it seems to be working according to the documentation comment, but this is very strange design for a few reasons:

1. When you call Logger.Flush() you expect to see errors from this specific call only (and not from any other that is using the same client).
2. We can't reliably retry failed requests.
3. We can't reliably measure number of dropped log entries.

**Comment by minherz** [comment]
Looking into the [code of the logger](https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L739) it says that an error is returned "if any errors occurred since the last call to Flush from any Logger".
Indeed the behavior is confusing since it invites to think that the returning error is somehow relates to the Flush() method.
Since flushing of unsent logs happens synchronously, the modified Logger.Flush() method will not have return value.

**Comment by minherz** [comment]
@loburm Can you provide us a Dockerfile you used so we can safely reproduce the test environment?
