### ISSUE TITLE
monitoring/dashboard/apiv1: ListDashboards function hangs

### ISSUE THREAD

**Issue by swarren83** [googleapis/google-cloud-go#3721]
**Client**

golang

**Environment**

MacOS - Catalina 10.15.7

**Go Environment**

go version go1.14.3 darwin/amd64
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/-/Library/Caches/go-build"
GOENV="/Users/-/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/-/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ln/wfzn6vzn08ldq6303cfkmw8hfqjvym/T/go-build072705740=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
**Code**

```
//usr/bin/env go run $0 "$@"; exit
package main

import (
        "context"
        "fmt"
        "os"
        "io/ioutil"

        dashboard "cloud.google.com/go/monitoring/dashboard/apiv1"
        "google.golang.org/api/iterator"
        "google.golang.org/api/transport/grpc"
        "google.golang.org/api/option"
        dashboardpb "google.golang.org/genproto/googleapis/monitoring/dashboard/v1"
)

func main() {
        f, _ := ioutil.ReadFile(os.Args[1])

        ctx := context.Background()
        conn, _ := grpc.DialInsecure(ctx)
        c, err := dashboard.NewDashboardsClient(ctx, option.WithCredentialsJSON(f), option.WithGRPCConn(conn))
        if err != nil {
                fmt.Print(err)
        }

        req := &dashboardpb.ListDashboardsRequest{
                Parent: os.Args[2],
        }
        it := c.ListDashboards(ctx, req)
        for {
                resp, err := it.Next()
                if err == iterator.Done {
                        break
                }
                if err != nil {
                        fmt.Print(err)
                }

                fmt.Print(resp)
        }
}
```

**Expected behavior**

A list of GCP dashboard objects are returned.

**Actual behavior**

Hangs and returns no error.

**Screenshots**

n/a

**Additional context**

n/a

**Comment by codyoss** [comment]
Hey,

May I ask what your use case is for using `DialInsecure`? In general that is an option that can be used for test when running against fakes or mocks. Dialing in that way skips authentication so you won't be able to talk to the backend service. If you remove the DialInsecure line and remove passing the option I believe your code will start to work.

**Comment by swarren83** [comment]
Removing `DialInsecure` does work.  Let me go back to my production code and see if I can generate the error I was getting that led me to use this setting.

**Comment by swarren83** [comment]
The example code works, but my production code is returning nothing.  Do you know if an initialized client can be used, shared client, or does the client need to be built within the context of the function calling ListDashboards?

Right now I have:
```
func InitDashboardClient() *dashboard.DashboardsClient {
         ctx := context.Background()
         f, _ := ioutil.Readfile("/path/to/creds")
         c, _ := dashboard.NewDashboardsClient(ctx, option.WithCredentialsJSON(f))
         return c
}

func list(client *dashboard.DashboardsClient) []*dashboardpb.Dashboard {
	var dashboards []*dashboardpb.Dashboard
	ctx := context.Background()
	projectName := "my-project-id"
	req := &dashboardv1pb.ListDashboardsRequest{Parent: fmt.Sprintf("projects/%s", projectName)}
	it := client.ListDashboards(ctx, req)
	for {
		dashboard, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			utils.Log.Error(err)
		}
		dashboards = append(dashboards, dashboard)
	}

	return dashboards
}
```

**Comment by codyoss** [comment]
Hey,

>  does the client need to be built within the context of the function calling ListDashboards?

You can, and should, share the client. It is goroutine(thread) safe.

> my production code is returning nothing

So you are not getting an error? In that case that means the API is not returning any dashboards.


Hope that helps.

**Comment by swarren83** [comment]
Correct, no error is returned.  In fact, not even debug statements inside of the `for` loop are returning.  I would expect if I added `fmt.Printf("dashboard: %v", dashboard)` after `it.Next()` that it would print "dashboard: ".  However, it seems that it doesn't even execute the Printf.

```
	for {
		dashboard, err := it.Next()
		fmt.Printf("dashboard.list dashboard.DisplayName: %s", dashboard.DisplayName)
		fmt.Printf("dashboard.list err: %v", err)
		if err == iterator.Done {
			fmt.Printf("dashboard.list breaking out of for loop...")
			fmt.Printf("dashboard.list dashboard: %v", dashboard.DisplayName)
			break
		}
		if err != nil {
			fmt.Print(err)
		}
		dashboards = append(dashboards, dashboard)
	}
	fmt.Printf("dashboard.list dashboards: %v", dashboards)
```

None of these print statements show up in stdout.

**Comment by swarren83** [comment]
@codyoss The following error is why I was using `DialInsecure`:

```
{"level":"error","msg":"rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\"","time":"2021-02-22T19:47:01Z"}
```

I am running this code inside of a container on k8s(version: 1.16.11).  How do I disable this error without using `DialInsecure`?

**Comment by codyoss** [comment]
Are you using alpine? If so try to add: `RUN apk add --no-cache ca-certificates`.

**Comment by swarren83** [comment]
Thank you for the suggestion but even with `ca-certificates` installed I still get the error.  I have another change that might work.
