### ISSUE TITLE
pubsublite: TopicConfigToUpdate should include ranges

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-go#3766]
[`TopicConfig`](https://pkg.go.dev/cloud.google.com/go/pubsublite#TopicConfig) specifies ranges for the various values (e.g. `PublishCapacityMiBPerSec` must be in the range 4-16). It would be useful for `TopicConfigToUpdate` to also have these comments for its fields for easier reference in IDEs and in [docs](https://pkg.go.dev/cloud.google.com/go/pubsublite#TopicConfigToUpdate).

**Comment by tmdiep** [comment]
Good point, will add these comments.

**Comment by hongalex** [comment]
In addition, in one of the [examples](https://pkg.go.dev/cloud.google.com/go/pubsublite#example-AdminClient.CreateTopic), `PerPartitionBytes` must be between 30 GiB and 10 TiB, but this isn't documented anywhere. We should update the comments in the library if this is still true.
