### ISSUE TITLE
workflow: add execution start

### ISSUE THREAD

**Issue by Mistic92** [googleapis/google-cloud-go#3782]
**Is your feature request related to a problem? Please describe.**
I'm trying to use GCP Workflow but in go library I don't see any way to trigger execution. This is available for Node.js 

**Describe the solution you'd like**
Option to trigger execution

**Additional context**
There is an example in node.js how to trigger execution of workflow
https://cloud.google.com/workflows/docs/quickstart-client-libraries

**Comment by Mistic92** [comment]
Oops, I see that there is package for [execution](https://pkg.go.dev/cloud.google.com/go@v0.78.0/workflows/executions/apiv1beta). But GCP support page link only to main one

https://cloud.google.com/workflows/docs/apis section client libraries. 

Maybe gcp page should be improved?

**Comment by codyoss** [comment]
Sounds like you found your solution. If one of the cloud.google.com pages is out of date you think please click the 'Send Feedback' button on that page so someone can look into it. Thanks!
