### ISSUE TITLE
bigquery: add 500 internal error in the retry strategy as an option

### ISSUE THREAD

**Issue by zhongshixi-blockthrough** [googleapis/google-cloud-go#3792]
**Is your feature request related to a problem? Please describe.**
I have seen 500 error ( googleapi: Error 500: An internal error occurred and the request could not be completed., internalError ) several times  which is handled by the retry strategy in bigquery v1.16.0.  Since the retry strategy follows  the definition in bigquery SLA. I would like to know why 500 internal error is not considered as error could be retried.

```
"Back-off Requirements" means, when an error occurs, the Customer Application is responsible for waiting for a period of time before issuing another request. This means that after the first error, there is a minimum back-off interval of 1 second and for each consecutive error, the back-off interval increases exponentially up to 32 seconds.
```

**Describe the solution you'd like**
Add 500 internal error as an optional error where the retry strategy could be applied since the existing retry strategy is pretty good.

**Comment by shollyman** [comment]
Thanks for reaching out.  I was able to take a look at this.  From the limited information, it looks like this error falls into the category of `INTERNAL` errors, and per https://google.aip.dev/194#generally-non-retryable-codes shouldn't be retried in the client layer itself.

It may be reasonable to retry these at your application level in the short term.  However, I'd encourage you to also file an issue [through a support channel or via the public issue tracker](https://cloud.google.com/bigquery/docs/getting-support) to get this addressed in the service itself.  They'll likely need more detailed information to make headway on identifying what's triggering the internal error (specific jobs, calls, projects, etc).

I'm going to close this issue at this time, but feel free to followup if you think I've mischaracterized the nature of the error behavior this or there's more information I may have overlooked.
