### ISSUE TITLE
logging: default bundler limits doesn't match official API

### ISSUE THREAD

**Issue by loburm** [googleapis/google-cloud-go#3823]
**Client**

Logging

**Code**

That's a limit that we see inside of package:
```go
	// DefaultEntryCountThreshold is the default value for the EntryCountThreshold LoggerOption.
	DefaultEntryCountThreshold = 1000

	// DefaultEntryByteThreshold is the default value for the EntryByteThreshold LoggerOption.
	DefaultEntryByteThreshold = 1 << 20 // 1MiB

	// DefaultBufferedByteLimit is the default value for the BufferedByteLimit LoggerOption.
	DefaultBufferedByteLimit = 1 << 30 // 1GiB
```

I'm not 100% sure what is the difference between DefaultEntryByteThreshold and DefaultBufferedByteLimit, but official [API](https://cloud.google.com/logging/quotas) has a different limits:

> Size of a log entry 256 KB
> Size of an entries.write request 10 MB

**Comment by nicoleczhu** [comment]
good pt, i think we are just using bundler defaults [see here](https://github.com/googleapis/google-api-go-client/blob/e00d87e52f2e2d0189045089be07de3dc043b865/support/bundler/bundler.go#L26)

ill get in a pr to raise these defaults to something that makes more sense given actual api limits
