### ISSUE TITLE
dose google-cloud-go has container registry SDK?

### ISSUE THREAD

**Issue by wzf1943** [googleapis/google-cloud-go#3833]
**Is your feature request related to a problem? Please describe.**
I'm trying to fetch container info from container registry by using programming way. But I don't find out any SDK related package about this part 

**Describe the solution you'd like**
Like storage SKD that I can use program way to fetch info

**Describe alternatives you've considered**
I can only use "gcloud container images list-tags" command to fetch info that I'm interested in.

**Additional context**

**Comment by codyoss** [comment]
We currently do not offer a client for working with this service. Although gcr.io it is [compliant with the Docker Registry api](https://cloud.google.com/container-registry/docs/reference/docker-api). This mean you could make requests with an authenticated client. You can create one of those with [NewClient](https://pkg.go.dev/google.golang.org/api/transport/http#NewClient).

There is a beta client for artifact registry is you are using that product: [cloud.google.com/go/artifactregistry/apiv1beta2](https://pkg.go.dev/cloud.google.com/go@v0.79.0/artifactregistry/apiv1beta2)

**Comment by cagataygurturk** [comment]
I would like this to be reopened if possible. As the author states, there are couple of more commands like list-tags, tag etc. that the Docker registry API is not entirely usable for.

**Comment by codyoss** [comment]
I believe artifact registry supports these types of features you are looking for : https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories.packages.tags
