### ISSUE TITLE
firestore: Realtime 

### ISSUE THREAD

**Issue by undeadindustries** [googleapis/google-cloud-go#3865]
**Client**

Comute Engine VM

**Environment**

Ubuntu 20.04, latest updates. AMD ROME, 4GB, 20GB SSD.

**Go Environment**

go1.14.7 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rob_shelby/.cache/go-build"
GOENV="/home/rob_shelby/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rob_shelby/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build182990027=/tmp/go-build -gno-record-gcc-switches"

**Code**
//CHANGES.MD says it's 1.5.0...
//Code edited to anonymize a bit. Any errors are because of that.
```
func PeopleSnapShots() {
	ctx := context.Background()
	iter := peopledb.Where("connected", "==", 1).Where("status", "==", 1).OrderBy("name", firestore.Asc).Snapshots(ctx)
	defer iter.Stop()
	for {
		next, err := iter.Next()
		//Empty the syncMap
		syncPeople.Range(func(key interface{}, value interface{}) bool {
			syncPeople.Delete(key)
			return true
		})
		if err == iterator.Done {
			//This literally has never happened. So no bug here.
			log.Printf("people Iterator.Done. This should never happen.")
			go PeopleSnapShots()
			return
		}
		if err != nil {
			//Never received a bug here either.
			log.Printf("SNAPS ERROR: %v", err)
			go PeopleSnapShots()
			return
		}
		doc := next.Documents
		for {
			docIter, err := doc.Next()
			if err == iterator.Done {
				break
			}
			if err != nil {
				//Never received this error either.
				log.Printf("NESTED SNAPS ERROR: %v", err)
				go PeopleSnapShots()
				return
			}
			t := docIter.Data()
			//include the sockets as well.
			temp := []string{}
	
			clients.Range(func(key interface{}, value interface{}) bool {
				if value.(*socket).email == t["email"] {
					temp = append(temp, key.(string))
				}
				return true
			})
			t["sockets"] = temp
			syncPeople.Store(t["email"], t)

		}

		//Sends parts of syncPeople to the correct websockets.
		sendOnlinePeopleToUsers()

	}
}
```

**Expected behavior**

App should run "forever" and anytime an update happens to the Firestore document, the snapshot updates and should spin through the iterator. 

Starts working after app is stopped and started again.

**Actual behavior**

This works for a while. An hour? Two days? A week? It's different every time. Then it stops working. I can even watch a document update, and the snapshot doesn't do anything. It's a simple app. I scoured it for data races or anything else that might cause weird behavior.

**Additional context**

I've read an old bug that this exact behavior was happening in Python and it got fixed.

**Comment by undeadindustries** [comment]
UPDATE: 
I created minimum  code that just logs when a doc change is detected. I can simply (manually) change the doc over and over. Within a few seconds, it breaks. No error or anything. It just stops detecting changes.

**Comment by undeadindustries** [comment]
With a bit more error handling, I got more detail on this.

Whenever a person logs in, there's another go function that sends the new list of online users to each socket.

That function, eventually will return this error:
`rpc error: code = DeadlineExceeded desc = context deadline exceeded`

Once I get that error, all snapshots seem to stop. Does that error cause a *firestore.CollectionRef to need to be recreated or something?

Since it is just me testing this, I recreate the error by constantly refreshing my browser, causing new websockets to be created and the go function to "quickly" mark me as offline then online and sending the list of users (me) to the other sockets (no one right now). It only takes about 2 minutes of refreshing to do this.

Server resources are never spiked. So it's not go functions consuming a bunch of memory or anything.

I hope that helps?

**Comment by crwilcox** [comment]
I think the code included here may not be enough to go on. I suspect from what you have stated though, the area writing documents stops doing so after deadline exceeded. 

Do you have a trace to share perhaps?

**Comment by undeadindustries** [comment]
Hi there, I'm sorry I don't right now. This might be a noob question, but what would the correct reaction be when catching a deadline exceeded error be to keep the app working correctly?
Thanks!

**Comment by crwilcox** [comment]
I am going to close as no-repro.

As for the "what to do with deadline exceeded" it sort of depends on what you are trying to do. I would consider retrying another time, possibly with a backoff. It is also possible the code can be altered to stream the information more quickly to a local store. My guess is that the iteration over the retrieved data is taking a longer than expected time and is not finished at the point the connection to firestore expires. If you end up with a reproducible code sample we can take a look at that point :)
