### ISSUE TITLE
storage: How to use custom domain but with pathstyle in URL signer options?

### ISSUE THREAD

**Issue by challarao** [googleapis/google-cloud-go#3866]
In URLStyle(for signing options), there are three styles implemented currently bucketBoundHostname, pathStyle, virtualHostedStyle. I need to use custom domain but with path style bucket convention. 

I tried to implement URLStyle interface, but its methods are private.

My assumption is that signed urls work no matter what the hostname is as long as the signing is done with the same host name. So it should be fundamentally legal. 

How to achieve this using go SDK?

Example:
https://customdomain.com/bucket/key?signature....&other params

**Comment by tritone** [comment]
I looked into this and I think you're correct that this use case is supported in the GCS API; however it's not currently supported by the Go SDK. I'm following up internally to see if there's a reason why we decided not to support this while building this feature.

Can you speak a little more to your use case here? I think our assumption was that most users would use bucketBoundHostname for [CNAMEs](https://cloud.google.com/storage/docs/request-endpoints#cname) (or other hosts that would map to a single bucket).

**Comment by tritone** [comment]
Since this is not currently supported in the library, I'm going to leave this open but change it to a feature request.

**Comment by challarao** [comment]
@tritone Sorry for a very late reply. But if I recall correctly, we had constraints around using bucket names as sub domains. It's a big project and we primarily use sub domains for differentiating between customers/deployments. I think wild cards were a bit of a problem.

**Comment by BrennaEpp** [comment]
Thanks for filing this issue! This was done in #8113. It should be in the next release: storage 1.31.0

With this release, you should be able to set `Hostname` on `SignedURLOptions` to obtain a URL using a custom domain with path style convention. Note that you don't have to do this step (ie. set `Hostname`) if you initialized the storage Client with `option.WithEndpoint("custom-domain")`.
