### ISSUE TITLE
bigquery: use jobs.query instead of jobs.insert to fix slow latency

### ISSUE THREAD

**Issue by derekperkins** [googleapis/google-cloud-go#3872]
**Is your feature request related to a problem? Please describe.**
Query latency is longer than it needs to be because it is using [jobs.insert](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert) instead of [jobs.query](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query).

**Describe the solution you'd like**
[Query.Read](https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Read) should use the query endpoint, rather than just being a convenience wrapper around jobs.insert and then polling.

**Describe alternatives you've considered**
Using the REST api directly.

**Additional context**
I'm using BI Engine, and it took 3x longer to retrieve results than it took for the query to run.

<img width="915" alt="Screen Shot 2021-03-29 at 1 34 28 PM" src="https://user-images.githubusercontent.com/3588778/112936017-361fe280-90e2-11eb-88c7-dcc75d2bee3d.png">

This was the response I got from the BI Engine team in [Google Groups](https://groups.google.com/g/bigquery-biengine-sql-preview-users/c/6lwtrL8nzv0) after investigating the query latency.

> Query took 6 seconds, from what I see I think primary reason is you see 12 primarily because you use you are using jobs.insert API. E.g. you inserted the job at 19:30:08 UTC, it was ready at 19:30:14, but your client was polling once in a while to see if job is complete. E.g. there is a lot of polling and waiting. For interactive queries using BI Engine we recommend using synchronous jobs.query.

**Comment by shollyman** [comment]
The [Query.Read](https://pkg.go.dev/cloud.google.com/go/bigquery#Query.Read) comment mentions that it supports the faster query path, though it's not super explicit about the implementation details.

It may be that the nature of your query config is not compatible with the faster path (the options you can pass to the underlying jobs.insert differ from what you can pass into the underlying jobs.query.  In cases where the config is incompatible, a `Query.Read()` will fallback to jobs.insert.

The logic we use for compatibility checking is here: https://github.com/googleapis/google-cloud-go/blob/7aeee23ec94418a1ea2a1c4455285e001fe61289/bigquery/query.go#L379

Happy to look at this more, but I'll need additional details (repro code, etc) to look further.

**Comment by derekperkins** [comment]
That's very helpful, I was setting a job id which fails on the `probeFastPath` check. Would you be opposed to adding `TimeoutMs` and `RequestId` to the `QueryConfig` struct? I definitely have queries that'll run longer than 10s, and it would be nice to be able to use the request id for idempotency. The random id it sets now seems unnecessary.

**Comment by shollyman** [comment]
I think exposing `RequestId` is more straightforward, but `TimeoutMs` has multiple connotations.  Could you confirm what behavior you'd want this to control?

**Comment by derekperkins** [comment]
> timeoutMs: Specifies the maximum amount of time, in milliseconds, that the client is willing to wait for the query to complete. By default, this limit is 10 seconds (10,000 milliseconds). If the query is complete, the jobComplete field in the response is true. If the query has not yet completed, jobComplete is false.
>
> You can request a longer timeout period in the timeoutMs field. However, the call is not guaranteed to wait for the specified timeout; it typically returns after around 200 seconds (200,000 milliseconds), even if the query is not complete.
>
> If jobComplete is false, you can continue to wait for the query to complete by calling the getQueryResults method until the jobComplete field in the getQueryResults response is true.

Just a passthrough setting for jobs.query. There's definitely some naming overlap in Go with context timeouts, but I wouldn't want/expect that to intersect with `timoutMs`. You're already handling the case when it times out, so this shouldn't require extra functionality.

**Comment by alvarowolfx** [comment]
`jobs.query` endpoint is already integrated into `Query.read` flow.
