### ISSUE TITLE
aiplatform: API client for Unified AI Platform

### ISSUE THREAD

**Issue by mugglmenzel** [googleapis/google-cloud-go#3961]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A convenient API client in Golang similar to the python and nodejs versions available:
What about a golang library for the new unified Cloud AI Platform (c.f. https://cloud.google.com/ai-platform-unified/docs/start/client-libraries)?

**Describe alternatives you've considered**
RPCs to Python or Javascript/Node code.

**Additional context**
There are golang libraries for many other AI cloud services, yet (Unified) AI Platform is not covered (c.f. https://pkg.go.dev/cloud.google.com/go#readme-supported-apis). A more critical example: AutoML has become part of AI Platform now and at some point this library only supports the legacy version if it does not add AI Platform.

**Comment by codyoss** [comment]
This is currently blocked and is already being tracked internally. See 178408983
