### ISSUE TITLE
storage: retry is not consistent between `storage.Reader` and `storage.Writer`

### ISSUE THREAD

**Issue by maros7** [googleapis/google-cloud-go#3963]
**Client**

Storage

**Environment**

MacOSX/Linux

```bash
$ go version; go env                                                                                                                                                                       ✔  18:06:46 
go version go1.16.3 darwin/amd64
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XXX/Library/Caches/go-build"
GOENV="/Users/XXX/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/XXX/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="XXX"
GOOS="darwin"
GOPATH="/Users/XXX/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/XXX/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/03/XXX/=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

Regarding this code:
https://github.com/googleapis/google-cloud-go/blob/34bbe35bbc31c3d337cacff86a3372bcae1f1f06/storage/not_go110.go#L26-L42

The `http.Client` is wrapping an error in `url.Error`:
https://github.com/golang/go/blob/9baddd3f21230c55f0ad2a10f5f20579dcf0a0bb/src/net/http/client.go#L717-L728

Meaning that errors that implement `interface{ Temporary() bool }` will not be retried by the code above in the `storage.Reader`. It is handled differently in the `google-go-api-client` library (used by `storage.Writer`). See:
https://github.com/googleapis/google-api-go-client/blob/e8cf7f70a1e0160405dd0f789a006e6b6074fbdb/internal/gensupport/resumable.go#L233-L258

**Expected behavior**

`http.tlsHandshakeTimeoutError` (and other errors implementing `interface{ Temporary() bool }`) should be retried when using `storage.Reader` (like with `storage.Writer`) when wrapped in e.g. `url.Error`.

**Actual behavior**

`http.tlsHandshakeTimeoutError` (and other errors implementing `interface{ Temporary() bool }`) is not retried since it is wrapped in an `url.Error` when using `storage.Reader` (like with `storage.Writer`).

**Comment by frankyn** [comment]
Thanks for filing this issue and your patience @maros7. I'll follow-up with a change to align the retry strategy between Reader and Writer.

**Comment by maros7** [comment]
@frankyn Thanks! We actually have a similar issue with the BigQuery client. Its "should this error be retried" function doesn't seem to handle low-level errors at all. But I can raise another issue for that.

https://github.com/googleapis/google-cloud-go/blob/bc0549d588ee26b6eb3774625f04d601b64a330a/bigquery/bigquery.go#L168-L189

**Comment by frankyn** [comment]
Thanks for the feedback and for filing a separate issue @maros7, the BigQuery team will be best suited to help address this issue. I'm working on addressing the inconsistency in Storage with @tritone.
