### ISSUE TITLE
firestore: timestamp cannot be written using struct

### ISSUE THREAD

**Issue by forest5013** [googleapis/google-cloud-go#4009]
**Client**

firestore

**Environment**

local with firestore emulator 

**Go Environment**

$ go version
go version go1.16.3 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/current"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/current/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build487440110=/tmp/go-build -gno-record-gcc-switches"

**Code**

```go
package main

type User struct {
	ID       string
	regTime  time.Time
	Email    string
	Username string
	Password string
	NickName string
	Sex      string
	Age      string
	Address  string
	Role     string
}

func main() {
	// Get firestore client

	//breakpoint 1
	ref := client.Collection("userInfo").NewDoc()
	b.ID = ref.ID
	b.Username = "test_user"
        b.Password = "test_pw"
	b.regTime = time.Now()

	err = um.UpdateUserRole(ctx, b.ID, "1")
	if err != nil {
		return "", fmt.Errorf("UserRegister error: creat error %v", err)
	}

	if _, err := ref.Create(ctx, b); err != nil {
		return "", fmt.Errorf("UserRegister error: creat error %v", err)
	}

        // breakpoint 2
	_, _ = um.client.Collection("userInfo").Doc(b.ID).Set(ctx, User{
		regTime: time.Now(),
	})

        // breakpoint 3
	_, _ = um.client.Collection("userInfo").Doc(b.ID).Set(ctx, map[string]interface{}{
		"regTime": time.Now(),
		"time":    time.Now(),
	})
}
```

**Expected behavior**

I am trying to write a timestamp to firestore. I checked the example in https://pkg.go.dev/cloud.google.com/go/firestore@v1.5.0#DocumentRef.Create. But it seems the struct way cannot write the timestamp into the firestore.

**Actual behavior**

The timestamp is not written into the database using struct method.

**Screenshots**

After breakpoint 1 is released, every field except regTime are written into the database
![bp1](https://user-images.githubusercontent.com/17601717/116001548-ccdca380-a5a9-11eb-9971-0f797fd76e82.png)
After breakpoint 2 is released, every field is erased as I used set set to store the timestamp
![bp2](https://user-images.githubusercontent.com/17601717/116001589-fb5a7e80-a5a9-11eb-8dfa-88fa45b7a98a.png)
After breakpoint 3 is released, timestamp is written successfully using the map method
![bp3](https://user-images.githubusercontent.com/17601717/116001689-8cc9f080-a5aa-11eb-9049-5b7abafed408.png)

**Additional context**

This can be reproduced every time.

**Comment by crwilcox** [comment]
Hi @forest5013 

We have an integratin test, `TestIntegration_ServerTimestamp` that does this action and verifies the data is written.

https://github.com/googleapis/google-cloud-go/blob/master/firestore/integration_test.go#L517

I have verified there aren't any issues with time.

However, when using a struct, only exported fields are set in firestore. This is stated in the documenation at https://pkg.go.dev/cloud.google.com/go/firestore@v1.5.0#DocumentRef.Create as you referenced in your issue.

![image](https://user-images.githubusercontent.com/638797/116619504-60d5a480-a8f5-11eb-8c9d-90c08c85e809.png)
