### ISSUE TITLE
PubSub: streaming pull operation slows down and resumes on a regular basis

### ISSUE THREAD

**Issue by kaipohu** [googleapis/google-cloud-go#4020]
I am running my code on GKE. I had 6 pods to handle this subscription and everything was fine till a week ago. (by Fine, it means 0 unacked message in general)

Then my team noticed a visible delay of pubsub handling. I firstly thought it was due to a big traffic so I put on 4 more pods but it is not working. Pulling messages doesn't stop. It just slows down and resumes. 

![Screen Shot 2021-04-29 at 3 58 35 PM](https://user-images.githubusercontent.com/22805556/116519590-3dfebc80-a904-11eb-898a-b25aa60efbfe.png)

[Editing Details in progress]

**Comment by mrmiroslav** [comment]
What was the resolution? We are experiencing the same issue?

**Comment by mrmiroslav** [comment]
It seems like pushing messages to a topic with `topic.PublishSettings.CountThreshold` affects how messages are pulled. If we run a test with threshold=1 vs theshold=1000, subscription receive has a very different throughput.
