### ISSUE TITLE
monitoring/apiv3/v2: expose TimeSeriesDescriptor

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-cloud-go#4030]
**Is your feature request related to a problem? Please describe.**

I want to write Cloud Monitoring MQL client tool using this client library but 
* [TimeSeriesDataIterator](https://pkg.go.dev/cloud.google.com/go/monitoring/apiv3/v2#TimeSeriesDataIterator) doesn't return label values and point data with name.
  * It doesn't expose descriptors like `LabelDescriptors` and `PointDescriptors` in [TimeSeriesDescriptor](https://pkg.go.dev/google.golang.org/api/monitoring/v3#TimeSeriesDescriptor).
  * Should use [`TimeSeriesDataIterator.Resource`](https://pkg.go.dev/cloud.google.com/go/monitoring/apiv3/v2#TimeSeriesDataIterator)?

**Describe the solution you'd like**

Expose `TimeSeriesDescriptor` from `TimeSeriesDataIterator`.

**Comment by codyoss** [comment]
Hey,

It sounds like you want to get at the raw response:

```go
var resp *monitoringpb.QueryTimeSeriesResponse
resp := iterator.Response(*monitoringpb.QueryTimeSeriesResponse)
fmt.Println(resp. TimeSeriesDescriptor)
```

Hope that helps.
