### ISSUE TITLE
spanner/spansql: Make spansql case-insensitive

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-go#4032]
spansql is currently case sensitive and expects all keywords and function names to be written in upper case. Although it is documented as a TODO, it sometimes causes unexpected errors as Cloud Spanner itself is not case sensitive for keywords and function names. It would therefore be beneficial to make the parsing of all keywords in spansql case insensitive.

Surprises can for example pop up when a user gets the current DDL of a database by calling https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.admin.database.v1#google.spanner.admin.database.v1.DatabaseAdmin.GetDatabaseDdl. This can return keywords and/or function names in lower case if a computed column has an expression that contains lower case keywords.

**Comment by dsymonds** [comment]
Yep. I had some ideas on how to implement this. The central idea is for the lexer to have a distinguished type (like it does for strings and int64s, etc.) for keywords, so it is picked up then. The parser helper funcs (expect, sniff, etc.) would restrict to looking for tokens of that type and also do the case insensitive matching. Other specific parts that need careful handling of case sensitivity can do their own specific matching (e.g. table names, or whatever).

I can probably start tackling this soon, unless @hengfengli is really super keen to do it himself.

**Comment by hengfengli** [comment]
@dsymonds Please feel free to go ahead.
