### ISSUE TITLE
bigquery: Grpc storage api

### ISSUE THREAD

**Issue by gauravgola96** [googleapis/google-cloud-go#4033]
I was trying out https://github.com/googleapis/google-cloud-go/blob/bigquery/v1.17.0/bigquery/storage/apiv1beta2/big_query_write_client_example_test.go

I am unable to figure out to send a nested json into stream.
My use case is where i want to read from db and stream it to big query. 
`go func() {
		reqs := []*storagepb.AppendRowsRequest{
			// TODO: Create requests.
		}
		for _, req := range reqs {
			if err := stream.Send(req); err != nil {
				// TODO: Handle error.
			}
		}
		stream.CloseSend()
	}()`
Can somebody plz give an example of requests.

**Comment by shollyman** [comment]
I've got some work pending here to make this a bit easier, but the API works based on proto serialization, rather than json serialization directly.  Will hold onto this until we have examples published.

**Comment by gauravgola96** [comment]
@shollyman 
```
     import( 	
     storagepb "google.golang.org/genproto/googleapis/cloud/bigquery/storage/v1alpha2", 
     storage "cloud.google.com/go/bigquery/storage/apiv1alpha2",
     "context",
     "fmt"
     )


      bqWrite, err := storage.NewBigQueryWriteClient(context.Background()) 
      stream := &storagepb.WriteStream{
		      Type:        storagepb.WriteStream_COMMITTED,
	      }

	req := &storagepb.CreateWriteStreamRequest{
		Parent: "projects/***/datasets/****/tables/****",
		WriteStream: stream,
	}

	resp, err1 := bqWrite.CreateWriteStream(context.Background(), req)

	if err != nil {
		fmt.Print(err)
		return nil,err
	}
	
```
	Getting error : 
	`"rpc error: code = Unimplemented desc = Operation is not implemented, or supported, or enabled.`

**Comment by shollyman** [comment]
The write client is live in apiv1beta2, apiv1alpha2 is turned down.

**Comment by shollyman** [comment]
Closing this.  Also, https://github.com/googleapis/google-cloud-go/issues/4366 may be valuable for following the progress of a veneer over the new write client.
