### ISSUE TITLE
internal: run goimports on generated snippets

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#4037]
I believe we should be able to run [imports.Process](https://pkg.go.dev/golang.org/x/tools@v0.1.0/imports#Process). Currently unformatted imports fail CI on regen. Manually patched in #4025

**Comment by codyoss** [comment]
cc @tbpg

**Comment by tbpg** [comment]
`goimports` is run on generated snippets here:

https://github.com/googleapis/google-cloud-go/blob/a2972783c4af806199d1c67c9f63ad9677f20f34/internal/gapicgen/gensnippets/gensnippets.go#L82-L88
