### ISSUE TITLE
datastore: Operations with datastore emulator are timing out if IPV6 DATASTORE_EMULATOR_HOST is used

### ISSUE THREAD

**Issue by g-landrey** [googleapis/google-cloud-go#4093]
**Client**

Chromeperf

**Environment**

We are developing in https://source.chromium.org/chromium/infra/infra/+/master:go/src/infra/chromeperf/

Here is the instruction on how we setup the environment: https://chromium.googlesource.com/infra/infra//+/HEAD/go/README.md#get-the-code

**Steps to reproduce**

Run `gcloud beta emulators datastore start`

The command prints host to which we should connect. In my case it by default uses IPV6 port. E.g. "export DATASTORE_EMULATOR_HOST=::1:8913" 

Run `export DATASTORE_EMULATOR_HOST=::1:8913 & go test ./...`

Test is the simple example from the datastore documentation (https://pkg.go.dev/cloud.google.com/go/datastore#Client.Put):
e.g.
```go
ctx := context.Background()
client, err := datastore.NewClient(ctx, "")
if err != nil {
  // TODO: Handle error.
}

type Article struct {
  Title       string
  Description string
  Body        string `datastore:",noindex"`
  Author      *datastore.Key
  PublishedAt time.Time
}
newKey := datastore.IncompleteKey("Article", nil)
_, err = client.Put(ctx, newKey, &Article{
  Title:       "The title of the article",
  Description: "The description of the article...",
  Body:        "...",
  Author:      datastore.NameKey("Author", "jbd", nil),
  PublishedAt: time.Now(),
})
if err != nil {
  // TODO: Handle error.
}
```

**Expected behavior**

Test finishes.

**Actual behavior**

client.Put command hangs forever and the test times out.

**Additional context**

If we explicitly use IPV4 port (e.g. "gcloud beta emulators datastore start --host-port=127.0.0.1:12345") - everything works fine.

**Comment by crwilcox** [comment]
Thanks for reporting. Glad you found a workaround but we can investigate this.

**Comment by crwilcox** [comment]
I think the issue here is the recommendation for how to export the IP address of the emulator.

IPv6 addresses should be in brackets to aid in parsing. When I provide it in this fashion it functions as expected.
```
❯ gcloud beta emulators datastore start --host-port=[::1]:8913
❯ export DATASTORE_EMULATOR_HOST=[::1]:8913
```

 I will create an issue on the emulator to address the following print out.
 ```
 [datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore]
[datastore]   export DATASTORE_EMULATOR_HOST=::1:8913
[datastore]
[datastore] Dev App Server is now running.
```
