### ISSUE TITLE
BigQuery: Add missing DecimalTargetType to ExternalDataConfigOptions in external.go

### ISSUE THREAD

**Issue by danieldeleo** [googleapis/google-cloud-go#4110]
Please add [DecimalTargetType](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#decimaltargettype) to the client library's [ExternalDataConfigOptions](https://github.com/googleapis/google-cloud-go/blob/5c5ca08c637a23cfa3e3a051fea576e1feb324fd/bigquery/external.go#L150) in external.go

Thanks!

**Comment by shollyman** [comment]
blocked on discovery.

**Comment by shollyman** [comment]
internal: b/188414733
