### ISSUE TITLE
spanner: Question about NUMERIC data type for key

### ISSUE THREAD

**Issue by yfuruyama** [googleapis/google-cloud-go#4117]
This is not a bug report, but I'm curious if NUMERIC data type is supported for keys (Primary Key or Secondary Index) for Cloud Spanner.

In the PR https://github.com/googleapis/google-cloud-go/pull/3627, NUMERIC data type was supported for keys in Go, but it looks like Cloud Spanner doesn't support NUMERIC type for valid key column ([doc](https://cloud.google.com/spanner/docs/data-types#allowable_types)).

How are users expected to use NUMERIC type for [spanner.Key](https://pkg.go.dev/cloud.google.com/go/spanner#Key)?

**Comment by yfuruyama** [comment]
@olavloite Could you take a look at this question when you have time?

**Comment by olavloite** [comment]
Cloud Spanner does (currently) not support `NUMERIC` as part of the key of a primary key or secondary index. The restriction in the client library has however been removed to be consistent with the client libraries for the other languages that in general did not have this limitation. This also ensures that if Cloud Spanner were to introduce support for `NUMERIC` as part of a key, the client library would also support it directly without the need for any changes. Note though that I do not know whether there are any plans for supporting `NUMERIC` for keys in the future or not.

**Comment by yfuruyama** [comment]
That makes sense. Thank you for answering the question!
