### ISSUE TITLE
redis: Missing AuthEnabled and InTransitEncryption parameters

### ISSUE THREAD

**Issue by dominikmueller** [googleapis/google-cloud-go#4129]
**Is your feature request related to a problem? Please describe.**
It currently is not possible to create Redis/Memorystore instances with Authentication and/or InTransitEncryption without using a deprecated go client library.

**Describe the solution you'd like**
I would like to be able to provision Redis instances with enabled security-features like TLS and authentication using the current google-cloud-go libraries.

The required configuration parameters (`AuthEnabled` and `TransitEncryptionMode`) presumably need to be added to the [interface definitions](https://github.com/googleapis/googleapis/tree/master/google/cloud/redis).

**Describe alternatives you've considered**
It's already possible to create such instances by using the [google-api-go-client library](https://github.com/googleapis/google-api-go-client/tree/master/redis/v1beta1). But since the redis-packages are [marked deprecated](https://github.com/googleapis/google-api-go-client/blob/master/redis/v1beta1/redis-gen.go#L9), it would be better to include all features and parameters to the new GRPC and Protocol Buffer-based Libraries so they can be used for current and future projects instead of having to rely on already deprecated libraries.

**Additional context**
\- none -

**Comment by codyoss** [comment]
Hey, thanks for the report. I have filed an internal issue, 188654996, for updating the public protos. It seems like they are out of date with the public discovery doc listing. I will close this issue for now, but will ping back once the update is rolled out. Thanks!
