### ISSUE TITLE
bigquery : Field "null" when for boolean values when given false, 0

### ISSUE THREAD

**Issue by gauravgola96** [googleapis/google-cloud-go#4130]
I am trying to stream boolean values into big query table. Using Grpc storage write client in Golang. 
But facing error as whenever 0 or false is sent it become null in the table

my proto message  
```
message event{
  bool abc = 1;
}
```

marshaling
```
eventProto := Event{ abc : false}
rowData,err := eventProto.Marshal()
```
I am using "google.golang.org/genproto/googleapis/cloud/bigquery/storage/v1beta2"

**Comment by shollyman** [comment]
I need to go back and extend support to do this.  Will try to find time soon.

**Comment by shollyman** [comment]
Closing this in favor of veneer work in https://github.com/googleapis/google-cloud-go/issues/4366.
