### ISSUE TITLE
logging: configure cloud.google.com/go/logging to log to stdout

### ISSUE THREAD

**Issue by rogierlommers** [googleapis/google-cloud-go#4131]
I use the cloud.google.com/go/logging package a lot, but for local (offline) development, I would like to configure the logging instance to log to stdout, instead of to the real (stackdriver) online platform. Is it possible to add this feature?

**Comment by nicoleczhu** [comment]
Hello, you can try out the preview for it here: https://pkg.go.dev/cloud.google.com/go/logging/jsonlog

**Comment by rogierlommers** [comment]
Hey @nicoleczhu , cool! Will do that soon. Need to finish stuff first... I'll let you know!
