### ISSUE TITLE
pubsub: add interface types for shared dataplane operations with Pub/Sub Lite

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/google-cloud-go#4141]
You should be able to define an interface as:

```
type Publisher {
  Stop()
  Publish(ctx context.Context, msg *pubsub.Message) *pubsub.PublishResult
}
```

Which is implemented by both Pub/Sub's Topic and Pub/Sub Lite's pscompat.PublisherClient, so you can be agnostic to which you are using. Similarly, on the subscriber side you can define an interface:

```
type Subscriber {
  Receive(ctx context.Context, f MessageReceiverFunc) error
}
```

Which is implemented by both the Pub/Sub Subscription and Pub/Sub Lite pscompat.SubscriberClient. Also, pubsub.MessageReceiverFunc should be defined as an alias for the type of function that needs to be passed to the Receive method, which is currently an anonymous function type.

I think that these interfaces should be defined and added to the pubsub package, as it would assist users in being able to write code that is agnostic to which system it is talking to.

Thoughts?

**Comment by dpcollins-google** [comment]
I realized these didn't already exist when trying to author a response to #4137

**Comment by hongalex** [comment]
Per offline discussion, we're not looking to implement this at this time.
