### ISSUE TITLE
pubsub: expose a Subscription.ReceiveSettings.MinExtensionPeriod setting

### ISSUE THREAD

**Issue by i0exception** [googleapis/google-cloud-go#4150]
It looks like as soon as the pubsub library receives a message, it sets the ack deadline for that message to the 99th percentile of the processing latency distribution. This works well when the subscriber is uniformly slow or uniformly fast. However, in cases where the processing latency can vary, subscribers might want to have a fixed ack deadline that's equal to the same value as what the subscription was created with. Providing a setting for MinExtensionPeriod similar to MaxExtensionPeriod can help clients set this minimum value. 

An alternative would be to provide an option to completely disable modifying ack deadlines (even on initial receipt) and only rely on the subscription ack deadline. I'd have expected the library to do this when MaxExtension = -1, but that doesn't seem to be the case. Please correct me if I'm wrong here.

**Comment by hongalex** [comment]
Thanks for filing this issue. When we increase the API surface of our libraries, we want to do this in a way that's consistent across languages. I'll bring this up with the other language maintainers to see if this makes sense.

As for your other suggestion, you're right that the library currently does not allow disabling automatic lease management. If this is something that you want to do in the meantime, it is possible to build upon the base autogenerated library at `cloud.google.com/go/pubsub/apiv1`. I'll also bring this up at the same time.

**Comment by hongalex** [comment]
Some additional clarification here: have you experienced any instances of performance degradation due to not being able to set a `MinExtensionPeriod`? As you mentioned, we use the 99th percentile because it gives the best estimate of when to send ModAcks, and we haven't heard of reports of performance hits even with high amounts of ModAcks.
