### ISSUE TITLE
pubsub: Allow to override PublisherClient default CallOptions in pubsub.NewClient

### ISSUE THREAD

**Issue by cprates** [googleapis/google-cloud-go#4162]
**Is your feature request related to a problem? Please describe.**
At the moment I'm trying to troubleshoot a issue with high latencies when publishing events and I would like to have more visibility on the retries the internal PublisherClient is doing, like logging the error codes, but because pubsub.Client.pubc is not exposed in any way I can't change its CallOptions nor pass those in methods like Topic.Publish.

**Describe the solution you'd like**
I guess that the easier way would be to pass my own retry policy when calling pubsub.NewClient as an option

**Comment by hongalex** [comment]
Thanks for bringing this to our attention! I think this makes sense. I'll be exploring adding this in a way similar to how the [spanner client library exposes CallOptions](https://github.com/googleapis/google-cloud-go/pull/2599).

**Comment by cprates** [comment]
If you didn't start yet I can give it a go

**Comment by hongalex** [comment]
Sorry for the lack of an update on this. I'm still planning to work on this, but a few higher priority items came up but will be my next priority. I'll update here once I have a PR out.
