### ISSUE TITLE
bigquery : rpc error: code = InvalidArgument desc = Request contains an invalid argument 

### ISSUE THREAD

**Issue by gauravgola96** [googleapis/google-cloud-go#4179]
I am facing strange behaviour when using Storage Write API in Pending mode. 
When I am trying to stream ~300-400 rows it works perfectly but after a certain size (~1k) it throws error when i do
`_, err = stream.Recv()`
Error : 
`rpc error: code = InvalidArgument desc = Request contains an invalid argument `

Although my request format is always same

Code:
```
go func(){
       for _, req := range reqs {
		if err := stream.Send(req); err != nil {
			log.Error().Err(err).Msgf("error in Streaming")
		}
		 stream.CloseSend()
		}
		 }()

	// waiting to receive non-nil error
	for {
	        _, err = stream.Recv()
	        if err==io.EOF{
		        break
	        }
	        if err != nil {
		        log.Error().Err(err).Msgf("error in Streaming ")
		        return nil, err
	        }
	}


```
I have tested it yesterday with huge records (~5-10K). It was working fine

**Comment by shollyman** [comment]
That appears to be indicative of a problem with the corresponding input request.  Try converting it to it's grpc.Status equivalent and checking to see if there's more details.  Could be a problem with the request itself, with the proto serialization of one of the data rows, etc.

**Comment by gauravgola96** [comment]
@shollyman what could be the reason when i process and stream the same rows with small batches works fine ?

**Comment by gauravgola96** [comment]
I checked status and response
```
	for {
			resp, err := appendRowsStream.Recv()
			if err==io.EOF{
				break
			}
			if err != nil {
				subLogger.Debug().Msgf("More information on error ", resp.GetError())
				subLogger.Debug().Msgf("More information on error  response", resp.GetResponse())
				subLogger.Error().Err(err).Msgf("error in Streaming dataset %s table %s", dataset, table)
				return nil, err
			}
	}
```

Output:
`"message":"More information on error %!(EXTRA *status.Status=<nil>)"}`
`,"message":"More information on error response %!(EXTRA <nil>)"}`

**Comment by codyoss** [comment]
Here is an example how to inspect the error: https://pkg.go.dev/cloud.google.com/go#hdr-Inspecting_errors

**Comment by gauravgola96** [comment]
@codyoss @shollyman 

I checked used the above example 

```
if err != nil{
		if s, ok := status.FromError(err); ok {
			subLogger.Error().Msgf("error is streaming batch | status message : ", s.Message())
			subLogger.Error().Msgf("error is streaming batch | status message Proto : ", s.Proto())
			subLogger.Error().Msgf("error is streaming batch | status message  Details: ", s.Proto().Details)
			for _, d := range s.Proto().Details {
				subLogger.Error().Msgf("error is streaming batch | err: ", d)
			}
		}
		return nil, err

```

```
{"level":"error","message":"error is streaming batch | status message : %!(EXTRA string=Request contains an invalid argument.)"}
{"level":"error","message":"error is streaming batch | status message Proto : %!(EXTRA *status.Status=code:3 message:\"Request contains an invalid argument.\")"}
{"level":"error","message":"error is streaming batch | status message  Details: %!(EXTRA []*anypb.Any=[])"}
```

**Comment by gauravgola96** [comment]
When my batch fails and I split it into smaller batch(~300) and stream, it works perfectly. But if same rows in a single batch ~500 throws the above error all of sudden some times.

**Comment by gauravgola96** [comment]
@shollyman @codyoss would you plz help?  I am still unable to figure out this

**Comment by shollyman** [comment]
There's a bound on request size (10Mb), so if your rows are sufficiently large it's possible you could be hitting this error.  My expectation is that this would yield an appropriate error response however.

**Comment by gauravgola96** [comment]
@shollyman @codyoss I checked on the rows I have been streaming and they are not large enough to cross 10MB size. I even made my batches small. I am still stucked here any suggestions would be really appreciated

**Comment by shollyman** [comment]
Looked at this again.  You've apparently got the send and recv code in the same goroutine, which means you're subject to things like request queue length; too many appends without reading results might be a source of errors here.

**Comment by shollyman** [comment]
Closing this one due to lack of further updates.
