### ISSUE TITLE
Spanner: add function to get database string

### ISSUE THREAD

**Issue by zanecat** [googleapis/google-cloud-go#4188]
**Is your feature request related to a problem? Please describe.**
Is it possible to have a method on spanner client that allows user to get the db string that's used to initiate the client?

**Describe the solution you'd like**
https://github.com/googleapis/google-cloud-go/blob/8a28ff6cebf22a30fa1bb54541b321436221e2f9/spanner/sessionclient.go#L89

Add a getter `func (c *spanner.client) GetDBName() string {...}` to return this field.

**Comment by hengfengli** [comment]
@olavloite What do you think about this? I feel it is okay to add one.

**Comment by olavloite** [comment]
> @olavloite What do you think about this? I feel it is okay to add one. But `GetDBName` does not seem to be right terminology as Name is the full path and in Go's convention, we don't use `Get` as prefix, should we call it `DatabaseId()` or `Database()`?

Yes, I think it would be reasonable to add that. I would however opt for `DatabaseName` to indicate clearly that:
1. It is the entire name of the database (`projects/my-project/instances/my-instance/databases/my-database`) and not just the id.
2. It is the name, and not some struct containing more information about the database (therefore I would prefer not to use `Database()`)

**Comment by zanecat** [comment]
Thanks a lot!
