### ISSUE TITLE
bigtable/bttest: emulator too lenient regarding RowFilter and CheckAndMutateRow conditions

### ISSUE THREAD

**Issue by dragonsinth** [googleapis/google-cloud-go#4201]
**Expected behavior**

bigtable emulator should fail statically incorrect filter and mutate requests like production bigtable.

**Actual behavior**

Several incomplete requests are not flagged as invalid by the bigtable emulator (bttest).  These queries fail against real bigtable.

- BlockAllFilter=false
- PassAllFilter=true
- Chain with less than 2 filters
- Interleave with less than 2 filters
- CheckAndMutateRowRequest with no Mutations specified

The bttest test suite actually produces invalid queries which fail against production bigtable.

**Comment by jimfulton** [comment]
@crwilcox shouldn't this issue be closed?

**Comment by dragonsinth** [comment]
It's definitely fixed, but I'm not sure how things work regarding linking issues to particular releases; some projects don't close issues into a release happens.
