### ISSUE TITLE
bigquery: Streaming Buffer insight and/or manual flushing

### ISSUE THREAD

**Issue by jessetuglu** [googleapis/google-cloud-go#4223]
**Is your feature request related to a problem? Please describe.**
Currently, as I see it, there is an option to stream data into bigquery, however there is a max 90 min – I have seen longer – waiting period in which this data is not queryable/editable. 

**Describe the solution you'd like**
Is there a way to manually flush this streaming buffer? Or, at the very least check if there indeed is a buffer via included method?

**Describe alternatives you've considered**
As far as alternatives, I have been using load rather than insert, but I have noticed this is slow and is not as consistent compared to the services that streaming provides. Plus, it's far more convenient to load go native types rather than a csv or json file of some sort.

Also, I'm aware that a previous issue has been opened (#507) regarding this, but it was closed and I'm not sure appending this comment to it would resurface it.

Thanks!

**Comment by shollyman** [comment]
What you're asking is a totally reasonable thing, and is in fact being added to the successor to the original streaming API (`tabledata.insertAll`).  Specifically, you can define a data stream to a table with specific flushing semantics (immediately after append, via moving an offset flush cursor, or via an explicit stream/close commit).

You can see the underlying API progress at https://pkg.go.dev/cloud.google.com/go/bigquery/storage/apiv1beta2#BigQueryWriteClient

There's work to wrap this in an easier to use manual veneer but it's not yet available. Taking a look at the java version may give you a better sense of how it will work.

**Comment by jessetuglu** [comment]
Great, thank you!

**Comment by shollyman** [comment]
Going to close this one as there's no action directly associated.  We post significant updates via [`CHANGES.md`](https://github.com/googleapis/google-cloud-go/blob/master/bigquery/CHANGES.md), so that's the best place to keep abreast of updates.
