### ISSUE TITLE
firestore: `LastUpdateTime` is `time.Time` must be microsecond precision

### ISSUE THREAD

**Issue by DazWilkin** [googleapis/google-cloud-go#4229]
See: https://github.com/googleapis/google-cloud-go/blob/d979830c5d1423eb5befd33d03ba7adf3ec4c217/firestore/options.go#L59

The [documentation](https://firebase.google.com/docs/firestore/reference/rest/v1/Precondition) does not fully explain how this works and it took me time to grok it.

> string (Timestamp&nbsp;format)
>
> When set, the target document must exist and have been last updated at that time.
>
> A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits. 
>
> Examples: "2014-10-02T15:01:23Z" and "2014-10-02T15:01:23.045123456Z".

Golang [time.Time](https://golang.org/pkg/time/#Time) is nanosecond precision and so we should be good. Even though `LastUpdateTime` takes a `time.Time`, the nanosecond resolution (last 3 digits) must be zeros for the Golang function to work.

This seems to be an implementation detail for the client library (and its documentation) rather than something that needs to be learned by the developer.

```Golang
now := time.Now()
log.Printf("[Now] %s (%d)\n", now, now.UnixNano())

preconds := firestore.LastUpdateTime(now)
_, err := ref.Delete(ctx, preconds)
if err == nil {
	t.Errorf("Expected failure")
}

errStatus, _ := status.FromError(err)
log.Printf("[Now] %s (%s)", errStatus.Code(), errStatus.Message())
```
Yields:
```
[Now] 2021-06-07 13:54:23.851441895 -0700 PDT m=+0.662380388 (1623099263851441895)
[Now] InvalidArgument (timestamp cannot have more than microseconds precision)
```

The error is incorrect because, Golang `time.Time` is always nanosecond precision. I realized that what it needs is a `time.Time` that's rounded to microsecond (1000 nanoseconds) units. And so, the code needs to be something of the form:

```Golang
roundNow := time.Unix(0, (now.UnixNano()/int64(time.Microsecond))*int64(time.Microsecond))
log.Printf("[RoundNow] %s (%d)\n", roundNow, roundNow.UnixNano())

preconds := firestore.LastUpdateTime(roundNow)
_, err := ref.Delete(ctx, preconds)
if err == nil {
	t.Errorf("Expected failure")
}

errStatus, _ := status.FromError(err)
log.Printf("[RoundNow] %s (%s)", errStatus.Code(), errStatus.Message())
```
Which fails correctly because we're not giving it a time that matches its last updated:
```
[RoundNow] 2021-06-07 13:54:23.851441 -0700 PDT (1623099263851441000)
[RoundNow] InvalidArgument (Invalid base version, it is greater than the stored version: projects/my-proj/databases/(default)/documents/tests/valid)
```

The error is likely uncommon because, the developer is likely to `Get`'ting the snapshot and then usings its `Updated` property to set the `LastUpdateTime(snap.Update)` but still...

**Comment by crwilcox** [comment]
I couldn't quite repro this with the provided code. I was able to make this occur, but it is rather particular. Just using now with nanosecond precision activated the other error for me.

Version: cloud.google.com/go/firestore v1.5.0


```
ctx := context.Background()
client, _ := firestore.NewClient(ctx, "project-id")
now := time.Now()

doc := client.Collection("organization").Doc("newdoc-1")
// Retrieve the document to see its update time.
snapshot, _ := doc.Get(ctx)
log.Printf("[doc update] %s (%d)\n", snapshot.UpdateTime, snapshot.UpdateTime.UnixNano())

// the recorded time from the above was 1632346201061394000,
// but set a nanosecond precise time
now := time.Unix(0, 1632346201061394010)

// Configure a precondition. Expect it to fail, but for the timestamp we provided
// being greater than the recorded, not for precision.
precond := firestore.LastUpdateTime(now)
_, err = doc.Delete(ctx, precond)
if err == nil {
  panic(err)
}
errStatus, _ := status.FromError(err)
log.Printf("[Now] %s (%s)", errStatus.Code(), errStatus.Message())
```

2021/09/22 14:39:47 [Now] InvalidArgument (timestamp cannot have more than microseconds precision)


There are a few things here we may wish to address:
1) We can likely round to microsecond precision in our client. It seems all document updates are microsecond.

2) The documentation specifies that you can use nanosecond precision, 9 fractional digits. But if you send a nanosecond precise time, it fails. This is possibly a documentation issue at https://firebase.google.com/docs/firestore/reference/rest/v1/Precondition

b/200849781 opened to discuss further direction.

**Comment by crwilcox** [comment]
Adding a few notes quick also. I use OS X for development and it seems time.Now() is microsecond aligned. This may have been why the initial repro was insufficient for me.

**Comment by crwilcox** [comment]
Thanks for raising this issue. As it isn't really safe to just round timestamps on the user's behalf, and that the error message is fairly clear, we are going to purse a documentation clarification to resolve this.

If as a user you are able to round, I'd suggest seeing the above closed PR as a way to do so. That said, as the time needs to match the entity, I expect the majority of users are providing the timestamp from the entity itself.
