### ISSUE TITLE
bigquery: *big.Rat required for InferSchema, but does not serialize properly

### ISSUE THREAD

**Issue by jtjanchor** [googleapis/google-cloud-go#4233]
**Client**

BigQuery

**Environment**

e.g. Alpine Docker on GKE

**Go Environment**

$ go version
go version go1.16 linux/amd64

$ go env

**Code**

```go
  package main
  
  import (
      "encoding/json"
      "fmt"
      "math/big"
  )
  
  func main() {
      type MySchema struct {
          NumericField *big.Rat `bigquery:"numeric_field,nullable" json:"numeric_field"`
      }

      rat := big.NewRat(3324, 10)
      row := MySchema{rat}
      encoded, err := json.Marshal(row)
      if err != nil {
          fmt.Printf("error: %s\n", err.Error())
      }

      fmt.Println(string(encoded))
  }
```

This outputs:

```
{"numeric_field":"1662/5"}
```

**Expected behavior**

The type required to infer a NUMERIC field can be serialized properly.

**Actual behavior**

`*big.Rat` does not serialize properly and causes this error when trying to load data:

```Invalid NUMERIC value: 1662/5```

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

This happens when uploading using newline delimited json (derived from `json.Marshal`). I haven't tried other upload formats.

**Comment by codyoss** [comment]
Hey @jtjanchor  the json package provides some nice examples on how to provide [custom JSON marshalling](https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON). I check out those docs and see if that solves the problems you are having.

**Comment by jtjanchor** [comment]
> Hey @jtjanchor the json package provides some nice examples on how to provide [custom JSON marshalling](https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON). I check out those docs and see if that solves the problems you are having.

I appreciate the quick response. I did try to create a custom type, something like `type NumericField big.Rat` that implemented custom marshaling/unmarshaling functions, but the field type was not inferred correctly. I believe it was inferred as a `RECORD` field.

**Comment by codyoss** [comment]
I am not an expert on the bigquery front, for that I will defer to shollyman. But here is an example of a custom marshaller that converts the value to a string.

```
package main

import (
	"encoding/json"
	"fmt"
	"math/big"
	"strconv"
)

type NumericField struct {
	*big.Rat
}

func (nf *NumericField) MarshalJSON() ([]byte, error) {
	f, _ := nf.Float64()
	str := strconv.FormatFloat(f, 'f', -1, 64)
	return []byte(fmt.Sprintf("\"%s\"", str)), nil
}

type MySchema struct {
	NumericField *NumericField `bigquery:"numeric_field,nullable" json:"numeric_field"`
}

func main() {
	rat := big.NewRat(3324, 10)
	row := MySchema{NumericField: &NumericField{rat}}
	encoded, err := json.Marshal(row)
	if err != nil {
		fmt.Printf("error: %s\n", err.Error())
	}

	fmt.Println(string(encoded))
	//{"numeric_field":"332.4"}
}

```

**Comment by shollyman** [comment]
Will need to take a look here.  One known gotcha is that `big.Rat` doesn't retain scale/precision, so we have some issues choosing between NUMERIC and BIGNUMERIC.

**Comment by shollyman** [comment]
Had a chance to catchup on issues.

There's effectively two paths forward:

1) The bigquery library is focused on converting rows for the streaming insert interface.  There's no special functionality for building any of the file formats BQ supports (csv, newline-delimited json, avro, etc).  Cody's suggestion about building a custom JSON marshaller may be a good approach to this.  Also worth calling out [`NumericString()`](https://pkg.go.dev/cloud.google.com/go/bigquery#NumericString) and similar functions in the package if you go this route.

2) Depending on your use case, you may be able to leverage the saver functionality related to streaming inserts without using the actual streaming insert interface.  By invoking a struct saver, the data in the row will get reformatted to a form more compatible for producing newline-delimited JSON.

Take a look at this repro test I wrote to validate.  Obviously this isn't dealing with the newline handling for multiple rows, but it may give you another avenue to explore:

```
func TestRepro_Issue4233(t *testing.T) {

	type MySchema struct {
		NumericField *big.Rat `bigquery:"numeric_field,nullable" json:"numeric_field"`
	}

	rat := big.NewRat(3324, 10)
	row := MySchema{rat}

	gotSchema, err := InferSchema(MySchema{})
	if err != nil {
		t.Errorf("inferSchema failed: %v", err)
	}

	wantSchema := Schema{
		{Name: "numeric_field", Type: NumericFieldType},
	}

	if !testutil.Equal(gotSchema, wantSchema) {
		t.Errorf("InferSchema differs: got %#v want %#v", gotSchema, wantSchema)
	}

	ss := StructSaver{
		Schema: gotSchema,
		Struct: row,
	}

	savedRow, _, err := ss.Save()
	if err != nil {
		t.Errorf("Save() failed: %v", err)
	}

	wantSaved := map[string]Value{
		"numeric_field": "332.400000000",
	}

	if !testutil.Equal(savedRow, wantSaved) {
		t.Errorf("saved row differs: got %#v want %#v", savedRow, wantSaved)
	}

	b, err := json.Marshal(savedRow)
	if err != nil {
		t.Errorf("json marshal fail: %v", err)
	}

	wantBytes := []byte(`{"numeric_field":"332.400000000"}`)

	if bytes.Compare(b, wantBytes) != 0 {
		t.Errorf("data mismatch: got %s want %s", string(b), string(wantBytes))
	}
```

**Comment by shollyman** [comment]
I'll go ahead and close this one out, feel free to comment further if I've missed something.
