### ISSUE TITLE
all: trace streaming grpc calls

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-go#4234]
In order to quiet the logs as reported in https://github.com/googleapis/google-cloud-go/issues/4133 we now only trace the time to first result for a streaming call. It may be interesting if we could trace/report on additional rpc calls.

This is a bit niche, and likely below in priority to finding a way to provide rpc traces for unary calls, but making a note here.

**Comment by codyoss** [comment]
Closing in favor of #4237
