### ISSUE TITLE
bigtable/cbt: control over data formatting in read and lookup

### ISSUE THREAD

**Issue by jimfulton** [googleapis/google-cloud-go#4265]
Bigtable has a very flexible data model and every value stored is simply an opaque byte array. Users often store data in a particular way, often in some binary encoded from. This makes cbt’s “read” commands much less useful, since values can only be printed as binary strings. To solve this we want to introduce a command-line option that specifies the format that cbt should use to display the data. This functionality should be available for the “lookup” and “read” commands.

Formatting should initially be controlled via a YAML configuration file supplied via a command-line option.

Formats (beyond the existing/default %q format):

- deserialized protocol-buffer data
- deserialized binary data (e.g. big-endian int64)
- hex

I'll be submitting a PR soon. :)

**Comment by telpirion** [comment]
This feature has been implemented in `cbt` version 0.12.0. (The `cbt` tool has also moved to another [repo](https://github.com/googleapis/cloud-bigtable-cbt-cli).)
