### ISSUE TITLE
bigquery: insertion fails silently when a column name in ValueSaver is incorrect

### ISSUE THREAD

**Issue by pofl** [googleapis/google-cloud-go#4269]
**Client**

BigQuery

**Environment**

alpine container as well as local execution

**Go Environment**

<details>
<pre>
 pofl@LATITUDE5300  ~/dwh-kafka2dwh/kafka2bigquery   master ±  go version
go version go1.16.3 linux/amd64
 pofl@LATITUDE5300  ~/dwh-kafka2dwh/kafka2bigquery   master ±  go env    
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pofl/.cache/go-build"
GOENV="/home/pofl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pofl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pofl/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pofl/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pofl/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pofl/dwh-kafka2dwh/kafka2bigquery/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4281501096=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

**Expected behavior**

- I'm inserting a row into a table via implementing ValueSaver interface
- I recently changed the schema of the table, i.e. I renamed a column
- But I forgot to adjust the Save() function
- The Save() function creates a row map with an entry that has the old column name which does not exist anymore
- The row map does not contain a value for the new column name
- _Expected behavior_: Inserter.Put() returns an error

**Actual behavior**

Inserter.Put() returns no error and the row does not get inserted.

**Screenshots**

![image](https://user-images.githubusercontent.com/14232537/122260550-b2e97e00-ced3-11eb-9521-6eb4e0b00f12.png)

screenshot show the row that is inserted on the left. The name of the column is `affected_account_id` instead of `acc_user_id` after renaming.

**Additional context**

	cloud.google.com/go/bigquery v1.18.0

**Comment by shollyman** [comment]
I am somewhat flummoxed on this one given current details.

From the partial dump on the left, I'd expect an error to be emitted; a quick runthrough of the error formatting code I don't see an obvious case where a response with errors present would get stripped.

If you can share more information on this, it would be helpful.  If you'd prefer not to put private details in this issue, feel free to email additional details directly to me (same username at google.com).

**Comment by pofl** [comment]
I finally got around to write up a minimal example that reproduces the bug.

```go
package main

import (
	"context"

	"cloud.google.com/go/bigquery"
	"github.com/hashicorp/go-uuid"
	log "github.com/sirupsen/logrus"
)

func main() {
	client, _ := bigquery.NewClient(context.Background(), FILLIN)
	client.Location = "EU"
	ds := client.Dataset("bug_mwp")
	table := ds.Table("one")
	_ = table.Create(context.Background(), &bigquery.TableMetadata{
		Schema: bigquery.Schema{
			{Required: false, Name: "one", Type: bigquery.StringFieldType},
			{Required: false, Name: "two", Type: bigquery.StringFieldType},
			{Required: false, Name: "three", Type: bigquery.StringFieldType},
		},
	})
	err := table.Inserter().Put(context.Background(), row{"test", false})
	if err != nil {
		log.Fatal("fail: " + err.Error())
	}
	err = table.Inserter().Put(context.Background(), row{"test", true})
	if err == nil { // fatal if no error
		log.Fatal("fail: " + err.Error())
	}
}

type row struct {
	dummy      string
	shouldFail bool
}

func (r row) Save() (row map[string]bigquery.Value, insertID string, err error) {
	row = make(map[string]bigquery.Value)
	insertID, _ = uuid.GenerateUUID()
	if r.shouldFail {
		row["one"] = r.dummy
		row["dos"] = r.dummy // typo here
		row["three"] = r.dummy
		return
	}
	row["one"] = r.dummy
	row["two"] = r.dummy
	row["three"] = r.dummy
	return
}
```
Neither Fatal is called and only one row is inserted.

**Comment by shollyman** [comment]
Thanks, confirmed this is not surfacing the returning error with cloud.google.com/go/bigquery v1.18.0:

```
2021/06/26 09:04:55 REQUEST
=====
POST /bigquery/v2/projects/shollyman-demo-test/datasets/repro_eu/tables/one/insertAll?alt=json&prettyPrint=false HTTP/1.1
Host: bigquery.googleapis.com
Authorization: Bearer <REDACTED>
Content-Type: application/json
User-Agent: google-api-go-client/0.5
X-Cloud-Trace-Context: 10540c6dabe12415edb06844da950f9a/11416575809934970165;o=0
X-Goog-Api-Client: gl-go/1.16.0 gccl/20201104

{"rows":[{"insertId":"f1fc75f1-f128-16de-09c4-6430898d21f4","json":{"dos":"test","one":"test","three":"test"}}]}

=====
2021/06/26 09:04:55 RESPONSE
=====
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Sat, 26 Jun 2021 16:04:55 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{"kind":"bigquery#tableDataInsertAllResponse","insertErrors":[{"index":0,"errors":[{"reason":"invalid","location":"dos","debugInfo":"","message":"no such field: dos."}]}]}

**Comment by shollyman** [comment]
I was looking at the output incorrectly this weekend, after I had rewritten the repro with some extra wire diagnostics.  Are there special setup steps necessary?  I can't induce lack of error.

Any chance you've got something like a proxy or similar in the way which may be intercepting requests/responses?

```
type row4269 struct {
	dummy      string
	shouldFail bool
}

func (r row4269) Save() (row map[string]Value, insertID string, err error) {
	row = make(map[string]Value)
	insertID = "" // will force library to generate an insertid
	if r.shouldFail {
		row["one"] = r.dummy
		row["dos"] = r.dummy // typo here
		row["three"] = r.dummy
		return
	}
	row["one"] = r.dummy
	row["two"] = r.dummy
	row["three"] = r.dummy
	return
}
func TestRepro_Issue4269(t *testing.T) {
	if client == nil {
		t.Skip("Integration tests skipped")
	}
	ctx := context.Background()
	table := dataset.Table("repro4269")
	_ = table.Create(ctx, &TableMetadata{
		Schema: Schema{
			{Required: false, Name: "one", Type: StringFieldType},
			{Required: false, Name: "two", Type: StringFieldType},
			{Required: false, Name: "three", Type: StringFieldType},
		},
	})

	for i := 0; i < 100; i++ {
		err := table.Inserter().Put(ctx, row4269{"test", false})
		if err != nil {
			t.Fatalf("fail when shouldn't(%d): %#v", i, err)
		}
		err = table.Inserter().Put(ctx, row4269{"test", true})
		if err == nil { // fatal if no error
			t.Fatalf("success when shouldn't(%d): %#v", i, err)
		}
	}
}



$ go test -v -run TestRepro_Issue4269
=== RUN   TestRepro_Issue4269
--- PASS: TestRepro_Issue4269 (14.81s)
PASS
ok      cloud.google.com/go/bigquery    15.720s
```

**Comment by pofl** [comment]
This behavior was observed on my notebook Wsl2/windows as well as in a k8s deployed microservice. I am not aware of anything like a proxy.

**Comment by shollyman** [comment]
Do you get consistent failure or periodic?  I'm trying to find out if I've overlooked something.

**Comment by pofl** [comment]
It fails silently 100% of the time

**Comment by shollyman** [comment]
Any chance this behavior is tied to a specific project?  I still haven't been able to reproduce this.  Any more details you can share would be welcome.

**Comment by pofl** [comment]
Hi shollyman, I was on vacation for the past two weeks and am now returning. After some final investigation I can now confirm that this is a false bug report and no such bug exists.

<details>
<summary>Explanation how I mistakenly perceived the library as not returning errors</summary>

I mistakenly observed the "bug" in the minimal example which I provided because 
1. For the case where no error should occur I wrote `if err != nil { Fail() }` and for the case where an error should occur I wrote `if err == nil { Fail() }`
2. Then my brain farted or something. I ran the program, nothing was logged, everything succeeded. Then I was like "See? No error. Told ya!" - having completely forgotten that the program expects the error and would have logged something if there had been _no_ error.


Now comes part two. Why I thought that the library returns no error in our production code:

This is the actual code of our micro service that tries to insert the row.

```go
func (ti *tableInserter) Insert(event InsertableEvent) error {
	ins := ti.ds.Table(ti.tableName).Inserter()

	// Due to our Kubernetes setup sometimes the connection gets closed before
	// the request is finished. Therefore retry gracefully. Don't worry, BigQuery
	// has a mechanism to prevent duplicate inserts.
	var err error
	for i := 0; i < 3; i++ {
		err := ins.Put(context.Background(), event)
		if err == nil {
			return err
		}
	}
	return err
}
```

My error is on line `err := ins.Put(context.Background(), event)` where `:=` should have been `=`.

</details>


This also means #4270 is a false report.

I feel so embarrassed to have made these reports while the error was on my end. I want to personally apologize to you as an actual person. I hope this hasn't caused you any stress. At one point this issue had the label 🚨 and I really hope nobody was woken up at night or something because of this false alarm.

**Comment by shollyman** [comment]
Thanks for getting back to me.  No worries about the mis-report, I'm much happier to see this get resolved than remain ambiguous.  So many reports are like books with the last pages torn out, unsatisfying resolution. You also went the extra mile and provided some concrete repro code, which is always appreciated. :) 

I'll go ahead and close out both issues.
