### ISSUE TITLE
bigquery: insertion fails silently when inserter is used with table$YYYYMMDD syntax

### ISSUE THREAD

**Issue by pofl** [googleapis/google-cloud-go#4270]
**Client**

BigQuery

**Environment**

local execution

**Go Environment**

<details>
<pre>
 pofl@LATITUDE5300  ~/dwh-kafka2dwh/kafka2bigquery   master ±  go version
go version go1.16.3 linux/amd64
 pofl@LATITUDE5300  ~/dwh-kafka2dwh/kafka2bigquery   master ±  go env    
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pofl/.cache/go-build"
GOENV="/home/pofl/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pofl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pofl/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pofl/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pofl/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pofl/dwh-kafka2dwh/kafka2bigquery/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4281501096=/tmp/go-build -gno-record-gcc-switches"
</pre>
</details>

**Expected behavior**

I'm reporting this from memory. This bug was observed about 5 weeks ago.

- I had read the godoc if `Inserter` which documents the `table$YYYYMMDD` syntax
- I was trying to backfill some events from our Kafka
- Since events are inserted into a timestamp-partitioned table I assumed I have to use `dataset.Table("tablename$20210616").Inserter().Put()` to make sure that events from the past end up in the proper date-partition (turns out I didn't have to, so maybe this is a sign that the godoc needs adjustments)
- _Expected behavior_: Either insertion succeeds -> nil error, or it fails -> Put() returns an error

**Actual behavior**

- Inserter.Put() returns no error and the row did not get inserted.

I'm sorry that I can't give you an example to reproduce this. Once I had realized that everything works as expected (and rows end up in the proper partition) when I don't add the $ suffix, I threw the code that didn't work away. I wanted to file an issue right then and there but ... procrastination. So now memories is all I have.

**Screenshots**

**Additional context**

This was in v1.17.0 or v1.16.0

**Comment by shollyman** [comment]
Hmm.  Do you recall if the table is/was externally partitioned or partitioned based on a user column?  The table suffix is really only relevant for the external (aka ingestion-time partitioned) table case, and it sounds from the description this may have been the case.

**Comment by shollyman** [comment]
I see our docstring is ambiguous on this as well.

**Comment by shollyman** [comment]
Closing per commentary on 4269.
