### ISSUE TITLE
logging: instance_name label is not valid for GCE Instance Resource

### ISSUE THREAD

**Issue by hopkiw** [googleapis/google-cloud-go#4272]
https://github.com/googleapis/google-cloud-go/blob/0232e6f224788a9c9adea6e5db56e0c0136954dd/logging/resource.go#L205

This code automatically detects and adds an `instance_name` label to the common resource object. However, the `instance_name` label never appears on any logs on the service side. I believe this is because the GCE instance resource only accepts a pre-validated set of labels which are the project, zone and instance ID. The code here should not add or send the instance_name label, and probably the service should reject resources with invalid labels to aid in discovery.

**Comment by hopkiw** [comment]
Alternately, the service could be updated to consider `instance_name` a valid label for a GCE Instance resource. This would have the added benefit of affecting existing software retroactively which is currently trying to send this label.

**Comment by minherz** [comment]
@hopkiw thank you for pointing to this problem. we will remove the code to align the behavior with the [documented](https://cloud.google.com/monitoring/api/resources#tag_gce_instance) set of labels for the GCE instance resource.
