### ISSUE TITLE
all: switch to google.golang.org/protobuf

### ISSUE THREAD

**Issue by neild** [googleapis/google-cloud-go#4273]
The most recent version of the Go protobuf API is the `"google.golang.org/protobuf"` module, released about a year ago.

Most of the Cloud client library packages are using the older `"github.com/golang/protobuf"` module. As of the time I write this, those packages are all using `v1.5.2` of this module, which is (mostly) a thin wrapper around the newer module.

It would be nice if the Cloud client libraries used the newer module directly.

In most cases, this can be accomplished by simply changing the import path to the newer module. Note that this doesn't change the underlying implementation being used at all, aside from removing one layer of wrapping.

In some cases, types from the "github.com/golang/protobuf" module appear in the exported API of a package. (In particular: `proto.Message`.) These places will need to continue to use the older module. This issue is about internal, non-externally-visible usage of the protobuf API.

**Comment by codyoss** [comment]
Related regen: https://github.com/googleapis/go-genproto/pull/623

**Comment by trakhimenok** [comment]
@codyoss any time soon to fix this one? For example firestore still references both github (obsolete) & google modules.

**Comment by trakhimenok** [comment]
New year, new hope to get this issue closed...

**Comment by codyoss** [comment]
Opened a PR to remove this as a direct dep across the whole repo.
