### ISSUE TITLE
pubsub: Memory growth observed while sending messages with ordering keys

### ISSUE THREAD

**Issue by srikanthvukkadapu** [googleapis/google-cloud-go#4288]
**Client**

PubSub v1.10.1

**Environment**

Ubuntu 20.04

**Go Environment**

go 1.16

**Expected behavior**

memory growth should not be observed while sending messages using transient `ordering keys` (ordering keys which have a limited life span) 

**Actual behavior**

Memory growth is observed while sending messages using `Topic.Publish` method with ordering keys. Attaching the proof report image. It looks like the maps `s.bundlers` and `s.outstanding` of PublishScheduler are growing. 

Should the increment of outstanding `s.outstanding[key]++` be done when the `key` is found in the map only as it is already initialised to `1` when it is not found in the map. 
https://github.com/googleapis/google-cloud-go/blob/71c046962a49468d8759113638a314326f4256a7/pubsub/internal/scheduler/publish_scheduler.go#L147 

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/34507991/122631733-52348e00-d0eb-11eb-9473-5238efad84e1.png">

**Comment by hongalex** [comment]
Someone else actually pointed out this issue and will be resolved by #4282.
