### ISSUE TITLE
storage: Writer.ObjectAttrs.Bucket is empty

### ISSUE THREAD

**Issue by gvmorley** [googleapis/google-cloud-go#4348]
Hi,

I'm using the Go Storage Client (v1.16.0) and I've noticed that `Writer.ObjectAttrs.Bucket` is empty.

This is my test code:
```golang
package main

import (
  "fmt"
  "cloud.google.com/go/storage"
  "context"
)

func main() {
  ctx := context.Background()
  storageClient, _ := storage.NewClient(ctx)
  w := storageClient.Bucket("myBucket").Object("myObject").NewWriter(ctx)
  fmt.Printf("%+v\n", w.ObjectAttrs)
  _ = w
}
```

And the result is:
```text
{Bucket: Name:myObject ContentType: ContentLanguage: CacheControl: EventBasedHold:false TemporaryHold:false RetentionExpirationTime:0001-01-01 00:00:00 +0000 UTC ACL:[] PredefinedACL: Owner: Size:0 ContentEncoding: ContentDisposition: MD5:[] CRC32C:0 MediaLink: Metadata:map[] Generation:0 Metageneration:0 StorageClass: Created:0001-01-01 00:00:00 +0000 UTC Deleted:0001-01-01 00:00:00 +0000 UTC Updated:0001-01-01 00:00:00 +0000 UTC CustomerKeySHA256: KMSKeyName: Prefix: Etag: CustomTime:0001-01-01 00:00:00 +0000 UTC}
```

Is that expected?

I would have thought that `Writer.ObjectAttrs.Bucket` would have contained the string `myBucket` from the test code above.

This test was done on:

* Go Version: 1.16.3 darwin/amd64
* OS: macOS 10.15.7
* Go Storage Client: 1.16.0

Not a show-stopper, but just seems incorrect.

Thanks.

**Comment by ddelgrosso1** [comment]
Hi @gvmorley,

The behavior you are seeing from the provided code snippet is in fact correct. The [ObjectAttrs](https://github.com/googleapis/google-cloud-go/blob/5ac09d911f9e65fd15acb7c0c7acb0dd635f364f/storage/storage.go#L1024) that you are printing represent the uncommitted attributes of the object that will be written. The ObjectAttrs are not intended to be read. If you wish to see the committed attributes that include the bucket name, you can first write the object and call [.Attrs()](https://pkg.go.dev/cloud.google.com/go/storage#ObjectHandle.Attrs) on the writer.

**Comment by gvmorley** [comment]
Hi @ddelgrosso1 

Thanks so much for your kind reply. That makes perfect sense.

I'm still quite the novice on my journey with Golang, so thanks again for pointing me in the right direction.

**Comment by ddelgrosso1** [comment]
Glad to help @gvmorley. I am going to close this issue. If you have any further questions please feel free to reopen or create a new issue.
