### ISSUE TITLE
compute: call compute package error

### ISSUE THREAD

**Issue by wanglong001** [googleapis/google-cloud-go#4377]
**Client**
cloud.google.com/go v0.86.0
compute
**Environment**
![image](https://user-images.githubusercontent.com/14817376/124420409-ff690080-dd91-11eb-8408-873da7fdf0e5.png)

**Go Environment**
$ go version
go version go1.16.5 darwin/amd64
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wangzelong/Library/Caches/go-build"
GOENV="/Users/wangzelong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangzelong/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/wangzelong/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/x22xctmd4fx7wc31mcgkw96h0000gn/T/go-build883774571=/tmp/go-build -gno-record-gcc-switches -fno-common"
**Code**

e.g.
```go
reqs := &computepb.ListRegionsRequest{Project: "psyched-subset-161702"}
cli, _ := compute.NewRegionsRESTClient(context.Background(), option.WithCredentialsJSON([]byte(CRED_JSON)))
a, err := cli.List(context.TODO(), reqs)
fmt.Println(a, err)
```
return 

```
<nil> Get "compute.googleapis.com/compute/v1/projects/psyched-subset-161702/regions": unsupported protocol scheme 
```

```go
reqs := &computepb.ListRegionsRequest{Project: "psyched-subset-161702"}
cli, _ := compute.NewRegionsRESTClient(context.Background(), option.WithCredentialsJSON([]byte(CRED_JSON)), option.WithEndpoint("https://compute.googleapis.com/"))
a, err := cli.List(context.TODO(), reqs)
fmt.Println(a, err)
```
return 

```
<nil> Get "https://compute.googleapis.com//compute/v1/projects/psyched-subset-161702/regions": stream error: stream ID 1; INTERNAL_ERROR

```

**Comment by wanglong001** [comment]
@noahdietz pls, help me fix it

**Comment by noahdietz** [comment]
Hi there, sorry about this, this client was launched in alpha and still had some bugs we missed. The fixes are pending and will come soon. Thanks.

**Comment by wanglong001** [comment]
@noahdietz  
Hi, I want to know the difference between these two repo ？ 
this repo and https://github.com/googleapis/google-api-go-client

**Comment by codyoss** [comment]
@noahdietz Maybe we should create a tracking bug with all known issues with the client so that people that are using the library can see what work is in progress still.

**Comment by noahdietz** [comment]
Tracking bug: https://github.com/googleapis/google-cloud-go/issues/4380

**Comment by codyoss** [comment]
@wanglong001 Thanks for the report, I am going to close this issue in favor of the one linked above.
