### ISSUE TITLE
pubsub: Configuring host proxy to publish a message

### ISSUE THREAD

**Issue by edualb** [googleapis/google-cloud-go#4379]
I have followed the [QuickStarter](https://cloud.google.com/pubsub/docs/quickstart-client-libraries) locally and I could test it perfectly, but when I try to put the pubsub library in the company project I figured out that I need to configure the proxy to connect the Google API, because I always receive an error `context deadline exceeded` because my app could not handle the connection. After that, I have been trying to configure the proxy of my company in pubsub lib.

Here are my tests:

1. Using `option.WithHTTPClient`:

```go
os := []option.ClientOption{}

proxyURL, err := url.Parse("http://proxy_host.com:9999") // example
clientHTTP := &http.Client{Timeout: time.Second * 1, Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)}}
o := option.WithHTTPClient(clientHTTP)

os = append(os, o)

client, err := pubsub.NewClient(context.Background(), "ProjecID", os...)
if err != nil {
	panic(fmt.Sprintf("Cannot connect client to PubSub Service for projectID: %s. Error: %s", projectID, err.Error()))
}
```

In this example, I have tried to use the `option.WithHTTPClient` but I received this error message:
```
pubsub(publisher): WithHTTPClient is incompatible with gRPC dial options
```

Of course, pubsub uses gRPC and can not use an HTTP Client, so I tried other approach.

2. Using `option.WithGRPCConn`:

```go
os := []option.ClientOption{}

ctx, _ := context.WithTimeout(context.Background(), 1*time.Second)
target := fmt.Sprintf("dns://%s:%s", "proxy_host.com", "9999") // example

conn, err := grpc.DialContext(ctx, target, grpc.WithInsecure()) // we are using grpc.WithInsecure just for test.
if err != nil {
	panic(fmt.Sprintf("It is not possible to dial with GRPC. ERROR: %s", err.Error()))
}
o := option.WithGRPCConn(conn)

os = append(os, o)

client, err := pubsub.NewClient(context.Background(), "ProjecID", os...)
if err != nil {
	panic(fmt.Sprintf("Cannot connect client to PubSub Service for projectID: %s. Error: %s", projectID, err.Error()))
}
```

However, I carry on receiving the error `context deadline exceeded`. Looking for more information, I found other alternative to try.

3. Set the environment variables `grpc_proxy`, `https_proxy` or `http_proxy`. 

I found [this](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) documentation and I try to set these environment variables:

```
grpc_proxy=proxy_host.com:9999
https_proxy=proxy_host.com:9999
http_proxy=proxy_host.com:9999
```

My application works, but did not anything. When I try send something, I did not receive an error and my application does not send the message to pubsub.

Could anyone help me to understand how can I configure the proxy of my company to use pubsub service?

**Comment by hongalex** [comment]
[This article](https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a) might be of help to you; there's a section in there that specifically mentions Pub/Sub and Go.

The issue forum here is for reporting problems with the client libraries. If you continue to have issues, I recommend asking on community forums, like StackOverflow with the `google-cloud-pubsub` tag.

**Comment by codyoss** [comment]
Depending on what needs your proxy has you may need to provide a custom dialer: https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md

I would suggest enabling verbose gRPC logging, mentioned in the environment variable doc you linked to, so you can better see what is going on with your network traffic.

Related: #1202
