### ISSUE TITLE
compute: fix bugs in alpha release

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#4380]
The `compute/apiv1` alpha release in v0.86.0 has a few known bugs. They are as follows:

- [x] missing scheme on default endpoint
- [x] `GET`/`DELETE` requests are generated with a body
- [x] remove `EmitUnpopulated` encoding option

First discovered post-release and then reported in #4377 by users.

This is a tracking bug.

**Comment by noahdietz** [comment]
https://github.com/googleapis/gapic-generator-go/pull/698 fixes the missing scheme.

**Comment by noahdietz** [comment]
https://github.com/googleapis/gapic-generator-go/pull/699 fixes the extraneous request body.

**Comment by noahdietz** [comment]
Regeneration of `compute/apiv1` with the above fixes passes CI: https://github.com/googleapis/google-cloud-go/pull/4364.

**Comment by codyoss** [comment]
@wanglong001 Thanks for the report, I am going to close this issue in favor of the one linked above.

**Comment by noahdietz** [comment]
Local integration tests succeed.

**Comment by noahdietz** [comment]
Fixes carried in https://github.com/googleapis/gapic-generator-go/releases/tag/v0.21.6.

**Comment by noahdietz** [comment]
Changes carried in #4383

**Comment by noahdietz** [comment]
To fix the third issue, need https://github.com/googleapis/gapic-generator-go/pull/702

**Comment by noahdietz** [comment]
Released generator fix in https://github.com/googleapis/gapic-generator-go/releases/tag/v0.21.7

**Comment by noahdietz** [comment]
Pending the outcome of some more testing before making a new release. Should have an update today midday PST.

**Comment by noahdietz** [comment]
Integration tests uncovered another issue, which was fixed with https://github.com/googleapis/gapic-generator-go/pull/710. Updating generator version in #4425.

**Comment by noahdietz** [comment]
All mentioned bugs were fixed in the release: https://github.com/googleapis/google-cloud-go/releases/tag/v0.87.0
