### ISSUE TITLE
storage: client not retrying on tls handshake error

### ISSUE THREAD

**Issue by tczhao** [googleapis/google-cloud-go#4381]
**Client**

Storage

**Environment**

**Go Environment**

**Code**

There's https://github.com/googleapis/google-cloud-go/pull/4019 that tried to address this issue.

However, 
the changes are only made to the [storage/go110.go](https://github.com/googleapis/google-cloud-go/blob/master/storage/go110.go)
instead of both [storage/go110.go](https://github.com/googleapis/google-cloud-go/blob/master/storage/go110.go) and [storage/not_go110.go](https://github.com/googleapis/google-cloud-go/blob/master/storage/not_go110.go)

**Expected behavior**

The storage client should retry on `net/http: TLS handshake timeout`

**Actual behavior**

The storage client is not retrying on `net/http: TLS handshake timeout`

**Comment by tczhao** [comment]
After reading https://code-review.googlesource.com/c/gocloud/+/55970/3/storage/not_go110_test.go#15
This make sense now,
`// +build !go1.10` means `<go1.10` not `!=go1.10`
Thus changes are only made to the `storage/go110.go` file

**Comment by tritone** [comment]
Yes, that is correct. We should clean this up at some point because we no longer support go versions <1.11
