### ISSUE TITLE
spanner/spansql: Support ALTER DATABASE (SET OPTIONS) statements

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-cloud-go#4390]
**Is your feature request related to a problem? Please describe.**

Some softwares use `spansql` package as a DDL parser but it doesn't support `ALTER DATABASE` statements.
If the DDL contains `ALTER DATABASE`, parsing will fail.
 
https://cloud.google.com/spanner/docs/data-definition-language?hl=en#alter-database
```
ALTER DATABASE `dbname` SET OPTIONS (enable_key_visualizer=true, optimizer_version=2, version_retention_period='7d')
```

**Describe the solution you'd like**

spansql package should support `ALTER DATABASE` with `SET OPTIONS`.

**Comment by hengfengli** [comment]
@olavloite Can you take a look at this?
