### ISSUE TITLE
bigquery: Add support for additional DML statistics from MERGE statements

### ISSUE THREAD

**Issue by d-torres** [googleapis/google-cloud-go#4408]
This feature request covers the additional of new information returned from MERGE statements on the total number of rows affected.  There are 3 types of information:
- Total number of records updated
- Total number of records inserted
- Total number of records deleted

Additional design and detail to be shared with implementers separately.

**Comment by shollyman** [comment]
already added in https://github.com/googleapis/google-cloud-go/pull/4405
