### ISSUE TITLE
pubsub: slow performance (cpu, db, network) inside a subscription Receive handler

### ISSUE THREAD

**Issue by kidoman** [googleapis/google-cloud-go#4409]
We are deploying to Cloud Run. Just to be sure that we were not loosing our minds, we wrote a couple of benchmarks (CPU, DB, Network) which we run both in a direct API handler as well as in a subscription Receive handler.

The processing speed inside the subscription receive handler seems to be at least a magnitude or more slower.

60 ms (to run math/big.ProbablyPrime on numbers 0 to 10_000_000) in a Cloud Run API Handler (we gave Cloud Run 4 cores and 4 Gi RMA), but the same exact code running in a Receive handler taking upwards of 30 seconds.

I am really unsure of what might be happening here.

**Comment by hongalex** [comment]
So just to clarify, you're comparing handling some function in Cloud Run directly versus running a Go Pub/Sub subscriber in Cloud Run? Are you [caching the Pub/Sub object](https://cloud.google.com/run/docs/tips/general#using_global_variables) and reusing it across runs? If you're instantiating a Pub/Sub client on each invocation, it requires a lot more overhead and could be contributing to the slowdown you noted.

**Comment by hongalex** [comment]
Closing due to lack of response, but feel free to recomment if my earlier comment didn't help and you experience this issue again.
