### ISSUE TITLE
cloudbuild: workerpool not found

### ISSUE THREAD

**Issue by alexdicianu** [googleapis/google-cloud-go#4432]
**Client**

Cloud Build

**Environment**

Docker, OSX, Kubernetes (all)

**Go Environment**

```
$ go version
go version go1.16.2 darwin/amd64
```

**Code**

Working example: 

```go
package main

import (
	"context"
	"fmt"

	cloudbuild "cloud.google.com/go/cloudbuild/apiv1/v2"
	"github.com/sirupsen/logrus"
	cloudbuildpb "google.golang.org/genproto/googleapis/devtools/cloudbuild/v1"
)

var log = logrus.WithField("component", "cloud-build-demo")

func initBuilder() (*cloudbuild.Client, error) {
	ctx := context.TODO()
	return cloudbuild.NewClient(ctx)
}

func main() {
	ctx := context.TODO()
	builder, err := initBuilder()
	if err != nil {
		log.WithError(err).Fatal("cannot instantiate builder")
	}
	cbr := &cloudbuildpb.CreateBuildRequest{
		ProjectId: "xxxxxxxxxxxxxxxxxx",
		Build: &cloudbuildpb.Build{
			Steps: []*cloudbuildpb.BuildStep{
				{
					Name:       "gcr.io/cloud-builders/curl",
					Entrypoint: "echo",
					Args:       []string{"hello", "world"},
				},
			},
			Options: &cloudbuildpb.BuildOptions{
				WorkerPool: "projects/xxxxxxxxxxxxxxxxxx/locations/us-central1/workerPools/xxxx",
			},
		},
	}
	op, err := builder.CreateBuild(ctx, cbr)
	if err != nil {
		log.WithError(err).Fatal("cannot create build")
	}
	metadata, err := op.Metadata()
	if err != nil {
		log.WithError(err).Error("cannot get metadata")
	}
	fmt.Printf("build metadata: %+v", metadata)
}

```

**Expected behavior**

The build is created and starts running.

**Actual behavior**

Error message received:
```
rpc error: code = NotFound desc = workerpool not found: \"projects/xxxxxxxxxxxxxxxxxx/locations/us-central1/workerPools/xxxx\"
```

**Screenshots**

n/a

**Additional context**

In trying out the new beta worker pool feature of Cloud Build, I tried creating a build targeted to run in the newly created worker pool. I am able to run that build using the `gcloud builds submit` command but when I try to do it programatically using the code above I'm getting the `workerpool not found error`. The credentials I'm using are the same in both cases.

**Comment by codyoss** [comment]
@alexdicianu  Thanks for the detailed report. That error message makes me think something is wrong in the WorkerPool field. Are you able to list the resource to ensure you have the correct resource path? 

```
gcloud alpha builds worker-pools list
```

Unfortunately I myself am not currently on the allowlist to test this feature. I would share this feedback/question with Cloud build team directly through their [issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=0).

**Comment by alexdicianu** [comment]
@codyoss thanks for the quick answer. Yes, I am able to list the resource and the path is correct. I will post this question in Cloud Build's issue tracker as well but I was thinking the problem lies within the Go client somewhere since I am able to run a build in the selected worker pool using the command: `gcloud builds submit`

**Comment by alexdicianu** [comment]
Also tracked under https://issuetracker.google.com/issues/193685195

**Comment by codyoss** [comment]
Thank you! I will close this issue now then as it can be tracked on the Cloud Build issue tracker. cc'ed myself there as well.
