### ISSUE TITLE
compute/metadata: accept request context

### ISSUE THREAD

**Issue by tam7t** [googleapis/google-cloud-go#4483]
**Is your feature request related to a problem? Please describe.**

`cloud.google.com/go/compute/metadata` API does have a way to make propagage a context to `http` requests. This means a context cannot be used to control RPC lifetime and that when open telemetry is used the requests from the `metadata` client are not associated with the parent span.

**Describe the solution you'd like**
Perhaps the package `*WithContext` variants of the existing functions could be added that allow passing in a request context.

**Describe alternatives you've considered**

**Additional context**

I'm able to attach tracing to the package by using the `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` package, but traces are not associated with parent spans.

```
hc := &http.Client{
	Transport: otelhttp.NewTransport(&http.Transport{
		Dial: (&net.Dialer{
			Timeout:   2 * time.Second,
			KeepAlive: 30 * time.Second,
		}).Dial,
	}),
	Timeout: 60 * time.Second,
}
mc := metadata.NewClient(hc)
```

**Comment by codyoss** [comment]
@tam7t Thanks for the feature request. I agree, this would probably be a good idea to support, at least to some extent. For your use cases are you using the helper methods(ProjectID, Hostname, InternalIP, etc) and/or are you using [Get](https://pkg.go.dev/cloud.google.com/go/compute/metadata#Client.Get)?

**Comment by tam7t** [comment]
My current usage is `ProjectID` and `InstanceAttributeValue`, and transitive usage of `metadata` through [Application Default Creds](https://github.com/golang/oauth2/blob/a41e5a7819143202e8d21fb9ac9c659fbd501fb3/google/google.go#L205)
