### ISSUE TITLE
all: Application Default Creds not included in context or tracing

### ISSUE THREAD

**Issue by tam7t** [googleapis/google-cloud-go#4487]
**Is your feature request related to a problem? Please describe.**

When ADC is used with instance-metadata

* resulting requests to instance metadata will not have RPC deadlines
* open-telemetry tracing of RPC calls wont include spans for retrieving metadata auth tokens (at least when using `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc`)

This is due to: 
* https://github.com/golang/oauth2/issues/262
* https://github.com/googleapis/google-cloud-go/issues/4483

**Describe the solution you'd like**

* I'd expect request deadlines to propagate to all downstream RPCs from the initial method call
* A way to enable tracing that separates out time spent talking to metadata server from time spent talking to the API

**Describe alternatives you've considered**

**Additional context**

**Comment by codyoss** [comment]
Hey @tam7t thanks for the request. I am not familiar with `otelgrpc` but I believe any requests that are made for ADC will all be HTTP based. To see this supported I agree that golang/oauth2#262 would need to be implemented first. Although that is an interface so we can't make changes to it, a new interface would need to be created and a migration path figured out for the many libraries using `TokenSource` today.

I don't think this request is really related to #4483 as that package just makes HTTP requests to a known endpoint, there is no auth involved.

This is something that is probably worth exploring and talking through but I think the changes would need to start in golang/oauth2 and then propagate to other packages. Would you mind opening this issue over on the oauth2 repo or adding some more context to golang/oauth2#262 why that change is important.

cc @broady

**Comment by tam7t** [comment]
Yeah, I only tagged https://github.com/googleapis/google-cloud-go/issues/4483 because the `oauth2` package depends on it in order to fetch the auth token from instance metadata. I will comment on the `golang/oauth2` package with context.

**Comment by codyoss** [comment]
With our new auth module starting to roll out token calls will now accept a context from the call they originate from. Also the compute/metadata package was likewise recently updated.
