### ISSUE TITLE
all: auth is treated as a channel level property and overwriting per-rpc is difficult

### ISSUE THREAD

**Issue by tam7t** [googleapis/google-cloud-go#4490]
**Is your feature request related to a problem? Please describe.**
The client libraries all treat authentication as a channel level property configured at client create time property instead of on a per-rpc basis:

```go
client, err := secretmanager.NewClient(ctx)
```

This is fine in most cases but when using the APIs in a multi-tenant system, where the identity for the downstream call to a GCP API may depend on the incoming request.

The [`secrets-store-csi-driver-provider-gcp`](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp) project runs as a single process per K8s node, and assumes the identity of many pod's when making requests to the Secret Manager API.

This leads to creating a new client with the appropriate auth in the request hander:

```go
func Handler(ctx context.Context, req *Request) {
	// ...
	// determine identity to assume based on incoming request
	ts := correctTokenForRequest(ctx, req)
	// construct a secret manager client with that identity
	client, _ := secretmanager.NewClient(ctx, option.WithTokenSource(ts))
	resp, _ := client.AccessSecretVersion(ctx, secretReq)
	// ..
}
```

This is not great because creating a new `secretmanager.Client` involves additional latency for establishing tcp connection tls handshakes. It would be better if a pool of underlying channel connection could be established on process start and re-used across RPCs

**Describe the solution you'd like**

I would like to be able to create a client normally and then override auth on a per-rpc basis with something like:

```go
client, err := secretmanager.NewClient(ctx)
resp, _ := client.AccessSecretVersion(ctx, secretReq, gax.WithTokenSource(ts))
```

Where the call to `client.AccessSecretVersion` would use the token from the `ts` token source instead of the Application Default Creds token.

**Describe alternatives you've considered**

I've come up with a solution here that seems to work: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/126/files

but it requires configuring the client with:

```
ops := []option.ClientOption{
	// tell the secretmanager library to not add transport-level ADC since
	// we need to override on a per call basis
	option.WithoutAuthentication(),
	// grpc oauth TokenSource credentials require transport security, so
	// this must be set explicitly even though TLS is used
	option.WithGRPCDialOption(grpc.WithTransportCredentials(credentials.NewTLS(nil))),
}

sc, err := secretmanager.NewClient(ctx, ops...)
```

and the RPC call site gets pretty ugly with wrappers:

```
resp, _ := client.AccessSecretVersion(ctx, req, gax.WithGRPCOptions(grpc.PerRPCCredentials(oauth.TokenSource{TokenSource: ts})))
```

I also looked at using `options.WithGRPCConn`:

```
sc, err := secretmanager.NewClient(ctx, options.WithGRPCConn(sharedConnection))
```

This still requires trickery as the [`google.golang.org/grpc/credentials/oauth.TokenSource`](https://pkg.go.dev/google.golang.org/grpc/credentials/oauth#TokenSource) sets `RequireTransportSecurity` to `true` but using TLS itself in GRPC isn't considered "transport security" without explicit configuration of `grpc.WithTransportCredentials(credentials.NewTLS(nil))`.

I'd also need to do more investigation to see if `options.WithGRPCConn` would work well with re-establishing the connection if it fails.

**Additional context**

**Comment by codyoss** [comment]
Hey @tam7t thanks for the feedback. I am glad you were able to figure out a workaround for your use-case. It is intentional that clients default to "channel" auth as this makes it easier for most use-cases in our client libraries. 

From my reading of this issue I think the main gottcha is the fact that in addition to `option.WithoutAuthentication` the option `option.WithGRPCDialOption(grpc.WithTransportCredentials)` is also needed. `gax` being able to pass a TokenSource seems like a nicer "sugar" API. Would you agree?

I will bring this up with some of the auth folk and other language client libraries to see what the experience is like for them.

**Comment by tam7t** [comment]
> From my reading of this issue I think the main gottcha is the fact that in addition to `option.WithoutAuthentication` the option `option.WithGRPCDialOption(grpc.WithTransportCredentials)` is also needed. `gax` being able to pass a TokenSource seems like a nicer "sugar" API. Would you agree?

Yup!

**Comment by broady** [comment]
I think we could implement this at the pool level: the pool could drain connections if it detects it has been left unused.

Every time a client makes a gRPC call, `Conn()` is called.

https://github.com/googleapis/google-api-go-client/blob/v0.52.0/transport/grpc/pool.go#L41
