### ISSUE TITLE
documentai: client authentication fails 

### ISSUE THREAD

**Issue by taalhach** [googleapis/google-cloud-go#4494]
**Client**

DocumentAI

**Go Environment**

$ go version
o version go1.15.6 linux/amd64

**Code**

```go
package main
import (	
documentai "cloud.google.com/go/documentai/apiv1"
"google.golang.org/api/option"
documentaipb "google.golang.org/genproto/googleapis/cloud/documentai/v1"
)
func main() {


		req := &documentaipb.ProcessRequest{
			Source: &documentaipb.ProcessRequest_RawDocument{
				RawDocument: &documentaipb.RawDocument{
					Content:  fileBytes,
					MimeType: "application/pdf",
				},
			},
			Name: "projects/{{PROJECT_ID}}/locations/us/processors/{{PROCESSOR_ID}}",
		}

		opt := option.WithCredentialsFile("/path/to/file/cred.json")
		ctx := context.Background()
		c, err := documentai.NewDocumentProcessorClient(ctx, opt)
		if err != nil {
			log.Debugf("failed to create client, err: %v", err)
			os.Exit(0)
		}
		defer c.Close()

		resp, err := c.ProcessDocument(ctx, req)
		if err != nil {
			log.Debugf("failed to process document, err: %v", err)
			os.Exit(0)
		}

}
```

**Expected behavior**

Client should process document 

**Actual behavior**

```
rpc error: code = Unauthenticated desc = Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

```
**Screenshots**

![image](https://user-images.githubusercontent.com/31938266/126874002-dc673183-060c-4491-b66e-06769bd3b88b.png)
**Additional context**

I have created service account and using credential from that account and while creating role i have created Basic > Owner role to give full access for now but i tried with document AI user role also. Still no luck on the other hand I have tried pubsub client with same credentials and it works perfectly fine. Is there something that i am doing wrong or this is bug with documentai client ??

**Comment by taalhach** [comment]
@codyoss can you please check this or mention someone who can confirm this bug or [recommend any solution?
thanks :)

**Comment by codyoss** [comment]
Hey @taalhach sorry you are having problems with authentication. My best guess is that you are pointing to a service account key that is no long active on your project. I tried to reproduce this with the sample code given and it work for me when I pointed to a valid service account with the correct permissions.

**Comment by taalhach** [comment]
@codyoss as you can see from screenshot it says it is an active key and i have generated more keys and tried with those but no luck. 
```
opt := option.WithCredentialsFile("path/to/key-fa7a66f98203.json")

c, err := documentai.NewDocumentProcessorClient(ctx, opt)
```

![image](https://user-images.githubusercontent.com/31938266/127013919-823552a7-d293-48bc-965a-f968c8def157.png)

does it have anything to do with gcp cli as i haven't installed it because client libraries can take care of auth by themselves ?

**Comment by taalhach** [comment]
@codyoss or is there something wrong with my service account setup as i have created using instructions [here](https://cloud.google.com/docs/authentication/production#create_service_account)

**Comment by taalhach** [comment]
finally after searching and spending a lot of time i found that was an issue of scopes when we pass credentials via file we need to add an extra `option.ClientOption`  which specifies the scopes for oauth2 access token. as we use service account so need to pass IAM API scope. unfortunately documentation does not even have any clue about that, i hope it can be of some help for someone. hit upvote here at [slackoverflow](https://stackoverflow.com/questions/65703339/fixedcredentialsprovider-gives-unauthorized-exception-when-calling-google-cloud) which really helped me. 
final piece of code:
```
		req := &documentaipb.ProcessRequest{
			Source: &documentaipb.ProcessRequest_RawDocument{
				RawDocument: &documentaipb.RawDocument{
					Content:  bytes,
					MimeType: "application/pdf",
				},
			},
			Name: "projects/{PROJECT_ID}/locations/us/processors/{PROCESSOR_ID}",
		}

		opt := option.WithCredentialsFile("path/to/credentials/file.json")
		ctx := context.Background()
		c, err := documentai.NewDocumentProcessorClient(ctx, opt, option.WithScopes("https://www.googleapis.com/auth/cloud-platform"))
		if err != nil {
			log.Debugf("failed to create client, err: %v", err)
			os.Exit(0)
		}
		defer c.Close()

		resp, err := c.ProcessDocument(ctx, req)
		if err != nil {
			log.Debugf("failed to process document, err: %v", err)
			os.Exit(0)
		}

```

**Comment by codyoss** [comment]
@taalhach Thanks for reporting back. I am still not able to reproduce this issue, but I am glad you got your code working. Default scopes should be added to the client for you unless you override them. The scope you are manually passing here looks to be the scope add be default. [1](https://github.com/googleapis/google-cloud-go/blob/master/documentai/apiv1/document_processor_client.go#L218) [2](https://github.com/googleapis/google-cloud-go/blob/b1b2afc2cd526f736953506133c61cf2e109b30f/documentai/apiv1/doc.go#L77-L81)

**Comment by taalhach** [comment]
@codyoss thanks for simplifying this piece of code really appreciate that :)
