### ISSUE TITLE
cloudsql: instances.list

### ISSUE THREAD

**Issue by wanglong001** [googleapis/google-cloud-go#4497]
https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/list?apix_params=%7B%22project%22%3A%22proj-x-317111%22%7D

I can't find it in this repo
Can this interface be called with this repo? If you can, please tell me how to call, thank you

**Comment by kurtisvg** [comment]
You can use this package for the Cloud SQL Admin API: https://pkg.go.dev/google.golang.org/api/sqladmin/v1beta4

These client libraries are located in https://github.com/googleapis/google-api-go-client
