### ISSUE TITLE
docs: publish help docs with product-neutral guides

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#4506]
Stuff like testing should be published in a "package" named `help`. It should include all of the markdown we want and a minimal TOC. See https://github.com/googleapis/google-cloud-go/tree/master/internal/godocfx.

**Comment by codyoss** [comment]
I am going to close this out for now. There is a cross-cutting effort going on that will be tracked elsewhere that should cover this sort of work. @telpirion FYI
