### ISSUE TITLE
internal: don't include unreleased packages in .repo-metadata-full.json

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#4541]
Currently, the repo-metadata includes a doc URL for unreleased packages. But, that URL won't exist until the module containing that package is released. So, we should prevent unreleased packages from showing up in the repo metadata.

I'm open to other solutions. Don't include the docs URL until it's released?

**Comment by noahdietz** [comment]
Perhaps we can modify the [manifest generation code](https://github.com/googleapis/google-cloud-go/blob/main/internal/gapicgen/generator/gapics.go#L601-L626) to key off of the `version.go` file containing `0.0.0` or something

**Comment by codyoss** [comment]
I don't think this is hurting any of our automation and has not raised any pain points over the last few years to my knowledge so I am inclined to close this out as WAI.
