### ISSUE TITLE
spanner: Can not decode Null value to user defined custom type with DecodeSpanner

### ISSUE THREAD

**Issue by NeoCN** [googleapis/google-cloud-go#4552]
**Client**

Spanner

**Environment**

macOS

**Go Environment**

$ go version
`go version go1.16.6 darwin/amd64`
$ go env

**Code**

https://github.com/googleapis/google-cloud-go/blob/v0.90.0/spanner/value.go#L1330-L1338

```go
		// Check if the pointer is a custom type that implements spanner.Decoder
		// interface.
		if decodedVal, ok := ptr.(Decoder); ok {
			x, err := getGenericValue(v)
			if err != nil {
				return err
			}
			return decodedVal.DecodeSpanner(x)
		}
```

https://github.com/googleapis/google-cloud-go/blob/v0.90.0/spanner/value.go#L1911-L1923

```go
// getGenericValue returns the interface{} value encoded in proto3.Value.
func getGenericValue(v *proto3.Value) (interface{}, error) {
	switch x := v.GetKind().(type) {
	case *proto3.Value_NumberValue:
		return x.NumberValue, nil
	case *proto3.Value_BoolValue:
		return x.BoolValue, nil
	case *proto3.Value_StringValue:
		return x.StringValue, nil
	default:
		return 0, errSrcVal(v, "Number, Bool, String")
	}
}
```

**Expected behavior**

With user defined custom type that implements spanner.Decoder interface, how the Null value is handled can be defined in the `DecodeSpanner` function, and the expected behavior is that `DecodeSpanner` function is invoked when decode Null value.

**Actual behavior**

As the code logic listed, `getGenericValue` function will return error when the value type is not `Number`, `Bool`, `String`.
And when the value is Null, the value type is `*structpb.Value_NullValue`, an error returned, so the `DecodeSpanner` in custom type will not be invoked and an error returned.

```
cannot use null_value:NULL_VALUE(Kind: *structpb.Value_NullValue) as Number, Bool, String Value
```

**Comment by hengfengli** [comment]
@olavloite Can you please take a look at this issue? Thanks.

**Comment by NeoCN** [comment]
Why restrict the type that can be decoded by `DecodeSpanner` ?

**Comment by NeoCN** [comment]
@hengfengli @olavloite Thanks for the quick fix. 

Can you share the reasons for restrict the type that can be decoded by `DecodeSpanner` ?

**Comment by olavloite** [comment]
> @hengfengli @olavloite Thanks for the quick fix.
> 
> Can you share the reasons for restrict the type that can be decoded by `DecodeSpanner` ?

I'm not exactly sure what you mean in this case. Do you mean the restriction before this change? If so, I think the restriction was simply an accidental omission by the original author that did not realize that null values needed special handling.
Or do you mean that there is some restriction still in place that will prevent the decoding of some specific type also after this change? If so, would you mind giving an example of what type cannot be decoded?

**Comment by hengfengli** [comment]
@NeoCN Do you mean why we limit to `proto3.Value_NumberValue`, `proto3.Value_BoolValue`, `proto3.Value_StringValue`? This is because all spanner primitive types (I think Array and Struct are not primitive types) are encoded to these three types of values, refer to https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/type.proto.

**Comment by NeoCN** [comment]
@hengfengli @olavloite Got it, thanks guys.

**Comment by NeoCN** [comment]
@hengfengli When will the new spanner package version with this bugfix be released ?

**Comment by hengfengli** [comment]
I can do a patch release (1.24.1) today.
