### ISSUE TITLE
pubsub: list subscription configs, not just names

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [googleapis/google-cloud-go#4559]
**Is your feature request related to a problem? Please describe.**
I have a use case for listing subscriptions where I want to check information in the `SubscriptionConfig` object. The underlying gRPC `ListSubscriptions` call includes this information (or at least the portion I need -- I'm not entirely sure if it includes everything needed to form a SubscriptionConfig?),  but the way it is exposed via the `Subscriptions` API on `pubsub.Client` and the resulting iterator it returns discards all this information (https://github.com/googleapis/google-cloud-go/blob/master/pubsub/subscription.go#L90-L96), and requires a second gRPC call for each subscription to re-acquire it!

**Describe the solution you'd like**
A couple possible solutions present themselves:
1. A `ListSubscriptionConfigs` API on `pubsub.Client` that returns an iterator exposing `SubscriptionConfig`s instead of `Subscription`s
2. A `NextConfig()` method on `SubscriptionIterator`

**Describe alternatives you've considered**
The workaround of calling `Config()` on every `Subscription` returned works, but is inefficient

**Comment by hongalex** [comment]
Hey, thanks for reporting! This is quite strange behavior indeed, and even though you already noted the workaround, I think this could be more user friendly.

Just opened a PR to address this.
