### ISSUE TITLE
pubsub: add docs or example for using PUBSUB_EMULATOR_HOST

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#4574]
Supersedes: #1617

**Comment by hongalex** [comment]
Just to be clear, is this adding an example for the GAPIC client to connect to the emulator?

**Comment by codyoss** [comment]
It would seem like this is something we support from the veneer layer. But I don't think we really document anywhere how to set this up and use it. I was intentionally vague as I know very little about the pubsub emulator myself 😅 . :

https://github.com/googleapis/google-cloud-go/blob/8b99dd356475a750000c06a44fc7b8423d703967/pubsub/pubsub.go#L128-L134
