### ISSUE TITLE
pubsub: pubsub package should expose PublishResult as a public member

### ISSUE THREAD

**Issue by johnpena** [googleapis/google-cloud-go#4588]
**Is your feature request related to a problem? Please describe.**

[PublishResult](https://github.com/googleapis/google-cloud-go/blob/master/internal/pubsub/publish.go) is effectively a public type of the `pubsub` package, because clients receive one as a return type when they call `topic.Publish(ctx, data)`. Unfortunately, `PublishResult` is in an `internal` package and can't be imported by client code. Thus, it can't be interacted with directly by clients, e.g. for use in test mocks. Ultimately client code using `PublishResult` is hard to test. 

**Describe the solution you'd like**

Move `publish.go` (linked above) to a non-internal package so that it can be imported by client code.

**Describe alternatives you've considered**

Testing requires a number of contortions to support this internal package, and is hard to get right. Another alternative is to use the pubsub emulator, but that requires a number of other contortions because the pubsub emulator requires java, which build environments often don't include. 

**Additional context**
N/A

**Comment by hongalex** [comment]
Hi, thanks for bringing this issue up.

Just to clarify, when you said "can't be imported by client code", what do you mean specifically?  We do export the alias of [`PublishResult`](https://github.com/googleapis/google-cloud-go/blob/543e3bb87fc2d7c94d519ae377e1fffe227d4dc0/pubsub/topic.go#L418).

For testing, we recently had a number of improvements to the pub/sub fake ([pstest](https://pkg.go.dev/cloud.google.com/go/pubsub/pstest)), that allows for  [setting custom `PublishResponses`](https://pkg.go.dev/cloud.google.com/go/pubsub/pstest#Server.AddPublishResponse) that is eventually used for `PublishResult` if you want to tweak those values. Does that help at all?

**Comment by johnpena** [comment]
@hongalex thanks for your guidance. pstest sounds like it's the right thing to use. Will give that a spin in the future instead of trying to directly mock the Pubsub client.
