### ISSUE TITLE
spanner: allow custom setting to bypass clock difference

### ISSUE THREAD

**Issue by boolafish** [googleapis/google-cloud-go#4631]
**Is your feature request related to a problem? Please describe.**

Our team was trying to manipulate the time in our service to test system reliability without our microservices. We used [chaos mesh](https://chaos-mesh.org/docs/simulate-time-chaos-on-kubernetes) to manipulate the time of the k8s pod/container.

However, we encountered the following error `Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe.` which blocks us from further testing after running a while. From some research, this would happen whenever there is a clock difference from the client to gcp server. 

**Describe the solution you'd like**

I would like to find a solution to continue to use spanner despite local clock differences. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hengfengli** [comment]
@boolafish This is not a Cloud Spanner issue but an authentication problem. I don't think we can do anything with it. If your clock has a lag, you should sync with NTP to correct it: 

* https://stackoverflow.com/questions/36189612/token-must-be-a-short-lived-token-and-in-a-reasonable-timeframe
* https://stackoverflow.com/questions/30115933/access-token-and-refresh-token-giving-invalid-grant-in-google-plus-in-python/30117441#30117441

@olavloite Any thoughts about this?

**Comment by boolafish** [comment]
> This is not a Cloud Spanner issue but an authentication problem.

ah true. hmm, I will find a more proper repo to post the issue later.

> If your clock has a lag, you should sync with NTP to correct it

ah, we create the lag on purpose to do chaos testing. Just currently we found out the chaos test would not last long because of the auth jtw token timing issue.

**Comment by hengfengli** [comment]
Since you created the lag, the auth works as expected. As a Cloud Spanner client, we rely on the auth underlying. Unless you don't use the auth to talk to gcp server, it is impossible to do that and I would not think there is a way to bypass it. You may be able to talk with the Cloud Spanner emulator: https://github.com/GoogleCloudPlatform/cloud-spanner-emulator. 

As this issue is not related to Cloud Spanner, I will close this issue.
