### ISSUE TITLE
compute/metadata: add retries

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#4642]
Add retries consistent to what is being done in other languages.

**Comment by codyoss** [comment]
Can probably borrow the logic used in apiaries today: https://github.com/googleapis/google-api-go-client/blob/8258338b24dd72029fd1705ff1a5fa15d55ce17c/internal/gensupport/resumable.go#L233-L258. I think that should cover the different edge cases well enough.

**Comment by codyoss** [comment]
@hostirosti This change is on HEAD. I will cut a release that includes this change on Monday, waiting for some other stuff to land first.

**Comment by valyala** [comment]
FYI, the commit, which fixes the issue, led to significant binary size increase for apps which import `compute/metadata` package. See https://github.com/googleapis/google-cloud-go/issues/4783 .
