### ISSUE TITLE
logging/apiv2: README.md information seems out of date

### ISSUE THREAD

**Issue by julieqiu** [googleapis/google-cloud-go#4674]
https://github.com/googleapis/google-cloud-go/blob/master/logging/apiv2/README.md says:

```
This code is EXPERIMENTAL and subject to CHANGE AT ANY TIME.
```

Which seems to be out of date information, since https://pkg.go.dev/cloud.google.com/go/logging uses that library, and is not advertised as experimental.

**Comment by codyoss** [comment]
Hey @julieqiu thanks for bringing this to our attention. This appears to be a historic artifact that has not been cleaned up for whatever reason. This library is stable. We will get this readme deleted. If a specific package is actually unstable/experimental we now add a warning in the godoc.
