### ISSUE TITLE
logging: Cannot get `protoPayload.serviceData.policyDelta` with ListLogEntries function.

### ISSUE THREAD

**Issue by mugioka** [googleapis/google-cloud-go#4736]
**Environment**

macOS Big Sur version 11.5.1
```
2.4 GHz 8core intel Core i9
```

**Go Environment**

$ go version
```
go version go1.15 darwin/amd64
```

**Code**
```go
package main

func main() {
        ctx := context.Background()
        adminClient, err := logadmin.NewClient(ctx, "MyProjectID")
	var entries []*logging.Entry
	jst, _ := time.LoadLocation("Asia/Tokyo")
	yday := time.Now().In(jst).AddDate(0, 0, -1)
	timestamp := time.Date(yday.Year(), yday.Month(), yday.Day(), 10, 0, 0, 0, yday.Location()).Format(time.RFC3339)
	fmt.Println(timestamp)
	iter := adminClient.Entries(ctx,
		logadmin.Filter(fmt.Sprintf(`protoPayload.methodName="SetIamPolicy" AND timestamp > "%s"`, timestamp)),
		logadmin.NewestFirst(),
	)
	// Fetch the most recent 20 entries.
	for len(entries) < 20 {
		entry, err := iter.Next()
		if err == iterator.Done {
			return entries, nil
		}
		if err != nil {
			return nil, err
		}
		fmt.Println(entry.Payload)
		entries = append(entries, entry)
	}
}
```

**Expected behavior**
The protoPayload.serviceData.policyDelta that can be retrieved in the Logging Explorer screen can also be retrieved successfully by the ListLogEntries function.

**Actual behavior**
The following values are currently included in the entry.Payload.
```
service_data:{type_url:"type.googleapis.com/google.iam.v1.logging.AuditData"  value:"\x12/\n-\x08\x01\x12\x0croles/editor\x1a\x1buser:oka_mugi@fuga.co.jp"}
```
Probably what is displayed on the Logging Explorer screen is included in the response, but not in the decoded format.

**Additional context**
This may not be a problem on the SDK side, but on the API side. Or is the correct behavior that the API can't get data such as policyDelta?

**Comment by mugioka** [comment]
It seems to be serialized in the protocol buffer.
I tried to deserialize it, but it seems that I am not getting the action shown on the log explorer.
![image](https://user-images.githubusercontent.com/62197019/132787766-fc120958-f945-4f24-bdbe-258833273cf0.png)

**Comment by codyoss** [comment]
You should be able to deserialize the data, here is a brief example:

```go
// import "google.golang.org/genproto/googleapis/cloud/audit"
// import alog "google.golang.org/genproto/googleapis/iam/v1/logging"

// convert the payload to a specific type
al, ok := entries[0].Payload.(*audit.AuditLog)
if !ok {
	log.Fatalf("can't cast: %T", entries[0].Payload)
}
// unmarshal the proto.Any
aData := &alog.AuditData{}
if err := al.ServiceData.UnmarshalTo(aData); err != nil {
	log.Fatalf("unable to marshal to: %v", err)
}
log.Println(aData.PolicyDelta)
```

Hope that helps!

**Comment by codyoss** [comment]
@simonz130 I think it might be a good idea to eventually add some samples for working with audit logs like this. It is not super straight forward imo.

**Comment by mugioka** [comment]
Oh, I'm sorry.
It was my lack of knowledge and research, ...
> 
I think it's great.

Thanks 😊.
