### ISSUE TITLE
bigquery: No way to get job statistics from Query

### ISSUE THREAD

**Issue by jameshartig** [googleapis/google-cloud-go#4745]
**Is your feature request related to a problem? Please describe.**
I'd like to use `Query.Read` to query and read the rows which can use the fast path queries API however the returned iterator does not give me any statistics on the query.

**Describe the solution you'd like**
Can the job's Statistics be put on the iterator so we could get them for metrics/billing purposes without having to resort to using the jobs.insert API?

**Describe alternatives you've considered**
Alternatively a new method could be added to only do the fast path and return an error if its not supported but this seems more complicated than just adding another field/method onto the iterator.

**Comment by shollyman** [comment]
What stats are you interested in?  A specific subset, or all?

**Comment by jameshartig** [comment]
> What stats are you interested in? A specific subset, or all?

Ideally the whole `JobStatistics` but for now just `TotalBytesProcessed`,  `TotalBytesBilled`, `CacheHit`.

**Comment by shollyman** [comment]
Would it be sufficient to expose the RowIterator source I wonder?  With the job reference you could then get the job metadata at your leisure.

**Comment by jameshartig** [comment]
In the case of the slow path the source would be a `Job` and in the fast path the source would be the `QueryResponse`? That sounds good to me!

**Comment by shollyman** [comment]
Yeah, both paths retain a reference to the job identifier/reference.  However, a RowIterator can be instantiated from a table directly, or by a query.  So we either have a job reference or a table reference.

**Comment by shollyman** [comment]
Take a look at https://github.com/googleapis/google-cloud-go/pull/4748 and see if that would address your needs.

**Comment by jameshartig** [comment]
Yep! That should work perfectly. Thanks for such a quick turnaround! I wasn't originally aware that the `queries` BQ endpoint actually still generated a job that you could get the status of but I see now that it returns a `JobReference`. Great

**Comment by jameshartig** [comment]
@shollyman thank you so much for the quick resolution! 🙏

**Comment by shollyman** [comment]
Working on that this week actually.  bigquery is its own submodule and released independently.  Keep an eye on https://github.com/googleapis/google-cloud-go/pull/4738 for updates.

**Comment by shollyman** [comment]
https://github.com/googleapis/google-cloud-go/releases/tag/bigquery/v1.23.0
