### ISSUE TITLE
storage: PostPolicyV4Options.SignBytes is not compatible with Credentials API

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-cloud-go#4752]
**Client**

Cloud Storage

**Environment**

Reproduced in local and remote environment

**Go Environment**

$ go version
go version go1.16.5 darwin/amd64

**Code**

The definition of `PostPolicyV4Options.SignBytes` and `SignedURLOptions.SignBytes` differ.

The input of `PostPolicyV4Options.SignBytes` is hashedBytes.

https://github.com/googleapis/google-cloud-go/blob/27c3ed022c83e598bacf34fbce47911985e0af35/storage/post_policy_v4.go#L221-L233
https://github.com/googleapis/google-cloud-go/blob/27c3ed022c83e598bacf34fbce47911985e0af35/storage/post_policy_v4.go#L310-L311

The input of `SignedURLOptions.SignBytes` is raw bytes.
https://github.com/googleapis/google-cloud-go/blob/27c3ed022c83e598bacf34fbce47911985e0af35/storage/storage.go#L699-L715

This difference seems to make `PostPolicyV4Options.SignBytes` incompatible with `projects.serviceAccounts.signBlob` of Service Account Credentials API.

**Code**

```go
email := os.Getenv("IMPERSONATE_SERVICE_ACCOUNT")
var signBytesFn func(b []byte) ([]byte, error)
var privateKey []byte

if email != "" {
	credCli, err := credentials.NewIamCredentialsClient(ctx)
	if err != nil {
		 panic(err)
	}
	defer credCli.Close()

	signBytesFn = func(b []byte) ([]byte, error) {
		 req := &credentialspb.SignBlobRequest{
			 Payload: b,
			 Name:    email,
		 }
		 resp, err := credCli.SignBlob(ctx, req)
		 if err != nil {
			 panic(err)
		 }
		 return resp.SignedBlob, err
	}
} else {
	cred, _ := google.FindDefaultCredentials(ctx)
	jwtConfig, _ := google.JWTConfigFromJSON(cred.JSON)
	email = jwtConfig.Email
	privateKey = jwtConfig.PrivateKey
}

opts := &storage.PostPolicyV4Options{
	GoogleAccessID: email,
	SignBytes:      signBytesFn,
	PrivateKey:     privateKey,
	Expires:        time.Now().Add(10 * time.Minute),
	Fields: &storage.PolicyV4Fields{
		 Metadata: map[string]string{},
	},
}

policy, err := storage.GenerateSignedPostPolicyV4(bucket, object, opts)
```

**Expected behavior**

Signed policy document are valid in both cases of `IMPERSONATE_SERVICE_ACCOUNT ` or `GOOGLE_APPLICATION_CREDENTIALS`.

**Actual behavior**

Signed policy document only valid in case of `GOOGLE_APPLICATION_CREDENTIALS`.

**Additional context**

Possible patch
https://github.com/googleapis/google-cloud-go/compare/storage/v1.16.1...apstndb:fix-policy-document

**Comment by BrennaEpp** [comment]
Hi @apstndb, thanks for filing this issue! We looked into this and are coming up with a solution for this. I'll update you later this week on the progress.

**Comment by BrennaEpp** [comment]
Update: I have a PR to implement a fix for this. To avoid breaking people depending on the current behaviour, we added an extra field to `PostPolicyV4Options` called `SignRawBytes` that is compatible with the credentials api and does not expect hashed bytes as input. 
Once that is merged and released, this code should work with the replacement of `SignBytes` -> `SignRawBytes`.
