### ISSUE TITLE
Bigtable: Getting incorrect result for valid RE2 regex pattern

### ISSUE THREAD

**Issue by modestlearner** [googleapis/google-cloud-go#4775]
I have a column named as **user:properties_string.properties.FIRSTNAME**

On using **user:properties_string.propertie*** regex i am not getting any result from the query whereas **user:properties_string.propertie.*** gives me a match.

Can someone please tell me is this intended or is it actually a bug.

**Comment by crwilcox** [comment]
The first regex, `user:properties_string.propertie*` would match
```
user:properties_string.propertie
user:properties_string.properti
user:properties_string.propertieeeeeeeeeee
```

The `*` is attached to the final `e`

The second will match anything that begins with `user:properties_string.propertie` as `*` is attached to `.` (any)
