### ISSUE TITLE
compute/metadata: binary size increase by 6.5Mb after the commit 81c6039503121f8da3de4f4cd957b8488a3ef620

### ISSUE THREAD

**Issue by valyala** [googleapis/google-cloud-go#4783]
We at [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) use `golang.org/x/oauth2/google` package [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6bc52fe41a7cf389606cb8e742f27d7b08f7a6c1/lib/promscrape/discovery/gce/api.go#L13) for obtaining metada from Google Compute Engine. The `golang.org/x/oauth2/google` package imports `cloud.google.com/go/compute/metadata` package. The commit 81c6039503121f8da3de4f4cd957b8488a3ef620 adds an additional dependency to this package - `github.com/googleapis/gax-go/v2`. This dependency increased VictoriaMetrics binary size by 6.5Mb after we upgraded `cloud.google.com/go` dependency from v0.93.3 to v0.94.1 in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/2814388891fe37b5b94628dd5f197ad0abb9c59c . This is more than 30% of binary size increase. We try hard keeping dependency bloat at minimum - see https://valyala.medium.com/stripping-dependency-bloat-in-victoriametrics-docker-image-983fb5912b0d . So it would be great if you could reduce the `compute/metadata` dependency size to pre-v0.94.0 sizes.

Possible solutions:
* Remove the dependency on `github.com/googleapis/gax-go/v2` from `compute/metadata` package. It is used for `gax.Sleep()` call, which can be easily embedded inside the `cloud.google.com/go` package.
* Restructure the `github.com/googleapis/gax-go/v2` package, so it doesn't include unneeded bloat by default when imported.

Related issue https://github.com/googleapis/google-cloud-go/issues/4642 .

**Comment by codyoss** [comment]
@valyala Thanks for reporting this. I agree that this seems like a lot of extra bloat for just adding some retries. I think we can do some refactoring here to make this package lighter again.

**Comment by codyoss** [comment]
This has been released under: https://github.com/googleapis/google-cloud-go/releases/tag/v0.95.0
