### ISSUE TITLE
spanner/spansql: support for JSON type in a table 

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#4906]
We got now an error message if we add a JSON type on a spanner table 
for example
CREATE TABLE table_name(
  column_name JSON,
  [other columns],
);

we got error :  got "JSON", want scalar type

more details concerning : https://cloud.google.com/spanner/docs/working-with-json

**Comment by rahul2393** [comment]
Thanks @geerttouquet for creating the issue, but can you help me answer few of the questions
* What version you are using to run the above DDL command.
* Is there any primary key column in the table. If possible can you share the complete DDL command which is failing.
Thanks

**Comment by geerttouquet** [comment]
* we are using cloud.google.com/go/spanner v1.25.0 
* in our table there is a primary key but it is not the JSON type
the original ddl is
CREATE TABLE resourceUnavailability (   resourceUnavailabilityId STRING(MAX) NOT NULL,   resourceName STRING(MAX) NOT NULL,   resourceType STRING(MAX) NOT NULL,   unavailabilityType STRING(MAX) NOT NULL,   otherTypeReason STRING(MAX) NOT NULL,   startTime TIMESTAMP NOT NULL,   endTime TIMESTAMP NOT NULL,   comment STRING(MAX) NOT NULL,   recurrence STRING(MAX) NOT NULL,   send_clientId STRING(MAX) NOT NULL,   send_clientVersion STRING(MAX) NOT NULL,   send_middleTierId STRING(MAX) NOT NULL,   send_middleTierVersion STRING(MAX) NOT NULL,   send_sessionId STRING(MAX) NOT NULL,   send_tenantId STRING(MAX) NOT NULL,   send_entityId STRING(MAX),   send_userId STRING(MAX) NOT NULL,   send_userRoleId STRING(MAX) NOT NULL,   send_version TIMESTAMP NOT NULL OPTIONS (     allow_commit_timestamp = true   ),   timings JSON, ) PRIMARY KEY(resourceUnavailabilityId)

**Comment by rahul2393** [comment]
Thanks, I tried running the above DDL using small golang script and it worked fine, can you share the sample code or gist to help replicate, also I tried running the DDL you shared in console spanner UI and it created the table fine.

**Comment by rahul2393** [comment]
@geerttouquet can you try this sample after setting the GOOGLE_APPLICATION_CREDENTIALS
https://gist.github.com/rahul2393/2effa25049363b8613639f0a484d379a
let me know if you get any errors.

**Comment by hengfengli** [comment]
@geerttouquet Are you running the above script against a spanner emulator? Currently, the emulator does not support JSON type yet.

**Comment by geerttouquet** [comment]
sorry for the misunderstanding ! 
It is with the spansql library
if you do spansql.ParseDDL("filename",<ddl statement>) , then you got the error got "JSON", want scalar type
