### ISSUE TITLE
pubsub: can't retrieve name from topic/sub config list method

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-go#4952]
#4607 adds the list config methods for topics/subscriptions. However, `TopicConfig` and `SubscriptionConfig` have no way to retrieve the name (path or ID) of the subscription. Other client (such as Pub/Sub Lite) uses the config with named values to create the resource, and doesn't take in a separate string in `CreateTopic/Subscription`. The proposed solution is to add additional methods `String()` and `ID()` to match `Topic` and `Subscription`. 

cc @mgabeler-lee-6rs

**Comment by mgabeler-lee-6rs** [comment]
Thanks for this, can confirm this made my use case run much quicker due to greatly reduced number of API calls needing to be made :grinning:
