### ISSUE TITLE
storage: Loading creds during NewClient breaks application without default creds

### ISSUE THREAD

**Issue by Xuanwo** [googleapis/google-cloud-go#4980]
**Client**

storage

**Environment**

Self-hosted CI (not on GCE)

**Go Environment**

$ go version
go 1.16

**Code**

```go
package gcs

import (
	"context"
	"net/http"
	"testing"

	gs "cloud.google.com/go/storage"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/option"
	htransport "google.golang.org/api/transport/http"
)

func TestClient(t *testing.T) {
	ctx := context.Background()

	var err error

	// We will have a costumed http client for timeout control.
	hc := http.DefaultClient
	hc.Transport, err = htransport.NewTransport(ctx, hc.Transport,
		// The cred could be loaded from file or JSON that user input.
		option.WithCredentials(&google.Credentials{}))
	if err != nil {
		t.Errorf("new transport error")
	}

	_, err = gs.NewClient(ctx, option.WithHTTPClient(hc))
	if err != nil {
		t.Errorf("new client failed: %v", err)
	}
}

func TestClientWithDuplicatedCredentials(t *testing.T) {
	ctx := context.Background()

	var err error

	// We will have a costumed http client for timeout control.
	hc := http.DefaultClient
	hc.Transport, err = htransport.NewTransport(ctx, hc.Transport,
		// The cred could be loaded from file or JSON that user input.
		option.WithCredentials(&google.Credentials{}))
	if err != nil {
		t.Errorf("new transport error")
	}

	// The trick way
	_, err = gs.NewClient(ctx, option.WithHTTPClient(hc), option.WithCredentials(&google.Credentials{}))
	if err != nil {
		t.Logf("init via set duplicated credentials could succeed")
	}
}
```

**Expected behavior**

Init with success.

**Actual behavior**

Output error:

```go
    utils_test.go:30: new client failed: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Additional context**

We met this error during our depandabot upgrade from 1.17 to 1.18: https://github.com/beyondstorage/go-service-gcs/pull/80

Our failed build log: https://teamcity.beyondstorage.io/buildConfiguration/Services_Gcs_IntegrationTests/934?showLog=934_67_67

![image](https://user-images.githubusercontent.com/5351546/137070654-c5b3df2a-513d-4dc3-9542-682a0be31059.png)

---

This problem is introduced by https://github.com/googleapis/google-cloud-go/pull/4604:

https://github.com/googleapis/google-cloud-go/blob/0f7457c6a9eff6465cfcf587aa8d60eb8b83dcaa/storage/storage.go#L134-L140

Do we have a better solution to handle the situation when user doesn't pass credential during `storage.NewClient`?

**Comment by tritone** [comment]
Thanks for reporting. @BrennaEpp is investigating this; @codyoss FYI as well.
