### ISSUE TITLE
pubsub: missing subscription in pull count view

### ISSUE THREAD

**Issue by jameshartig** [googleapis/google-cloud-go#5009]
**Client**

PubSub

**Environment**

CentOS 7 on GCE

**Go Environment**

$ go version
go version go1.17.2 linux/amd64
$ go env
N/A

**Code**

N/A

**Expected behavior**

I expect `cloud.google.com/go/pubsub/pull_count` it have a key of `subscription`.

**Actual behavior**

I don't see any subscription key. I am converting the opencensus metrics to prometheus metrics but I see a `subscription` key on other streaming metrics.

**Additional context**

I think `withSubscriptionKey` needs to be called in `newMessageIterator` like how it's called in `newPullStream`.

**Comment by hongalex** [comment]
Thanks for filing an issue and great catch. I think you're totally spot on (just missing the `withSubscriptionKey` call), just opened a PR to address this.

**Comment by jameshartig** [comment]
@hongalex thanks for the quick fix!
