### ISSUE TITLE
BigQuery golang SDK(v1.19.0) caused slower performance compared to the same query from BigQuery Console.

### ISSUE THREAD

**Issue by stevenzhang-support** [googleapis/google-cloud-go#5021]
**Client**
 It is a Golang service which use "cloud.google.com/go/bigquery v1.19.0" to call into bigquery.

**Environment**
An GCP Compute Engine instance that has Go app running 

**Go Environment**
N/A

$ go version
$ go env

**Code**
N/A
**Actual behavior**
Customer had run the same SQL query via a client using BigQuery Golang SDK v1.19.0 from here but the query was running 2x slower or longer than that if the same SQL was launched from BigQuery Console. I have checked internally that the actual execution time is 2x slower or longer for jobs launched by the Golang SDK to BigQuery. It looks the issue has nothing to do with the SDK until I found below:

The BigQuery Method uses this method to call BigQuery endpoint I guess:
*methodName: "google.cloud.bigquery.v2.JobService.InsertJob"*
But the SDK seems using another API method 
*methodName: "google.cloud.bigquery.v2.JobService.Query"*

Actually, we have three environments for SQL execution on  Big query.
1. By Using SDK(golang v1.19.0) which deployed in GCP EC2 node
2. Google Cloud BigQuery Console

1 will get slow query and 2 is faster (x2) query.

**The question given**
1) Whether or not it is intended, the SDK gives the same performance as a query directly made in the BigQuery console. 
2) Is the implementation of this SDK the same as what is implemented by BigQuery UI to call BigQuery endpoint?

**Expected behavior**
By Using SDK(golang v1.19.0) which deployed in GCP EC2 node run BigQuery job as fast as Google Cloud BigQuery Console

**Screenshots**
N/A

**Additional context**
N/A

**Comment by shollyman** [comment]
Any updates?

**Comment by stevenzhang-support** [comment]
I have explicitly asked customer to join a meeting for information gathering and share the code snippets. But customer has not responded to any of the request to move the case further. Please kindly wait or the case could be closed afterward due to inactivity.

**Comment by shollyman** [comment]
Closing this.  If there's actionable info in the future feel free to revisit the issue and we can reopen it.
