### ISSUE TITLE
compute/metadata: short description of bug

### ISSUE THREAD

**Issue by Deiz** [googleapis/google-cloud-go#5062]
**Client**

metadata

**Code**

e.g.
```go
package main

func main() {
	email, err := metadata.Get("/instance/service-accounts/default/email")
	if err != nil {
		// err should be non-nil if the metadata server is unreachable (i.e. not running on GCP)
	}

	// instead, we wind up here with a zero-value email
}
```

**Expected behavior**

When not running on GCP, or otherwise unable to reach the metadata server, this package's operations should fail.

**Actual behavior**

A nil error and zero-value string are returned.

This is occurring due to the fix for #4713.

**Comment by codyoss** [comment]
@Deiz Thanks for the report, I will take a look at your PR shortly!
