### ISSUE TITLE
bigquery: nil is returned when retrieving empty nested repeated value

### ISSUE THREAD

**Issue by yitzhaki** [googleapis/google-cloud-go#5066]
**Client**
local project

**Environment**
local environment

**Go Environment**
$ go version go1.16.4 windows/amd64

**Package**
cloud.google.com/go/bigquery v1.19.0

**Code**
```go
type A struct {
	*B
}

type B struct {
	C []*C
}

type C struct {
	ValueList []string
}

q := c.bqClient.Query(query)
q.Parameters = params
job, err := q.Run(c.ctx)
if err != nil {
	return err
}
status, err := job.Wait(c.ctx)
if err != nil {
	return err
}
if err := status.Err(); err != nil && !strings.Contains(err.Error(), "Already Exists") {
	return err
}
it, err = job.Read(c.ctx)
if err != nil {
	return err
}
if err != nil {
	return err
}
a := A{B: &B{}}
err = it.Next(&a)
```

**Expected behavior**
return [] as value of ValueList

**Actual behavior**
nil is returned, even that the insert value of ValueList  was []

**Comment by shollyman** [comment]
This seems to be similar to https://github.com/googleapis/google-cloud-go/issues/4950

**Comment by shollyman** [comment]
Closing this one in favor of #4950; it's effectively the same issue around how we represent empty vs nil array.
