### ISSUE TITLE
bigquery: Query job statistics for BI Engine

### ISSUE THREAD

**Issue by Dror88** [googleapis/google-cloud-go#5080]
**Is your feature request related to a problem? Please describe.**

I am trying to fetch the [BI Engine query job statistics](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#bienginestatistics) for my jobs, but it seems that this field does not exist on the [`QueryStatistics`](https://github.com/googleapis/google-cloud-go/blob/98779eba0f1f95b195aa6194210208767c169f5e/bigquery/job.go#L421) struct.

I can see it on the auto-generated googleapis/google-api-go-client [`JobStatistics2`](https://github.com/googleapis/google-api-go-client/blob/fff2ed2561e512e6e4356cc522ad8bb6c5883296/bigquery/v2/bigquery-gen.go#L4388) struct, but I can't get this info using the "cloud.google.com/go/bigquery" package.

**Describe the solution you'd like**

Is it possible to add the `BiEngineStatistics` field to `QueryStatistics`? Maybe [here](https://github.com/googleapis/google-cloud-go/blob/98779eba0f1f95b195aa6194210208767c169f5e/bigquery/job.go#L924)?

**Comment by shollyman** [comment]
Good spot.  I thought I'd done this at some point in the past, but past me is an unreliable witness.  This is pretty simple, will have a PR shortly.
