### ISSUE TITLE
pubsub: rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by barneystinson-sc** [googleapis/google-cloud-go#5091]
**PubSub**

**Alpine Docker on GKE**

**Go Environment**
go version = 1.17

**Package**
Version :- v1.17.0

I have a cron in my code which usually fetches messages from pubsub every 10 seconds and few times a day I get this error 

`rpc error: code = DeadlineExceeded desc = context deadline exceeded`

Settings 

`sub.ReceiveSettings.Synchronous = true
sub.ReceiveSettings.MaxOutstandingMessages = 1`

Is it a fatal issue?

**Comment by hongalex** [comment]
Hey, thanks for filing an issue. What is your publish rate? Is there a reason you're running a cron job to pull messages rather than leave the process running?

**Comment by mayank7parmar** [comment]
Hey Hongalex, so 
Reason to choose cron :- I am breaking a big large task into smaller tasks and publishing to pubsub and then a cron subscribes to it. Every task in pubsub takes some time so I add every task to an internal channel so if my previous task isn't completed it is still in pipeline. If my subscriber keeps running it may I might just fill the channel buffer too soon. Is there an issue to use a subscription in a cron?
Could it cause of the settings I chose?
`sub.ReceiveSettings.Synchronous = true sub.ReceiveSettings.MaxOutstandingMessages = 1`

**Comment by hongalex** [comment]
This doesn't really solve your issue, but I don't see the point of maintaining a channel if you have `MaxOutstandingMessages = 1`. This effectively guarantees that you won't pull more messages until you call `message.Ack()`. Using cron jobs probably isn't causing the `context deadline exceeded` error, but client instantiation/cleanup does have overhead so 

Also, how long is your processing time?

**Comment by mayank7parmar** [comment]
Publish rate is about 1 message per minute

**Comment by mayank7parmar** [comment]
@hongalex I don't wait for the message to be processed, my cron just pulls one msg from the pubsub and adds it to a channel. So basically I pull a message from pubsub ,add it to a channel and then acknowledge the message.
Can I maintain one single sub client and pass it to my cron that way I'll just have one single instance?
Also do you have any insights onto how it can occur?
I am sharing the code I have been using in the subscriber for your reference :- 


`err = sub.Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
		retries += 1
		err = json.Unmarshal(msg.Data, &message)
		if err != nil {
			logger.Println("Error while un-marshall", err.Error(), nil)
			msg.Nack() //Send a not acknowledged if the json can't be marshalled
		}
		_, err := redisRespository.Get(ctx, msg.ID)
		if err == nil || err == redis.ErrNil {
			err = redisRespository.SetNX(ctx, msg.ID, "true")
			if err != nil { 
				logger.Println("Error while setting key status", err.Error(), nil)
				slackService.RaiseSlackAlert(ctx, "Error while setting key status "+err.Error())
			} else {
				received += 1
				msg.Ack()
			}
		} else {
			logger.Println("Error while fetching from redis", err.Error(), nil)
			slackService.RaiseSlackAlert(ctx, "Error while fetching from redis "+err.Error())
		}
		messageList = append(messageList, message)
		if received >= 1 {
			cancel()
		}
		if retries >= 5 {
			cancel()
		}
	})
	if err != nil {
		logger.Println("Error while fetching messages from pubsub", err.Error(), nil)
		slackService.RaiseSlackAlert(ctx, "Error while fetching messages from pubsub"+err.Error())
	}
	for _, message := range messageList {
		if len(global.CONSUMER_CHAN) == cap(global.CONSUMER_CHAN) {
			return fmt.Errorf("CHANNEL FILLED") //add to channel
		}
		global.CONSUMER_CHAN <- message
	}
	//added to chanel
	if err != nil {
		return fmt.Errorf("Receive: %v", err)
	}
	return nil`

**Comment by hongalex** [comment]
To address your previous point
> If my subscriber keeps running it may I might just fill the channel buffer too soon

You should call `message.Ack()` after your message is added to your channel. That way, you can do away with the cron job entirely and allow flow control to work properly (process one message at a time).

**Comment by maxekman** [comment]
I have had some really hard to find issues with DeadlineExceeded errors when running a fairly parallel app with only one pubsub client on a 1 CPU VM. The reason is that the default connection pool size is set to GOMAXPROCS() (https://github.com/googleapis/google-cloud-go/blob/pubsub/v1.17.1/pubsub/pubsub.go#L136).

Very hard to track down which operations that takes longer time. Eventually some operation will hit the default 60 sec deadline. One solution is to manually set the GRPC connection pool size when creating the client:

`option.WithGRPCConnectionPool(2)`

**Comment by hongalex** [comment]
Closing as `Ack` and `Modack` RPC errors are now ignored, since these operations should be fire-and-forget anyway.
