### ISSUE TITLE
bigquery: Temporary table support

### ISSUE THREAD

**Issue by prochac** [googleapis/google-cloud-go#5107]
BigQuery SDK should support temporary tables. The same temp table as it can be created by following query, if SQL method is used:
```sql
CREATE TEMPORARY TABLE foo ( ... )
```
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement

But by SDK documentation we should create table with expiration time.
https://pkg.go.dev/cloud.google.com/go/bigquery#hdr-Datasets_and_Tables
That's the only part mentioning temporary tables.
But It is an old way to do it, since 2019, when CREATE TEMP TABLE was introduced.

I think it should be as a parameter for 
https://pkg.go.dev/cloud.google.com/go/bigquery#Table.Create
, so part of 
https://pkg.go.dev/cloud.google.com/go/bigquery#TableMetadata

Or am I missing something?

**Comment by shollyman** [comment]
I suppose it comes down to what you're doing with the temporary table.  If you're just wanting to do multi-statement queries, it's perfectly reasonable to supply SQL text for execution that's effectively a `CREATE TEMPORARY TABLE foo AS ....; SELECT blah FROM foo;`

If you want to issue multiple queries over time and not in the same script block, what you'll want to do is bind the statements to a session.  This capability was recently added via https://github.com/googleapis/google-cloud-go/pull/4754.

If your use case falls outside those patterns, perhaps you could describe what your intent is in a bit more detail?

**Comment by prochac** [comment]
We use temp table to run merge query to final table
```sql
MERGE the_table T USING temp_table S ON T.col = S.col WHEN NOT MATCHED THEN INSERT ...
```
Currently, we create a regular table for it.

**Comment by shollyman** [comment]
I'm still not sure what you're requesting.

A temporary table is ephemeral, and exists either for the lifetime of a single query job (or a query session).  It doesn't really make sense to create the temp table programmatically the same way you would a managed table by invoking `table.Create()` for example, as that's outside the scope of a query.

What are you envisioning that you would do with a temp table created via the the library rather than SQL?

**Comment by shollyman** [comment]
Closing this, as there's been no further interaction.  If you have more details, feel free to comment and we can reopen this issue.
