### ISSUE TITLE
bigquery/storage/managedwriter: mutex is copied over in managed_streamer.go

### ISSUE THREAD

**Issue by GlenDC** [googleapis/google-cloud-go#5120]
**Client**

`bigquery/storage/managewriter.Client`

**Environment**

N/A

**Go Environment**

N/A

**Code**

https://github.com/googleapis/google-cloud-go/blob/1f5aa78a4d6633871651c89a6d9c48e3409fecc5/bigquery/storage/managedwriter/managed_stream.go#L256

**Expected behavior**

Clone the request in a controlled manner.

**Actual behavior**

Clone by property values. This works fine for simple data structures,
but in this case it also means we are copying over a Mutex, which isn't something you want to do I imagine.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by shollyman** [comment]
Good spot, thanks!
