### ISSUE TITLE
spanner(spannertest): not failing as expected on queries with the wrong table hint key

### ISSUE THREAD

**Issue by kkoji** [googleapis/google-cloud-go#5129]
**Client**

spannertest

**Environment**

MacOS

**Go Environment**

$ go version
go version go1.17.2 darwin/amd64

$ go env
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kojimakazuya/Library/Caches/go-build"
GOENV="/Users/kojimakazuya/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kojimakazuya/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kojimakazuya/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/kojimakazuya/go/src/spanner-test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7z/_8ztjvm972bbhb5sssbfjty00000gn/T/go-build2806173167=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**
Given a schema like the following
```
CREATE TABLE Sample (
	ID STRING(MAX) NOT NULL,
	SecondID STRING(MAX) NOT NULL,
) PRIMARY KEY (ID)

CREATE INDEX SampleIndex ON Sample (SecondID)
```

Query

Specifies a non-existent index or hint key.
```
SELECT * FROM Sample@{FORCE_INDEX=SampleIndexA}
// or 
SELECT * FROM Sample@{A=B}
```

**Expected behavior**

The following error occurs when using the spanner emulator.
```
spanner: code = "InvalidArgument", desc = "Invalid hint value for: FORCE_INDEX hint: \"SampleIndexA\"."
```

```
spanner: code = "InvalidArgument", desc = "Unsupported hint: A."
```

**Actual behavior**

No error occurs in the environment using spannertest

**Comment by olavloite** [comment]
I'm not sure this is something that we in general would want to support. One of the known limitations of the emulator is that it does not return the same errors as real Cloud Spanner, and also that it does not necessarily verify the existence/validity of all names, such as table hint keys and index names. Implementing checks for this specific hint would of course be possible, but it would start a precedence that the emulator supports and checks all hints, and the list of possible hints is steadily growing.

@hengfengli What are your thoughts on this?

**Comment by hengfengli** [comment]
@olavloite I agree with you that this is not what we would like to support. We should not try to return everything same as the emulator does.

**Comment by hengfengli** [comment]
@kkoji Please check the above comment and I will close this issue. Let us know if you have further questions.
