### ISSUE TITLE
spanner: ToStruct can ignore the missing fields instead of throwing error

### ISSUE THREAD

**Issue by git-hulk** [googleapis/google-cloud-go#5131]
`ToStruct` requires all select result fields MUST be matched in the struct receiver and it would cause trouble when using the `*` as the select result. Does it make sense that ignore those fields
that didn't exist instead of throwing an error? Or create another new API to workaround?

Example 

DDL:
```sql
CREATE TABLE entries (
    key           STRING NOT NULL,
    value         STRING
) PRIMARY KEY (key)
```

Firstly, we have only two fields `key` and `value`:
```go
struct Entry {
  Key   string
  Value string
}

func GetValue(key string) (*Entry, error) {
  ...
  spannerCli.Single().Query(ctx, spanner.Statement {
      SQL: 'SELECT * FROM entries WHERE key=@key',
      Params: map[string]string{"key": key},
  ).Do(func(r *spanner.Row) error {
       entry := new(Entry)
       r.ToStruct(entry)
  )
}
```
Then we add a new field like `expire` into the table `entries`, the old code would NOT work, so
we should update the fields carefully that DDL shouldn't be updated before changing the code. Another workaround was to specify all fields explicitly but I don't think is a good way when the table fields grow.

I would be happy to send the PR to resolve this issue if it makes sense.

**Comment by hengfengli** [comment]
@rahul2393 Can you please take a look at this issue? Thanks.
