### ISSUE TITLE
How can I use the filter in "subnetworks.list" API of GCP Compute Engine?

### ISSUE THREAD

**Issue by MMichael-S** [googleapis/google-cloud-go#5155]
Hi Guys

I am a newbie for GoLang. 
I want to use the "subnetworks.list" API of GCP Compute Engine to get subnetworks by filter "network".

From the API reference page:
https://cloud.google.com/compute/docs/reference/rest/beta/subnetworks/list

When I use filter string -- network="https://www.googleapis.com/compute/beta/projects/prj-XXXXXX/global/networks/test-NNNN", I can get the correct response.

But when I use the same string in Go code, I got nothing response. My code as following.

Thank you for any replies and suggestions.

------------------------------------------------------------------------------

package main

import (
	"context"
	"fmt"
	"io"
	// "net/url"
	"os"

	compute "cloud.google.com/go/compute/apiv1"
	"google.golang.org/api/iterator"
	computepb "google.golang.org/genproto/googleapis/cloud/compute/v1"
)

func main() {
	listSubnet(os.Stdout, "prj-XXXXXX", "asia-southeast1")
}

func listSubnet(w io.Writer, projectID, region string) error {

	ctx := context.Background()

	SubnetworksClient, err := compute.NewSubnetworksRESTClient(ctx)

	if err != nil {
		return fmt.Errorf("NewSubnetworksRESTClient: %v", err)
	}

	defer SubnetworksClient.Close()

	filterCondition := `network="https://www.googleapis.com/compute/beta/projects/prj-XXXXXX/global/networks/test-NNNN"`

	println("filterCondition:", filterCondition)

	req := &computepb.ListSubnetworksRequest{
		Project: projectID,
		Region:  region,
		Filter:  &filterCondition,
		// TODO: Fill request struct fields.
		// See https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/compute/v1#ListSubnetworksRequest.
	}
	it := SubnetworksClient.List(ctx, req)

	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			// TODO: Handle error.
			return fmt.Errorf("Error: %v", err)
		}
		// TODO: Use resp.
		fmt.Fprintf(w, "- %s \n %s\n %s\n", *resp.Name, *resp.Network, resp.IpCidrRange)
		_ = resp
	}
	return nil
}

------------------------------------------------------------------------------

**Comment by MMichael-S** [comment]
Add a note
If I use the filter condition as following, I can get correct response.
filterCondition := `name="default"`

And I have tried the QueryEscape method. :(
// filterCondition := url.QueryEscape(`network="https://www.googleapis.com/compute/beta/projects/prj-mmdela-demo1/global/networks/test-oppo"`)

**Comment by MMichael-S** [comment]
I found that I made a ridiculous mistake. 
The API version is different, and the network name URL is different. 
Close this issue~

**Comment by Laotree** [comment]
just in case, someone faces my confusion:
if you want to get subnetworks by filtering "network".
you could consider as following
```
filter := fmt.Sprintf("network eq .*/%s", network)
iterator := client.List(context.Background(), &computepb.ListSubnetworksRequest{
	Project: project,
	Region:  region,
	Filter:  &filter,
})
```
