### ISSUE TITLE
logging: Add support for partialSuccess flag in entries.write request for oversized log entries

### ISSUE THREAD

**Issue by losalex** [googleapis/google-cloud-go#5156]
**Is your feature request related to a problem? Please describe.**
Today some requests might contain oversized log entries which cause entire write request to be dropped instead just of oversized log entries to be dropped (see [log-limits](https://cloud.google.com/logging/quotas#log-limits) for more information).
 **Describe the solution you'd like**
The solution for this problem is to add `partialSuccess` flag as described in [request-body](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write#request-body).
 **Describe alternatives you've considered**
Custom logic to truncate oversized entries could be implemented, but unfortunately truncating JSON structured log entries is complex and building generic solution for reduction JSON data is out of scope.

**Comment by minherz** [comment]
Duplicates #3824
