### ISSUE TITLE
artifactregistry: poor documentation on parent usage

### ISSUE THREAD

**Issue by mestrade** [googleapis/google-cloud-go#5164]
I'm currently trying to use the artifactregistry api but i can't figure out what to put in the parent field in a ListRepositoriesRequest.

Usually the parent is built with organizations/{id} and/or projects/{id} but in this case, all options are rejected.

The only value that seems to work is a project={id} but then the API return a permission denied error code with few information:

Tested with:

- "organizations/{id}/projects/{id}" <- failed saying that organizations is not expected here.
- "projects/{id}"  <- failed with code invalid argument and no details
- "project/{id} <- failed with code invalid argument and no details
- "project={id} <- failed with code permission denied (credentials have org admin and owner role)
- "{id} <- failed with code invalid argument and no details

Finally i don't know if this project={id} is the solution of if i miss something here but the documentation is helpless for me :/

Matthieu

**Comment by mestrade** [comment]
From the API documentation, it follows the pattern: /^projects\/[^/]+\/locations\/[^/]+$/ 
From the same API, it documents a projects.locations call that list all possible locations, which is not implemented in apiv1beta2.
Dunno if it's planned in a near future...

**Comment by codyoss** [comment]
Seems like you have came across the correct pattern: `projects/*/locations/*`. [Docs](https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta2/projects.locations.repositories/list)

The clients in this repo are for the most part auto generated. If you have a question about an API or have a feature request I suggest reaching out to one of the options listed on that products [support page](https://cloud.google.com/artifact-registry/docs/support). Hope that helps.
