### ISSUE TITLE
compute: BulkInsert of Confidential VMs not working

### ISSUE THREAD

**Issue by katexochen** [googleapis/google-cloud-go#5168]
Hi, I'm trying to create multiple confidential compute enabled instances with [BulkInsert](https://pkg.go.dev/cloud.google.com/go@v0.97.0/compute/apiv1#InstancesClient.BulkInsert), but the operation fails with

`VM_MIN_COUNT_NOT_REACHED: Requested minimum count of 1 VMs could not be created.` (Status code 503)

If I disable the confidential compute property the request works just fine. I can also create a single confidential VM with [Insert](https://pkg.go.dev/cloud.google.com/go@v0.97.0/compute/apiv1#InstancesClient.Insert) instead of BulkInsert.

Why isn't the creation working with BulkInsert?

Here is the BulkInsertInstanceResource I'm using in my request:
```go
computepb.BulkInsertInstanceResource{
		Count: proto.Int64(int64(1)),
		InstanceProperties: &computepb.InstanceProperties{
                        // if I remove this field, the request succeeds
			ConfidentialInstanceConfig: &computepb.ConfidentialInstanceConfig{
				EnableConfidentialCompute: proto.Bool(true),
			},
			Description: proto.String("xxxx"),
			Disks: []*computepb.AttachedDisk{
				{
					AutoDelete: proto.Bool(true),
					Boot:       proto.Bool(true),
					DeviceName: proto.String("xxxx-disk"),
					InitializeParams: &computepb.AttachedDiskInitializeParams{
						DiskSizeGb:  proto.Int64(10),
						SourceImage: proto.String("projects/xxxx/global/images/xxxx"),
					},
					Mode: computepb.AttachedDisk_READ_WRITE.Enum(),
				},
			},
			MachineType: proto.String("n2d-standard-2"),
			NetworkInterfaces: []*computepb.NetworkInterface{
				{
					Name: proto.String("xxxx"),
				},
			},
			Scheduling: &computepb.Scheduling{
				OnHostMaintenance: computepb.Scheduling_TERMINATE.Enum(),
			},
			ShieldedInstanceConfig: &computepb.ShieldedInstanceConfig{
				EnableIntegrityMonitoring: proto.Bool(true),
				EnableSecureBoot:          proto.Bool(true),
				EnableVtpm:                proto.Bool(true),
			},
		},
		NamePattern: proto.String("instance-###"),
	}
```
Thanks in advance.

**Comment by codyoss** [comment]
Hey, I am not super familiar with this part of the compute client. I would suggest reaching out to one of the links on the [Compute Support Page](https://cloud.google.com/compute/docs/support) for question related to the API. Hope that helps.
