### ISSUE TITLE
compute: unable to resize instance group to 0

### ISSUE THREAD

**Issue by matihost** [googleapis/google-cloud-go#5174]
https://github.com/googleapis/google-cloud-go/blob/main/compute/apiv1/instance_group_managers_client.go#L1301

When size is 0, the size parameter is not added to HTTP param - and server returns 400 bad request - leading to unability to resize intance group to 0.

The gcloud cli works:
```
gcloud compute instance-groups managed resize NAME  --zone=ZONE --size=0
```

**Comment by codyoss** [comment]
cc @noahdietz WDYT? A bug perhaps?

**Comment by noahdietz** [comment]
Opened https://github.com/googleapis/gapic-generator-go/issues/819 to track the bug fix.

**Comment by noahdietz** [comment]
https://pkg.go.dev/cloud.google.com/go@v0.99.0 should have the fix https://github.com/googleapis/google-cloud-go/blob/5563382a8560ea851e6d54962ea71165b2807b24/compute/apiv1/instance_group_managers_client.go#L1297-L1302
