### ISSUE TITLE
compute/apiv1/firewall_policies_client.go: invalid operation: req.ParentId != nil (mismatched types string and nil)

### ISSUE THREAD

**Issue by regnaio** [googleapis/google-cloud-go#5176]
I tried updating my `go.mod` packages by running:
`go get -u ./...`

Received the error message:
```bash
go get -u ./...

# cloud.google.com/go/compute/apiv1
/go/pkg/mod/cloud.google.com/go@v0.97.0/compute/apiv1/firewall_policies_client.go:684:32: invalid operation: req.ParentId != nil (mismatched types string and nil)
/go/pkg/mod/cloud.google.com/go@v0.97.0/compute/apiv1/firewall_policies_client.go:869:32: invalid operation: req.ParentId != nil (mismatched types string and nil)
```

On `go1.17.3 linux/amd64`

For your reference, here are the source code lines mentioned in the error:
https://github.com/googleapis/google-cloud-go/blob/main/compute/apiv1/firewall_policies_client.go#L684-L689
```go
if req != nil && req.ParentId != nil {
    params.Add("parentId", fmt.Sprintf("%v", req.GetParentId()))
}
if req != nil && req.RequestId != nil {
    params.Add("requestId", fmt.Sprintf("%v", req.GetRequestId()))
}
```

**Comment by noahdietz** [comment]
@codyoss the `parent_id` field was actually required by the API, so they removed the proto3 `optional` label that made it a pointer. The client needs to be regenerated because the go-genproto stub is now just a `string` (no longer a `*string`).

**Comment by rosmo** [comment]
A workaround for now: `go get google.golang.org/genproto@v0.0.0-20211102202547-e9cf271f7f2c`

**Comment by codyoss** [comment]
This should now be fixed in the most recent release of compute. Closing.
