### ISSUE TITLE
Bigquery: How to get bigquery query result?

### ISSUE THREAD

**Issue by layla004** [googleapis/google-cloud-go#5191]
Hi, I want to ask a question, I am trying this query by following the documentation:
```
q := client.Query(`
    select * from project.dataset.table WHERE date(_PARTITIONTIME) >= '2021-12-03' order by _PARTITIONTIME desc LIMIT 1
`)
it, err := q.Read(ctx)
if err != nil {
    // TODO: Handle error.
}

for {
    var values []bigquery.Value
    err := it.Next(&values)
    if err == iterator.Done {
        break
    }
    if err != nil {
        // TODO: Handle error.
    }
    fmt.Println(values)
}
```

But I get `values` as below:
`[test <nil> <nil> <nil> <nil> heloo <nil> <nil> <nil> <nil>]`
Actually I need to get result with column name information too, for example: 
```
[
 {
   "column_name": "column 1",
   "value": "test",
},
{
   "column_name": "column 2",
   "value": null,
},
.......
]
```

Is it possible to get query result like that without creating a struct?
Please help, thank you ☺️

**Comment by shollyman** [comment]
I need to improve this documentation, as dynamic processing of query results can be a bit more complex than the static struct form.  The short a

Consider this iterator loop:
```
for {
  var row []bigquery.Value
  err := it.Next(&row)
  if err == iterator.Done {
    break
  }
  if err != nil {
    return err
  }
  // TODO: process row slice
}
```

In this example, the row is essential a slice of `bigquery.Value` types, which is essentially the empty interface.  To do something with specific values, you can use a type switch.  It's also worth pointing out that the schema is also present on the iterator, so if you want to walk the schema vs the row slice directly that's possible.

I'll see about putting together a more complete type switch example.

**Comment by layla004** [comment]
Thanks @shollyman
