### ISSUE TITLE
logging: memory leak at high frequency logging

### ISSUE THREAD

**Issue by filip-johansson-ingka** [googleapis/google-cloud-go#5204]
We have an issue when using the go logging library. We are experiencing a very high memory consumption, potentially a leak, when writing logs at a high frequency.
We first observed this issue in one of our Go services hosted in Cloud Run. When receiving a high amount of requests (6000rps+) we can see the memory utilisation increasing until the instances runs our of allocated memory. 
We write one log entry per request. With the logging disabled the service handles the same load consuming around 10-20% of the total memory.

We can replicate this behaviour locally by running a simple for-loop that logs on each iteration. Eventually the client OnError()-function is invoked with the following error: "bundler reached buffered byte limit".

We've tried changing the values of:
[EntryCountThreshold()](https://pkg.go.dev/cloud.google.com/go/logging#EntryCountThreshold)

[ConcurrentWriteLimit()](https://pkg.go.dev/cloud.google.com/go/logging#ConcurrentWriteLimit)

This doesn't mitigate the problem. However when adding a 10ms sleep on each iteration the problem is gone.

Package version: v1.4.2

Container image: golang:1.17.3-alpine3.14

Local environment/version: go1.17.2 darwin/amd64

Sample code to reproduce the issue:

```
package main

import (
	"context"
	"log"
	"sync"

	glogging "cloud.google.com/go/logging"
	"github.com/google/uuid"
)

func onInternalStackdriverExporterError(err error) {
	log.Println(err)
}

const numOfWorkers = 1

func main() {
	wg := sync.WaitGroup{}
	ctx := context.Background()

	c, _ := glogging.NewClient(ctx, "gcp-project-id")

	c.OnError = onInternalStackdriverExporterError

	logr := c.Logger("log-load-test")

	for i := 0; i < numOfWorkers; i++ {
		wg.Add(1)
		go doSomething(logr)
	}

	wg.Wait()
}

func doSomething(logger *glogging.Logger) {
	for {
		//time.Sleep(10 * time.Millisecond) //running this Sleep mitigates the memory leak.

		e := glogging.Entry{
			Severity: glogging.Severity(100),
			Payload:  uuid.New().String(),
		}

		logger.Log(e)
	}
}
```

**Comment by minherz** [comment]
@filip-johansson-ingka thank you for reporting. The logging library (in Go) does not support batching multiple write log requests. In the reported rate (6000rps+) you exceed the [write API quota](https://cloud.google.com/logging/quotas#api-limits). We will look into the problem to handle errors correctly.
At the moment we cannot propose a better mitigation than reducing the amount of write calls or aggregating the logs before sending them.
we will update you about the progress.

**Comment by filip-johansson-ingka** [comment]
@minherz Thank you for your feedback. We'll tune our logging.

**Comment by andreas-hakansson-ingka** [comment]
@minherz While batch writing would be great, I also feel that the logging library should not be allowed to uncontrollably consume memory if it is able to send entries to the Cloud Logging API. Failure in a logging library should not propagate into the calling service and potentially cause business issues due to things like OOM killing services. Ideally, the logging library should support something like a fixed-size buffer and/or a maximum TTL that each entry is allowed to stay in the buffer before it is purged. Together these features would help ensure that it the logging library is minimal impact on the calling service in case of failure.

Thoughts on this?

**Comment by minherz** [comment]
@andreas-hakansson-ingka the [message](https://github.com/googleapis/google-api-go-client/blob/0f5a4b28d8482a3edf3ecd5331c9a1f1120574b5/support/bundler/bundler.go#L41) you mention is returned by the [bundler](https://github.com/googleapis/google-api-go-client/blob/0f5a4b28d8482a3edf3ecd5331c9a1f1120574b5/support/bundler/bundler.go#L244) which can be configured in the library. The default is 1GiB but it can be updated using https://github.com/googleapis/google-cloud-go/blob/5a2ed6b2cd1c304e0f59daa29959863bff9b5c29/logging/logging.go#L322

I cannot deduce the total volume of the logs you try to ingest in your scenario. However, clearly the total size of the memory used for the logs exceed the limit which results in the error. According to your description the scenario works when you relax the ingestion by introducing small delays between log ingestions.

Please, try to setup the limit to 2 GiB and see if it resolves the problem. So far it does not seem as a memory leak but the controlled error that is returned when the currently bundled log entries hit the predefined threshold.
