### ISSUE TITLE
kms: locations.list

### ISSUE THREAD

**Issue by wrighbr** [googleapis/google-cloud-go#5205]
**Describe the solution you'd like**
Make it possible to list all locations of kms within the golang sdk. This possible to  via the api see below link it would be nice have this within the sdk as well

https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations/list

**Comment by codyoss** [comment]
@noahdietz With the future plugin work do we plan to generate these generic methods?

**Comment by noahdietz** [comment]
Yep, this will launch at some point in H1 '22 I think. This kind of request is why we did it* so thanks @wrighbr :)

\* "it" being generation of the common "mixed in" services like IAM, Locations, and Operations on Product API clients.

**Comment by codyoss** [comment]
Cool, I will leave this issue open for tracking.

**Comment by joseph-cobhams-sp** [comment]
@noahdietz Is there an ETA on when this could be available?

**Comment by noahdietz** [comment]
Hey thanks for following up on this. We can definitely support generation of this now. Need to update some configs, execute regen, then cut a release. @codyoss if everything went perfectly, when do you think we'd be able to feasibly cut a release of this client?

**Comment by codyoss** [comment]
This seems reasonable to me. This may still take a few weeks to get rolled out, but we will investigate getting this supported.

**Comment by noahdietz** [comment]
Submitting the config upstream today. The next regen/release should contain the desired APIs.

**Comment by codyoss** [comment]
I believe this is now fixed. Closing.
