### ISSUE TITLE
spanner/spansql: v1.28.0 generated columns

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#5209]
**Client**
golang
**Environment**

**Go Environment**
$ go version go version go1.16.9 

**Code**

sql code that can be parsed by cloudspanner but it gives an error on spansql

CREATE TABLE test (
	patientId STRING(MAX) NOT NULL,
	starttime TIMESTAMP NOT NULL,
	cetDate DATE AS (EXTRACT(DATE FROM startTime AT TIME ZONE "CET")) STORED,
) PRIMARY KEY (patientId);

_, err := spansql.ParseDDL("filename", test.sql) gives following error 
ParseDDL("CREATE TABLE test (\n\tpatientId STRING(MAX) NOT NULL,\n\tstarttime TIMESTAMP NOT NULL,\n\tcetDate DATE AS (EXTRACT(DATE FROM startTime AT TIME ZONE \"CET\")) STORED,\n) PRIMARY KEY (patientId);"): filename:4: got "FROM", want ")" or ","

**Comment by rahul2393** [comment]
Thanks for opening the request @geerttouquet I was able to replicate the issue, will create a PR but from the documentation of https://cloud.google.com/spanner/docs/reference/standard-sql/date_functions#extract return type of Extract is always Int64 and we cannot extract Date from a Date
