### ISSUE TITLE
containeranalysis: connection is not shared

### ISSUE THREAD

**Issue by thepwagner** [googleapis/google-cloud-go#5217]
**Client**

Grafeas

**Go Environment**

`go version go1.17.5 darwin/arm64`

**Expected behavior**

Documentation on `containeranalysis.Client.GetGrafeasClient()`  states "Calling Close on either the grafeas or containeranalysis client will close the shared connection in both." [source](https://github.com/googleapis/google-cloud-go/blob/2c664a69a3dc63763b1c76eec2c771daf0c9b301/containeranalysis/apiv1/container_analysis_client.go#L114-L116).

I expect calling close on either client to close the shared connection in both.

**Actual behavior**

`containeranalysis.NewClient()` initializes a connection pool, but it is not shared with `grafeasclient` [source](https://github.com/googleapis/google-cloud-go/blob/2c664a69a3dc63763b1c76eec2c771daf0c9b301/containeranalysis/apiv1/container_analysis_client.go#L93-L100).
`grafeas.NewClient()` initializes an independent connection pool [source](https://github.com/googleapis/google-cloud-go/blob/2c664a69a3dc63763b1c76eec2c771daf0c9b301/grafeas/apiv1/grafeas_client.go#L121-L124).

**Additional context**

I think the comment should be removed, or the connection pool between these clients should be shared.

**Comment by codyoss** [comment]
@thepwagner Thanks for pointing this out. As far as I can see this has never been a true statement I will update code/docs accordingly.
