### ISSUE TITLE
cloud.google.com/go: unable to get

### ISSUE THREAD

**Issue by michael-stevens** [googleapis/google-cloud-go#5280]
**Client**

go get

**Environment**

Debian in linux container on chrome os.

**Go Environment**

mstevens@penguin:~/test$ go version
go version go1.17.5 linux/amd64
mstevens@penguin:~/test$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mstevens/.cache/go-build"
GOENV="/home/mstevens/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mstevens/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mstevens/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mstevens/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2912778342=/tmp/go-build -gno-record-gcc-switches"

**Code**

In empty directory do this:

```
mstevens@penguin:~/test$ go mod init example.com/test
go: creating new go.mod: module example.com/test
mstevens@penguin:~/test$ go get cloud.google.com/go
go get: cloud.google.com/go@v0.100.2 requires
        cloud.google.com/go/compute@v0.1.0: unrecognized import path "cloud.google.com/go/compute": reading https://cloud.google.com/go/compute?go-get=1: 404 Not Found
```

**Expected behavior**

go get succeeds

**Actual behavior**

go get fails with 404 error on compute module.

**Additional context**

Started after attempting to update to latest release with `go get -u`.

**Comment by codyoss** [comment]
Thanks for the report, the dependency should now resolve as of about ~20 min ago. Sorry for any issues this caused.

https://pkg.go.dev/cloud.google.com/go/compute
