### ISSUE TITLE
Trying to use the gocloud library and I got a compiling error because of this line.

### ISSUE THREAD

**Issue by t3r-cni** [googleapis/google-cloud-go#5304]
https://github.com/googleapis/google-cloud-go/blob/132904a061809ba7117c51e8a8000f1adac34e48/storage/storage.go#L1476

../../pkg/mod/cloud.google.com/go/storage@v1.16.1/storage.go:1416:53: o.GetCustomerEncryption().GetKeySha256 undefined (type *"google.golang.org/genproto/googleapis/storage/v2".Object_CustomerEncryption has no field or method GetKeySha256)

**Comment by codyoss** [comment]
Please try updating both your storage version and genproto to latest and this should be resolved!

**Comment by t3r-cni** [comment]
`go get -u all 
`
updated everything I needed.
