### ISSUE TITLE
Support Spot VMs

### ISSUE THREAD

**Issue by regnaio** [googleapis/google-cloud-go#5317]
EDIT: After studying this issue more, I think it can be summarized as:

Will `google-cloud-go` gain support for `container/v1beta1`?

i.e., would https://github.com/googleapis/google-api-go-client/tree/main/container/v1beta1 be integrated into https://github.com/googleapis/google-cloud-go/tree/main/container?

---

https://cloud.google.com/spot-vms

Currently, I only see Preemptible VMs supported in google-cloud-go, but not Spot VMs

https://pkg.go.dev/google.golang.org/api/container/v1beta1 supports `Spot` under `NodeConfig` as shown below:

```
...
// Spot: Spot flag for enabling Spot VM, which is a rebrand of the
// existing preemptible flag.
Spot bool `json:"spot,omitempty"`
...
```

However, `Spot` is not seen in either https://pkg.go.dev/cloud.google.com/go/container@v1.0.0/apiv1 or https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20220106181925-4b6d468c965f/googleapis/container/v1

Maybe this is because https://pkg.go.dev/cloud.google.com/go/container@v1.0.0/apiv1beta1 (i.e. v1beta1) does not exist?

Thank you for your help!

**Comment by codyoss** [comment]
Hey, these clients are auto-generated from the source of truth found [here](https://github.com/googleapis/googleapis). Looking at the container protos I don't see any mention of Spot. It may be the protos are out of date. Would you mind opening up a bug on the container service teams issue tracker asking about this feature. [Issue Tracker](https://issuetracker.google.com/issues/new?component=187077&template=0). Thanks.

**Comment by regnaio** [comment]
Thank you. I just tried opening up a bug on the container service teams issue tracker
https://issuetracker.google.com/u/1/issues/213863133
