### ISSUE TITLE
pubsub: fake server does not handle deadletters and retry counts

### ISSUE THREAD

**Issue by yottta** [googleapis/google-cloud-go#5319]
**Client**

PubSub

**Go Environment**

go version go1.16.6 darwin/amd64

**Description**

The PubSub library offers a testing server that is still in beta and therefore does not have all the functionalities.
This ticket is about improving the PubSub testing server to handle correctly Deadletters and retries.

**Expected behavior**

When a Subscription is created with a DeadLetter and retries configuration, an unacked message is received from the subscription only as many times as specified in the retries configuration.

**Actual behavior**

When a Subscription is created with a DeadLetter configuration, an unacked message is never sent to deadletter and is received from the subscription indefinitely.

**Comment by yottta** [comment]
Fixed by #5320

**Comment by burdzwastaken** [comment]
@yottta could the PR #5374 or #5463 get merged soon so this functionality is available? will help with our testing strategy. thank you so much

**Comment by burdzwastaken** [comment]
sorry @yottta had a brainfart & didn't realize you were the contributor. thanks for the approval anyway <3
