### ISSUE TITLE
spanner: Imports "testing"

### ISSUE THREAD

**Issue by aaronbee** [googleapis/google-cloud-go#5326]
spanner v1.29.0 imports the standard library "testing" package: https://github.com/googleapis/google-cloud-go/blob/spanner/v1.29.0/spanner/stats.go#L22

This adds an unwanted dependency to programs that import the spanner module. Imports of "testing" should be limited to _test.go files or test packages that don't get imported by production packages.

**Expected behavior**

```
$ go list -deps cloud.google.com/go/spanner | grep '^testing$'
```
should have an empty result

**Actual behavior**

```
$ go list -deps cloud.google.com/go/spanner | grep '^testing$'
testing
```

**Additional context**

Added in this PR: https://github.com/googleapis/google-cloud-go/pull/5199

**Comment by codyoss** [comment]
Thanks @aaronbee! I have opened a PR to fix this.
