### ISSUE TITLE
iamadmin: failing queries when going through proxy

### ISSUE THREAD

**Issue by joelddiaz** [googleapis/google-cloud-go#5329]
**Client**

go/iam/admin/apiv1

**Environment**

Local CLI golang binary running on Fedora

**Go Environment**

[jdiaz@minigoomba test (master *%)]$ go version
go version go1.17.3 linux/amd64
[jdiaz@minigoomba test (master *%)]$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jdiaz/.cache/go-build"
GOENV="/home/jdiaz/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jdiaz/.gvm/pkgsets/go1.17.3/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jdiaz/.gvm/pkgsets/go1.17.3/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jdiaz/.gvm/gos/go1.17.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jdiaz/.gvm/gos/go1.17.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jdiaz/projects/mygo/src/github.com/joelddiaz/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1003375082=/tmp/go-build -gno-record-gcc-switches"
[jdiaz@minigoomba test (master *%)]$ 

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"
	"log"

	iamadmin "cloud.google.com/go/iam/admin/apiv1"
	iamv1 "google.golang.org/api/iam/v1"
	iamadminpb "google.golang.org/genproto/googleapis/iam/admin/v1"

	"golang.org/x/oauth2/google"
	compute "google.golang.org/api/compute/v1"
	"google.golang.org/api/option"
)

func main() {

	creds, err := google.FindDefaultCredentials(context.TODO(), compute.CloudPlatformScope)
	if err != nil {
		log.Fatalf("error geting default creds: %v", err)
	}

	projectName := creds.ProjectID
	fullProjectResourceName := fmt.Sprintf("//cloudresourcemanager.googleapis.com/projects/%s", projectName)

	fluentIAMClient, err := iamv1.NewService(context.TODO(), option.WithCredentials(creds))
	if err != nil {
		log.Fatalf("error setting up flient IAM client: %+v\n", err)
	}

	fluentPermTest := &iamv1.QueryTestablePermissionsRequest{
		FullResourceName: fullProjectResourceName,
	}
	_, err = fluentIAMClient.Permissions.QueryTestablePermissions(fluentPermTest).Do()
	if err != nil {
		log.Fatalf("error during fluent QueryTestablePermissions(): %+v\n", err)
	}

	otherIAMClient, err := iamadmin.NewIamClient(context.TODO(), option.WithCredentials(creds))
	if err != nil {
		log.Fatalf("error setting up other IAM client; %+v\n", err)
	}

	otherPermTest := &iamadminpb.QueryTestablePermissionsRequest{
		FullResourceName: fullProjectResourceName,
	}
	_, err = otherIAMClient.QueryTestablePermissions(context.TODO(), otherPermTest)
	if err != nil {
		log.Fatalf("error during other QueryTestablePermissions(): %+v\n", err)
	}
}

```

**Expected behavior**

Using QuertyTestablePermissions() using both the google-api-go-client and the google-cloud-go packages should work.

**Actual behavior**

When run without setting a proxy, the entire command runs to completion without error. When setting an HTTPS_PROXY env var, only the first QueryTestablePermissions() call works. The second QueryTestablePermisions() call fails with:
```
[jdiaz@minigoomba test (master *%)]$ export GOOGLE_APPLICATION_CREDENTIALS=~/gcp-creds.json
[jdiaz@minigoomba test (master *%)]$ env | grep HTTPS
[jdiaz@minigoomba test (master *%)]$ ./bin/mytest 
[jdiaz@minigoomba test (master *%)]$ echo $?
0
[jdiaz@minigoomba test (master *%)]$ export HTTPS_PROXY=https://PROXYUSER:PROXYSECRET@squid.mydomain.com:3130
[jdiaz@minigoomba test (master *%)]$ ./bin/mytest 
2022/01/11 09:12:55 error during other QueryTestablePermissions(): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing reading server HTTP response: read tcp 192.168.86.52:56604->3.87.55.230:3130: read: connection reset by peer"
[jdiaz@minigoomba test (master *%)]$ echo $?
1
```
**Additional context**

The HTTPS_PROXY can work if you set it to a non-https proxy URL, but consistently fails (only for the google-cloud-go package) when using an https proxy URL.

```
[jdiaz@minigoomba test (master *%)]$ # USE PORT 3128 FOR NON-HTTPS PROXY URL
[jdiaz@minigoomba test (master *%)]$ export HTTPS_PROXY=http://PROXYUSER:PROXYSECRET@squid.mydomain.com:3128
[jdiaz@minigoomba test (master *%)]$ ./bin/mytest 
[jdiaz@minigoomba test (master *%)]$ echo $?
0
```

The squid software is an up-to-date version from Fedora 35 (squid-5.2-1.fc35.aarch64). The squid proxy is using self-signed certificates. The root CA for the squid server is trusted by the host where the binary is running. The important bits of the squid.conf file look like:

```
auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated

http_port 3128

https_port 3130 cert=/etc/squid/certs/squid.mydomain.com.crt key=/etc/squid/certs/squid.mydomain.com.key cafile=/etc/squid/certs/rootCA.crt
```

FWIW, it is not only the QueryTestablePermissions() call that fails. I've seen ListServiceAccounts() fail, but in that case it just hangs and doesn't provide any useful output.

Also, just ran a `go get -u` and rebuilt everything before hitting submit, and confirmed the failure is still occurring.

**Comment by codyoss** [comment]
I will have a deeper look at this issue tomorrow. But the difference between these two clients is the one that works(other repo) uses JSON over HTTP. The clients in this repo are gRPC based. Here is a related gRPC issue around proxies with some hints: https://github.com/grpc/grpc-go/issues/2243

**Comment by codyoss** [comment]
Sorry, this slipped off my radar, were you able to find a solution with the above mentioned issue?

**Comment by joelddiaz** [comment]
@codyoss no, I was not able to get it working. FWIW, I'm not doing any low-level grpc calls. All the grpc stuff is from the dependencies in this repo.
My HTTPS_PROXY env var is of the form HTTPS_PROXY="https://username@password:dns.for.proxy.com:HTTPS_PROXY_PORT"

**Comment by akhil-rane** [comment]
@codyoss do we have any update on this issue?

**Comment by codyoss** [comment]
Sorry forgot to ping back here. This is not an issue with these libraries but a configuration issue. The second client in this example uses grpc and proxying with auth works a little different than a standard HTTP/JSON client. This will likely require you to configure a custom dialer. For some info on that please see:

- https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md#custom-proxy
- https://github.com/grpc/grpc-go/issues/2422

The relevant client options you will need is: https://pkg.go.dev/google.golang.org/api/option#WithGRPCDialOption

You will want to configure your own gRPC dialer with /w proxy info set up.

Hope that helps. Closing this issue out but please feel free to message back if you are still having issues.
