### ISSUE TITLE
storage: support user-defined headers passed via the context.Context metadata

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#5385]
Today, the JSON client surface requires that an entire custom HTTPClient be provided to have an end-user's own request headers included in API calls. This is a cumbersome experience. gRPC clients support "headers" via the context.Context metadata of the context provided at call time to ever method. This is a straight forward and clean way to support user-specified header injection. We should consider adding support for it at the client level in the same fashion.

cc: @tritone

**Comment by tritone** [comment]
This is now supported at the apiary layer via the callctx package. I add support for XML storage methods and add docs to the storage package describing how to do this in a PR here: #8294
