### ISSUE TITLE
logging: `SpanID` is not set on log entry after being pulled from `X-Cloud-Trace-Context` header

### ISSUE THREAD

**Issue by quentin-fox** [googleapis/google-cloud-go#5388]
**Client**

logging

**Environment**

Cloud Run

**Go Environment**

```
$ go version
go version go1.17 darwin/arm64

$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/quentin/Library/Caches/go-build"
GOENV="/Users/quentin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/quentin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/quentin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/quentin/.asdf/installs/golang/1.17/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/quentin/.asdf/installs/golang/1.17/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2q/hq40f1l513162yt5fz31h5w40000gn/T/go-build3652117571=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Expected behavior**

When a `http.Request` is attached to the log entry through `logging.Entry.HTTPRequest.Request`, if there is a valid span ID encoded in the `X-Cloud-Trace-Context` header, it should be added to the `logging.Entry.SpanID` struct field.

**Actual behavior**

The span ID is not attached.

If this is not intentional, the offending line of code is here:

https://github.com/googleapis/google-cloud-go/blob/f9608d4622c56362b2ed0a5845b8fe27f81995aa/logging/logging.go#L843

The comparator there should be `!=` instead of `==`. Right now, it's setting the value of `e.SpanID` only when `spanID` is an empty string, which is either a no-op, or potentially overwriting existing data.

I'm pretty sure that this isn't the intended behaviour - I checked in the nodejs logging client, and found a similar set of code, except it checks for truthiness of the parsed span ID, rather than falsiness like in this library.

https://github.com/googleapis/nodejs-logging/blob/c8d499b216c4bbc868f6817425495998b72a19c4/src/entry.ts#L233

If this isn't intentional, I'm happy to submit a PR and fix this!

If not, I think it would benefit the library if there was a small comment explaining why this choice was made.

Thanks!

**Comment by minherz** [comment]
Hi,
thank you for submitting your question. Without a sample application it is hard for us to validate the problem. About your claim 

> Right now, it's setting the value of e.SpanID only when spanID is an empty string

Perhaps you misread the code. The code populates `e.Trace` and `e.SpanId` **only** if they do not already have values. You can see the validation in Line 834 for `e.Trace` and Line 843 for `e.SpanId`:
https://github.com/googleapis/google-cloud-go/blob/f9608d4622c56362b2ed0a5845b8fe27f81995aa/logging/logging.go#L834-L845

There is no code that validates `spanID` for being empty. If you see the described behavior in your application where the log entry fields `Trace` and `SpanID` are empty and they do not get populated, please provide the version of the client library and Go that you use together with a simple application that reproduce the problem.

Thank you

**Comment by quentin-fox** [comment]
Wow that's 100% right. My bad! I think I may have something wrong in my config then, I'll reopen a separate issue if I find that the issue persists.
