### ISSUE TITLE
debugger: is not a submodule

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#5453]
**Client**

Debugger 

**Expected behavior**

https://pkg.go.dev/cloud.google.com/go#section-sourcefiles lists `debugger` as a module.

**Actual behavior**

https://pkg.go.dev/cloud.google.com/go#section-sourcefiles lists `debugger` as a subdirectory.

**Additional context**

https://github.com/googleapis/google-cloud-go/tree/main/debugger/ appears to be missing `go.mod` and `go.sum` files.

**Comment by codyoss** [comment]
At this time there is no intention of making this a module. The code here will eventually be removed as it does not work with modern versions of Go.
