### ISSUE TITLE
Bigquery: why there is flow control in managed write api?

### ISSUE THREAD

**Issue by richzw** [googleapis/google-cloud-go#5479]
We notice there is [flow control logic](https://github.com/googleapis/google-cloud-go/blob/main/bigquery/storage/managedwriter/flow_controller.go) in bigquery managed write API. As we all know. there is also flow control logic in gRPC streaming mode which is based on http2 flow control.

We want to know why there is additional flow control in managed write API of bigquery?

**Comment by shollyman** [comment]
Happy to add a few notes.

http2 flow control is mostly about signalling pushback between message sender and receiver.  The AppendRows contract uses a bidi stream, so both endpoints end up as both senders and receivers.  Append requests are paired 1:1 with responses, so the flow controller is a higher level abstraction that has awareness of the end-to-end flow and manages the API-level abstraction.

As an aside, there's some work in flight to address a performance issue with the current impl (currently using an unbuffered channel rather than a buffered one), which when addressed should improve performance.

**Comment by richzw** [comment]
@shollyman Thank you for your update.

As you mentioned there is an `unbuffed channel` in the current impl. After searching the managed write codes, I notice there are two channels, one is 

```go
type AppendResult struct {
	ready chan struct{}
```

and the other is 

```go
type ManagedStream struct {
	pending     chan *pendingWrite                        // writes awaiting status
```

I think the unbuffer channel `pending     chan *pendingWrite ` should be replaced with buffered one. Please correct me if I am wrong

**Comment by richzw** [comment]
@shollyman 

One more thing I notice the `ready` channel in `AppendResult` is unbuffered. Maybe it could lead to goroutine leak in this case

```go
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(3)*time.Millisecond)
	defer cancel()

	go func() {
		_ = AppendRow(ctx, true)
	}()

	r, err := GetResult(ctx)
```

What if the `GetResult` return earlier than `AppendRow`, I think there will be no chance for `ready` channel to be received data, namely, the `ready` channel would be blocked forever, and lead to goroutine leak. Maybe the same last case in this [ref](https://www.ardanlabs.com/blog/2018/11/goroutine-leaks-the-forgotten-sender.html) Please correct me if I am wrong

**Comment by shollyman** [comment]
Closing this in favor of https://github.com/googleapis/google-cloud-go/issues/5459 and associated PR reviews, which covers the same topic.  Feel free to comment there if you have more feedback.

**Comment by richzw** [comment]
Hi @shollyman ,

I notice the `pending   chan *pendingWrite ` is changed from unbuffered channel to buffered channel [#5459](https://github.com/googleapis/google-cloud-go/issues/5459). 

I think maybe the `ready chan struct{}` of `AppendResult ` should also be changed from unbuffered channel to buffered channel to avoid deadlock in some cases. Please correct me if something wrong or missing.

**Comment by shollyman** [comment]
The ready channel in AppendResult is a signaling mechanism for communicating that the write is completed.  It doesn't pass data, it's only open or closed.  Buffering that would add no value.

**Comment by richzw** [comment]
@shollyman 

My bad, I misunderstand the usage of the ready channel. Thank you very much for your explanation.
