### ISSUE TITLE
storage: add endpoint samples

### ISSUE THREAD

**Issue by Breathtender** [googleapis/google-cloud-go#5502]
We need samples added that describe how to set the endpoint for our storage clients.
Such as setting for localhost/emulator, or private/vpc, or for the soon to be added locational endpoints feature.

Sample tracker & Request:

https://docs.google.com/document/d/1aeL7jgs789s7xg9khTxGzGWkb4k-t6LUk-uqhhs1Vuw/edit#

**Comment by cojenco** [comment]
Moved issue to  https://github.com/GoogleCloudPlatform/golang-samples/issues/2463
