### ISSUE TITLE
spanner: Enabling TrackSessionHandles causes deadlock

### ISSUE THREAD

**Issue by volicx** [googleapis/google-cloud-go#5710]
**Client**

Spanner

**Environment**

My local environment.

**Go Environment**

```
$ go version
go version go1.16.13 linux/arm64
```

<details>
<summary>$ go env</summary>
<pre><code>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/lima.linux/.cache/go-build"
GOENV="/home/lima.linux/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lima.linux/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lima.linux/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.16.13"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lima.linux/go/src/github.com/volicx/spanner/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build351475225=/tmp/go-build -gno-record-gcc-switches"
</code></pre>
</details>

<details>
<summary>$ cat go.mod</summary>
<pre><code>
module github.com/volicx/spanner

go 1.16

require cloud.google.com/go/spanner v1.29.0
</code></pre>
</details>

**Code**

Here is the code to reproduce this issue.

```golang
package main

import (
        "context"
        "fmt"
        "log"
        "time"

        "cloud.google.com/go/spanner"
)

const (
        TrackSessionHandles = true

        ProjectID    = "{{ PLEASE REWRITE THIS }}"
        InstanceID   = "{{ PLEASE REWRITE THIS }}"
        DatabaseName = "{{ PLEASE REWRITE THIS }}"
)

func main() {
        if err := reproduce(); err != nil {
                log.Fatal(err)
        }
}

func reproduce() error {
        ctx := context.Background()
        client, err := createClient(ctx)
        if err != nil {
                return err
        }
        defer client.Close()

        ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
        defer cancel()

        errCh := make(chan error)
        for i := 0; i < 10000; i++ {
                go func(ctx context.Context) {
                        ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
                        defer cancel()
                        _, err := client.ReadWriteTransaction(ctx, func(c context.Context, rwt *spanner.ReadWriteTransaction) error {
                                return nil
                        })
                        if err != nil {
                                errCh <- err
                        }
                }(ctx)
        }
        return <-errCh
}

func createClient(ctx context.Context) (*spanner.Client, error) {
        sessionPoolConfig := spanner.DefaultSessionPoolConfig
        sessionPoolConfig.TrackSessionHandles = TrackSessionHandles
        clientConfig := spanner.ClientConfig{SessionPoolConfig: sessionPoolConfig}
        dsn := fmt.Sprintf("projects/%s/instances/%s/databases/%s", ProjectID, InstanceID, DatabaseName)
        return spanner.NewClientWithConfig(ctx, dsn, clientConfig)
}
```

**Expected behavior**

Regardless of the value of `TrackSessionHandles`, the program will terminate after 2 seconds.

**Actual behavior**

If `TrackSessionHandles` is `false`, the program will terminate after 2 seconds.
If `TrackSessionHandles` is `true`, the program will not exit forever.

**Additional context**

N/A

**Comment by rahul2393** [comment]
Hello @volicx 
I tried replicating the issue but program got terminated with both true/false values. I tested using Docker image golang:1.16.3-alpine3.13

Here is my dockerfile 
```
FROM golang:1.16.3-alpine3.13

WORKDIR app

COPY . .

RUN go mod download

RUN GOOGLE_APPLICATION_CREDENTIALS=application_default_credentials.json time go run main.go
```

with TrackSessionHandles=false output is 
<img width="1756" alt="Screen Shot 2022-03-02 at 2 42 14 PM" src="https://user-images.githubusercontent.com/18293335/156331063-a3b2e265-f142-4e20-abef-cdbc72880965.png">


with TrackSessionHandles=true
<img width="1138" alt="Screen Shot 2022-03-02 at 2 41 51 PM" src="https://user-images.githubusercontent.com/18293335/156331098-472b2849-911d-44d7-8c0c-59fc6bf25eb8.png">
 output is

**Comment by volicx** [comment]
Hi @rahul2393

Thanks for checking.
I tried using your Dockerfile in my local environment and still reproduced the issue.

It may be related to machine specs.
I can confirm that it also reproduces in GCE.
Can you test in the same environment?

Compute:
- Zone: asia-northeast1-b
- Machine type: e2-medium

Spanner:
- Configuration: asia-northeast1
- Processing units: 1,000

**Comment by yfuruyama** [comment]
@rahul2393 (cc: @olavloite )

I have analyzed the following stack trace provided by @volicx and I found there is a deadlock between two goroutines.

* `goroutine A` tries to get two locks in the order of [sessionPool.mu.Lock()](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.29.0/spanner/session.go#L834) and [sessionHandle.mu.Lock()](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.29.0/spanner/session.go#L841)
* `goroutine B` tries to get two locks in the order of [sessionHandle.mu.Lock()](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.29.0/spanner/session.go#L67) and [sessionPool.mu.Lock()](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.29.0/spanner/session.go#L1079)

So two goroutines tried to lock in different order and caused this deadlock.


Stack Trace (sensitive information reducted):
```
###############
# goroutine A
###############
1 @ 0x104a2b9a0 0x104a3d4c0 0x104a3d4b1 0x104a5b950 0x104a692b4 0x104f161f4 0x104f15fc9 0x104f15e78 0x104f15d7c 0x104f16a50 0x104f3e3f4 0x104f3e884 0x104f10940 0x104f0a594 0x104f0a418 0x104f459c0 0x104a5f864
#	0x104a5b94f	sync.runtime_SemacquireMutex+0x3f								/usr/local/go/src/runtime/sema.go:71
#	0x104a692b3	sync.(*Mutex).lockSlow+0xf3									/usr/local/go/src/sync/mutex.go:138
#	0x104f161f3	sync.(*Mutex).Lock+0x2e3									/usr/local/go/src/sync/mutex.go:81
#	0x104f15fc8	cloud.google.com/go/spanner.(*sessionPool).getTrackedSessionHandleStacksLocked+0xb8		/...../cloud.google.com/go/spanner/session.go:841
#	0x104f15e77	cloud.google.com/go/spanner.(*sessionPool).errGetSessionTimeoutWithTrackedSessionHandles+0x67	/...../cloud.google.com/go/spanner/session.go:826
#	0x104f15d7b	cloud.google.com/go/spanner.(*sessionPool).errGetSessionTimeout+0x6b				/...../cloud.google.com/go/spanner/session.go:809
#	0x104f16a4f	cloud.google.com/go/spanner.(*sessionPool).takeWriteSession+0x5ff				/...../cloud.google.com/go/spanner/session.go:1041
#	0x104f3e3f3	cloud.google.com/go/spanner.(*Client).rwTransaction.func2+0x73					/...../cloud.google.com/go/spanner/client.go:474
#	0x104f3e883	cloud.google.com/go/spanner.runWithRetryOnAbortedOrSessionNotFound.func1+0x53			/...../cloud.google.com/go/spanner/retry.go:92
#	0x104f1093f	cloud.google.com/go/spanner.runWithRetryOnAbortedOrSessionNotFound+0x17f			/...../cloud.google.com/go/spanner/retry.go:128
#	0x104f0a593	cloud.google.com/go/spanner.(*Client).rwTransaction+0x103					/...../cloud.google.com/go/spanner/client.go:467
#	0x104f0a417	cloud.google.com/go/spanner.(*Client).ReadWriteTransaction+0xc7					/...../cloud.google.com/go/spanner/client.go:437
#	0x104f459bf	main.reproduce.func1+0x7f									/...../main.go:50

###############
# goroutine B
###############
190 @ 0x104a2b9a0 0x104a3d4c0 0x104a3d4b1 0x104a5b950 0x104a692b4 0x104f179a4 0x104f1746d 0x104f13924 0x104f11dd4 0x104f3e36c 0x104f0a5b4 0x104f0a418 0x104f459c0 0x104a5f864
#	0x104a5b94f	sync.runtime_SemacquireMutex+0x3f				/usr/local/go/src/runtime/sema.go:71
#	0x104a692b3	sync.(*Mutex).lockSlow+0xf3					/usr/local/go/src/sync/mutex.go:138
#	0x104f179a3	sync.(*Mutex).Lock+0x563					/usr/local/go/src/sync/mutex.go:81
#	0x104f1746c	cloud.google.com/go/spanner.(*sessionPool).recycle+0x2c		/...../cloud.google.com/go/spanner/session.go:1079
#	0x104f13923	cloud.google.com/go/spanner.(*session).recycle+0x43		/...../cloud.google.com/go/spanner/session.go:320
#	0x104f11dd3	cloud.google.com/go/spanner.(*sessionHandle).recycle+0xc3	/...../cloud.google.com/go/spanner/session.go:75
#	0x104f3e36b	cloud.google.com/go/spanner.(*Client).rwTransaction.func1+0x3b	/...../cloud.google.com/go/spanner/client.go:464
#	0x104f0a5b3	cloud.google.com/go/spanner.(*Client).rwTransaction+0x123	/...../cloud.google.com/go/spanner/client.go:499
#	0x104f0a417	cloud.google.com/go/spanner.(*Client).ReadWriteTransaction+0xc7	/...../cloud.google.com/go/spanner/client.go:437
#	0x104f459bf	main.reproduce.func1+0x7f					/...../main.go:50
```

**Comment by yfuruyama** [comment]
I created a [fix](https://github.com/googleapis/google-cloud-go/pull/5745). Please take a look.

**Comment by yfuruyama** [comment]
This is another code snippet to reproduce this problem.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof"
	"sync/atomic"
	"time"

	"golang.org/x/sync/errgroup"

	"cloud.google.com/go/spanner"
)

const (
	TrackSessionHandles = true
	ProjectID    = "{{ PLEASE REWRITE THIS }}"
	InstanceID   = "{{ PLEASE REWRITE THIS }}"
	DatabaseName = "{{ PLEASE REWRITE THIS }}"

	timeoutSec       = 5
	parallel         = 1000
	sessionMinOpened = 1
	sessionMaxOpened = 1
)

func main() {
	go http.ListenAndServe(":6000", nil)

	if err := reproduce(); err != nil {
		log.Fatal(err)
	}
	// Wait for the last flash of counter.
	time.Sleep(1 * time.Second)
}

func reproduce() error {
	ctx := context.Background()
	client, err := createClient(ctx)
	if err != nil {
		return err
	}
	defer client.Close()

	ctx, cancel := context.WithTimeout(ctx, timeoutSec*time.Second)
	defer cancel()

	// Print counter.
	var counter uint64
	go func() {
		ticker := time.NewTicker(1 * time.Second)
		for {
			_ = <-ticker.C
			log.Printf("Done: %d\n", counter)
		}
	}()

	var eg errgroup.Group
	for i := 0; i < parallel; i++ {
		eg.Go(func() error {
			ctx, cancel := context.WithTimeout(ctx, timeoutSec*time.Second)
			defer cancel()
			_, err := client.ReadWriteTransaction(ctx, func(c context.Context, rwt *spanner.ReadWriteTransaction) error {
				return nil
			})
			atomic.AddUint64(&counter, 1)
			return err
		})
	}
	return eg.Wait()
}

func createClient(ctx context.Context) (*spanner.Client, error) {
	sessionPoolConfig := spanner.DefaultSessionPoolConfig
	sessionPoolConfig.TrackSessionHandles = TrackSessionHandles
	sessionPoolConfig.MinOpened = sessionMinOpened
	sessionPoolConfig.MaxOpened = sessionMaxOpened
	clientConfig := spanner.ClientConfig{SessionPoolConfig: sessionPoolConfig}
	dsn := fmt.Sprintf("projects/%s/instances/%s/databases/%s", ProjectID, InstanceID, DatabaseName)
	return spanner.NewClientWithConfig(ctx, dsn, clientConfig)
}
```

This codes runs 1,000 read-write transactions simultaneously and prints how many transactions has been executed so far. You might need to run several times to reproduce this problem because this is timing issue.

One of the reproduced examples:

```
$ go run main.go 
2022/03/10 16:46:52 Done: 0
2022/03/10 16:46:53 Done: 3
2022/03/10 16:46:54 Done: 6
2022/03/10 16:46:55 Done: 10
2022/03/10 16:46:56 Done: 38
2022/03/10 16:46:57 Done: 76
2022/03/10 16:46:58 Done: 76
2022/03/10 16:46:59 Done: 76
2022/03/10 16:47:00 Done: 76
2022/03/10 16:47:01 Done: 76  <- No progress. Stuck.

**Comment by yfuruyama** [comment]
@rahul2393 (cc: @olavloite )
Can you try the above code to see if this issue is reproducible on your side?

**Comment by rahul2393** [comment]
Nope, I am using 1.30.0 version and the application is stopping with error message always

<img width="1751" alt="Screen Shot 2022-03-22 at 11 18 55 AM" src="https://user-images.githubusercontent.com/18293335/159416299-c3f8cf0a-2d76-4b06-9ea7-a3700865cdca.png">

**Comment by rahul2393** [comment]
@yfuruyama this will [fix](https://github.com/googleapis/google-cloud-go/pull/5777) the above issue

cc: @olavloite
