### ISSUE TITLE
aiplatform: add implementation for v1beta1

### ISSUE THREAD

**Issue by alethenorio** [googleapis/google-cloud-go#5737]
**Is your feature request related to a problem? Please describe.**
There's a big push right now for the new Vertex AI platform for building MLOps, all of which have APIs under the aiplatform package however using the `apiv1` package which is the only one implemented here just returns `unimplemented`. Using python SDK works without any issue. I get a feeling this is because the current implementation of most APIs live under the `v1beta1` protos. It is very hard for us who have an entire organization working in Go to have to fallback to python SDKs or start implementing the REST APIs by hand.

**Describe the solution you'd like**
Have an implementation for the `v1beta1` protos of `aiplatform` package

**Describe alternatives you've considered**
Building a REST API by hand or falling back to python SDKs

**Additional context**

**Comment by codyoss** [comment]
@alethenorio Thanks for this feedback. I will do some research here and get back to you. If other languages have published this API already, it might just be an oversight that we don't have it yet in Go.

**Comment by alethenorio** [comment]
@codyoss Thank for the quick response here. Can also confirm that I was able to call the APIs using the genproto repo directly with v1beta1 protos. Looking forward to this release
