### ISSUE TITLE
Use Go NewKeyManagementClient without credentials from environment variables

### ISSUE THREAD

**Issue by torntrousers** [googleapis/google-cloud-go#5740]
Is it possible to use the Go KMS client without having the credentials pointed to from environment variables? For example, I have this code which works:
```
func TestNewKeyManagementClient(t *testing.T) {
	path, _ := OS.Getwd()
	OS.Setenv("GOOGLE_APPLICATION_CREDENTIALS", path+"/testdata/kms-project-327709-ae30f3fc36b5.json")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	client, err := kms.NewKeyManagementClient(ctx)
	assert.Nil(t, err)

	err = client.Close()
	assert.Nil(t, err)
}
```
but if I don't set "GOOGLE_APPLICATION_CREDENTIALS" then it fails. I wondered about using the option.ClientOption parameter on the NewKeyManagementClient function but I can't find any doc about what to put in there.

Is this possible? 

This is using: 
        cloud.google.com/go/kms v1.1.0
	google.golang.org/api v0.59.0
	google.golang.org/genproto v0.0.0-20211018162055-cf77aa76bad2

TIA!

**Comment by codyoss** [comment]
All of our clients support what is called Application Default Credentials(ADC), detailed [here](https://google.aip.dev/auth/4110). Clients will auto-detect that environment variable, well known paths, check for compute metadata service else you may explicitly provide them with a client option. Here a a couple of the relevant options:

- [WithCredentialsFile](https://pkg.go.dev/google.golang.org/api/option#WithCredentialsFile)
- [WithCredentials](https://pkg.go.dev/google.golang.org/api/option#WithCredentials)
- [WithTokenSource](https://pkg.go.dev/google.golang.org/api/option#WithTokenSource)

Hope that helps, please let me know if you have any followup questions.

P.S. This is also lightly touched on in our [README](https://github.com/googleapis/google-cloud-go#authorization)

**Comment by torntrousers** [comment]
Thanks for the speedy reply. Looks like [WithCredentialsJSON](https://pkg.go.dev/google.golang.org/api/option#WithCredentialsJSON) will let me pass in a string which will do what i need.
