### ISSUE TITLE
pubsub: suggestion: add struct tag to `pubsub.Message.ID`

### ISSUE THREAD

**Issue by kanata2** [googleapis/google-cloud-go#5749]
Currently, there is a difference between the schema of the message sent by push subscription and Go's struct definition, then we  cannot decode it correctly like the following code.

```go
import "cloud.google.com/go/pubsub"

func handler(w http.ResponseWriter, r *http.Request) {
	var m struct { Message pubsub.Message }
	if err := json.NewDecoder(r.Body).Decode(&m); err != nil { ... }
        ...
       println(m.Message.ID) // empty
}
```

So I would like to make some changes to the ID field, such as adding `json: "message_id"` to the ID field.
What do you think?

**Comment by hongalex** [comment]
Could you tag the field in the custom struct instead? An example of this would is in https://github.com/GoogleCloudPlatform/golang-samples/blob/2bd24627dd5e411dc431c68a895f1348c2aed18e/appengine/go11x/pubsub/authenicated_push/main.go

**Comment by kanata2** [comment]
The `google.golang.org/api/pubsub/v1.PubsubMessage` struct is what I want. Thanks.
