### ISSUE TITLE
bigquery: oauth2: cannot fetch token: 404 Not Found

### ISSUE THREAD

**Issue by glserranv** [googleapis/google-cloud-go#5750]
**Client**

BigQuery

**Environment**

Running locally with a service account with access to bigquery

**Go Environment**

$ go version
go version go1.17.5 darwin/arm64
$ go env
GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/glserran/Library/Caches/go-build"
GOENV="/Users/glserran/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/glserran/go/pkg/mod"
GONOPROXY="github.com/grupo-valoreo/*"
GONOSUMDB="github.com/grupo-valoreo/*"
GOOS="darwin"
GOPATH="/Users/glserran/go"
GOPRIVATE="github.com/grupo-valoreo/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/glserran/src/sync-tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cy/hd7g2zc93mdcy9dp4z1cs_wc0000gn/T/go-build3287429980=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go

func MakeBQClient(projectId string, tableName string, dataSet string) SourceClient {
	c, _ := bigquery.NewClient(context.Background(), projectId)
	return &bqImpl{
		client:    c,
		projectId: projectId,
		tableName: tableName,
		dataSet:   dataSet,
	}
}


func Query(queryString string){
               query := impl.client.Query(queryString)

		row, err := query.Read(context.Background())
		if err != nil {
			panic(err)
		}
}
```

**Expected behavior**

should return a row with some values. 

**Actual behavior**
errors with message:

""Post \"https://bigquery.googleapis.com/bigquery/v2/projects/$somepoject/jobs?alt=json&prettyPrint=false\": oauth2: cannot fetch token: 404 Not Found\nResponse: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/token</code> was not found on this server.  <ins>That’s all we know.</ins>"

**Additional context**

This used to work but have tested in previous versions and doesn't work. I have tested with v.1.28.0, v1.29.0, v1.8.0

**Comment by shollyman** [comment]
Unclear from the report what's going on here.  The fact that it's implicating the oauth token path makes me wonder how auth is setup.  BigQuery resolves auth credentials using Application Default Credentials resolution.  If you're dealing with service account credentials, I'd expect a JWT signing.  Is there a GOOGLE_APPLICATION_CREDENTIALS set?  gcloud credentials?

More information about ADC in general: https://google.aip.dev/auth/4110

**Comment by glserranv** [comment]
I found the issue. The issue is that my code modified http.DefaultClient and the bigquery.Client uses this by default. Those modifications cause the issue.

**Comment by shollyman** [comment]
If you need to customize the client, there's always https://pkg.go.dev/google.golang.org/api/option#WithHTTPClient as well.
