### ISSUE TITLE
storage: Signed URL documentation

### ISSUE THREAD

**Issue by dmorejon** [googleapis/google-cloud-go#5757]
Hi there! Thanks in advance.

**Problem/Confusion:** 
I was looking to create a Signed URL for upload to a GCS Bucket. [This section](https://pkg.go.dev/cloud.google.com/go/storage#hdr-Signed_URLs) at the top of the documentation implies the only way to do this is with `storage.SignedURL`, which requires reading in the service account private key, etc.

I'm deploying on Cloud Run and all other GCP services auto-detect default credentials and I didn't know GCS did too until I stumbled upon [this repo](https://github.com/salrashid123/gcs_signedurl/#golang) that clearly and concisely explains the issues and options.

Solution: 
Add a blurb to the Signed URL documentation stating that the `*BucketHandle` method can use the default application credentials. Hope this can help other people find the correct method quicker!

**Comment by BrennaEpp** [comment]
Hi @dmorejon, thanks so much for opening this issue! We will look into updating the go docs for Signed URL.

**Comment by tritone** [comment]
Nice catch, we missed this in the docs update when we added `BucketHandle.SignedURL` last year. @BrennaEpp could you update these docs as well?
