### ISSUE TITLE
core: release a v1 

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#5769]
**Is your feature request related to a problem? Please describe.**
As the core module for google-cloud-go is still v0, there are no compatibility guarantees for the underpinnings of the generated libraries. When we import the SDK and all of its submodules into the monorepo, we'd like not to be in the case where we're forced to perform an all-submodules update if such a breaking change is made, as we're restricted to having exactly one implementation of the core module.

**Describe the solution you'd like**
If you release a v1, you'd be committing to a higher compatibility guarantee, and reducing the likelihood of requiring whole-world updates when importing, since older per-service submodules should be able to continue to operate on dot releases of v1, or if a v2 is necessary, then they can continue to operate on a mix of v1 and v2.

**Describe alternatives you've considered**
The status quo just means that breaking changes will force importers to go to significant lengths to maintain monorepo policy, and will (further) stall imports of modern versions of the SDK.

**Additional context**
monorepo policy includes: you can have exactly one version of a Go library per major version of that library, and that version must satisfy all its dependencies already in the monorepo. Thus a in-major-version breaking change requires an atomic change of the library with the breaking change and every client that must be amended to handle the in-major-version breaking change.

**Comment by codyoss** [comment]
At this point there is not much left in this root module. There are two more modules to carve out and other than that the rest of the code is truely "beta" code, and most of these are testing/debuging utilities. For this reason I don't think the root module will ever be v1. I did create two issues for the modules that yet need to be carved out: #6276 #6275

Closing this in favor of those issues.
