### ISSUE TITLE
pubsub: ack called but message retried

### ISSUE THREAD

**Issue by schmurfy** [googleapis/google-cloud-go#5823]
**Client**

PubSub

**Environment**

Alpine on GKE

**Go Environment**

$ go version
1.17.5
$ go env

**Code**

e.g.
```go
ctx := context.Background()
client, err := pubsub.NewClient(ctx, projectID)
if err != nil {
	return fmt.Errorf("pubsub.NewClient: %v", err)
}
defer client.Close()

sub := client.Subscription(subID)

return sub.Receive(ctx, func(_ context.Context, msg *pubsub.Message) {
        fmt.Printf("Got message: %q\n", string(msg.Data))
        msg.Ack()
})
```

**Expected behavior**

Messages are ack and not retried

**Actual behavior**

Some messages are retried despite being acked almost instantly

**Additional context**

Subscriptions config:
```
Type: Pull
Retention: 10min
Expiry: 31 days
Ack deadline: 300s (it should not matter in pull mode anyway)
Retry Policy: exponential backoff from 1s to 30s
``` 

The problem appeared after a recent migration, the messages count might be a factor but we are far from what pubsub can support. The cpu usage of the pod is really low so I don't think that's an issue either.

We tried a lot of things but nothing worked. We also have 3 different deployment of this application on three different gcp projects and only one of them has this issue.

I am not sure where is the issue but if anyone has an idea I take it.

**Comment by hongalex** [comment]
Is the code you provided above exactly what you're using in your application? Specifically, are you using the default `sub.ReceiveSettings`?

I understand that you said the message count is far below what Pub/Sub can support, but could you describe what your publish throughput looks like?

**Comment by schmurfy** [comment]
it is not exactly the code but the meaningful parts are the same and yes we use the defaults.

**Comment by schmurfy** [comment]
I forgot to mention the gcp monitoring shows that events are expiring now while it was at zero before our increase in pubsub usage:
![image](https://user-images.githubusercontent.com/2983/160997417-a865fee8-c741-4f1b-971f-e0ec05df6a34.png)

**Comment by hongalex** [comment]
1. How many messages are you publishing at once? 

> We also have 3 different deployment of this application on three different gcp projects and only one of them has this issue

Are these three deployment receiving messages from 3 different subscriptions?

**Comment by schmurfy** [comment]
Sorry I was not notified of your reply, not sure why...
We are using `v1.17.1` but as as I said above we have the exact same code with similar events count on two different gcp projects and only one of them is showing this behaviour.
It looks more and more like some sort of configuration issue except that pubsub is a blackbox on which we have little to no control we have no way to confirm this.

One option would to be to remove and recreate the topic and subscription but of the two possible outcomes none would make me feel better:
- it changes nothing and the same problem happens on the new topic/subscription
- it solves the problem

**Comment by hongalex** [comment]
Yeah I understand the frustration. Couple things to note here: first of all, Pub/Sub is at-least-once delivery by default. Message redelivered should be expected if messages are expiring.

Secondly, I noticed that that's a lot of expirations at the peak. I would recommend tweaking some [`ReceiveSettings`](https://pkg.go.dev/cloud.google.com/go/pubsub#ReceiveSettings) to see if that helps. Some suggestions are: increasing the number of `MaxOutstandingMessages` and increasing `NumGoroutines` if your CPU usage is low and see if that helps. If the problem persists after that and you can file a support case, I recommend doing that so we can look into the details of your project/subscription.

**Comment by hongalex** [comment]
Is this issue still impacting you? If so, could you provide any updates since then?

**Comment by codyoss** [comment]
@hongalex Let's just close this out due to lack of response.

**Comment by hongalex** [comment]
Feel free to comment again if this is still actual and we'll continue to look into this.
