### ISSUE TITLE
logging: detectResource() is slow when not in Google Env

### ISSUE THREAD

**Issue by jtwatson** [googleapis/google-cloud-go#5855]
**Client**

Cloud Logging

**Environment**

Local development

**Code**

```go
package main

import (
	"context"
	"log"
	"os"

	"cloud.google.com/go/logging"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()

	// Creates a client.
	projectID := os.Getenv("GOOGLE_CLOUD_PROJECT")
	file := "my-credentials-file.json"
	client, err := logging.NewClient(ctx, projectID, option.WithCredentialsFile(file))
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	logger := client.Logger("my-log") //  <<<----- This hangs for 5 seconds
	_ = logger
}
```

**Expected behavior**

Creating the `logger` from the `client` should be fast.

**Actual behavior**

the code hangs for about 5 seconds

**Additional context**

I run into this issue when I am developing locally and pushing logs to Cloud Logging. But this would also be an issue for anyone using Cloud Logging from a local environment.

The issue is with [isKubernetesEngine()](https://github.com/googleapis/google-cloud-go/blob/db75317f07e054ba3e552abd472b679d91cbf312/logging/resource.go#L142) function. This function starts off by making a call to `metadata.InstanceAttributeValue("cluster-name")`. The call fails and the error is classified as a retry. It then enters a retry loop of max 5 tries with back-off. 

All other detection functions failed quite quickly. Not sure if there is a way to detect GKE without using the metadata server...

This issue was introduced [here](https://github.com/googleapis/google-cloud-go/commit/a2538e16123c21da62036b56df8c104360f1c2d6)

This little issue really makes iterative coding/testing slow.

**Comment by minherz** [comment]
we are in the process to revise the automatic resource detection (in #5829). as part of the work we will address the behavior that you describe.

**Comment by minherz** [comment]
Please, track #6029 to see when this change will be introduced. The modification reduces timeout and minimizes the time. We cannot totally eliminate the delay because the resource detection validates whether the application runs in a GCP environment by trying to access the metadata server. The logic includes retrying mechanism because the server sometimes can be not responsive to the first request. The expected delay is one time per application run and supposed to be within 1sec.
