### ISSUE TITLE
pubsub: document what happens when MaxExtension is exceeded while in-process

### ISSUE THREAD

**Issue by mbrancato** [googleapis/google-cloud-go#5858]
**Client**

PubSub

**Environment**

Docker on GKE

**Go Environment**

$ go version
1.17.2

$ go env

**Code**

e.g.
```go
package main

import (
    "time"
)

func main() {
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, "project-id")
	if err != nil {
		// TODO: Handle error.
	}
	sub := client.Subscription("subName")
	// This program is expected to process and acknowledge messages in 30 seconds. If
	// not, the Pub/Sub API will assume the message is not acknowledged.
	sub.ReceiveSettings.MaxExtension = 30 * time.Second
	err = sub.Receive(ctx, func(ctx context.Context, m *pubsub.Message) {
		// Processing that may, at times, exceed the max extension time
                time.sleep(1 * time.Minute)
		m.Ack()
	})
	if err != context.Canceled {
		// TODO: Handle error.
	}
}
```

**Expected behavior**

Message should appear to have ack'd but really be a no-op.

**Actual behavior**

Great question - I see some edge cases where messages may appear stuck in memory and memory consumption grows. This should be under control of max outstanding messages, but it seems unbounded. A working theory here is that some messages are not being processed in time and are causing problems.

The documentation doesn't appear to cover what happens with the message if the max extension is reached while in-process.

**Additional context**

currently using `cloud.google.com/go/pubsub v1.17.1`

**Comment by hongalex** [comment]
There shouldn't be anything too surprising that's handled here. As you sort of alluded to, messages that are not handled within MaxExtension are expired. This means that these messages will be redelivered by the Pub/Sub servers. This behavior is described [here](https://pkg.go.dev/cloud.google.com/go/pubsub#hdr-Deadlines). Although these are "expired", this only means that messages will not have their acknowledgement deadline modified. The handler function passed into `Receive` will continue to execute. However, until `Ack` or `Nack` is called on these messages, they will still continue to exist in memory and gum up the flow control system (MaxOutstandingMessages).

If you have found instances where `MaxOutstandingMessages` / `MaxOutstandingBytes` is not respected, please report this as a separate issue and I'd be happy to take a look. Hope that helps!
