### ISSUE TITLE
bigquery: SchemaFromJSON doesn't support policyTags

### ISSUE THREAD

**Issue by Nabil372** [googleapis/google-cloud-go#5867]
Hi there!

[SchemaFromJSON](https://pkg.go.dev/cloud.google.com/go/bigquery#SchemaFromJSON) ignores policyTags in JSONs which are generated by [protoc-gen-bq-schema](https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema).
This function no longer does what it's described to do:
"SchemaFromJSON takes a JSON BigQuery table schema definition (as generated by https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema) and returns a fully-populated Schema."

Example JSON taken from [protoc-gen-bq-schema](https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema#example-with-policy-tags):

```json
[
 {
  "name": "a",
  "type": "INTEGER",
  "mode": "REQUIRED",
  "policyTags": {
   "names": [
    "private"
   ]
  }
 },
 {
  "name": "b",
  "type": "STRING",
  "mode": "NULLABLE",
  "policyTags": {
   "names": [
    "public"
   ]
  }
 },
 {
  "name": "nested",
  "type": "RECORD",
  "mode": "REQUIRED",
  "fields": [
   {
    "name": "a",
    "type": "INTEGER",
    "mode": "REQUIRED",
    "policyTags": {
     "names": [
      "private"
     ]
    }
   },
   {
    "name": "b",
    "type": "STRING",
    "mode": "NULLABLE"
   }
  ]
 }
]
```

The function is still able to produce a `bigquery.Schema` but it ignores the `policyTags`.

**Comment by shollyman** [comment]
Will take a look at this as a FR.
