### ISSUE TITLE
cmd: google-cloud-go: Build failing

### ISSUE THREAD

**Issue by amitmukati-2604** [googleapis/google-cloud-go#5912]
While building google-cloud-go package for version v0.54.0 the build is failing due to undenfined type syscall in server.go (cmd/go-cloud-debug-agent/internal/debug/server/server.go).The build is failing due to RIP and RSP registers as these registers are not available in ppc64le. Adding below the error and the failing build logs link.

# ERROR:- 
#cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/server
cmd/go-cloud-debug-agent/internal/debug/server/server.go:316:18: assignment mismatch: 2 variables but 1 value
cmd/go-cloud-debug-agent/internal/debug/server/server.go:316:48: s.stoppedRegs.Rip undefined (type syscall.PtraceRegs has no field or method Rip)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:376:15: s.stoppedRegs.Rip undefined (type syscall.PtraceRegs has no field or method Rip)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:382:32: s.stoppedRegs.Rip undefined (type syscall.PtraceRegs has no field or method Rip)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:383:32: s.stoppedRegs.Rsp undefined (type syscall.PtraceRegs has no field or method Rsp)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:573:67: s.stoppedRegs.Rip undefined (type syscall.PtraceRegs has no field or method Rip)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:573:86: s.stoppedRegs.Rsp undefined (type syscall.PtraceRegs has no field or method Rsp)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:603:37: regs.Rip undefined (type syscall.PtraceRegs has no field or method Rip)
cmd/go-cloud-debug-agent/internal/debug/server/server.go:603:47: regs.Rsp undefined (type syscall.PtraceRegs has no field or method Rsp)

google-cloud-go: v0.54.0
go version: 1.17
arch: pp64le
os: linux
distro: ubi 8.5
Attaching below logs of build failure.
[google-cloud-go_logs.txt](https://github.com/googleapis/google-cloud-go/files/8512928/google-cloud-go_logs.txt)

could you please address the build failures?

**Comment by hongalex** [comment]
Hi, could you try updating to the latest version v0.100.0 and see if this issue still occurs?

**Comment by amitmukati-2604** [comment]
Hi, I tried with the v0.100.0 and facing the same error.

**Comment by codyoss** [comment]
Is that arch correct? `pp64le`? Or do you mean `ppc64le`. In general our libraries are compatible and only tested against more common linux arches such as: arm and amd. It would not surprise me if some things did not compile for power pc, especially that debug package tree

**Comment by amitmukati-2604** [comment]
yes it is ppc64le.

**Comment by codyoss** [comment]
Is this actually causing you an issue besides not being able to build that dir? I don't think people should really be using that project as it is deprecated and no longer works with versions of Go this project is tested against. The code may just be removed in the future. But again, we don't test for power PC so I am not sure if there are other things we do that are not compatible with that arch as well.

**Comment by codyoss** [comment]
Closing this as this in not an environment we support or test against today.
