### ISSUE TITLE
feat(godocfx): add friendly api name to yaml

### ISSUE THREAD

**Issue by dansaadati** [googleapis/google-cloud-go#5949]
```doc-templates``` will display the friendly api name in the ```<h1>```([pr](https://github.com/googleapis/doc-templates/pull/367)) and first paragraph summary ([pr](https://github.com/googleapis/doc-templates/pull/373)) of generated pages. ```godocfx``` should include a ```friendlyApiName``` as an item key in the yaml which describes the simplified name of the Go library along with its API version.  For example, the Cloud Vision apiv1p1beta1 library should set the friendly api name to be something like "Cloud Vision V1p1beta1 API"

This change will help discern documentation across API versions.

**Comment by codyoss** [comment]
@dansaadati Is this something that is still going to have action taken? I wonder if this is best to track in an internal bug instead of here?

**Comment by dansaadati** [comment]
Yes, assigning to @tbpg . We'd like this added to improve SEO for Go pages.
