### ISSUE TITLE
logging/logadmin: How to set WriteIdentity when creating a log sink?

### ISSUE THREAD

**Issue by shaobovaltix** [googleapis/google-cloud-go#6019]
**Client**

e.g. logadmin

**Environment**

e.g. CentOS

**Go Environment**

$ go version
go version go1.15.3 linux/amd64

**Code**

e.g.
```go
sink, err := logging.CreateSink(
	context.Background(),
	&logadmin.Sink{
		ID:             "test-sink",
		Destination:    "test-topic",
		Filter:        "",
		WriterIdentity: <my-own-service-account-email>,
	},
)
```

**Expected behavior**

created a log sink with specified write identity in the code

**Actual behavior**

The log sink was created with write identity serviceAccount:cloud-logs@system.gserviceaccount.com, but this service account cannot be added to the topic to allow the sink to send logs to.

**Additional context**

What I'm trying to do is to create a pubsub topic, a subscription to the topic and a log sink to send logs to the topic. It looks like I need to create the sink with proper write identity and grant pubsub publisher permission to the write identity so that the sink can send logs to the topic. I'm wondering what's the best practice to achieve this?

**Comment by minherz** [comment]
hi, the existing API does not allow to customize which identity can be used for the sink. after a sink is created, the identity (its email) is provided as a part of the output. this identity should be granted write permission to the relevant destination (e.g. bucket or pubsub topic). please, have a look into overview of the "create sink" [documentation](https://cloud.google.com/logging/docs/export/configure_export_v2#creating_sink) for the reference.

The client library provides the identity that should be granted the write permission in the `logadmin.Sink` [object](https://github.com/googleapis/google-cloud-go/blob/ef4a48cbc46641ac56a3043c0ccd52e7cd06908f/logging/logadmin/sinks.go#L58). You can enforce a generation of the unique service account as a write identity for the new sink if you set the [`SinkOpts.UniqueWriterIdentity`](https://github.com/googleapis/google-cloud-go/blob/ef4a48cbc46641ac56a3043c0ccd52e7cd06908f/logging/logadmin/sinks.go#L105) field to `true` in the call to `logadmin.CreateSinkOpt`. If you create the sink with `logadmin.CreateSink` the unique_write_identity parameter will be passed as false. See the [API documentation](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#google.logging.v2.CreateSinkRequest.FIELDS.bool.google.logging.v2.CreateSinkRequest.unique_writer_identity) to understand how the write identity is defined if the parameter is passed as `false`.

**Comment by minherz** [comment]
Closing this issue after 3 week of idle. Feel free to reopen it if you'd like to follow up on the answer.
