### ISSUE TITLE
Found no api to get project info by project id with service account 

### ISSUE THREAD

**Issue by zeromsi** [googleapis/google-cloud-go#6044]
I'm searching for an api to get project info by project id with service account. It would be great to if someone help me in this regard.

Thanks

**Comment by codyoss** [comment]
If your code is running on Google Compute you can query the metadata service to find out this sort of information. We have a package to help get info from it: [metadata](https://pkg.go.dev/cloud.google.com/go/compute/metadata)

Another option is always to inject envvars into your deploy process which give you access to that info. Hope that helps!
