### ISSUE TITLE
spansql : create view gives an error : unexpected token "c"

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#6045]
**Client**

golang spansql v1.32.0

**Go Environment**

$ go version 1.69.9

the sql 

CREATE VIEW
		   resourceconfiguration_view SQL SECURITY INVOKER AS
		SELECT c.id,r.id
		  FROM resourceconfiguration c
		         LEFT JOIN sa_service_runners r
		                   ON r.id = c.impersonation;

The problem is c.id in the select statement .  if you don't use c.id, it works , but you will need this if the tables have the same column names

we got following error 
    spansql_test.go:101: ParseDDL("CREATE VIEW\n    resourceconfiguration_view SQL SECURITY INVOKER AS\nSELECT c.id,r.id\n  FROM resourceconfiguration c\n         LEFT JOIN sa_service_runners r\n                   ON r.id = c.impersonation;"): filename:4: unexpected token "c"

**Comment by geerttouquet** [comment]
The problem occurs when you do _, err := spansql.ParseDDL

**Comment by neglect-yp** [comment]
You can work around this problem by explicitly specifying `AS`. The following DDL can be parsed.

```sql
CREATE VIEW
resourceconfiguration_view SQL SECURITY INVOKER AS
SELECT c.id,r.id
FROM resourceconfiguration AS c
LEFT JOIN sa_service_runners AS r
ON r.id = c.impersonation
```
Note that the trailing `;` has to be removed.

---

FYI:
https://github.com/googleapis/google-cloud-go/blob/6ab8bed93a978e00a6c195d8cb4d574ca6db27c3/spanner/spansql/parser.go#L2262-L2263

**Comment by geerttouquet** [comment]
thanks , this is a good workaround
