### ISSUE TITLE
storage: panic when invalid bucket name

### ISSUE THREAD

**Issue by devduck123** [googleapis/google-cloud-go#6054]
**Client**

Storage

**Environment**

**Go Environment**

$ go version
go1.18 darwin/arm64
$ go env

**Code**

```go
package main

func do() error {
        // invalid bucket here
        bucketName := "foo/bar"
	bucket := client.Bucket(bucketName)
	object := bucket.Object(objectPath)
	w := object.NewWriter(ctx)
	_, err := w.Write() // <--- panic here
	if err != nil {
		return err
	}
	if err := w.Close(); err != nil {
		return err
	}
}
```

**Expected behavior**

Expected clear error message to be returned.

**Actual behavior**

Panic occurs in storage library because Google Cloud Storage expects bucket name to be the root bucket name.

**Comment by tritone** [comment]
Hi @devduck123 , I tried to reproduce the issue locally and can't reproduce it.

For a bucket foo/bar, I get: `2022/06/06 13:50:28 err: googleapi: Error 400: Invalid bucket name: 'foo/bar', invalid
exit status 1`

For a random non-existent bucket, I get: `2022/06/06 13:53:44 err: googleapi: Error 404: The specified bucket does not exist., notFound`

Can you give more details on how to reproduce the issue? What does the panic look like?

**Comment by devduck123** [comment]
Found out that the issue was caused due to my prematurely closing the stream.
