### ISSUE TITLE
storage: undefined: storage.CommonRequestParams

### ISSUE THREAD

**Issue by RobinUS2** [googleapis/google-cloud-go#6055]
**Client**

storage

**Environment**

macOS M1

**Go Environment**

$ go version
go version go1.18.2 darwin/arm64

$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/snip/Documents/gopath/bin"
GOCACHE="/Users/snip/Library/Caches/go-build"
GOENV="/Users/snip/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/snip/Documents/gopath/pkg/mod"
GONOPROXY="github.com/snip"
GONOSUMDB="github.com/snip"
GOOS="darwin"
GOPATH="/Users/snip/Documents/gopath"
GOPRIVATE="github.com/snip"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wm/sqg6cz6s5qn8ht69xr4th9900000gp/T/go-build3589280729=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

import of package

**Expected behavior**

package imports

**Actual behavior**

```
go: upgraded golang.org/x/sync v0.0.0-20210220032951-036812b2e83c => v0.0.0-20220513210516-0976fa681c29
# cloud.google.com/go/storage
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/grpc_client.go:162:7: req.CommonRequestParams undefined (type *"google.golang.org/genproto/googleapis/storage/v2".DeleteBucketRequest has no field or method CommonRequestParams)
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/grpc_client.go:162:40: undefined: storage.CommonRequestParams
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/grpc_client.go:181:7: req.CommonRequestParams undefined (type *"google.golang.org/genproto/googleapis/storage/v2".GetBucketRequest has no field or method CommonRequestParams)
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/grpc_client.go:181:40: undefined: storage.CommonRequestParams
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/writer.go:455:24: undefined: storage.CommonRequestParams
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/writer.go:457:23: undefined: storage.CommonRequestParams
../../../gopath/pkg/mod/cloud.google.com/go/storage@v1.22.0/writer.go:465:3: unknown field 'CommonRequestParams' in struct literal of type "google.golang.org/genproto/googleapis/storage/v2".StartResumableWriteRequest
```

**Screenshots**

-

**Additional context**

builds of ~ 1 month ago were just fine

**Comment by tritone** [comment]
Apologies for the issue. This is due to a breaking change in a dependency which just went through yesterday (similar to #4991).

We will cut a release today that will fix the issue. In the meantime, you can work around by downgrading the go-genproto dependency to an earlier version. `google.golang.org/genproto@v0.0.0-20220505152158-f39f71e6c8f3` should work.

FYI @noahdietz

**Comment by codyoss** [comment]
If you pull in storage v1.22.1 everything should work as expected. Thank you for the report @RobinUS2 and sorry for this disruption. Out of curiosity can you share what version of genproto and storage where in your go.mod when you experienced this issue? Thanks again!

**Comment by drakkan** [comment]
> If you pull in storage v1.22.1 everything should work as expected. Thank you for the report @RobinUS2 and sorry for this disruption. Out of curiosity can you share what version of genproto and storage where in your go.mod when you experienced this issue? Thanks again!

Hi, it happens with these entries in go.mod

```
cloud.google.com/go/storage v1.22.0
google.golang.org/genproto v0.0.0-20220519153652-3a47de7e79bd // indirect
```

it works with storage v1.22.1, thanks

**Comment by RobinUS2** [comment]
yes it's resolved again, thanks!
