### ISSUE TITLE
internal/gapicgen: Incorrect import path when generating a new client into a "v2" directory 

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-go#6070]
In google-cloud-go, run `genbot` locally to generate a new client into a "v2" directory. 

1. Edit `internal/gapicgen/generator/config.go`. Add `/v2` before api version in the import path:

```
ImportPath:            "cloud.google.com/go/recaptchaenterprise/v2/apiv1",
```

1. In `internal/gapicgen`, run genbot: 

```
$ go run cloud.google.com/go/internal/gapicgen/cmd/genbot -local -gocloud-dir /Users/chrisdsmith/oss/google-cloud-go -only-gapics -gapic=cloud.google.com/go/recaptchaenterprise/v2/apiv1
```

1.  Inspect the generated file `recaptchaenterprise/v2/apiv1/version.go`:

    Got: `import "cloud.google.com/go/recaptchaenterprise/internal"`
    Want: `import "cloud.google.com/go/recaptchaenterprise/v2/internal"`

**Comment by quartzmo** [comment]
See `internal/gapicgen/generator/_version.go.txt`.

**Comment by codyoss** [comment]
@quartzmo Would you mind opening this issue instead in gapic-generator-go. I believe that is where we will have to make a change.

**Comment by quartzmo** [comment]
https://github.com/googleapis/gapic-generator-go/issues/1002#issuecomment-1131982990

**Comment by codyoss** [comment]
Ooops I was mistaken, forgot we hacked that in on this side of the world: https://github.com/googleapis/google-cloud-go/pull/5687/commits/02a6052ef157493717ba1d89b3c8f913a041fba9#diff-f135601d93025b997e601de66bdc5d9b39e110ab8669e74ff429ff159353c2b9

**Comment by codyoss** [comment]
I think this has been fixed for a while now.
