### ISSUE TITLE
videointelligence: Generate apiv1beta3 client with support for streaming video

### ISSUE THREAD

**Issue by tyronegroves** [googleapis/google-cloud-go#6109]
Python and CPP clients have streaming video clients. I am not able to generate a client that will work with Go.

**Comment by codyoss** [comment]
Ah you mean v1p3beta1 it looks like, this seems reasonable.

**Comment by tyronegroves** [comment]
@codyoss @quartzmo Any movement on this?

**Comment by tyronegroves** [comment]
@codyoss ok thanks appreciate you guys. Very responsive!

**Comment by tyronegroves** [comment]
@codyoss @quartzmo  any updates on this?
