### ISSUE TITLE
datastore: delete entities in a specific namespace in one transaction

### ISSUE THREAD

**Issue by OscarVanL** [googleapis/google-cloud-go#6111]
**Is your feature request related to a problem? Please describe.**
We want to provide functionality to delete all data for a company in a cloud datastore, for example in the case where we need to offboard a company from our product, or receive a GDPR deletion request.

We have a [multitenancy datastore](https://cloud.google.com/datastore/docs/concepts/multitenancy), data is split by company (1 company = 1 tenant), where each tenant has a different namespace. 

The approach we had intended to use was to create a transaction, do a kindless query across the company's namespace:
```
allNamespaceQuery := datastore.NewQuery("").
	Namespace(companyID).
	KeysOnly().Transaction(txn)

keys, err := client.GetAll(c, allNamespaceQuery, nil)
```

We would then exclude Kinds prefixed with "__", and then use DeleteMulti to remove them:
```
err = txn.DeleteMulti(entitiesToRemove)
```

The problem is that `Multi` operations and `Commit` operations are limited to 500 entities. It is likely that a tenant will have more than 500 entities. So these operations may fail.

**Describe the solution you'd like**
We would like a way to delete all entities for a particular namespace as a transaction that is either successful or unsuccessful to avoid leaving our datastore in an unexpected state.

**Describe alternatives you've considered**
We could avoid this issue by splitting the entitiesToRemove into chunks of 500 or less, however this means we would need to do the operation without using transactions, or as multiple transactions, which could leave us in a sticky situation where a customer is _partially off-boarded_.

**Additional context**

**Comment by OscarVanL** [comment]
To add some wider context to this MR, the documentation suggests using [dataflow for bulk cloud datastore deletions](https://cloud.google.com/datastore/docs/bulk-delete).

However the page this links to [says that this is deprecated](https://cloud.google.com/dataflow/docs/guides/templates/provided-utilities#datastore-bulk-delete-[deprecated]).

It suggests to use the firestore bulk delete process as a replacement, but from past experience it is usually the case that firestore APIs are not compatible with cloud datastore.

Is this just an oversight in the documentation, or has this feature of cloud data store been deprecated with no viable replacement?

**Comment by telpirion** [comment]
I'm going to close this GitHub issue as it pertains more to the behavior of the Datastore service rather than the Go client library for Datastore.

I encourage you to raise this issue on the [public issue tracker for Datastore](https://issuetracker.google.com/issues/new?component=187197&template=0).
