### ISSUE TITLE
pubsub: `maxExtention` upper bound is added to the iterator's ack distribution.

### ISSUE THREAD

**Issue by jeniok12** [googleapis/google-cloud-go#6123]
**Client**

PubSub

**Environment**

golang:1.17.11 linux/amd64 Docker on GKE

**Go Environment**

$ go version
```
go version go1.17.11 linux/amd64
```

$ go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.11"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2525013341=/tmp/go-build -gno-record-gcc-switches"
```

**Code**
https://github.com/googleapis/google-cloud-go/blob/dcca23fa48bff5ae51ce337df5c0f0b8ad408dc6/pubsub/iterator.go#L162-L167

**Expected behavior**
If no `ReceiveSettings.MaxExtensionPeriod` is set, the ack deadline should not be extended.

**Actual behavior**
Ack deadline is extended once by 10 minutes.

**Screenshots**
When GKE deployment is scaling down, there is an increase in `oldest message age`.
![image](https://user-images.githubusercontent.com/18429787/171839012-1100f14a-1d0b-45eb-a1b7-8a79b49a5110.png)

**Additional context**
Started after upgrading to v1.22.0.

**Comment by hongalex** [comment]
Thanks for filing an issue, this will be fixed in the next release!
