### ISSUE TITLE
bigtable: `loadtest` and `scantest` cannot import a go program `cbt`

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-cloud-go#6124]
**Client**

bigtable

**Environment**

any; tested here on Debian linux

**Go Environment**

```
$ go version
go version go1.19-pre2 cl/451353751 +37eae7ce94 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/nherring/.cache/go-build"
GOENV="/usr/local/google/home/nherring/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/local/google/home/nherring/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/local/google/home/nherring/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/google-golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/google-golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19-pre2 cl/451353751 +37eae7ce94"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build434925960=/tmp/go-build -gno-record-gcc-switches"
```

**Code**

```go
import "cloud.google.com/go/cbt"
```

**Expected behavior**

`$ go install cloud.google.com/go/bigtable/cmd/loadtest@main` succeeds.

**Actual behavior**

```
$ go install cloud.google.com/go/bigtable/cmd/loadtest@main
go/pkg/mod/cloud.google.com/go/bigtable@v1.13.1-0.20220602163155-70c3c843847a/cmd/loadtest/loadtest.go:37:2: import "cloud.google.com/go/cbt" is a program, not an importable package
```

**Additional context**

After cbt was broken out into its own separate repo, the imports were refactored, but they do not work because cbt is no longer a package.

**Comment by telpirion** [comment]
That's not good! Let me take a quick look.

**Comment by telpirion** [comment]
Hmm, we'll need to look at this a bit more deeply. Try `go install cloud.google.com/go/bigtable/cmd/loadtest@latest` -- that seems to be working for me.

**Comment by chressie** [comment]
You should be able to repro this with go install cloud.google.com/go/bigtable/cmd/loadtest@main, which will use the latest commit on the main branch.

**Comment by telpirion** [comment]
@chressie I'm able to repro this issue without any problem (thank you for the tip, though!). I think the fix here is to export the Config logic from `cbt` that loadtest and scantest rely on. I'll create an issue in the `cbt` repo to track this work.

**Comment by enocom** [comment]
Here's a workaround in the meantime:

```
go install cloud.google.com/go/bigtable/cmd/loadtest@8cdfe257d52cfeab60daec1be67f5fb9075077d6
```

**Comment by Capstan** [comment]
@telpirion I'm trying to import `cbt` into the monorepo and due to the one-version rule, having both that `Config` and the older bigtable's cbt's `Config` around simultaneously would violate it. The `go install` was just a short repro of the issue I'm having while trying to wire it up internally. So I'll wait until there's a `cbt` that will work for both and/or changes to `loadtest` or `scantest` I can apply as a temporary patch.

**Comment by telpirion** [comment]
Closing this issue as it has been resolved internally.
