### ISSUE TITLE
datastore: uncomment `!=`, `in`, and `not-in` test cases in integration_test

### ISSUE THREAD

**Issue by telpirion** [googleapis/google-cloud-go#6184]
The test GCP project for this repro needs updating to allow usage of the `!=`, `in`, and `not-in` operators. Once this update has occurred, we need to uncomment the integration tests for these operations.

**Comment by tekkamanendless** [comment]
Are you referring to the Datastore emulator?  As of July 2 (the last time that I checked), the emulator does not support the new operators, but the production Datastore does.

**Comment by telpirion** [comment]
That's good to know that you're seeing these features in prod! Thank you @tekkamanendless .
