### ISSUE TITLE
spannertest: add support for dropping Foreign Keys

### ISSUE THREAD

**Issue by gmontagu** [googleapis/google-cloud-go#6254]
**Is your feature request related to a problem? Please describe.**
When testing a SQL migration DDL statement and attempting to drop a Foreign Key from a table, spannertest throws the error: `(details: rpc error: code = Unimplemented desc = unhandled DDL table alteration type spansql.DropConstraint)` 

**Describe the solution you'd like**
Support for DROP CONSTRAINT call when using spannertest.

**Describe alternatives you've considered**
Forgoing adding the DDL statement to the migration script and manually running the command against spanner. But then we lose the ability to spin up new in memory spanner instances with this constraint droppd.

**Additional context**
Additional options are also not yet supported:
SET OPTIONS - `ALTER TABLE {table} ALTER COLUMN {column} SET OPTIONS (allow_commit_timestamp=true); `

**Comment by rahul2393** [comment]
Hello @gmontagu can you please share the DDL command to replicate the issue please.

**Comment by rahul2393** [comment]
Please use the latest version of client library to validate if it's still failing.
