### ISSUE TITLE
translate: "es-es" to "pt-br"  return "rpc error: code = Internal desc = Internal translation backend error ERROR_UNSUPPORTED_CONTENT_TYPE(8)"

### ISSUE THREAD

**Issue by liule** [googleapis/google-cloud-go#6298]
The following paragraph is translated from "es es" to "pb-br". There is an internal error in the server. We report this error in both python and go client tests

`Gracias a las tecnologías de comprensión del lenguaje natural (CLN) y grafos de conocimiento (KG, porsus siglas en inglés), la IA puede reconocer el significado de las palabras, identificar expresiones similares y calificar de forma inteligente dependiendo de si los estudiantes aciertan las palabras clave a nivel semántico.`

**Comment by codyoss** [comment]
This issue is being tracked internally
Internal issue: 237737439

I will report back when there is more to share, thanks for the report.

**Comment by codyoss** [comment]
It appears the internal bug has been marked fixed. This should no longer be an issue, please let me know otherwise if that is not true.
