### ISSUE TITLE
compute/metadata: make its own module

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#6311]
Now that we generate a compute library we should separate out the metadata package into its own module. This will potentially have a nice benefit of lightening our dependency graph once things rely on it. 

Also in the future it would be nice to have a new version of this package/module that is context aware, see #4483. In order to do that though I think we first need to have a stable module to give people time to update should they choose to do so.

**Comment by liggitt** [comment]
excited to get a tagged version of the dependency-free compute/metadata module so we can help consumers thin out their dependency graphs
