### ISSUE TITLE
logging: Make NewServer usable

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [googleapis/google-cloud-go#6329]
**Is your feature request related to a problem? Please describe.**
Would like to write tests against a component, which uses logging.

**Describe the solution you'd like**
I should be able to use `NewServer` similar to what internal tests are doing.

**Describe alternatives you've considered**
Alternative is to extract an interface and use the interface instead of logging.

**Comment by codyoss** [comment]
I would take a look at our [testing.md](https://github.com/googleapis/google-cloud-go/blob/main/testing.md) for ideas on how to write tests against packages in this repo.
