### ISSUE TITLE
Datastore: Should I rollback after a failed transaction Commit

### ISSUE THREAD

**Issue by OscarVanL** [googleapis/google-cloud-go#6339]
Hi,

I'm a little confused about whether I should be rolling back datastore transactions if the commit operation failed.

My assumption was that if an error occurred during `tx.Commit()`, then I should call `tx.Rollback()` based on this paragraph from the docs:

> If a [transaction](https://cloud.google.com/datastore/docs/concepts/transactions) fails, ensure you try to rollback the transaction. The rollback minimizes retry latency for a different request contending for the same resource(s) in a transaction. Note that a rollback itself might fail, so the rollback should be a best-effort attempt only.

However, I had a look at the RunInTransaction source code from the datastore package and noticed that if `tx.Commit()` has an error the behaviour is not to rollback.

```
func (c *Client) RunInTransaction(ctx context.Context, f func(tx *Transaction) error, opts ...TransactionOption) (cmt *Commit, err error) {
	ctx = trace.StartSpan(ctx, "cloud.google.com/go/datastore.RunInTransaction")
	defer func() { trace.EndSpan(ctx, err) }()

	settings := newTransactionSettings(opts)
	for n := 0; n < settings.attempts; n++ {
		tx, err := c.newTransaction(ctx, settings)
		if err != nil {
			return nil, err
		}
		if err := f(tx); err != nil {
			_ = tx.Rollback()
			return nil, err
		}
		if cmt, err := tx.Commit(); err != ErrConcurrentTransaction {
			return cmt, err
		}
		// Pass this transaction's ID to the retry transaction to preserve
		// transaction priority.
		if !settings.readOnly {
			settings.prevID = tx.id
		}
	}
	return nil, ErrConcurrentTransaction
}
```

I just wanted to clarify that this is the behaviour I should also follow in my transactions-based code that does not run via `RunInTransaction`?

Thank you!

**Comment by loeffel-io** [comment]
This is a pretty easy example how i use rollbacks

```go 
func (service *TodoService) UpdateTodo(ctx context.Context, req *todoprotov1.UpdateTodoRequest) (*todoprotov1.UpdateTodoResponse, error) {
	var err error
	var todoproto *todoprotov1.Todo
	var tx *googlespanner.ReadWriteStmtBasedTransaction

	if tx, err = service.TodoDatabaseRepository.Client().NewTransaction(ctx); err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	defer func() {
		if r := recover(); r != nil {
			tx.Rollback(ctx)
			panic(r)
		}
	}()

	var todos []tododatabasemodel.IDatabaseModel
	if todos, err = service.TodoDatabaseRepository.Todo(ctx, tx); err != nil {
		tx.Rollback(ctx)
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	if len(todos) != 1 {
		tx.Rollback(ctx)
		return nil, status.Errorf(codes.NotFound, fmt.Sprintf("todo not found: %s", string(req.GetId())))
	}

	var todo = todos[0].(*tododatabasemodelv1.TodoDatabaseModel)
	todo.Content = req.GetContent()

	if err = service.TodoDatabaseRepository.UpdateTodo(tx, todos[0]); err != nil {
		tx.Rollback(ctx)
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	if _, err = tx.Commit(ctx); err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	if todoproto, err = todos[0].ToProto(); err != nil {
		return nil, status.Errorf(codes.Internal, err.Error())
	}

	return &todoprotov1.UpdateTodoResponse{
		Todo: todoproto,
	}, nil
}
```

**Comment by OscarVanL** [comment]
Thanks, our code looked pretty similar to this except for the missing panic recovery, this is a great suggestion as we recently had some panics in API calls that would lock up our datastore because the transaction was not rolled back or committed.

We eventually switched from using `NewTransaction`, because unlike `RunInTransaction` it does not retry the transaction in the case of a conflicting transaction (I.E, when you start the transaction there is another ongoing transaction operating on the same entities). Comparably, RunInTransaction retries 3 times in the case of transaction contention.

However specifically I wanted to know if it was expected to call `Rollback` if the `Commit` call fails when using NewTransaction.

**Comment by telpirion** [comment]
It sounds like this issue has been resolved. I'll close this for now.

Off hand, I would use `RunInTransaction` due to its improved retry logic.
