### ISSUE TITLE
logging: Resource detection for 2nd gen of Cloud Functions is detected as CloudRun resource

### ISSUE THREAD

**Issue by minherz** [googleapis/google-cloud-go#6367]
**Client**

Logging

**Environment**

Cloud Functions 2nd gen(eration)

**Actual behavior**
When application that ingest logs using `logging` runs on 2nd gen Cloud Functions resource, the ingested logs are populated with the resource metadata of the `cloud_run_revision`](https://cloud.google.com/monitoring/api/resources#tag_cloud_run_revision) resource type.

**Expected behavior**

The ingested logs will be populated with the resource metadata for the [`cloud_function`](https://cloud.google.com/monitoring/api/resources#tag_cloud_function) resource type.

**Additional context**

Recent changes to the 2nd gen Cloud Functions removed populating the `product_name` file with the correct resource type. Additionally, the 2nd gen Cloud Functions resource has environment variables that pass both [CloudRun resource detection](https://github.com/googleapis/google-cloud-go/blob/399840483c20cffcc88db9f5168eb490ff1e52be/logging/resource.go#L129) and [Cloud Functions resource detection](https://github.com/googleapis/google-cloud-go/blob/399840483c20cffcc88db9f5168eb490ff1e52be/logging/resource.go#L104). 

Unfortunately, for 2nd gen implementation it is impossible to detect between these two resource types independently (i.e. to get the same results when running detection functions in any order).

**Comment by daniel-sanche** [comment]
My first question was why this isn't showing up on the environment tests, but looking at the tests, it looks like they're being skipped and marked as a success. I opened a bug for that: https://github.com/googleapis/google-cloud-go/issues/6368

It looks like the other languages are passing (unless they're just using the old version of Functions). I'll look into this in more detail soon

**Comment by daniel-sanche** [comment]
I spun up a new environment test for functions gen 2, and I'm not seeing this problem in the logs created there: 
![image](https://user-images.githubusercontent.com/3914119/190827043-65e11cce-dcc3-41d6-b391-6827e93a2eb0.png)

This must have been either fixed in recent releases, or fixed on the agnet side
