### ISSUE TITLE
all: sync branch workflow is triggered and fails on forked repositories by default

### ISSUE THREAD

**Issue by neglect-yp** [googleapis/google-cloud-go#6398]
Sync branch workflow has a schedule trigger.
https://github.com/googleapis/google-cloud-go/blob/8a8ba85311f85701c97fd7c10f1d88b738ce423f/.github/workflows/sync_branch.yaml#L2-L4

And it was triggered on my fork then it failed because the required secret was not set.
https://github.com/neglect-yp/google-cloud-go/actions/runs/2715223009

I can configure to disable GitHub Actions on my fork so that workflows are not triggered, but I think it's better that workflows are not triggered or all jobs in the workflow are skipped on forks by default.

**Comment by noahdietz** [comment]
Ack, I will configure it to not run on forks.

**Comment by neglect-yp** [comment]
Thank you!
