### ISSUE TITLE
storage: revert 6443 before merging storage-refactor to main

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-go#6444]
We created a separate kokoro job to run continous build on branch storage-refactor; however it required making a change to the continuous.sh(#6443) build script which must be reverted before merging the branch back into main.

This is a tracking issue to follow-up and revert the change.

**Comment by noahdietz** [comment]
Fixed by https://github.com/googleapis/google-cloud-go/pull/6465/commits/9757864c9a0704e5f33257cefef95ce06de6f10f
