### ISSUE TITLE
storage: add JSON API implementation for Reader

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-go#6462]
Currently the Reader uses the XML API to download objects from GCS, due to performance differences as of a few years ago.

These differences are much smaller or nonexistent these days. In addition, certain features are missing from the GCS XML API that users might want (e.g. NotMatch preconditions, see #5890 ).

This issue is to add a JSON API implementation to the Reader. The exported Reader surface would remain the same. Default would remain to use XML to avoid breaking current users (at least until the next major release).

**Comment by danielduhh** [comment]
Fixed by https://github.com/googleapis/google-cloud-go/pull/7158
