### ISSUE TITLE
pubsub: when using pubsub emulator GOOGLE_APPLICATION_CREDENTIALS should not be needed

### ISSUE THREAD

**Issue by rainoko** [googleapis/google-cloud-go#6466]
**Client**

PubSub

**Environment**

Docker google/cloud-sdk:emulators

**Go Environment**

go version go1.18.1 linux/amd64

**Code**
```
_ = os.Setenv("PROJECT_ID", "local")
_ = os.Setenv("PUBSUB_EMULATOR_HOST", "localhost:8085")
```

**Expected behavior**

should work without specifying  GOOGLE_APPLICATION_CREDENTIALS

**Actual behavior**

google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information

**Additional context**

right now workaround is to specify some dummy credentials.json like
```
{
  "source_credentials": {
    "client_id": "...",
    "client_secret": "...",
    "refresh_token": "...",
    "type": "authorized_user"
  },
  "service_account_impersonation_url": "dummy",

  "type": "impersonated_service_account"
}
```

**Comment by hongalex** [comment]
Which version of the client library are you using? I tried testing this by unsetting `GOOGLE_APPLICATION_CREDENTIALS` and it didn't give me the error message you provided.

**Comment by hongalex** [comment]
Closing due to lack of response but feel free to comment if this is still affecting you.
