### ISSUE TITLE
Bigtable: stream terminated by RST_STREAM with error code: INTERNAL_ERROR is not retried by client

### ISSUE THREAD

**Issue by aravindsrinivasan** [googleapis/google-cloud-go#6476]
Package: `cloud.google.com/go/bigtable v1.13.0`

When our bigtable instance has high throughput we see the following error on occasion:
```
rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR
```
This to me looks like a transient error that should be retried by the client. I see the Spanner client retrying this exact error:
https://github.com/googleapis/google-cloud-go/blob/5a2ed6b2cd1c304e0f59daa29959863bff9b5c29/spanner/retry.go#L59-L70

Could also do the same in the Bigtable client? Or is this error actually not retryable in the context of Bigtable?

**Comment by aravindsrinivasan** [comment]
Any update here?

**Comment by bhshkh** [comment]
Not yet picked up. Will pick up soon
