### ISSUE TITLE
bigquery/storage: Wrong error return from stream.Recv(): "Request contains an invalid argument" with code 3

### ISSUE THREAD

**Issue by Av1shay** [googleapis/google-cloud-go#6483]
**Client**

cloud.google.com/go/storage v1.15.0 (BigQueryWriteClient)

**Environment**

MacOS

**Go Environment**

$ go version
go version go1.18.1 darwin/arm64
$ go env

**Code**

```go
package main

import (
	storage "cloud.google.com/go/bigquery/storage/apiv1"
	"cloud.google.com/go/bigquery/storage/managedwriter/adapt"
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	storagepb "google.golang.org/genproto/googleapis/cloud/bigquery/storage/v1"
	"log"
)

func main() {
	ctx := context.Background()
	bigqueryWriteClient, err := storage.NewBigQueryWriteClient(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer bigqueryWriteClient.Close()

	rows := getDataFromSomeWhere()
	stream, err := bigqueryWriteClient.AppendRows(ctx)
	if err != nil {
		log.Fatal(err)
	}
	descriptor, err := adapt.NormalizeDescriptor(rows[0].ProtoReflect().Descriptor())
	if err != nil {
		log.Fatal(err)
	}
	streamName := fmt.Sprintf("projects/%s/datasets/%s/tables/%s/streams/_default", "project-id", "dataset-id", "table-id")

	data := make([][]byte, len(rows))
	for i, row := range rows {
		buf, err := proto.Marshal(row)
		if err != nil {
			t.Fatal(err)
		}
		data[i] = buf
	}

	go func() {
		err = stream.Send(&storagepb.AppendRowsRequest{
			WriteStream: streamName,
			Rows: &storagepb.AppendRowsRequest_ProtoRows{
				ProtoRows: &storagepb.AppendRowsRequest_ProtoData{
					WriterSchema: &storagepb.ProtoSchema{
						ProtoDescriptor: descriptor,
					},
					Rows: &storagepb.ProtoRows{
						SerializedRows: data,
					},
				},
			},
		})
		if err != nil {
			log.Fatal(err)
		}
		stream.CloseSend()
	}()
	for {
		_, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

**Expected behavior**
Expected the code to work, or if the limit exceeded, to know that from the error message.

**Actual behavior**

When trying to send large number of rows at once, it fails with error: "Request contains an invalid argument" error code 3, even though it doesn't seems to be an issue with the arguments- All rows have the same data. 
When I try to send 20000 rows at once (6400MB) it works well, when I try to send 30000 rows at once (9600MB) it fails with the above error.
It seems like it related to reaching limit in the API for max request size.

**Screenshots**

**Additional context**

**Comment by shollyman** [comment]
This is the expected behavior, and documented as part of [`AppendRowsRequest`]( https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.AppendRowsRequest):

> The size of a single AppendRowsRequest must be less than 10 MB in size. Requests larger than this return an error, typically INVALID_ARGUMENT.

**Comment by shollyman** [comment]
I agree that the error response isn't ideal, but the size limit is not enforced by the write API directly.  I'm going to close this, but if I've missed something please let me know.
