### ISSUE TITLE
bigquery: managedwriter.WithAppendRowsCallOption does not pass CallOptions when creating the raw AppendRows client

### ISSUE THREAD

**Issue by acleone** [googleapis/google-cloud-go#6487]
**Client**

cloud.google.com/go/bigquery@v1.37.0

#5078 added `managedwriter.WithAppendRowsCallOption`, but the CallOptions are not passed to `streamFunc` when creating the underlying `AppendRows` client, so `WithAppendRowsCallOption` does nothing. This seems to be an oversight when calling `streamFunc` in `ms.open`.

**Code**

 https://github.com/googleapis/google-cloud-go/blob/bigquery/v1.37.0/bigquery/storage/managedwriter/client.go#L104 :

```go
		open: func(streamID string, opts ...gax.CallOption) (storagepb.BigQueryWrite_AppendRowsClient, error) {
			arc, err := streamFunc(
				// Bidi Streaming doesn't append stream ID as request metadata, so we must inject it manually.
-				metadata.AppendToOutgoingContext(ctx, "x-goog-request-params", fmt.Sprintf("write_stream=%s", streamID)))
+				metadata.AppendToOutgoingContext(ctx, "x-goog-request-params", fmt.Sprintf("write_stream=%s", streamID)),
+				opts...)
			if err != nil {
				return nil, err
			}
			return arc, nil
		},
```

Repro:

```go
package main

import (
	"cloud.google.com/go/bigquery/storage/managedwriter"
	"github.com/googleapis/gax-go/v2"
	"google.golang.org/grpc"
)

func main() {
	managedClient, _ := managedwriter.NewClient(...)
	gaxOpt := gax.WithGRPCOptions(grpc.MaxCallSendMsgSize(10 * 1024 * 1024))
	writerOpts := []managedwriter.WriterOption{
		managedwriter.WithDestinationTable(tablePath),
		managedwriter.WithType(managedwriter.DefaultStream),
		managedwriter.WithSchemaDescriptor(...),
		managedwriter.WithAppendRowsCallOption(gaxOpt),
	}
	managedStream, _ := managedClient.NewManagedStream(
		context.Background(),
		writerOpts...)
	// managedStream.open does not correctly pass opts to AppendRows
	// func (c *BigQueryWriteClient) AppendRows(ctx context.Context, opts ...gax.CallOption) (storagepb.BigQueryWrite_AppendRowsClient, error)
	
}
```

**Expected behavior**

managedClient calls `func (c *BigQueryWriteClient) AppendRows(ctx context.Context, opts ...gax.CallOption) (storagepb.BigQueryWrite_AppendRowsClient, error)` with the options given in `managedwriter.WithAppendRowsCallOption`

**Actual behavior**

No CallOptions are passed to `BigQueryWriteClient.AppendRows`.

**Comment by shollyman** [comment]
Great spot, thanks for reporting. The fix is trivial, but the testing is challenging given the bidi nature of the stream and how the "real" stream opener differs from a testing function.

I'll send out the fix, and see if I can come up with a reasonable way to test this.
