### ISSUE TITLE
bigquery: schema field of type NUMERIC is not assignable to struct field

### ISSUE THREAD

**Issue by ejstembler** [googleapis/google-cloud-go#6492]
**Client**

BigQuery

**Environment**

golang:1.18

**Go Environment**

go version go1.18.5 darwin/amd64

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/my-user/Library/Caches/go-build"
GOENV="/Users/my-user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/my-user/.asdf/installs/golang/1.18.5/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/my-user/.asdf/installs/golang/1.18.5/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/my-user/.asdf/installs/golang/1.18.5/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/my-user/.asdf/installs/golang/1.18.5/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/my-user/Projects/my-project/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j3/zqjvh17x5hz0d87m0wtkq6cm0000gn/T/go-build792818999=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

```go
package main

type MyRecord struct {
    Quantity float64 `bigquery:"Quantity,nullable"` // NUMERIC BigQuery type
    // other fields...
}
```

```go
package main

func (repo *MyBigQueryRepository) FindMyRecordById(id string) (MyRecord, error) {

        // snip...

	var record MyRecord
	for {

		err := it.Next(&record)
		if err == iterator.Done {
			break
		}
		if err != nil {
			return MyRecord{}, err
		}
	}
	return record, nil
}
```

**Expected behavior**

BigQuery row loaded into struct.

**Actual behavior**

```
bigquery: schema field Quantity of type NUMERIC is not assignable to struct field Quantity of type float64
```

**Notes**

I have a record `struct` in Go which attempts to match the corresponding BigQuery schema. However, I haven't found any documentation on how certain BigQuery types should be matched to Go's types.

For this particular example, nullable `NUMERIC`, I've tried using: `float64`, `bigquery.NullFloat64` and I've even tried using `null.Float` from gopkg.in/guregu/null.v4 which I used for Postgres databases.

It would be nice if there were documentation somewhere which illustrated the BiqQuery data types to Go data types. For my particular table, I have other BigQuery data types I need to support besides nullable `NUMERIC`, nullable `BIGNUMERIC`, nullable `BOOLEAN`, nullable `DATE`, nullable `TIMESTAMP`, etc...

**Comment by ejstembler** [comment]
After reading the unit tests, [bigquery/value_test.go](https://github.com/googleapis/google-cloud-go/blob/835fe4fe59f4a3c64c5762a530228d5369618897/bigquery/value_test.go) , I discovered that nullable `NUMERIC` maps to `*big.Rat` from `math/big`.

This should be documented somewhere.

**Comment by shollyman** [comment]
Sorry this wasn't clearer. It looks like we've allowed the docs to drift a bit.  https://pkg.go.dev/cloud.google.com/go/bigquery#RowIterator.Next doesn't inform the user (BQ->Go datatypes), but 
https://pkg.go.dev/cloud.google.com/go/bigquery#InferSchema does (Go->BQ).

Reopening this to clarify the docs a bit more.

**Comment by alvarowolfx** [comment]
Hopefully this is resolve by #6560
