### ISSUE TITLE
spanner: Is there order by dynamic parameter for spanner.Statement

### ISSUE THREAD

**Issue by jianjungki** [googleapis/google-cloud-go#6496]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when use 
`iter := txn.Query(ctx, spanner.Statement{
		SQL: "SELECT * FROM test ORDER BY @orderBy",
		Params: map[string]interface{}{
			"orderBy":     orderBy
	},
})
`
That will generate `SELECT * FROM test ORDER BY "id desc"`
Which I need is `SELECT * FROM test ORDER BY id desc`, how can I achive that
Because we need dynamic sort for these code.

**Describe the solution you'd like**
Perhaps can add a string type for doing that?

**Comment by rahul2393** [comment]
@jianjungki Only literal values can be passed as params, for your use case I would suggest to build the SQL string using 

```
sql := fmt.Sprintf("SELECT * FROM test ORDER BY %v", orderBY)
```
Use the above formatted sql for query.
