### ISSUE TITLE
httpreplay: Get error "flag redefined: v" when trying to get new Recorder

### ISSUE THREAD

**Issue by tomasbanet** [googleapis/google-cloud-go#6501]
httpreplay version: v0.103.0

**Code**

```go
_, err := httpreplay.NewRecorder("gcs-recorder-output.txt", []byte{})
if err != nil {
  return nil, err
}
```

**Expected behavior**

`httpreplay.Recorder` is instantiated without any errors.

**Actual behavior**

Got the following runtime error when trying to run the compiled binary:
```
panic: ./bin flag redefined: v

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00004e1e0, {0x22c1d40, 0xc0003294d8}, {0x22b2b69, 0x1}, {0x20dc402, 0x9})
	/usr/local/Cellar/go/1.18.2/libexec/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).IntVar(...)
	/usr/local/Cellar/go/1.18.2/libexec/src/flag/flag.go:658
flag.(*FlagSet).Int(0x8?, {0x22b2b69, 0x1}, 0x0, {0x20dc402, 0x9})
	/usr/local/Cellar/go/1.18.2/libexec/src/flag/flag.go:671 +0x7e
flag.Int(...)
	/usr/local/Cellar/go/1.18.2/libexec/src/flag/flag.go:678
github.com/google/martian/v3.init()
	/Users/tomasb/go/src/arista/vendor/github.com/google/martian/v3/init.go:24 +0x65
```

It looks like "github.com/google/martian/v3" is being imported twice. In vendor/cloud.google.com/go/httpreplay/internal/proxy/log.go and in vendor/cloud.google.com/go/httpreplay/internal/proxy/record.go. This causes the Init function from vendor/github.com/google/martian/v3/init.go to run:
```
var (
	level = flag.Int("v", 0, "log level")
)

// Init runs common initialization code for a martian proxy.
func Init() {
	flag.Parse()
	mlog.SetLevel(*level)
}
```

This seems to cause the flag parsing error.

As a work-around you can do:
```
// Init runs common initialization code for a martian proxy.
func Init() {
	level := flag.Int("v", 0, "log level")
	flag.Parse()
	mlog.SetLevel(*level)
}
```

which seems to run fine.

**Go Environment**

$ go version
`go version go1.18.2 darwin/amd64`

**Comment by codyoss** [comment]
Hey, thanks for the report. Quickly reading this I would say this is an issue in martian. It looks like you found a relevant issue too. Can this be closed out. I don't believe we have a v flag at all unless I am missing something.

**Comment by codyoss** [comment]
Closing due to lack of response.

**Comment by tomasbanet** [comment]
Hi. Sorry. Looks like martian maintainers merged a fix into master 10 days ago (it's in v3.3.2). Maybe we could bump up the github.com/google/martian/v3 dependency to this version? (currently it's v3.2.1)

**Comment by codyoss** [comment]
Sure, I can do that. You can always also explicitly require a higher version in your module to work around this. Just underscore import martian and depend on the latest.

**Comment by codyoss** [comment]
Until we drop support for Go 1.15 we can't upgrade this dep in our code. It use a symbol `net.ErrClosed` from 1.16 in its latest code. We will update once we have a min support version >=1.16

**Comment by tomasbanet** [comment]
> Sure, I can do that. You can always also explicitly require a higher version in your module to work around this. Just underscore import martian and depend on the latest.
Good suggestion. Thanks
