### ISSUE TITLE
errorreporting: Enable connectionless testing

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [googleapis/google-cloud-go#6508]
**Client**

ErrorReporting

**Environment**

CI machine without connection to GCP

**Code**

e.g.
```go
package main

func main() {
  ec, err := errorreporting.NewClient(
    context.Background(),
    "testproject",
    errorreporting.Config{
      ServiceName:    serviceName,
      ServiceVersion: "v1.0",
    },
    option.WithGRPCConn(conn),
    option.WithoutAuthentication(),
    option.WithGRPCDialOption(grpc.WithInsecure()
  )
}
```

**Expected behavior**

There should be a way of spawning a local server and then be able to call `NewClient` with `conn`.

**Actual behavior**

Test currently override `errorreporting.newClient`.

**Additional context**

See `logging/v2` for how it can be done.

**Comment by codyoss** [comment]
This is possible today with basically the options you are passing there. Is something not working as you expect? Here is a general guide on testing our clients: [testing.md](https://github.com/googleapis/google-cloud-go/blob/main/testing.md)

**Comment by AndreasBergmeier6176** [comment]
Maybe I am too dense - but can you provide an example how you would build `conn`? I cannot seem to get a `conn` for **errorreporting**.

**Comment by codyoss** [comment]
Did you take a look at the testing guide I sent? That should have an example you don't need to specify a conn, just and endpoint override.

**Comment by AndreasBergmeier6176** [comment]
Did get it. Thanks.
