### ISSUE TITLE
storage: Error on Service Account Impersonation

### ISSUE THREAD

**Issue by acham1** [googleapis/google-cloud-go#6518]
After upgrading the storage client `cloud.google.com/go/storage` above 1.16.0, service account impersonation via `"google.golang.org/api/option"#ImpersonateCredentials` ceases to behave as expected.

## Where is the breaking version?

The breaking version is somewhere between v1.16.1 .. v1.21.1 (inclusive)

## How to reproduce?

Background: 
- My default service account does Not have permission to list objects in the bucket.
- My impersonated service account Does have permission to list objects in the bucket.
- When I downgrade `cloud.google.com/go/storage` in go.mod to 1.16.0, this script runs to completion.
- If I upgrade to a higher version, the impersonation fails and the script exits with an error.

```
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/storage"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
)

var serviceAccountID = "<REDACTED>"

func example(ctx context.Context) error {
	client, err := storage.NewClient(
		ctx,
		option.ImpersonateCredentials(serviceAccountID),
		option.WithScopes(
			"https://www.googleapis.com/auth/cloud-platform",
		),
	)

	if err != nil {
		return fmt.Errorf("init storage client: %w", err)
	}

	objects := client.Bucket("example-cf898b45-2797-41c7-8646-3663fde97127").Objects(ctx, nil)
	for {
		_, err := objects.Next()
		if err == iterator.Done {
			break
		} else if err != nil {
			return fmt.Errorf("list objects: %w", err)
		} else {
			// Do Work
		}
	}

	return nil
}

func main() {
	ctx := context.Background()

	err := example(ctx)
	if err != nil {
		panic(err)
	}
}
```

These are the error logs:
```
panic: list objects: Get "https://storage.googleapis.com/storage/v1/b/example-cf898b45-2797-41c7-8646-3663fde97127/o?alt=json&delimiter=&endOffset=&includeTrailingDelimiter=false&pageToken=&prefix=&prettyPrint=false&projection=full&startOffset=&versions=false": impersonate: status code 403: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}


goroutine 1 [running]:
main.main()
	/Users/alan/Code/backend/main.go:47 +0x45
exit status 2
```

**Comment by codyoss** [comment]
You likely need to provide more scopes. Here are the scopes the storage client usually passed by default: https://github.com/googleapis/google-cloud-go/blob/main/storage/storage.go#L149

Also that impersonation mechanism that you are using has limitations. Please use the tokensource option and the [impersonate](https://pkg.go.dev/google.golang.org/api/impersonate) package instead for better configurability.

**Comment by acham1** [comment]
Thanks; I updated the scopes in my client constructor to include the scopes from the blob linked above, but am still encountering the same error in OP for now:

```
	client, err := storage.NewClient(
		ctx,
		option.ImpersonateCredentials(serviceAccountID),
		option.WithScopes(
			storage.ScopeFullControl,
			"https://www.googleapis.com/auth/cloud-platform",
		),
	)
```

I'm trying the suggestion about the `tokensource` option next 👍

**Comment by acham1** [comment]
@codyoss swapping out the impersonation mechanism from one based on `google.golang.org/api/option#ImpersonateCredentials` to one based on `google.golang.org/api/impersonate#CredentialsTokenSource` seems to resolve the error; thanks!

```
	ts, err := impersonate.CredentialsTokenSource(ctx, impersonate.CredentialsConfig{
		TargetPrincipal: serviceAccountID,
		Scopes:          []string{"https://www.googleapis.com/auth/cloud-platform"},
	})
	if err != nil {
		return fmt.Errorf("init credentials token source: %w", err)
	}

	client, err := storage.NewClient(ctx, option.WithTokenSource(ts))
	if err != nil {
		return fmt.Errorf("init storage client: %w", err)
	}
```

**Comment by codyoss** [comment]
Awesome, glad we could help. I will officially deprecate that experimental option soon.
