### ISSUE TITLE
pubsub: undefined: pubsub.AckResult when updating Go version cloud.google.com/go/pubsub v1.24.0 => v1.25.0 

### ISSUE THREAD

**Issue by chrisntb** [googleapis/google-cloud-go#6555]
This morning when we update our dependencies using command `go get -u all; go mod tidy && go mod vendor` v1.25.0 of `cloud.google.com/go/pubsub` is pulled down and this causes our build to fail with these errors:

vendor/cloud.google.com/go/pubsub/message.go:109:26: undefined: pubsub.AckResult
vendor/cloud.google.com/go/pubsub/message.go:112:34: undefined: pubsub.AcknowledgeStatus
vendor/cloud.google.com/go/pubsub/iterator.go:553:13: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:594:14: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:760:14: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:762:14: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:772:13: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:774:13: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:776:13: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:781:12: undefined: pubsub.SetAckResult
vendor/cloud.google.com/go/pubsub/iterator.go:781:12: too many errors

**Comment by gnagel** [comment]
Same here 🤞

**Comment by Tigraine** [comment]
Same here ☝️

**Comment by codyoss** [comment]
Thanks for the report and sorry for the inconvenience. A release should be out today to fix these error but in the meantime please downgrade the pubsub module back to 1.24.0 or upgrade cloud.googe.com/go to v0.104.0

**Comment by codyoss** [comment]
Running `go get cloud.google.com/go/pubusb@1.25.1` should fix this issue.
