### ISSUE TITLE
compute: Received 500 Back From Get gstatic.com/iap/verify/public_key-jwk When Using Workload Identity on GKE

### ISSUE THREAD

**Issue by visortim** [googleapis/google-cloud-go#6574]
**Client**

Metadata

**Environment**

Alpine Docker on GKE w/ Workload Identity Auth

**Go Environment**

Go 1.16 using google-cloud-go SDK versions v0.82.0 and v0.102.0
I noticed some robustness improvements to the code, so I tried upgrading, but it had no effect.
Kube Cluster 1.23.8-gke.1900
Node Pool Version 1.22.10-gke.600

**Code**

where m.validator -> *idtoken.Validator from "google.golang.org/api/idtoken"
```
	payload, err := m.validator.Validate(ctx, idToken, [REDACTED])
	if err != nil {
		return nil, errors.Wrap(err, "validating id token")
	}
```

**Expected behavior**

I would expect the behavior to be the same for this function call regardless of how the service account is authenticated, i.e. validate the token and move on. The URL in question that appears to be failing with a 500 response is publicly accessible at [https://www.gstatic.com/iap/verify/public_key-jwk](https://www.gstatic.com/iap/verify/public_key-jwk)

**Actual behavior**

Previously, it was authenticated to the service account via a json file mounted kubernetes secret set to the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. Upon changing the application to run as the *same* service account via the GKE workload identity feature, with zero other changes to the infrastructure or code, the SDK fails internally when making this get request: 
`validating id token: Get “https://www.gstatic.com/iap/verify/public_key-jwk”: compute: Received 500 Internal Server Error`

**Additional context**
All of the cluster's applications (except this one) are now on workload identity connected auth and work fine. This application's workfload identity auth seems to work fine for all other aspects of this application's needs. Additionally, the metadata server seems to be available and responding as I would expect and the kube yaml has the `iam.gke.io/gke-metadata-server-enabled: "true"` for each service with a workload identity authenticated service account.

**Possibly Related**
https://github.com/googleapis/google-cloud-go/issues/2750

**Comment by visortim** [comment]
I have confirmed that the decoded JWTs from each deployment type are identical in the first two segments except the expiry and both look like the below:
```
{
    "aud": "/projects/[REDACTED]/global/backendServices/[REDACTED]",
    "azp": "/projects/[REDACTED]/global/backendServices/[REDACTED]",
    "email": "[REDACTED]@[REDACTED].com",
    "exp": 1661546126,
    "hd": "[REDACTED].com",
    "iat": [REDACTED],
    "iss": "https://cloud.google.com/iap",
    "sub": "accounts.google.com:[REDACTED]"
}
```

**Comment by codyoss** [comment]
@visortim Can you please share how you are creating the validator? A validator does not require any auth to work, so if you are trying to pass a tokensource or something like this, please try to remove that.

**Comment by codyoss** [comment]
@visortim Try not passing any scopes, should not be required.

**Comment by visortim** [comment]
> @visortim Try not passing any scopes, should not be required.

We tried this and it did not work, receiving the following error message: `Invalid OAuth scope or ID token audience provided.`

Interestingly, our git history shows that we only added the scopes when upgrading from `v0.68.0` to `v0.75.0` because it became required. If I remember correctly, the IAP broke without this addition then.

**Comment by codyoss** [comment]
@visortim Where are you getting that error from? I think this is a different issue and does not have anything to do with the validation perhaps. The only two endpoints the validators hits are these: https://github.com/googleapis/google-api-go-client/blob/219f166eed5853b4a78de8cba896404b5a56449b/idtoken/validate.go#L28-L29

Neither require scopes and are publicly available. If you are able to provide a small reproducer maybe I could help. If you have a support contract it may be best to open up a ticket through there instead.

**Comment by visortim** [comment]
> @visortim Where are you getting that error from? I think this is a different issue and does not have anything to do with the validation perhaps. The only two endpoints the validators hits are these: https://github.com/googleapis/google-api-go-client/blob/219f166eed5853b4a78de8cba896404b5a56449b/idtoken/validate.go#L28-L29
> 
> Neither require scopes and are publicly available(I believe you can hit both from your browser for instance). If you are able to provide a small reproducer maybe I could help. If you have a support contract it may be best to open up a ticket through there instead.

I believe this error message (`Invalid OAuth scope or ID token audience provided.`) is simply indicating that the scopes option is required, since we only see this error message when the scopes option with `*` is removed.

I have filed the issue with GCP support now as well and will let you know what they come back with.

**Comment by codyoss** [comment]
I am going to close this issue out for now as I don't think there is anything I can do without looking at some code. If you paste the issue number though for your internal ticket I can try to follow that thread in case I am able to assist.

**Comment by codyoss** [comment]
Actually I have a hunch what might be wrong here. Can you please try moving to the validate function for now to see if that solves the issue?(instead of creating a validator and calling the method)

**Comment by visortim** [comment]
> Actually I have a hunch what might be wrong here. Can you please try moving to the validate function for now to see if that solves the issue?(instead of creating a validator and calling the method)

The validate function call is done interactively on requests. The validator instantiation is done at application startup. The internal GCP case number is 40898899.

**Comment by visortim** [comment]
Hooray, this worked. Thanks for your help.

**Comment by codyoss** [comment]
Awesome, I opened an issue in our other repo to fix the underlying issue. Thanks for the report!
