### ISSUE TITLE
storage: writing to gcs bucket return context deadline exceeded

### ISSUE THREAD

**Issue by wchensc** [googleapis/google-cloud-go#6593]
**Client**
storage: 1.18.2

**Environment**

MacOs local

**Go Environment**
1.18

**Code**

```
f, err := os.Open(localFilePath)
if err != nil {
return err
}
defer f.Close()

wc := g.Client.Bucket(bucket).Object(remoteFilePath).NewWriter(ctx)
// default is 8M, which is way more than what we need for uploading small files (which we do a lot),
// and it causes memory waste for creating such large cache. explicitly set it to 512k
wc.ChunkSize = 512 * 1024

if _, err := stdlib.CancelableCopy(ctx, wc, f); err != nil { 
g.log.Error("Failed to run upload file", "err", err)
//return err
}

if err := wc.Close(); err != nil {
g.log.Error("close error", "err", err)
return err
}


func CancelableCopy (ctx context.Context, dst io.Writer, src io.Reader) (written int64, err error) {
	return io.Copy(dst, readerFunc(func(p []byte) (int, error) {
		select {
		// if context has been canceled
		case <-ctx.Done():
			// stop process and propagate "context canceled" error
			return 0, ctx.Err()
		default:
			// otherwise just run default io.Reader implementation
			return src.Read(p)
		}
	}))
}
```

**Expected behavior**

Successfully uploaded the file.

**Actual behavior**
```
{"err":"Post \"https://storage.googleapis.com/upload/storage/v1/b/BUCKETNAMEo?alt=json\u0026name=R5CNC0E180F%2F2022-08-31+00%3A59%3A20.962252+-0700+PDT+m%3D%2B26.304338150%2Fxxx.apk\u0026prettyPrint=false\u0026projection=full\u0026uploadType=resumable\": context deadline exceeded","lvl":"eror","msg":"Failed to run upload file","t":"2022-08-31T00:59:30.983488-07:00","task":"web server"}
{"lvl":"info","msg":"one block done","t":"2022-08-31T00:59:30.983549-07:00","task":"web server"}
```

Sometimes if we restart the server and do it again it can successfully upload the file. But it only happens 1 in 10 times. Nothing is different between the runs.

**Screenshots**

e.g. A chart showing how messages are slow. Delete if not necessary.

**Additional context**

**Comment by wchensc** [comment]
Thanks @tritone for the timely reply. 

• How long is the context deadline you are setting?
I set the deadline to 10 minutes later. Actually the `context deadline exceeded` is not coming from my end. It is the GCS bucket writer throwing it where I didn't even pass any context. wc.close() also return the same error.
Plus the error returned immediately, not after 10 minutes. I noticed that the error mostly returned when the chunksize is full.


• How large is the file being uploaded?
200M.

• Have these failures been happening for a while, or did they just start recently? (I noticed that the client library version you 
are using was released last year so I assume the application has been in use for a while now).
I just used the lib so i am not sure whether it just happened recently or not.

**Comment by tritone** [comment]
That's interesting and the part about receiving this error immediately seems surprising. Is it possible that the context is somehow getting canceled from elsewhere in your application?

I will try to repro this locally and let you know what I find.

I also recommend using the newest client library release (v1.26.0) if possible, if you're newly building an application.

**Comment by tritone** [comment]
Update: I was unable to repro the issue, either with the most recent client library release or with v1.18.2. I ran 100 iterations of a repro based on yours for each version.

Is it possible that you could make a more minimal runnable repro that recreates the problem for you? I had to make a few changes in my version because of refs not in the snippet, etc.

**Comment by wchensc** [comment]
Thanks a lot. I will work on a mini example today and push to a repo.

**Comment by siriele** [comment]
Hello @wchensc I had a similar problem and I resolved it by checking the context that I was using to create the client as well as the request. 

Can you paste the code that includes the creation of the context you pass into both the  `storage.NewClient` and the `Copy`?
I see in your example code the calls to create the context are not included

**Comment by wchensc** [comment]
@siriele The code of the ctx creation is as follow:
`ctx, _ := context.WithTimeout(context.Background(), 2 * time.Minute).`

How did you solve the problem and what was wrong with the context in your code? Thanks.

**Comment by wchensc** [comment]
@siriele I think I found it. It was because of where I created the client with a short timeout value. Thanks

**Comment by tritone** [comment]
Good to hear that adjusting the context deadline fixed the issue.
