### ISSUE TITLE
iam: No release listed in releases on GitHub

### ISSUE THREAD

**Issue by fdc-viktor-luft** [googleapis/google-cloud-go#6597]
Please list some release information on the package "iam" like you have for instance for "storage". See [here](https://github.com/googleapis/google-cloud-go/releases/tag/storage%2Fv1.26.0).

### Reason
We're using a Renovate-Bot integration which scans for updates on packages and one of our used packages is
`cloud.google.com/go/iam v0.3.0` in our `go.mod`. The following happens now:

<img width="835" alt="Bildschirmfoto 2022-09-01 um 09 34 47" src="https://user-images.githubusercontent.com/17571883/187858303-7964a95e-9e97-48ab-8b59-2b97aaab1feb.png">

It seems like it uses the non-prefixed version v0.104.0 that is listed [here](https://github.com/googleapis/google-cloud-go/releases/tag/v0.104.0).

For another of our dependencies `cloud.google.com/go/pubsub v1.25.1` it correctly reads the version from [here](https://github.com/googleapis/google-cloud-go/releases/tag/pubsub%2Fv1.25.1).

### Request
Can you please add a release for `cloud.google.com/go/iam v0.3.0` similar to the `pubsub` release. I'll inform you then if my issue with Renovate was fixed. Thank you 👍

**Comment by anopheles** [comment]
I think this might be a renovate issue, see https://github.com/renovatebot/renovate/issues/8852

**Comment by codyoss** [comment]
https://pkg.go.dev/cloud.google.com/go/iam?tab=versions This is a renovate issue. Please ping the linked thread or create a new bug there. There may be some config option you can pass to make it resolve correct.
