### ISSUE TITLE
Field marked as deprecated is being used by firebase trigger for cloud function

### ISSUE THREAD

**Issue by mogli91** [googleapis/google-cloud-go#6612]
https://github.com/googleapis/google-cloud-go/blob/989cd0e8da8f50ab5d2353b93732b4b997f4c868/functions/metadata/metadata.go#L39

The docs going with the above structs say that the field `RawPath` is only being used by storage in combination with pubsub. Please mention that it is also used by Firebase Realtime Database Triggers (a trigger for cloud functions) to identify the resource (document) that triggered the call.

https://cloud.google.com/functions/docs/calling/realtime-database#functions_firebase_rtdb-go

**Comment by quartzmo** [comment]
You wrote `RawType`, did you mean `RawPath`?

**Comment by mogli91** [comment]
Indeed, thanks for pointing this out. I have updated the issue with `RawPath` instead of `RawType`. Apologies for the typo.

**Comment by quartzmo** [comment]
@mogli91 PTAL at my edit in #6660, and feel free to suggest changes.
