### ISSUE TITLE
dialogflow: docs for using `DetectIntent` in v2 or v3 beta1

### ISSUE THREAD

**Issue by germolinal** [googleapis/google-cloud-go#6613]
**Is your feature request related to a problem? Please describe.**
I am trying to use the Go client library to communicate with a bot that combines intents and knowledge bases. Apparently, `v2` does not allow knowledge bases for now, so I am looking at `v2beta1`

**Describe the solution you'd like**
Is there any documentation on how to do that? I went to the [`v2beta1` documentation](https://pkg.go.dev/google.golang.org/api/dialogflow/v2beta1) and could only find info on how to create a new service:

```go
import "google.golang.org/api/dialogflow/v2beta1"
...
ctx := context.Background()
dialogflowService, err := dialogflow.NewService(ctx)
```

But this object does not seem to relate to what the sable `v2` uses to detect intent:

```go
ctx := context.Background()
	c, err := dialogflow.NewSessionsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &dialogflowpb.DetectIntentRequest{
		// TODO: Fill request struct fields.
		// See https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/dialogflow/v2#DetectIntentRequest.
	}
	resp, err := c.DetectIntent(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
```

**Describe alternatives you've considered**
I guess I could migrate to Typescript, but I'd rather not.

**Additional context**

I am just starting with Google's Go libraries for Cloud Run... am I not getting something?

Thanks!

**Comment by quartzmo** [comment]
The documentation you linked above is for the [google.golang.org/api/dialogflow](https://pkg.go.dev/google.golang.org/api/dialogflow/v2beta1) library, which is part of [Google APIs Client Library for Go](https://github.com/googleapis/google-api-go-client), "auto-generated Go libraries from the Google Discovery Service's JSON description files." Based on the `v2` example provided, I believe you want the documentation for the `v2beta1` client belonging to this repo, which is here:

https://pkg.go.dev/cloud.google.com/go/dialogflow/apiv2beta1

**Comment by germolinal** [comment]
Thanks!!! Everything worked just fine!!!
