### ISSUE TITLE
bigquery: Timestamp is not parsed correctly

### ISSUE THREAD

**Issue by whs** [googleapis/google-cloud-go#6651]
**Client**

BigQuery

**Environment**

Local

**Go Environment**

```
$ go version go1.19 linux/amd64
go version go1.19 linux/amd64
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/whs/.cache/go-build"
GOENV="/home/whs/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/whs/go/pkg/mod"
GONOPROXY="git.wndv.co"
GONOSUMDB="git.wndv.co"
GOOS="linux"
GOPATH="/home/whs/go"
GOPRIVATE="<private>"
GOPROXY="<private>,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v3"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/whs/<private>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3667506472=/tmp/go-build -gno-record-gcc-switches"
```

**Code**

e.g.
```go
package main

func getQuery(job *bigquery.Job) string {
	cfg, err := job.Config()
	if err != nil {
		panic("this block should never hit")
	}
}
```

**Expected behavior**

The error block is not hit

**Actual behavior**

time.ParseError

- Layout = {string} "2006-01-02 15:04:05.999999-07:00"
- Value = {string} "2020-10-15T00:00:00Z"

Looking at the source, the timestamp layout is defined as https://github.com/googleapis/google-cloud-go/blob/6ece8bf62897ef5eb9b0f54fea737c1dd27e9b31/bigquery/params.go#L32-L33 and used at https://github.com/googleapis/google-cloud-go/blob/6ece8bf62897ef5eb9b0f54fea737c1dd27e9b31/bigquery/params.go#L419

In the linked documentation, the timestamp format is given as `YYYY-[M]M-[D]D[( |T)[H]H:[M]M:[S]S[.F]]` so the timestamp parser used in the Go package do not support all permitted formats in the BigQuery documentation.

**Comment by alvarowolfx** [comment]
@whs can you provide more information on how are you passing timestamps to create the query job ? The code provided on the issues doesn't have any timestamp. Are you trying to pass a string directly or parsing it to a `civil.DateTime` ?
