### ISSUE TITLE
bigquery/storage: ManagedStream should not hold context.Canceled and context.DeadlineExceeded error

### ISSUE THREAD

**Issue by tamayika** [googleapis/google-cloud-go#6657]
**Client**

BigQuery/Storage

**Environment**

Any

**Go Environment**

Any

**Code**

```go
package main

func main() {
	/* initialization skipped */
	// this repro uses context.WithCancel(), but the same happens on context.WithTimeout() and context.DeadlineExceeded
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		// wait to ManagedStream.lockingAppend()
		time.Sleep(100 * time.Millisecond)
		cancel()
	}()
	_, err := stream.AppendRows(ctx, bytes)                 // context.Canceled is returned: expected
	_, err = stream.AppendRows(context.Background(), bytes) // context.Canceled is returned: unexpected
}
```

This problem is race condition, so please add `time.Sleep(1 * time.Second)` to https://github.com/googleapis/google-cloud-go/blob/main/bigquery/storage/managedwriter/managed_stream.go#L266

**Expected behavior**

ManagedStream does not hold context error.

**Actual behavior**

ManagedStream holds context error.

**Screenshots**

**Additional context**

**Comment by shollyman** [comment]
Thanks for the report.  Yes, its an error to retain the append-level error as the stream error.  PR forthcoming.
