### ISSUE TITLE
datastore: query example uses deprecated code `Query.Filter`

### ISSUE THREAD

**Issue by horvski** [googleapis/google-cloud-go#6725]
[The example for query](https://pkg.go.dev/cloud.google.com/go/datastore#hdr-Queries) uses the deprecated 'Filter' method, instead of 'FilterField'.

It would be nice if ' TestQueryConstruction' in 'datastore_test.go' added testing for 'FilterField' with all of the scenarios currently being tested with 'Filter'.

Updating the query example in the [datastore docs](https://pkg.go.dev/cloud.google.com/go/datastore) will make it much clearer for developers on how to properly construct a datastore query. Additionally, an example with the new operators would be very helpful.

I would not mind writing the tests/examples if anyone would suggest the best way for me to submit these changes.

**Comment by telpirion** [comment]
Hi @horvski ! Thank you for submitting a request. 

Updating the docs and tests to use `Query.FilterField()` is on the backlog of items to address. We would readily welcome any contributions you can make! Take a look at the [CONTRIBUTING](https://github.com/googleapis/google-cloud-go/blob/main/CONTRIBUTING.md) to get started.
