### ISSUE TITLE
datastore: what characters are reserved in key namekeys

### ISSUE THREAD

**Issue by horvski** [googleapis/google-cloud-go#6767]
As far as I can tell from reading the [datastore documentation](https://cloud.google.com/datastore/docs/concepts/entities#kinds_and_identifiers), there are no reserved characters for key namekeys. 

We are assuming that all character in the ASCII range are valid for ID's.

Can you confirm that this is true, and unlikely to change in the future?

**Comment by telpirion** [comment]
Hi @horvski : The [official documentation](https://cloud.google.com/datastore/docs) that you've linked to is the best place to ask your question. If you have a specific question about the Datastore Go client, please provide more clarification.

**Comment by horvski** [comment]
@telpirion I am not seeing where to leave a question, can you point me to the right place?
