### ISSUE TITLE
pubsublite: cannot use pslAckh (type *pslAckHandler) as type "cloud.google.com/go/internal/pubsub"

### ISSUE THREAD

**Issue by chintanpurplle** [googleapis/google-cloud-go#6790]
**Client**

cloud.google.com/go/pubsublite/pscompat

**Environment**

Google Cloud Functions

**Go Environment**
Go 1.16 

**Code**

e.g.
```go
// Package p contains an HTTP Cloud Function.
package p

import (
	"encoding/json"
	"fmt"
	"html"
	"io"
	"log"
	"net/http"
	"cloud.google.com/go/pubsub"
	"cloud.google.com/go/pubsublite/pscompat"
)

func ProcessPayload(w http.ResponseWriter, r *http.Request) {
	
	const topic = "SOME TOPIC NAME"
	publisher, err := pscompat.NewPublisherClient(r.Context(), topic)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Fprint(w, "OK")
}

```

**Expected behavior**

Earlier the build was working as expected when i deployed it 2 months back. but right now I'm trying to deploy the code again and its giving me error. The build should proceed without this error.

**Actual behavior**
When we are trying to create the build again it gives below error.

_Deployment failure:
Build failed: # example.com/cloudfunction
serverless_function_source_code/function.go:12:2: imported and not used: "cloud.google.com/go/pubsublite"
serverless_function_source_code/function.go:37:20: undefined: pscompat; Error ID: 975560ac_

**Screenshots**

<img width="905" alt="Screenshot 2022-09-30 at 12 06 39" src="https://user-images.githubusercontent.com/104752821/193206164-f4d2f6ac-eff0-4316-ae82-ca750ae360be.png">

**Additional context**

The code was built last 2 months back. was trying to add some logs and upon save the build started failing. removed the code and tried to build the original code and it failed with same error. tried creating a new cloud function by only importing the pubsublite related dependencies and created a publisher client and it still failing.

**Comment by hongalex** [comment]
Can you update to `cloud.google.com/go/pubsublite@v1.4.0` and see if this fixes it for you? This recent version of Pub/Sub Lite should fix the errors related to the invalid interface error for `pslAckHandler`.

**Comment by codyoss** [comment]
@hongalex Let's close this out due to lack of response.
