### ISSUE TITLE
storage: Add PublicAccessPrevention to BucketAttrs and BucketAttrsToUpdate?

### ISSUE THREAD

**Issue by nkvoll** [googleapis/google-cloud-go#6798]
**Is your feature request related to a problem? Please describe.**
I am unable to configure the full `IamConfiguration` (e.g setting `PreventPublicAccess`) via the `storage.Client`.

**Describe the solution you'd like**
I would like `PublicAccessPrevention` to be added to the `storage.BucketAttrs` and `storage.BucketAttrsToUpdate` structs.

**Describe alternatives you've considered**
An option would be add the full `IamConfiguration` field to `BucketAttrs`/`BucketAttrsToUpdate`, but that might be a larger change.

**Additional context**
N/A

**Comment by tritone** [comment]
`PublicAccessPrevention` was already added to `BucketAttrs` and `BucketAttrsToUpdate` in the library last year. Do you need to upgrade your library version? The changes went out in storage/v1.16.0 (and another enum value was added in v1.18.0).

**Comment by nkvoll** [comment]
Thank you @tritone :) I was looking at this through another repository that needs to have its dependencies updated and assumed it was recent. Sorry for the noise.
