### ISSUE TITLE
storage: bucket.Objects always returns "bucket doesn't exist" when using Firebase Emulator

### ISSUE THREAD

**Issue by dumabg** [googleapis/google-cloud-go#6815]
I have a function that deletes some objects. This function works well, but when is used with Firebase Emulator, always return "bucket doesn't exist".

go 1.16

**Code**

e.g.
```
    storage, err := fire.DefaultFirebaseApp.Storage(ctx)
	if err != nil {
		return err
	}
	bucket, err := storage.DefaultBucket()
	if err != nil {
		return err
	}
	it := bucket.Objects(ctx, &cloudStorage.Query{
		Prefix: 'images/img',
	})
	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return err
		}
		err = bucket.Object(attrs.Name).Delete(ctx)
		if err != nil {
			return err			
		}
	}
	return nil
```

**Expected behavior**
Code working with Firebase Emulator

**Comment by tritone** [comment]
This code seems to be from the Firebase Admin SDK rather than this repo, so please file an issue over there instead at https://github.com/firebase/firebase-admin-go to get support.

**Comment by dumabg** [comment]
Opened: [https://github.com/firebase/firebase-admin-go/issues/514](https://github.com/firebase/firebase-admin-go/issues/514)
