### ISSUE TITLE
pubsub: message is created while context is cancelled

### ISSUE THREAD

**Issue by PierekEast** [googleapis/google-cloud-go#6843]
**Client**
PubSub

**Environment**
gcr.io/distroless/static:latest on GKE

**Go Environment**
golang:1.17-alpine

**Code**

```go
func (p *Publisher) Publish(ctx context.Context, msg []byte) (msgID string, err error) {
	t := p.client.Topic(p.topicID)

	result := t.Publish(
		ctx, &pubsub.Message{
			Data: msg,
		},
	)

	msgID, err = result.Get(ctx)
	if err != nil {
		p.logger.Error(
			"failed to publish message",
			topicIDField(p.topicID), msgIDField(msgID), msgField(msg), zap.Error(err),
		)

		return "", fmt.Errorf("failed to publish message: %w", err)
	}

	p.logger.Info(fmt.Sprintf("message published - %v", msgID), topicIDField(p.topicID), msgIDField(msgID), msgField(msg))

	return msgID, nil
}
```

I am not sure whether it is a bug, probably not, but I'd be grateful for the explanation here.
Sometimes we receive the `cancelled context` error while fetching msgID from `result.Get(ctx)`. In such case the empty string is returned as msgID.
The problem is that the message is still created.
We know that the message is created, because the other service which is the Listener pulls the message and processes it properly.

The problem is that in the Publisher service we have to return the error because we couldn't get the msgID and the external service which is calling the Publisher will retry on error. The second request usually processes fine and then we end up with two exactly the same messages (speaking about payload), but different msgIDs in the Listener service.

Is it a normal behaviour?

**Comment by hongalex** [comment]
Are you passing in a context with a deadline into this custom defined Publish method? If so, then yes this can happen. Basically, the library's Publish might succeed but when we get to publishResult.Get, it might time out.

Second, I would highly recommend not creating a new topic reference every time you publish. They should be reused across publish instances to allow for better performance through batching and flow control.

**Comment by PierekEast** [comment]
So this is all embeed within the grpc request and the context passed here is the request context I guess. And we thought that maybe somehow in grpc internals this context is being cancelled? So just before hitting this publish function I've created a check with <-ctx.Done() to ensure (or minimize the probability,) that the context is not being cancelled by some grpc internals. Today we had the case and it was catched there but in this Publish method . I'm not quite sure if the ctx passed here is with deadline. I guess it's not, the time from receiving the request in the service and reaching the publish method is within miliseconds. Also the err is `context cancelled` and the err for deadline exceeded is slightly different?

Thanks for the second point

**Comment by PierekEast** [comment]
This ctx check looks like that:


```go
	var msgID string
	select {
	case <-ctx.Done():
		err = ctx.Err()

		switch {
		case errors.Is(err, context.Canceled):
			s.logger.Error("context cancelled before publishing", zap.Error(err))
		case errors.Is(err, context.DeadlineExceeded):
			s.logger.Error("context deadline exceeded before publishing", zap.Error(err))
		}
	default:
		msgID, err = s.publisher.Publish(ctx, jsonBytes)
	}
```

**Comment by hongalex** [comment]
The context check isn't really necessary since you should just be reading the err returned by `Publish` for any errors.

Anyway, could you implement the point I made above by instantiating the topic and passing it into your publisher object for reuse? I suspect that should decrease the amount of wonkiness happening that leads to this behavior. If this still occurs, feel free to comment below and I'll investigate further.

**Comment by PierekEast** [comment]
Ok 😊 will be in touch, thanks

**Comment by PierekEast** [comment]
Hello again. We've applied the suggestions - the Publish code looks like that:
```go
func (p *publisher) Publish(ctx context.Context, msg []byte) (msgID string, err error) {
	result := p.topic.Publish(
		ctx, &pubsub.Message{
			Data: msg,
		},
	)

	msgID, err = result.Get(ctx)
	if err != nil {
		p.logger.Error(
			"failed to publish message",
			topicIDField(p.topic.ID()), msgIDField(msgID), msgField(msg), zap.Error(err),
		)

		return "", fmt.Errorf("failed to publish message: %w", err)
	}

	p.logger.Info(fmt.Sprintf("message published - %v", msgID), topicIDField(p.topic.ID()), msgIDField(msgID), msgField(msg))

	return msgID, nil
}
```

The topic is instantiated within the ```p *publisher```.

The invocation of this method looks like that:
```go
      var timeout = 10 * time.Second
      
      ctxPubSub, cancel := context.WithTimeout(ctx, timeout)
      defer cancel()
      
      msgID, err = s.publisher.Publish(ctxPubSub, jsonBytes)

```
so we are spawning a new context with some timeout for a pubsub processing.


We are still receiving the same error from: 
```go
msgID, err = result.Get(ctx)
```

Log:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/79984312/198211223-31f8af38-8a3a-407b-9f59-ef13f4bbd431.png">

The occurrence happens once per 25 000 successful publications.

And the result is as before - we got an error, but the message was published to the topic, because the receiver service got this message and acked.

**Comment by hongalex** [comment]
Are you still encountering this issue and did trying the steps in the earlier comment help at all?

**Comment by PierekEast** [comment]
> Are you still encountering this issue and did trying the steps in the earlier comment help at all?

Hello, sorry. I think we could close the topic. 
I think the main reason for cancelled requests is the fact that the sender was using nodejs grpc lib to fire requests and there are some issues with it (there are ons of issues reported in the internet).

So pubsub is working as expected.

The mystery is why the request was canceling the request exactly during the pubsub processing.

But once we catched context cancelled right before publishing to topic ;) 


Also, your advices about topic and publisher settings were helpful, thanks.
