### ISSUE TITLE
managedidentities: LDAPS Settings API Support

### ISSUE THREAD

**Issue by tgoodsell-tempus** [googleapis/google-cloud-go#6860]
**Is your feature request related to a problem? Please describe.**
I'm attempting to create some automation tooling for our handling of the LDAPS certificate used with Managed AD. However, there is no SDK methods for using these APIs currently available.

**Describe the solution you'd like**
Methods for these API endpoints added to the SDK.

**Describe alternatives you've considered**
Writing out the API calls themselves using the lower level client, not a bad solution but difficult for us to support alone longer term.

**Additional context**
API Methods:
`getLdapsSettings`: https://cloud.google.com/managed-microsoft-ad/reference/rest/v1/projects.locations.global.domains/getLdapssettings

`updateLdapsSettings`: https://cloud.google.com/managed-microsoft-ad/reference/rest/v1/projects.locations.global.domains/updateLdapssettings

**Comment by codyoss** [comment]
Hey, thanks for the feature request. Unfortunately these libraries are auto-generated, so if you would like to file a feature request you will want to do it with the upstream source for these libraries. Here is a link to the product support page based off of the link you shared: https://cloud.google.com/managed-microsoft-ad/docs/get-support

Hope that helps.
