### ISSUE TITLE
firestore: How do I pass a databaseID in the firestore client

### ISSUE THREAD

**Issue by takeoff-pharatesid** [googleapis/google-cloud-go#6866]
Whenever I create a new firestore client,  it points to the (default) database in the firestore

I would like to know how do i create/configure the client so that it points to a particular database in the firestore.

Also I would like to have details on the best practices of the databases for firestore, having only one (default) database for all kinds of use cases a good practice or we should create multiple databases as per the usecase ?

**Comment by telpirion** [comment]
Hi @takeoff-pharatesid ,

Multiple databases are not currently supported in Firestore, although support may be added for them in the future ( see #5331 ).

Best practices documentation is out-of-scope for the Go client library. I would review the official documentation on [cloud.google.com](https://cloud.google.com/firestore/docs).
