### ISSUE TITLE
pubsub: Cliffhanger in documentation for Message type

### ISSUE THREAD

**Issue by DenisPalnitsky** [googleapis/google-cloud-go#6877]
**Client**
PubSub

**Issue**
Looks like part of the documentation is missing for `Message` type

Here is the exact location: https://github.com/googleapis/google-cloud-go/blob/8b203b8aea4dada5c0846a515b14414cd8c58f78/pubsub/message.go#L41

![image](https://user-images.githubusercontent.com/154290/196246623-3791a02a-7876-4628-9ae8-9ab80b30e322.png)

**Additional Context**
I tried to find missing peace in git history without any success

**Comment by hongalex** [comment]
Thanks for filing this issue, opened a PR to fix that comment.
