### ISSUE TITLE
pubsublite: Cap number of assigned partitions, to avoid cascading out-of-memory failures

### ISSUE THREAD

**Issue by sveiss** [googleapis/google-cloud-go#6892]
**Is your feature request related to a problem? Please describe.**
Pub/Sub Lite flow control settings are per-partition, but there’s no simple way to cap the number of partitions assigned to a consumer client.

A partial failure impacting a subset of consumers can cascade as the remaining healthy consumers accept too many partition assignments and exhaust their memory limits, putting more pressure on the remaining healthy consumers. Under Kubernetes, the CrashLoopBackOff restart backoff policy further exacerbates the situation, making it unrecoverable without operator intervention.

**Describe the solution you'd like**
Ultimately, I want this situation to not devolve into a death spiral. If more consumer processes have failed than I have provisioned redundancy to cope with, then message processing should be delayed, but the remaining consumers should continue to function and newly started consumers should be able to pick up the slack once the original failure is recovered.

I see a few routes here:

The most direct approach would be to add a `MaxAssignedPartitions` field to `pscompat.ReceiveSettings`. Attempts to assign more partitions than this limit would be ignored (with appropriate diagnostics emitted).

Alternatively, `ReassignmentHandler` could perhaps be allowed to modify the set of `nextPartitions`, which would allow flexibility in which partitions get ignored.

Another approach would be to allow the user `ReassignmentHandler` to modify the flow control settings: that way we could at least dynamically scale down `MaxOutstandingBytes` if more partitions were assigned than we were expecting. 

Making `MaxOutstandingBytes` global instead of per-partition would make memory usage simpler to reason about, but would be a breaking API change (assuming it’s architecturally possible!).

**Describe alternatives you've considered**
Currently, if we get into this failure state, we restart all the consumer processes at once, to encourage a sufficiently even distribution of partition assignments.

We could implement our own partition assignment system. It doesn’t look like the partition assignment service API is documented, so this would be a substantial amount of duplicative work.

We could configure MaxOutstandingBytes low enough and our memory limits high enough to accommodate an unreasonably large number of assigned partitions, but this would impose a high level of overhead on the normal operations case.

**Comment by tmdiep** [comment]
Thanks for the suggestions; we have considered some of them for other use cases. However, since this scenario is abnormal application behavior, we'd like to explore other solutions first.

The server waits 30 seconds before reassigning partitions when it detects that a consumer is offline. It appears from a quick search that it is still not possible to prevent or tune CrashLoopBackOff. Ideally the processes shouldn't crash, but perhaps there's another way to restart them immediately.

Just curious what you're setting `MaxOutstandingBytes` to and the number of partitions in the topic? We'd suggest reducing `MaxOutstandingBytes` such that it buffers ~1 second of data, which would depend on the RTT of the network and the throughput of message processing by a single consumer.

**Comment by sveiss** [comment]
I take your point about this being abnormal application behaviour, but I would still prefer to see more resilience in the face of undersized consumer clusters. Even if our application was perfectly crash-free, hardware or network issues can still take out a large number of consumers at once. 

We also run into this when waiting for the k8s cluster autoscaler to provision more capacity for us: for example, deploying a brand new consumer on an existing topic will frequently run into this, as a handful of pods launch quickly and the rest wait for new nodes to spin up.

Right now, our MaxOutstandingBytes is set to 50M (which we've progressively tuned down from the default 1G in `DefaultReceiveSettings`). This is quite a bit larger than 1 second of data, so I'll try tuning that down further. 

I can share the number of partitions in a support ticket or by email if it's still relevant; it's not something I can share publicly.

**Comment by tmdiep** [comment]
Feel free to reach out again if tuning `MaxOutstandingBytes` doesn't help. If you prefer not to share details publicly, we have pubsub-lite-help@google.com monitored by the dev team, in addition to support tickets.
