### ISSUE TITLE
firestore: reenable checking readtime in integration test

### ISSUE THREAD

**Issue by telpirion** [googleapis/google-cloud-go#6894]
The project used for running integration tests don't have snapshots enabled. As a result, the integration tests for this feature fail.

Once this feature is enabled for the test project, the integration test should be re-enabled.

**Comment by bhshkh** [comment]
test was disabled in https://github.com/googleapis/google-cloud-go/pull/6895

and enabled in https://github.com/googleapis/google-cloud-go/pull/9274
