### ISSUE TITLE
auth: provide error objects for different situations

### ISSUE THREAD

**Issue by briandealwis** [googleapis/google-cloud-go#6899]
**Is your feature request related to a problem? Please describe.**
We're having to use pattern matching on error strings to recognize problematic situations and to recommend actions to remediate the situation.  Our suggestions may not match those suggested by the auth libraries (e.g., we may not want our users to use `gcloud auth application-default login`).

**Describe the solution you'd like**
We would like for auth library to return wrapped error objects that can be tested for:
```golang
if e := (&oauth.ApplicationDefaultCredentialError{}); errors.As(err, &e) {
	return nil, jsonrpc2.NewError(ErrCodeNoADC, e.Error())
}
if e := (&oauth.PermissionDeniedError{}); errors.As(err, &e) {
	return nil, jsonrpc2.NewError(ErrCodePermissionDenied, e.Error())
}
return nil, jsonrpc2.NewError(ErrCodeRequestFailed, fmt.Sprintf("unable to frob the foo: %v", err))
```

**Describe alternatives you've considered**

Currently we're relying on string matching against the returned errors, which seems fragile.

```golang
switch {
case err == nil:
	return nil

// full errors:
// 1. `google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`
// 2. seen on GCE: `Post "https://foo.googleapis.com/v1/projects/xxx/locations/us/frob?alt=json&prettyPrint=false": impersonate: unable to generate access token: Post "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/sa@xxx.iam.gserviceaccount.com:generateAccessToken": metadata: GCE metadata "instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform" not defined`
case strings.Contains(err.Error(), "could not find default credentials") ||
	strings.Contains(err.Error(), "impersonate: unable to generate access token:"):
	return &ApplicationDefaultCredentialError{Err: err}

// full error (trimmed newlines): `rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: impersonate: status code 403: {"error": {"code": 403, "message": "The caller does not have permission", "status": "PERMISSION_DENIED"}`
case strings.Contains(err.Error(), "per-RPC creds failed due to error: impersonate: status code 403"):
	return &PermissionDeniedError{Err: err}

default:
	return err
}
```

**Comment by codyoss** [comment]
If errors are related to a HTTP failure I believe they already are structured as: https://pkg.go.dev/golang.org/x/oauth2#RetrieveError

Furthermore if the error is retrievable I believe you will find https://pkg.go.dev/golang.org/x/oauth2/google#AuthenticationError in the chain. 

Between these two should be the programatic cases people need to check for I believe. Have you tried using these types?

**Comment by briandealwis** [comment]
I apologize: I not only missed some key details (I'm using gRPC), but I failed to dig far enough into these errors.  

I traced the no-ADC case to:
https://github.com/golang/oauth2/blob/e48dfd961a9308e36f20c50dc588b45244d22b1e/google/default.go#L156-L158
I will open an issue there.

The permission denied error is a gRPC error — I'm not sure how I mistook this as an error-string.
