### ISSUE TITLE
PubSub: documentation typo for subscription retry policy

### ISSUE THREAD

**Issue by minsung-moloco** [googleapis/google-cloud-go#6903]
[PubSub documentation](https://cloud.google.com/pubsub/docs/handling-failures#exponential-backoff) states subscription retry policy's maximum backoff defaults to 600 seconds while [go-client documentation](https://github.com/googleapis/google-cloud-go/blob/bd8eea37bab71693dd1eb22b1f99e4570f0f4075/pubsub/subscription.go#L578-L585) states 10 seconds. I assume this is a typo in the go-client source code side.

**Comment by hongalex** [comment]
Thanks again for filing an issue!
