### ISSUE TITLE
cloud.google.com/go/speech/apiv1p1beta1/speechpb: json Unmarshal to speechpb.RecognizeResponse does not parse StartTime and EndTime from results

### ISSUE THREAD

**Issue by tdi** [googleapis/google-cloud-go#6904]
**Client**

e.g. speech 

**Environment**

Local and GCP Cloud run. 

**Go Environment**

$ go version
go version go1.19.2 darwin/arm64
$ go env

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/darek/Library/Caches/go-build"
GOENV="/Users/darek/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/darek/Projects/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/darek/Projects/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.2/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/darek/Projects/transcribe-service/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k2/n8d97xn906b3bg597kc9m2600000gn/T/go-build2893531059=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

import (
	// "encoding/json"

	"encoding/json"
	"fmt"
	"os"

	"cloud.google.com/go/speech/apiv1p1beta1/speechpb"
)

type GoogleChunk struct {
	StartTime   float64
	EndTime     float64
	SpeakerName string
}

func (g GoogleChunk) String() string {
	return fmt.Sprintf("Chunk: %s, %f, %f", g.SpeakerName, g.StartTime, g.EndTime)
}

func (g GoogleChunk) Len() float64 {
	return g.EndTime - g.StartTime
}

type GoogleTranscript struct {
	chunks []GoogleChunk
	offset float64
}

func NewGoogleTranscript(chunks []GoogleChunk, offset float64) *GoogleTranscript {
	gt := &GoogleTranscript{offset: offset}
	gt.SetChunks(chunks)
	return gt
}

func NewGoogleTranscriptFromFile(filename string, offset float64) (*GoogleTranscript, error) {
	file, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	chunks := make([]GoogleChunk, 0)
	var resp speechpb.RecognizeResponse
	err = json.Unmarshal(file, &resp)
	if err != nil {
		return nil, err
	}

	// get the last result in diarization results
	result := resp.GetResults()[len(resp.GetResults())-1]
	words_info := result.GetAlternatives()[0].GetWords()
	for _, word := range words_info {
		fmt.Println(word.EndTime)
		chunks = append(chunks, GoogleChunk{
			StartTime:   float64(word.GetStartTime().GetSeconds()) + float64(word.GetStartTime().GetNanos())/1000000000,
			EndTime:     2.0,
			SpeakerName: word.Word,
		})
	}

	gt := NewGoogleTranscript(chunks, offset)

	return gt, nil
}

func (g *GoogleTranscript) SetChunks(chunks []GoogleChunk) {
	g.chunks = chunks
	g.chunks = g.mergeChunks()
	g.chunks = g.removeSilence()
}

func (g *GoogleTranscript) GetChunks() []GoogleChunk {
	return g.chunks
}

// Merge chunks by speaker to bigger chunks
func (t *GoogleTranscript) mergeChunks() []GoogleChunk {
	var currentSpeaker string
	var lastChunk GoogleChunk
	mergedChunks := make([]GoogleChunk, 0)
	for _, chunk := range t.chunks {
		switch {
		case chunk.SpeakerName == "":
			currentSpeaker = chunk.SpeakerName
			lastChunk = chunk
		case currentSpeaker == chunk.SpeakerName:
			lastChunk.EndTime = chunk.EndTime
		case currentSpeaker != chunk.SpeakerName:
			currentSpeaker = chunk.SpeakerName
			mergedChunks = append(mergedChunks, lastChunk)
			lastChunk = chunk
		}
	}
	mergedChunks = append(mergedChunks, lastChunk)
	return mergedChunks
}

func (t *GoogleTranscript) removeSilence() []GoogleChunk {
	mergedChunks := t.mergeChunks()
	var newChunks []GoogleChunk
	for i := range mergedChunks {
		if mergedChunks[i].Len() >= t.offset {
			newChunks = append(newChunks, mergedChunks[i])
		}
	}
	return newChunks
}

func main() {

	gt, _ := NewGoogleTranscriptFromFile("trans.json", 2.0)

	for _, chunk := range gt.GetChunks() {
		fmt.Println(chunk)
	}
}

```

**Expected behavior**

StartTime and EndTime should be Unmarshalled. 

**Actual behavior**

StartTime and EndTime are <nil>

**Additional context**

I am using directly json created by google Speech to text.

**Comment by codyoss** [comment]
Hey, you can't use the json package directly with protos. You need to make use of the [protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) pkg. Hope that helps.

**Comment by tdi** [comment]
@codyoss you mean I should use protojson to Unmarshal json file  created by Google Speech To Text logn running operation? 

So json tags on the structs are just for Marshallers? 

I will try protojson - but last time I checked it paniced my code.

**Comment by codyoss** [comment]
If you are marshalling them to a type in that package, yes you need to use protojson. If the type you actually want is in our "old libraries" the json package would work -- as they are not proto based

**Comment by tdi** [comment]
Protojson does not recognize `speakerLabel` which is present in the json but it is not present in the `type WordInfo struct {
` 

Is this a bug ? 

proto: (line 506:9): unknown field "speakerLabel"
