### ISSUE TITLE
pubsub: ack handler should be settable for testing purposes

### ISSUE THREAD

**Issue by mikestefanello** [googleapis/google-cloud-go#6971]
**Is your feature request related to a problem? Please describe.**
Writing unit tests for a pubsub receiver is challenging because there is no way to determine if the message was acked or nacked. There are no fields or methods available to retrieve that information and the ack handler (`ackh`) is an unexported field with no available method to set it. Perhaps this data is available if you setup the test server, but that complexity shouldn't be required to simply test a receiver.

For example:

```go
func (r *pubsubReceiver) Receive(ctx context.Context, msg *pubsub.Message) {
  if someLogic() {
    msg.Ack()
  } else {
    msg.Nack()
  }
}
```

There is no way to write a test to determine what happened (as far as I can tell).

**Describe the solution you'd like**
I can see this being resolved in one of two ways:

1. Provide an exported field or method on `Message` to determine if the message was acked or nacked. I suppose the challenge is differentiating between Ack() being called and the message actually being acked, but I don't think it would be that hard to make that clear.
2. Provide a method to set your own handler for the `ackh` field, for testing purposes. See below for my example of what I'm doing now. If you go this route, you could also provide a simple mock handler.

**Describe alternatives you've considered**
Previously mentioned are the two alternatives I think are suitable. See below for the hack I am currently employing.

**Additional context**
To get around this issue, I employed [this hack](https://noamt.medium.com/go-mocking-googles-pubsub-message-19479930caaf) (slightly modified, as that is now outdated) to forcefully set the `ackh` field with my own implementation of `AckHandler`.

IE:

```go
type AckStatus struct {
	acked  bool
	nacked bool
}

func (a *AckStatus) IsAcked() bool {
	return a.acked
}

func (a *AckStatus) IsNacked() bool {
	return a.nacked
}

func (a *AckStatus) OnAck() {
	a.acked = true
}

func (a *AckStatus) OnNack() {
	a.nacked = true
}

func (a *AckStatus) OnAckWithResult() *pubsub.AckResult {
	a.OnNack()
	return &pubsub.AckResult{}
}

func (a *AckStatus) OnNackWithResult() *pubsub.AckResult {
	a.OnNack()
	return &pubsub.AckResult{}
}
```

**Comment by rolandhawk** [comment]
I also need this feature. This will also be useful for monitoring purpose (ex: exporting ack metrics).

I think the easiest way to accommodate this request is by exposing https://pkg.go.dev/cloud.google.com/go/internal/pubsub#NewMessage in `cloud.google.com/go/pubsub` package.

**Comment by hongalex** [comment]
Tagging @tmdiep here since the Pub/Sub Lite library depends on these shared structs/interfaces. I vaguely remember discussing this at some point, do you remember what the outcome of that conversation was?

**Comment by tmdiep** [comment]
The decision was not to extend the API surface.

The API has evolved slightly since, but the workarounds suggested at the end of https://github.com/googleapis/google-cloud-go/pull/2920 are still valid.

**Comment by hongalex** [comment]
> I also need this feature. This will also be useful for monitoring purpose (ex: exporting ack metrics).

We do have some metrics exporting available via [OpenCensus right now](https://github.com/googleapis/google-cloud-go/blob/main/pubsub/trace.go), including ack count. We plan to move this implementation towards using OpenTelemetry once the metrics SDK is stabilized across languages.

Aside from that, the workarounds are listed in the comment above so I'll be closing the issue.
