### ISSUE TITLE
bigquery: Dataset storage billing model

### ISSUE THREAD

**Issue by Dror88** [googleapis/google-cloud-go#6978]
**Is your feature request related to a problem? Please describe.**

We want to create BQ datasets and set the [storage billing model](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#storagebillingmodel) property to `PHYSICAL`, but it doesn't look like this option is available using the latest release.

**Describe the solution you'd like**

We would like a `StorageBillingModel` field to be added to the `bigquery.DatasetMetadata` struct so we can create datasets with Physical billing storage model.

**Describe alternatives you've considered**

We are currently using this SDK and would rather not resort to calling the [BQ REST API](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/insert) by ourselves...

**Comment by shollyman** [comment]
Looks like this is now in discovery.  We were deferring including the field until present.
