### ISSUE TITLE
compute: firewall policies api should be allowed to create regional/global policies

### ISSUE THREAD

**Issue by Weiyureal666** [googleapis/google-cloud-go#6996]
**Is your feature request related to a problem? Please describe.**
I'm working on a feature based on the `Insert()` API of `FirewallPoliciesClient`, I have noticed that `ParentId` of the `InsertFirewallPolicyRequest` is required. 

<img width="632" alt="Screenshot 2022-11-05 at 4 41 35 PM" src="https://user-images.githubusercontent.com/40848649/200111432-5da95597-84b8-45bf-8415-a10c973cfe60.png">
And I can not find any parameters related to region or global options either, which is different from the console's behaviour. 

It seems that the `Insert()` API forces the callers to create a hierarchical firewall policy instead of a region/global policy through official go SDK. 
**Describe the solution you'd like**
May be can change the `InsertFirewallPolicyRequest.ParentId` to an optional parameter and add `Region`to`InsertFirewallPolicyRequest` which accept `regions/[region]` or `regions/global` value to allow callers to create regional/global firewall policies

**Comment by codyoss** [comment]
Hey @Weiyureal666 this is an auto-generated library based off of a spec. If you would like to make feature requests I would recommend reaching out on the product specific cloud issue tracker: https://issuetracker.google.com/issues/new?component=187134&template=0

Hope that helps
