### ISSUE TITLE
apidiff flaging breaking changes it should not for us

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#7007]
apidiff is currently catching some breaking changes we don't want it to. Any time a new RPC is added to a client the proto stub has a method added to an interface. We should try to filter out these breaking changes if possible. See #7005 as an example.

**Comment by codyoss** [comment]
cc @noahdietz

**Comment by noahdietz** [comment]
Yep, need to include this bit (from go-genproto) since we are doing stubs here: https://github.com/googleapis/go-genproto/blob/main/.github/workflows/apidiff.yaml#L68-L69
