### ISSUE TITLE
datastore: authentication non-blocking locally

### ISSUE THREAD

**Issue by hermanbanken** [googleapis/google-cloud-go#7015]
**Client**
Datastore, but probably others too

**Environment**
Locally with gcloud auth login & application default credentials.

**Go Environment**

$ go version
$ go env

```
go version go1.19.2 darwin/arm64

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
```

**Code**
https://gist.github.com/hermanbanken/8299d88a54d9b8f1ab0b425c7736d44e

```
func setup(parentCtx context.Context, proj string) (*datastore.Client, error) {
	// Wait a max of 15 seconds before giving up connecting to the datastore; ctx should only be used while dialing
	ctx, cancel := context.WithTimeout(parentCtx, 15*time.Second)
	defer cancel()

	return datastore.NewClient(ctx, proj, option.WithGRPCDialOption(grpc.WithBlock()))
}
```

**Expected behavior**

The NewClient call should not finish before the authentication is completed, and subsequent Get calls should work / 404.

**Actual behavior**

The setup function finishes before the authentication is done, the `defer cancel()` runs, and the subsequent RPCs to `Get` fail with `rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: context canceled`.

**Additional context**

Note that the behavior in GCE/GKE is different from locally. Being authenticated as a user has this issue, while being authenticated via a Metadata API with access token works.

```bash
herman@cloudshell:~/8299d88a54d9b8f1ab0b425c7736d44e (dummy)$ GCLOUD_PROJECT=dummy go run ./
2022/11/10 14:44:21 datastore: no such entity
```

```
herman@mac $ time GCLOUD_PROJECT=dummy go run ./
2022/11/10 15:45:19 rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: context canceled
exit status 1
GCLOUD_PROJECT=dummy go run ./  0.52s user 0.38s system 81% cpu 1.103 total
```

**Comment by quartzmo** [comment]
@hermanbanken Thank you for reporting this issue. I used your example to reproduce it locally myself as described.

**Comment by quartzmo** [comment]
> The NewClient call should not finish before the authentication is completed, and subsequent Get calls should work / 404.

I think maybe this expectation is incorrect, given the `cancel()`? The reality is that the `Context` you provide to `NewClient` may be used for authentication requests for entire lifetime of the returned client, well past the moment that `NewClient` returns. An example usage (outside the scope of your sample, but still relevant) is token refresh: The `Context` provided to `NewClient` is typically [stored](https://github.com/golang/oauth2/blob/master/oauth2.go#L227-L259) in a `tokenRefresher` struct for later [use](https://github.com/golang/oauth2/blob/68a41d64f90fbf7f9a758cf5abd1e2a9a63c5fca/internal/token.go#L232).

Feel free to reopen this issue to discuss further or if you have more questions. Thank you!
