### ISSUE TITLE
pubsub: retry settings

### ISSUE THREAD

**Issue by enumag** [googleapis/google-cloud-go#7040]
**Is your feature request related to a problem? Please describe.**

I'd like to have better control over the retry policies for my pubsub messages. I found this documentation:

https://cloud.google.com/pubsub/docs/publisher#retry

However it's notably lacking an example for Go and I was unable to find anything similar in the source code of your Go library. The documentation even notes:

> note that not all client libraries support custom retry settings

It seems Go is one of those that don't have this feature?

 **Describe the solution you'd like**

Retry settings should be implemented in the pubsub library for Go and code sample should be available in the documentation.

 **Describe alternatives you've considered**

No alternative seems to be available for Go.

 **Additional context**

Screenshot from documentation:

![Screenshot from 2022-11-15 10-02-15](https://user-images.githubusercontent.com/539462/201877183-e93e81e4-0970-4b7e-a1e2-0eacfd887d4e.png)

**Comment by hongalex** [comment]
Apologies as this seemed to have fallen under the radar. Could you describe the use case for wanting custom retry settings for Publish?

You are able to specify a custom Publish retryer by using `NewClientWithConfig`. Here's a brief snippet on how to set that up

```go
config := &ClientConfig{
	PublisherCallOptions: &vkit.PublisherCallOptions{
		Publish: []gax.CallOption{
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Aborted,
					codes.Canceled,
					codes.Internal,
					codes.ResourceExhausted,
					codes.Unknown,
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
	},
}
client, err := NewClientWithConfig(ctx, projID, config, opts...)```

**Comment by enumag** [comment]
If it's already possible then great. But the documentation should be updated to include a go example.

**Comment by hongalex** [comment]
Sure, I'll use this issue around as a docs request to add this sample to our docs.

**Comment by hongalex** [comment]
Apologies, I believe my last example is incorrect as of #5728 since we started using a custom retrier at the Publish level which overrides the retrier defined at the client construction level.

I'll track this as a bug for now since I need to discuss with other client lib owners whether or not we want to collectively support custom retries.
