### ISSUE TITLE
pubsub: Allow to set host in the client

### ISSUE THREAD

**Issue by eddumelendez** [googleapis/google-cloud-go#7095]
Hi, I want to write a test using [testcontainers-go](https://github.com/testcontainers/testcontainers-go) and as you can see [here](https://www.testcontainers.org/modules/gcloud/#pubsub) java client already allows to set the host and port, which is a random port provided by testcontainers. By setting the env var we are not able to run tests in parallel.

```java
String hostport = emulator.getEmulatorEndpoint();
ManagedChannel channel = ManagedChannelBuilder.forTarget(hostport).usePlaintext().build();
```

**Comment by hongalex** [comment]
If I understand your concern correctly, you want to be able to specify multiple endpoints for your tests to run, while running within the same environment such that the env var option doesn't work for you, is that right?

I'm not super familiar with testcontainers, but the environment variable behavior (using `PUBSUB_EMULATOR_HOST`) is something we're interested in keeping. If you want to play around with custom options, you could use `google.golang.org/api/option` and `option.WithEndpoint("localhost.com:1234")` to specify a custom endpoint for your individual emulator instances. You will also need to specify using [insecure credentials](https://pkg.go.dev/google.golang.org/grpc/credentials/insecure#NewCredentials)

**Comment by eddumelendez** [comment]
@hongalex thank you! I follow your suggestions. You can see it [here](https://github.com/testcontainers/testcontainers-go/pull/670).
