### ISSUE TITLE
pubsub: unauthenticated errors after running fine for a few days

### ISSUE THREAD

**Issue by sanket28** [googleapis/google-cloud-go#7113]
Client

PubSub

Environment

Go application on GKE

I have a Go application running on GKE and I'm using the Go pubsub client library. I can successfully connect to pubsub using service account credentials and publish to Pubsub. But after a few days, the client keeps giving me these errors when I try to publish: 

```
rpc error: code = Unauthenticated desc = Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See [https://developers.google.com/identity/sign-in/web/devconsole-project."](https://developers.google.com/identity/sign-in/web/devconsole-project.%22,)
```

I'm calling the following publish method:

```
func (t *Topic) Publish(ctx context.Context, msg *Message) *PublishResult
```

I need to restart my application for pubsub to work again.
Are we supposed to manually re-auth after a certain amount of time or does the library handle that?

Please advise. Thanks!

**Comment by hongalex** [comment]
This should theoretically be automatic. We've seen these kinds of unauthenticated errors with GKE applications and is something we recommend filing a support ticket for to get the proper eyes on it.

From a client library perspective though, do all `Publish` calls fail after you receive the first error or do some go through? If they all fail and a restart is critical, there's probably not much that's actionable on the library side.

**Comment by sanket28** [comment]
I believe they all fail until I restart. Since this is not a library issue, who should I contact for further assistance?

Thanks!

**Comment by sanket28** [comment]
They all fail and my application needs a restart.

**Comment by hongalex** [comment]
Yeah I recommend filing a support ticket directly if you have a support contract since this seems to be a GKE specific issue. Closing for now but please do comment if you think there's anything actionable that can be changed in the library.
