### ISSUE TITLE
cloud.google.com/go/pubsub: doesn't work with go 1.16

### ISSUE THREAD

**Issue by FranciscoKurpiel** [googleapis/google-cloud-go#7115]
**Client**

PubSub

**Environment**

- appengine, with `runtime: go116` (this is the highest supported version)
- basel with rules_go and `go_download_sdk(name = "go1.16.15", goos = "linux", goarch = "amd64", version = "1.16.15")`
- github with `actions/setup-go@v3` and `go-version: 1.16`
- archlinux, go 1.16.15

**Go Environment**

AppEngine is the most relevant one, can't get output from `go version` and `go env`, but `app.yaml` starts with:

```
runtime: go116
```

**Code**

e.g.
```go
package main

import (
	"context"

	"cloud.google.com/go/pubsub"
)

func main() {
	ctx := context.Background()

	pubsub.NewClient(ctx, "project/anything")
}
```

**Expected behavior**
According to [README.md](https://github.com/googleapis/google-cloud-go/blob/main/README.md#supported-versions) go 1.15 to 1.19 should be supported.

**Actual behavior**

```
# golang.org/x/sys/unix
../vendor/golang.org/x/sys/unix/syscall.go:83:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../vendor/golang.org/x/sys/unix/syscall_linux.go:2255:9: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
../vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)

```

**Additional context**

Works with 1.26.0, broken with 1.27.0.

EDIT: fixed URL for README.md

**Comment by FranciscoKurpiel** [comment]
The issue also affects `cloud.google.com/go/logging`.

**Comment by codyoss** [comment]
Sorry for the inconvenience, patched this with https://github.com/googleapis/google-cloud-go/commit/754015236d5af7c82a75da218b71a87b9ead6eb5 and rolling out releases now.

**Comment by codyoss** [comment]
All of the affected libraries have now have a newer patch release that should no longer have this issue. Please let me know if you still see an issue after pulling in new versions.

**Comment by FranciscoKurpiel** [comment]
Thank you very much, that was super fast! It works fine for me, as long as I don't use the `-u` when manually updating. Dependabot updates work fine.
