### ISSUE TITLE
spanner: Transaction aborted. Database schema probably changed during transaction

### ISSUE THREAD

**Issue by dearcj** [googleapis/google-cloud-go#7136]
**Client**

cloud.google.com/go/spanner v1.31.0

**Environment**

MacOsX

**Go Environment**
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/urijdorogoj/Library/Caches/go-build"
GOENV="/Users/urijdorogoj/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/urijdorogoj/Developer/nuorder/nuordergo/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/urijdorogoj/Developer/nuorder/nuordergo:/Users/urijdorogoj/Developer/nuorder/nuordergo/go1.19"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/urijdorogoj/Developer/nuorder/nuordergo/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/urijdorogoj/Developer/nuorder/nuordergo/go1.19/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7g/61tzj3s93v105xzmvyqwgfz00000gn/T/go-build2951473525=/tmp/go-build -gno-record-gcc-switches -fno-common"
go version go1.19 darwin/amd64

**Code**

Sorry for lack of example. The issue is, we have a server with RW transactions and it works fine (no errors). We have a set of tests that uses this server methods (basically rw transaction of select and update mutations). And occasionally like in 10% of cases we see this error

```
2022-12-05T16:44:43.406+0200    ERROR   storage/server.go:1043  UpdateAuthRequest spanner DoUpdate error    
    {"error": "spanner: code = \"Aborted\", desc = \"Transaction was aborted.\""}
git.nuorder.com/go/nuorder/service/auth/v1/storage.(*Server).UpdateAuthRequest.func2
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/service/auth/v1/storage/server.go:1043
cloud.google.com/go/spanner.(*ReadWriteTransaction).runInTransaction
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/transaction.go:1182
cloud.google.com/go/spanner.(*Client).rwTransaction.func2
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/client.go:497
cloud.google.com/go/spanner.runWithRetryOnAbortedOrSessionNotFound.func1
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/retry.go:92
cloud.google.com/go/spanner.runWithRetryOnAbortedOrSessionNotFound
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/retry.go:128
cloud.google.com/go/spanner.(*Client).rwTransaction
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/client.go:468
cloud.google.com/go/spanner.(*Client).ReadWriteTransaction
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/vendor/cloud.google.com/go/spanner/client.go:438
git.nuorder.com/go/nuorder/service/auth/v1/storage.(*Server).UpdateAuthRequest
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/service/auth/v1/storage/server.go:977
git.nuorder.com/go/nuorder/service/auth/v1/storage_test.TestStorageServer_UpdateAuthRequest.func1.1
        /Users/urijdorogoj/Developer/nuorder/nuordergo/src/git.nuorder.com/go/nuorder/service/auth/v1/storage/server_test.go:504
testing.tRunner
        /Users/urijdorogoj/Developer/nuorder/nuordergo/go1.19/src/testing/testing.go:1446
```

Here's how we create spanner client
```
	opts = append(opts, option.WithGRPCConnectionPool(4))
	opts = append(opts, option.WithCredentialsFile(config.CredentialsFile))
	spannerClient, err := spanner.NewClientWithConfig(ctx, config.URL(), spanner.ClientConfig{
		NumChannels: 12,
	}, opts...)
```	

We are definitely not doing:
1) any background migrations meanwhile
2) failed transactions don't timeout
3) no conflicts regarding primary key fields etc. (it might happen event with a first request)

Any possible insights why this might happen? We have a set of simple update methods that ocassionally fails with aborted. Might it be linked to "session not found" or session pool settings in general?

**Expected behavior**

No aborted error

**Actual behavior**

"Transaction aborted. Database schema probably changed during transaction" error

**Comment by rahul2393** [comment]
@dearcj can you please check with latest client library version?

**Comment by rahul2393** [comment]
@dearcj please reopen if issue exists in latest version.

**Comment by psinghbay1** [comment]
We see it everyday. We use java-spanner lib. We see this even we don't perform DDL regularly. We are on latest java-spanmer version
