### ISSUE TITLE
spanner: Have client.ReadOnlyTransaction perform retries automatically on Session Not Found errors.

### ISSUE THREAD

**Issue by dgsgoog** [googleapis/google-cloud-go#7171]
client.ReadWriteTransaction and client.Single both retry automatically when they catch a Session Not Found error, however, client.ReadOnlyTransaction does not. This means users need to manually retry ReadOnlyTransactions when sessions are not found, which may cause issues if the errors are not handled correctly.

Recently some changes in the way isSessionNotFoundError works caused the retry strategy for some of our customer to fail, resulting in an increase of uncaught Session Not Found errors on their system. If ReadOnlyTransaction had retried these errors automatically the issue might not have happened.

If this change is not possible then perhaps we can edit the API documentation to make it more visible that client.ReadOnlyTransaction does not retry session not found errors...

Thanks!

**Comment by rahul2393** [comment]
Incorporating this will be a breaking change because syntax need to be changed for existing ReadOnlyTransaction operations, we already are currently doing retry for "Session not found errors" when initiating the read only transaction.
