### ISSUE TITLE
trace: enable BatchWriteSpans retry by default

### ISSUE THREAD

**Issue by damemi** [googleapis/google-cloud-go#7184]
**Is your feature request related to a problem? Please describe.**
When using the trace client, the [default options](https://github.com/googleapis/google-cloud-go/blob/trace/v1.2.0/trace/apiv2/trace_client.go#L56-L72) enable retries for CreateSpan but not BatchWriteSpans

**Describe the solution you'd like**
It would be nice to update the default options to enable retries for BatchWriteSpans as well. I realize that this may be an intentional omission, so in that case it would be helpful to provide some guidance or reasoning for this.

**Describe alternatives you've considered**
Manually setting `client.CallOptions.BatchWriteSpans` after the client has been created seems to work.

**Additional context**
This came up in the opentelemetry exporters repo in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/208. I wrote a fix that manually sets the CallOption for this in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/550, but want to check the reasoning behind this first to make sure we aren't creating a problem.

**Comment by codyoss** [comment]
Retries are configured by the API teams. If you think this API should have different retry setting I would open up a feature request for that API. You can see the configuration for retires in the googleapis repo: https://github.com/googleapis/googleapis/blob/ed55a83de3eb7986035b0e4a23a4c37aae4bb2ab/google/devtools/cloudtrace/v1/cloudtrace_grpc_service_config.json
