### ISSUE TITLE
Logging: panic: send on closed channel

### ISSUE THREAD

**Issue by sharadregoti** [googleapis/google-cloud-go#7191]
**Client**

e.g. Logging

**Environment**

e.g. Local machine

**Go Environment**

$ go version
go version go1.19.2 linux/amd64
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sharad/.cache/go-build"
GOENV="/home/sharad/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sharad/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sharad/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sharad/personal/cloudquery/cli/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4205103398=/tmp/go-build -gno-record-gcc-switches"

**Code**
```
package common

import (
	"context"
	"log"

	"cloud.google.com/go/logging"
)

var logger *log.Logger

func init() {
	ctx := context.Background()

	// Sets your Google Cloud Platform project ID.
	projectID := "try-out-gcp-features"

	// Creates a client.
	client, err := logging.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer client.Close()

	// Sets the name of the log to write to.
	logName := "my-log"

	logger = client.Logger(logName).StandardLogger(logging.Info)

	// Logs "hello world", log entry is visible at
	// Cloud Logs.
	logger.Println("Hello from CLI")
}

func Error(msg string) {
	logger.Println(msg)
}
```

**Expected behavior**
Succesfully log the message

**Actual behavior**
Getting panic
```
panic: send on closed channel

goroutine 82 [running]:
cloud.google.com/go/logging.(*Client).error(0xc0004e2a80, {0xdd4300?, 0xc000676120})
        /home/sharad/go/pkg/mod/cloud.google.com/go/logging@v1.6.1/logging.go:221 +0x47
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000200300, {0xc000014180, 0x1, 0x1})
        /home/sharad/go/pkg/mod/cloud.google.com/go/logging@v1.6.1/logging.go:710 +0x186
cloud.google.com/go/logging.(*Client).Logger.func2({0xb5a320?, 0xc00017c600?})
        /home/sharad/go/pkg/mod/cloud.google.com/go/logging@v1.6.1/logging.go:279 +0x45
google.golang.org/api/support/bundler.(*Bundler).handle(0xc000020000, 0xc00067a180?)
        /home/sharad/go/pkg/mod/google.golang.org/api@v0.103.0/support/bundler/bundler.go:324 +0x4a
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle
        /home/sharad/go/pkg/mod/google.golang.org/api@v0.103.0/support/bundler/bundler.go:179 +0x14d
```

**Additional context**
"Hello from CLI" is visible in glcoud logging. But when i import the package & called the Error Function. I get this error

**Comment by codyoss** [comment]
This is because you are closing the client before it is being used with the `defer client.Close()` line. That line executes at the end of init and closes the underlying logging client. If if you are going to have a globally accessible logger you need to consider how you will shut it down at the end of your application. You will likely need some sort of shutdown hooks so that you ensure your logger is flushed. Hope that helps.
