### ISSUE TITLE
run: Cannot list operations -  Operation is not implemented, or supported, or enabled

### ISSUE THREAD

**Issue by imilchev** [googleapis/google-cloud-go#7197]
**Client**
`cloud.google.com/go/run/apiv2`

**Environment**
macOS Ventura 13.1

**Go Environment**
go version go1.19.4 darwin/arm64

**Code**

e.g.
```go
runSvc, err := run.NewServicesClient(ctx)
if err != nil {
  return nil, err
}
defer runSvc.Close()

it := runSvc.ListOperations(ctx, &longrunningpb.ListOperationsRequest{Name: fmt.Sprintf("projects/%s/locations/-", projectId)})
for {
  t, err := it.Next()
  if err == iterator.Done {
	break
  }
  if err != nil {
	return nil, err
  }
  // Do work...
}
```

**Expected behavior**
Get a list of Cloud Run operations

**Actual behavior**
```
rpc error: code = Unimplemented desc = Operation is not implemented, or supported, or enabled.
```

**Additional context**
I saw https://github.com/googleapis/google-cloud-go/issues/5860 and the answer stated that list operations do not need to provide an explicit endpoint. I am doing a list operation in this case but it seems like it does not work as expected. 

The provided solution there is to use `option.WithEndpoint("us-east1-run.googleapis.com:443")` for specifying the endpoint. However that option cannot be passed to the constructor of the client as it does not implement the required interface.

**Comment by quartzmo** [comment]
@imilchev I didn't yet investigate whether list operation need to provide an explicit endpoint, but I did try adapting the example from the []() docs to show how to pass the endpoint option. The example below appears to work correctly for me, although in my project I did not have any operations to list.

```go
package main

import (
	"context"
	"fmt"

	run "cloud.google.com/go/run/apiv2"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"

	longrunningpb "google.golang.org/genproto/googleapis/longrunning"
)

func main() {
	projectId := "my-project"
	region := "us-central1"
	endpoint := fmt.Sprintf("%s-run.googleapis.com:443", region)

	ctx := context.Background()
	c, err := run.NewServicesClient(ctx, option.WithEndpoint(endpoint))
	if err != nil {
		panic(err)
	}
	defer c.Close()

	req := &longrunningpb.ListOperationsRequest{
		Name: fmt.Sprintf("projects/%s/locations/%s", projectId, region),
	}
	it := c.ListOperations(ctx, req)
	fmt.Println("it: ", it)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			panic(err)
		}
		fmt.Println("resp: ", resp)
	}
}

```

**Comment by imilchev** [comment]
Okay, I think it's just the error message that is confusing here. I compared your code sample with mine and it turns out specifying the location was the only thing missing.

This code results in `rpc error: code = Unimplemented desc = Operation is not implemented, or supported, or enabled.`
```go
it := runSvc.ListOperations(ctx, &longrunningpb.ListOperationsRequest{Name: fmt.Sprintf("projects/%s/locations/-", projectId)})
```

This code works correctly (also without specifying the endpoint explicitly):
```go
it := runSvc.ListOperations(ctx, &longrunningpb.ListOperationsRequest{Name: fmt.Sprintf("projects/%s/locations/us-central1", projectId)})
```

Perhaps it would help if the comment for `ListOperationsRequest.Name` states that the location needs to be explicitly provided and that `-` is not supported. Changing the error message for that specific case to make it more clear would help too. 

Thanks for the help!
