### ISSUE TITLE
container: Allow programmatic creation of subnetworks to avoid exceeding max secondary ranges per subnetwork (30)

### ISSUE THREAD

**Issue by pmalek** [googleapis/google-cloud-go#7219]
**Is your feature request related to a problem? Please describe.**

Seems that in order to avoid hitting the secondary ranges limit per subnetwork (30) (as described in https://github.com/elastic/cloud-on-k8s/issues/2615#issuecomment-591118282 one can use `--create-subnetwork` flag using the CLI: `gcloud container clusters create`. That option doesn't seem present when using the API.

I.e. using this:

```
pbcluster := containerpb.Cluster{
	Name:             name,
	InitialNodeCount: 1,
	AddonsConfig: ...,
	// Subnetwork: "custom", // this is not allowed when "custom" subnetwork doesn't exist
}
req := containerpb.CreateClusterRequest{
	Parent: fmt.Sprintf("projects/%s/locations/%s", project, location),
	Cluster: &pbcluster,
}
_, err = mgrc.CreateCluster(ctx, &req)
```

one cannot create the subnet to use as with the CLI. `containerpb.CreateClusterRequest` doesn't seem to expose an appropriate flag nor is there a separate API that would allow subnet creation (that I can find).

**Describe the solution you'd like**

Feature parity within the API for `--create-subnetwork` flag

**Describe alternatives you've considered**

Spawning a separate process which would call `gcloud container clusters create --create-subnetwork ...`

**Comment by codyoss** [comment]
Hey, this clients are auto-generated from the container api spec. If you have a feature request for the API I suggest you check out their issue tracker and file an issue there if there is not one already: https://issuetracker.google.com/savedsearches/559746. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers

**Comment by czeslavo** [comment]
@pmalek @codyoss It seems that the feature is already exposed via the API, but did not find it. It's possible to set this parameter in `Cluster.IpAllocationPolicy.CreateSubnetwork` (https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips#api_1).

**Comment by quartzmo** [comment]
@czeslavo Thank you for finding this! Here is a link to the pkg docs for `containerpb.IPAllocationPolicy`: https://pkg.go.dev/cloud.google.com/go/container@v1.10.0/apiv1/containerpb#IPAllocationPolicy
