### ISSUE TITLE
storage: ErrObjectNotExist in NewRangeReader for "./" prefixed objects

### ISSUE THREAD

**Issue by wimagguc** [googleapis/google-cloud-go#7236]
**Client**

Storage

**Environment**

MacOS

**Go Environment**

$ go version

```
go version go1.18.7 darwin/arm64
```

**Code**

`NOTE` in the following examples, both `gs://bucket/object1.mcap` and `gs://bucket/./object1.mcap` objects exist (and are copies of one another).

```go
handle := gcs.Bucket(bucketName).Object("object1.mcap")
fmt.Println(handle.Attrs(ctx))
// Prints the attributes for `object1.mcap`
r, err := handle.NewRangeReader(ctx, 0, -1)
// Works as expected, no error.
```

Compare to:

```go
handle := gcs.Bucket(bucketName).Object("./object1.mcap")
fmt.Println(handle.Attrs(ctx))
// Prints the attributes for `./object1.mcap` as above
r, err := handle.NewRangeReader(ctx, 0, -1)
// Error: `storage: object doesn't exist`
```

**Expected behavior**

Running the same script for both existing objects, they should behave the same. The "./" object prefix shouldn't cause unexpected issues.

**Actual behavior**

* There's no difference in `handle.Attrs(ctx)` — this prints the same for both `./object1.mcap` and `object1.mcap`
* But `handle.NewRangeReader(ctx, 0, -1)` works for `object1.mcap` only, and displays an error for `./object1.mcap`:

```
storage: object doesn't exist
```

**Additional context**

`NOTE` that `x/object1.mcap` or other paths will work as well, the only exception so far being the `./` prefix. Objects with "./" prefix should be legitimate.

**Comment by tritone** [comment]
Hey, apologies for the belated response on this. We are looking into the issue; however, it may be a limitation on characters in the XML API, which is used for downloads by the SDK by default.

However, we have recently added support for downloads via the JSON API. I tested and validated that a filename like the one you mention works via this route. See https://pkg.go.dev/cloud.google.com/go/storage@main#WithJSONReads for how to enable. (Note that this will be going out in storage/v1.30.0, which we plan on releasing this week).
