### ISSUE TITLE
iam: snippets missing for apiv1 and apiv2

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-go#7241]
No snippets have been generated to [internal/generated/snippets/iam](https://github.com/googleapis/google-cloud-go/tree/main/internal/generated/snippets/iam) for the new IAM clients [iam/apiv1](https://github.com/googleapis/google-cloud-go/tree/main/iam/apiv1) and [iam/apiv2](https://github.com/googleapis/google-cloud-go/tree/main/iam/apiv2).

**Comment by quartzmo** [comment]
This will be fixed by googleapis/gapic-generator-go#1220.

**Comment by codyoss** [comment]
Closing this out as I see snippets here now.
