### ISSUE TITLE
assetpb: asset json declaration is not matching the CAI asset json definition

### ISSUE THREAD

**Issue by eeeeethan2333** [googleapis/google-cloud-go#7268]
**Client**

NA

**Environment**

NA

**Go Environment**

NA

**Code**

e.g.
```go

type Asset struct {
	
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AssetType string `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	Resource *Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	IamPolicy *v1.Policy `protobuf:"bytes,4,opt,name=iam_policy,json=iamPolicy,proto3" json:"iam_policy,omitempty"`
	OrgPolicy []*v11.Policy `protobuf:"bytes,6,rep,name=org_policy,json=orgPolicy,proto3" json:"org_policy,omitempty"`
         ........

}
```

**Expected behavior**

package: cloud.google.com/go/asset/apiv1/assetpb
https://github.com/googleapis/google-cloud-go/blob/b3715585aa6892fc41a29027694c72f31390441a/asset/apiv1/assetpb/assets.pb.go#L321

the json definition in the golang code is different from CAI json definition in [official doc](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/Asset). 

**Actual behavior**
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/32735445/213129589-1559ac42-cca5-4bf1-92d9-9022db107677.png">
the json structure defined in code

<img width="709" alt="image" src="https://user-images.githubusercontent.com/32735445/213129747-9f17d544-f0c9-431c-8b5c-32daea05ad4d.png">
json structure defined in CAI asset page

**Screenshots**
NA

**Additional context**

NA

**Comment by quartzmo** [comment]
@eeeeethan2333 Can you provide example code to demonstrate a runtime error? Thanks!

**Comment by quartzmo** [comment]
There is no problem here, since the library marshals using protojson rather than ordinary json.

```go
package main

import (
    "log"

    "cloud.google.com/go/asset/apiv1/assetpb"
    "google.golang.org/protobuf/encoding/protojson"
)

func main() {
    a := assetpb.Asset{
        AssetType: "a type",
    }
    b, err := protojson.Marshal(&a)
    if err != nil {
        log.Fatal(err)
    }
    log.Printf("%s", b)
}
```

Output:

```sh
2023/01/24 16:09:38 {"assetType":"a type"}
```

**Comment by eeeeethan2333** [comment]
Got it, thank you @quartzmo

**Comment by eeeeethan2333** [comment]
I still have one question seeking for your help. May I know the reason whay the json structure is defined differently from official doc?
pls excuse that I am not quite familiar with the protojson, what I want to do is I need to include the Asset struct in other json struct as below. in this case, I need to define all the protojson function which is not needed if I use json.marshall directly.

```
package main

import (
	"log"

	"cloud.google.com/go/asset/apiv1/assetpb"
	"google.golang.org/protobuf/encoding/protojson"
)

type MyData struct {
	Asset assetpb.Asset `json:"asset,omitempty"`
}

func main() {

	myData := MyData{
		Asset: assetpb.Asset{
			AssetType: "a type",
		},
	}

	b, err := protojson.Marshal(&myData)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%s", b)
	var myDataV2 MyData
	err = protojson.Unmarshal(b, &myDataV2)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%s", myDataV2.AssetType)
}

```

**Comment by codyoss** [comment]
For your own just structs use the standard library. protojson is only intended for stubs generated with protoc from a proto file.
