### ISSUE TITLE
bigquery: doc of RowIterator.TotalRows seems to be wrong.

### ISSUE THREAD

**Issue by hkanali** [googleapis/google-cloud-go#7285]
[Doc](https://github.com/googleapis/google-cloud-go/blob/main/bigquery/iterator.go#L58-L60) says `Available after the first call to Next.` but, I can retrieve TotalRows anytime.
This problem seem to be resolved before https://github.com/googleapis/google-cloud-go/issues/2946

**Comment by shollyman** [comment]
Need to audit the various and sundry query paths and ensure our RowIterator docs are clear on this.
