### ISSUE TITLE
firestore: Support for count aggregation query

### ISSUE THREAD

**Issue by ivaaaan** [googleapis/google-cloud-go#7324]
**Is your feature request related to a problem? Please describe.**
To my understanding, it's not possible to call the count query from the firestore sdk: https://firebase.google.com/docs/firestore/query-data/aggregation-queries. 

**Describe the solution you'd like**
Count queries should be possible within firestore sdk

**Comment by ivaaaan** [comment]
I have just discovered this: https://pkg.go.dev/cloud.google.com/go/firestore#Query.NewAggregationQuery
Would be nice to update docs on then ;)

**Comment by telpirion** [comment]
@ivaaaan Thank you for the feedback. If you have feedback about the documentation on firebase.google.com, be sure to leave your comment there.
