### ISSUE TITLE
vision: Can't use online images for google cloud vision

### ISSUE THREAD

**Issue by egonik-unlp** [googleapis/google-cloud-go#7331]
**Client**

Not sure

**Environment**

Alpine Docker on GCP, Local Docker, Local Run

**Go Environment**

$ go version
go version go1.19.5 linux/amd64 in all cases 

$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gonik/.cache/go-build"
GOENV="/home/gonik/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gonik/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gonik/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2493489210=/tmp/go-build -gno-record-gcc-switches"
 local config

**Code**

e.g.
```go
func RetText(imageURL string) ([]string, error) {
	ctx := context.Background()
	c, err := vision.NewImageAnnotatorClient(ctx, option.WithCredentialsFile( //REDACTED )
	if err != nil {
		fmt.Println("ERROR CREANDO CLIENTE -> ", err)
		return make([]string, 0), err
	}
	res, err := c.AnnotateImage(ctx, &pb.AnnotateImageRequest{
		Image: vision.NewImageFromURI(imageURL),
		Features: []*pb.Feature{
			{Type: pb.Feature_TEXT_DETECTION, MaxResults: 5},
		},
	})
	if err != nil {
		fmt.Println("Error GOOGLE", err)
		return make([]string, 0), err
	}
	stringIngredientes := res.FullTextAnnotation.GetText()
	arrRes := strings.Split(stringIngredientes, ",")
	for i, item := range arrRes {
		arrRes[i] = strings.ToLower(item)
	}
	return arrRes, nil
}
```

**Expected behavior**
Receiving whatever text was recognized from image. Most of times I do not get this behaviour.

**Actual behavior**
With most image urls I get this error message: 
error:{code:7 message:"We're not allowed to access the URL on your behalf. Please download the content and pass it in."}

**Comment by quartzmo** [comment]
Hi @egonik-unlp,

This behavior is not related to any defect in the `cloud.google.com/go/vision` client library. It is referenced in [this GitHub issue](https://github.com/googleapis/google-cloud-java/issues/2276) from 2017 and [this StackOverflow question](https://stackoverflow.com/questions/71550557/gcloud-vision-api-code-7-were-not-allowed-to-access-the-url-on-your-behalf-ple) from 2022. You may contact  [Cloud Vision API Support](https://cloud.google.com/vision/docs/getting-support) channels for more assistance.
