### ISSUE TITLE
compute: missing support for MultiWriter disk mode

### ISSUE THREAD

**Issue by Shnatsel** [googleapis/google-cloud-go#7333]
[Cloud documentation](https://cloud.google.com/compute/docs/disks/sharing-disks-between-vms#multi_writer_mode) describes the `"multiWriter": "True"` field on disk creation API endpoint.

However, it is not exposed by the Go client library for Compute Engine. That is the case even in latest git (commit 48ba16f3a09893a3527a22838ad1e9ff829da15b). I've double-checked by grepping this repo for "multiwriter" in case-insensitive mode.

**Comment by codyoss** [comment]
The source of truth for the generation of this client is https://github.com/googleapis/googleapis. I don't see mention of that field there. I also see that this is a beta command in gcloud which could indicate it is not available in the stable API yet. If you think it should be the API may need to be republished by the service team in order for that feature to roll out.
