### ISSUE TITLE
storage: Conditions validation errors before writes

### ISSUE THREAD

**Issue by pfridberg** [googleapis/google-cloud-go#7339]
I've recently looked into the code for using pre-conditions when writing to a bucket. The documentation clearly states for each of the different fields in the `Conditions` struct that a zero value has no effect. What it doesn't really explain is the fact that a struct with all fields set to the zero value will fail validation, as opposed to just having no effect and behave just like a writer without any conditions set at all. This confused me as I only got this error when trying to close the writer, and the `Write()` function also returning the number of bytes written.

When digging through the code I discovered that the validation, i.e. supplying a struct with only zero values, of the actual [Conditions](https://github.com/googleapis/google-cloud-go/blob/8722d72d69992a8ca5de85f43145c97acc9ced8f/storage/storage.go#L1703) struct happens inside the goroutine for the read-end part of the `PipeWriter`. This means that the write will happen before the reader closes with en error, which seems a little weird to me. Since we don't need to do any network calls to do the validation [here](https://github.com/googleapis/google-cloud-go/blob/8722d72d69992a8ca5de85f43145c97acc9ced8f/storage/storage.go#L1737), why is this not done synchronously before any writing is done so that we can get the error already when trying to write, instead of having to do another operation before seeing it?

Isn't it more intuitive to return an error and 0 bytes written when calling `Write()` on the writer in this example:
```
conditions := storage.Conditions{DoesNotExist: false}
obj = obj.If(conditions)
writer := obj.NewWriter(ctx)

// no error returned here, only the length of data
if i, err := writer.Write(data); err != nil {
        fmt.Println(err)
}

// error returned here
if err := w.Close(); err != nil {
	switch e := err.(type) {
	case *googleapi.Error:
		if e.Code == http.StatusPreconditionFailed {
			fmt.Println("The object already exists!")
		}
	default:
		panic(err)
	}
}
```

The part of the client code referred to here is in the [OpenWriter](https://github.com/googleapis/google-cloud-go/blob/main/storage/http_client.go#L978) function.

**Comment by tritone** [comment]
Thanks for the issue @pfridberg .

I took a look at the code path you mentioned. One possible cause for confusion is that, as we note in the `Writer.Write` docs, "writes happen asynchronously". To be more specific, the actual API call is lazy; we don't actually make a request to the API until either the Writer's internal buffer is full, or the user calls `Writer.Close`, whichever happens first. Meanwhile, we only validate Conditions when they are applied to the actual API request (see the `applyConds` method); therefore, this doesn't happen until right before the request is to be made.

I think we could in theory have an earlier validation specifically for the case you mention before we start creating the API request object; however this is not in keeping with how the logic around conditions generally flows elsewhere in the library and we generally try not to add extra layers of input validation beyond the minimum required. Also, users need to be aware regardless that data is not written to GCS until `Writer.Close` is called and returns success. If you think this could be clearer in documentation, I'm open to suggestions on that point.

**Comment by pfridberg** [comment]
Thanks for the explanation @tritone.

I think the documentation for the `Writer` is good enough, as it says there you need to check for errors on `Writer.Close`. However, since the validation of the struct isn't happing right away, I guess it could be clearer in the `Conditions` documentation that a zero-value struct isn't just "no effect", but actually not valid. It might be just me, but the "no effect"-statement isn't super clear in this case.
