### ISSUE TITLE
bigquery: maximum concurrency error causes infinite retries

### ISSUE THREAD

**Issue by jameshartig** [googleapis/google-cloud-go#7340]
**Client**

BigQuery

**Environment**

GCE

**Go Environment**

N/A

**Code**

query.Run(ctx)

**Expected behavior**

If backend returns "Query was not admitted as the maximum concurrency has been reached. Please visit the URL to learn more about how the query can be queued in BigQuery: https://cloud.google.com/bigquery/docs/query-queues." the error is retried a reasonable amount of times and then an error is returned. Alternatively maybe it shouldn't retry at all as that might exacerbate the issue.

**Actual behavior**

Run(ctx) never returns and will retry indefinitely. Unfortunately I don't have any goroutine stack from when this happened but we don't any retrying ourselves and we don't see any indication the code after Run ever ran.

**Screenshots**

`jobservice.getqueryresults` errors several times a minute until we restarted the application:
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/112555/216395654-e35dd357-3ced-4c1f-9dde-c08d11b7dffc.png">

**Additional context**

This also could've been a BigQuery server-side bug as well because as soon as we restarted the application the query worked fine. I'm sure the continuous retrying didn't help the concurrency issue but it's unclear if it returned an error if we would've been okay querying again on the same connection.

During that time period we never had more than 2 concurrent queries according to stackdriver metrics:
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/112555/216397236-3ced065f-989a-49a9-bb03-df17f70f14f3.png">

**Comment by shollyman** [comment]
Thanks for the report, I'll have to take a deeper look on this one.  It's related to newer features, so it's entirely possible it was a server issue, or it may represent a need to further amend our default retry predicate.

**Comment by jameshartig** [comment]
@shollyman thanks for the quick response! Let me know if I can be of help on my side at all for investigating. Also, just to clarify, the error message mentioned query queues, which I know is a preview feature right now, but we're not using those.

**Comment by shollyman** [comment]
I was able to reproduce this.

The TL;DR is that the error responses here appear to have changed subtly, and we're interpreting a terminal error (query was not admitted) as a ratelimit pushback and retrying the polling of the job, rather than recognizing the job failed.  I've opened internal issue 268396903 to track this internally.

**Comment by shollyman** [comment]
Marking this blocked, backend team is working on the signaling problem.

**Comment by jameshartig** [comment]
@shollyman thanks for the update. Does that mean there won't need to be any update to this client and the backend fix should resolve the issue?

**Comment by shollyman** [comment]
Yes, effectively.  The intent is to go back to returning `jobRateLimitedExceeded` rather than the ambiguous `rateLimitExceeded` as the structured error reason.  We don't retry the former as its a terminal state, but continue to retry the latter.

**Comment by jameshartig** [comment]
@shollyman any update on the backend changes?

**Comment by shollyman** [comment]
Nothing substantial.  My understanding is this is gated behind the rollout of newer [admission control features](https://cloud.google.com/bigquery/docs/query-queues), and should be resolved when this is done.

**Comment by shollyman** [comment]
quick update:  per the relevant service team, a fix for this is in the process of rolling out.  I don't have the timeline, but at that point it should be possible to disambiguate job vs API rate limit responses.

**Comment by shollyman** [comment]
Closing this out, as all regions should now have the necessary changes.
