### ISSUE TITLE
pubsub: cached contexts causing context canceled errors

### ISSUE THREAD

**Issue by uditha-atukorala** [googleapis/google-cloud-go#7481]
**Client**

PubSub

**Environment**

macOS Ventura with ADC setup using `gcloud auth application-default login`.

**Go Environment**

```
❯ go version
go version go1.20.1 darwin/arm64
```

**Code**

```go
package main

import (
	"context"

	"cloud.google.com/go/pubsub"
)

var topic *pubsub.Topic

func initClient() {
	ctx, cancel := context.WithTimeout(context.Background(), 5000000000)
	defer cancel() 

	client, err := pubsub.NewClient(ctx, "project-id")
	if err != nil {
		panic(err)
	}

	topic = client.Topic("topic-id")

	ok, err := topic.Exists(ctx)
	if err != nil {
		panic(err)
	}

	if !ok {
		panic("Topic doesn't exist")
	}
}

func main() {
	initClient() // simulates pub/sub client being initialised during boot

	// Following simulates publishing to pub/sub within a request handler
	ctx, cancel := context.WithTimeout(context.Background(), 5000000000)
	defer cancel()

	msg := &pubsub.Message{
		Data: []byte(`{"k": "v"}`),
	}

	r := topic.Publish(ctx, msg)
	if _, err := r.Get(ctx); err != nil {
		panic(err)
	}
}
```

**Expected behavior**

Should be able to publish messages to Pub/Sub topic successfully.

**Actual behavior**

Attempts to publish messages to Pub/Sub topic fails with error message `rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: context canceled`.

**Additional context**

It seems the `context` used to initialise the Pub/Sub client is used when publishing messages although a new `context` is passed through.

**Comment by codyoss** [comment]
The lifetime of the client context should match that of the application. So usually it should be a background context. From [our docs](https://pkg.go.dev/cloud.google.com/go#hdr-Timeouts_and_Cancellation): "Do not attempt to control the initial connection (dialing) of a service by setting a timeout on the context passed to NewClient. Dialing is non-blocking, so timeouts would be ineffective and would only interfere with credential refreshing, which uses the same context."
