### ISSUE TITLE
container: List clusters returns errors for the wrong project

### ISSUE THREAD

**Issue by imilchev** [googleapis/google-cloud-go#7485]
**Client**
Container

**Environment**
macOS Ventura 13.2.1

**Go Environment**

$ go version
```
go version go1.19.6 darwin/arm64
```
$ go env
```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/ivanmilchev/Library/Caches/go-build"
GOENV="/Users/ivanmilchev/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ivanmilchev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ivanmilchev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.19/1.19.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.19/1.19.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ivanmilchev/Projects/cnquery/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y2/x6cy9qs12hd29g_12nhby5_h0000gn/T/go-build714947938=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

e.g.
```go
package main

func main() {
	ctx := context.Background()
        creds, err := googleoauth.FindDefaultCredentials(ctx)
        if err != nil {
               return err
        }


	containerSvc, err := container.NewClusterManagerClient(ctx, option.WithCredentials(creds))
	if err != nil {
		return err
	}
	defer containerSvc.Close()

	// List the clusters in the current projects for all locations
	resp, err := containerSvc.ListClusters(ctx, &containerpb.ListClustersRequest{Parent: "projects/12345678/locations/-"})
	if err != nil {
		return err
	}
}
```

**Expected behavior**
I want to list the clusters in my project `12345678`

**Actual behavior**
I receive an error for a completely different project:
```
rpc error: code = PermissionDenied desc = Kubernetes Engine API has not been used in project 87654321 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=87654321 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.\nerror details: name = ErrorInfo reason = SERVICE_DISABLED domain = googleapis.com metadata = map[consumer:projects/87654321 service:container.googleapis.com]\nerror details: name = Help desc = Google developers console API activation url = https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=87654321
```

**Additional context**
gcloud CLI returns the correct project set as default:
```
gcloud config get-value project    
12345678
```

I checked the contents of `~/.config/gcloud/application_default_credentials.json`:
```json
{
  "client_id": "***",
  "client_secret": "***",
  "quota_project_id": "87654321", # <-- here is the ID of the project I am getting error for
  "refresh_token": "***",
  "type": "authorized_user"
}
```

Running `gcloud container clusters list` returns the list of clusters from the correct project

**Comment by quartzmo** [comment]
Hi @imilchev, thank you for this question.

The [README](https://github.com/googleapis/google-cloud-go#authorization) states:

> By default, each API will use [Google Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials) for authorization credentials used in calling the API endpoints. This will allow your application to run in many environments without requiring explicit configuration.

Therefore, I have two questions:

1. Is there a reason you explicitly show the usage of `googleoauth.FindDefaultCredentials` to retrieve the default credentials in your example, or can this be removed?
2. Have you tried using [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login) to change to the desired project? Unfortunately, I don't see this command mentioned in the google-cloud-go README, but it is discussed in the [google-cloud-java README](https://github.com/googleapis/google-cloud-java/blob/main/README.md#application-default-credentials).

**Comment by imilchev** [comment]
Hi @quartzmo, 

I feel like the problem I am encountering is happening only for the `container` package. I am part of a company that develops security software and we have integrations with a lot of the services in GCP. We follow the same pattern with all of them and the only one that is causing issues is this one. 

I will try to explain a bit what we are doing:
- We try to detect your default creds for GCP with `googleoauth.FindDefaultCredentials(ctx)`. That is in case you haven't explicitly provided other creds
- We then scan the default organization for your creds and discover all projects you have access to
- For every project we discover all resources you have deployed and we run checks against them

This is the reason why the snippet I sent to you looks that way. With the same credentials we are potentially listing resources in multiple different GCP projects (that is if your user has access to them).

I ran a couple of more tests to pin-point what is going wrong exactly and will try to describe it below. Hopefully it makes sense.

`~/.config/gcloud/application_default_credentials.json` contents:
```json
{
  "client_id": "***",
  "client_secret": "***",
  "quota_project_id": "projectA", # <-- here is the ID of the project I am getting error for
  "refresh_token": "***",
  "type": "authorized_user"
}
```

In `projectA` Kubernetes API has never been used and is therefore disabled.

I then try to list the clusters in `projectB` with the same code snippet that I have provided in the original question. I get the following error:
```
rpc error: code = PermissionDenied desc = Kubernetes Engine API has not been used in project projectA before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=projectA then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.\nerror details: name = ErrorInfo reason = SERVICE_DISABLED domain = googleapis.com metadata = map[consumer:projects/projectA service:container.googleapis.com]\nerror details: name = Help desc = Google developers console API activation url = https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=projectA
```

For the sake of testing I went to the GCP console and enabled the Kubernetes API in `projectA`. Then I ran the exact same code again where I want to list the clusters in `projectB`. I get no error and correctly receive back the clusters in `projectB`.

It seems like there is some weird check happening somewhere in the GCP API that tries to validate whether the API that you are trying to use is enabled in the project that is specified in `~/.config/gcloud/application_default_credentials.json`. However, that is not necessarily the project that you are trying to query, so the error is irrelevant in this case. The check should validate that the API is enabled for the project that is specified as input parameter to the API call.

I am happy to demo it to you if it makes it easier to understand the problem!

**Comment by quartzmo** [comment]
> I am happy to demo it to you if it makes it easier to understand the problem!

Thank you for this detailed description. Your experiment with enabling the Kubernetes API in projectA now makes it much clearer.

> It seems like there is some weird check happening somewhere in the GCP API

Unfortunately, the scope of this repo (and issues opened against it) is limited to the client libraries and their helper libraries. We have no insight or access to the internal behavior of the backend APIs, for which in this case you must contact GKE support.

I will investigate the open-source auth stack (primarily [oauth2/google](https://github.com/golang/oauth2/tree/master/google)) to see if I can find the cause of the problem. (Please take a look yourself as well.)

**Comment by imilchev** [comment]
I skimmed through the code I can't see any logic that in the auth stack that would cause the `container` API to behave differently than all the others. It might be a server-side issue that is causing this. If that is the case where do we report those?

**Comment by quartzmo** [comment]
Thanks for taking a look at the client auth stack. I will do, and report back. Meanwhile, if you have paid support, that's the best path, but there are product issue tracker links. Click `Create new Google Kubernetes Engine` in this page: https://cloud.google.com/support/docs/issue-trackers

**Comment by quartzmo** [comment]
@imilchev 

Are you sure this assumption is correct? (emphasis mine)

> It seems like there is some weird check happening somewhere in the GCP API that tries to validate whether the API that you are trying to use is enabled in the project that is specified in ~/.config/gcloud/application_default_credentials.json. However, that is not necessarily the project that you are trying to query, so the error is irrelevant in this case. **The check should validate that the API is enabled for the project that is specified as input parameter to the API call.**

I spend some time trying to verify it, but only found statements such as this one in [Service usage - troubleshooting](https://cloud.google.com/service-usage/docs/troubleshooting):

> To use any Google API service, you need to:
> 
> 1. Create or use an existing Google Cloud project.
> 2. Enable the service for the Cloud project.
> 3. Pass an API key or an OAuth access token associated with the Cloud project.

**Comment by codyoss** [comment]
I believe the billing project, quota project, also needs the api enabled. So I think this error is correct.

**Comment by quartzmo** [comment]
Please re-open for further discussion if you have new information and still believe the error is incorrect.
