### ISSUE TITLE
testing: samples testing is problematic

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-go#7493]
https://github.com/GoogleCloudPlatform/golang-samples/pull/2857 against golang-samples added a new quickstart for documentai, and carved out its own module.

There is nothing inherently wrong with the sample, but it causes problems for google-cloud-go's use of samples testing because it's the only target in documentai module, so the effective steps of `cd documentai; go build ./...` yield an error similar to the following:

```
Building module ./documentai/go.mod
go: build output "documentai_quickstart" already exists and is a directory
```

go build appears to handle the case of building a single package vs multiple packages differently.

example log demonstrating this: https://source.cloud.google.com/results/invocations/34e25818-668e-40a3-8ed9-b39b492f54b1/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Fsamples/log

**Comment by codyoss** [comment]
We don't have this test any more. Closing.
