### ISSUE TITLE
alloydb: Go client library for AlloyDB

### ISSUE THREAD

**Issue by GauravJain21** [googleapis/google-cloud-go#7498]
**Is your feature request related to a problem? Please describe.**
I would like to have Go client library support for AlloyDB so that external users can use it via code. We also need it urgently for developing robust Terraform templates

**Describe the solution you'd like**
The goal is to have a Go client library for AlloyDB.

**Describe alternatives you've considered**
There are two alternatives:
1. API calls
2. gcloud cli

- Using gcloud cli for dev purposes is a non-trivial task as it is a command line tool.
- Directly using the APIs is:
    - Hectic as you need to construct the payload and serialise and deserialise request and responses.
    - Cumbersome as you also need to write the Exception and Error handling logic yourself.

**Additional context**

**Comment by quartzmo** [comment]
Good news, it looks like we have a green light to move ahead with this.

https://github.com/googleapis/googleapis/tree/master/google/cloud/alloydb

**Comment by GauravJain21** [comment]
Hey Chris,
Thank you so much for the prompt reply and action!
Could you please help me with a timeline when this client can be available for the general public to use?
I see that the kokoro build is failing currently. I went to Sponge and can see errors related to variable naming and loading phase errors. There are over 7 errors I could see in the test-suite.
Does this impact the general availability of our Go client library or can we guarantee that the generated clients right now are safe to use?
Best,
Gaurav Jain

**Comment by quartzmo** [comment]
> Could you please help me with a timeline when this client can be available for the general public to use?

I am hoping to release the `v1`, `v1alpha` and `v1beta` clients by EOD tomorrow (2023-03-02), in a single Go module.

> Does this impact the general availability of our Go client library or can we guarantee that the generated clients right now are safe to use?

As a rule, new generated clients do not depend on automated testing other than a simple build to verify that they compile. For established clients, there is API breaking change detection.

The `v1` client will be released as "beta". After approximately a 1-month bake period, if no issues arise, it will be promoted to "GA".

**Comment by quartzmo** [comment]
https://github.com/googleapis/google-cloud-go/pull/7503

**Comment by quartzmo** [comment]
Release is at https://github.com/googleapis/google-cloud-go/releases/tag/alloydb/v0.1.0
