### ISSUE TITLE
[Google Chat] Unable to unmarshal PubSub message

### ISSUE THREAD

**Issue by mancubus77** [googleapis/google-cloud-go#7521]
#### Environment details

  - Programming language: go 
  - OS: MacOS Monterey 
  - Language runtime version: 1.19.5
  - Package version: 0.110.0

#### Steps to reproduce

 Messages from Google Chat published to PubSub topic and consumed by the application: 
```        
        var incomingMessage *chat.Message
	err = sub.Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
		log.Printf("Received Message %s.\n", string(msg.Data))
		msg.Ack()
		err := json.Unmarshal(msg.Data, &incomingMessage)
```

 `incommingMessage` is empty and has very little information about the event 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/16170560/221702287-61a885e6-c262-40e5-a2ab-db2bc0124109.png">

 Meanwhile unmarshaling in interface works well
```
	err = sub.Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
		log.Printf("Received Message %s.\n", string(msg.Data))
		msg.Ack()
		var chatMessage map[string]interface{}
		json.Unmarshal(msg.Data, &chatMessage)
```
<img width="743" alt="image" src="https://user-images.githubusercontent.com/16170560/221702746-d7a00cfb-5587-4f4a-9f99-2eadba6cfb1b.png">

  1. Add bot
  2. Create topic
  3. Configure bot to send messages to topic
  4. subscribe to topic 
  5. unmarchal received message to *chat.Message structure

**Comment by codyoss** [comment]
Can you please check and share the error you are getting from unmarshalling the data.

**Comment by mancubus77** [comment]
> Can you please check and share the error you are getting from unmarshalling the data.

There is no error, data structure is just empty.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/16170560/223998769-71d6dc11-279a-4a02-be94-2874d76f4571.png">

Only `incomingMessage.space` and `incomingMessage.ServerResponse` unmarshalled

**Comment by mancubus77** [comment]
Struct doesn't match with JSON Schema:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/16170560/224001264-dd74c782-8669-4bd6-9e99-77c770f83866.png">

Left window: unmarshalled JSON 
Right window: *chat.Message structure

**Comment by codyoss** [comment]
I don't think you are populating it to the correct model. Looking at the docs you want this: https://developers.google.com/chat/api/reference/rest/v1/Event

I am not sure if a type is published for this. https://pkg.go.dev/google.golang.org/api@v0.111.0/chat/v1#DeprecatedEvent may be the thing, but you can always create your own type to. Hope that helps.

**Comment by mancubus77** [comment]
Thank you @codyoss 
`DeprecatedEvent` is right structure... weird that it's `deprecated` and there is no replacement.
