### ISSUE TITLE
spanner: timeout / context canceled during getting session

### ISSUE THREAD

**Issue by ericwenn** [googleapis/google-cloud-go#7527]
**Client**

Spanner

**Environment**

Managed Cloud Run

**Description**
Since upgrading spanner library to v1.43.0 we have started seeing intermittent timeout/context canceled issues when getting sessions, with error message:
```
timeout / context canceled during getting session.
Enable SessionPoolConfig.TrackSessionHandles if you suspect a session leak to get more information about the checked out sessions.
```

After this happens once the Spanner client is unable to get any sessions, which means all requests to our service times out after 10s (our configured request deadline), until the instance is restarted.

![Screenshot_20230309_170104](https://user-images.githubusercontent.com/5495697/224082407-fd4bc9f2-189b-485f-b420-cc88979b109f.png)
^Traces from when issue happens, until instance is manually restarted (~4:20 - 4:30).

Looking at the traces does not add more information for debugging. The only culprit is `cloud.google.com/go/spanner.Query (9974.995 ms)` which seems to block everything.

We have not been able to reproduce this issue consistently, it seems to happen randomly every 1-2 days.

---

When we noticed this first we rolled back to v1.42.0 and have not seen this issue on that version (running in production for ~1 week). 

Looking at recent issues in this repository we tried to bump to the unreleased version based on the fix for [this issue](https://github.com/googleapis/google-cloud-go/issues/7496), but still saw the issues on that commit.

Judging from changes between v1.42.0 and v.1.43.0 [these changes](https://github.com/googleapis/google-cloud-go/pull/7149) seem to be the culprit, but I'm not sure of that.

**Comment by rahul2393** [comment]
Hello @ericwenn 
Can you help with your sessionConfig values, and what type of load distribution you have read:write ration to help us replicate the issue.

**Comment by rahul2393** [comment]
Thanks for quick answer, do you have QPS numbers with 1 client

**Comment by ericwenn** [comment]
Avg 1 QPS

**Comment by jzelinskie** [comment]
We've got some reports (mentioned in GitHub above) from folks using v1.42.0

**Comment by ericwenn** [comment]
@rahul2393 any ideas on this?

**Comment by rahul2393** [comment]
Hello @ericwenn We are trying to replicate the issue at our end with session config having min/max=1 session, will update here if we find anything.

Feel free to share any code you have to help replicate quickly.

**Comment by ericwenn** [comment]
Hello @rahul2393,
After enabling tracking of session handles and waiting for the issue to re-appear we managed to track this down, and likely fix it.

We were opening a ReadOnlyTransaction without closing it after we're done. We are deploying that fix right now, and will keep an eye out.

Off-topic: Do you have any ideas on how to systematically prevent these type of issues, for example when running tests not allowing the spanner client to have open sessions when it is shut down (or similar)?

**Comment by rahul2393** [comment]
@ericwenn Closing this ticket since you already found the issue, will create another ticket for preventing client to open sessions when it is shut down.
Feel free to open this if you feel this issue need more investigation.
Thanks
