### ISSUE TITLE
vision: missing package paths in googleapis protos for v2 client

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-go#7534]
**Client**

Cloud Vision

**Expected behavior**

googleapis/googleapis Protobuf definitions should support the imports of `v2` clients in google-cloud-go.

**Actual behavior**

As originally raised in https://github.com/googleapis/googleapis/pull/782, per @wyattanderson:

> the current Go package path for the `google.cloud.vision.v1` Protobuf definitions in googleapis/googleapis is incorrect. `cloud.google.com/go/vision/apiv1/visionpb` does not exist as a Go module in googleapis/googleapis. When published to `googleapis/google-cloud-go`, a `v2/` path segment is added (I believe this occurred in #6072). This complicates depending on the googleapis/googleapis Protobuf definition because the generated Go code will be incorrect unless the Go package dependency is overridden out-of-band.

**Additional context**

Started after feat(vision/v2): Release breaking changes as v2 module #6072

**Comment by codyoss** [comment]
This has been fixed
