### ISSUE TITLE
docs: consistent godoc strings for GA status

### ISSUE THREAD

**Issue by broady** [googleapis/google-cloud-go#755]
I propose we use a consistent code block after the first paragraph/sentence of a godoc if the package isn't GA.

For example, for monitoring, currently:

> 
> Package monitoring is an experimental, auto-generated package for the Stackdriver Monitoring API.
> 
> Manages your Stackdriver Monitoring data and configurations. Most projects must be associated with a Stackdriver account, with a few exceptions as noted on the individual method pages.
> 

Would become:

> 
> Package monitoring is an auto-generated package for the Stackdriver Monitoring API.
> 
> ```
> NOTE: This package is not stable, and may be subject to change.
> ```
> 
> Manages your Stackdriver Monitoring data and configurations. Most projects must be associated with a Stackdriver account, with a few exceptions as noted on the individual method pages.
> 

We'd want to use the same notice in non-autogenerated packages (e.g., errorreporting)

-------------------------------------------------

also, in the README, we could use some badges to make the different statuses a bit clearer (of course, using alt-text for screen readers):

![stable](https://img.shields.io/badge/%20-stable-green.svg)
![beta](https://img.shields.io/badge/%20-beta-yellow.svg)
![alpha](https://img.shields.io/badge/%20-alpha-red.svg)

What do you think?

/cc @pongad @jba @rakyll

**Comment by pongad** [comment]
I like this. I can make the change for GAPICs

**Comment by jba** [comment]
SGTM, except that I would want to distinguish beta (some changes might happen) from alpha (anything goes) in the wording of the comment.

**Comment by adams-sarah** [comment]
:tada: :tada:

**Comment by broady** [comment]
> This package is in beta, and not stable, and may be subject to changes.

> This package is in alpha, and not stable, and is likely to be subject to changes.

**Comment by adams-sarah** [comment]
oops sorry just seeing this.

@broady the alpha one I don't think makes [gramatical] sense? maybe I'm wrong.
I think it should either be "is likely to change" or "is subject to changes". But "likely subject to changes" is like saying "we are not sure if we are sure if the code will change", I think.

**Comment by broady** [comment]
+1. "likely to change" sgtm

**Comment by adams-sarah** [comment]
oh wait, i guess the beta one is incorrect too then..

**Comment by pongad** [comment]
All GAPICs client should be fixed now, I'll unassign myself.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/36891 should close out this issue, IIUC.
