### ISSUE TITLE
metadata.FromContext doesn't work when using vendor folder with gen2 pub/sub trigger cloud function

### ISSUE THREAD

**Issue by gowelaine** [googleapis/google-cloud-go#7557]
**Client**

pub/sub event-driven cloud function (gen2) with vendor folders

**Environment**
N/A

**Go Environment**
1.19

**Code**
```

func init() {
	functions.CloudEvent("Test", test)
}

func test(ctx context.Context, e event.Event) error {
	log.Printf("%+v\n", ctx)
	meta, err := metadata.FromContext(ctx)
	if err != nil {
		// Assume an error on the function invoker and try again.
		return fmt.Errorf("metadata.FromContext: %v", err)
	}

return nil
}
```

**Expected behavior**

Metadata should be extracted from context

**Actual behavior**
```
2023/03/15 17:43:03 &{Context:context.Background.WithValue(type *http.contextKey, val <not Stringer>).WithValue(type *http.contextKey, val 192.168.1.1:8080).WithCancel.WithCancel parent:0xc0000af9c0}

Function error: metadata.FromContext: unable to find metadata
```

**Additional context**
I tried to follow this bug to remove the folder metadata https://github.com/googleapis/google-cloud-go/issues/1947, however, it fails to build my cloud function due to unable to find directory.

Based on my understanding 1.19 should be ok, but it seems like this is still an issue.

a little content is, if I run this with pub/sub cloud function gen1, it works well
```

func Test(ctx context.Context, m PubSubMessage) error {
	meta, err := metadata.FromContext(ctx)
	if err != nil {
		// Assume an error on the function invoker and try again.
		return fmt.Errorf("metadata.FromContext: %v", err)
	}
}

```

**Comment by codyoss** [comment]
I wonder if this issue should be filed against the functions framework: https://github.com/GoogleCloudPlatform/functions-framework-go

May be related to https://github.com/GoogleCloudPlatform/functions-framework-go/pull/103

**Comment by gowelaine** [comment]
that is a bit interesting since if we run gen1 cloud function, it does not throw error but only gen2

**Comment by quartzmo** [comment]
Closing, replaced by https://github.com/GoogleCloudPlatform/functions-framework-go/issues/176
