### ISSUE TITLE
bigquery: bigquery.Value has nil value when the cell output has zero value

### ISSUE THREAD

**Issue by shrdlu68** [googleapis/google-cloud-go#7577]
Attempting to cast a `bigquery.Value` (an interface{}) to a type such as a `float64` results in a panic, despite the cell value having a zero value for the type ("0.0").

The expected behavior is that bigQuery.Value would result in the float zero value rather than panic because the it is nil-valued.

**Comment by alvarowolfx** [comment]
@shrdlu68 I tried to reproduce your scenario with the given snippets and wasn't able to see the same behavior. 

Reading as a slice of `bigquery.Value`s:
```
ctx := context.Background()
q := client.Query("select @zeroVal as floatZeroValue, @val as floatValue")
q.Parameters = []bigquery.QueryParameter{
{
	Name:  "zeroVal",
	Value: 0.0,
},
{
	Name:  "val",
	Value: 3.14,
},
}
it, err := q.Read(ctx)
if err != nil {
	  t.Fatal(err)
}
for {
	  var row []bigquery.Value
	  err = it.Next(&row)
	  if err == iterator.Done {
	  	  break
 	   }
  	  if err != nil {
	  	  t.Fatal(err)
  	  }
  	  fmt.Println(row)
	  floatZeroValue := row[0].(float64)
	  fmt.Println(floatZeroValue, reflect.TypeOf(row[0]))
  	  floatValue := row[1].(float64)
  	  fmt.Println(floatValue, reflect.TypeOf(row[1]))
}
/* Output 
[0 3.14]
0 float64
3.14 float64
*/
```

Reading as a struct with float64 fields:
```
ctx := context.Background()
q := client.Query("select @zeroVal as floatZeroValue, @val as floatValue")
q.Parameters = []QueryParameter{
	{
		Name:  "zeroVal",
		Value: 0.0,
	},
	{
		Name:  "val",
		Value: 3.14,
	},
}
it, err := q.Read(ctx)
if err != nil {
	t.Fatal(err)
}
for {
	var row struct {
		FloatZeroValue float64
		FloatValue     float64
	}
	err = it.Next(&row)
	if err == iterator.Done {
		break
	}
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(row)
	floatZeroValue := row.FloatZeroValue
	fmt.Println(floatZeroValue)
	floatValue := row.FloatValue
	fmt.Println(floatValue)
}
/* Output 
{0 3.14}
0
3.14
*/
```

Can you provide a bit more information so I can help on your issue ?

**Comment by shrdlu68** [comment]
Thanks @alvarowolfx 
This is what a sample of the query output looks like when I run the exact same query on the "SQL Workspace":
```
[
  {
    "foo_min": "18564.0",
    "foo_max": "18564.0",
    "foo": "48058.396791502855"
  },
  {
    "foo_min": "0.0",
    "foo_max": "0.0",
    "foo": "14076.674851478565"
  },
  {
    "foo_min": "0.0",
    "foo_max": "0.0",
    "foo": "6501.4528056355775"
  },
  {
    "foo_min": "3.8589437548557659",
    "foo_max": "4.2292682950271505",
    "foo": "395413.89480189676"
  }
]
```
As you can see, there are no nil values, but attempting to read foo_min panics with `panic: interface conversion: bigquery.Value is nil, not float64`

**Comment by alvarowolfx** [comment]
@shrdlu68 are you reading directly from a table without any transformation or are you using some SQL function ? I can only see the problem if explicitly the query returns mixed values for `float64` and `NULL`s. Like the following:

```
ctx := context.Background()
q := client.Query(`
	create or replace table test_dataset.test_null_float (
	value float64
	);
	
	truncate table test_dataset.test_null_float;

	insert into test_dataset.test_null_float VALUES 
	(1.2),
	(2.4),
	(RAND()),
	(RAND()),
	(RAND()),
	(RAND()),
	(RAND()),
	(RAND()),
	(NULL),
	(1.3);
	
	select min(ifnull(value,0.0)), max(ifnull(value,0.0)), value  
	from test_dataset.test_null_float
	group by value;
`)
it, err := q.Read(ctx)
if err != nil {
	t.Fatal(err)
}
for {
	var row []Value
	err = it.Next(&row)
	if err == iterator.Done {
		break
	}
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(row)
	fmt.Print("[")
	for _, v := range row {
		floatValue := 0.0
		if v != nil {
			floatValue = v.(float64)
		}
		fmt.Print(floatValue, reflect.TypeOf(v), " ")
	}
	fmt.Println("]")
}
```

Can you give more information on your SELECT statement ?

**Comment by shrdlu68** [comment]
There are no transformations. The columns are derived from `SUM` aggregations:
```
SELECT SUM(min) AS sum_foo, SUM(max) AS foo_max, SUM(expected_value) AS foo...
```
In any case, the Json output above is the output of the exact same query without modification, which would match what is received after `q.Read()`.

**Comment by alvarowolfx** [comment]
@shrdlu68 would be nice if you can provide some test code that can reproduce that issue. I tried a couple of variations here ( like using NUMERIC/BIGNUMERIC fields and the other samples that I sent ) but couldn't see the behavior that you reported. I'm more than happy the fix the issue, but without a way to reproduce it, I'm a bit blocked.
