### ISSUE TITLE
bigquery/storage/managedwriter: restore stream after crash

### ISSUE THREAD

**Issue by stgleb** [googleapis/google-cloud-go#7591]
**Is your feature request related to a problem? Please describe.**
I wan't to write some portion of data via pending stream, but I am concerned about data
that was in pending state if process crashes. Is there a way to recover stream by any descriptor e.g name and finalize and commit it?

**Describe the solution you'd like**

Make streams reusable and accessible by the name or id to reuse them in case of process crash.

**Comment by shollyman** [comment]
There's not currently a way to list recent streams in the API, if that's the nature of the recovery you're asking about.  You'll need to keep track of the stream IDs.

If you're relying on the library to create the pending streams for you transparently, invoking [`StreamName()`](https://pkg.go.dev/cloud.google.com/go/bigquery/storage/managedwriter#ManagedStream.StreamName) on the ManagedStream instance will give you the identifier.

**Comment by stgleb** [comment]
@shollyman So, did I get it right, If I instantiate stream with the same name after process restart I would be able to commit pending writes from previous run?

**Comment by stgleb** [comment]
@shollyman great! this is exaclt what I was looking for.

**Comment by stgleb** [comment]
@shollyman the very last question from me, in example https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/bigquery/snippets/managedwriter/bigquerystorage_append_rows_pending.go#L143

I can see that managed writer name is taken from pending, but is there option to use custom name? For instance I'll have my own static stream name `my_stream`.

**Comment by shollyman** [comment]
The format of a stream identifier is determined by the system, you have no ability to use leverage custom names.

They're generally of the form `projects/someprojectid/datasets/somedataset/tables/sometable/streams/streamid`, where stream ID is either some opaque hash generated by the system, or the special name "default" in the case of default streams.

**Comment by stgleb** [comment]
okay, got it
