### ISSUE TITLE
bigquery: Timeout not working

### ISSUE THREAD

**Issue by jeancarlosgarcia** [googleapis/google-cloud-go#7604]
**Client**

Bigquery

**Code**
```
package client

func executeQuery(ctx context.Context, q *bigquery.Query) (*bigquery.RowIterator, error) {
	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
	defer cancel()

	return q.Read(ctx)
}
```

**Expected behavior**

It should return a timeout error.

**Actual behavior**

Even assigning a timeout of 1 * time.Nanosecond, the client takes more than the configured time.

**Comment by shollyman** [comment]
Thanks for the report, was able to confirm we're not respecting context properly here.  I'll look into adding a fix for this.
