### ISSUE TITLE
httpr: Release a new version with updated artifacts

### ISSUE THREAD

**Issue by ofek** [googleapis/google-cloud-go#7628]
**Is your feature request related to a problem? Please describe.**

We are in need of this but the latest release seems to have been 5 years ago https://github.com/googleapis/google-cloud-go/releases/tag/v0.25.0

**Additional context**

https://github.com/google/go-replayers/issues/27#issuecomment-1481758534

**Comment by codyoss** [comment]
This module has had many releases since then. Please see: https://pkg.go.dev/cloud.google.com/go?tab=versions.  Hope that helps

**Comment by ofek** [comment]
@codyoss Can you please reopen this? I'm talking about something completely different.

cc @jba Perhaps you can help explain the situation regarding why artifacts are uploaded here rather than the origin repo.

**Comment by codyoss** [comment]
I am unsure of what these artifacts are or how they are used. If you need a binary of one of the projects in this repo I suggest building it for the OS you need. The only publishing this repo currently does it tagging for modules.
