### ISSUE TITLE
firestore: Bulkwriter not doing what writebatch used to do. Can't write 2 fields to same doc if one is a value and other a Servertimestamp at same time, for ex.

### ISSUE THREAD

**Issue by diver2** [googleapis/google-cloud-go#7636]
The straightforward code below also returns the same error, due to the same reason.
```go
func main() {
	ctx := context.Background()
	app, err := firebase.NewApp(ctx, nil)
	if err != nil {
		log.Fatalf("error initializing app: %v\n", err)
	}

	client, err12 := app.Firestore(ctx)
	if err12 != nil {
		log.Fatalf("app.Firestore: %v", err12)
	}
	map1 := map[string]interface{}{}
	map1["answer"] = 42
	map1["createdAt"] = firestore.ServerTimestamp
	client.Collection("AATEST").Doc("SETDOC").Set(ctx, map1) // THIS WORKS

	bulkWriter := client.BulkWriter(ctx)
	_, errBulkBUGS := bulkWriter.Set(
		client.Collection("AATEST").Doc("SETDOCVIABULK"),
		map1,
	)
	if errBulkBUGS != nil {
		fmt.Printf("errBulkBUGS = %v\n", errBulkBUGS)
	}
	bulkWriter.End()
	return
}
```
returns: errBulkBUGS = firestore: too many writes sent to bulkwriter

_Originally posted by @diver2 in https://github.com/googleapis/google-cloud-go/issues/7558#issuecomment-1472735595_

**Comment by diver2** [comment]
See also - 
https://github.com/googleapis/google-cloud-go/issues/7558#issuecomment-1472723266

**Comment by telpirion** [comment]
cc @bcoe and @codyoss 

Hello @diver2 

Please be sure to review our [CODE_OF_CONDUCT](https://github.com/googleapis/google-cloud-go/blob/main/CODE_OF_CONDUCT.md) before responding. I will attempt to answer your questions one-by-one.

1. The `Bulkwriter.Set()` method will evaluate the `map` that you've provided as two separate writes--one for the key "answer" and another for "createdAt". If you comment out the line `map["createdAt"] = firestore.ServerTimestamp`, then the error doesn't happen. 
**Action item**: This definitely could be clearer in the documentation.
2. When I commented out the line `map["answer"] = 42`, I still get the error. It does seem like `Bulkwriter.Set()` treats the `firestore.ServerTimestamp` constant as two separate writes to the same document--one write being the document's key and the other being the "createdAt" field in the document. See the source code [here](https://github.com/googleapis/google-cloud-go/blob/main/firestore/document.go#L229) and [here](https://github.com/googleapis/google-cloud-go/blob/main/firestore/document.go#L323). The [documentation also implies this](https://pkg.go.dev/cloud.google.com/go/firestore#pkg-constants) but could definitely be clearer. 
**Action item**: Determine whether this feature request is feasible.
3. `Bulkwriter` is not intended to completely replace `WriteBatch`. If you need to make multiple writes to the same document, you should use a [`Transaction`](https://pkg.go.dev/cloud.google.com/go/firestore#Transaction) instead. See the [`WriteBatch` documentation](https://pkg.go.dev/cloud.google.com/go/firestore#WriteBatch).

In the implementation of `Bulkwriter`, the Go client library uses the gRPC [`BatchWrite`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.BatchWriteRequest). The service comments explicitly say that "You cannot write to the same document more than once per request." The `WriteBatch` type, provided in the Go client, uses the gRPC [`Write`](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.Write) method, passing in multiple writes to the `update_transforms` method. Note that the `WriteBatch` applies transforms atomically and in order (`Bulkwriter` does not). If you require multiple writes to the same document--which implies they need to be atomic and in-order--then please use `Transaction`.

I will leave this issue open until we update the documentation accordingly.

**Comment by diver2** [comment]
@meredithslota 
I believe this should not have been marked as a feature request, but as a bug. 
I think this impacts your prioritization of issues. I imagine you have an auto filter that puts bugs before feature requests.
Att

**Comment by bhshkh** [comment]
We are working on this.
