### ISSUE TITLE
storage.client: how to undelete/restore bucket

### ISSUE THREAD

**Issue by cdancy** [googleapis/google-cloud-go#7684]
Hello All,

From the GCP console and then going to `Logging -> Logs Storage` I can click on a bucket that is in a "pending deletion" state and click "restore deleted bucket". How can we do this through the golang sdk? We can't for the life of us figure this out unless it's simply not possible here for some reason.

Thanks AOT,
Chris

**Comment by tritone** [comment]
Thanks for the question. Logs storage is via the Logging API, not Cloud Storage, so the operations live in that product's client library. See https://pkg.go.dev/cloud.google.com/go/logging@v1.7.0/apiv2#ConfigClient.UndeleteBucket I believe.
