### ISSUE TITLE
bigquery: provide a way to handle unmarshalling error in RowIterator.Next()

### ISSUE THREAD

**Issue by akkivarma10** [googleapis/google-cloud-go#7699]
**Is your feature request related to a problem? Please describe.**
While iterating over the job results using `RowIterator.Next()` with struct, it sometimes returns null value error such as:
- `bigquery: NULL values cannot be read into structs`
- `bigquery: NULL cannot be assigned to field Xyz of type STRING`
I want to be able to handle such cases to skip the rows altogether and proceed to fetching next row.

**Describe the solution you'd like**
It would be great if we can get a custom error Type/Object which represents such unmarshalling error. This will help in comparing error types and handle accordingly.
For example if the error is of unmarshalling type I want to skip and proceed to next row 
whereas if it is another error (network/bigquery) then stop fetching rows

**Additional context**
Current code:
```go
for {
  b := models.HelloWorld{}
  err := it.Next(&b)
  rowNo++
  if err == iterator.Done {
	  break
  }
  if err != nil {
	  logger.Error(
		  ctx, "Error while unmarshalling iterator",
		  map[string]interface{}{"err": err.Error(), "tempRowNo": rowNo},
	  )
	  return nil, err
  }
  result = append(result, b)
}
	
```
How I want it to be:
```go
for {
  b := models.HelloWorld{}
  err := it.Next(&b)
  rowNo++
  if err == iterator.Done {
	  break
  }
  if err != nil {
	  logger.Error(
		  ctx, "Error while next iterator",
		  map[string]interface{}{"err": err.Error(), "tempRowNo": rowNo},
	  )
	  if error.Is(err, bigquery.UnmarshalError) {
                   continue
          }
          return nil, err
  }
  result = append(result, b)
}
```

**Comment by shollyman** [comment]
The issue here is that these operations may be page-based rather than row-based inside the iterator, so graceful recovery isn't straightforward

If you want to take full control of the unmarshaling process, you can implement the [`ValueLoader`](https://pkg.go.dev/cloud.google.com/go/bigquery#ValueLoader) interface on your destination type (`models.HelloWorld` in this example).

**Comment by akkivarma10** [comment]
ohh ok, so is it possible to expose the `structLoader.Load` method ?
so that it can be used by the custom `ValueLoader.Load` method and handle unmarshalling error as the error returned by `Load` method would always be related to unmarshalling.

**Comment by shollyman** [comment]
That's a fairly internal thing.  The library bears an open source license, so you're free to copy and adapt as you see fit.

It's also not clear what you're doing with the datastructure afterwards.  Would a fully dynamic approach be better, where you iterate using `[]bigquery.Value` as the type and simply use type assertions (and the iterator's schema) to process the row data?

**Comment by akkivarma10** [comment]
So the model defined (`models.HelloWorld` in example) is used at multiple places in a legacy code and cannot be changed, so cannot use `[]bigquery.Value` directly, will look into alternatives as well as the one you suggested.

Still I think there should be some way of letting the client know whether they can make a call to iterator's `next` again or not in case of any error, similar to how we have `iterator.Done`

**Comment by alvarowolfx** [comment]
We provided options to handle unmarshalling error and we are not going to alter iterator contract as this will cause breaking changes.
