### ISSUE TITLE
firestore: tracing error "no more items in iterator" on iterator.Done

### ISSUE THREAD

**Issue by klaus-ziegert** [googleapis/google-cloud-go#7711]
**Client**

firestore

**Go Environment**

go version go1.19.5 darwin/amd64

**Code**

After the `next()` function has finished executing and `iterator.Done` has been returned as an error, the span should not add this error using `trace.EndSpan(it.ctx, err)`.
https://github.com/googleapis/google-cloud-go/blob/7afc98a698a0857c33f14c94a72ae2510919537d/firestore/query.go#L913-L963

Instead, the expected behavior is to check if `iterator.Done` is the error returned, and only add an error to the span if it's a different error. The defer-func should look like this:
```
defer func() { 
if errors.Is(err, iterator.Done) {
    trace.EndSpan(it.ctx, nil) 
} else {
    trace.EndSpan(it.ctx, err)
}
}()
```

**Expected behavior**
After `next()` returns `iterator.Done`, no error should be set in the span.

**Actual behavior**
The error "UNKNOWN: no more items in iterator" is set in the span after next() returns iterator.Done.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/86786055/230752983-b76f3166-a550-4305-88d9-f93594a3afca.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/86786055/230753127-97819444-ba79-4962-b1dc-9aa105e5b76e.png">

**Comment by noahdietz** [comment]
Seemed simple enough so I opened a PR. Thanks for the code snippet @klaus-ziegert
