### ISSUE TITLE
dataflow: Setting autoscaling algorithm to none does not get reflected on the job.

### ISSUE THREAD

**Issue by Deep1998** [googleapis/google-cloud-go#7724]
**Client**

Dataflow @v0.8.0

**Environment**

MacOs

**Go Environment**
$go version
go version go1.19.4 darwin/amd64

$go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/deepchowdhury/Library/Caches/go-build"
GOENV="/Users/deepchowdhury/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/deepchowdhury/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/deepchowdhury/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/deepchowdhury/Desktop/harbourbridge/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/58/hc4cb7rs0q51vl7fgmqk27zc00t2n6/T/go-build2366493409=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"

	dataflow "cloud.google.com/go/dataflow/apiv1beta3"
	"cloud.google.com/go/dataflow/apiv1beta3/dataflowpb"
)

func main() {
	ctx := context.Background()
	c, err := dataflow.NewFlexTemplatesClient(ctx)
	if err != nil {
		fmt.Printf("could not create flex template client: %v", err)
	}
	defer c.Close()
	launchParameter := &dataflowpb.LaunchFlexTemplateParameter{
		JobName: "deeppoc",
		//Template: &dataflowpb.LaunchFlexTemplateParameter_ContainerSpecGcsPath{ContainerSpecGcsPath: "gs://dataflow-templates-southamerica-west1/2023-01-29-00_RC00/flex/Cloud_Datastream_to_Spanner"},
		Template: &dataflowpb.LaunchFlexTemplateParameter_ContainerSpecGcsPath{ContainerSpecGcsPath: "gs://deepchowdhury-gsql/images/datastream-to-spanner-image-spec.json"},
		Parameters: map[string]string{
			"inputFilePattern":         "gs://deep-tco/1tb",
			"streamName":               "teststream",
			"instanceId":               "deep-machmeter-test",
			"databaseId":               "finance-ledger",
			"sessionFilePath":          "gs://deep-tco/1tb/session.json",
			"deadLetterQueueDirectory": "3",
			"shadowTablePrefix":        "10",
		},
		Environment: &dataflowpb.FlexTemplateRuntimeEnvironment{
			MaxWorkers:            10,
			NumWorkers:            3,
			AutoscalingAlgorithm:  1, // 1 corresponds to AUTOSCALING_ALGORITHM_NONE
			EnableStreamingEngine: true,
			AdditionalExperiments: []string{"use_runner_v2"},
			MachineType:           "n2-standard-64",
		},
	}

	req := &dataflowpb.LaunchFlexTemplateRequest{
		ProjectId:       "span-cloud-testing",
		LaunchParameter: launchParameter,
		Location:        "us-central1",
	}
	fmt.Printf("%+v", req)
	_, err = c.LaunchFlexTemplate(ctx, req)
	if err != nil {
		fmt.Printf("flexTemplateRequest: %+v\n", req)
		fmt.Printf("unable to launch template: %v", err)
	}
}
```

**Expected behavior**

Set the autoscaling algorithm to none, and thats what gets printed when I print the request body.

**Actual behavior**

The job has autoscaling enabled.

**Screenshots**
<img width="1489" alt="Screenshot 2023-04-11 at 3 34 00 AM" src="https://user-images.githubusercontent.com/19630018/231007743-ef625b3d-515a-4007-b316-dc952f4a0f1e.png">

**Comment by noahdietz** [comment]
I would recommend attempting the same thing with `gcloud` (if it supports this flag) to help narrow down the issue.

If the request message is printed and indeed has the correct field values, I'd say that this is an API issue and would encourage you to [search for a similar issue](https://b.corp.google.com/savedsearches/559728) or [open your own](https://b.corp.google.com/issues/new?component=187168&template=1162867).

Thanks for taking the time to report the issue.
