### ISSUE TITLE
storage: add support for matchGlob 

### ISSUE THREAD

**Issue by goober** [googleapis/google-cloud-go#7727]
**Is your feature request related to a problem? Please describe.**
Support for the `matchGlob` parameter when [listing objects](https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters) in a bucket is not available from the SDK. 

**Describe the solution you'd like**
Add an attribute to the `storage.Query` struct to be able to provide a glob pattern to match.

**Describe alternatives you've considered**
The alternative is to use the JSON API directly, which works, but then you need to handle all the boilerplate with headers and authentication etc. by your self.

**Comment by tritone** [comment]
Thanks for the PR -- we had this in our backlog for this quarter anyway. I left some comments, we can work with you on the PR or finish it off ourselves.

**Comment by goober** [comment]
Fixed by https://github.com/googleapis/google-cloud-go/pull/8618
