### ISSUE TITLE
datastore: Receiving invalid argument error but filters match the error suggestion.

### ISSUE THREAD

**Issue by carpcarp** [googleapis/google-cloud-go#7739]
**Client**
Datastore

**Environment**
go1.20.2 darwin/arm64

**Code**
	query := datastore.NewQuery("Event").
		Filter("Status =", "BLOCK").
		Project("PortalID", "ExecutesAt").DistinctOn("PortalID").
		Filter("ExecutesAt <", time.Now().Add(1*time.Second)).
		Order("PortalID")

Error:
[] Failed to fetch events: rpc error: code = InvalidArgument desc = Inequality filter on ExecutesAt must also be a group by property when group by properties are set.

Existing index (I think it could be relevant so including it here):

indexes:
- kind: Event
  properties:
  - name: Status
  - name: ExecutesAt
  - name: PortalID

**Expected behavior**
I have "ExecutesAt" present in the projection group so I can't figure out why I receive this error.

Essentially I'm trying to return a list of PortalIDs that require a batch operation.

**Comment by bhshkh** [comment]
I'm seeing a different error when I try to run the query you have provided in the description:

```
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"cloud.google.com/go/datastore"
	"google.golang.org/api/iterator"
)

type Event struct {
	Status     string
	PortalID   string
	ExecutesAt time.Time
}

func main() {
	ctx := context.Background()

	// Set your Google Cloud Platform project ID.
	projectID := "my-project-id"

	client, err := datastore.NewClient(ctx, projectID)
	if err != nil {
		fmt.Printf("Failed to create client: %v\n", err)
	}
	defer client.Close()
	keys := []*datastore.Key{
		datastore.NameKey("Event", "ev1", nil),
		datastore.NameKey("Event", "ev2", nil),
		datastore.NameKey("Event", "ev3", nil),
	}

	events := []*Event{
		{Status: "BLOCK", PortalID: "id1", ExecutesAt: time.Now()},
		{Status: "BLOCK", PortalID: "id2", ExecutesAt: time.Now()},
		{Status: "BLOCK", PortalID: "id3", ExecutesAt: time.Now()},
	}

	_, err = client.PutMulti(ctx, keys, events)
	if err != nil {
		fmt.Printf("Failed to save event: %v\n", err)
	}
	query := datastore.NewQuery("Event").
		Filter("Status =", "BLOCK").
		Project("PortalID", "ExecutesAt").DistinctOn("PortalID").
		Filter("ExecutesAt <", time.Now().Add(1*time.Second)).
		Order("PortalID")

	it := client.Run(ctx, query)
	for {
		var event Event
		if _, err := it.Next(&event); err == iterator.Done {
			break
		} else if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("PortalID: %v, ExecutesAt: %v", event.PortalID, event.ExecutesAt)
	}
}

```

Error:
```
2023/07/30 10:00:21 rpc error: code = InvalidArgument desc = inequality filter property and first sort order must be the same: ExecutesAt and PortalID
exit status 1
```


@carpcarp , are you still seeing this issue? If yes, can you please share a sample code?
