### ISSUE TITLE
spanner: Error wraped into Internal

### ISSUE THREAD

**Issue by osterante** [googleapis/google-cloud-go#7740]
**Client**

Spanner v1.45.0

**Environment**

The local environment on M1 MacBookPro

**Go Environment**
$ go version
go version go1.20 darwin/arm64

<details>
<summary>$ go env</summary>

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/UserName/Library/Caches/go-build"
GOENV="/Users/UserName/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/UserName/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/UserName/go"
GOPROXY="https://proxy.golang.org/,direct"
GOROOT="/Users/UserName/.anyenv/envs/goenv/versions/1.20.0"
GOSUMDB="[sum.golang.org](http://sum.golang.org/)"
GOTMPDIR=""
GOTOOLDIR="/Users/UserName/.anyenv/envs/goenv/versions/1.20.0/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/UserName/Projects/Project/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x3/0yyktc4d5_11gvj8gsjxsck5mc3vtb/T/go-build887811120=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

**Code**

e.g.
```go
func main() {
        ctx, cancel := context.WithCancel(context.Background())
        client, _ := spanner.NewClient(ctx, "path to db")

        _, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, tx *spanner.ReadWriteTransaction) error {
                iter := tx.Query(ctx, spanner.NewStatement("SELECT 1"))
                if _, err := iter.Next(); err != nil {
                        return err
                }
                return nil
        })
        if err != nil {
                panic(err)
        }

        cancel() // cancel here

        _, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, tx *spanner.ReadWriteTransaction) error {
                iter := tx.Query(ctx, spanner.NewStatement("SELECT 1"))
                if _, err := iter.Next(); err != nil {
                        return err
                }
                return nil
        })
        if err != nil {
                if status.Code(err) == codes.Canceled {
                        fmt.Println("expected")
                } else {
                        fmt.Printf("Unexpected err: %v", err)
                }
        }
}
```

**Expected behavior**

print `expected`

**Actual behavior**

`Unexpected err: spanner: code = "Internal", desc = "error while BeginTransaction during retrying a ReadWrite transaction: spanner: code = \"Canceled\", desc = \"context canceled\""`

**Additional context**

It happens after https://github.com/googleapis/google-cloud-go/pull/7149 is merged.

**Comment by noahdietz** [comment]
The offending line is here: https://github.com/googleapis/google-cloud-go/blob/adcbb74d786d8239113fc17e228638fa0eb2d664/spanner/client.go#L536

It likely needs to check `if errors.Is(err, context.Canceled)` then use `codes.Canceled` instead of `Internal`.

I'm not familiar with the `spanner.Error` and how it works, but hopefully it leverages Go error wrapping to preserve the original error so users can use the same test above. That test is the idiomatic way of checking for a canceled RPC, especially for cloud.google.com/go clients since the middleware will return that native error in such situations.

**Comment by osterante** [comment]
I'm not sure, but it seems that the error was returned directly before https://github.com/googleapis/google-cloud-go/pull/7149 is merged.
https://github.com/googleapis/google-cloud-go/pull/7149/files#diff-a7eef968d026e320839e33486c1ce4e449d69d9f6c86052edeae4528b60b5579L528-L530

**Comment by rahul2393** [comment]
Thanks @osterante already created the PR, will be fixed in next release
