### ISSUE TITLE
pubsub: turn PublishResult into an interface, or make it mockable

### ISSUE THREAD

**Issue by dmathieu** [googleapis/google-cloud-go#7801]
**Is your feature request related to a problem? Please describe.**

The exposed [PublishResult](https://pkg.go.dev/cloud.google.com/go/pubsub#PublishResult) is available publicly, but can't be manipulated manually, as everything behind it is within an internal package.

While not being able to publish results ourselves makes sense at runtime, it makes writing unit tests quite harder, as we can't mock call our handlers with specific results.

**Describe the solution you'd like**

I would like to be able to create `PublishResult` structs, and mark them as ready, give them an error and a custom server name.

**Describe alternatives you've considered**

Not having this is kind of preventing writing any unit tests for things that rely on PublishResult, so the only alternative is not having tests.

**Additional context**

N/A at this stage.

**Comment by hongalex** [comment]
We're currently not interested in doing this. There's some history to why PublishResult is private, and if you're interested, the discussion is in #3200 

I would suggest using the fake with the [`AddPublishResponse`](https://github.com/googleapis/google-cloud-go/blob/a75c8b64ac954254bb8391e1828a2b6c55b0f23d/pubsub/pstest/fake.go#L190) method as an alternative.
