### ISSUE TITLE
run: enable cpu boost on service creation

### ISSUE THREAD

**Issue by martinal** [googleapis/google-cloud-go#7810]
**Is your feature request related to a problem? Please describe.**
When using apiv2 to create a cloud run service there is no field for enabling cpu boost.

**Describe the solution you'd like**
A `CpuBoost bool` field somewhere in the runpb.ServiceCreateRequest or substructs.

**Describe alternatives you've considered**
We previously did this from python by setting annotations, but the apiv2 docs for golang state that such annotations will be rejected.

I guess another alternative I can use short term is to run gcloud cli to enable it after service creation but I'd like to keep it all in Go.

**Additional context**

**Comment by codyoss** [comment]
Thanks for reaching out. It appears the public protos have not been upgraded for a while. I will put in a request to get this done. I would expect the changes to come out sometime next week. In the meantime if you can't wait and want to write some code in Go you can use our older style libraries as the field seems to be published here: https://pkg.go.dev/google.golang.org/api/run/v2

But again this is the library I would recommend using in general and a patch should be out in not too long. Thanks for the report.

**Comment by martinal** [comment]
I've created a cloud run service with this api and it turns out Startup CPU Boost is Enabled by default, maybe the option was removed?

**Comment by martinal** [comment]
That could also be because I had set
```
				Annotations: map[string]string{
					"run.googleapis.com/cpu-throttling":    "true",
					"run.googleapis.com/startup-cpu-boost": "true",
				},
```
in which case I think the documentation is wrong, stating these would be ignored, so great if you can still review what's the proper way.

**Comment by martinal** [comment]
Any news on this @codyoss ?

**Comment by codyoss** [comment]
Oops forgot to close this issue. It was added in the most recent release: https://pkg.go.dev/cloud.google.com/go/run@v1.0.1/apiv2/runpb#ResourceRequirements
