### ISSUE TITLE
cloudtasks: task size limit in Go client differs from the Cloud Task Quota documentation 

### ISSUE THREAD

**Issue by fratle** [googleapis/google-cloud-go#7821]
The Go tasks client states that the size limit of a task is 100KB, but the Tasks quota states 1MB.

Is this an limitation in the Go client or is the documentation wrong?

**Client**

Cloud Tasks

**Code**

https://github.com/googleapis/google-cloud-go/blob/c2bf628da9b4f30df75608ffa77c2fb8d6a6cf8d/cloudtasks/apiv2/cloud_tasks_client.go#L511

**Expected behavior**

1MB limit on cloud tasks as stated here: https://cloud.google.com/tasks/docs/quotas

**Actual behavior**

The code comment states that 100KB is the Task size limit.

**Comment by quartzmo** [comment]
@fratle The client documentation is provided by the API product owner. There is an open issue on the Cloud Tasks issue tracker that may be relevant. If not, you may open a new issue there.

https://b.corp.google.com/issues/151434306
