### ISSUE TITLE
vision: incorrect version in `v2` snippets metadata

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-go#7826]
As a result of snippetgen moving to gapic-generator-go, the snippets metadata file ([snippet_metadata.google.devtools.clouddebugger.v2.json](https://github.com/googleapis/google-cloud-go/blob/main/internal/generated/snippets/vision/v2/apiv1p1beta1/snippet_metadata.google.cloud.vision.v1p1beta1.json)) for `vision/v2/apiv1p1beta1` was incorrectly updated in #7814. It appears that the post-processor used the latest `1.x.x` version of the module:

```json
    "version": "1.2.0",
```

should be:

```json
    "version": "2.7.0",
```

**Comment by rkarmaka98** [comment]
Fixes: #7826

**Comment by codyoss** [comment]
I believe this should be better now that we have moved this to in place
