### ISSUE TITLE
Unexpected behavior of pagination using `PageInfo().Token` in the Go client

### ISSUE THREAD

**Issue by wilfreddesert** [googleapis/google-cloud-go#7902]
```
rawQuery := "SELECT num FROM UNNEST(GENERATE_ARRAY(1, 25)) num;"
query := bqClient.Query(rawQuery)
it, err := query.Read(ctx)
if err != nil {
    panic(err) // for brevity
}

for {
    var row myObject

    it.PageInfo().Token = token
    if err := it.Next(&row); err != nil {
        if errors.Is(err, iterator.Done) {
            break
    }
        return nil, "", err
    }

    nextToken = it.PageInfo().Token

    out = append(out, row)
    token = nextToken
    }
```

I am experiencing an issue with how Token-based pagination works. Most likely, it's because of my misunderstanding so please correct me. 

My idea was to use a combination of `(MaxSize, Token)` to implement cursor-based pagination so that I can get rows from a BQ table in batches. 

My expectation is that `token` should be updated every `MaxSize` rows once a new page has started. What happens, however, is that the value of `token` doesn't change at all regardless of `MaxSize` and I just iterate over all rows in the same way as without any token.  

That said, inspecting the `PageInfo` object inside of `iterator` confirms that there is a field called `rows` and its capacity is always the same as what I specify for `MaxSize`. How do I use that to process rows in batches? 

Thanks!

**Comment by codyoss** [comment]
You should not need to manipulate tokens at all. That is transparently taken care of for you with this convention. Here is an example from our samples repo -- hope that helps. https://github.com/GoogleCloudPlatform/golang-samples/blob/8ca425453938998d5fca511abae33aa2103e5505/bigquery/snippets/querying/bigquery_query.go#L48-L58

**Comment by wilfreddesert** [comment]
@codyoss , I don't understand. What do you mean "I shouldn't need to". You are reading 100 rows in your example because of the `LIMIT` clause. 

In my case, I cannot rely on LIMIT/OFFSET pagination because I don't have a reliable column to order by. This is why I decided to benefit from cursor-based pagination. If I understand correctly, this `PageInfo()` is exactly for that, right?

**Comment by wilfreddesert** [comment]
The table I want to query might have millions of rows so saving them all in one slice might not be feasible so I want to do that in batches of, say, 100K and then export to my own storage.

**Comment by wilfreddesert** [comment]
Let's say I have a method `getBatch`. 

Correct me if my understanding is incorrect. I can start with an empty string as `token` so it will start from the very beginning. Inside the method, I can gradually populate a slice of capacity `PageInfo().MaxSize()` and start processing this slice/batch. Before returning, I can also return the `PageInfo().Token` so that it can be used when querying for the next batch. 

For the second batch, I will first set `it.PageInfo().Token = tokenFromPrevIteration` and proceed this way until I get an empty string again which means that this is the end of data. 

Does that make sense to you?

**Comment by codyoss** [comment]
That sounds correct

**Comment by wilfreddesert** [comment]
Thank you! It would be cool to have that documented more explicitly but it's cool that such a possibility exists at all ;)
