### ISSUE TITLE
logging: panic: send on closed channel

### ISSUE THREAD

**Issue by ukai** [googleapis/google-cloud-go#7944]
**Client**

e.g.  Cloud Logging

**Environment**

e.g.  Google Compute Engine: n2-highmem-8

**Go Environment**

$ go version 
go version go1.20.3 linux/amd64

$ go env

**Code**

https://chromium.googlesource.com/infra/infra/+/refs/heads/main/go/src/infra/build/siso/o11y/clog/clog.go

**Expected behavior**

no panic

**Actual behavior**

```
panic: send on closed channel

goroutine 1350295 [running]:
cloud.google.com/go/logging.(*Client).error(0xc0006a9180, {0xff4920?, 0xc0035ca120})
	cloud.google.com/go/logging@v1.6.1/logging.go:221 +0x47
cloud.google.com/go/logging.(*Logger).writeLogEntries(0xc000131c80, {0xc0989fe1c0, 0x4, 0x4})
	cloud.google.com/go/logging@v1.6.1/logging.go:710 +0x186
cloud.google.com/go/logging.(*Client).Logger.func2({0xcf7320?, 0xc01fa52288?})
	cloud.google.com/go/logging@v1.6.1/logging.go:279 +0x45
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0007640b0, 0xc0006e0fb8?)
	google.golang.org/api@v0.108.0/support/bundler/bundler.go:324 +0x4a
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle
	google.golang.org/api@v0.108.0/support/bundler/bundler.go:179 +0x14d
```
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8781065344454878161/+/u/Build_all_without_remote_cache/stdout

Probabbly Log is called in background goroutines after main goroutine called Close?
Protecting each Log call by mutex would not be good for performance.

Is there any way to fix this? Ignore new log entries after Close in cloud logging package?
or just use Flush and not call Close for these use case?

**Comment by codyoss** [comment]
You are correct, I suspect this is happening because you are trying to log further after closing the client -- which is an invalid state for the client. I believe the solution here is to manage your background goroutines and only call close once they are finished processing. For all of our clients, not just logging, it is expected that no further action is taken with the client after they are closed.

**Comment by noahdietz** [comment]
@ukai have you had a chance to investigate your application code?

Silently ignoring calls to `Log` after the client has been closed is probably not a good user experience. Debugging "why isn't my app logging?" because of a `Close` synchronization issue would be a nasty one.

**Comment by ukai** [comment]
hmm, I just fixed by not calling `Close`.
