### ISSUE TITLE
BigQuery: uint64 not supported - but really it is a NUMERIC

### ISSUE THREAD

**Issue by RobHumphris** [googleapis/google-cloud-go#7950]
**Client**

BigQuery

**Environment**

All,

**Go Environment**

go version go1.20.3 linux/amd64

**Code**

Discovered using Protobuf generated schemas, we use a perfectly valid `uint64`, which I then use `[(gen_bq_schema.bigquery)={type_override: 'NUMERIC'}]` to override the schema generation. As the [data type conversions](https://cloud.google.com/bigquery/docs/write-api#data_type_conversions) suggests,

But when I try to infer the schema from the protobuffer the `uint64` error is raised.

I created a function in the same style as `isSupportedUintType`:
```go
// isUint64Type reports whether t is a uint64 type, this exceptional
// type can be represented by the BigQuery NUMERIC type
func isUint64Type(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Uint64:
		return true
	default:
		return false
	}
}
```
Calling the function between lines [462 & 436 of schema.go](https://github.com/googleapis/google-cloud-go/blob/main/bigquery/schema.go#L463) :
```go
if isUint64Type(rt) {
	return &FieldSchema{Required: !nullable, Type: NumericFieldType}, nil
}
```
Yielded a successful result.
Could this be used? My project is rather dependent on it as I have a few thousand sensors reporting in that use protobuffers for their measurements.

**Comment by RobHumphris** [comment]
Sure thing. We have a large number of protobufs that define the communications between our IoT assets and the cloud.
I generate the structures with the Go plugin for `protoc` and as of this tech spike I create BigQuery schemas (using protoc-gen-bq-schema) to define the BigQuery table.
Now I want to do a streaming insert to the table so use `inferSchema` via the function:
```go
func (c *BigQueryClient[T]) StreamingWrite(ctx context.Context, o any, ts ...int64) error {
	inserter := c.table(ts...).Inserter()
	err := inserter.Put(ctx, o)
	if err != nil {
		return fmt.Errorf("inserter.Put: %w", err)
	}
	return nil
}
```
The whole idea is that we use generics to avoid having to write and maintain all the DAL mapping.

**Comment by shollyman** [comment]
Thanks for the details.

I think you probably want to use the new write API, rather than old streaming insert method that gets called in that snippet.  With the newer API, you just need to serialize your messages to bytes and send them.  Take a look at https://pkg.go.dev/cloud.google.com/go/bigquery/storage/managedwriter, which is the API corresponding to the [data type mapping](https://cloud.google.com/bigquery/docs/write-api#data_type_conversions) you referenced in the initial report.

**Comment by RobHumphris** [comment]
Thanks I will look at that, but before I disappeared down that rabbit hole with the fear that I would run into the self-same issue I wanted to use my existing code base.
