### ISSUE TITLE
bigquery/managedwriter: EOF when append

### ISSUE THREAD

**Issue by stgleb** [googleapis/google-cloud-go#7967]
I have a long running process, that initially creates managedWriter and then write data received in a loop:

```
managedStream, err := client.NewManagedStream(...)

for {
	res, err := appender.AppendRows(ctx, [][]byte{data})
	if err != nil {
		...
	}
	_, err = res.GetResult(ctx)
	if err != nil {
		...
	}
}
```
But append rows produces EOF

`"message":"append error: append rows EOF"`

What can be reason for that and how it can be fixed? Create managed writer per each request?

**Comment by shollyman** [comment]
You're getting the EOF on the AppendRows, or returned from the GetResult?

If it's the former, I'd expect internal retries to handle this unless you're closing the writer or there's more serious transport issues.

If it's the latter, this is possible and it's just a matter of retrying the write.  The underlying writer uses a long-lived connection, but that connection can go away and be reopened.  You can either control retrying in your code, or construct the ManagedStream with the `EnableWriteRetries` WriterOption to have it attempt this automatically on your behalf, in which case it will attempt to re-enqueue writes as appropriate.

For more details, see the package docs about [error handling and automatic retries](https://pkg.go.dev/cloud.google.com/go/bigquery/storage/managedwriter#hdr-Error_Handling_and_Automatic_Retries).

**Comment by stgleb** [comment]
it returns EOF when AppendRows, thank you, I'll check this out

**Comment by postmastery** [comment]
Retries are default disabled. Without retries I noticed incidental EOF errors returned from AppendRows. 
You can try setting option `managedwriter.EnableWriteRetries(true)` on a managed stream.

**Comment by shollyman** [comment]
I'm going to go ahead and close this out.  If there's still more to revisit here, please comment/reopen as needed.
