### ISSUE TITLE
google-cloud-go: unable to patch empty list value

### ISSUE THREAD

**Issue by f-feary** [googleapis/google-cloud-go#8059]
**Client**

Affects all clients with protobuf generated types

**Environment**

All enviroments

**Go Environment**

All Go versions

**Code**

e.g.
```go
patch, err := sdk.ServiceAttachment.Patch(gctx, &computepb.PatchServiceAttachmentRequest{
				Project:                   sdk.ProjectID,
				Region:                    cluster.Config.Region,
				RequestId:                 &requestId,
				ServiceAttachment:         *svcAtchmt.Name,
				ServiceAttachmentResource: &computepb.ServiceAttachment{
					ConsumerAcceptLists: []*computepb.ServiceAttachmentConsumerProjectLimit{},
				},
			})
```

**Expected behavior**

The ConsumerAcceptLists resource is replaced with an empty list, as when you pass an empty string to the CLI equivalent.

**Actual behavior**

Because of the protobuf-generated JSON omitempty tag, the ConsumerAcceptLists does not get serialized in the request, and nothing changes.

In another example of this issue we were able to workaround this by using Update to update the entire resource instead (a non-ACID compliant request but a working solution). In this situation there is no Update method.

**Comment by quartzmo** [comment]
Hi @f-feary,

Thanks for opening this issue. I think you may have discovered a possible deficiency in the Compute API in the sense that the [serviceAttachments.patch]() RPC does not accept a field mask parameter in which you may specify a field that you wish to send as empty (or nil). If you are interested in requesting this feature we can discuss how to do so. For an immediate solution, would you be able to use the older HTTP-based Go client to make this call?

https://github.com/googleapis/google-api-go-client

https://pkg.go.dev/google.golang.org/api

https://pkg.go.dev/google.golang.org/api@v0.125.0/compute/v1#ServiceAttachmentsPatchCall


Please see docs on [ForceSendFields](https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields), summarized here:

> You can override the `omitempty` feature by adding the field name to the `ForceSendFields` slice. See `ForceSendFields` docs on any struct for more details. ([ServiceAttachment](https://pkg.go.dev/google.golang.org/api@v0.125.0/compute/v1#ServiceAttachment) for example):

```go
// ForceSendFields is a list of field names (e.g. "ConnectedEndpoints") to
// unconditionally include in API requests. By default, fields with
// empty or default values are omitted from API requests. However, any
// non-pointer, non-interface field appearing in ForceSendFields will be
// sent to the server regardless of whether the field is empty or not.
// This may be used to include empty fields in Patch requests.
ForceSendFields [][string](https://pkg.go.dev/builtin#string) `json:"-"`
```

Additional note: `omitempty` is broadly used for all JSON-mapped structs in the client libraries in this repo.

**Comment by quartzmo** [comment]
@f-feary If you still want to pursue this as a feature request, please look for similar requests in the Compute Engine issue tracker (I didn't find any): [tracker.google.com/savedsearches/559746](https://issuetracker.google.com/savedsearches/559755). All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers. Thank you.
