### ISSUE TITLE
profiler: Debug log output stream is not configurable

### ISSUE THREAD

**Issue by Bo0mer** [googleapis/google-cloud-go#8089]
Currently when `DebugLogging` is set to `true` the profiler package always logs to stderr. 

```go
		err = profiler.Start(profiler.Config{
			ProjectID:      cfg.GoogleProjectID,
			Service:        "my-service",
			ServiceVersion: buildInfo.Main.Version,
			DebugLogging:   true,
		})
```

Produced error messages:

![Screenshot 2023-06-07 at 13 04 53](https://github.com/googleapis/google-cloud-go/assets/3696685/8ac68c76-bf5d-45bc-a0f7-b9e7e6c8d453)

Do you think it makes sense to expose the internally used logger by any means? This way one will able to configure a different output stream for the debug log messages.

**Comment by noahdietz** [comment]
@Bo0mer let's try to be a little more specific with the desired requirements here. 

My guess is that you'd like the logger to send debug logs to a different file descriptor/stream/buffer that _isn't_ `os.Stderr`. That sounds reasonable! I don't think we need to expose the entire logger to achieve this, nor do I think we should just yet.

If the only requirement is to be able to direct logging to a different output, then we can just add a field `LogOutput io.Writer` that defaults to `os.Stderr` to the `profiler.Config`.

**Comment by Bo0mer** [comment]
@noahdietz sorry for not being specific enough. Your suggestion totally makes sense and in fact that's what I'm trying to achieve. I want to get the debug logs on stdout, so they're not treated as error severity by the platform I'm using to collect and explore the log messages produced by the application.

Having the `LogOutput` field in the `profiler.Config` would be totally sufficient.

Thanks for your fast response.

**Comment by noahdietz** [comment]
Sure thing, easy enough. I've got a PR open.

**Comment by noahdietz** [comment]
I'm sorry this shouldn't have been closed until released. I don't typically own this module's release, but I am cutting this one #7555 to get this and another fix out.
