### ISSUE TITLE
compute: How can I get all quotas by using cloud.google.com/go/compute/apiv1?

### ISSUE THREAD

**Issue by Mr-Rain** [googleapis/google-cloud-go#8153]
By searching 'All Quotas' in GCP portal, I can see there are a lot of quotas for my project. And I want to list all quotas with service Compute Engine API. However, when I using cloud.google.com/go/compute/apiv1, I found not all quotas are listed, eg: Subnetwork ranges per VPC Network

```
import (
    "context"
    compute "cloud.google.com/go/compute/apiv1"
)

ctx := context.Background()
computeCredential, err := google.CredentialsFromJSON(ctx, []byte(cred[vault.GcpServiceAccount]), constant.GCPComputeScope)
if err != nil {
	// TODO: Handle error.
}
projectClient, err := compute.NewProjectsRESTClient(ctx, option.WithCredentials(computeCredential))
if err != nil {
	// TODO: Handle error.
}
project := "MyProject"
req := &computepb.GetProjectRequest{
	Project: project
}
resp, err := c.Get(ctx, req)
if err != nil {
	// TODO: Handle error.
}
for _, quota := range resp.Quotas{
    // TODO: Use prometheus handle quota
}
```

**Comment by codyoss** [comment]
This seems like a product question and not directly related to the libraries. I do see a subnetworks quota if that is what you mean? I think the best place to reach out for help on this product is the support page for this product: https://cloud.google.com/compute/docs/getting-support. Hope that helps getting you moving in the correct direction.
