### ISSUE TITLE
go-cloud-debug-agent: logpoints keep emitting after being removed

### ISSUE THREAD

**Issue by arjenvanderende** [googleapis/google-cloud-go#816]
After adding a logpoint and removing it again via Stackdriver Debug, the logpoint keeps emitting to Stackdriver Logging. 

Also, each logpoint emits multiple times, even though a single logpoint was created.

<img width="641" alt="screen shot 2017-11-30 at 09 41 01" src="https://user-images.githubusercontent.com/357115/33421528-a422ce94-d5b2-11e7-9d41-341cd8d37703.png">

Because the `go-cloud-debug` binary is not versioned, I've tried two separate versions:
* the download from the [setup guide](https://cloud.google.com/debugger/docs/setup/compute-engine-go#download_the_agent)
* built from source from the [current master](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/28b507a1143b9134490384bc95088187dde1b96a)

Both agents exhibit the same issue.

**Comment by arjenvanderende** [comment]
I just discovered that the logpoint I configured for this issue are still emitting today. So the logpoints don't adhere to the 24 hour limit as [mentioned here](https://cloud.google.com/debugger/docs/logpoints#logpoints). This might be expected because deleting the logpoint also doesn't stop emission, but it was a surprise to me :-)

**Comment by zombiezen** [comment]
@shantuo, could you take a look?

**Comment by jadekler** [comment]
Friendly ping - @shantuo or @zombiezen do either of y'all have context on this?

**Comment by codyoss** [comment]
Closing as [cmd/go-cloud-debug-agent is deprecated](https://github.com/googleapis/google-cloud-go/releases/tag/v0.69.0).
