### ISSUE TITLE
pubsub: does client publisher sends multiple batches in parallel?

### ISSUE THREAD

**Issue by nagydaoudt** [googleapis/google-cloud-go#8161]
Hey,

I have a question regarding the behavior of message sending in a specific topic with the following settings:
```
topicObject.PublishSettings.CountThreshold = 100
topicObject.PublishSettings.DelayThreshold = 100 * time.Millisecond
```

Let's say I have already received 100 messages and they are being sent. However, during the sending process, another batch of 100 messages becomes ready to be sent.

My question is: Will both batches be sent sequentially or in parallel? I'm looking to understand the concurrency behavior in this scenario.

Thank you

**Comment by hongalex** [comment]
They will be sent in parallel by default. How many publish RPCs that are in flight can be configured via `PublishSettings.FlowControlSettings` (https://pkg.go.dev/cloud.google.com/go/pubsub#PublishSettings). This might be useful if you are publishing too fast and run into network issues.
