### ISSUE TITLE
go-cloud-debug-agent: performance degrades significantly after adding logpoint

### ISSUE THREAD

**Issue by arjenvanderende** [googleapis/google-cloud-go#817]
We have a small Go application that we'd like to be able to debug with `go-cloud-debug-agent` on production. There is a moderate, but reasonable overhead when embedding the agent in our application: we see an increase in request latency of about 10% to 15%. 

When creating a logpoint via Stackdriver Debug the request latency degrades significantly: 
* the 80th percentile increases from ~75ms to ~250ms
* the 95th percentile increases from ~100ms to ~500ms
* the 99th percentile increases from ~140ms to ~800ms

<img width="624" alt="screen shot 2017-11-30 at 10 02 43" src="https://user-images.githubusercontent.com/357115/33422343-addcd7f6-d5b5-11e7-92e1-a947da975fc3.png">

Performance never recovers. Even after removing the logpoint the performance remains degrades, although I suspect this might be caused by issue: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/816

I'm not sure what the stance is on having go-cloud-debug-agent running by-default on production, but this performance issue makes it unsuitable for us to even consider enabling it there.

**Comment by zombiezen** [comment]
Thanks for the feedback.  The Go Cloud Debugger support is in alpha, and isn't terribly optimized for speed right now.  We're aware of this issue and have plans to address this soon, but I can't give a firm date on when this will land.

**Comment by jadekler** [comment]
Closing this, since many changes have been made in the last year or so. If this is still an issue, please let me know and I can re-open.

**Comment by jadekler** [comment]
Whoops, found out this is still actively being investigated. Re-opening.

**Comment by codyoss** [comment]
Closing as I think a lot has changed since 2017. Please feel free to reopen if this is still an issue though.
