### ISSUE TITLE
Bigtable emulator source directory should have a README

### ISSUE THREAD

**Issue by mbrukman** [googleapis/google-cloud-go#821]
It would be nice if this directory: https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/bigtable/cmd/emulator included a README that told a user:

* how to build/install the emulator via Go, e.g., `go get [?]`
* how to run this emulator binary, i.e., sample flags
* how to connect to it, i.e., what env var to set and how, e.g., `BIGTABLE_EMULATOR_HOST=....`

Given this, it should make it possible to have a very light-weight alternative to having to install `gcloud` and updating it to install emulators (as per [this page](https://cloud.google.com/bigtable/docs/emulator)) if someone wants to use the Bigtable emulator in a CI scenario.

**Comment by jadekler** [comment]
Please see https://godoc.org/cloud.google.com/go/bigtable/cmd/cbt
