### ISSUE TITLE
storage: Incorrect page token value in the URL

### ISSUE THREAD

**Issue by karanpopat** [googleapis/google-cloud-go#8218]
**Client**

Storage

**Code**

e.g.
```go
package main

func main() {
	bucketName := "bucket-name"

	ctx := context.Background()

	// To get config arguments from plugin config file
	opts := setSessionConfig(ctx, d.Connection)

	// so it was not in cache - create service
	svc, err := storage.NewService(ctx, opts...)
	if err != nil {
		return nil, err
	}

	resp := svc.Objects.List(bucketName).Projection("full").MaxResults(100)
	if err := resp.Pages(ctx, func(page *storage.Objects) error {
		for _, object := range page.Items {

			plugin.Logger(ctx).Error("listStorageObjects", page.NextPageToken, page.Header)

			if d.RowsRemaining(ctx) == 0 {
				page.NextPageToken = ""
				break
			}
		}
		return nil
	}); err != nil {
		plugin.Logger(ctx).Trace("gcp_storage_object.listStorageObjects", "api_error", err)
		return nil, err
	}

	return nil, err
}
```

While working with pagination using the page token, I noticed that the generated URL for subsequent API requests contains "MISSING" appended to the page token instead of the actual page token value

```url
Error: Get "https://storage.googleapis.com/storage/v1/b/australia-southeast1-gdp-de-c6d33507-bucket/o?alt=json&maxResults=1000&pageToken=Ckhsb2dzL2RhZ19pZD1haXJmbG93X21vbml0b3JpbmcvcnVuX2lkPW1hbnVhbF9fMjAyMy0wMi0yMlQxOTo1NDoyMiswMDowMC8%!!(MISSING)D(MISSING)&prettyPrint=false&projection=full": context canceled
	Get "https://storage.googleapis.com/storage/v1/b/australia-southeast1-gdp-de-c6d33507-bucket/o?alt=json&maxResults=1000&pageToken=CmJsb2dzL2RhZ19pZD1haXJmbG93X21vbml0b3JpbmcvcnVuX2lkPW1hbnVhbF9fMjAyMy0wMi0xMlQyMjowOTozNiswMDowMC90YXNrX2lkPWVjaG8vYXR0ZW1wdD0xLmxvZw%!!(MISSING)D(MISSING)%!!(MISSING)D(MISSING)&prettyPrint=false&projection=full": context canceled
```

**Expected behavior**

The URL for subsequent API requests should contain the actual page token value and not have "MISSING" appended

**Actual behavior**

While working with pagination using the page token, I noticed that the generated URL for subsequent API requests contains "MISSING" appended to the page token instead of the actual page token value

Error: Get "https://storage.googleapis.com/storage/v1/b/australia-southeast1-gdp-de-c6d33507-bucket/o?alt=json&maxResults=1000&pageToken=Ckhsb2dzL2RhZ19pZD1haXJmbG93X21vbml0b3JpbmcvcnVuX2lkPW1hbnVhbF9fMjAyMy0wMi0yMlQxOTo1NDoyMiswMDowMC8%!!(**MISSING)D(MISSING**)&prettyPrint=false&projection=full": context canceled
	Get "https://storage.googleapis.com/storage/v1/b/australia-southeast1-gdp-de-c6d33507-bucket/o?alt=json&maxResults=1000&pageToken=CmJsb2dzL2RhZ19pZD1haXJmbG93X21vbml0b3JpbmcvcnVuX2lkPW1hbnVhbF9fMjAyMy0wMi0xMlQyMjowOTozNiswMDowMC90YXNrX2lkPWVjaG8vYXR0ZW1wdD0xLmxvZw%!!(**MISSING)D(MISSING)%!!(MISSING)D(MISSING)**&prettyPrint=false&projection=full": context canceled

**Comment by tritone** [comment]
Hi @karanpopat . The code looks to be from the generated library here: https://pkg.go.dev/google.golang.org/api@v0.130.0/storage/v1. If that's correct, this is the wrong github repo for this issue; it should be moved to [googleapis/google-api-go-client](https://github.com/googleapis/google-api-go-client).

In any case, we recommend you use this library instead: https://pkg.go.dev/cloud.google.com/go/storage. See https://pkg.go.dev/cloud.google.com/go/storage#BucketHandle.Objects which will handle the page token logic for you.

If you want to use the package you are currently using for whatever reason, file an issue in the other repo and I can investigate there.
