### ISSUE TITLE
storage: v1.31.0 fails tests in conjunction with cloud.google.com/go/httpreplay where v1.30.1 did not

### ISSUE THREAD

**Issue by gannett-ggreer** [googleapis/google-cloud-go#8233]
**Client**

`go test`

**Environment**

macOS Monterey 12.6.3

**Go Environment**

$ go version

go version go1.20.5 darwin/amd64

$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ggreer/Library/Caches/go-build"
GOENV="/Users/ggreer/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ggreer/p/go/pkg/mod"
GONOPROXY="github.com/GannettDigital"
GONOSUMDB="github.com/GannettDigital"
GOOS="darwin"
GOPATH="/Users/ggreer/p/go"
GOPRIVATE="github.com/GannettDigital"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.20.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.20.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/ggreer/p/go/src/github.com/GannettDigital/content-api/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p6/7bbg8bnn0ys4581_ssb8zkz00000gp/T/go-build377390741=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

https://gist.github.com/gannett-ggreer/9e1a2a19380ac3e1da526a9cad79f4e2

**Expected behavior**

Recorded traffic can be replayed by cloud.google.com/go/httpreplay

**Actual behavior**

Fails with "ERROR: martian: failed to round trip: no matching request".

**Screenshots**

There is sample output in the linked gist.

**Additional context**

v1.30.1 is fine, v1.31.0 is not.

**Comment by tritone** [comment]
I found that a header that should be ignored by httpreplay currently isn't. Made a PR to fix which should go out in the next release of cloud.google.com/go (storage version should not matter). In the mean time you can also do a workaround in your example by adding `rep.IgnoreHeader("X-Goog-Gcs-Idempotency-Token")`

**Comment by codyoss** [comment]
Released: https://github.com/googleapis/google-cloud-go/releases/tag/v0.110.6
