### ISSUE TITLE
pubsub: REST API fetching inconsistent number of messages

### ISSUE THREAD

**Issue by phaneendra11** [googleapis/google-cloud-go#8235]
Hi,

We are using pubsub REST API to pull messages from the Subscription. Our application works as scheduled job where in every schedule (every 5 mins), we will be fetching the messages from pubsub to process. Initially when we make a single call to pubsub using REST API, we are receiving only a handful of messages (e.g. 10) even though the backlog is huge (e.g. 10K messages).

After going through the documentation, we are making three consecutive calls to the Rest API, and able to see that more messages (almost upto the maxMessages configured in request) are getting received in the second and third API calls.

However, this is looking flaky, as fetching messages from the pubsub quickly is essential to the smooth working of our component. Since the documentation is vague when it says we need to make simultaneous requests, whats the recommended way to use a Pull REST API? 
How many API calls are required in order for the API to send the "MaxMessages" in the response? 
How many times should we invoke the API, when we get zero messages in the response, to be sure that there are no more messages in the backlog?

(Unfortunately our component is not designed to work with Streaming Pull mechanism and want to use the REST API approach)

Documentation Reference: https://cloud.google.com/pubsub/docs/pull#quotas_and_limits
"Setting a value for max_messages in the request does not guarantee that max_messages are returned, even if there are that many messages in the backlog. The Pub/Sub Pull API might return fewer than max_messages in order to reduce the delivery latency for messages that are readily available to be delivered.

A pull response that comes with 0 messages must not be used as an indicator that there are no messages in the backlog. It's possible to get a response with 0 messages and have a subsequent request that returns messages.

To achieve low message delivery latency with the unary pull mode, it's essential to have many simultaneously outstanding pull requests. As the throughput of the topic increases, more pull requests are necessary. In general, the StreamingPull mode is preferable for latency-sensitive applications."

**Comment by hongalex** [comment]
For high utilization subscriptions, we recommend having at least 20 pull RPCs outstanding at any given minute. This has to do with how the underlying infrastructure scales up and down, and having too few requests will cause the subscriber to appear inactive. Also, when using synchronous Pull, over-pulling is always preferred to under-pulling.

This is discussed in [this blog post](https://medium.com/google-cloud/google-cloud-pub-sub-how-to-monitor-the-health-of-your-subscription-for-optimal-end-to-end-latency-540b868e7929)
