### ISSUE TITLE
logging: Deserializing events routed to pubsub sink from logrouter fails on LogEntrySourceLocation\Line

### ISSUE THREAD

**Issue by talgi** [googleapis/google-cloud-go#8256]
**Client**

Go Client reading from PubSub

**Go Environment**

Ver 1.19

**Code**
// Sample taken from GCP log explorer
b := []byte("{\ninsertId: \"xxxx\"\njsonPayload: {\nmessage: \"Failed to get record: decoder: failed to decode payload: EOF\"\npid: \"1\"\n}\nlabels: {6}\nlogName: \"projects/xxx/logs/stderr\"\nreceiveTimestamp: \"2023-07-13T08:25:50.320399376Z\"\nresource: {2}\nseverity: \"WARNING\"\nsourceLocation: {\nfile: \"server.go\"\nline: \"103\"\n}\ntimestamp: \"2023-07-13T08:25:45.234204489Z\"\n}")

logEntry :=  := gcpLogging.Entry{}
if err := json.Unmarshal(b, &logEntry); err != nil {....

**Expected behavior**

Unmarshalling should succeed

**Actual behavior**

error unmarshaling LogEntry: json: cannot unmarshal string into Go struct field LogEntrySourceLocation.SourceLocation.line of type int64

**Additional context**

GCP Logs sent through log router sink are JSON serizlied. Since in LogEntrySourceLocation the 'Line' field is actually passed as 
a string from GCP (see here: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntrySourceLocation for gcp documentation).
logpb.LogEntrySourceLocation is generated from proto file and has no json:string flag and thus failing unmarshalling as the line is defined as int64.

**Comment by codyoss** [comment]
Did you do as I suggested in the PR you opened and use the protojson library? The standard library does not work with proto stubs.

https://github.com/googleapis/google-cloud-go/pull/8252#issuecomment-1632759615
