### ISSUE TITLE
cloudtasks: Client not using provided Service Account

### ISSUE THREAD

**Issue by drexhacker** [googleapis/google-cloud-go#8271]
**Client**

Cloud Tasks Client (with service account)

**Environment**

ubuntu 22.04 linux on GCE

**Go Environment**

$ go version
`go version go1.20.6 linux/amd64`
$ go env
```env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/joshua/.cache/go-build"
GOENV="/home/joshua/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/joshua/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/joshua/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3217169298=/tmp/go-build -gno-record-gcc-switches"
```

**Code**
Environment Variables
```env
CLOUDTASKS_CREDENTIALS='{
  "type": "service_account",
  "project_id": "my-project",
  "private_key_id": "<private-key-id>",
  "private_key": "-----BEGIN PRIVATE KEY-----\n<private-key>\n-----END PRIVATE KEY-----\n",
  "client_email": "<service-account-name>@<project-id>.iam.gserviceaccount.com",
  "client_id": "<client-id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/http-cloudtasks%40<project-id>.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'
```

Credentials Code
```go
// CloudTasksCredentials returns Google Application credentials as bytes.
func (container *Container) CloudTasksCredentials() []byte {
	container.logger.Debug("creating Cloud Tasks credentials")
	return []byte(os.Getenv("CLOUDTASKS_CREDENTIALS"))
}
```

Client Code
```go
// CloudTasksClient creates a new instance of cloudtasks.Client
func (container *Container) CloudTasksClient() (client *cloudtasks.Client) {
	container.logger.Debug(fmt.Sprintf("creating %T", client))

	client, err := cloudtasks.NewClient(context.Background(), option.WithCredentialsJSON(container.CloudTasksCredentials()))
	if err != nil {
		container.logger.Fatal(err)
		container.logger.Fatal(stacktrace.Propagate(err, "cannot initialize cloud tasks client"))
	}

	return client
}
```

**Expected behavior**

Expected the Client to use the `PROJECT_ID` supplied by the service account.

**Actual behavior**

But instead it uses an unkown project id `25699032575`
```sh
Caused by: rpc error: code = PermissionDenied desc = Cloud Tasks API has not been used in project 25699032575 before or it is disabled.
```

**Additional context**

Facing the Same Error on GCE and CloudRun.
Note: I created a service account with `Cloud Tasks Admin` Role but it still fails.

**Comment by bpcsys** [comment]
Will this possibly work if I use Non Google based instances?

**Comment by quartzmo** [comment]
@drexhacker Thank you for reporting this issue. I will investigate it today.

**Comment by quartzmo** [comment]
In the demo above, `25699032575` is **not** a project ID, it is a [project number](https://cloud.google.com/resource-manager/docs/creating-managing-projects). Can you please check if this project number belongs to the project specified in your credentials JSON? See [Get an existing project](https://cloud.google.com/resource-manager/docs/creating-managing-projects#get_an_existing_project).

**Comment by drexhacker** [comment]
@quartzmo Thanks for the response. Regarding that '25699032575' is not the project number for my project because I only have one project and it's Project number starts with 5*****.

**Comment by quartzmo** [comment]
The client must be getting project number `` from somewhere in the environment. Can you investigate if any of the [Application Default Credentials](https://cloud.google.com/docs/authentication/application-default-credentials) locations are set?

**Comment by quartzmo** [comment]
As for your code, I think I see an issue: You need to transform the JSON to credentials using [CredentialsFromJSON](https://pkg.go.dev/golang.org/x/oauth2/google#CredentialsFromJSON). You must pass the appropriate `scopes` for your API to this method. See the example copied below from:

https://pkg.go.dev/cloud.google.com/go#hdr-Authentication_and_Authorization

```go
ctx := context.Background()
creds, err := google.CredentialsFromJSON(ctx, []byte("JSON creds"), secretmanager.DefaultAuthScopes()...)
if err != nil {
	// TODO: handle error.
}
client, err := secretmanager.NewClient(ctx, option.WithCredentials(creds))
if err != nil {
	// TODO: handle error.
}
_ = client // Use the client.
```

**Comment by bpcsys** [comment]
@quartzmo Let Me Try your suggestions Then get back to you. Thanks Alot

**Comment by drexhacker** [comment]
@quartzmo So This is the same Error I have been receiving even after setting the GOOGLE_APPLICATION_CREDENTIALS with `gcloud auth application-default login`.
```sh
Caused by: rpc error: code = PermissionDenied desc = Cloud Tasks API has not been used in project 25699032575 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudtasks.googleapis.com/overview?project=25699032575 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.\nerror details: name = ErrorInfo reason = SERVICE_DISABLED domain = googleapis.com metadata = map[consumer:projects/25699032575 service:cloudtasks.googleapis.com]\nerror details: name = Help desc = Google developers console API activation url = https://console.developers.google.com/apis/api/cloudtasks.googleapis.com/overview?project=25699032575","time":"2023-07-20T08:47:23.828567059Z","caller":"/home/joshua/bpc-messenger/pkg/handlers/message_handler.go:99"}
```
The project ID `25699032575` seems to be retrieved from Google Metadata Servers. This is just my thinking based off the following line in the error log above `error details: name = ErrorInfo reason = SERVICE_DISABLED domain = googleapis.com metadata = map[consumer:projects/25699032575 service:cloudtasks.googleapis.com]`.

**Comment by quartzmo** [comment]
Hmm, this is confusing. According to [How Application Default Credentials works](https://cloud.google.com/docs/authentication/application-default-credentials):

> ADC searches for credentials in the following locations:

> * [GOOGLE_APPLICATION_CREDENTIALS environment variable](https://cloud.google.com/docs/authentication/application-default-credentials#GAC)
> * [User credentials set up by using the Google Cloud CLI](https://cloud.google.com/docs/authentication/application-default-credentials#personal)
> * [The attached service account, returned by the metadata server](https://cloud.google.com/docs/authentication/application-default-credentials#attached-sa)

**Comment by drexhacker** [comment]
@quartzmo same thing happened on both Cloud Run & GCP.
I even tried setting the GOOGLE_APPLICATION_CREDENTIALS manually but all in vain.

**Comment by drexhacker** [comment]
I wonder why it ignores the service account.

**Comment by drexhacker** [comment]
@quartzmo In the Same Project I am using Firebase Admin and Auth and it is working well

**Comment by quartzmo** [comment]
Here is the corresponding logic in the `oauth2/google` package:

https://github.com/golang/oauth2/blob/master/google/default.go#L109-L170

**Comment by drexhacker** [comment]
@quartzmo Am really sorry for taking your time but am abit confused what is going on. Because to day I tried it out on a non google VM instance but still the same error.

**Comment by quartzmo** [comment]
>  to day I tried it out on a non google VM instance but still the same error.

Can you execute your app in a debugger with breakpoints in [this section of `default.go`](
https://github.com/golang/oauth2/blob/master/google/default.go#L109-L170)?

**Comment by codyoss** [comment]
Please not that you may need to enable the client and resource project(the one you mention in the resource path when you are getting this error): https://cloud.google.com/apis/docs/getting-started#enabling_apis. Have you tried to enable the the api for the project id as the error suggests?

**Comment by bpcsys** [comment]
> > to day I tried it out on a non google VM instance but still the same error.
> 
> Can you execute your code in a debugger with breakpoints in [this section of `default.go`](https://github.com/golang/oauth2/blob/master/google/default.go#L109-L170)?

@quartzmo Am going to do this now.

**Comment by bpcsys** [comment]
> Please not that you may need to enable the client and resource project(the one you mention in the resource path when you are getting this error): https://cloud.google.com/apis/docs/getting-started#enabling_apis. Have you tried to enable the the api for the project id as the error suggests?

Regarding this I am getting this Error: 
```
Troubleshooting info:
  Principal: biddawoproperties@gmail.com
  Resource: 25699032575
  Troubleshooting URL: console.cloud.google.com/iam-admin/troubleshooter;permissions=resourcemanager.projects.get;principal=biddawoproperties@gmail.com;resources=%2F%2Fcloudresourcemanager.googleapis.com%2Fprojects%2F25699032575

Missing permissions:
  resourcemanager.projects.get
```

**Comment by drexhacker** [comment]
> > to day I tried it out on a non google VM instance but still the same error.
> 
> Can you execute your code in a debugger with breakpoints in [this section of `default.go`](https://github.com/golang/oauth2/blob/master/google/default.go#L109-L170)?

I have set the breakpoints but it the seems not to be reaching these points

**Comment by drexhacker** [comment]
@quartzmo To shade more light below code belongs to the part that raises the above errors.
```go
// Enqueue a task to the queue
func (queue *googlePushQueue) Enqueue(ctx context.Context, task *PushQueueTask, timeout time.Duration) (queueID string, err error) {
	ctx, span := queue.tracer.Start(ctx)
	defer span.End()

	ctxLogger := queue.tracer.CtxLogger(queue.logger, span)

	headers := map[string]string{"Content-Type": "application/json"}
	for key, value := range task.Headers {
		headers[key] = value
	}
	// Build the Task payload.
	// https://godoc.org/google.golang.org/genproto/googleapis/cloud/tasks/v2#CreateTaskRequest
	req := &taskspb.CreateTaskRequest{
		Parent: queue.queueConfig.Name,
		Task: &taskspb.Task{
			// https://godoc.org/google.golang.org/genproto/googleapis/cloud/tasks/v2#HttpRequest
			MessageType: &taskspb.Task_HttpRequest{
				HttpRequest: &taskspb.HttpRequest{
					Headers:    headers,
					HttpMethod: queue.httpMethodToProtoHTTPMethod(task.Method),
					Url:        task.URL,
				},
			},
			ScheduleTime: timestamppb.New(time.Now().UTC().Add(timeout)),
		},
	}

	// Add a payload message if one is present.
	req.Task.GetHttpRequest().Body = task.Body

	queueTask, err := queue.client.CreateTask(ctx, req)
	if err != nil {
		msg := fmt.Sprintf("cannot schedule task %s to URL: %s", string(task.Body), task.URL)
		return queueID, queue.tracer.WrapErrorSpan(span, stacktrace.Propagate(err, msg))
	}

	ctxLogger.Info(fmt.Sprintf(
		"item added to [%s] queue with id [%s] and schedule [%s]",
		queue.queueConfig.Name,
		queueTask.Name,
		queueTask.ScheduleTime,
	))

	return queueTask.Name, nil
}
```
Please help find out what am doing wrong

**Comment by drexhacker** [comment]
Let me try it out today

**Comment by quartzmo** [comment]
Closing for now. Please re-open if you are experiencing a blocker that cannot be resolved by following the guidance in documentation and error messages, thanks.
