### ISSUE TITLE
bigquery: Job list filter API

### ISSUE THREAD

**Issue by iffyio** [googleapis/google-cloud-go#8278]
**Is your feature request related to a problem? Please describe.**
Hi! Looking at the [job listing API](https://github.com/googleapis/google-cloud-go/blob/5b288b5039807211225342063c5991a1a20b51e8/bigquery/job.go#L775), it seems to only support retrieving the entire job history - this call takes several minutes to paginate through for non-trivial bigquery instances and makes it infeasible for us to even overfetch and do the filtering on the client side

**Describe the solution you'd like**
Would it be possible to add an API that allows users to filter only results that they're interested in via the min/max creation time, State and AllUsers parameters? That would make the API usable for folks that need to access job history since we can provide the parameters on method invocation
Or is there already a way to get this info efficiently via the sdk?

**Describe alternatives you've considered**
Initially tried to overfetch and filter client side but that took ages so the request was eventually aborted before completion

**Comment by shollyman** [comment]
The filters are exposed on the returned [`JobIterator`](https://pkg.go.dev/cloud.google.com/go/bigquery#JobIterator), rather than supplied on the `Jobs()` call itself.  You can set the filters then start your loop to enumerate jobs.

**Comment by iffyio** [comment]
Ah I see, that works thanks a lot!
