### ISSUE TITLE
bigquery: breaking changes for v2

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#836]
Consider these breaking changes for v2 of the client:

- Rename `FullyQualifiedName` to `FullyQualifiedID`.
- Instead of `LoaderFrom`, a `LoadFrom` method that takes a `LoadConfig`. Similarly for `CopierFrom` and `ExtractorTo`.
- Rethink how external tables and data are specified. `GCSReference` should not have to implement `ExternalData` for backwards compatibility.
- Rethink load sources. Now `LoadSource` is implemented by `ReaderSource` and `GCSReference`. Is there a clearer design?
- Rename the `QueryConfig.Q` field.
- Rethink the loader/saver design, especially the names `ValueSaver` and `ValuesSaver`.

**Comment by jba** [comment]
- Remove the `Value` type and just use `interface{}`. This would avoid unnecessary conversions. See also #845.

**Comment by kurtmaile** [comment]
Agreed would be nice.

**Comment by jadekler** [comment]
Tracking in internal bug 135054263.

**Comment by derekperkins** [comment]
The `Inserter` interface leaves a lot to be desired. I'd much prefer to have an option to pass in json that I've marshaled rather than having to jump through hoops to get `map[string]bigquery.Value`. We have some complex structs where we double marshal to get data into that format.

```
func (o *ComplexBQObject) Save() (map[string]bigquery.Value, string, error) {
	data, err := json.Marshal(o)
	if err != nil {
		return nil, "", e.Wrap(err)
	}
	toSave := map[string]bigquery.Value{}
	if err = json.Unmarshal(data, &toSave); err != nil {
		return nil, "", e.Wrap(err)
	}
	return toSave, "", nil
}
```
