### ISSUE TITLE
bigquery: StorageReadClient doesn't use page token

### ISSUE THREAD

**Issue by derekperkins** [googleapis/google-cloud-go#8373]
**Client**

BigQuery

**Environment**

Distroless on GKE

**Go Environment**

go 1.20.4

**Code**

e.g.
```go
package main

func main() {
	bqClientWithStorage, err := bigquery.NewClient(c, d.Getenv("GCP_PROJECT_ID"))

	err = bqClientWithStorage.EnableStorageReadClient(c)

	job, err := bqClient.JobFromProject(c, "project", "job", "US")

	// get a row iterator from the job
	iter, err := p.Job.Read(c)
	if err != nil {
		return nil, e.Wrap(err, e.With("pageToken", p))
	}

	// set the page token and size on the iterator
	iter.PageInfo().Token = token
	iter.PageInfo().MaxSize = pageSize

	for i := 0; ; i++ {
		var cl bqCluster
		err = iter.Next(&cl)
		...

		if pageSize = i {
			// store the next page token for the next loop (not necessarily in the same process)
			fmt.Println(iter.PageInfo().Token)

			break
		}
	}
}
```

**Expected behavior**

I can use a page token to iterate through rows

**Actual behavior**

No page token is set

**Additional context**

Iteration works with out of process page tokens using the normal BigQuery client, but fails after enabling the storage read client.

I don't see anywhere other than the first initialization that references the token or page size in the related functions, which seems to confirm that they aren't supported.
https://github.com/googleapis/google-cloud-go/blob/main/bigquery/storage_iterator.go#L115-L233

**Related issues**
- #8173

**Comment by derekperkins** [comment]
cc @alvarowolfx

**Comment by alvarowolfx** [comment]
Indeed this isn't supported when using the Storage Read API. We are discussing some ideas to support that using synthetic page tokens. But in cases where multiple parallel streams are being used to fetch data, in which ordering is not guaranteed, supporting pagination is even harder. 

I'll at least for the time being document that page tokens are not supported when using the Storage Read API.

**Comment by derekperkins** [comment]
Thanks for the confirmation. I'm looking at workarounds, and I don't see any references to [RowIterator.StartIndex](https://pkg.go.dev/cloud.google.com/go/bigquery#RowIterator) in that file either, which would be another way to handle pagination. Is that also not usable?

Is there any way to use the storage read api with out of process pagination? I'm hoping to avoid dropping down to the raw api so that our existing Loaders can be reused.

**Comment by alvarowolfx** [comment]
The [RowIterator.StartIndex](https://pkg.go.dev/cloud.google.com/go/bigquery#RowIterator) right now isn't supported either. But I'm investigating here and that has the potential to be a way of supporting out of process pagination. But like for ordered queries, we will need to restrict it to use a single stream and then override the `storagepb.ReadRowsRequest` `Offset` to start from the given `RowIterator.StartIndex` instead of starting from zero.

**Comment by alvarowolfx** [comment]
I made some tests and modifications here and unfortunately the Storage Read API doesn't allow us to start from a offset when the previous data was not consumed yet. 

```
table := "`bigquery-public-data.samples.wikipedia`"
sql := fmt.Sprintf(`SELECT id, title, timestamp, comment FROM %s LIMIT 2000`, table)
q := storageOptimizedClient.Query(sql)	
it, err := q.Read(ctx)
if err != nil {
	t.Fatal(err)
}

it.StartIndex = 1000
total, err := countIteratorRows(it)
if err != nil {
	t.Fatal(err)
}

if total != (it.TotalRows - it.StartIndex) {
	t.Fatalf("should have read %d rows, but read %d", it.TotalRows, total)
}
```

Throws an error:
```
rpc error: code = FailedPrecondition desc = there was an error operating on '[REDACTED]': offset 1000 has not been allocated yet
```

I'll check with the Storage team what else can be done, but in the short term, I don't think it will be possible.

**Comment by derekperkins** [comment]
Thanks for digging into that. Beyond just documentation, I think it'd be better if the client would just fallback to the non-storage api version or just error out, so users don't think that it's working when it isn't.
