### ISSUE TITLE
pubsub: PERMANENT_FAILURE_INVALID_ACK_ID on ack of messages when exactly-once delivery is enabled

### ISSUE THREAD

**Issue by oschwald** [googleapis/google-cloud-go#8398]
**Client**

PubSub v1.33.0

**Environment**

Ubuntu  22.04.6

**Go Environment**

$ go version

go version go1.20.7 linux/amd64

**Code description**

We have a Pub/Sub subscription with exactly-once delivery enabled that we are receiving from. We have the following `ReceiveSettings` set:

```
  MaxExtension: 6 * time.Hour,
  MaxOutstandingMessages: 10,
  MinExtensionPeriod: 5 * time.minute,
```

In the callback to `Receive` we process the message in the same goroutine. We then ack or nack using `AckWithResult` or NackWithResult`.

**Expected behavior**

For `AckWithResult`  to complete successfully assuming we have not hit the max-extension time.

**Actual behavior**

When the job takes longer than `MinExtensionPeriod`, it is very common for us to get `PERMANENT_FAILURE_INVALID_ACK_ID` errors when we finally do ack it. Based on my understanding of the client, the ack deadline should be automatically extended if we exceed the min-extension period. However, this does not seem to be happening consistently.

**Comment by hongalex** [comment]
Thanks for filing an issue. Could you help me with the following

1. Is this recent behavior or have you always encountered the permanent errors when calling `AckWithResult`
2. How long are your message processing times?
3. Are your message processing times consistent (e.g. consistently taking 1 hour to complete)

**Comment by hongalex** [comment]
So I tried to reproduce your environment with information provided (receive settings, processing times) and I haven't been able to get that error.

Could you file a support ticket (linking to this issue) so we can look into this in more detail from our end? If the error is stemming from ModifyAckDeadline calls failing (which happens in the library automatically), we would be able to see that easier.

**Comment by oschwald** [comment]
Thanks! We created case #46445663.

**Comment by hongalex** [comment]
I'll follow the case there, closing this issue. If there ends up being an issue with the client library, I'll reopen and respond to this issue.
