### ISSUE TITLE
generativelanguage: invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided.

### ISSUE THREAD

**Issue by elbertwang** [googleapis/google-cloud-go#8406]
**Client**

ai/generativelanguage/apiv1beta2/text_client.go

**Environment**

mac

**Go Environment**

go version go1.20.7 darwin/amd64
$ ➜  palm_go go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wangyunpeng/Library/Caches/go-build"
GOENV="/Users/wangyunpeng/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangyunpeng/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wangyunpeng/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wangyunpeng/code/palm_go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bx/9lskr7ms6dnflpdq4x3ck2tw00x3tc/T/go-build2047193391=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"

	generativelanguage "cloud.google.com/go/ai/generativelanguage/apiv1beta2"
	generativelanguagepb "cloud.google.com/go/ai/generativelanguage/apiv1beta2/generativelanguagepb"
)

func main() {
	ctx := context.Background()
	// This snippet has been automatically generated and should be regarded as a code template only.
	// It will require modifications to work:
	// - It may require correct/in-range values for request initialization.
	// - It may require specifying regional endpoints when creating the service client as shown in:
	//   https://pkg.go.dev/cloud.google.com/go#hdr-Client_Options
	c, err := generativelanguage.NewTextRESTClient(ctx)
	if err != nil {
		// TODO: Handle error.
		fmt.Println(err)
	}
	defer c.Close()

	temp := float32(0.2)
	maxtokens := int32(256)
	topp := float32(0.2)
	topk := int32(40)

	//text prompt
	txt := &generativelanguagepb.TextPrompt{
		Text: "I am a bison",
	}

	req := &generativelanguagepb.GenerateTextRequest{
		// TODO: Fill request struct fields.
		// See https://pkg.go.dev/cloud.google.com/go/ai/generativelanguage/apiv1beta2/generativelanguagepb#GenerateTextRequest.
		Model:           "name=models/text-bison@001",
		Prompt:          txt,
		Temperature:     &temp,
		MaxOutputTokens: &maxtokens,
		TopP:            &topp,
		TopK:            &topk,
	}
	resp, err := c.GenerateText(ctx, req)
	if err != nil {
		fmt.Println(err)
	}
	// TODO: Use resp.
	_ = resp
	fmt.Println(resp)

}

```

**Expected behavior**

➜  palm_go env | grep GOO
GOOGLE_APPLICATION_CREDENTIALS=/Users/wangyunpeng/sa.json

**Actual behavior**

➜  palm_go go run main.go
Post "https://generativelanguage.googleapis.com/v1beta2/name=models/text-bison@001:generateText?%24alt=json%3Benum-encoding%3Dint": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}
<nil>

**Additional context**

**Comment by codyoss** [comment]
I believe the last I checked you need to use an API key with this api. Example:

```golang
import (
	"context"
	"fmt"
	"log"
	"os"

	generativelanguage "cloud.google.com/go/ai/generativelanguage/apiv1beta2"
	"cloud.google.com/go/ai/generativelanguage/apiv1beta2/generativelanguagepb"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()
	client, err := generativelanguage.NewDiscussRESTClient(ctx, option.WithAPIKey("YOUR_KEY_HERE))
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	resp, err := client.GenerateMessage(ctx, &generativelanguagepb.GenerateMessageRequest{
		Model: "models/chat-bison-001",
		Prompt: &generativelanguagepb.MessagePrompt{
			Messages: []*generativelanguagepb.Message{{
				Content: "How tall is the Eiffel Tower?",
			}},
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(resp.Candidates[0].Content)
}
```

Hope that helps!
