### ISSUE TITLE
storage: Listing `Buckets` should return the same structure as the JSON API

### ISSUE THREAD

**Issue by erezrokah** [googleapis/google-cloud-go#8423]
**Client**

`Storage`

**Environment**

MacOS

**Go Environment**

`go version go1.20.6 darwin/arm64`

**Code**

https://github.com/googleapis/google-cloud-go/blob/fbe78a28e01043b059e86c6e960d092b299ac9a4/storage/bucket.go#L753

Listing buckets returns `BucketAttrs` which has a different structure than the JSON resource https://cloud.google.com/storage/docs/json_api/v1/buckets

**Expected behavior**

Listing buckets should return a similar response to the JSON API

**Actual behavior**

Listing buckets wraps the raw bucket response and normalizes fields

**Additional context**

It seems the .Net SDK does mimic the JSON API https://github.com/googleapis/google-api-dotnet-client/blob/492d0c312b872b2c09cf1bb803fe293e8593c27b/Src/Generated/Google.Apis.Storage.v1/Google.Apis.Storage.v1.cs#L6955

Also, it seems missing fields are added one at a time per request (https://github.com/googleapis/google-cloud-go/issues/4804, https://github.com/googleapis/google-cloud-go/pull/3608)

**Comment by tritone** [comment]
Yes, this is the design of the cloud.google.com/go/storage package; all API fields for resources such as bucket and object are wrapped in handwritten code. Of the other GCS clients some (such as Python, Java, C++) do it similarly to Go while others (such as .Net and Node or our raw Go client https://pkg.go.dev/google.golang.org/api@v0.138.0/storage/v1) expose the resource directly. It would be impossible to make such a transition for this package without a massive breaking change, which we don't intend to undertake.
