### ISSUE TITLE
bigquery: Wrong value for datasetID sent by bqToForeignKeys

### ISSUE THREAD

**Issue by shalinibani** [googleapis/google-cloud-go#8442]
Function  `bqToForeignKeys()` in `table.go` sends datasetID instead of projectID as first parameter to `DatasetInProject` while creating metadata for foreign keys.

**Comment by alvarowolfx** [comment]
thanks for the report @shalinibani, I've just opened PR https://github.com/googleapis/google-cloud-go/pull/8447 to fix the issue

**Comment by shalinibani** [comment]
Thanks for fixing this!
