### ISSUE TITLE
bigquery: simplify inserting rows from JSON

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#845]
Simplify inserting rows from a JSON source.

Currently you can decode each JSON row into a struct and call `Uploader.Put` with it. That assumes you have the struct defined.

You could also decode the JSON into a `map[string]interface{}`. Then you need a `ValueSaver` to convert that into a `map[string]Value`. 

`Uploader.Put` should accept a `map[string]interface{}` directly.

**Comment by jadekler** [comment]
@shollyman WDYT - should we work on this? Otherwise, let's close. I haven't heard complaints about this.

**Comment by shollyman** [comment]
I'm anticipating further evolutionary changes to the surface that will make streaming writes available via a GAPIC-based API endpoint.  Closing this.
