### ISSUE TITLE
Spanner: Support Custom Types that point back to supported types

### ISSUE THREAD

**Issue by hostirosti** [googleapis/google-cloud-go#853]
It would be great to use custom types/structs in db object structs that point back to supported types.
**Motivation:** Custom types enable custom type marsheling and unmarsheling for e.g. JSON or CSV that aren't supported by default.

**Example:**
```go
type blobField []byte
type dbProductInfo struct {
    ProductID  int64     `spanner:"ProductID"`
    UpdateDate time.Time `spanner:"UpdateDate"`
    Data       blobField `spanner:"Data"`
}
```

**Current Behavior:** Cloud Spanner Client Error: spanner: code = "InvalidArgument", desc = "client doesn't support type main.blobField"

**Desired Behavior:** It should just work

**Comment by clanstyles** [comment]
I would also like this feature.

**Comment by clanstyles** [comment]
In the mean time, what's the recommended approach to handle this?

**Comment by jba** [comment]
> In the mean time, what's the recommended approach to handle this?

Populate the fields manually, or define spanner-specific structs that only use valid field types.

**Comment by jadekler** [comment]
@olavloite WDYT about this issue? Is this reasonable, or is it too far out of scope?

**Comment by olavloite** [comment]
This sounds reasonable to me.

**Comment by dsymonds** [comment]
39a127f added support for decoding to custom types, but does encoding from custom types (the other direction) work? Should this bug remain open for that?

**Comment by olavloite** [comment]
Reopening, as https://github.com/googleapis/google-cloud-go/commit/39a127f4a0380ed5c2614616d09ac0e4efaad370 only added support for decoding, and as @dsymonds rightly pointed out above, encoding should also be supported.

**Comment by lazeratops** [comment]
Is there an example of intended usage for this? Decoding works for me, but encoding a `type MyType int64` fails. The unit tests in the commit above test `encodeValue()` directly, but it seems that applying an `InsertStruct()` mutation fails on `isSupportedMutationType()` and seems to never get to the point of running `encodeValue()` and converting the custom type.

**Comment by olavloite** [comment]
> Is there an example of intended usage for this? Decoding works for me, but encoding a `type MyType int64` fails. The unit tests in the commit above test `encodeValue()` directly, but it seems that applying an `InsertStruct()` mutation fails on `isSupportedMutationType()` and seems to never get to the point of running `encodeValue()` and converting the custom type.

It seems that you're right about this. It does allow encoding such structs as parameters of an update statement, but not for encoding such a struct as a `Mutation`.
