### ISSUE TITLE
artifactregistry : doesn't support docker image deletion

### ISSUE THREAD

**Issue by wzf1943** [googleapis/google-cloud-go#8555]
**Is your feature request related to a problem? Please describe.**
We are integrating artifact registry into our pipeline, but we found current gcloud sdk doesn't support docker image deletion in artifact repository. 

**Describe the solution you'd like**
We would like gcloud can fully support docker image deletion in API

**Describe alternatives you've considered**
We are thinking if we should call bash script to delete the expired docker images but this one's scalability has limitation

**Comment by noahdietz** [comment]
Hello there. I need a bit more information.

> gcloud sdk doesn't support docker image deletion

Are you referring to the [gcloud CLI](https://cloud.google.com/sdk/gcloud)?

> We are integrating artifact registry into our pipeline...docker image deletion in artifact repository.

Can you share the API documentation for the specific feature you are trying to use? I want to be sure of what you are asking to be made available.

**Comment by codyoss** [comment]
Closing due to lack of response.
