### ISSUE TITLE
ResourceManager: Cloud Resource Manager API has not been used in project PROJECT before or it is disabled

### ISSUE THREAD

**Issue by dunefro** [googleapis/google-cloud-go#8574]
**Client**

ResourceManager

**Environment**

Darwin Kernel Version 22.6.0

**Go Environment**

$ go version
```
go version go1.21.0 darwin/arm64
```
$ go env
```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/username/Library/Caches/go-build'
GOENV='/Users/usernam/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/username/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/username/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.0/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.0/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/private/tmp/new/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/0t/0h0jxlvn2qs6jzr6pk9l8kt40000gn/T/go-build3185342968=/tmp/go-build -gno-record-gcc-switches -fno-common'
```
**Code**

```go
//

package main

import (
	"context"
	"fmt"
	"log"
	"os"

	resourcemanager "cloud.google.com/go/resourcemanager/apiv3"
	resourcemanagerpb "cloud.google.com/go/resourcemanager/apiv3/resourcemanagerpb"
	"google.golang.org/api/iterator"
)

func main() {
	ctx := context.Background()
	c, err := resourcemanager.NewProjectsClient(ctx)
	if err != nil {
		log.Fatal(err)
	}
	req := &resourcemanagerpb.ListProjectsRequest{
		ShowDeleted: false,
	}
	it := c.ListProjects(ctx, req)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
		// TODO: Use resp.
		fmt.Println(resp.DisplayName)
	}
}

```

**Expected behavior**

I should be able to list all projects which I have access

**Actual behavior**

It gives below error
```
rpc error: code = PermissionDenied desc = Cloud Resource Manager API has not been used in project PROJECT_NAME before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=PROJECT_NAME then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
error details: name = ErrorInfo reason = SERVICE_DISABLED domain = googleapis.com metadata = map[consumer:projects/PROJECT_NAME service:cloudresourcemanager.googleapis.com]
error details: name = Help desc = Google developers console API activation url = https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=PROJECT_NAME
exit status 1
```

**Additional context**

This is a simple code to list all the projects for which I have access but there are certain projects for which Cloud Resource Manager API  has to be enabled. However when I am trying to run `gcloud projects list` it runs fine and no resource manager API has to be explicity enabled

**Comment by noahdietz** [comment]
Hi @dunefro what type of credentials are you using/how did you authenticate? Service account? User credentials? My guess is that since this RPC does not take a specific project to target with the call, it is using the quota project in your credentials to "charge" the API call, and that project doesn't have the API enabled yet.

**Comment by noahdietz** [comment]
`gcloud auth login` doesn't set up ADC for things like client libraries I think. Can you run [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login) instead and give it another try?

**Comment by dunefro** [comment]
The above issue is not coming but I am getting this error now
```
rpc error: code = InvalidArgument desc = field [parent] has issue [invalid parent name]
error details: name = BadRequest field = parent desc = invalid parent name
exit status 1
```

**Comment by noahdietz** [comment]
> Is it compulsory to pass parent name

Yes. From [the docs](https://pkg.go.dev/cloud.google.com/go/resourcemanager/apiv3/resourcemanagerpb#ListProjectsRequest):
![request_docs](https://github.com/googleapis/google-cloud-go/assets/6644735/1523bb07-c922-4a02-8090-79957957f3ce)

Please ensure that the organization ID provided in the `ORG` segment in your example is the proper value.

**Comment by noahdietz** [comment]
I'm going to close this issue now as I think we've solved the original problem. If you continue to have other issues, please open another issue! This makes things more discoverable for others and easier for us to triage things. Thanks
