### ISSUE TITLE
Spanner Statement IN array Params

### ISSUE THREAD

**Issue by peternavr** [googleapis/google-cloud-go#858]
The following query is failing. "No matching signature for operator IN for argument types STRING and {ARRAY<STRING>}

```
	stmt := spanner.Statement{
		SQL: `
			SELECT 
				Id,
				Name
			FROM People
			WHERE Id IN (@ids)
		`,
		Params: map[string]interface{}{
			"ids": ids,
		},
	}
```

If I query it manually, it works. It's the ids slice that's failing. 
```
			SELECT 
				Id,
				Name
			FROM People
			WHERE Id IN ('a')
```

What's the right way to do this?

**Comment by oskbor** [comment]
@clanstyles 
Did you find a way to do that?

**Comment by olavloite** [comment]
@oskbor 
Assuming that the `ids` 
The following should work. Note the UNNEST before the list of values. This is needed as you are passing the query an array of values. See also https://cloud.google.com/spanner/docs/arrays#scanning-arrays

```go
        ids := []string{"foo", "bar"}
	stmt := spanner.Statement{
		SQL: `
			SELECT 
				Id,
				Name
			FROM People
			WHERE Id IN UNNEST (@ids)
		`,
		Params: map[string]interface{}{
			"ids": ids,
		},
	}
```
