### ISSUE TITLE
pubsub/pstest: Support for subscription filters

### ISSUE THREAD

**Issue by andreas-lindfalk** [googleapis/google-cloud-go#8582]
**Is your feature request related to a problem? Please describe.**
Nor the pubsub emulator or pstest support subscription filters, making it impossible to integrationtest a pubsub setup making use of filters today. 

**Describe the solution you'd like**
There is an embryo in pstest for filters, they can be set and updated and there is a filterMsgs func where filters could be applied according to the documented filter rules. In other words, implement support for subscription filters in pstest 

**Describe alternatives you've considered**
As mentioned, the pubsub emulator does not support subscription filters either…

**Additional context**
I could take a stab at implementing this if you peps at Google have limited resources ;)

**Comment by hongalex** [comment]
Hey, thanks for bringing this up. Yeah unfortunately supporting filtering in either the emulator and the fake is not a high priority item currently.

If you have a PR to send over, I would be happy to look it over and find a way to get that merged in. Would require signing a [CLA](https://cla.developers.google.com/clas)

**Comment by zezhehh** [comment]
> Hey, thanks for bringing this up. Yeah unfortunately supporting filtering in either the emulator and the fake is not a high priority item currently.
> 
> If you have a PR to send over, I would be happy to look it over and find a way to get that merged in. Would require signing a [CLA](https://cla.developers.google.com/clas)

Just submitted a PR. It would be great if you could take a look :D 
https://github.com/googleapis/google-cloud-go/pull/9015
