### ISSUE TITLE
spanner: flaky transaction tag test failure

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-go#8590]
```
=== NAME  TestClient_ReadOnlyTransaction_Tag
    testing.go:1465: race detected during execution of test
--- FAIL: TestClient_ReadOnlyTransaction_Tag (0.04s)
=== CONT  TestClient_PDML_Priority
=== NAME  TestStressSessionPool/TestStressSessionPoolGroup2
    session_test.go:894: TestStressSessionPoolWithCfg2Worker093
    session_test.go:894: TestStressSessionPoolWithCfg2Worker094
    session_test.go:894: TestStressSessionPoolWithCfg2Worker095
    session_test.go:894: TestStressSessionPoolWithCfg2Worker096
=== NAME  TestClient_ReadWriteTransaction_Tag
    testing.go:1465: race detected during execution of test
--- FAIL: TestClient_ReadWriteTransaction_Tag (0.08s)
```

Source: https://source.cloud.google.com/results/invocations/d3b0eafa-7bda-43b9-987b-2de813e47c96/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Flatest-version/log

**Comment by rahul2393** [comment]
Seems like issue on spannertest package, thanks for pointing it out, will dig more.

**Comment by noahdietz** [comment]
I think this issue is now blocking PRs with Kokoro failures: https://source.cloud.google.com/results/invocations/667dd248-c60f-4196-b5b9-9b2e7f294198/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Flatest-version/log

**Comment by codyoss** [comment]
If we are prioritizing fixing this issue please skip the test until there is time to fix the issue.

**Comment by rahul2393** [comment]
Let me create PR to skip the test for now

**Comment by rahul2393** [comment]
Found a code block which can cause data race, will reopen if it does not fix it.
