### ISSUE TITLE
spanner/spansql: parseDDL does not support GENERATE_UUID

### ISSUE THREAD

**Issue by egonvb** [googleapis/google-cloud-go#8594]
```
	sql := "CREATE TABLE Test ( " +
		"Id STRING(36) NOT NULL DEFAULT( GENERATE_UUID() )" +
		") PRIMARY KEY (Id);"
	ddl, err := spansql.ParseDDL("", string(sql))
```

results in following error

`err :1.65: got "(" while expecting ")"`

The parser looks unable to handle the generate_uuid function as default for the column.

**Comment by rahul2393** [comment]
Hello @egonvb, we already have a fix in pipeline to be released in 1.50.0 https://github.com/googleapis/google-cloud-go/pull/8482.
