### ISSUE TITLE
create tool to automate mass change rollout across modules

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-go#8617]
It would be nice to have a tool that could construct a single commit that fans a change out to all/select modules in this monorepo, making use of the `BEGIN_NESTED_COMMIT` and `END_NESTED_COMMIT `.

Some use cases are:
- manually rolling out a dep bump
- notice of a drop in support of a runtime

**Comment by noahdietz** [comment]
I added the hacky [`updateall`](https://github.com/googleapis/google-cloud-go/tree/main/internal/actions/cmd/updateall#updateall) command to `internal/actions/cmd` that was meant to dump a specific dep in all submodules that contained it.

Would be useful if that command could spit out the commit message for the change e.g. "use the following nested commit to trigger releases in all modified modules". That is to say, if this functionality could be a library as well as an executable, that would be sweet.

**Comment by codyoss** [comment]
> Would be useful if that command could spit out the commit message for the change 

I think that is a great idea!
