### ISSUE TITLE
datastore: The reference implementation in the documentation uses a depricated function `Query.Filter`

### ISSUE THREAD

**Issue by takanakahiko** [googleapis/google-cloud-go#8638]
Related Issue: #6725

The [datastore documentation](https://pkg.go.dev/cloud.google.com/go/datastore@v1.14.0) uses a depricated function ( `Query.Filter` ).
It should be fixed to `FilterField` as new users will use `Filter` by reference to it.

In addition to what was pointed out in the related Issue( #6725 ) , there are other points that should be fixed as follows

- https://github.com/googleapis/google-cloud-go/blob/5feb3eaa2a73b147f7858b5c91c59315a914b344/datastore/example_test.go#L274
- https://github.com/googleapis/google-cloud-go/blob/5feb3eaa2a73b147f7858b5c91c59315a914b344/datastore/doc.go#L223

**Comment by takanakahiko** [comment]
Since this is a fairly small change, I made the PR( #8639  ) before the issue was discussed in the Issue.
If there are any problems, I will rework the PR with the correct flow.

**Comment by takanakahiko** [comment]
@bhshkh It's been a week since I created the issue and PR, but no action has been taken. Please let me know if there is anything that needs to be done here.

**Comment by bhshkh** [comment]
Thanks for creating the PR. I have approved it.

**Comment by takanakahiko** [comment]
thx!
