### ISSUE TITLE
Firestore: `BulkWriterJob.Results()` should return gRPC status code for `status.Code()`

### ISSUE THREAD

**Issue by wjkoh** [googleapis/google-cloud-go#8641]
I'm disappointed that the BulkWriterJob.Results() method does not return an error that we can use the status.Code() on to determine if the error is a "not found" error or an "already exists" error, like we can with other Firestore functions like DocumentRef.Set(). I would like to see BulkWriterJob.Results() return an error that we can access gRPC status codes from.

**Comment by noahdietz** [comment]
_Disclaimer: I don't work on this package, just on rotation triaging un triaged issues._

I think this might be the logic in question:
https://github.com/googleapis/google-cloud-go/blob/0c97c14046893ca5d73d371b3abfe4af297bfd7a/firestore/bulkwriter.go#L334-L338

I could be wrong, but perhaps that code could be using `%w` to wrap the `Status` as an `error` via the [`status.ErrorProto` api](https://pkg.go.dev/google.golang.org/grpc/status#ErrorProto). Might just be that one line fix...
