### ISSUE TITLE
bigquery: `rowIterator.Next` calls hangs forever possibly because of not having `bigquery.readsessions.getData` permission

### ISSUE THREAD

**Issue by k-anshul** [googleapis/google-cloud-go#8660]
**Client**
bigquery - main

**Environment**
macOS arm64

**Go Environment**
go version go1.21.0 darwin/arm64

**Expected behavior**
Client should throw permission denied error(or similar)

**Actual behavior**
Client hangs forever 

**Additional context**
I used a debugger to catch the place where its stuck. These are my findings.
The issue only happens when the SDK fetches the results using arrow streams. 
In `storage_iterator.go` while processing streams in `processStream` function. It first creates a session and then read rows using `it.session.readRows` call. It checks for applicable error for retrying but weirdly no errors are returned here. It then consumes the stream using `it.consumeRowStream` call. I see the error being returned here but there is no retry classification logic here and it retries for all errors apart from context cancellation errors. 
Here is the error msg that I see:
```
error(*fmt.wrapError) *{msg: "failed to consume rows on stream xxx: rpc error: code = PermissionDenied desc = there was an error operating on 'xxxx': the user does not have 'bigquery.readsessions.getData' permission for 'xxxxx'", err: error(*google.golang.org/grpc/internal/status.Error) *{s: *(*"google.golang.org/grpc/internal/status.Status")(0x140011ba088)}}
```

**Comment by alvarowolfx** [comment]
I'm investigating this issue here @k-anshul. Weirdly enough, the PermissionDenied error should have been thrown on the `it.session.readRows`, not on the `consumeRowStream` > `rowStream.Recv`. I'll keep you up to date as I find more about this issue.
