### ISSUE TITLE
storage: importing cloud.google.com/go/storage disables the dead code elimination

### ISSUE THREAD

**Issue by dominiquelefevre** [googleapis/google-cloud-go#8745]
When the go compiler encounters a call to `MethodByName()`, it assumes that every method of every reachable type can be accessed, and nothing may be eliminated. `cloud.google.com/go/storage` uses `MethodByName()` to invoke methods like `IfMetagenerationMatch()`. This disables the DCE in all users of GCS.

Go 1.22 has gained support for calls like `MethodByName("Foobar")` where the name of a method to look up is a compile-time constant. In this case the compiler no longer disables the DCE, and only keeps methods named Foobar.

Rewrite `setConditionField()` so that `MethodByName()` is only called with compile-time constants. This way importing `cloud.google.com/go/storage` will not inhibit the DCE.

**Comment by dominiquelefevre** [comment]
Hey, anybody out here? @tritone?

**Comment by BrennaEpp** [comment]
Hi @dominiquelefevre, thanks for opening this issue.

Rewriting `setConditionField` requires code duplication that is not ideal, but is however necessary for Go to eliminate dead code to reduce binary sizes. Given that maintaining the variable in the call to `MethodByName` may affect the size of all binaries importing storage, I think it makes sense to move forward with this. I will go ahead and review your PR.

Just adding more context:
In general, the reachability analysis that the Go linker does for dead code elimination (DCE) is pretty effective, except that if one uses reflect [`(reflect.Value).MethodByName`](https://pkg.go.dev/reflect#Value.MethodByName) to access a method, usually it can't determine what methods it needs so it will be very conservative and keep essentially all exported methods. After [recent changes](https://go-review.googlesource.com/c/go/+/522436), if `MethodByName` is called with a constant name, it only keep methods with that name, not other methods. But this property is global, meaning that in the entire program, if there is any single call of MethodByName with a non-constant name, it will have to be conservative. This means a single import can require all methods be kept, effectively disabling dead code elimination.
See: https://cs.opensource.google/go/go/+/master:src/cmd/link/internal/ld/deadcode.go;l=418-422
