### ISSUE TITLE
bigquery: wrong google.golang.org/api version causes any build to fail since version v1.57.0

### ISSUE THREAD

**Issue by brachipa** [googleapis/google-cloud-go#8946]
**Client**

bigquery

**Environment**

A simple go app

**Code**

```go
func main() {
	ctx := context.Background()
	client, err := bigquery.NewClient(ctx, "abc")
	if err != nil {
		panic(err)

	}
	client.Close()
}
```
go.mod 

```go

require cloud.google.com/go/bigquery v1.57.0
```

**Expected behavior**

Build should pass and project should be compiled

**Actual behavior**

The bigquery itself can't be compiled with the bellow errors:

# cloud.google.com/go/bigquery
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:249:6: ds.ExternalDatasetReference undefined (type *"google.golang.org/api/bigquery/v2".Dataset has no field or method ExternalDatasetReference)
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:316:62: d.ExternalDatasetReference undefined (type *"google.golang.org/api/bigquery/v2".Dataset has no field or method ExternalDatasetReference)
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:409:6: ds.ExternalDatasetReference undefined (type *"google.golang.org/api/bigquery/v2".Dataset has no field or method ExternalDatasetReference)
../../go/pkg
/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:964:42: undefined: bigquery.ExternalDatasetReference
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:974:49: undefined: bigquery.ExternalDatasetReference
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/dataset.go:978:13: undefined: bigquery.ExternalDatasetReference
../../go/pkg/mod/cloud.google.com/go/bigquery@v1.57.0/query.go:491:12: qRequest.JobCreationMode undefined (type *"google.golang.org/api/bigquery/v2".QueryRequest has no field or method JobCreationMode)

Seems because a wrong indirect dependency `google.golang.org/api v0.134.0 // indirect`

Looks related to this change 343cea8c43b1e31ae21ad50ad31d3b0b60143f8c
the version was downgraded from 0.145.0 to 0.134.0
<img width="1356" alt="Screenshot 2023-10-31 at 17 25 05" src="https://github.com/googleapis/google-cloud-go/assets/46258658/b162146f-f19f-436b-b760-531983ac900a">
 too much to incompatible version.

**Comment by shollyman** [comment]
Thanks for the report.  Yeah, looks like an unintentional merge stomp of some form.  We'll get this cleaned up, and investigate why it didn't get flagged in our release pipeline.

**Comment by shollyman** [comment]
We've released cloud.google.com/go/bigquery v1.57.1 to address this.
