### ISSUE TITLE
spanner: provide table and index details for unique constraint violations for Mutation API

### ISSUE THREAD

**Issue by toga4** [googleapis/google-cloud-go#8971]
**Is your feature request related to a problem? Please describe.**
When using Mutation API, such as `spanner.Insert`, to insert records into multiple tables, it's not possible to determine which unique constraint was violated.
In situations where a violation of a specific unique constraint is anticipated, while others should not be violated, handling just an `codes.AlreadyExists` error is not sufficient to identify the root cause.
The error message retrieved using `spanner.ErrDesc` may include the table or index name, but as these messages are not standardized as part of the API and can change, relying on them makes the code unreliable.
Attempts to unwrap to a `*apierror.APIError` type have not included the necessary information.

**Describe the solution you'd like**
I would like more detailed error information.
Although it is probably handled internally as a `*apierror.APIError` type, introducing an API such as `spanner.ErrDetails`, that would allow to extract detailed error information specific to Spanner from this type, would be ideal.
Through the structure returned by this API, would like to extract information such as the table name and index name where the unique constraint violation occurred.

**Describe alternatives you've considered**
One alternative would be using ReadWrite transactions to pre-check for unique constraint violations before insertion by reading.
However, this increases communication with the server and the possibility of transaction aborts, which degrades performance.
Another method would be to use DML for insertion, but this also might have poorer performance compared to the bufferable Mutation API.

**Additional context**
none.

**Comment by noahdietz** [comment]
> I would like more detailed error information.

FWIW the call stack should not be mutating the returned Status object. If there are no details in the return `Status`, there will be no details in the returned `APIError`. You can retrieve the `Status` object directly from the `error` using the typical [`FromError` grpc-go API](https://pkg.go.dev/google.golang.org/grpc@v1.59.0/status#FromError) and verify.

If I'm wrong about that, it would constitute a bug in `APIError` parsing or in the Spanner client (if it mutated the error returned).

If I'm write about the lack of details, this would be Service feedback, not client library feedback, and would belong in [the public issue tracker](https://b.corp.google.com/issues/new?component=190851&template=844402&pli=1).

Triaged as a feature request for rotation Triaging.

**Comment by toga4** [comment]
Thank you for your comment.

Indeed, my feature request points out the lack of detailed error information returned by the service.
I understand that if the details are not present in the Status object, they won't be in the APIError either.

As you have suggested, I'll create an issue in the public issue tracker to feedback.
