### ISSUE TITLE
Checkout of git repository is broken on Windows by recently added aux.go files

### ISSUE THREAD

**Issue by gregoryT5** [googleapis/google-cloud-go#8983]
**Summary**

Can no longer finish clone+checkout of this git repository on Windows because of the new aux.go files added in commit b44c4b301a91e8d4d107be6056b49a8fbdac9003 .

**Environment**

Bazel using `bazel-gazelle` to retrieve this git repository on Windows 10.

**Code**

when using bazel-gazelle:

```
go_repository(
    name = "com_google_cloud_go",
    commit = "b44c4b301a91e8d4d107be6056b49a8fbdac9003",
    importpath = "cloud.google.com/go",
)
```

**Expected behavior**

Repository can be cloned on Windows, which worked before the commit mentioned above.

**Actual behavior**

Repository fails clone on Windows because of the aux.go files.  "aux" is a reserved filename on Windows.

Example of a simple `git clone` failing because of this (i.e., it is not an issue exclusive to bazel or bazel-gazelle):

```
$ git clone https://github.com/googleapis/google-cloud-go.git
Cloning into 'google-cloud-go'...
remote: Enumerating objects: 332613, done.
remote: Counting objects: 100% (22169/22169), done.
remote: Compressing objects: 100% (1053/1053), done.
remote: Total 332613 (delta 21422), reused 21168 (delta 21106), pack-reused 310444
Receiving objects: 100% (332613/332613), 189.86 MiB | 13.77 MiB/s, done.
Resolving deltas: 100% (225671/225671), done.
error: invalid path 'accessapproval/apiv1/aux.go'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Proposed resolution**

Rename the aux.go files to something that isn't a reserved name on Windows.

**Comment by noahdietz** [comment]
Ok we can switch it, but it will take some time to get it all rolled out/released. Apologies, didn't realize this would be a problem.

**Comment by gregoryT5** [comment]
completely understand, thanks for following up with the fix!

**Comment by vzsg** [comment]
Another casualty of the aux.go filename is the Go module mirror.

The following URL returns a similar error message instead of version data: [https://sum.golang.org/lookup/cloud.google.com/go/storage@v1.35.0](https://sum.golang.org/lookup/cloud.google.com/go/storage@v1.35.0)

Which breaks `go list`:

```
% go list -m --versions cloud.google.com/go/storage
go: loading module retractions for cloud.google.com/go/storage@v1.0.0: verifying go.mod: cloud.google.com/go/storage@v1.35.0/go.mod: reading https://sum.golang.org/lookup/cloud.google.com/go/storage@v1.35.0: 404 Not Found
	server response: not found: create zip: internal/apiv2/aux.go: malformed file path "internal/apiv2/aux.go": "aux" disallowed as path element component on Windows
```

...and by extension, Goland's update checking feature (where I got the error first).

**Comment by noahdietz** [comment]
I am hoping to have a release today/tomorrow with the updates for most modules. Some modules take special attention, so they likely won't be released until next week (11/13).

Again apologies for the issue.

**Comment by noahdietz** [comment]
Just realized that the original report was using a commit hash directly, becuase the `aux.go` generation hadn't been released to any module, until Storage released and @vzsg reported that. So we only need to make a Storage patch release.

**Comment by noahdietz** [comment]
@gregoryT5 HEAD should bare the fix now

@vzsg I'm cutting a storage patch release now

**Comment by noahdietz** [comment]
Thanks @gregoryT5 for using commit hashes and not tagged releases to flag this when you did. That said, start using tagged releases 😆 (jk, kind of)

**Comment by vzsg** [comment]
> @vzsg I'm cutting a storage patch release now

Thank you! The new version resolved the issue in both Goland and the command line 👍🏻

**Comment by gregoryT5** [comment]
> Thanks @gregoryT5 for using commit hashes and not tagged releases to flag this when you did. That said, start using tagged releases 😆 (jk, kind of)

thanks for fixing! we actually are using specific versions, but unfortunately it turns out `bazel-gazelle` has a weird bad behavior when using `go_repository` where it first does a `git clone` of the full repo before checking out the specified version, rather than just checking out the specified revision on initial clone, causing it to be affected by whatever is at HEAD.

**Comment by noahdietz** [comment]
> > Thanks @gregoryT5 for using commit hashes and not tagged releases to flag this when you did. That said, start using tagged releases 😆 (jk, kind of)
> 
> thanks for fixing! we actually are using specific versions, but unfortunately it turns out `bazel-gazelle` has a weird bad behavior when using `go_repository` where it first does a `git clone` of the full repo before checking out the specified version, rather than just checking out the specified revision on initial clone, causing it to be affected by whatever is at HEAD.

TIL! That indeed sounds like an odd behavior. Regardless, thanks for the report, super appreciated.
