### ISSUE TITLE
firestore: index required but no link provided 

### ISSUE THREAD

**Issue by johnbalvin** [googleapis/google-cloud-go#8987]
**Client**

FIrestore 

**Go Environment**

$ go version go1.21.4 windows/amd64 
$ set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\upwork\abogado\cjf mapa\bot\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\user\AppData\Local\Temp\go-build1963280502=/tmp/go-build -gno-record-gcc-switches

**Code**

```
	"cloud.google.com/go/firestore"

func main() {
	query := clients.FR.Collection("collection").Where("field_string", "==", value).Where("field_int", "==", year).OrderBy("Number", firestore.Desc).Limit(1)
	snaps, err := query.Documents(ctx).GetAll()
	if err != nil {
		log.Fatalln("err: ", err) // 
		//err:  rpc error: code = FailedPrecondition desc = Missing index configuration. Please create corresponding index via gcloud.
	}
}
```

**Expected behavior**

Getting the query result 

**Actual behavior**

this error without the link: 
 rpc error: code = FailedPrecondition desc = Missing index configuration. Please create corresponding index via gcloud.

**Screenshots**
![image](https://github.com/googleapis/google-cloud-go/assets/25888114/8619367b-e52d-4e43-929b-4429bd5f8e4f)

**Comment by johnbalvin** [comment]
even using the interfaz, I still get the issue without the link: 
![image](https://github.com/googleapis/google-cloud-go/assets/25888114/6be263ff-5484-4c44-970d-c702999c2ec4)

**Comment by noahdietz** [comment]
@johnbalvin can you be a little more specific about what "link" you are expecting to see? 

Do you mean that you expect a help link in the error message? Thanks

**Comment by johnbalvin** [comment]
Hi @noahdietz yes, when there is an issue with the index, I usually get a link for creating the index, that's the link I'm referring to

**Comment by noahdietz** [comment]
So you saying there has been a change in the behavior of this specific method in this error mode?

Could be that the service has stopped sending such a link in the error response, or the client changed how the error is wrapped thus squashing what was previously returned.

**Comment by johnbalvin** [comment]
> So you saying there has been a change in the behavior of this specific method in this error mode?
> yes 
> Could be that the service has stopped sending such a link in the error response, or the client changed how the error is wrapped thus squashing what was previously returned.
> I don't know about it, but it doesn't send the link on the UI, so probably the service doesn't send the link anymore

**Comment by noahdietz** [comment]
> I don't know about it, but it doesn't send the link on the UI, so probably the service doesn't send the link anymore

Thanks, that's really helpful. If the service has changed something, then it would be best for you to file an issue on the service's public issue tracker [here](https://b.corp.google.com/issues/new?component=530136&template=1192449).

We can't do much from here as we do not work on the Firestore service, just the client libraries. As such, I'm going to close this issue. If @bhshkh disagrees as maintainer of the firestore module, she can reopen the issue.
