### ISSUE TITLE
bigquery: support for RANGE type

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-go#9017]
This issue tracks the work to enable support for the RANGE datatype in the BigQuery Go client libraries.

**Comment by alvarowolfx** [comment]
I'll check if the RANGE type is supported when using Storage Read API acceleration and add support for it if needed.

**Comment by shollyman** [comment]
Released as https://github.com/googleapis/google-cloud-go/releases/tag/bigquery/v1.61.0

Marking this work done.
