### ISSUE TITLE
storage: `MediaURL` attribute returned after upload does not match schema for relevant access level.

### ISSUE THREAD

**Issue by magandrez** [googleapis/google-cloud-go#9038]
**Client**

cloud.google.com/go/storage v1.35.1

**Environment**

- Google Cloud Storage with a bucket (e.g. "foobar" with public access set to *NOT PUBLIC*).
- For bucket "foobar", the role "Storage Object Viewer" has been given to a group of users.

**Go Environment**

$ go version
go version go1.21.1 linux/amd64

$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/manuel/.cache/go-build'
GOENV='/home/manuel/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/manuel/workbench/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/manuel/workbench/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/manuel/workbench/processor/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2175479791=/tmp/go-build -gno-record-gcc-switches'

**Code**

Mimicking implementation from an [example of upload from GoogleCloudPlatform/golang-samples](https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/storage/objects/stream_file_upload.go) 

```go
package objects

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"time"

	"cloud.google.com/go/storage"
)

// streamFileUpload uploads an object via a stream.
func streamFileUpload() (string, error) {
	bucket := "foobar"
	object := "foobar.txt"
	ctx := context.Background()
	client, err := storage.NewClient(ctx)
	if err != nil {
		return "", fmt.Errorf("storage.NewClient: %w", err)
	}
	defer client.Close()

	b := []byte("Hello world.")
	buf := bytes.NewBuffer(b)

	ctx, cancel := context.WithTimeout(ctx, time.Second*50)
	defer cancel()

	// Upload an object with storage.Writer.
	wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
	wc.ChunkSize = 0 // note retries are not supported for chunk size 0.

	if _, err = io.Copy(wc, buf); err != nil {
		return "", fmt.Errorf("io.Copy: %w", err)
	}
	// Data can continue to be added to the file until the writer is closed.
	if err := wc.Close(); err != nil {
		return "", fmt.Errorf("Writer.Close: %w", err)
	}
	return wc.Attrs().MediaLink, nil
}

```

**Expected behavior**

Calling `streamFileUpload` described above given the environment above, I would expect that would generate a URL with a schema of an [authenticated browser download link described here](https://cloud.google.com/storage/docs/request-endpoints#cookieauth). On the fanciest of the scenarios, I would expect that, depending on the access for the bucket, the `MediaLink` attribute would generate URLs with a schema that would match the access to the bucket.

**Actual behavior**

The string returned is that which would give access to a public object with a URL schema described [here](https://cloud.google.com/storage/docs/request-endpoints#access_to_public_objects). This is at odds with the bucket being set to not allow public access. Accessing the returned URL on a browser results in status 401 Unauthorized even though I am authenticated with a user under the group with the role described in the section "Environment" (above) and that's the only account authenticated in the browser instance.

**Comment by tritone** [comment]
Sorry for the delayed response on this. We are simply piping through the mediaLink field returned by the [object resource](https://cloud.google.com/storage/docs/json_api/v1/objects) to this field. I don't think we use the https://storage.cloud.google.com format you mention anywhere in the client libraries since the main use case is programmatic access, not anything related to browser downloads. I think branching logic based on whether the object is public or not on the client side gets complicated pretty quickly, and there are a variety of different valid download URLs for the same object, so I am not inclined to add any client side logic for this specific case.

You can file a feature request with the product team if you like, but I think it's easy to just construct the correct URL in application logic based on the bucket and object name. Let me know if you have further questions.
