### ISSUE TITLE
speech: StreamingRecognize function never returns value.

### ISSUE THREAD

**Issue by torniker** [googleapis/google-cloud-go#9041]
**Client**

Speech
cloud.google.com/go/speech v1.21.0

**Environment**

MacOS Sonoma 14.1.1

**Go Environment**

$ go version go1.21.3 darwin/arm64

$ go env

```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/koko/Library/Caches/go-build'
GOENV='/Users/koko/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/koko/go/pkg/mod'
GOOS='darwin'
GOPATH='/Users/koko/go'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.3/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.3/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/xv/5ch5fd1n7_x87bv7vpbhk04r0000gn/T/go-build1984898348=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"
	"log"

	speech "cloud.google.com/go/speech/apiv2"
	"google.golang.org/api/option"
)

func main() {

	ctx := context.Background()

	client, err := speech.NewClient(
		ctx,
		option.WithEndpoint("europe-west4-speech.googleapis.com"),
	)
	if err != nil {
		log.Fatal(err)
		return
	}
	fmt.Println("--> before")
	stream, err := client.StreamingRecognize(ctx)
	if err != nil {
		log.Fatal(err)
		return
	}
	fmt.Println("--> after", stream)
}

```

**Expected behavior**

Transcribe audio to using stream. 

**Actual behavior**

Never finishes execution.

**Additional context**

If you run the code you'll see that `--> before` is printed but it never gets to `--> after`. 

One thing I've noticed is that if I don't specify `option.WithEndpoint("europe-west4-speech.googleapis.com")` it prints after, but you'll notice that the `stream` is `nil`. 

These are the version of dependencies in go.mod:
```
google.golang.org/api v0.149.0
google.golang.org/grpc v1.59.0
cloud.google.com/go/speech v1.21.0
```

Not sure if this is a bug or am I doing something wrong?

**Comment by torniker** [comment]
@noahdietz Thanks for the response. 

I've figured that the problem in my code was that I haven't specified port for the endpoint. It should've been:
```
option.WithEndpoint("europe-west4-speech.googleapis.com:443"),
```

One point is that probably the code behind this should give some kind of feedback in that case, I changed the actual library code to see what was the error, it said: `missing port in address`

The second and more important (for me at least) is that I still get nil and don't know why

```go
func (c *gRPCClient) StreamingRecognize(ctx context.Context, opts ...gax.CallOption) (speechpb.Speech_StreamingRecognizeClient, error) {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	var resp speechpb.Speech_StreamingRecognizeClient
	opts = append((*c.CallOptions).StreamingRecognize[0:len((*c.CallOptions).StreamingRecognize):len((*c.CallOptions).StreamingRecognize)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.client.StreamingRecognize(ctx, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	fmt.Println("-->", resp) // <-- the resp is nil for me
	return resp, nil
}
```

**Comment by noahdietz** [comment]
> I haven't specified port for the endpoint.

Oh that is a tricky one. We should do something about that...at least a documentation update for the `WithEndpoint` option.

> P.S. The endpoint I've got is from here

I see. I would not use that as a reference for connection endpoints. I think that is a reference for the language codes, where they are supported when a location is provided in the request message. That is different than making a connection.

Please just try using the `eu-speech.googleapis.com:443` endpoint because that is what they publish as their preferred regional endpoints.

**Comment by torniker** [comment]
Everything works just fine with port at the end. Sorry my bad.. Probably changed source in the library and that's why it was returning `nil`. 

Closing this issue.

**Comment by noahdietz** [comment]
Glad it worked out, thanks for debugging that.
