### ISSUE TITLE
storage: make a new release

### ISSUE THREAD

**Issue by dominiquelefevre** [googleapis/google-cloud-go#9069]
The change https://github.com/googleapis/google-cloud-go/commit/ca2493f43c299bbaed5f7e5b70f66cc763ff9802 was committed three weeks ago, but the latest release of `cloud.google.com/go/storage` (1.35.1 as of the moment when I file this issue) does not include it.

Make a new release of `cloud.google.com/go/storage` to include the latest improvements and fixes.

**Comment by tritone** [comment]
@dominiquelefevre we'll have it out by the end of the week; we are finishing one more thing to be included. The release PR is #9002 .

**Comment by BrennaEpp** [comment]
This is now released.
