### ISSUE TITLE
Cannot access `totalSize` for discoveryengine.SearchClient.Search

### ISSUE THREAD

**Issue by samiemad** [googleapis/google-cloud-go#9092]
I am trying to integrate Vertex AI search into our application. We would like to show how many total results does the query match. Doing a curl request, I get the total size in the response:

```
curl --location 'https://eu-discoveryengine.googleapis.com/v1alpha/projects/$project>/locations/eu/collections/default_collection/dataStores/$dataStore/servingConfigs/default_search:search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data '{
    "query": "Hello world",
    "pageSize": 10
}'

>>> result:
{
    "results": [...],
    "totalSize": 91,
    "attributionToken": "...",
    "nextPageToken": "...",
    "guidedSearchResult": {},
    "summary": {}
}
```

But when using the go library, I cannot seem to find `totalSize` field in the returned struct `SearchResponse_SearchResultIterator`

https://github.com/googleapis/google-cloud-go/blob/ea015f070e8e4dc7da5cf5208a4b67fe6ee19518/discoveryengine/apiv1beta/search_client.go#L458

Looking around, I can see the field in discoveryenginepb https://github.com/googleapis/google-cloud-go/blob/2ba47cb7adfef32617eb11888331ccc2d2a0f84d/discoveryengine/apiv1beta/discoveryenginepb/search_service.pb.go#L598C5-L598C5
But for some reason it is not exposed to discoveryengine

Am I using it wrong? How can I access the total result size for my query without having to iterate over all results?

**Comment by jagobagascon** [comment]
I'm having the same issue trying to access the `correctedQuery` field. According to the proto the return type of the `Search` function should be `SearchResponse` and not `SearchResponse_SearchResultIterator`.

https://github.com/googleapis/googleapis/blob/d1d165ff0067197fc14491d7d9509c9112daa988/google/cloud/discoveryengine/v1/search_service.proto#L43

**Comment by quartzmo** [comment]
Hi @samiemad, as you can see from the link provided above, the `Search` RPC returns a pointer to a [`SearchResponse_SearchResultIterator`](https://pkg.go.dev/cloud.google.com/go/discoveryengine@v1.4.0/apiv1beta#SearchResponse_SearchResultIterator). This type provides automatic pagination. But it also exposes the underlying `Response` from the backend. You have to cast it to the correct type for the RPC.

```
type SearchResponse_SearchResultIterator struct {

	// Response is the raw response for the current page.
	// It must be cast to the RPC response type.
	// Calling Next() or InternalFetch() updates this value.
	Response interface{}
        ...
```

**Comment by quartzmo** [comment]
The correct type to cast the response to is [`SearchResponse`](https://pkg.go.dev/cloud.google.com/go/discoveryengine@v1.4.0/apiv1beta/discoveryenginepb#SearchResponse), which you also linked. It's in a different package that just contains types from protos, so it can be a little hard to find in the docs.

**Comment by quartzmo** [comment]
Please note that in order to get the underlying response, you have to call `Next` on the iterator at least once. Here's an example:

```go
package main

import (
	"context"
	"log"

	discoveryengine "cloud.google.com/go/discoveryengine/apiv1beta"
	discoveryenginepb "cloud.google.com/go/discoveryengine/apiv1beta/discoveryenginepb"
)

func main() {
	ctx := context.Background()
	// This snippet has been automatically generated and should be regarded as a code template only.
	// It will require modifications to work:
	// - It may require correct/in-range values for request initialization.
	// - It may require specifying regional endpoints when creating the service client as shown in:
	//   https://pkg.go.dev/cloud.google.com/go#hdr-Client_Options
	c, err := discoveryengine.NewSearchClient(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer c.Close()

	req := &discoveryenginepb.SearchRequest{
		// TODO: Fill request struct fields.
		// See https://pkg.go.dev/cloud.google.com/go/discoveryengine/apiv1beta/discoveryenginepb#SearchRequest.
	}
	it := c.Search(ctx, req)

	_, err = it.Next()
	if err != nil {
		log.Fatal(err)
	}

	searchResponse := it.Response.(discoveryenginepb.SearchResponse)
	log.Println("searchResponse.TotalSize", searchResponse.TotalSize)
}
```

**Comment by samiemad** [comment]
> Please note that in order to get the underlying response, you have to call Next on the iterator at least once.

Ah I see.. That is why it was `nil` when I looked in the debugger. Thanks for your help!

**Comment by jagobagascon** [comment]
@quartzmo It feels so weird to me that the [proto](https://github.com/googleapis/googleapis/blob/d1d165ff0067197fc14491d7d9509c9112daa988/google/cloud/discoveryengine/v1/search_service.proto#L43) and the [Golang API](https://github.com/googleapis/google-cloud-go/blob/2ba47cb7adfef32617eb11888331ccc2d2a0f84d/discoveryengine/apiv1beta/search_client.go#L149) differ. Is this a common practice in this library? Also what if there are no search results?

**Comment by quartzmo** [comment]
@jagobagascon,

 Sorry for the late response due to end of year deliverables.

> It feels so weird to me that the [proto](https://github.com/googleapis/googleapis/blob/d1d165ff0067197fc14491d7d9509c9112daa988/google/cloud/discoveryengine/v1/search_service.proto#L43) and the [Golang API](https://github.com/googleapis/google-cloud-go/blob/2ba47cb7adfef32617eb11888331ccc2d2a0f84d/discoveryengine/apiv1beta/search_client.go#L149) differ. Is this a common practice in this library?

The client libraries in this repo were designed to make it easier for users to interact with the backend services. They add a lot of convenience. Auth is once example, but transparently iterating over paged results is another popular feature. It's present in every client.

>  Also what if there are no search results?

If there are no search results, I believe the second return value from the iterator's `Next` method will be `iterator.Done`.  If done is immediately detected, `TotalSize` can be assumed to be zero?

**Comment by jagobagascon** [comment]
There are other values apart from `TotalSize` that may be interesting to read, I need the `CorrectedQuery` for example.

I tried but for some reason the API always returns search results, even when I just send gibberish I receive `I'm sorry, I don't know what you're asking`.

**Comment by quartzmo** [comment]
I'll look into the feasibility of an update to the automatic pagination that would support the following usage, in which `it.Response` is non-nil even in the case of no results. 

(ATTENTION: The following snippet demonstrates a proposed change in behavior and is NOT currently supported.)

```go
it := c.Search(ctx, req)

_, err = it.Next()
if err != nil && err != iterator.Done {
	log.Fatal(err)
}

searchResponse := it.Response.(discoveryenginepb.SearchResponse)
log.Println("searchResponse.TotalSize", searchResponse.TotalSize)
```

**Comment by codyoss** [comment]
Closing in favor of: https://github.com/googleapis/gapic-generator-go/issues/1467.
