### ISSUE TITLE
documentai: fail to unmarshal BatchProcessDocuments json output into documentaipb.Document

### ISSUE THREAD

**Issue by cyber-nic** [googleapis/google-cloud-go#9172]
**Client**
Document AI
cloud.google.com/go/documentai@v1.23.7/apiv1/documentaipb

**Environment**
Verified on local linux + Go Cloud Function triggered by OCR output storage event.

**Go Environment**
$ go version
go version go1.21.4 linux/amd64

lib
cloud.google.com/go/documentai@v1.23.7/apiv1/documentaipb

**Code**

```go
// ...
// get object handle
reader, err := store.Bucket(b).Object(f).NewReader(ctx)
if err != nil {
    return err
}
defer reader.Close()

// read the object into a byte slice
jso, err := io.ReadAll(reader)
if err != nil {
    return err
}

// unmarshal json to doc ai Document
var doc documentaipb.Document
err = json.Unmarshal(jso, &doc)
if err != nil {
    return err
}
```
[sample from](https://github.com/cyber-nic/go-gcp-doc-ai/blob/822125f7a2ed0e51c24ac55f1ab8f38f3812ffc8/apps/nlp-worker/main.go#L72C1-L73C1)

**Expected behavior**
Unmarshals correctly into Document struct.

**Actual behavior**
error `json: cannot unmarshal string into Go struct field Document_Page_Layout.pages.blocks.layout.orientation of type documentaipb.Document_Page_Layout_Orientation"`

[json outputted by DocAI BatchProcessDocuments](https://github.com/googleapis/google-cloud-go/files/13675115/0ocr_test-0.json)

input: https://www.mattmahoney.net/ocr/stock_gs200.jpg

**Comment by quartzmo** [comment]
@cyber-nic,

Thanks for reporting this. It looks to me like the JSON string values for `orientation` (e.g., `"orientation":"PAGE_UP"`) that are exported to Cloud Storage are incompatible with the [`documentaipb#Document_Page_Layout_Orientation`](https://pkg.go.dev/cloud.google.com/go/documentai@v1.23.7/apiv1/documentaipb#Document_Page_Layout_Orientation) enum type in this generated library. I'll have to do some more research to understand how this can be fixed.

**Comment by quartzmo** [comment]
Here's the answer:

Because `documentaipb.Document` is a generated protobuf type, you can't use standard `json` to unmarshall it. Instead, you need to use [google.golang.org/protobuf/encoding/protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson). I tested it as shown below:

```go
package main

import (
	"log"
	"os"

	"cloud.google.com/go/documentai/apiv1/documentaipb"
	"google.golang.org/protobuf/encoding/protojson"
)

func main() {
	// read the object into a byte slice
	jso, err := os.ReadFile("0ocr_test-0.json")
	if err != nil {
		log.Fatal(err)
	}

	// unmarshal json to doc ai Document
	var doc documentaipb.Document
	err = protojson.Unmarshal(jso, &doc)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(doc.Pages[0].Blocks[0].Layout.Orientation)

}
```

```sh
➜  documentaipb-unmarshall-json-9172 go run main.go
2023/12/15 15:05:12 PAGE_UP
```

**Comment by jclasley** [comment]
@quartzmo I had this issue as well, and your solution worked to prevent the error. However, the unmarshal is giving me zero values for every field in the result set. Triggering the unmarshal with a `json.Unmarshal` does populate it.

For example:
```go
// getting it from storage, so it is wrapped in `"document"`
func TestDecode(t *testing.T) {
        b := somehowGetOuput()
  	var raw struct {
		Data json.RawMessage `json:"document"`
	}

	err = json.Unmarshal(b, &raw)
	require.NoError(t, err)
	require.NotNil(t, raw.Data)

	doc := new(documentaipb.Document) // doesn't matter if I do `new` or `var doc documentaipb.Document` and pass a pointer to unmarshal
	err = protojson.Unmarshal(raw.Data, doc)

	var test struct {
		Entities []*documentaipb.Document_Entity `json:"entities"`
	}
	err = json.Unmarshal(raw.Data, &test)
	require.NoError(t, err)

	require.Greater(t, len(test.Entities), 0) // passes
	require.Greater(t, len(doc.Entities), 0)  // fails
}
```

The struct tags for `documentaipb.Document` look like they should work. I'm at a loss

**Comment by quartzmo** [comment]
@jclasley What happens if you use the code I provided above? Fragment here: 

```go
	// read the object into a byte slice
	jso, err := os.ReadFile("0ocr_test-0.json")
	if err != nil {
		log.Fatal(err)
	}

	// unmarshal json to doc ai Document
	var doc documentaipb.Document
	err = protojson.Unmarshal(jso, &doc)
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by jclasley** [comment]
@quartzmo I've resolved it. I was using a Node cloud function to do the DocumentAI job, `JSON.stringify` the results, and then dump those in a storage bucket. I was retrieving from the bucket and trying to decode from there, but the `JSON.stringify` does not respect all protobuf message fields, so the stringified response is different than the expected protobuf message (namely buffer fields are turned into an object of `{"type": [Buffer], "value": [<buffer>]}` which screwed up the `protojson.Unmarshal`.
