### ISSUE TITLE
storage: Add Support for includeFolders option in ListObjects

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/google-cloud-go#9187]
Add Support for manual managed folders feature includeFolders. More details see [internal doc](https://docs.google.com/document/d/1bPZtUAI8inzLQhXCpXEDTqSLURPBb2D3zo5DZ9aAXkE/edit?tab=t.0) Note: This is only the manual addition for includeFolders. No other part is relevant.

**Comment by sydney-munro** [comment]
needed for GA by March 12, 2024

**Comment by tritone** [comment]
Added in #9211. gRPC support will come later.
