### ISSUE TITLE
pubsub/pstest: add support to register other servers into the grpc.Server

### ISSUE THREAD

**Issue by tpokki** [googleapis/google-cloud-go#9198]
**Is your feature request related to a problem? Please describe.**

I'd like to use `GetPolicy()` and `SetPolicy()` in the tests that rely on the `pstest.Server`. For this, I would need to register my `FakeIAMPolicyServer` into the `grpc.Server` instance. Currently the instance is hidden behind unexposed variables.

**Describe the solution you'd like**

I would like to add new method with callback function to initialise the `pstest.Server`:
```go
func NewServerWithFakes(port int, registerFakes func(*grpc.Server), opts ...ServerReactorOption) *Server
```

The existing `NewServer` and `NewServerWithPort` would use internally empty callback for backwards compatiblity.

The server [registration process ](https://github.com/googleapis/google-cloud-go/blob/e60c18d8ac6ea3f242c146e076e13a4d1dda30da/pubsub/pstest/fake.go#L135
) would change like this:
```go
	pb.RegisterPublisherServer(srv.Gsrv, &s.GServer)
	pb.RegisterSubscriberServer(srv.Gsrv, &s.GServer)
	pb.RegisterSchemaServiceServer(srv.Gsrv, &s.GServer)

	// register user provided fake servers, such as IAMPolicyServer
	registerFakes(srv.Gsrv)
	srv.Start()
```

The new method would be used for example like this:

```go
	srv := pstest.NewServerWithFakes(
		0,
		func (gsrv *grpc.Server) {
			// register one or more additional fake server
			iampb.RegisterIAMPolicyServer(gsrv, &FakeIAMPolicyServer{})
		},
	)
```

**Describe alternatives you've considered**
The `srv` in the `pstest.Server` could be exposed. But then we would need new method that creates new server without calling the `srv.Start()`. Registering additional fakes is only possible before the `Gsrv.Serve()` is called.

**Comment by hongalex** [comment]
Sorry this got lost in the triage. I'm amenable to this idea. If you want to send a PR to this, I'd be happy to review this, otherwise I'll get to this when I have cycles.
