### ISSUE TITLE
pubsub: add OC measures for publishing

### ISSUE THREAD

**Issue by jba** [googleapis/google-cloud-go#921]
Add measurements for publish count, time and errors.

See #914.

**Comment by fastest963** [comment]
@jba any updates to this? We're publishing a few thousand messages a second and it's crucial we have some insight into how many publishes are being batched together, the duration of the batched publish, and other metrics that help us tweak our publish config. Thanks!

**Comment by jadekler** [comment]
Hello again @fastest963 :) This work is awaiting review from my colleagues - you're welcome to follow it at https://code-review.googlesource.com/c/gocloud/+/32890.

**Comment by jadekler** [comment]
Whoops didn't mean to hit the Close button.

**Comment by odeke-em** [comment]
I believe @hongalex finished this up with CL https://code-review.googlesource.com/c/gocloud/+/42710
and we now have https://godoc.org/cloud.google.com/go/pubsub#pkg-variables

Measure|View|Purpose
---|---|---
PublishedMessage|PublishedMessagesView|A count aggregation for the number of published messages
PublishLatency|PublishLatencyView|A distribution aggregation for the latencies of various batch upload operations

With that I shall close this issue but please feel free to re-open as you please.
