### ISSUE TITLE
storage: document Object Retention updates

### ISSUE THREAD

**Issue by guestisp** [googleapis/google-cloud-go#9228]
Based on #8929 i'm trying to update (extend) an object retention but i always get a 403 Access denied.

This is what i'm trying to use:
```
        retainUntilDate := clock.Now().Add(opts.RetentionPeriod).UTC()
	objectAttrsToUpdate := storage.ObjectAttrsToUpdate{
		Retention: &storage.ObjectRetention{
			Mode:        "Unlocked",
			RetainUntil: retainUntilDate,
		},
	}

	if _, err := gcs.bucket.Object(objectName).Update(ctx, objectAttrsToUpdate); err != nil {
		return errors.Wrap(err, "unable to extend retention period")
	}
```
looks good to me. The service account used is set as a Storage Administrator so has full r/w acl set

Can someone add and fix some docs and examples ? Object retention is set properly on object creation.
In example, the docs about `OverrideUnlockedRetention` has a wrong example, not showing anything related to the OverrideUnlockedRetention: https://cloud.google.com/go/docs/reference/cloud.google.com/go/storage/latest#cloud_google_com_go_storage_ObjectHandle_OverrideUnlockedRetention

**Comment by tritone** [comment]
I've filed an internal issue with the docs team regarding the incorrect example in the reference docs, thanks for pointing that out. I believe we are going to add client library samples to https://cloud.google.com/storage/docs/using-object-lock ; checking with a teammate on the timeline for that.

In the mean time, https://pkg.go.dev/cloud.google.com/go/storage#ObjectAttrsToUpdate.Retention should describe what you need to do if you want to set the retention policy to unlocked. In your example, you'd want to do the following instead:

```
if _, err := gcs.bucket.Object(objectName).OverrideUnlockedRetention(true).Update(ctx, objectAttrsToUpdate); err != nil {
	return errors.Wrap(err, "unable to extend retention period")
}
```

We can update the package docs to be a bit more specific here as well.

**Comment by tritone** [comment]
I added an example for this in the storage docs. Thanks to an internal bug that was fixed, this should also show up in the cloud.google.com docs you referenced as well after the next release (and the extraneous example was removed).
