### ISSUE TITLE
storage: Add "Name contains" support in Query

### ISSUE THREAD

**Issue by 0x0elliot** [googleapis/google-cloud-go#9237]
**Is your feature request related to a problem? Please describe.**
When a storage bucket might contain a lot of items, It is inefficient to use "prefix" (currently, prefix is only supported by the "query" struct) when querying items. 

Currently `Query` looks like [this](https://pkg.go.dev/cloud.google.com/go/storage#Query)

**Describe the solution you'd like**
```go
// Create a query to list objects in the bucket
query := &storage.Query{
	NameContains: "abc"
}
```

then being able to retrieve it afterwards.

**Describe alternatives you've considered**
No alternate. This is a basic missing feature.

**Additional context**
Right now, I have to iterate through all cloud functions to search once. This is terrible searching!

**Comment by 0x0elliot** [comment]
Let me know if I can help with this. Just point me in the right direction. I need it, so I might as well implement it.

**Comment by tritone** [comment]
You can use [`Query.MatchGlob`](https://pkg.go.dev/cloud.google.com/go/storage#Query.MatchGlob) for this use case. See [here](https://cloud.google.com/storage/docs/json_api/v1/objects/list#list-object-glob) for syntax details. E.g. to find all blobs with names containing `foo`, you would set `MatchGlob` to `**foo**`
