### ISSUE TITLE
internal/trace: opentelemetry-go requires Go 1.20

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-go#9267]
**Client**

Spanner

**Go Environment**

Go1.19

**Actual behavior**

From @harshachinta:

I tried to run a sample application with Go1.19 against Spanner go client library for collecting metrics and got the below error
```
[go.opentelemetry.io/otel/sdk/metric](https://www.google.com/url?q=http://go.opentelemetry.io/otel/sdk/metric&sa=D)
/go/pkg/mod/[go.opentelemetry.io/otel/sdk/metric@v1.21.0/meter.go:472:26](https://www.google.com/url?q=http://go.opentelemetry.io/otel/sdk/metric@v1.21.0/meter.go:472:26&sa=D): undefined: errors.Join
/go/pkg/mod/[go.opentelemetry.io/otel/sdk/metric@v1.21.0/meter.go:516:26](https://www.google.com/url?q=http://go.opentelemetry.io/otel/sdk/metric@v1.21.0/meter.go:516:26&sa=D): undefined: errors.Join
note: module requires Go 1.20
FAIL    [cloud.google.com/go/spanner/test](http://cloud.google.com/go/spanner/test) [build failed]
```

**Additional context**

This is the release that dropped the compatibility for Go 1.19
https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.18.0

google-cloud-go updated to opentelemetry-go v1.21.0 in https://github.com/googleapis/google-cloud-go/pull/9230.

**Comment by codyoss** [comment]
I think we should downgrade the dependency and pin it for the time being.

**Comment by quartzmo** [comment]
Do not merge pending investigation of downgrading and pinning the dependency.
