### ISSUE TITLE
speech: rpc error: code = Canceled desc = The operation was cancelled

### ISSUE THREAD

**Issue by gouyuwang** [googleapis/google-cloud-go#9282]
Using streaming speech recognition with speech-to-text v2, you will get the above message every time you get close to 60 seconds of recognition. Even if I turn off local manual termination, it doesn't work. v1 doesn't have this problem, and the v1 docs have a 5 minute limit, but the v2 docs don't see this 60 second related information!

**Comment by quartzmo** [comment]
Hi @gouyuwang, 

The Speech client is auto-generated and the issue you are referring to is out-of-scope for this repo. Please check the existing [Cloud Speech-to-Text issues](https://issuetracker.google.com/savedsearches/559758) and file an issue there if there is not one already. All cloud issue trackers can be found at https://cloud.google.com/support/docs/issue-trackers.
