### ISSUE TITLE
pubsub: move off of dependency on go.einride.tech/aip

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#9338]
We try to avoid having direct dependencies on third party libraries, especially those with a vanity import, whenever possible, for a variety of reasons. As such, we should endeavor to move away from using `go.einride.tech/aip` in `pubsub/pstest` for the fake's filtering functionality.

Note: This is not a judgement of the mentioned package in any way. This is simply because of an undocumented, unenforced policy we have in this repo based on past experiences with 3p deps. We will be working to document & enforce this policy going forward.

**Comment by noahdietz** [comment]
@hongalex if we can verify that this is a test only dep and it doesn't end up in the client's compile library, then it can stay.

**Comment by hongalex** [comment]
I confirmed this by building 2 binaries, one that uses `cloud.google.com/go/pstest` and the other that doesn't. Running `go version -m <binary>` on both results and diffing them reveals the one that doesn't use the `pstest` package doesn't include the third party dependency.

```
1c1
< binary-wo-pstest: go1.21.9
---
> binary-with-pstest: go1.21.9
13a14
>       dep     github.com/google/go-cmp        v0.6.0  h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
16a18
>       dep     go.einride.tech/aip     v0.67.1 h1:d/4TW92OxXBngkSOwWS2CH5rez869KpKMaN44mdxkFI=
21a24
>       dep     go.opentelemetry.io/otel/sdk    v1.26.0 h1:Y7bumHf5tAiDlRYFmGqetNcLaVUZmh4iYfmGxtmz7F8=
```

**Comment by noahdietz** [comment]
Ok, thanks Alex for taking the time to validate things. We can keep it for the time being, I'll close this.

**Comment by hongalex** [comment]
We should still remove this functionality. Filtering is supported by the Pub/Sub emulator, so we should be directing users to use that for their filtering needs instead of the fake.

**Comment by hongalex** [comment]
Despite my last comment, I have opened the previous PR as a way to support filtering in the pstest package without the external dependency.

**Comment by alethenorio** [comment]
@noahdietz As a maintainer of that library, I was very curious about this specific part of your sentence

> especially those with a vanity import

While we've done vanity imports at Einride for a while, I'd love to get some feedback on how it impacts the community at large to better drive our decisions going forward.

EDIT: I took that to be the same as a library using a vanity URL but maybe that was not the case?
