### ISSUE TITLE
storage: bucketAttrs class in bucket.go does not have Updated field for last modification time for bucket

### ISSUE THREAD

**Issue by raghavyadav01** [googleapis/google-cloud-go#9361]
**Is your feature request related to a problem? Please describe.**
The "bucketAttrs" class in the "bucket.go" file (https://github.com/googleapis/google-cloud-go/blob/9ce3d5b63d2c41119b64e691118303be4ae1b204/storage/bucket.go#L341) lacks an updated field to capture the last modification time for the bucket. I am currently developing a proxy service that redirects requests from "gxs-hadoop-connector" to a proxy for GCS object storage. The GCS-Hadoop-connector requires the Modified time for the bucket, and it encounters issues because the proxy server is unable to provide this modified time, resulting in crashes.

**Describe the solution you'd like**
How can I get last modified time of a bucket  in go client SDK. 

**Describe alternatives you've considered**

**Additional context**

**Comment by raghavyadav01** [comment]
Any Updates on the issue ?

**Comment by noahdietz** [comment]
triaged labels, feel free to change

**Comment by tritone** [comment]
Sorry for the belated response. Exposing this via BucketAttrs would be a feature request. You're welcome to open to a PR for this; otherwise we'll probably get around to it next quarter.

**Comment by raghavyadav01** [comment]
Thank you for fixing the bug.
