### ISSUE TITLE
bigtable: third party dependency exception for rsc.io/binaryregexp

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#9376]
Module: `bigtable`
Usage(s): [`bigtable/bttest/inmem.go`](https://github.com/googleapis/google-cloud-go/blob/2fe67df51fa44b01efa37af97f1284ac4fcd2403/bigtable/bttest/inmem.go#L966-L972)

For the time being, it will be exempt from the third party dep check, but please do one of the following:

A. Remove the dependency by switching to a package own directly by Google, handwriting necessary functionality, or using stdlib
B. Justify the exception and [ack the risks](https://github.com/googleapis/google-cloud-go/blob/main/CONTRIBUTING.md#policy-on-new-dependencies), maintaining the exception indefinitely

**Comment by bhshkh** [comment]
This dependency was added to resolve https://github.com/googleapis/google-cloud-go/issues/1405 
I have tried replacing the dependency with other packages but couldn't find a replacement. 
Please add this as an exception
