### ISSUE TITLE
spanner: third party dependency exception for github.com/stretchr/testify

### ISSUE THREAD

**Issue by noahdietz** [googleapis/google-cloud-go#9378]
Module: `spanner`
Usage(s): [`spanner/integration_test.go`](https://github.com/googleapis/google-cloud-go/blob/2fe67df51fa44b01efa37af97f1284ac4fcd2403/spanner/integration_test.go#L48)

For the time being, it will be exempt from the third party dep check, but please do one of the following:

A. Remove the dependency by switching to a package own directly by Google, handwriting necessary functionality, or using stdlib
B. Justify the exception and [ack the risks](https://github.com/googleapis/google-cloud-go/blob/main/CONTRIBUTING.md#policy-on-new-dependencies), maintaining the exception indefinitely

**Comment by rahul2393** [comment]
Used in tests only.

**Comment by egonelbre** [comment]
I don't have any concerns with testify package personally, but in this case the dependency removal is trivial. i.e. https://github.com/googleapis/google-cloud-go/blob/7bf49049cdc44ca260d1c1354bc7661de9ed8585/spanner/integration_test.go#L2254

```
// replace
require.NoError(t, err)

// with
if err != nil {
    t.Errorf("Apply returns error %v, want nil", err)
}
```

**Comment by noahdietz** [comment]
Awesome, thank you @egonelbre

**Comment by noahdietz** [comment]
Need to remove the exemption now, oops
