### ISSUE TITLE
storage: opencensus.NewTracer deprecated

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-go#9379]
Unfortunately it seems like the opencensus bridge package removed `opencensus.NewTracer` in [v0.44.0](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus@v0.44.0). It was marked deprecated in [the version before](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus@v0.43.0#NewTracer).

This currently makes IDEs complain about this line in the storage benchmarker: https://github.com/googleapis/google-cloud-go/blob/2fe67df51fa44b01efa37af97f1284ac4fcd2403/storage/internal/benchmarks/main.go#L405

**Comment by BrennaEpp** [comment]
Thee offending code lines were removed.
