### ISSUE TITLE
profiler: high memory usage leading to OOM

### ISSUE THREAD

**Issue by xaurx** [googleapis/google-cloud-go#9441]
**Client**

Profiler

**Environment**

GKE containers

**Go Environment**

checked with:
go 1.20.x
go 1.21.x

**Code**

we start profiler in all our processes in a simple way like this:
```
import "cloud.google.com/go/profiler"
...
                err := profiler.Start(profiler.Config{
                        Service:        s.Name,
                        ServiceVersion: s.Version,
                })
```
go.mod cloud.google.com/go/profiler refers to v0.4.0

**Expected behavior**

Normal processing of profiles with sane amount of memory.

**Actual behavior**

Profiler takes >1.5GB RAM and lead to OOMs. We don't even know real max usage as 1.5GB is what profiler was able to profile and catch for itself.

**Screenshots**

<img width="1217" alt="Screenshot 2024-02-20 at 12 05 21" src="https://github.com/googleapis/google-cloud-go/assets/46705673/6b82800d-e52a-4ff7-a57a-e87ca3185279">

**Comment by punya** [comment]
@aalexand do you have any guidance on this?

**Comment by noahdietz** [comment]
triaged labels, feel free to change

**Comment by xaurx** [comment]
@punya will check with NoAllocProfiling=true.
@aalexand unfortunately GCP profiler doesn't show "count" metric (or I have not found it). All it says that top profiles are about ~18GB, i.e. assuming it really collects per 10 secs then we get 1.8GB of allocations per second.
The VM we are running software is 2VCPU, 16GB RAM.

May it start collecting new profile before the previous one has completed uploading to GCP?

**Comment by aalexand** [comment]
> unfortunately GCP profiler doesn't show "count" metric (or I have not found it).

![image](https://github.com/googleapis/google-cloud-go/assets/1519040/067807a2-71b5-4869-927c-43b0cc094d61)

**Comment by xaurx** [comment]
@punya disabling AllocProfiling helped, confirm.
@aalexand "count" metric is about ~40M in top profiles. My guess is that the ones which caused OOM were having even more events.

**Comment by shiqi-synctera** [comment]
@punya Hey, we're seeing this as well with `deltaAllocProfile` taking ~ 200MB out of a total 250MB profile. With a count of 1.66 Million out of a total 2.46 Million. Is this still a bug of some sort? Or is the solution to just always turn off alloc profiling?

**Comment by punya** [comment]
@shiqi-synctera the solution is to turn off allocation profiling.

**Comment by xaurx** [comment]
@punya these are bad defaults if everybody has to disable it.

**Comment by punya** [comment]
@xaurx I agree but I don't want to break someone who's relying on the old behavior (it should really have been opt-in to begin with).

**Comment by shiqi-synctera** [comment]
🤔  huh - meaning it's entirely expected (and intended) that allocated heap profiling will take huge amounts of memory?

**Comment by punya** [comment]
It’s certainly not desired, but we don’t have any capacity or plans to improve it in the foreseeable future.

**Comment by slsyy** [comment]
@punya we have the same issue, but for the heap as well (`NoAllocProfiling: true`). In worst scenario (Top 1%) it takes about 80% of all heap, which leads to OOM

Allocation stack is similar: just `heapProfile` instead of `allocProfile`
