### ISSUE TITLE
Type `SimulateSecurityHealthAnalyticsCustomModuleRequest_SimulatedResource` struct is different then GCP ref docs.

### ISSUE THREAD

**Issue by maisam216** [googleapis/google-cloud-go#9477]
https://github.com/googleapis/google-cloud-go/blob/e7a497e2dca397b9624556283a68d96e852d78cc/securitycenter/apiv1/securitycenterpb/securitycenter_service.pb.go#L4603

Creating fake resource yaml file structure is not correct in the [docs](https://cloud.google.com/security-command-center/docs/custom-modules-sha-test#format_of_the_test_data). where depends on the go type struct it should be like:

```
resourceType: cloudkms.googleapis.com/CryptoKey
resourceData:
  rotationPeriod: '2592001s'
```

**Comment by codyoss** [comment]
If I am understanding you correctly it sounds like that docs page is incorrect. Would you post this feedback on that page in that case? There should be a Send feedback button on the top right of the page context. Closing for now but please let me know if I misunderstood

**Comment by maisam216** [comment]
Thanks for your response, yeah exactly. I will post this feedback on that page.
