### ISSUE TITLE
compute: how to unit test the compute REST client?

### ISSUE THREAD

**Issue by kwould** [googleapis/google-cloud-go#9489]
**Client**

RegionInstanceGroupManagersClient

**Environment**

Local test environment

**Go Environment**
```
go version
go version go1.20.6 darwin/arm64
```

**Code**

```
type fakeRegionInstanceGroupManagerServer struct {
	computepb.UnimplementedRegionInstanceGroupManagersServer
}

func (f *fakeRegionInstanceGroupManagerServer) ListManagedInstances(
	ctx context.Context,
	req *computepb.ListManagedInstancesInstanceGroupManagersRequest,
) *compute.ManagedInstanceIterator {
	return nil
}

func TestManagedInstanceGroup(t *testing.T) {
	ctx := context.Background()
	fakeRegionInstanceGroupManagerServer := &fakeRegionInstanceGroupManagerServer{}
	l, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		t.Fatal(err)
	}
	gsrv := grpc.NewServer()
	computepb.RegisterRegionInstanceGroupManagersServer(gsrv, fakeRegionInstanceGroupManagerServer)
	fakeServerAddr := l.Addr().String()
	go func() {
		if err := gsrv.Serve(l); err != nil {
			panic(err)
		}
	}()


	client, err := compute.NewRegionInstanceGroupManagersRESTClient(ctx,
		option.WithEndpoint(fakeServerAddr),
		option.WithoutAuthentication(),
		option.WithGRPCDialOption(grpc.WithInsecure()),
	)
	if err != nil {
		t.Fatal(err)
	}
	....
}

```

**Expected behavior**

Able to test code with the suggestions in [Testing GRPC services using fakes](https://github.com/googleapis/google-cloud-go/blob/main/testing.md#testing-grpc-services-using-fakes)

**Actual behavior**
Compile time errors with:
```
cannot use fakeRegionInstanceGroupManagerServer (variable of type *fakeRegionInstanceGroupManagerServer) as computepb.RegionInstanceGroupManagersServer value in argument to computepb.RegisterRegionInstanceGroupManagersServer: *fakeRegionInstanceGroupManagerServer does not implement computepb.RegionInstanceGroupManagersServer (wrong type for method ListManagedInstances)
                have ListManagedInstances(context.Context, *computepb.ListManagedInstancesInstanceGroupManagersRequest) *compute.ManagedInstanceIterator
                want ListManagedInstances(context.Context, *computepb.ListManagedInstancesRegionInstanceGroupManagersRequest) (*computepb.RegionInstanceGroupManagersListInstancesResponse, error)
```

**Additional context**
If i'm understanding correctly, it looks like when https://github.com/googleapis/google-cloud-go/commit/36f46494111f6d16d103fb208d49616576dbf91e#diff-841e795c617ea8a5eca82b71d4eafafdaf08b97aef388a1318c082e41dc821f1 got pushed the corresponding changes to the Unimplemented Servers didn't happen. 
Happy to tackle the PR, just following the contribution guidelines for submitting an issue first

**Comment by kwould** [comment]
Not sure i'm on the right track here but it seems like we can't use the fakes provided because they only work for GRPC server/client pairs. Since these are RESTClients it seems like I am stuck going the mock route unless there are other tools in computepb that i'm unaware of.

**Comment by quartzmo** [comment]
Yes, the compute client is REST only, so guidance for gRPC testing won't apply to it. I'm going to update the title of this issue for better SEO, then close it. Please feel free to add comments with any advice/tips you may have for testing the compute client, that would be much appreciated, thank you!
