### ISSUE TITLE
auth: Export `defaultBaseTransport` function 

### ISSUE THREAD

**Issue by xstephen95x** [googleapis/google-cloud-go#9546]
**Is your feature request related to a problem? Please describe.**

We are requesting that the `defaultBaseTransport` function be exported. 

Our usage requires us to wrap the transport being used for audit logging (log all outgoing requests).  But currently, since this function is not exported, there is no way to simply "wrap" the transport. We'd have to provide our own transport.

However, we would prefer to use the default transport used by the SDK, rather than needed set up our own.
The `defaultBaseTransport` function applies some nuanced logic, such as overriding `trans.MaxIdleConnsPerHost` and setting `http2Trans.ReadIdleTimeout = time.Second * 31`. These settings seem like valuable performance improvements.

It is possible we could just copy and paste the code from `defaultBaseTransport` into our own library, but it would be much preferred to just use Google's implementation so that we can easily stay up to date.

**Describe the solution you'd like**

Export `defaultBaseTransport` or its nuanced setup logic.

Alternatively, `NewTransport` could check if `base == nil` can call an unexported `defaultBaseTransport`.

**Describe alternatives you've considered**

Re-implementing `defaultBaseTransport` ourselves. However, we would need to re-read this package every time there is a new release of this package, to make sure we stay up to date. This is cumbersome and risk prone. 

Alternatively, we can do something like:
```go
client, _, _ := ghttp.NewClient(ctx)
defaultTransport := client.Transport
```
to access the defaultTransport, but this also seems brittle.

**Additional context**
Code available here:
See: https://github.com/googleapis/google-cloud-go/blob/511d9b2d7055a2711b3976c319e98d7aec31121f/auth/httptransport/transport.go#L89 

Example:
```go
import (
  "context"
  "fmt"
  "io/ioutil"
  "net/http"
  "testing"

  "cloud.google.com/go/storage"
  "google.golang.org/api/option"
  ghttp "google.golang.org/api/transport/http"
)

type wrapper struct {
  http.RoundTripper
}

func (w *wrapper) RoundTrip(req *http.Request) (*http.Response, error) {
  /* Here, we can inspect any detail of the outgoing request, and perform logging */
  return w.RoundTripper.RoundTrip(req)
}

func TestFoo(t *testing.T) {
  ctx := context.Background()
  // Here, we have to may to use `baseDefaultTransport()`
  rt, _ := ghttp.NewTransport(ctx, http.DefaultTransport)
  w := &wrapper{ RoundTripper: rt}
  hc := &http.Client{ Transport: w }
  client, _ := storage.NewClient(ctx, option.WithHTTPClient(hc))
}
```

**Comment by codyoss** [comment]
Thanks for reaching out. As of right now I don't expect us to externalize this, but may reconsider in the future if there is good reason. It sounds like the root issue here is you wish the had access to to logs about requests made through the client. This is an issue under active investigation and we want to make a better experience here.
