### ISSUE TITLE
storage: Storage Control Quickstart Support

### ISSUE THREAD

**Issue by sydney-munro** [googleapis/google-cloud-go#9661]
1. Please update Library Install Section to include install instructions for storage control, if applicable.
2. Please create sample with region tag storage_control_quickstart_sample that shows an example of initializing a storage control client and performing an call.
3. Please include me on reviews for tracking.

See [internal doc](http://goto.google.com/storage-control-quickstart) for further information.

**Comment by tritone** [comment]
1. I updated the top-level package docs to mention storage control in #9692. There are no separate install instructions for storage control so I think we are good there.
2. Quickstart PR is linked above from the golang-samples repo.
