### ISSUE TITLE
Behavior of  bucketHandle.ListObjects(ctx, storage.Query: {prefix : "someprefix"})

### ISSUE THREAD

**Issue by dneralla** [googleapis/google-cloud-go#969]
How many gcs operations does this correspond to ? Considering ObjectService paginates with page size of 1000 ? Is the number of operations charged for gonna be objects matching that prefix / 1000 ? as there will be that many calls ? or does it in anyway depend on objects not matching the prefix query too ?

**Comment by dneralla** [comment]
Thanks for the info. We are just trying to figure out rise in number of operations we do. This definitely helps. And is there a way to increase the pagesize (ofcourse ,increases memory usage) using client library.

**Comment by jba** [comment]
Yes, but realize that it's just a hint to the service.
```
iter.PageInfo().MaxSize = somethingLarge
```
See https://godoc.org/cloud.google.com/go/storage#ObjectIterator.PageInfo.
