### ISSUE TITLE
Assistant with verify fitness api scopes

### ISSUE THREAD

**Issue by fluttyCat** [googleapis/google-cloud-go#9721]
We developed an app that uses fitness api, right now we have verification errors that wont scopes to be verified. Our users cannot use the google fit right now, and now our app is block.
It says we need to do 2 actions, but i believe we have done those actions before.
1• Update brand information Ensure that your app's name, logo, and OAuth clients meet all requirements

2• Comply with scope requirements
Ensure your selected scopes are as granular as possible and meets our usage requirements
I uploaded the an image of the error we get in the application and what in our console we face.
we really can use some assistance, thank you

![IMG_5795](https://github.com/googleapis/google-cloud-go/assets/48894215/34f5cdb0-a144-41e0-825b-c19b0a57cae9)
![IMG_5787](https://github.com/googleapis/google-cloud-go/assets/48894215/c77e0e5a-9aa1-4c36-ad6c-cb912e0eed2b)

**Comment by codyoss** [comment]
This does not sound like an issue with these Go client libraries, but let me know if I am wrong. I don't think this is the correct channel for the issue you are having.
