### ISSUE TITLE
pubsub: increase default goroutines

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#973]
We are limiting the throughput of this client quite a lot. In steady-state it seems to handle receiving 12,000 messages a minute. We can probably increase this by a factor of 5-10 by tweaking the default number of goroutines to a larger number.

**Comment by jba** [comment]
We initially had a larger default but it overwhelmed some users. Maybe after we've shaken down the implementation more and everyone is used to it, we could raise the defaults.

**Comment by jadekler** [comment]
@jba 👍 sounds good. This is mostly just making an issue to track the AI you had mentioned a week ago before I forgot (I had it on a post-it note and was afraid to lose track).

**Comment by fastest963** [comment]
@jadekler what was the conclusion here? We've been using 10-20x goroutines relative to CPUs. We've been hitting over 320k messages/minute on n2-standard-2 instances. I noticed the default is 1 goroutine. Haven't played around with the 10-20 number in many months, should we be lowering our number?

On that note, we can't seem to pull more than ~3 million messages/minute total for a given subscription. Not sure if there's some other limitation we're hitting but you'll notice:
![image](https://user-images.githubusercontent.com/112555/49631745-29cb6500-f9c1-11e8-839c-569cd1e251a9.png)

In that graph it's showing the rate per host of messages received. On the left we had about 24 servers and by the end we only had 8. As we decreased the number of servers 3x the rate per server went up by 3x (~100k on left to ~300k on right).

**Comment by kamalaboulhosn** [comment]
If I'm understanding correctly, when the number of subscribers dropped from 24 to 8, the number of messages per subscriber increased from 100k/minute to 300k/minute, is that right? So basically, the load was balanced across all subscribers available to get to about 3M messages/sec. This would make me think that either:

1. The subscribers are receiving messages as fast as they are being published.
2. The [streaming pull throughput quota](https://cloud.google.com/pubsub/quotas#quota_limits) of 120,000,000kB per minute is being reached. This would happen if the message size were around 40kB.

**Comment by fastest963** [comment]
@kamalaboulhosn thanks for the quick reply!

1) During this time we had about 300 million messages in the back log and publishing was happening at ~4 million/minute.
2) Our average message size is actually <1kb (~990 bytes) and according to the cloud dashboard we weren't near the quota.

I'm doing more digging today, including sharding the messages across multiple topics and I'll update the thread if I find anything else out.
