### ISSUE TITLE
import package go mod error

### ISSUE THREAD

**Issue by zdjjj** [googleapis/google-cloud-go#9748]
go: downloading go.opentelemetry.io/otel/sdk v1.21.0
go: finding module for package go.opentelemetry.io/otel/exporters/otlp/internal
go: git.woa.com/qqcms/content_center/chatproxy imports
	git.woa.com/galileo/trpc-go-galileo imports
	git.woa.com/galileo/trpc-go-galileo/traces imports
	git.woa.com/galileo/eco/go/sdk/base/exporters/otlp/traces imports
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp imports
	go.opentelemetry.io/otel/exporters/otlp/internal: module go.opentelemetry.io/otel/exporters/otlp@latest found (v0.20.1), but does not contain package go.opentelemetry.io/otel/exporters/otlp/internal

this is my go.mod:
`module git.woa.com/qqcms/content_center/chatproxy  go 1.21  require ( 	git.code.oa.com/dp/venus-demo v0.0.0-20230907143900-b57b73e0c157 	git.code.oa.com/pcg-csd/trpc-ext/trpc-task/tasksdk v1.18.8 	git.code.oa.com/qqcms/common/contentdatabus v0.1.7 	git.code.oa.com/qqcms/common/storge v1.0.0 	git.code.oa.com/server/glib v1.0.10 	git.code.oa.com/trpc-go/trpc-config-rainbow v0.1.34 	git.code.oa.com/trpc-go/trpc-database/kafka v0.2.9 	git.code.oa.com/trpc-go/trpc-database/redis v0.1.9 	git.code.oa.com/trpc-go/trpc-filter/debuglog v0.1.7 	git.code.oa.com/trpc-go/trpc-filter/recovery v0.1.4 	git.code.oa.com/trpc-go/trpc-filter/validation v0.1.3 	git.code.oa.com/trpc-go/trpc-go v0.15.1 	git.code.oa.com/trpc-go/trpc-log-atta v0.1.14 	git.code.oa.com/trpc-go/trpc-naming-polaris v0.5.0 	git.code.oa.com/trpc-go/trpc-opentracing-tjg v0.2.0 	git.code.oa.com/trpcprotocol/cpcdp_mario/common_plugin v1.1.39 	git.code.oa.com/trpcprotocol/galaxies/access v1.1.22 	git.code.oa.com/trpcprotocol/weishi_vu/inferno v1.1.4 	git.woa.com/galileo/trpc-go-galileo v0.8.5 	git.woa.com/mikemintang/webot v1.3.1 	git.woa.com/trpc-go/tnet/extensions/websocket v0.0.3 	git.woa.com/trpc-go/trpc-tnet-transport/websocket v0.1.2 	git.woa.com/trpcprotocol/gen_platform/aigc_gen_platform_aigc v1.1.9 	git.woa.com/trpcprotocol/qqcms/chatgpt_proxy v1.1.66 	github.com/360EntSecGroup-Skylar/excelize v1.4.1 	github.com/DATA-DOG/go-sqlmock v1.5.0 	github.com/Shopify/sarama v1.29.1 	github.com/agiledragon/gomonkey v2.0.2+incompatible 	github.com/go-redis/redis_rate/v10 v10.0.1 	github.com/gobwas/ws v1.2.1 	github.com/golang/mock v1.6.0 	github.com/lithammer/shortuuid/v4 v4.0.0 	github.com/pkoukk/tiktoken-go v0.1.3 	github.com/redis/go-redis/v9 v9.0.4 	github.com/sashabaranov/go-openai v1.9.3 	github.com/smartystreets/goconvey v1.7.2 	github.com/spaolacci/murmur3 v1.1.0 	github.com/stretchr/testify v1.8.4 	github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.830 	github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/nlp v1.0.830 	github.com/tidwall/gjson v1.14.2 	github.com/tidwall/sjson v1.2.5 	gorm.io/driver/mysql v1.3.3 	gorm.io/gorm v1.24.7-0.20230306060331-85eaf9eeda11 )  require golang.org/x/sys v0.12.0 // indirect  require ( 	git.code.oa.com/atta/attaapi-go v1.0.8 // indirect 	git.code.oa.com/atta/attaapi-go/v2 v2.0.1 // indirect 	git.code.oa.com/devsec/protoc-gen-secv v0.3.4 // indirect 	git.code.oa.com/going/l5 v0.2.1 // indirect 	git.code.oa.com/polaris/polaris-go v0.11.2 // indirect 	git.code.oa.com/rainbow/golang-sdk v0.3.36 // indirect 	git.code.oa.com/rainbow/proto v1.58.0 // indirect 	git.code.oa.com/sec-api/go/checkurl v0.1.0 // indirect 	git.code.oa.com/tjg/tjg-opentracing-go v0.7.1 // indirect 	git.code.oa.com/tjg/tjg_go_api v1.9.1 // indirect 	git.code.oa.com/trpc-go/trpc-metrics-runtime v0.3.3 // indirect 	git.code.oa.com/trpc-go/trpc-selector-cl5 v0.2.0 // indirect 	git.code.oa.com/trpc-go/trpc-selector-dsn v0.1.3 // indirect 	git.code.oa.com/trpcprotocol/cpcdp_mario/plugin_manage_svr v1.3.13 // indirect 	git.code.oa.com/trpcprotocol/cpcdp_mario/plugin_protocol_proxy v1.1.20 // indirect 	git.code.oa.com/trpcprotocol/pcg_csd/taskschedule_manage v1.2.76 // indirect 	git.code.oa.com/trpcprotocol/qq_news/content_databus v1.1.78 // indirect 	git.code.oa.com/trpcprotocol/qqcms/common_search_proxy v1.1.20 // indirect 	git.woa.com/galileo/eco/go/sdk/base v0.8.5 // indirect 	git.woa.com/jce/jce v1.2.0 // indirect 	git.woa.com/polaris/polaris-server-api/api/metric v1.0.0 // indirect 	git.woa.com/polaris/polaris-server-api/api/monitor v1.0.7 // indirect 	git.woa.com/polaris/polaris-server-api/api/v1/grpc v1.0.2 // indirect 	git.woa.com/polaris/polaris-server-api/api/v1/model v1.0.9 // indirect 	git.woa.com/ssmsdk/ssm-sdk-golang/ssm v1.1.0 // indirect 	git.woa.com/trpc-go/go_reuseport v1.7.0 // indirect 	git.woa.com/trpc-go/tnet v0.0.9 // indirect 	github.com/BurntSushi/toml v0.3.1 // indirect 	github.com/andybalholm/brotli v1.0.4 // indirect 	github.com/bytedance/sonic v1.8.8 // indirect 	github.com/cenkalti/backoff/v4 v4.2.1 // indirect 	github.com/cespare/xxhash/v2 v2.2.0 // indirect 	github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 // indirect 	github.com/clbanning/mxj v1.8.4 // indirect 	github.com/coreos/go-semver v0.3.0 // indirect 	github.com/coreos/go-systemd/v22 v22.3.2 // indirect 	github.com/davecgh/go-spew v1.1.1 // indirect 	github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f // indirect 	github.com/dlclark/regexp2 v1.8.1 // indirect 	github.com/eapache/go-resiliency v1.2.0 // indirect 	github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21 // indirect 	github.com/eapache/queue v1.1.0 // indirect 	github.com/fsnotify/fsnotify v1.4.9 // indirect 	github.com/ghodss/yaml v1.0.0 // indirect 	github.com/go-logr/logr v1.2.4 // indirect 	github.com/go-logr/stdr v1.2.2 // indirect 	github.com/go-playground/form/v4 v4.2.0 // indirect 	github.com/go-sql-driver/mysql v1.7.0 // indirect 	github.com/gobwas/httphead v0.1.0 // indirect 	github.com/gobwas/pool v0.2.1 // indirect 	github.com/gogo/protobuf v1.3.2 // indirect 	github.com/golang/protobuf v1.5.3 // indirect 	github.com/golang/snappy v0.0.4 // indirect 	github.com/gomodule/redigo v2.0.0+incompatible // indirect 	github.com/google/flatbuffers v2.0.6+incompatible // indirect 	github.com/google/go-querystring v1.0.0 // indirect 	github.com/google/uuid v1.3.0 // indirect 	github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1 // indirect 	github.com/grpc-ecosystem/grpc-gateway/v2 v2.16.0 // indirect 	github.com/hashicorp/errwrap v1.0.0 // indirect 	github.com/hashicorp/go-multierror v1.1.1 // indirect 	github.com/hashicorp/go-uuid v1.0.2 // indirect 	github.com/jcmturner/aescts/v2 v2.0.0 // indirect 	github.com/jcmturner/dnsutils/v2 v2.0.0 // indirect 	github.com/jcmturner/gofork v1.0.0 // indirect 	github.com/jcmturner/gokrb5/v8 v8.4.2 // indirect 	github.com/jcmturner/rpc/v2 v2.0.3 // indirect 	github.com/jinzhu/copier v0.3.5 // indirect 	github.com/jinzhu/inflection v1.0.0 // indirect 	github.com/jinzhu/now v1.1.5 // indirect 	github.com/json-iterator/go v1.1.12 // indirect 	github.com/jtolds/gls v4.20.0+incompatible // indirect 	github.com/jxskiss/base62 v1.1.0 // indirect 	github.com/klauspost/compress v1.15.9 // indirect 	github.com/klauspost/cpuid/v2 v2.0.9 // indirect 	github.com/kr/pretty v0.3.1 // indirect 	github.com/lestrrat-go/strftime v1.0.6 // indirect 	github.com/mitchellh/go-homedir v1.1.0 // indirect 	github.com/mitchellh/mapstructure v1.5.0 // indirect 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect 	github.com/modern-go/reflect2 v1.0.2 // indirect 	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect 	github.com/mozillazg/go-httpheader v0.2.1 // indirect 	github.com/natefinch/lumberjack v2.0.0+incompatible // indirect 	github.com/opentracing/opentracing-go v1.2.0 // indirect 	github.com/panjf2000/ants/v2 v2.4.7 // indirect 	github.com/pierrec/lz4 v2.6.0+incompatible // indirect 	github.com/pkg/errors v0.9.1 // indirect 	github.com/pmezard/go-difflib v1.0.0 // indirect 	github.com/qianbin/directcache v0.9.7 // indirect 	github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475 // indirect 	github.com/remeh/sizedwaitgroup v1.0.0 // indirect 	github.com/robfig/cron v1.2.0 // indirect 	github.com/smartystreets/assertions v1.2.0 // indirect 	github.com/spf13/cast v1.3.1 // indirect 	github.com/stretchr/objx v0.5.0 // indirect 	github.com/tencentyun/cos-go-sdk-v5 v0.7.42 // indirect 	github.com/tidwall/match v1.1.1 // indirect 	github.com/tidwall/pretty v1.2.0 // indirect 	github.com/twitchyliquid64/golang-asm v0.15.1 // indirect 	github.com/valyala/bytebufferpool v1.0.0 // indirect 	github.com/valyala/fasthttp v1.43.0 // indirect 	github.com/xdg-go/pbkdf2 v1.0.0 // indirect 	github.com/xdg-go/scram v1.0.2 // indirect 	github.com/xdg-go/stringprep v1.0.2 // indirect 	go.etcd.io/etcd/api/v3 v3.5.2 // indirect 	go.etcd.io/etcd/client/pkg/v3 v3.5.2 // indirect 	go.etcd.io/etcd/client/v3 v3.5.2 // indirect 	go.opentelemetry.io/otel v1.17.0 // indirect 	go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.14.0 // indirect 	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.17.0 // indirect 	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.17.0 // indirect 	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.14.0 // indirect 	go.opentelemetry.io/otel/metric v1.17.0 // indirect 	go.opentelemetry.io/otel/sdk v1.17.0 // indirect 	go.opentelemetry.io/otel/trace v1.19.0 // indirect 	go.opentelemetry.io/proto/otlp v1.0.0 // indirect 	go.uber.org/atomic v1.9.0 // indirect 	go.uber.org/automaxprocs v1.4.0 // indirect 	go.uber.org/multierr v1.8.0 // indirect 	go.uber.org/zap v1.21.0 // indirect 	golang.org/x/arch v0.0.0-20210923205945-b76863e36670 // indirect 	golang.org/x/crypto v0.11.0 // indirect 	golang.org/x/net v0.12.0 // indirect 	golang.org/x/sync v0.3.0 // indirect 	golang.org/x/text v0.11.0 // indirect 	golang.org/x/time v0.3.0 // indirect 	google.golang.org/genproto v0.0.0-20230711160842-782d3b101e98 // indirect 	google.golang.org/genproto/googleapis/api v0.0.0-20230711160842-782d3b101e98 // indirect 	google.golang.org/genproto/googleapis/rpc v0.0.0-20230711160842-782d3b101e98 // indirect 	google.golang.org/grpc v1.58.2 // indirect 	google.golang.org/protobuf v1.31.0 // indirect 	gopkg.in/natefinch/lumberjack.v2 v2.2.1 // indirect 	gopkg.in/yaml.v2 v2.4.0 // indirect 	gopkg.in/yaml.v3 v3.0.1 // indirect ) 
`

**Comment by codyoss** [comment]
It is not clear to me how this relates to `cloud.google.com/go`. Can you please provide a minimal reporoducer. This looks like a dep resolution issue with otel.
