### ISSUE TITLE
perf: `fmt.Errorf` used instead of `errors.New`

### ISSUE THREAD

**Issue by egonelbre** [googleapis/google-cloud-go#9749]
Throughout the whole codebase there are many places that use `fmt.Errorf` whereas `errors.New` can be used. Using `fmt.Errorf` is roughly 4x slower than `errors.New`.

This can be easily benchmarked with:

```
var result error

func BenchmarkFmtError(b *testing.B) {
	for range b.N {
		result = fmt.Errorf("something")
	}
}

func BenchmarkErrorsNew(b *testing.B) {
	for range b.N {
		result = errors.New("something")
	}
}
```

On my computer I'm getting:

```
BenchmarkFmtError-32             9535638               123.8 ns/op            32 B/op          2 allocs/op
BenchmarkErrorsNew-32           32106765                33.87 ns/op           16 B/op          1 allocs/op
```

This performance issue can be automatically fixed with:

```
gofmt -w -r "fmt.Errorf(s) -> errors.New(s)" .
```

Those error paths usually aren't hot paths, however it might impact the size of code generated.

**Comment by codyoss** [comment]
Thanks for the detailed report. This is a good suggestion. It looks like a good number of these are in our generated code so we can patch our generator to remove a lot of these and gofmt the rest.
