### ISSUE TITLE
storage: list objects in a bucket with custom ordering

### ISSUE THREAD

**Issue by guestisp** [googleapis/google-cloud-go#9766]
Hi all.
I've seen that the default (and only) sorting schema for objects in a bucket is lexicographically by name

Would be great to add a custom sorting schema, like creation date, modified date and so on.

Meanwhile, as i'm not an experienced Go programmer, do you know any sample code that does this ? I need to sort the objects by creation date.

**Comment by tritone** [comment]
Hi @guestisp , as far as I know these features are not supported by the GCS APIs, which the client library wraps. The full list of features for object listing is available here: https://cloud.google.com/storage/docs/json_api/v1/objects/list . I believe we expose all possible options for this API via the Go client.

If you'd like to file a FR with the Cloud Storage team for this kind of API, I'd reach out to your account manager (and they might also be helpful around how you can support your desired workload with the existing feature set of GCS).

**Comment by guestisp** [comment]
can you point me to the Cloud storage repository were to open the issue?

**Comment by tritone** [comment]
@guestisp you can submit and track GCP product feature requests here: https://cloud.google.com/support/docs/issue-trackers . Or reach out to your GCP account contact if you have one.
