### ISSUE TITLE
pubsub topic access hangs

### ISSUE THREAD

**Issue by dt665m** [googleapis/google-cloud-go#992]
## Client

PubSub

## Describe Your Environment

GCE Centos7 
google-cloud-go tag v0.21.0

## Expected Behavior

client.Topic(topicName) gives me access to topic.Exists()

## Actual Behavior

process hangs on client.Topic

I'm having issues getting a pubsub subscription connected from a GCE instance.  Code:
```go
ctx := context.Background()
client, err := pubsub.NewClient(ctx, projectID)
if err != nil {
  panic(err)
}

topic := client.Topic(someTopic)
ok, err := topic.Exists(ctx) //<-- hangs with no error message
```

My hunch is that the service account associated with GCE isn't setup properly, but I got this working with the same exact code on the same instance just a while ago.  I need some guidance on how to begin to debug what is going on here, since no error is given at all, even if I wait for quite a while.  Is my instance having issues trying to connect to the pubsub service?

**Comment by jadekler** [comment]
Glad you got it sorted out! :)

**Comment by kaushiksriram100** [comment]
@dt665m : May I know how was the proxy setting resolved. I have the exact same issue in my production environment which is going through proxy. Works fine from my local laptop. 

the Subscription.Receive() function hangs forever and doesn't honor the context deadline. 

For ex I use: 
`pub, err := pubsub.NewClient(ctx, projectID, option.WithCredentialsFile("file"))
if err != nil {
		fmt.Println(err.Error())
	}
	cctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
	defer cancel()

	sub := pub.Subscription("sub")
	ok, err := sub.Exists(cctx)  // <- hangs here and then after a minute deadline exceeded. 

	if err != nil {
		fmt.Println(err.Error())
		return
	}
	fmt.Println(ok)

`

**Comment by dt665m** [comment]
What we found was that having HTTPS_PROXY or HTTP_PROXY exported in environment variables caused a blanket switch to all global http clients (such as calls made via http.Post or with the http.DefaultClient).  This, in turn, probably changed the GRPC settings in the pubsub client to use the same proxy settings as well, which wasn't what we wanted.  

For our case, the fix was easy.  For parts of our code that needs proxying, we defined our own http client using the proxy, eg.
```
client := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyUrl)}}
```
and leave do not set the HTTPS_PROXY or HTTP_PROXY convenience variables.  Hope this helps.

**Comment by kaushiksriram100** [comment]
Probably I am a bit confused here. 

Do you mean a custom http client to authenticate with pubsub? May be I am not understanding this properly.

I am deploying a simple pubsub consumer service inside a docker container. Creates a pubsub client, assigns a subscription and then consumes. Nowhere in code I have any http client. Am I missing something? 

Thank you very much for responding.

**Comment by dt665m** [comment]
Sorry, without knowing exactly how your network and containers and proxies are setup, I can't really help much.  Basically, if you are exporting HTTP_PROXY, then that does affect the pubsub client's built in GRPC/HTTP clients.  That part was what caused the issue for us.
